export const MODEL_VERSION='L048-manual-audience-evidence-v1';
export const KINDS=['expert','beginner'];
export const bytes=value=>new TextEncoder().encode(value).length;
const clone=value=>JSON.parse(JSON.stringify(value));
function keys(value,expected,label){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length!==expected.length||Object.keys(value).some(k=>!expected.includes(k)))throw Error(`${label}字段无效`);}
function text(value,max,label,required=false){if(typeof value!=='string'||[...value].length>max||(required&&!value.trim())||/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(value)||/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(value))throw Error(`${label}须${required?'非空且':''}≤${max}Unicode码点，无非法控制/代理字符`);}
function rev(value){if(!Number.isInteger(value)||value<1||value>1000000)throw Error('修订须1–1000000整数');}
export function spanQuote(value,start,end){if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||start>=end||end>value.length)throw Error('区间须0起算UTF-16整数半开[start,end)，非空且在当前稿内');const q=value.slice(start,end);text(q,240,'证据片段',true);return q;}
export function selectionRange(raw,value,start,end){if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||start>=end||end>value.length)throw Error('选区须非空且在文本框内');if(raw===value)return[start,end];if(value!==raw.replace(/\r\n|\r/g,'\n'))throw Error('文本框与当前稿不符');const map=[0];for(let i=0;i<raw.length;){i+=raw[i]==='\r'&&raw[i+1]==='\n'?2:1;map.push(i);}return[map[start],map[end]];}
export function exampleDraft(){const expert='缓存存储副本，命中时复用。TTL=60秒。LRU按最近使用排序。',beginner='缓存是临时存储的副本。TTL是副本可用时长，设为60秒。命中时直接复用。LRU选择替换对象。';const anchor=(value,q)=>({start:value.indexOf(q),end:value.indexOf(q)+q.length,quote:q,textRevision:1,itemRevision:1});return{schemaVersion:1,facts:[
{id:'F1',statement:'缓存保存副本',required:true,revision:1,source:{label:'用户练习事实',location:'第一条',quote:'缓存保存副本'},anchors:{expert:anchor(expert,'缓存存储副本'),beginner:anchor(beginner,'缓存是临时存储的副本')},note:''},
{id:'F2',statement:'TTL设为60秒',required:true,revision:1,source:{label:'用户练习事实',location:'第二条',quote:'TTL设为60秒'},anchors:{expert:anchor(expert,'TTL=60秒'),beginner:anchor(beginner,'设为60秒')},note:''},
{id:'F3',statement:'命中时复用副本',required:true,revision:1,source:{label:'用户练习事实',location:'第三条',quote:'命中时复用副本'},anchors:{expert:anchor(expert,'命中时复用'),beginner:null},note:'入门稿虽有对应字样，尚需人工绑定'}],versions:{expert:{label:'专家练习稿',location:'用户自编',text:expert,revision:1,terms:[{id:'E1',name:'LRU',revision:1,explanation:anchor(expert,'按最近使用排序'),note:'人工确认的解释片段'}]},beginner:{label:'入门练习稿',location:'用户自编',text:beginner,revision:1,terms:[{id:'B1',name:'缓存',revision:1,explanation:anchor(beginner,'临时存储的副本'),note:''},{id:'B2',name:'TTL',revision:1,explanation:anchor(beginner,'副本可用时长'),note:''},{id:'B3',name:'LRU',revision:1,explanation:null,note:'出现术语或替换对象字样不自动算解释'}]}}};}
function validateAnchor(a,version,item){if(a===null)return;keys(a,['start','end','quote','textRevision','itemRevision'],'锚');if(!Number.isInteger(a.start)||!Number.isInteger(a.end)||a.start<0||a.start>=a.end||a.end>32000)throw Error('旧证据区间须[0,32000]整数非空');text(a.quote,240,'旧证据',true);rev(a.textRevision);rev(a.itemRevision);if(a.textRevision>version.revision||a.itemRevision>item.revision)throw Error('证据不能来自未来修订');}
export function validateDraft(raw,{forStorage=false}={}){if(bytes(JSON.stringify(raw))>(forStorage?65536:262144))throw Error(forStorage?'完整草稿超过64KiB，不写配置；关闭只能恢复较早合法输入，请导出完整报告':'完整输入超过256KiB，整份拒绝不截断');keys(raw,['schemaVersion','facts','versions'],'草稿');if(raw.schemaVersion!==1)throw Error('只接受schemaVersion=1输入');keys(raw.versions,KINDS,'两版');for(const kind of KINDS){const v=raw.versions[kind];keys(v,['label','location','text','revision','terms'],'稿件');text(v.label,160,'来源名');text(v.location,320,'出处');text(v.text,16000,'稿件');rev(v.revision);if(!Array.isArray(v.terms)||v.terms.length>10)throw Error('每版术语最多10条');const ids=new Set();for(const t of v.terms){keys(t,['id','name','revision','explanation','note'],'术语');if(typeof t.id!=='string'||!(kind==='expert'?/^E(?:[1-9]|10)$/:/^B(?:[1-9]|10)$/).test(t.id)||ids.has(t.id))throw Error('术语ID未知/重复');ids.add(t.id);text(t.name,80,'人工术语',true);text(t.note,320,'术语依据');rev(t.revision);validateAnchor(t.explanation,v,t);}}
if(!Array.isArray(raw.facts)||raw.facts.length>20)throw Error('共同事实最多20条');const ids=new Set();for(const f of raw.facts){keys(f,['id','statement','required','revision','source','anchors','note'],'事实');if(typeof f.id!=='string'||!/^F(?:[1-9]|1\d|20)$/.test(f.id)||ids.has(f.id))throw Error('事实ID未知/重复');ids.add(f.id);text(f.statement,320,'人工事实',true);text(f.note,320,'事实依据');if(typeof f.required!=='boolean')throw Error('必保须明确布尔值');rev(f.revision);keys(f.source,['label','location','quote'],'事实来源');text(f.source.label,160,'事实来源名');text(f.source.location,320,'事实出处');text(f.source.quote,320,'事实来源原句');keys(f.anchors,KINDS,'事实两版绑定');for(const kind of KINDS)validateAnchor(f.anchors[kind],raw.versions[kind],f);}return clone(raw);}
export function anchorState(version,item,a){if(!a)return{current:false,reasons:['unbound'],line:null,column:null};const reasons=[];if(a.textRevision!==version.revision)reasons.push('text-revision-changed');if(a.itemRevision!==item.revision)reasons.push('item-revision-changed');if(a.end>version.text.length)reasons.push('outside-current-text');else{try{if(spanQuote(version.text,a.start,a.end)!==a.quote)reasons.push('quote-mismatch');}catch{reasons.push('invalid-current-span');}}let line=null,column=null;if(!reasons.length){line=1;let begin=0;for(const m of version.text.matchAll(/\r\n|\r|\n/g)){const end=m.index+m[0].length;if(end>a.start)break;line++;begin=end;}column=a.start-begin+1;}return{current:!reasons.length,reasons,line,column};}
function itemOf(draft,kind,type,id){if(!KINDS.includes(kind))throw Error('版本未知');const row=(type==='fact'?draft.facts:type==='term'?draft.versions[kind].terms:[]).find(x=>x.id===id);if(!row)throw Error('事实/术语ID未知');return row;}
export function bindSpan(raw,kind,type,id,start,end){const d=validateDraft(raw),row=itemOf(d,kind,type,id),v=d.versions[kind],a={start,end,quote:spanQuote(v.text,start,end),textRevision:v.revision,itemRevision:row.revision};if(type==='fact')row.anchors[kind]=a;else row.explanation=a;return validateDraft(d);}
export function clearSpan(raw,kind,type,id){const d=validateDraft(raw),row=itemOf(d,kind,type,id);if(type==='fact')row.anchors[kind]=null;else row.explanation=null;return d;}
export function addFact(raw){const d=validateDraft(raw);if(d.facts.length>=20)throw Error('共同事实最多20条');const id=Array.from({length:20},(_,i)=>`F${i+1}`).find(id=>!d.facts.some(x=>x.id===id));d.facts.push({id,statement:'新的人工事实（请编辑）',required:true,revision:1,source:{label:'',location:'',quote:''},anchors:{expert:null,beginner:null},note:''});return d;}
export function addTerm(raw,kind){const d=validateDraft(raw);if(!KINDS.includes(kind))throw Error('版本未知');const v=d.versions[kind];if(v.terms.length>=10)throw Error('每版术语最多10条');const prefix=kind==='expert'?'E':'B',id=Array.from({length:10},(_,i)=>prefix+(i+1)).find(id=>!v.terms.some(x=>x.id===id));v.terms.push({id,name:'新术语（请编辑）',revision:1,explanation:null,note:''});return d;}
function finish(input,versions){const required=input.facts.filter(x=>x.required),facts=input.facts.map(f=>({...f,statuses:Object.fromEntries(KINDS.map(k=>[k,anchorState(input.versions[k],f,f.anchors[k])])),sourceUnknown:['label','location','quote'].filter(key=>!f.source[key].trim())}));const differences=facts.filter(f=>f.statuses.expert.current!==f.statuses.beginner.current).map(f=>({id:f.id,expertBound:f.statuses.expert.current,beginnerBound:f.statuses.beginner.current}));const report={feature:'L048',schemaVersion:1,modelVersion:MODEL_VERSION,input,facts,versions,differences,sourceReviewFactIds:facts.filter(f=>f.sourceUnknown.length).map(f=>f.id),definitions:['两版事实覆盖独立计算，分母均为共同必保事实；当前人工绑定不证明语义一致或来源可靠。','术语清单由用户声明；解释锚未绑定/失效才列该版待核，不自动发现全部术语或判断解释正确。','0必保覆盖率未定义；可选事实与所有术语完整保留，未知来源分别显示。','改对应稿使该稿全部锚失效；改事实说明使两版该事实锚失效；改术语名使该术语解释锚失效，不搜索漂移。','保留当前两稿与旧quote/修订，不保存历次全文或自动核验作者意图。']};for(const k of KINDS){const count=required.filter(f=>anchorState(input.versions[k],f,f.anchors[k]).current).length;report.versions[k].coverage={required:required.length,bound:count,fraction:required.length?`${count}/${required.length}`:null,ratio:required.length?count/required.length:null};report.versions[k].pendingFactIds=facts.filter(f=>!f.statuses[k].current).map(f=>f.id);}reportJson(report);reportMarkdown(report);return report;}
function oneVersion(input,kind){const v=input.versions[kind],terms=v.terms.map(t=>({...t,status:anchorState(v,t,t.explanation)}));return{codePoints:[...v.text].length,terms,pendingTermIds:terms.filter(t=>!t.status.current).map(t=>t.id)};}
export function makeReport(raw){const input=validateDraft(raw);return finish(input,Object.fromEntries(KINDS.map(k=>[k,oneVersion(input,k)])));}
export async function analyze(raw,{canceled=()=>false,yieldControl=()=>new Promise(r=>setTimeout(r,0))}={}){const input=validateDraft(raw),versions={};async function checkpoint(){if(canceled())throw Error('分析已取消，没有部分报告');await yieldControl();if(canceled())throw Error('分析已取消，没有部分报告');}await checkpoint();for(const k of KINDS){versions[k]=oneVersion(input,k);await checkpoint();}await checkpoint();return finish(input,versions);}
export function reportJson(p){const s=JSON.stringify(p,null,2);if(bytes(s)>2097152)throw Error('完整JSON超过2MiB，整份拒绝');return s;}
export function reportMarkdown(p){const raw=reportJson(p).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),fence='`'.repeat(Math.max(3,...[...raw.matchAll(/`+/g)].map(m=>m[0].length+1)));const s=['# L048 受众版本对照',`专家版人工事实绑定${p.versions.expert.coverage.fraction??'未定义'}；入门版${p.versions.beginner.coverage.fraction??'未定义'}。`,`专家版术语待核${p.versions.expert.pendingTermIds.join('/')||'无'}；入门版${p.versions.beginner.pendingTermIds.join('/')||'无'}。`,`${fence}json\n${raw}\n${fence}`].join('\n\n');if(bytes(s)>2097152)throw Error('完整Markdown超过2MiB，整份拒绝');return s;}
