import{h}from'../../core/ui.js';
import{LIMITS,geometry,validateRects,maskPixels,pointerRect,sha,base64,reportText}from'./model.mjs';
let pdfModule;async function pdfjs(){if(!pdfModule)pdfModule=import('../../../../node_modules/pdfjs-dist/build/pdf.min.mjs').then(m=>{m.GlobalWorkerOptions.workerSrc=new URL('../../../../node_modules/pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).href;return m;});return pdfModule;}
export default{id:'T022',create(root,ctx={}){
let alive=true,active=false,busy=false,phase=null,epoch=0,pages=[],source=null,rects=[],nextID=1,result=null,preview=null,loading=null,worker=null,workerReject=null,drag=null;const docs=new Set(),renders=new Set(),temporary=new Set(),buttons=[];
const input=h('input',{type:'file',accept:'.pdf,application/pdf','aria-label':'选择待遮盖PDF'}),selected=h('select',{'aria-label':'遮盖页码'}),canvas=h('canvas',{'aria-label':'框选遮盖区域的页面',tabindex:0,style:{display:'block',maxWidth:'100%',height:'auto',border:'1px solid var(--line,#3a4541)',touchAction:'none'}}),status=h('p',{role:'status'}),list=h('div',{'aria-label':'完整遮盖框清单'}),outputs=h('div',{'aria-label':'完整最终纯图像PDF预览'}),report=h('pre',{'aria-label':'完整遮盖审计报告',style:{whiteSpace:'pre-wrap',maxHeight:'300px',overflow:'auto'}}),confirmed=h('input',{type:'checkbox','aria-label':'已核对全部最终页与未遮盖内容'}),fields={};
const live=()=>alive&&active&&!document.hidden,message=t=>{if(alive)status.textContent=t;},files=()=>window.toolbox?.files||{};
function controls(){input.disabled=selected.disabled=!live()||busy;for(const n of Object.values(fields))n.disabled=!live()||busy||!pages.length;confirmed.disabled=!live()||busy||!result;for(const[b,k]of buttons)b.disabled=!live()||(k==='cancel'?(!busy||phase==='save'):busy)||(k==='add'&&!pages.length)||(k==='build'&&(!pages.length||!rects.length))||(k==='pdf'&&(!result||!confirmed.checked||files().saveBinarySupportsCopyOnly!==true))||(k==='text'&&(!result||files().saveTextSupportsCopyOnly!==true))||(k==='report'&&!result);for(const b of list.querySelectorAll('button'))b.disabled=!live()||busy;}
function button(label,fn,kind){const b=h('button',{type:'button',onclick:fn,style:{margin:'4px'}},label);buttons.push([b,kind]);return b;}
const field=(key,label)=>{const n=h('input',{type:'number',min:0,step:1,value:key==='width'||key==='height'?'20':'0','aria-label':label});fields[key]=n;return h('label',{style:{display:'inline-block',margin:'6px'}},label+' ',n);};
function dispose(d){try{Promise.resolve(d?.destroy?.()).catch(()=>{});}catch{}}
function stop(){worker?.terminate();worker=null;workerReject?.(Error('已取消构建'));workerReject=null;dispose(loading);loading=null;for(const r of renders){try{r.cancel();}catch{}}for(const d of docs)dispose(d);renders.clear();docs.clear();for(const c of temporary)c.width=c.height=1;temporary.clear();}
function clearResult(){result=preview=null;confirmed.checked=false;report.textContent='';for(const c of outputs.querySelectorAll('canvas'))c.width=c.height=1;outputs.replaceChildren();controls();}
function pageIndex(){return Number(selected.value)-1;}
function draw(){const p=pages[pageIndex()];if(!p){canvas.width=canvas.height=1;return;}canvas.width=p.width;canvas.height=p.height;const c=canvas.getContext('2d'),image=p.canvas.getContext('2d').getImageData(0,0,p.width,p.height);c.putImageData(new ImageData(maskPixels(image.data,p.width,p.height,rects.filter(r=>r.page===pageIndex()+1)),p.width,p.height),0,0);}
function showRects(){list.replaceChildren(...rects.map(r=>h('p',{},'R'+r.id+' · 第'+r.page+'页 · x='+r.x+' y='+r.y+' 宽='+r.width+' 高='+r.height,h('button',{type:'button',onclick:()=>{if(live()&&!busy){rects=rects.filter(x=>x.id!==r.id);changed();}}},'删除遮盖框 R'+r.id))));controls();}
function changed(){clearResult();draw();showRects();message('遮盖框改变，旧PDF失效。请重新生成，核对全部页后另存。');}
function add(value){if(!live()||busy||!pages.length)return;try{const r={id:nextID,page:pageIndex()+1,...value};validateRects(pages,[...rects,r]);rects.push(r);nextID++;changed();}catch(e){message('遮盖框拒绝：'+e.message);}}
function addFields(){const r={};for(const[key,n]of Object.entries(fields)){if(!/^(?:0|[1-9]\d*)$/.test(n.value)){message('遮盖坐标和尺寸须十进制整数');return;}r[key]=Number(n.value);}add(r);}
function point(e){const box=canvas.getBoundingClientRect();if(!box.width||!box.height)throw Error('页面显示尺寸无效');return[(e.clientX-box.left)*canvas.width/box.width,(e.clientY-box.top)*canvas.height/box.height];}
canvas.addEventListener('pointerdown',e=>{if(!live()||busy||!pages.length||e.button!==0)return;e.preventDefault();drag={id:e.pointerId,start:point(e)};canvas.setPointerCapture?.(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const saved=drag;drag=null;try{canvas.releasePointerCapture?.(e.pointerId);if(live()&&!busy)add(pointerRect(saved.start,point(e),canvas.width,canvas.height));}catch(error){message('框选拒绝：'+error.message);}});canvas.addEventListener('pointercancel',()=>{drag=null;});selected.addEventListener('change',()=>{if(live()&&!busy){drag=null;draw();}});confirmed.addEventListener('change',controls);
async function renderPDF(bytes,target,token,original){const m=ctx.pdfjs?await ctx.pdfjs():await pdfjs(),task=m.getDocument({data:bytes.slice(),isEvalSupported:false,disableFontFace:true,stopAtErrors:true,standardFontDataUrl:new URL('../../../../node_modules/pdfjs-dist/standard_fonts/',import.meta.url).href,cMapUrl:new URL('../../../../node_modules/pdfjs-dist/cmaps/',import.meta.url).href,cMapPacked:true});loading=task;const doc=await task.promise;loading=null;docs.add(doc);const candidates=[];let total=0;try{if(doc.numPages<1||doc.numPages>8)throw Error('仅1–8页PDF');for(let i=1;i<=doc.numPages;i++){if(!alive||epoch!==token)throw Error('渲染已取消');const p=await doc.getPage(i),view=p.getViewport({scale:2}),width=Math.ceil(view.width),height=Math.ceil(view.height);geometry(width,height);if((total+=width*height)>16777216)throw Error('全部页合计像素超限');const c=h('canvas',{'aria-label':(original?'源':'最终')+'第'+i+'页',style:{maxWidth:'100%',height:'auto',display:'block',margin:'12px 0'}});c.width=width;c.height=height;temporary.add(c);const context=c.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,width,height);const r=p.render({canvasContext:context,viewport:view,background:'#ffffff'});renders.add(r);try{await r.promise;}finally{renders.delete(r);}if(!alive||epoch!==token)throw Error('渲染已取消');candidates.push({width,height,widthPt:view.width/2,heightPt:view.height/2,rotation:p.rotate,cropBox:[...p.view],canvas:c});if(target)target.append(h('p',{},'最终第'+i+'页 · '+width+'×'+height+'像素'),c);p.cleanup();}return candidates;}catch(e){for(const p of candidates){p.canvas.width=p.canvas.height=1;temporary.delete(p.canvas);}throw e;}finally{docs.delete(doc);await doc.destroy();}}
async function read(file){if(!live()||busy||!file)return;const token=++epoch;phase='read';busy=true;clearResult();controls();message('渲染全部来源页到144DPI白底位图，不提取正文。');const timer=setTimeout(()=>{if(alive&&epoch===token){epoch++;stop();message('超过30秒，载入取消；不提供部分来源。');}},30000);let candidate=[];try{if(!Number.isSafeInteger(file.size)||file.size<1||file.size>2097152||typeof file.name!=='string'||!file.name||file.name.length>240||/[\x00-\x1f\x7f]/.test(file.name))throw Error('仅有效文件名、1字节至2MiB PDF');const bytes=new Uint8Array(await file.arrayBuffer());if(!alive||epoch!==token)return;if(bytes.length!==file.size)throw Error('File字节数不符');const identity={name:file.name,bytes:bytes.length,sha256:await sha(bytes)};candidate=await renderPDF(bytes,null,token,true);if(!alive||epoch!==token)return;for(const p of pages)p.canvas.width=p.canvas.height=1;pages=candidate;candidate=[];for(const p of pages)temporary.delete(p.canvas);source={...identity,pageCount:pages.length};rects=[];nextID=1;selected.replaceChildren(...pages.map((_,i)=>h('option',{value:String(i+1)},'第'+(i+1)+'页')));selected.value='1';draw();showRects();message('全部'+pages.length+'页已渲染。逐页框选或填整数像素框；至少一框后生成新纯图像PDF。');}catch(e){if(alive&&epoch===token)message('来源拒绝：'+e.message);}finally{clearTimeout(timer);dispose(loading);loading=null;for(const p of candidate)p.canvas.width=p.canvas.height=1;for(const c of temporary)c.width=c.height=1;temporary.clear();phase=null;busy=false;input.value='';controls();}}
input.addEventListener('change',()=>read(input.files?.[0]));
function buildWorker(data){return new Promise((resolve,reject)=>{const w=ctx.workerFactory?ctx.workerFactory():new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});worker=w;let settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);w.terminate();if(worker===w)worker=null;if(workerReject===cancel)workerReject=null;error?reject(error):resolve(value);},cancel=e=>finish(e),timer=setTimeout(()=>finish(Error('PDF构建超过30秒')),30000);workerReject=cancel;w.onmessage=e=>e.data?.ok===true?finish(null,e.data.result):finish(Error(e.data?.error||'未确认完整构建'));w.onerror=()=>finish(Error('本地构建线程失败'));try{w.postMessage({op:'build',pages:data});}catch(e){finish(e);}});}
async function prepare(){if(!live()||busy||!pages.length||!rects.length)return;const token=epoch;phase='build';busy=true;clearResult();controls();message('重建每页实色遮盖位图，再创建全新纯图像PDF。');const working=[],auditPages=[];try{const plan=validateRects(pages,rects);let total=0;for(let i=0;i<pages.length;i++){if(!alive||epoch!==token)return;const p=pages[i],c=h('canvas');c.width=p.width;c.height=p.height;temporary.add(c);const pixels=p.canvas.getContext('2d').getImageData(0,0,p.width,p.height);c.getContext('2d').putImageData(new ImageData(maskPixels(pixels.data,p.width,p.height,plan.filter(r=>r.page===i+1)),p.width,p.height),0,0);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!alive||epoch!==token)return;if(!blob||blob.type!=='image/png'||(total+=blob.size)>10485760)throw Error('完整遮盖位图超过10MiB或编码失败');const png=new Uint8Array(await blob.arrayBuffer());if(!alive||epoch!==token)return;working.push({width:p.width,height:p.height,widthPt:p.widthPt,heightPt:p.heightPt,png});auditPages.push({page:i+1,width:p.width,height:p.height,widthPt:p.widthPt,heightPt:p.heightPt,sourceRotation:p.rotation,sourceCropBox:p.cropBox,maskedBitmapSHA256:await sha(png)});c.width=c.height=1;temporary.delete(c);}const built=await buildWorker(working);if(!alive||epoch!==token)return;const finalPages=await renderPDF(built.bytes,outputs,token,false);for(const p of finalPages)temporary.delete(p.canvas);if(!alive||epoch!==token)return;const audit={format:'T022-raster-redaction-audit',version:1,source,renderDPI:144,pages:auditPages,rects:plan,output:{name:'redacted-raster.pdf',bytes:built.bytes.length,sha256:built.sha256,pageCount:built.pageCount},scope:'新文档仅重建页面位图；不复制源文字/附件/注释对象/历史/元数据。输出丧失搜索与矢量文本。区域由用户指定，未遮盖视觉内容仍保留；报告含来源文件名和哈希。'};reportText(audit,'json');reportText(audit,'md');result={...built,audit};preview={extension:'json',content:reportText(audit,'json')};report.textContent=preview.content;message('全部最终纯图像页已预览。核对每页遮盖与未遮盖内容，勾选确认后另存PDF。');}catch(e){if(alive&&epoch===token){clearResult();message('生成未完成：'+e.message+'；不能保存部分PDF。');}}finally{for(const c of temporary)c.width=c.height=1;temporary.clear();busy=false;phase=null;controls();}}
async function save(pdf){if(!live()||busy||!result||pdf&&!confirmed.checked)return;const f=files();if(pdf?f.saveBinarySupportsCopyOnly!==true:f.saveTextSupportsCopyOnly!==true)return;const token=epoch;phase='save';busy=true;controls();try{const r=pdf?await f.saveBinary({copyOnly:true,defaultName:'redacted-raster.pdf',extension:'pdf',base64:base64(result.bytes),sha256:result.sha256}):await f.saveText({copyOnly:true,defaultName:'redaction-audit.'+preview.extension,extension:preview.extension,content:preview.content});if(alive&&epoch===token)message(r?.ok===true?'新副本保存成功；原PDF未修改。':r?.canceled?'保存取消，完整预览保留。':'保存失败：'+(r?.error||'未确认成功'));}catch(e){if(alive&&epoch===token)message('保存失败：'+e.message);}finally{busy=false;phase=null;controls();}}
function show(ext){if(live()&&!busy&&result){preview={extension:ext,content:reportText(result.audit,ext)};report.textContent=preview.content;}}
function cancel(){epoch++;stop();clearResult();message('处理取消，旧回调废弃；等待读取或编码结束，未提供部分输出。');}
function leave(){cancel();for(const p of pages)p.canvas.width=p.canvas.height=1;pages=[];source=null;rects=[];drag=null;selected.replaceChildren();list.replaceChildren();canvas.width=canvas.height=1;message('已清除来源位图与结果；返回须重新选择，不自动运行。');controls();}
const visibility=()=>{if(document.hidden)leave();controls();};document.addEventListener('visibilitychange',visibility);
root.append(h('section',{style:{padding:'18px',maxWidth:'1100px',margin:'0 auto',lineHeight:'1.6'}},h('h2',{},'PDF 永久遮盖'),h('p',{},'源≤2MiB、1–8页。每页144DPI，边≤4096/4194304像素，所有页合计≤16777216像素。以原页渲染位图为坐标基准，黑色实心覆盖；新PDF失去文字搜索、矢量与交互。'),input,selected,canvas,h('p',{},'在页上按住鼠标框选，或用以下整数像素坐标添加。坐标原点左上，右下边界不包含。'),field('x','遮盖X'),field('y','遮盖Y'),field('width','遮盖宽度'),field('height','遮盖高度'),button('添加当前页遮盖框',addFields,'add'),list,button('生成并预览全部纯图像PDF页',prepare,'build'),button('取消本次遮盖处理',cancel,'cancel'),status,outputs,h('label',{},confirmed,' 已核对全部最终页与未遮盖内容'),button('另存永久遮盖纯图像PDF新副本',()=>save(true),'pdf'),button('预览完整JSON遮盖审计',()=>show('json'),'report'),button('预览完整Markdown遮盖审计',()=>show('md'),'report'),report,button('另存当前遮盖审计新副本',()=>save(false),'text'),h('p',{},'遮盖只作用于明确划定的区域；其他视觉内容仍可读。来源审计包含文件名和哈希，分享前请检查。重新构建PDF只接收新PNG位图，不传入原PDF对象。容量与期限不等同于解压内存安全沙箱。保存开始后取消按钮禁用，现有目标拒覆盖；所有源字节和大位图不写配置。')));controls();return{activate(){if(alive){active=true;controls();}},deactivate(){if(alive){active=false;leave();}},destroy(){if(!alive)return;active=false;leave();alive=false;document.removeEventListener('visibilitychange',visibility);root.replaceChildren();}};
}};
