const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {pathToFileURL}=require('node:url');
const feature=path.resolve(__dirname,'../src/renderer/features/E026');
const modelPromise=import(pathToFileURL(path.join(feature,'model.mjs')).href);
const cardsPromise=import(pathToFileURL(path.join(feature,'cards.mjs')).href);
const OPTIONS={players:['小明','小红'],filter:'truth',rotation:'sequential',turns:3,seed:'demo'};
async function make(options=OPTIONS,bank){const {Party}=await modelPromise;return new Party(options,bank?{bank}:undefined);}
function resolve(p,action){const v=p.view();return p.resolve(action,v.turn,v.current.id);}
const SMALL=[{id:'X1',kind:'truth',prompt:'你喜欢哪一种水果？'},{id:'X2',kind:'truth',prompt:'你想在周末做什么？'},{id:'X3',kind:'dare',prompt:'用手在空中画一个圆。'}];

test('one hundred original cards have fifty per category, unique IDs and prompts and nonempty readable text',async()=>{const {CARDS}=await cardsPromise;const {validateBank}=await modelPromise;assert.equal(CARDS.length,100);assert.equal(CARDS.filter(c=>c.kind==='truth').length,50);assert.equal(CARDS.filter(c=>c.kind==='dare').length,50);assert.equal(new Set(CARDS.map(c=>c.id)).size,100);assert.equal(new Set(CARDS.map(c=>c.prompt)).size,100);assert.equal(validateBank(CARDS).length,100);assert.ok(CARDS.every(c=>c.prompt.trim()&&!c.prompt.includes('null')));});
test('strict bank validation rejects extra fields, duplicate normalized prompts/IDs, invalid kinds and excessive sizes',async()=>{const {parseBank}=await modelPromise;const raw=cards=>JSON.stringify({version:1,cards});assert.equal(parseBank(raw(SMALL)).length,3);for(const value of ['{',JSON.stringify({version:2,cards:SMALL}),JSON.stringify({version:1,cards:SMALL,extra:true}),raw([]),raw(Array(201).fill(SMALL[0])),raw([SMALL[0],SMALL[0]]),raw([{...SMALL[0],prompt:' '}]),raw([{...SMALL[0],prompt:'x'.repeat(241)}]),raw([{...SMALL[0],id:'bad id'}]),raw([{...SMALL[0],kind:'anything'}]),raw([{...SMALL[0],extra:true}]),raw([{...SMALL[0],prompt:'x\ny'}]),raw([SMALL[0],{...SMALL[0],id:'other',prompt:` ${SMALL[0].prompt} `}]),' '.repeat(65537)])assert.throws(()=>parseBank(value));});
test('options bound player counts/names, normalized uniqueness, category, rotation, turns and reproducible seed',async()=>{const {validateOptions}=await modelPromise;assert.equal(validateOptions(OPTIONS).players.length,2);for(const o of [{...OPTIONS,players:['A']},{...OPTIONS,players:Array(13).fill('A')},{...OPTIONS,players:['A','ａ']},{...OPTIONS,players:['a\nb','c']},{...OPTIONS,filter:null},{...OPTIONS,rotation:'none'},{...OPTIONS,turns:0},{...OPTIONS,turns:101},{...OPTIONS,turns:1.1},{...OPTIONS,seed:'bad seed'}])assert.throws(()=>validateOptions(o));});
test('truth-only never draws a dare, consumes all fifty without repetition and reports natural exhaustion',async()=>{const p=await make({...OPTIONS,turns:100});p.start();const ids=[];while(p.view().phase==='active'){const v=p.view();assert.equal(v.current.kind,'truth');ids.push(v.current.id);resolve(p,'completed');}assert.equal(ids.length,50);assert.equal(new Set(ids).size,50);assert.equal(p.result().endReason,'exhausted');assert.equal(p.result().turns.length,50);});
test('dare-only and mixed filters produce only their permitted cards and a matching limit report',async()=>{const p=await make({...OPTIONS,filter:'dare',turns:4});p.start();for(let i=0;i<4;i++){assert.equal(p.view().current.kind,'dare');resolve(p,'skipped');}assert.equal(p.result().endReason,'turnLimit');const mixed=await make({...OPTIONS,filter:'both',turns:100});mixed.start();while(mixed.view().phase==='active')resolve(mixed,'completed');assert.equal(mixed.result().turns.filter(c=>c.kind==='truth').length,50);assert.equal(mixed.result().turns.filter(c=>c.kind==='dare').length,50);});
test('same options and bank reproduce card/player order; sequential cycle visits the listed players',async()=>{const a=await make();const b=await make();a.start();b.start();const replay=[];for(let i=0;i<3;i++){assert.deepEqual(a.view(),b.view());const v=a.view();replay.push([v.current.id,v.player]);resolve(a,'completed');resolve(b,'completed');}assert.deepEqual(replay,[['T013',0],['T002',1],['T023',0]]);});
test('random player cycles include each person once and prevent identical players across cycle boundaries',async()=>{const p=await make({...OPTIONS,players:['A','B','C'],rotation:'random',turns:12});p.start();const owners=[];while(p.view().phase==='active'){owners.push(p.view().player);resolve(p,'completed');}for(let i=0;i<12;i+=3)assert.equal(new Set(owners.slice(i,i+3)).size,3);for(let i=1;i<owners.length;i++)assert.notEqual(owners[i],owners[i-1]);});
test('skipping is zero penalty without explanation, and completion/skip/removal are separately recorded',async()=>{const p=await make();p.start();resolve(p,'completed');resolve(p,'skipped');resolve(p,'removed');const r=p.result();assert.deepEqual(r.turns.map(t=>t.action),['completed','skipped','removed']);assert.ok(r.turns.every(t=>t.penalty===0));assert.ok(r.summary.every(s=>s.penalty===0));assert.equal(r.summary[0].completed,1);assert.equal(r.summary[1].skipped,1);assert.equal(r.summary[0].removed,1);assert.equal(r.removals[0].id,'T023');});
test('deleted undrawn cards are permanently excluded immediately, recorded, and current deletion uses resolve only',async()=>{const p=await make({...OPTIONS,turns:100});assert.equal(p.removeAvailable('T013'),true);assert.equal(p.removeAvailable('T013'),false);p.start();assert.equal(p.view().current.id,'T002');assert.equal(p.removeAvailable('T002'),false);while(p.view().phase==='active')resolve(p,'completed');assert.equal(p.result().turns.length,49);assert.equal(p.result().turns.some(t=>t.id==='T013'),false);assert.equal(p.result().removals[0].source,'editor');});
test('paused deletion of remaining cards stops repeats and zero eligible cards exhaust safely',async()=>{const p=await make({...OPTIONS,turns:5},SMALL);p.start();const current=p.view().current.id;p.pause();for(const c of SMALL)if(c.id!==current)p.removeAvailable(c.id);assert.equal(resolve(p,'skipped'),false);p.resume();resolve(p,'skipped');assert.equal(p.result().endReason,'exhausted');assert.equal(p.result().turns.length,1);const empty=await make({...OPTIONS,turns:5},SMALL);empty.removeAvailable('X1');empty.removeAvailable('X2');empty.start();assert.equal(empty.result().endReason,'exhausted');assert.equal(empty.result().turns.length,0);});
test('pause preserves the exact card/player, stops actions, and stale round/card tokens cannot consume a subsequent card',async()=>{const p=await make();p.start();const old=p.view();p.pause();assert.equal(p.start(),false);assert.equal(resolve(p,'completed'),false);assert.equal(p.end(),false);p.resume();assert.equal(p.view().current.id,old.current.id);resolve(p,'completed');assert.equal(p.resolve('completed',old.turn,old.current.id),false);assert.equal(p.resolve('bad',2,p.view().current.id),false);assert.equal(p.view().consumed,1);});
test('host ending records unresolved current card without penalty; result is immutable to external report changes',async()=>{const p=await make();assert.equal(p.result(),null);p.start();assert.equal(p.end(),true);const r=p.result();assert.equal(r.turns[0].action,'unresolved');assert.equal(r.summary[0].unresolved,1);assert.equal(r.turns[0].penalty,0);r.turns[0].prompt='changed';assert.notEqual(p.result().turns[0].prompt,'changed');assert.equal(p.end(),false);assert.equal(p.pause(),false);});
test('empty selected category and malformed small history fail clearly and history strips card/large fields',async()=>{await assert.rejects(make(OPTIONS,[SMALL[2]]));const {cleanHistory}=await modelPromise;const row={options:OPTIONS,finishedAt:'2026-10-03',endReason:'turnLimit',completed:1,skipped:1,removed:1,cards:SMALL};const rows=cleanHistory(Array(15).fill(row));assert.equal(rows.length,10);assert.equal(rows[0].cards,undefined);for(const bad of [{...row,completed:4},{...row,skipped:-1},{...row,endReason:null},null])assert.equal(cleanHistory([bad]).length,0);});

class Element {
  constructor(tag,doc){this.nodeType=1;this.tagName=tag.toUpperCase();this.doc=doc;this.children=[];this.attributes={};this.style={};this.dataset={};this.events=new Map();this.value='';this.disabled=false;this._text='';}
  setAttribute(k,v){this.attributes[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;}
  getAttribute(k){return this.attributes[k];}
  append(...items){for(const item of items){item.parentNode=this;this.children.push(item);}}
  replaceChildren(...items){this.children.forEach(x=>{x.parentNode=null;});this.children=[];this._text='';this.append(...items);}
  addEventListener(t,fn){const list=this.events.get(t)||[];list.push(fn);this.events.set(t,list);}
  emit(t,props={}){if(this.disabled&&t==='click')return;const e={target:this,detail:1,preventDefault(){this.defaultPrevented=true;},...props};for(const fn of this.events.get(t)||[])fn(e);}
  click(){this.emit('click');}
  set textContent(v){this.replaceChildren();this._text=String(v);}
  get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}
}
async function mount({activate=true,saved=null,failSave=false,files=null}={}){
  const modules={...await modelPromise,...await cardsPromise};const doc={hidden:false,events:new Map(),createElement(tag){return new Element(tag,this);},createTextNode(v){return {nodeType:3,textContent:String(v)};},addEventListener(t,fn){this.events.set(t,fn);},removeEventListener(t){this.events.delete(t);}};doc.body=doc.createElement('body');const root=doc.createElement('main');doc.body.append(root);const windowEvents=new Map();const win={toolbox:{files},addEventListener(t,fn){windowEvents.set(t,fn);},removeEventListener(t){windowEvents.delete(t);}};const writes=[];const context=vm.createContext({document:doc,window:win,URL,Date,Math,Promise,structuredClone,console,...modules,module:{exports:{}}});
  vm.runInContext(fs.readFileSync(path.resolve(feature,'../../core/ui.js'),'utf8').replace(/export /g,'')+'\nmodule.exports={h};',context);context.h=context.module.exports.h;const source=fs.readFileSync(path.join(feature,'index.js'),'utf8').replace(/^import .*;\r?$/gm,'').replace('export default','module.exports =').replace(/import\.meta\.url/g,JSON.stringify(pathToFileURL(path.join(feature,'index.js')).href));vm.runInContext(source,context);const lifecycle=context.module.exports.create(root,{config:{get(){return saved;},async set(key,value){if(failSave)throw new Error('disk full');writes.push({key,value});}}});
  const all=(node=root)=>[node,...node.children.flatMap(x=>x.nodeType===1?all(x):[])];const button=text=>all().find(e=>e.tagName==='BUTTON'&&e.textContent===text);const field=label=>all().find(e=>e.getAttribute('aria-label')===label);function setup(opts=OPTIONS){field('玩家名称').value=opts.players.join('\n');field('卡片类别').value=opts.filter;field('玩家轮换').value=opts.rotation;field('本局轮数').value=String(opts.turns);field('局号').value=opts.seed;button('建立新局').click();}if(activate){lifecycle.activate();setup();}return {root,doc,lifecycle,windowEvents,all,button,field,writes,setup,text(){return root.textContent;},start(){button('开始抽卡').click();}};
}
function finish(ui){ui.start();ui.button('完成，下一张').click();ui.button('跳过，下一张').click();ui.button('移除此卡，下一张').click();}

test('create inactive and explicit start lead to truth-only playable card without null or undefined text',async()=>{const ui=await mount({activate:false});ui.button('建立新局').click();assert.equal(ui.button('开始抽卡'),undefined);ui.lifecycle.activate();ui.setup();assert.ok(ui.button('开始抽卡'));ui.start();assert.match(ui.text(),/第 1\/3 轮 · 轮到 小明/);assert.match(ui.text(),/T013/);assert.match(ui.text(),/如果只能带一本书去度假/);assert.equal(ui.text().includes('null'),false);assert.equal(ui.text().includes('undefined'),false);ui.lifecycle.destroy();});
test('single-step completion, skip and removal advance players with zero penalty and a full action journal',async()=>{const ui=await mount();finish(ui);assert.match(ui.text(),/达到设定轮数/);assert.match(ui.text(),/第 1 轮 · 小明 · 完成/);assert.match(ui.text(),/第 2 轮 · 小红 · 跳过/);assert.match(ui.text(),/第 3 轮 · 小明 · 移除/);assert.match(ui.text(),/惩罚 0/);ui.button('编辑题库').click();assert.equal(ui.button('删除 T023'),undefined);ui.lifecycle.destroy();});
test('stale and double-click action controls cannot consume multiple cards or end a later card',async()=>{const ui=await mount();const oldStart=ui.button('开始抽卡');ui.start();const oldEnd=ui.button('结束本局');const complete=ui.button('完成，下一张');complete.emit('click',{detail:2});assert.match(ui.text(),/第 1\/3/);complete.click();complete.click();oldEnd.click();assert.match(ui.text(),/第 2\/3/);ui.setup();oldStart.click();assert.ok(ui.button('开始抽卡'));ui.lifecycle.destroy();});
test('deletion before drawing excludes seeded first card immediately and empty category produces a clear error',async()=>{const ui=await mount();ui.button('编辑题库').click();ui.button('删除 T013').click();ui.button('关闭题库编辑').click();ui.button('继续').click();ui.start();assert.match(ui.text(),/T002/);ui.button('结束本局').click();ui.button('编辑题库').click();ui.field('题库 JSON 草稿').value=JSON.stringify({version:1,cards:[SMALL[2]]});ui.button('校验并替换题库').click();ui.button('关闭题库编辑').click();ui.setup();assert.match(ui.text(),/所选类别没有可用卡片/);ui.lifecycle.destroy();});
test('paused current-card delete is disabled in editor and undealt deletion cannot restore consumed/removed cards',async()=>{const ui=await mount();ui.start();ui.button('编辑题库').click();assert.equal(ui.button('删除 T013').disabled,true);ui.button('删除 T002').click();ui.button('关闭题库编辑').click();ui.button('继续').click();ui.button('跳过，下一张').click();assert.match(ui.text(),/T023/);assert.equal(ui.text().includes('T002'),false);ui.button('移除此卡，下一张').click();ui.button('编辑题库').click();ui.button('恢复内置 100 张卡').click();ui.button('关闭题库编辑').click();ui.button('继续').click();ui.button('完成，下一张').click();assert.match(ui.text(),/可用卡片已抽完|达到设定轮数/);ui.lifecycle.destroy();});
test('new cards and whole-bank replacement affect next game only, imported text is safe and editor errors preserve draft',async()=>{const ui=await mount();ui.start();ui.button('编辑题库').click();ui.field('新卡内容').value='<img src=x onerror=boom> 说一句祝福';ui.button('添加卡片').click();assert.ok(ui.button('删除 C001'));ui.field('题库 JSON 草稿').value='{';ui.button('校验并替换题库').click();assert.match(ui.text(),/不是有效 JSON/);assert.equal(ui.field('题库 JSON 草稿').value,'{');const custom=[{id:'SAFE',kind:'truth',prompt:'<script>alert(1)</script> 一道文本题'}];ui.field('题库 JSON 草稿').value=JSON.stringify({version:1,cards:custom});ui.button('校验并替换题库').click();assert.equal(ui.field('题库 JSON 草稿').value,'');assert.equal(ui.all().some(e=>e.tagName==='SCRIPT'||e.tagName==='IMG'),false);ui.button('关闭题库编辑').click();ui.button('继续').click();assert.match(ui.text(),/T013/);ui.setup();ui.start();assert.match(ui.text(),/<script>alert\(1\)<\/script> 一道文本题/);ui.button('跳过，下一张').click();assert.match(ui.text(),/可用卡片已抽完/);ui.lifecycle.destroy();});
test('malformed settings do not abandon the active card and custom duplicates are rejected',async()=>{const ui=await mount();ui.start();ui.field('玩家名称').value='同名\n同名';ui.button('建立新局').click();assert.match(ui.text(),/名称不可重复/);assert.ok(ui.button('跳过，下一张'));ui.field('玩家名称').value='A\nB';ui.field('本局轮数').value='101';ui.button('建立新局').click();assert.match(ui.text(),/1–100/);ui.button('编辑题库').click();ui.field('新卡内容').value='如果只能带一本书去度假，你想带哪本？';ui.button('添加卡片').click();assert.match(ui.text(),/内容不可重复/);ui.lifecycle.destroy();});
test('lifecycle pause and hidden/blur stop stale buttons, preserve current card and clean all listeners on destroy',async()=>{const ui=await mount();ui.start();const old=ui.button('跳过，下一张');ui.lifecycle.deactivate();old.click();ui.lifecycle.activate();assert.ok(ui.button('继续'));ui.button('继续').click();assert.match(ui.text(),/T013/);ui.doc.hidden=true;ui.doc.events.get('visibilitychange')();old.click();ui.doc.hidden=false;ui.doc.events.get('visibilitychange')();assert.ok(ui.button('继续'));ui.button('继续').click();ui.windowEvents.get('blur')();assert.ok(ui.button('继续'));ui.button('继续').click();assert.match(ui.text(),/第 1\/3/);ui.lifecycle.destroy();assert.equal(ui.doc.events.size,0);assert.equal(ui.windowEvents.size,0);assert.equal(ui.root.children.length,0);old.click();assert.equal(ui.root.children.length,0);});
test('draft bounded input and hiding editor keep session paused without rendering stale editor content',async()=>{const ui=await mount();ui.start();ui.button('编辑题库').click();const draft=ui.field('题库 JSON 草稿');draft.value='x'.repeat(70000);draft.emit('input');assert.equal(draft.value.length,65536);ui.windowEvents.get('blur')();const editor=ui.all().find(e=>e.className==='e026-editor');assert.equal(editor.style.display,'none');ui.button('编辑题库').click();ui.button('关闭题库编辑').click();assert.equal(draft.value,'');assert.ok(ui.button('继续'));ui.lifecycle.destroy();});
test('copyOnly full report contains removals/actions, honors canceled save, and bank export reimports successfully',async()=>{const calls=[];const ui=await mount({files:{saveTextSupportsCopyOnly:true,async saveText(arg){calls.push(arg);return {canceled:true};}}});finish(ui);ui.button('导出完整报告 JSON 副本').click();await new Promise(r=>setImmediate(r));assert.equal(calls.length,1);assert.equal(calls[0].copyOnly,true);const report=JSON.parse(calls[0].content);assert.equal(report.turns.length,3);assert.equal(report.removals[0].id,'T023');assert.ok(report.turns.every(t=>t.penalty===0));assert.match(ui.text(),/已取消保存/);ui.button('导出当前题库 JSON 副本').click();await new Promise(r=>setImmediate(r));const {parseBank}=await modelPromise;assert.equal(parseBank(calls[1].content).length,99);assert.equal(calls[1].copyOnly,true);ui.lifecycle.destroy();});
test('resolved unsuccessful native saves show failure for report and bank without losing the session',async()=>{const ui=await mount({files:{saveTextSupportsCopyOnly:true,async saveText(){return {ok:false,error:'EEXIST'};}}});finish(ui);for(const label of ['导出完整报告 JSON 副本','导出当前题库 JSON 副本']){ui.button(label).click();await new Promise(r=>setImmediate(r));assert.match(ui.text(),/保存失败：EEXIST/);assert.equal(ui.text().includes('已保存为新 JSON 副本'),false);}assert.match(ui.text(),/第 2 轮 · 小红 · 跳过/);ui.lifecycle.destroy();});
test('missing copyOnly bridge blocks both exports and history failure leaves report usable',async()=>{let calls=0;const ui=await mount({failSave:true,files:{async saveText(){calls++;}}});finish(ui);await new Promise(r=>setImmediate(r));assert.match(ui.text(),/历史保存失败/);ui.button('导出完整报告 JSON 副本').click();assert.match(ui.text(),/支持副本保护/);ui.button('导出当前题库 JSON 副本').click();assert.equal(calls,0);assert.match(ui.text(),/第 2 轮 · 小红 · 跳过/);ui.lifecycle.destroy();});
test('history version is checked, ten-summary limit is enforced, and no large cards/journal are persisted',async()=>{const saved={version:1,recent:Array(10).fill({options:OPTIONS,finishedAt:'2026-10-03',endReason:'turnLimit',completed:1,skipped:1,removed:1})};const ui=await mount({saved});finish(ui);ui.lifecycle.deactivate();ui.lifecycle.activate();await new Promise(r=>setImmediate(r));assert.equal(ui.writes.length,1);assert.equal(ui.writes[0].value.recent.length,10);const raw=JSON.stringify(ui.writes[0]);assert.equal(raw.includes('T013'),false);assert.equal(raw.includes('prompt'),false);assert.equal(raw.includes('removals'),false);ui.lifecycle.destroy();const future=await mount({saved:{...saved,version:2}});assert.equal(future.text().includes('2026-10-03'),false);future.lifecycle.destroy();});
