const test=require('node:test'),assert=require('node:assert/strict'),model=import('../src/renderer/features/T090/model.mjs');
test('T090: aggregate spare2h does not hide Monday deficit2h; dates and estimates preserved',async()=>{const{example,calculateCapacity}=await model;const input=example(),before=JSON.stringify(input),r=calculateCapacity(input);assert.equal(r.totals.availableMinutes,1200);assert.equal(r.totals.taskMinutes,1080);assert.equal(r.totals.netMinutes,120);assert.deepEqual(r.overloadedDates,['2026-10-05']);assert.equal(r.days[0].deficitMinutes,120);assert.equal(r.totals.dailySpareMinutes,240);assert.equal(r.candidates[0].originalEstimateMinutes,360);assert.equal(r.candidates[0].deficitIfRemovedMinutes,0);assert.equal(JSON.stringify(input),before);});
test('T090: fixed use counted once, fixed-only overflow has no invented candidate',async()=>{const{example,calculateCapacity}=await model;const i=example();i.tasks=[];i.days[0].fixed='300';const r=calculateCapacity(i);assert.equal(r.days[0].deficitMinutes,60);assert.equal(r.totals.fixedMinutes,300);assert.deepEqual(r.candidates,[]);});
test('T090: eligible candidates only overloaded days, independent largest-first trial',async()=>{const{example,calculateCapacity}=await model;const i=example();i.tasks[1].deferrable=true;i.tasks.push({id:'A',title:'小任务',date:i.days[0].date,minutes:'60',deferrable:true});i.tasks.push({id:'X',title:'不可延后',date:i.days[0].date,minutes:'30',deferrable:false});const r=calculateCapacity(i);assert.deepEqual(r.candidates.map(x=>x.id),['T1','A']);assert.equal(r.candidates[1].dayDeficitMinutes,210);assert.equal(r.candidates[1].deficitIfRemovedMinutes,150);});
test('T090: real dates, duplicate dates/IDs and outside dates rejected, not dropped',async()=>{const{example,calculateCapacity,date}=await model;assert.equal(date('2000-02-29'),'2000-02-29');for(const d of ['1900-02-29','2100-02-29','2026-02-30','2026-13-01','1899-01-01','2026-1-01'])assert.throws(()=>date(d));for(const edit of [i=>i.days.push({...i.days[0]}),i=>i.tasks.push({...i.tasks[0]}),i=>i.tasks[0].date='2026-10-20']){const i=example();edit(i);assert.throws(()=>calculateCapacity(i));}});
test('T090: bounded integer minutes, cardinalities and Boolean flag strict',async()=>{const{example,calculateCapacity,minutes}=await model;for(const v of ['-1','1.5','1e2',' 60','014','1441',NaN])assert.throws(()=>minutes(v,'x'));assert.equal(minutes('1440','x'),1440);for(const edit of [i=>i.tasks[0].minutes='0',i=>i.tasks[0].deferrable='false',i=>i.days=[],i=>i.days=Array(32).fill(i.days[0]),i=>i.tasks=Array(201).fill(i.tasks[0])]){const i=example();edit(i);assert.throws(()=>calculateCapacity(i));}});
test('T090: exact fit, zero tasks and unsorted dates stable; no schedule mutation',async()=>{const{example,calculateCapacity}=await model;const i=example();i.tasks[0].minutes='240';i.days.reverse();const r=calculateCapacity(i);assert.equal(r.days[0].date,'2026-10-05');assert.deepEqual(r.overloadedDates,[]);assert.equal(r.days[0].spareMinutes,0);i.tasks=[];assert.equal(calculateCapacity(i).totals.taskMinutes,0);});
test('T090: reports snapshot isolated; import ignores forged result and recomputes, UTF8/version bound',async()=>{const{example,calculateCapacity,restore}=await model;const i=example(),r=calculateCapacity(i);i.tasks[0].minutes='1';assert.equal(r.inputs.tasks[0].minutes,'360');const fake={...r,totals:{netMinutes:99999}};assert.equal(calculateCapacity(restore(JSON.stringify(fake))).totals.netMinutes,120);assert.throws(()=>restore(JSON.stringify({...r,schemaVersion:2})));assert.throws(()=>restore('你'.repeat(21846)),/64KiB/);});
test('T090: Markdown includes exact original dates/minutes and independent-candidate caveat',async()=>{const{example,calculateCapacity,markdown}=await model;const i=example();i.tasks[0].title='a|b`x';const md=markdown(calculateCapacity(i));assert.match(md,/2026-10-05/);assert.match(md,/原估时360分钟/);assert.match(md,/逐项独立/);assert.match(md,/a b'x/);});
