const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');globalThis.crypto||=crypto.webcrypto;const model=import('../src/renderer/features/E009/model.mjs'),clone=v=>JSON.parse(JSON.stringify(v));
// Independent oracle scans EMPTY landing holes using coordinate-pair Sets, never production rules/encoding.
const valid=(x,y)=>x>=0&&x<7&&y>=0&&y<7&&(x>=2&&x<=4||y>=2&&y<=4),xy=i=>[i%7,Math.floor(i/7)],key=(x,y)=>x+','+y;
function oracleMoves(pegs){const occupied=new Set(pegs.map(i=>key(...xy(i)))),moves=[];for(let y=0;y<7;y++)for(let x=0;x<7;x++)if(valid(x,y)&&!occupied.has(key(x,y)))for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const mx=x+dx,my=y+dy,sx=x+2*dx,sy=y+2*dy;if(valid(mx,my)&&valid(sx,sy)&&occupied.has(key(mx,my))&&occupied.has(key(sx,sy)))moves.push([sy*7+sx,y*7+x,my*7+mx]);}return moves;}
function oracleJump(pegs,from,to){const move=oracleMoves(pegs).find(([f,t])=>f===from&&t===to);if(!move)throw Error('independent illegal jump');const next=pegs.filter(i=>i!==from&&i!==move[2]);next.push(to);assert.equal(next.length,pegs.length-1);return next;}
function oracleSolution(l){let pegs=[...l.pegs];for(const[f,t]of l.solution)pegs=oracleJump(pegs,f,t);assert.equal(pegs.length,1,l.id);return pegs;}
if(!process.versions.electron){const test=require('node:test');
test('E009 standard33holes/32pegs and all11 complete solutions independently prove solvable',async()=>{const m=await model;assert.equal(m.HOLES.length,33);assert.equal(m.LEVELS.length,11);assert.equal(m.LEVELS[0].pegs.length,32);assert.ok(!m.LEVELS[0].pegs.includes(24));assert.equal(new Set(m.LEVELS.map(l=>[...l.pegs].sort((a,b)=>a-b).join())).size,11);for(const l of m.LEVELS){assert.equal(new Set(l.pegs).size,l.pegs.length);assert.ok(l.pegs.every(i=>valid(...xy(i))));assert.equal(l.solution.length,l.pegs.length-1);assert.deepEqual(oracleSolution(l),[24]);const g=m.createGame(l.id);for(const[f,t]of l.solution){const before=g.board.flatMap((v,i)=>v===1?[i]:[]);assert.deepEqual(m.legal(g.board).map(v=>[v.from,v.to,v.mid]).sort(),oracleMoves(before).sort());const expected=oracleJump(before,f,t),removed=(f+t)/2,step=m.jump(g,f,t);assert.equal(step.mid,removed);assert.equal(g.board[f],0);assert.equal(g.board[removed],0);assert.equal(g.board[t],1);assert.deepEqual(g.board.flatMap((v,i)=>v===1?[i]:[]).sort((a,b)=>a-b),expected.sort((a,b)=>a-b));}assert.equal(m.stats(g).won,true);assert.equal(g.path.length,l.pegs.length-1);}assert.equal(m.LEVELS[0].solution.length,31);const meta=JSON.parse(fs.readFileSync(path.join(__dirname,'../src/renderer/features/E009/meta.json')));assert.deepEqual(Object.keys(meta).sort(),['category','description','group','id','title']);assert.equal(meta.id,'E009');});
test('E009 strict orthogonal jump rejects occupied/gap/diagonal/offboard/rowwrap unchanged; anyhole singleton wins',async()=>{const m=await model,g=m.createGame(),before=clone(g);for(const pair of[[38,40],[38,22],[38,23],[38,52],[20,22],[0,2],[33,24]]){assert.throws(()=>m.jump(g,...pair));assert.deepEqual(g,before);}m.jump(g,38,24);assert.equal(m.stats(g).remaining,31);assert.equal(m.undo(g),true);assert.deepEqual(g.board,before.board);assert.equal(g.actions,m.token(38,24)+'u--');const singleton=m.createGame();singleton.board=singleton.board.map((v,i)=>v===-1?-1:Number(i===2));assert.equal(m.stats(singleton).won,true);assert.throws(()=>m.jump(singleton,2,16),/胜利/);assert.equal(m.undo(singleton),false);assert.throws(()=>m.legal(Array(49).fill(0)));});
test('E009 independently found deadend failure stillundo, win freezes and firstrecord replays',async()=>{const m=await model;let failure;function search(pegs,trace){if(pegs.length>1&&!oracleMoves(pegs).length)return trace;for(const[f,t]of oracleMoves(pegs)){const r=search(oracleJump(pegs,f,t),[...trace,[f,t]]);if(r)return r;}}for(const l of m.LEVELS.slice(1)){const tr=search(l.pegs,[]);if(tr?.length){failure={l,tr};break;}}assert.ok(failure);const g=m.createGame(failure.l.id);failure.tr.forEach(([f,t])=>m.jump(g,f,t));assert.equal(m.stats(g).failed,true);assert.equal(m.undo(g),true);assert.equal(m.stats(g).failed,false);const win=m.createGame('P01');m.level('P01').solution.forEach(([f,t])=>m.jump(win,f,t));const rec=m.completedRecord(win),v=m.source(win,[rec]);assert.equal(m.validateSource(v).completed.length,1);assert.throws(()=>m.source(win,[]));assert.equal(m.undo(win),false);assert.throws(()=>m.jump(win,24,10));assert.throws(()=>m.source(win,[rec,rec]));});
test('E009 source reconstructs completejumpundo/selected/elapsed; strictversion,duplicatekeys,derived,precision,corruption rejected',async()=>{const m=await model,g=m.createGame();m.jump(g,38,24);m.undo(g);m.jump(g,38,24);g.selected=33;g.elapsed=1234;const v=m.source(g),parsed=m.parse(m.encode(v));assert.deepEqual(parsed.game,g);assert.deepEqual(parsed.completed,[]);for(const bad of[{...v,schema:2},{...v,board:g.board},{...v,current:{...v.current,levelId:'unknown'}},{...v,current:{...v.current,actions:'u--'}},{...v,current:{...v.current,selected:38}},{...v,current:{...v.current,elapsed:-1}},{...v,current:{...v.current,actions:'zz0'}},{...v,completed:[{levelId:'P01',solution:'',elapsed:0}]}])assert.throws(()=>m.validateSource(bad));for(const t of['{"schema":1,"schema":1}',String.raw`{"schema":1,"\u0073chema":1}`,JSON.stringify(v).replace('"schema":1','"schema":1e0'),' '.repeat(65537),'{"schema":9007199254740993}'])assert.throws(()=>m.parse(t));const won=m.createGame('P01');m.level('P01').solution.forEach(([f,t])=>m.jump(won,f,t));assert.throws(()=>m.replay('P01',won.actions+'u--'));});
test('E009 exactly10000actions full replay64KiB paged report no truncation and limit refuses101sthundred',async()=>{const m=await model,g=m.createGame();for(let i=0;i<5000;i++){m.jump(g,38,24);m.undo(g);}assert.equal(m.stats(g).actions,10000);assert.equal(g.actions.length,30000);const text=m.encode(m.source(g));assert.ok(Buffer.byteLength(text)<65536);assert.deepEqual(m.parse(text).game,g);const before=clone(g);assert.throws(()=>m.jump(g,38,24),/10000/);assert.deepEqual(g,before);const r=m.report(g,[]);assert.equal(r.history.length,10000);assert.equal(r.livePath.length,0);assert.match(m.markdown(r),/\|10000\|undo/);assert.throws(()=>m.replay('P00',g.actions+m.token(38,24)));});
test('E009 injected monotonicclock exact120seconds excludes10s pause/day away and freezes7daycap',async()=>{const m=await model;let now=0;const c=new m.Clock(()=>now);c.start();now=120000;assert.equal(c.pause(),120000);now+=10000;assert.equal(c.value(),120000);c.start();now+=30000;assert.equal(c.pause(),150000);now+=86400000;assert.equal(c.value(),150000);c.start();now-=10;assert.equal(c.value(),150000);c.pause();c.restore(m.LIMITS.elapsed-1);c.start();now+=1000;assert.equal(c.pause(),m.LIMITS.elapsed);assert.throws(()=>c.restore(m.LIMITS.elapsed+1));});
class Element{constructor(tag){this.nodeType=1;this.tagName=tag;this.children=[];this.attributes={};this.listeners={};this.style={};this.value='';this.checked=false;this.disabled=false;}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(t,f){(this.listeners[t]||=[]).push(f);}removeEventListener(t,f){this.listeners[t]=(this.listeners[t]||[]).filter(x=>x!==f);}append(...a){this.children.push(...a);}replaceChildren(...a){this.children=[];this.append(...a);}get textContent(){return this.children.map(n=>n.textContent).join('');}set textContent(v){this.replaceChildren({nodeType:3,textContent:String(v)});}focus(){if(!this.disabled){document.activeElement=this;for(const f of this.listeners.focus||[])f();}}async fire(t,e={}){if(this.disabled)return;for(const f of [...(this.listeners[t]||[])])await f({target:this,preventDefault(){},...e});}}
const all=r=>r.children.flatMap(n=>n.nodeType===1?[n,...all(n)]:[]),ctl=(r,t)=>all(r).find(n=>n.attributes['aria-label']===t),btn=(r,t)=>all(r).find(n=>n.tagName==='button'&&n.textContent===t),cell=(r,i)=>all(r).find(n=>n.attributes['data-index']===String(i));async function idle(){for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));}
async function withUI(initial,fn,options={}){const old={document:global.document,window:global.window,requestAnimationFrame:global.requestAnimationFrame,setInterval:global.setInterval,clearInterval:global.clearInterval},events={},calls=[],writes=[],timers=new Map(),canvases=[];let stored=initial,next=0,now=0;global.document={hidden:false,activeElement:null,createElement:t=>{const e=new Element(t);if(t==='canvas'){canvases.push(e);e.getContext=()=>({fillRect(){},strokeRect(){},fillText(){},beginPath(){},arc(){},fill(){},stroke(){}});e.toBlob=cb=>setImmediate(()=>cb(new Blob([Uint8Array.of(137,80,78,71,1)])));}return e;},createTextNode:s=>({nodeType:3,textContent:String(s)}),addEventListener:(k,f)=>(events[k]||=[]).push(f),removeEventListener:(k,f)=>{events[k]=(events[k]||[]).filter(x=>x!==f);}};global.window={toolbox:{files:options.files||{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};},saveBinarySupportsCopyOnly:true,saveBinary:async p=>{calls.push(p);return{ok:true};}}}};global.requestAnimationFrame=()=>assert.fail('noRAF');global.setInterval=f=>{timers.set(++next,f);return next;};global.clearInterval=id=>timers.delete(id);const root=new Element('main'),config=options.config||{get:()=>stored,set:async(_k,v)=>{stored=clone(v);writes.push(stored);}},life=(await import('../src/renderer/features/E009/index.js')).default.create(root,{config,now:()=>now});life.activate();try{await fn(root,life,{events,calls,writes,timers,canvases,stored:()=>stored,advance:n=>{now+=n;for(const f of timers.values())f();},hidden:v=>{document.hidden=v;for(const f of events.visibilitychange||[])f();}});}finally{life.destroy();for(const[k,v]of Object.entries(old))if(v===undefined)delete global[k];else global[k]=v;}}
test('E009 UI mouse firstjump/illegal unchanged, keyboard arrowsSpaceEscape validfocus and activeonly timer',async()=>{await withUI(null,async(r,_l,e)=>{assert.equal(all(r).filter(n=>n.attributes.role==='gridcell').length,33);assert.equal(e.timers.size,0);await cell(r,38).fire('click');assert.equal(e.writes.length,0);await btn(r,'开始 / 继续计时').fire('click');e.advance(120000);cell(r,37).focus();await cell(r,37).fire('keydown',{key:'ArrowRight'});assert.equal(document.activeElement,cell(r,38));await cell(r,38).fire('keydown',{key:' ',repeat:true});assert.equal(e.writes.length,0);await cell(r,38).fire('keydown',{key:' '});await idle();assert.equal(e.stored().current.selected,38);await cell(r,38).fire('keydown',{key:'Escape'});await idle();assert.equal(e.stored().current.selected,null);await cell(r,38).fire('click');await idle();await cell(r,33).fire('click');await idle();await cell(r,24).fire('click');assert.match(ctl(r,'操作状态').textContent,/正交/);assert.equal(e.stored().current.actions,'');await cell(r,38).fire('click');await idle();await cell(r,24).fire('click');await idle();assert.equal(e.stored().current.actions,'120');assert.equal(e.stored().current.elapsed,120000);assert.match(ctl(r,'独粒棋统计').textContent,/剩31枚/);assert.match(cell(r,31).attributes['aria-label'],/空孔/);await btn(r,'暂停计时').fire('click');await idle();assert.equal(e.timers.size,0);e.advance(10000);assert.equal(e.stored().current.elapsed,120000);});});
test('E009 UI lifecycle hidden/deactivate frozen noresume, cleanup and pause after pendingdisk persisted',async()=>{await withUI(null,async(r,life,e)=>{await btn(r,'开始 / 继续计时').fire('click');e.advance(5000);e.hidden(true);await idle();assert.equal(e.timers.size,0);e.advance(86400000);e.hidden(false);assert.match(ctl(r,'独粒棋统计').textContent,/5\.0秒.*暂停/);await btn(r,'开始 / 继续计时').fire('click');e.advance(7000);life.deactivate();await idle();life.activate();assert.equal(e.timers.size,0);assert.equal(e.stored().current.elapsed,12000);const old=cell(r,38);life.destroy();assert.equal(old.listeners.click.length,0);assert.equal(e.events.visibilitychange.length,0);assert.equal(r.children.length,0);assert.equal(e.timers.size,0);});let finish,stored,writes=0;await withUI(null,async(r,life,e)=>{await btn(r,'开始 / 继续计时').fire('click');await cell(r,38).fire('click');assert.equal(ctl(r,'重开关卡选择').disabled,true);e.advance(10000);life.deactivate();life.activate();finish();await idle();assert.equal(writes,2);assert.equal(stored.current.elapsed,10000);assert.equal(e.timers.size,0);},{config:{get:()=>null,set:async(_k,v)=>{stored=clone(v);writes++;if(writes===1)await new Promise(r=>{finish=r;});}}});});
test('E009 UI win onlyonce/frozen firstrecord survives confirmed reset and complete restore; failed undo',async()=>{const m=await model;await withUI(m.source(m.createGame('P01')),async(r,_l,e)=>{await btn(r,'开始 / 继续计时').fire('click');for(const[f,t]of m.level('P01').solution){await cell(r,f).fire('click');await idle();await cell(r,t).fire('click');await idle();}assert.match(ctl(r,'独粒棋统计').textContent,/剩1枚.*胜利.*已完成1\/11/);assert.equal(e.timers.size,0);assert.equal(btn(r,'撤销最近一次跳吃').disabled,true);assert.equal(btn(r,'开始 / 继续计时').disabled,true);await cell(r,24).fire('click');assert.equal(e.stored().completed.length,1);ctl(r,'重开关卡选择').value='P01';await btn(r,'确认开启所选独粒棋关卡').fire('click');assert.equal(e.stored().current.actions.length,6);ctl(r,'确认放弃当前独粒棋重开').checked=true;await btn(r,'确认开启所选独粒棋关卡').fire('click');await idle();assert.equal(e.stored().current.actions,'');await btn(r,'开始 / 继续计时').fire('click');for(const[f,t]of m.level('P01').solution){await cell(r,f).fire('click');await idle();await cell(r,t).fire('click');await idle();}assert.equal(e.stored().completed.length,1);assert.equal(m.validateSource(e.stored()).game.board[24],1);});});
test('E009 UI paged10000 source no truncatedexport, undo paused completeaudit',async()=>{const m=await model,g=m.createGame();m.jump(g,38,24);await withUI(m.source(g),async(r,_l,e)=>{await btn(r,'撤销最近一次跳吃').fire('click');await idle();assert.equal(e.stored().current.actions,'120u--');assert.match(ctl(r,'独粒棋统计').textContent,/剩32枚.*暂停/);});const capped=m.replay('P00','120u--'.repeat(5000));await withUI(m.source(capped),async(r,_l,e)=>{assert.equal(ctl(r,'独粒棋操作预览').children[1].children.length,50);assert.equal(btn(r,'开始 / 继续计时').disabled,true);await btn(r,'另存独粒棋JSON新副本').fire('click');assert.equal(JSON.parse(e.calls[0].content).current.actions.length,30000);await btn(r,'另存完整Markdown记录').fire('click');assert.match(e.calls[1].content,/\|10000\|undo/);});});
test('E009 UI invalidfuture never overwrite, fileconfirm strictUTF8/size, savefailure retry and missingcapability',async()=>{const m=await model;await withUI({schema:2},async(r,_l,e)=>{await btn(r,'从空独粒棋进度开始').fire('click');assert.equal(e.writes.length,0);ctl(r,'确认清空无效独粒棋存档').checked=true;await btn(r,'从空独粒棋进度开始').fire('click');await idle();assert.equal(e.stored().schema,1);});const bytes=Buffer.from(m.encode(m.source(m.createGame('P01'))));await withUI(null,async(r,_l,e)=>{ctl(r,'独粒棋续玩JSON').files=[{size:bytes.length,arrayBuffer:async()=>new Uint8Array(bytes).buffer}];await ctl(r,'独粒棋续玩JSON').fire('change');await idle();await btn(r,'应用独粒棋续玩').fire('click');assert.equal(e.writes.length,0);ctl(r,'确认替换独粒棋全部进度').checked=true;await btn(r,'应用独粒棋续玩').fire('click');await idle();assert.equal(e.stored().current.levelId,'P01');for(const f of[{size:65537,arrayBuffer:()=>assert.fail('oversize read')},{size:1,arrayBuffer:async()=>Uint8Array.of(255).buffer}]){ctl(r,'独粒棋续玩JSON').files=[f];await ctl(r,'独粒棋续玩JSON').fire('change');await idle();assert.equal(btn(r,'应用独粒棋续玩').disabled,true);assert.equal(e.stored().current.levelId,'P01');}});let fail=true;await withUI(null,async r=>{await btn(r,'开始 / 继续计时').fire('click');await cell(r,38).fire('click');await idle();assert.match(ctl(r,'独粒棋保存状态').textContent,/失败.*临时/);fail=false;await btn(r,'重试本地保存').fire('click');assert.match(ctl(r,'独粒棋保存状态').textContent,/已保存/);},{config:{get:()=>null,set:async()=>{if(fail)throw Error('disk');}}});await withUI(null,async r=>{assert.equal(btn(r,'另存完整独粒棋PNG').disabled,true);assert.equal(btn(r,'另存独粒棋JSON新副本').disabled,true);},{files:{}});});
test('E009 UI JSONMDPNGcopyOnly hash release strictok/cancel/failed partial and stale callback ignored',async()=>{await withUI(null,async(r,_l,e)=>{for(const label of['另存独粒棋JSON新副本','另存完整Markdown记录','另存完整独粒棋PNG'])await btn(r,label).fire('click');assert.ok(e.calls.every(p=>p.copyOnly===true));assert.equal(JSON.parse(e.calls[0].content).current.levelId,'P00');assert.equal(e.calls[2].sha256,crypto.createHash('sha256').update(Buffer.from(e.calls[2].base64,'base64')).digest('hex'));assert.ok(e.canvases.every(c=>c.width===0&&c.height===0));});let response;await withUI(null,async r=>{for(response of[{ok:'true'},{canceled:true},{ok:false,error:'exists'},{ok:false,partialPath:'manual'}]){await btn(r,'另存完整独粒棋PNG').fire('click');assert.match(ctl(r,'操作状态').textContent,response.canceled?/已取消/:response.partialPath?/人工核对 manual/:/另存失败/);}},{files:{saveBinarySupportsCopyOnly:true,saveBinary:async()=>response}});let finish;await withUI(null,async(r,life)=>{const pending=btn(r,'另存独粒棋JSON新副本').fire('click');await idle();life.deactivate();await idle();life.activate();finish({ok:true});await pending;assert.ok(!ctl(r,'操作状态').textContent.includes('已另存'));},{files:{saveTextSupportsCopyOnly:true,saveText:()=>new Promise(r=>{finish=r;})}});});
test('E009 UI independent deadend restores asfailed, allowsundo and exports failedstatus; MD includes exact fullsource',async()=>{const m=await model;function dead(pegs,tr=[]){if(pegs.length>1&&!oracleMoves(pegs).length)return tr;for(const[f,t]of oracleMoves(pegs)){const r=dead(oracleJump(pegs,f,t),[...tr,[f,t]]);if(r)return r;}}const l=m.LEVELS.slice(1).find(l=>dead(l.pegs)?.length),tr=dead(l.pegs),g=m.createGame(l.id);tr.forEach(([f,t])=>m.jump(g,f,t));g.elapsed=12345;await withUI(m.source(g),async(r,_l,e)=>{assert.match(ctl(r,'独粒棋统计').textContent,/失败/);assert.equal(btn(r,'开始 / 继续计时').disabled,true);assert.equal(btn(r,'撤销最近一次跳吃').disabled,false);await btn(r,'另存完整Markdown记录').fire('click');assert.match(e.calls[0].content,/无可走且多于1，失败/);const text=e.calls[0].content.match(/```json\n([\s\S]*?)\n```/)[1];assert.deepEqual(JSON.parse(text),m.source(g));await btn(r,'撤销最近一次跳吃').fire('click');await idle();assert.equal(m.stats(m.validateSource(e.stored()).game).failed,false);assert.equal(e.stored().current.elapsed,12345);assert.match(ctl(r,'独粒棋统计').textContent,/暂停/);});});
test('E009 exporting pauses and persists exactdraftelapsed even without a jump; restore never auto starts',async()=>{let value;await withUI(null,async(r,_l,e)=>{await btn(r,'开始 / 继续计时').fire('click');e.advance(4321);await btn(r,'另存独粒棋JSON新副本').fire('click');assert.equal(e.stored().current.elapsed,4321);assert.deepEqual(JSON.parse(e.calls[0].content),e.stored());assert.equal(e.timers.size,0);value=clone(e.stored());});await withUI(value,async(r,_l,e)=>{assert.match(ctl(r,'独粒棋统计').textContent,/4\.3秒.*暂停/);assert.equal(e.timers.size,0);});});
}else nativeCheck().catch(e=>{console.error(e);require('electron').app.exit(1);});

async function nativeCheck(){
 const{app,BrowserWindow,ipcMain,session,nativeImage}=require('electron'),os=require('node:os'),{pathToFileURL}=require('node:url'),rootDir=path.resolve(__dirname,'..'),evidence=fs.mkdtempSync(path.join(os.tmpdir(),'agent-toolbox-E009-native-'));
 app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();const m=await model;await app.whenReady();const{Store}=require('../src/main/store'),store=new Store(app.getPath('userData')),writes=[],texts=[],binaries=[],requests=[],permissions=[];
 ipcMain.handle('config:all',()=>store.all());ipcMain.handle('config:set',(_e,k,v)=>{writes.push(clone(v));return store.set(k,v);});ipcMain.handle('features:list',()=>require('../src/main/feature-catalog').listFeatures(path.join(rootDir,'src/renderer/features')));
 ipcMain.handle('files:saveText',(_e,p)=>{const target=path.join(evidence,p.defaultName),result=require('../src/main/text-export').writeText(target,p.content,p.copyOnly===true);texts.push({target,result});return result;});
 ipcMain.handle('files:saveBinary',(_e,p)=>{const target=path.join(evidence,p.defaultName),result=require('../src/main/feature-binary').writeBinaryCopy(target,p);binaries.push({target,result});return result;});
 session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(d,cb)=>{requests.push(d.url);cb({cancel:true});});session.defaultSession.setPermissionRequestHandler((_wc,p,cb)=>{permissions.push(p);cb(false);});
 const url=p=>pathToFileURL(path.join(rootDir,p)).href,fixture=path.join(evidence,'fixture.html');fs.writeFileSync(fixture,`<html><head><meta charset="UTF-8"><style>body{font:15px sans-serif;margin:0;background:white}button,input,select{margin:5px}</style></head><body><main id="root"></main><script type="module">
 import feature from ${JSON.stringify(url('src/renderer/features/E009/index.js'))};import{Config}from ${JSON.stringify(url('src/renderer/core/config.js'))};window.root=document.getElementById('root');window.config=await Config.load();window.rafRequests=0;window.timerTicks=0;window.liveTimers=new Set();const raf=requestAnimationFrame.bind(window),si=setInterval.bind(window),ci=clearInterval.bind(window);window.requestAnimationFrame=f=>{rafRequests++;return raf(f);};window.setInterval=(f,n)=>{const id=si(()=>{timerTicks++;f();},n);liveTimers.add(id);return id;};window.clearInterval=id=>{liveTimers.delete(id);return ci(id);};
 window.life=feature.create(root,{config});life.activate();window.ctl=t=>root.querySelector('[aria-label="'+t+'"]');window.btn=t=>[...root.querySelectorAll('button')].find(n=>n.textContent===t);window.cell=i=>root.querySelector('[data-index="'+i+'"]');window.wait=async f=>{for(let i=0;i<2000;i++){if(f())return;await new Promise(r=>setTimeout(r,10));}throw Error('native timeout: '+ctl('操作状态').innerText);};window.ready=true;</script></body></html>`,{flag:'wx'});
 const win=new BrowserWindow({show:false,width:1050,height:1400,webPreferences:{preload:path.join(rootDir,'src/main/preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,offscreen:true,backgroundThrottling:false}}),js=s=>win.webContents.executeJavaScript(s);win.webContents.setFrameRate(60);
 async function ready(){await js(`(async()=>{for(let i=0;i<2000;i++){if(window.ready)return;await new Promise(r=>setTimeout(r,10));}throw Error('ready timeout');})()`);}await win.loadFile(fixture);await ready();assert.ok((await js('toolbox.features.list()')).features.some(f=>f.id==='E009'));
 async function pointer(expression){const p=await js(`(()=>{const b=${expression};if(!b||b.disabled)throw Error('disabled '+${JSON.stringify(expression)});b.scrollIntoView({block:'center'});const r=b.getBoundingClientRect();return{x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);win.webContents.sendInputEvent({type:'mouseMove',...p});win.webContents.sendInputEvent({type:'mouseDown',button:'left',modifiers:['leftButtonDown'],clickCount:1,...p});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p});await js('new Promise(r=>setTimeout(r,20))');}
 const click=(label,control=false)=>pointer(`${control?'ctl':'btn'}(${JSON.stringify(label)})`),idle=()=>js(`wait(()=>!ctl('重开关卡选择').disabled)`),key='featureLab.E009.progress';
 async function reload(){const done=new Promise(r=>win.webContents.once('did-finish-load',r));win.reload();await done;await ready();}
 async function jumpByMouse(from,to){await pointer(`cell(${from})`);await idle();await pointer(`cell(${to})`);await idle();}
 async function reset(id){await js(`ctl('重开关卡选择').value=${JSON.stringify(id)}`);await click('确认放弃当前独粒棋重开',true);await click('确认开启所选独粒棋关卡');await idle();assert.equal(store.get(key).current.levelId,id);assert.equal(store.get(key).current.actions,'');await click('开始 / 继续计时');}
 async function png(){await click('另存完整独粒棋PNG');await js(`wait(()=>ctl('操作状态').innerText.includes('已另存完整新副本'))`);const file=binaries.at(-1);assert.equal(file.result.ok,true);const image=nativeImage.createFromPath(file.target),bitmap=image.getBitmap();assert.deepEqual(image.getSize(),{width:820,height:820});const pegs=oracleSolution(m.level(store.get(key).current.levelId));for(let y=0;y<7;y++)for(let x=0;x<7;x++){const i=y*7+x,off=((134+y*80+40)*820+120+x*80+40)*4,expect=!valid(x,y)?[255,253,245]:pegs.includes(i)?[62,110,99]:[191,178,155];assert.deepEqual([bitmap[off+2],bitmap[off+1],bitmap[off]],expect,`independent pixel ${i}`);}assert.equal(file.result.sha256,crypto.createHash('sha256').update(fs.readFileSync(file.target)).digest('hex'));return file.target;}
 const opening=path.join(evidence,'opening-window.png');fs.writeFileSync(opening,(await win.webContents.capturePage()).toPNG(),{flag:'wx'});assert.equal(await js('liveTimers.size'),0);
 await click('开始 / 继续计时');await jumpByMouse(38,24);assert.equal(store.get(key).current.actions,'120');assert.match(await js(`ctl('独粒棋统计').innerText`),/剩31枚/);
 await pointer('cell(33)');await idle();await pointer('cell(38)');assert.match(await js(`ctl('操作状态').innerText`),/正交/);assert.equal(store.get(key).current.actions,'120');
 await click('暂停计时');await idle();const draft=clone(store.get(key));assert.equal(draft.current.selected,33);await js('new Promise(r=>setTimeout(r,400))');assert.equal(await js('liveTimers.size'),0);await reload();assert.deepEqual(store.get(key),draft);assert.match(await js(`ctl('独粒棋统计').innerText`),/暂停/);assert.match(await js(`cell(33).getAttribute('aria-label')`),/已选中/);
 await click('撤销最近一次跳吃');await idle();assert.equal(store.get(key).current.actions,'120u--');assert.match(await js(`ctl('独粒棋统计').innerText`),/剩32枚/);
 await js(`ctl('重开关卡选择').value='P01'`);await click('确认开启所选独粒棋关卡');assert.equal(store.get(key).current.levelId,'P00');await reset('P01');await jumpByMouse(19,17);assert.match(await js(`ctl('独粒棋统计').innerText`),/剩2枚/);
 await js('cell(10).focus()');for(const keyCode of['Space','Down','Down','Space']){win.webContents.sendInputEvent({type:'keyDown',keyCode});win.webContents.sendInputEvent({type:'keyUp',keyCode});await js('new Promise(r=>setTimeout(r,20))');await idle();}
 assert.match(await js(`ctl('独粒棋统计').innerText`),/剩1枚.*胜利.*已完成1\/11/);assert.equal(store.get(key).completed.length,1);assert.equal(await js('liveTimers.size'),0);assert.deepEqual(oracleSolution(m.level('P01')),[24]);const pngs=[await png()];
 await reset('P10');for(const[f,t]of m.level('P10').solution)await jumpByMouse(f,t);assert.match(await js(`ctl('独粒棋统计').innerText`),/剩1枚.*胜利.*已完成2\/11/);pngs.push(await png());
 await reset('P00');let oraclePegs=[...m.level('P00').pegs];for(const[f,t]of m.level('P00').solution){oraclePegs=oracleJump(oraclePegs,f,t);await jumpByMouse(f,t);const actual=m.validateSource(store.get(key)).game.board.flatMap((v,i)=>v===1?[i]:[]);assert.deepEqual(actual.sort((a,b)=>a-b),[...oraclePegs].sort((a,b)=>a-b));}
 const ended=clone(store.get(key));assert.equal(ended.completed.length,3);assert.equal(ended.current.actions.length,93);assert.deepEqual(oraclePegs,[24]);assert.match(await js(`ctl('独粒棋统计').innerText`),/剩1枚.*当前31跳.*勝利|剩1枚.*当前31跳.*胜利/);pngs.push(await png());
 for(const label of['另存独粒棋JSON新副本','另存完整Markdown记录']){await click(label);await js(`wait(()=>ctl('操作状态').innerText.includes('已另存完整新副本'))`);}const json=fs.readFileSync(texts[0].target),jsonSHA=crypto.createHash('sha256').update(json).digest('hex');assert.deepEqual(JSON.parse(json),ended);assert.match(fs.readFileSync(texts[1].target,'utf8'),/\|31\|jump\|B4\|D4\|C4\|1\|/);
 const finalPNG=binaries.at(-1),pngSHA=crypto.createHash('sha256').update(fs.readFileSync(finalPNG.target)).digest('hex');await click('另存完整独粒棋PNG');await js(`wait(()=>ctl('操作状态').innerText.includes('另存失败'))`);assert.equal(binaries.at(-1).result.ok,false);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(finalPNG.target)).digest('hex'),pngSHA);
 await click('另存独粒棋JSON新副本');await js(`wait(()=>ctl('操作状态').innerText.includes('另存失败'))`);assert.equal(texts.at(-1).result.ok,false);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(texts[0].target)).digest('hex'),jsonSHA);
 await reset('P01');await click('暂停计时');await idle();await js(`(()=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(${JSON.stringify([...json])})],'独粒棋续玩.json',{type:'application/json'}));ctl('独粒棋续玩JSON').files=dt.files;ctl('独粒棋续玩JSON').dispatchEvent(new Event('change'));})();wait(()=>ctl('独粒棋导入预览').innerText.includes('已校验 P00'))`);
 await click('应用独粒棋续玩');assert.equal(store.get(key).current.levelId,'P01');await click('确认替换独粒棋全部进度',true);await click('应用独粒棋续玩');await idle();assert.deepEqual(store.get(key),ended);await reload();assert.deepEqual(store.get(key),ended);assert.equal(await js('liveTimers.size'),0);assert.match(await js(`ctl('独粒棋统计').innerText`),/胜利.*已完成3\/11/);
 await reset('P03');await js('new Promise(r=>setTimeout(r,350))');const ticks=await js('timerTicks');assert.ok(ticks>0);await js('life.deactivate();wait(()=>ctl("独粒棋保存状态").innerText.includes("已保存"))');const left=clone(store.get(key)),stoppedTicks=await js('timerTicks');await js('life.activate();new Promise(r=>setTimeout(r,500))');assert.equal(await js('timerTicks'),stoppedTicks);assert.equal(await js('liveTimers.size'),0);assert.deepEqual(store.get(key),left);assert.match(await js(`ctl('独粒棋统计').innerText`),/暂停/);
 await js('life.destroy();new Promise(r=>setTimeout(r,100))');assert.equal(await js('root.childNodes.length'),0);assert.equal(await js('liveTimers.size'),0);assert.equal(await js('timerTicks'),stoppedTicks);assert.equal(await js('rafRequests'),0);assert.deepEqual(requests,[]);assert.deepEqual(permissions,[]);
 console.log(JSON.stringify({evidence,opening,pngs,mouseStandardFirstJump:true,keyboardP01SecondJump:true,unfinishedSelectedReload:true,undoAudit:true,confirmedReset:true,solvedByActualInput:['P01','P10','P00'],standard31OracleCheckedEachStep:true,fullFileAPIRoundtrip:true,completedReload:true,firstCompletions:ended.completed.length,all49PixelCenters:true,pngSHA256:pngSHA,jsonSHA256:jsonSHA,textSaves:texts,binarySaves:binaries,configBytes:fs.statSync(store.file).size,activeTimerTicks:ticks,deactivateTimerTicks:stoppedTicks,returnNoAutoplay:true,rafRequests:0,networkRequests:0,permissions:0,boundary:'Hidden/offscreen production Electron/preload/catalog/Config/Store/text/binary WX, actualmouse+keyboard+FileAPI. Isolated IPC target replaces OSdialog; fullapp/crossOS untested. Injected exact120s clock test separate from native350/500ms lifecycle checks.'}));win.destroy();app.quit();
}
