const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {pathToFileURL}=require('node:url');
const feature=path.resolve(__dirname,'../src/renderer/features/T091');
const modelPromise=import(pathToFileURL(path.join(feature,'model.mjs')).href);
const KEY='DEMO_A1B2C3D4E5F6G7H';const PHONE='13800138000';const SOURCE=`intro\napi_key = "${KEY}"; phone=${PHONE}; harmless-context-text\n`;
function file(content=SOURCE,name='notes.txt',extra={}){const bytes=typeof content==='string'?new TextEncoder().encode(content):new Uint8Array(content);return {name,type:'text/plain',size:bytes.byteLength,webkitRelativePath:'',slice(start,end){return {async arrayBuffer(){return bytes.slice(start,end).buffer;}};},...extra};}
async function scan(files=[file()],ids=['keyAssignment','token','phone'],opts={}){const {Scan}=await modelPromise;const s=new Scan(ids);const report=await s.run(files,{yieldTask:async()=>{},...opts});return {s,report};}
function safe(value){const text=typeof value==='string'?value:JSON.stringify(value);assert.equal(text.includes(KEY),false);assert.equal(text.includes(PHONE),false);assert.equal(text.includes('harmless-context-text'),false);return text;}

test('sample key and mainland phone locate exactly two items with line/column/UTF16 offset and no source context',async()=>{const {report}=await scan();assert.equal(report.summary.findings,2);assert.equal(report.files[0].status,'scanned');const [key,phone]=report.findings;assert.deepEqual([key.line,key.column,key.offset],[2,12,SOURCE.indexOf(KEY)]);assert.equal(phone.offset,SOURCE.indexOf(PHONE));assert.equal(phone.length,11);assert.match(key.maskedValue,/已遮蔽/);safe(report);});
test('overlapping assignment and typical token matches merge into one while disabled phone is not a finding',async()=>{const {detect}=await modelPromise;const text='api_key = "sk-ABCDEFGHIJKLMNOPQRSTUVWX"\nphone=13800138000';const found=detect(text,['keyAssignment','token','phone']);assert.equal(found.matches.length,2);assert.deepEqual(found.matches[0].rules,['keyAssignment','token']);const {report}=await scan([file(text)],['keyAssignment']);assert.equal(report.findings.length,1);safe(report);});
test('fixed rules detect typical Github/AWS markers and reject arbitrary or no regular-expression rule selections',async()=>{const {detect,Scan}=await modelPromise;assert.equal(detect('ghp_'+'A'.repeat(36)+' AKIA'+'B'.repeat(16),['token']).matches.length,2);for(const ids of [[],['custom'],['phone','phone'],null])assert.throws(()=>new Scan(ids));assert.throws(()=>detect('x'.repeat(262145),['phone']));assert.throws(()=>detect('', ['phone'],0));assert.equal(detect('1238001380001',['phone']).matches.length,0);});
test('valid UTF8 BOM and Unicode preserve declared UTF16 positions; invalid UTF8 and UTF16 are never called clean',async()=>{const {report}=await scan([file('\uFEFF😀'+PHONE),file([0xc3,0x28],'bad.txt'),file([0xff,0xfe,0x41,0],'utf16.txt')]);assert.equal(report.findings[0].column,3);assert.equal(report.findings[0].offset,2);assert.equal(report.files[1].status,'unscanned');assert.equal(report.files[1].reason,'unknownEncoding');assert.equal(report.files[2].reason,'unknownEncoding');assert.equal(report.summary.unscanned,2);});
test('binary extensions/MIME, null bytes and low control-byte content are listed unscanned',async()=>{const {report}=await scan([file('ASCII','photo.png'),file('ASCII','binary.bin'),file('ASCII','opaque',{type:'application/octet-stream'}),file([65,0,66],'nul.txt'),file([1,2,3,4,5],'control.txt')]);assert.ok(report.files.every(f=>f.status==='unscanned'&&f.reason==='binary'));assert.equal(report.summary.scanned,0);});
test('file-count and per-file bounds do not silently truncate or read rejected files',async()=>{const {Scan,LIMITS}=await modelPromise;const s=new Scan(['phone']);await assert.rejects(s.run(Array(51).fill(file())));let reads=0;const tooBig=file('x','big.txt',{size:LIMITS.fileBytes+1,slice(){reads++;throw new Error('should not read');}});const {report}=await scan([tooBig]);assert.equal(reads,0);assert.equal(report.files[0].reason,'tooLarge');assert.equal(report.summary.scanned,0);});
test('two-megabyte total limit lists later files unscanned and never reads them',async()=>{const {LIMITS}=await modelPromise;let reads=0;const files=Array.from({length:9},(_,i)=>file('x'.repeat(LIMITS.fileBytes),`f${i}.txt`));files[8].slice=()=>{reads++;throw new Error('no');};const {report}=await scan(files);assert.equal(report.summary.readBytes,LIMITS.totalBytes);assert.equal(report.summary.scanned,8);assert.equal(report.files[8].reason,'totalLimit');assert.equal(reads,0);});
test('five-hundred finding cap marks partial coverage and does not call later files scanned',async()=>{const {report}=await scan([file((PHONE+'\n').repeat(501)),file('hello','later.txt')]);assert.equal(report.findings.length,500);assert.equal(report.files[0].status,'partial');assert.equal(report.files[1].reason,'resultLimit');assert.equal(report.summary.partial,1);safe(report);});
test('read errors, unsupported File APIs and mismatched declared bytes remain explicit unscanned states',async()=>{const errors=[file('', 'secret.txt',{slice(){return {async arrayBuffer(){throw new Error(KEY);}};}}),file('x','old.txt',{slice:undefined}),file('ab','mismatch.txt',{size:1})];const {report}=await scan(errors);assert.deepEqual(report.files.map(f=>f.reason),['readError','unsupported','invalidSize']);assert.equal(report.summary.scanned,0);safe(report);});
test('cancel between files retains prior findings and records canceled files plus reason',async()=>{const {Scan}=await modelPromise;const s=new Scan(['keyAssignment','phone']);const report=await s.run([file(),file(SOURCE,'next.txt')],{yieldTask:async()=>{},onProgress:r=>{if(r.summary.findings===2)s.cancel('user');}});assert.equal(report.state,'canceled');assert.equal(report.cancelReason,'user');assert.equal(report.findings.length,2);assert.equal(report.files[1].status,'canceled');assert.equal(s.cancel(),false);safe(report);});
test('cancel while a read is pending prevents that content from producing findings and counts bytes returned',async()=>{const {Scan}=await modelPromise;let resolve;const gate=new Promise(r=>{resolve=r;});const selected=file(SOURCE,'pending.txt',{slice(){return {arrayBuffer(){return gate;}};}});const s=new Scan(['phone']);const running=s.run([selected],{yieldTask:async()=>{}});await Promise.resolve();s.cancel('deactivated');resolve(new TextEncoder().encode(SOURCE).buffer);const report=await running;assert.equal(report.files[0].status,'canceled');assert.equal(report.findings.length,0);assert.equal(report.summary.readBytes,selected.size);assert.equal(report.cancelReason,'deactivated');safe(report);});
test('names and relative paths containing source values/tokens/phones are masked in JSON and Markdown',async()=>{const {toMarkdown}=await modelPromise;const {report}=await scan([file(SOURCE,KEY+'.txt',{webkitRelativePath:`分享/${PHONE}/${KEY}.txt`})]);assert.ok(report.files[0].path.includes('[已遮蔽]'));assert.equal(report.findings[0].path,report.files[0].path);safe(report);safe(toMarkdown(report));});
test('disabled key rule still cannot leak a short compound API value through paths or review reasons',async()=>{const compound='ab/c.def';const {s,report}=await scan([file(`api_key=${compound}\n${PHONE}`, 'c.def.txt',{webkitRelativePath:compound+'.txt'})],['phone']);assert.equal(report.findings.length,1);assert.equal(JSON.stringify(report).includes(compound),false);s.annotate('R001','falsePositive',`样例 ${compound}`);assert.equal(JSON.stringify(s.report()).includes(compound),false);});
test('manual false-positive marking requires reason, retains all findings, scrubs values and cannot alter returned report internals',async()=>{const {s}=await scan();assert.throws(()=>s.annotate('R001','falsePositive',''));assert.throws(()=>s.annotate('R001','falsePositive','x'.repeat(181)));assert.throws(()=>s.annotate('R001','wrong','x'));const r=s.annotate('R001','falsePositive',`测试占位符 ${KEY}，样例手机号 ${PHONE}`);assert.equal(r.findings[0].status,'falsePositive');assert.equal(r.findings.length,2);assert.match(r.findings[0].reason,/测试占位符/);safe(r);r.findings[0].status='mutated';assert.equal(s.report().findings[0].status,'falsePositive');s.annotate('R001','unreviewed');assert.equal(s.report().findings[0].status,'unreviewed');});
test('masked Markdown escapes annotation markup, links findings by file ID and does not claim safety',async()=>{const {toMarkdown}=await modelPromise;const {s}=await scan();s.annotate('R001','falsePositive','样例 | <注释> [标签]');const md=toMarkdown(s.report());assert.ok(md.includes('\\|'));assert.ok(md.includes('\\<'));assert.match(md,/R001 \| F001/);assert.match(md,/不证明/);assert.throws(()=>toMarkdown({feature:'wrong'}));safe(md);});

class Element{
  constructor(tag,doc){this.nodeType=1;this.tagName=tag.toUpperCase();this.doc=doc;this.children=[];this.attributes={};this.style={};this.dataset={};this.events=new Map();this.value='';this.disabled=false;this.checked=false;this.files=[];this._text='';}
  setAttribute(k,v){this.attributes[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;if(k==='checked')this.checked=true;}
  getAttribute(k){return this.attributes[k];}
  append(...items){for(const item of items){item.parentNode=this;this.children.push(item);}}
  replaceChildren(...items){this.children.forEach(x=>{x.parentNode=null;});this.children=[];this._text='';this.append(...items);}
  addEventListener(t,fn){const list=this.events.get(t)||[];list.push(fn);this.events.set(t,list);}
  emit(t,props={}){if(this.disabled&&t==='click')return;const e={target:this,detail:1,preventDefault(){this.defaultPrevented=true;},...props};for(const fn of this.events.get(t)||[])fn(e);}
  click(){this.emit('click');}
  set textContent(v){this.replaceChildren();this._text=String(v);}
  get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}
}
async function mount({activate=true,filesAPI=null}={}){
  const modules=await modelPromise;const doc={hidden:false,events:new Map(),createElement(tag){return new Element(tag,this);},createTextNode(v){return {nodeType:3,textContent:String(v)};},addEventListener(t,fn){this.events.set(t,fn);},removeEventListener(t){this.events.delete(t);}};doc.body=doc.createElement('body');const root=doc.createElement('main');doc.body.append(root);const context=vm.createContext({document:doc,window:{toolbox:{files:filesAPI}},URL,Date,Math,Promise,console,...modules,module:{exports:{}}});vm.runInContext(fs.readFileSync(path.resolve(feature,'../../core/ui.js'),'utf8').replace(/export /g,'')+'\nmodule.exports={h};',context);context.h=context.module.exports.h;const source=fs.readFileSync(path.join(feature,'index.js'),'utf8').replace(/^import .*;\r?$/gm,'').replace('export default','module.exports =').replace(/import\.meta\.url/g,JSON.stringify(pathToFileURL(path.join(feature,'index.js')).href));vm.runInContext(source,context);let configCalls=0;const lifecycle=context.module.exports.create(root,{config:{set(){configCalls++;}}});const all=(node=root)=>[node,...node.children.flatMap(x=>x.nodeType===1?all(x):[])];const button=text=>all().find(e=>e.tagName==='BUTTON'&&e.textContent===text);const field=label=>all().find(e=>e.getAttribute('aria-label')===label);function choose(values=[file()],directory=false){const input=field(directory?'选择目录':'选择文本文件');input.files=values;input.value='native-name';input.emit('change');return input;}async function waitDone(){for(let n=0;n<1500;n++){if(button('取消扫描').disabled)return;await new Promise(r=>setTimeout(r,1));}throw new Error('scan timeout');}if(activate)lifecycle.activate();return {root,doc,all,button,field,lifecycle,choose,waitDone,configCalls:()=>configCalls,text(){return root.textContent;},async scan(values=[file()],directory=false){choose(values,directory);button('开始本地扫描').click();await waitDone();}};
}

test('inactive create ignores selection; file/directory events scan only File objects and clear native selector labels',async()=>{const ui=await mount({activate:false});ui.choose();assert.equal(ui.button('开始本地扫描').disabled,true);ui.lifecycle.activate();const input=ui.choose([file()]);assert.equal(input.value,'');ui.button('开始本地扫描').click();await ui.waitDone();assert.match(ui.text(),/发现 2 项/);assert.match(ui.text(),/行 2 · 列 12/);assert.equal(ui.text().includes(KEY),false);assert.equal(ui.text().includes(PHONE),false);assert.equal(ui.configCalls(),0);assert.equal(ui.field('选择目录').getAttribute('webkitdirectory'),'');ui.lifecycle.destroy();});
test('rule toggles and too-many-file error preserve prior results without pretending skipped selection was scanned',async()=>{const ui=await mount();ui.field('中国大陆手机号格式').checked=false;await ui.scan();assert.match(ui.text(),/发现 1 项/);ui.choose(Array(51).fill(file()));assert.match(ui.text(),/超过 50/);assert.ok(ui.text().includes('R001'));ui.field('高信号密钥赋值').checked=false;ui.field('典型令牌或访问标识').checked=false;ui.button('开始本地扫描').click();assert.match(ui.text(),/至少选择一条/);ui.lifecycle.destroy();});
test('directory file status and binary/UTF8 failures remain visible alongside retained findings',async()=>{const ui=await mount();await ui.scan([file(SOURCE,'notes.txt',{webkitRelativePath:'资料/notes.txt'}),file([255,254,65,0],'utf16.txt'),file('x','photo.png')],true);assert.match(ui.text(),/未扫描 2/);assert.match(ui.text(),/不是严格 UTF-8/);assert.match(ui.text(),/疑似二进制/);assert.ok(ui.text().includes('R002'));ui.lifecycle.destroy();});
test('UI marking updates reason/status, enforces false-positive reason and invalidates export preview',async()=>{const ui=await mount();await ui.scan();ui.button('预览 JSON 报告').click();assert.ok(ui.field('已遮蔽报告预览'));ui.field('R001 审阅状态').value='falsePositive';ui.all().find(e=>e.tagName==='BUTTON'&&e.textContent==='保存审阅标记').click();assert.match(ui.text(),/需填写/);ui.field('R001 审阅原因').value=`这是测试占位符 ${KEY}`;ui.all().find(e=>e.tagName==='BUTTON'&&e.textContent==='保存审阅标记').click();assert.equal(ui.field('已遮蔽报告预览'),undefined);ui.button('预览 JSON 报告').click();const report=JSON.parse(ui.field('已遮蔽报告预览').value);assert.equal(report.findings[0].status,'falsePositive');assert.match(report.findings[0].reason,/测试占位符/);safe(report);ui.lifecycle.destroy();});
test('cancel while reading and lifecycle hiding retain explicit canceled coverage without starting on reactivation',async()=>{let resolve;const gate=new Promise(r=>{resolve=r;});const pending=file(SOURCE,'pending.txt',{slice(){return {arrayBuffer(){return gate;}};}});const ui=await mount();ui.choose([pending,file(SOURCE,'later.txt')]);ui.button('开始本地扫描').click();await new Promise(r=>setTimeout(r,3));ui.doc.hidden=true;ui.doc.events.get('visibilitychange')();resolve(new TextEncoder().encode(SOURCE).buffer);await ui.waitDone();ui.doc.hidden=false;assert.match(ui.text(),/取消 2/);ui.button('预览 JSON 报告').click();const report=JSON.parse(ui.field('已遮蔽报告预览').value);assert.equal(report.state,'canceled');assert.equal(report.cancelReason,'hidden');ui.lifecycle.deactivate();ui.lifecycle.activate();assert.match(ui.text(),/取消 2/);ui.lifecycle.destroy();assert.equal(ui.doc.events.size,0);assert.equal(ui.root.children.length,0);});
test('JSON/MD previews and copyOnly exports never include key/phone/context/path values; success requires ok===true',async()=>{const calls=[];const ui=await mount({filesAPI:{saveTextSupportsCopyOnly:true,async saveText(args){calls.push(args);return {ok:true};}}});await ui.scan([file(SOURCE,KEY+'.txt',{webkitRelativePath:`${PHONE}/${KEY}.txt`})]);for(const [label,extension] of [['预览 JSON 报告','json'],['预览 Markdown 报告','md']]){ui.button(label).click();safe(ui.field('已遮蔽报告预览').value);assert.match(ui.text(),/实际目标路径在原生保存对话框/);ui.button('导出当前预览副本').click();await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).copyOnly,true);assert.equal(calls.at(-1).extension,extension);safe(calls.at(-1).content);assert.match(ui.text(),/已保存已遮蔽报告新副本/);}ui.lifecycle.destroy();});
test('canceled, resolved failure, missing success flag and thrown exports preserve preview/results and mask bridge errors',async()=>{for(const outcome of [{canceled:true},{ok:false,error:`拒绝 ${KEY} ${PHONE}`},undefined,new Error(`错误 ${KEY}`)]){const ui=await mount({filesAPI:{saveTextSupportsCopyOnly:true,async saveText(){if(outcome instanceof Error)throw outcome;return outcome;}}});await ui.scan();ui.button('预览 JSON 报告').click();const before=ui.field('已遮蔽报告预览').value;ui.button('导出当前预览副本').click();await new Promise(r=>setImmediate(r));assert.equal(ui.field('已遮蔽报告预览').value,before);assert.equal(ui.text().includes('已保存已遮蔽报告新副本'),false);assert.match(ui.text(),outcome?.canceled?/已取消保存/:/保存失败/);safe(ui.text());ui.lifecycle.destroy();}});
test('old bridge blocks export and destroying an in-flight scan clears resources without late DOM updates',async()=>{let calls=0;const ui=await mount({filesAPI:{async saveText(){calls++;}}});await ui.scan();ui.button('预览 JSON 报告').click();ui.button('导出当前预览副本').click();assert.equal(calls,0);assert.match(ui.text(),/支持副本保护/);ui.lifecycle.destroy();let resolve;const gate=new Promise(r=>resolve=r);const next=await mount();next.choose([file(SOURCE,'pending.txt',{slice(){return {arrayBuffer(){return gate;}};}})]);next.button('开始本地扫描').click();await new Promise(r=>setTimeout(r,3));next.lifecycle.destroy();resolve(new TextEncoder().encode(SOURCE).buffer);await new Promise(r=>setTimeout(r,5));assert.equal(next.root.children.length,0);assert.equal(next.doc.events.size,0);});
test('replacement selection waits for a canceled pending read and stale progress cannot overwrite the new scan',async()=>{let resolve;const gate=new Promise(r=>resolve=r);const ui=await mount();ui.choose([file(SOURCE,'old.txt',{slice(){return {arrayBuffer(){return gate;}};}})]);ui.button('开始本地扫描').click();await new Promise(r=>setTimeout(r,3));ui.choose([file('hello','new.txt')]);assert.equal(ui.button('开始本地扫描').disabled,true);assert.match(ui.text(),/等待此前/);resolve(new TextEncoder().encode(SOURCE).buffer);await ui.waitDone();assert.equal(ui.button('开始本地扫描').disabled,false);ui.button('开始本地扫描').click();await ui.waitDone();assert.match(ui.text(),/发现 0 项/);assert.equal(ui.text().includes('R001'),false);ui.lifecycle.destroy();});
test('stale review controls cannot mark same-numbered findings belonging to a later scan',async()=>{const ui=await mount();await ui.scan();ui.field('R001 审阅状态').value='falsePositive';ui.field('R001 审阅原因').value='旧扫描的练习占位符';const old=ui.all().find(e=>e.tagName==='BUTTON'&&e.textContent==='保存审阅标记');await ui.scan([file(SOURCE,'new.txt')]);old.click();ui.button('预览 JSON 报告').click();const report=JSON.parse(ui.field('已遮蔽报告预览').value);assert.equal(report.findings[0].status,'unreviewed');assert.equal(report.findings[0].reason,'');ui.lifecycle.destroy();});
