const test=require('node:test');const assert=require('node:assert/strict');const model=()=>import('../src/renderer/features/L037/model.mjs');
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

const close=(actual,expected)=>assert.ok(Math.abs(actual-expected)<=1e-10*Math.max(1,Math.abs(expected)),`${actual} ~ ${expected}`);
test('L037 手算10/8 sd2/2 n20/20 Δ2 d1全中间项',async()=>{const m=await model(),r=m.derive(m.example());assert.equal(r.delta,2);assert.deepEqual(r.d,{defined:true,value:1});assert.deepEqual([r.pooled.weightA,r.pooled.weightB,r.pooled.weightedA,r.pooled.weightedB,r.pooled.numerator,r.pooled.denominator,r.pooled.variance,r.pooled.sd],[19,19,76,76,152,38,4,2]);assert.equal(r.sourceMode,'summary');assert.equal(Object.hasOwn(r.groups.a,'rawValues'),false);});
test('L037 unequal n独立oracle权重2/4 pooled12 d√3，交换正负',async()=>{const m=await model(),d=m.example();d.summary={a:{mean:'10',sd:'2',n:'3'},b:{mean:'4',sd:'4',n:'5'}};const r=m.derive(d);assert.deepEqual([r.pooled.weightedA,r.pooled.weightedB,r.pooled.denominator,r.pooled.variance],[8,64,6,12]);close(r.d.value,Math.sqrt(3));const swapped=m.derive({...d,summary:{a:d.summary.b,b:d.summary.a}});assert.equal(swapped.delta,-6);close(swapped.d.value,-Math.sqrt(3));});
test('L037 pooledSD零同均值和不同均值d都未定义，非零SD同均值d0',async()=>{const m=await model();for(const mean of['8','10']){const d=m.example();d.summary.a.sd='0';d.summary.b.sd='0';d.summary.a.mean=mean;const r=m.derive(d);assert.equal(r.pooled.sd,0);assert.equal(r.d.defined,false);assert.equal(Object.hasOwn(r.d,'value'),false);assert.match(r.d.reason,/均值差为0也不定义为0/);}const d=m.example();d.summary.a.mean='8';assert.equal(m.derive(d).d.value,0);});
test('L037 原始数据n-1样本SD与离差平方和，非总体SD',async()=>{const m=await model(),d=m.example('raw'),r=m.derive(d);assert.deepEqual([r.groups.a.n,r.groups.a.mean,r.groups.a.variance,r.groups.a.sd,r.groups.a.sumSquaredDeviations],[3,10,4,2,8]);assert.deepEqual(r.groups.a.rawValues,[8,10,12]);assert.equal(r.groups.b.mean,8);assert.equal(r.pooled.denominator,4);assert.equal(r.d.value,1);});
test('L037 来源互斥summary忽略非法原始词，raw忽略非法汇总数字',async()=>{const m=await model(),s=m.example();s.raw={a:'this is not data',b:'not numbers'};assert.equal(m.derive(s).d.value,1);const r=m.example('raw');r.summary.a={mean:'NaN',sd:'-99',n:'0'};assert.equal(m.derive(r).d.value,1);assert.equal(m.derive(r).sourceMode,'raw');});
test('L037 中心化Welford大偏移小离差，独立两遍oracle50组',async()=>{const m=await model(),offset=999999999,delta=2**-23,pair=[offset,offset+delta],s=m.sampleStatistics(pair);assert.equal(s.variance,delta**2/2);let seed=7;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};for(let i=0;i<50;i++){const values=Array.from({length:2+Math.floor(random()*50)},()=>Math.floor(random()*200)-100),mean=values.reduce((a,b)=>a+b,0)/values.length,variance=values.reduce((sum,x)=>sum+(x-mean)**2,0)/(values.length-1),actual=m.sampleStatistics(values);close(actual.mean,mean);close(actual.variance,variance);close(actual.sd,Math.sqrt(variance));}});
test('L037 原始逗号/空白语法，空字段/代码/最少数量拒绝',async()=>{const m=await model();assert.deepEqual(m.parseData(' 1, 2\n3\t4 ','A').values,[1,2,3,4]);for(const raw of['','1','1,,2','1,2,','1, ,2','[1,2]','1;2','alert(1),2','NaN,2','1e999,2'])assert.throws(()=>m.parseData(raw,'A'));});
test('L037 两组合计1000上界完整导出，1001拒绝不截断',async()=>{const m=await model(),d=m.example('raw');d.raw.a=Array.from({length:500},(_,i)=>String(i)).join(',');d.raw.b=Array.from({length:500},(_,i)=>String(-i)).join(',');const r=m.derive(d);assert.equal(r.groups.a.rawValues.length+r.groups.b.rawValues.length,1000);assert.equal(r.groups.b.rawTokens.at(-1),'-499');assert.match(m.reportMarkdown({draft:d,result:r}),/-499/);d.raw.b+=',-500';assert.throws(()=>m.derive(d),/合计.*1000/);assert.equal(d.raw.b.endsWith('-500'),true);});
test('L037 finite范围与平方下溢拒绝、上边界计算有限',async()=>{const m=await model();for(const x of['Infinity','NaN','1e-151','1e-999','1000000001','-1000000001','1'.repeat(33)])assert.throws(()=>m.numeric(x,'x'));assert.equal(m.numeric('0','x'),0);assert.equal(m.numeric('1e-150','x'),1e-150);assert.throws(()=>m.sampleStatistics([1e-150,1.000000000000001e-150]),/精度范围/);const d=m.example();d.summary={a:{mean:'1e9',sd:'1e9',n:'1000000'},b:{mean:'-1e9',sd:'1e9',n:'1000000'}};const r=m.derive(d);assert.equal(r.delta,2e9);assert.equal(r.d.value,2);assert.equal(Number.isFinite(r.pooled.numerator),true);});
test('L037 样本SD非负n2至百万整数/条件不适用不推荐其他检验',async()=>{const m=await model();for(const patch of[{sd:'-1'},{n:'1'},{n:'2.5'},{n:'2e1'},{n:'1000001'}]){const d=m.example();Object.assign(d.summary.a,patch);assert.throws(()=>m.derive(d));}for(const patch of[{design:'paired'},{design:'unknown'},{variance:'unequal'},{variance:'unknown'}])assert.throws(()=>m.derive({...m.example(),...patch}),/不适用/);});
test('L037 JS精度/模型声明/数据导出边界明确，不输出推断结论',async()=>{const m=await model(),r=m.derive(m.example());assert.match(r.warnings.join(''),/没有被自动验证/);assert.match(r.warnings.join(''),/JS Number.*舍入/);assert.match(r.warnings.join(''),/未选模式的原始记录/);assert.match(r.warnings.join(''),/不计算p值.*置信区间.*临床/);assert.equal(Object.hasOwn(r,'pValue'),false);});
test('L037 snapshot完整模式草稿和结果不变，schema/原始64KiB/字段容量',async()=>{const m=await model(),d=m.example(),before=structuredClone(d),r=m.derive(d),stored=m.prepareStoredState({...d,result:r});assert.deepEqual(d,before);assert.equal(Object.hasOwn(stored,'result'),false);assert.deepEqual(m.validateStoredState(stored),stored);assert.throws(()=>m.validateStoredState({...stored,schemaVersion:2}),/版本/);assert.throws(()=>m.validateStoredState({...stored,extra:'x'.repeat(65536)}),/64KiB/);assert.throws(()=>m.prepareStoredState({...d,raw:{a:'x'.repeat(18001),b:''}}),/18000/);assert.throws(()=>m.derive({...d,raw:{a:'汉'.repeat(18000),b:'汉'.repeat(18000)}}),/64KiB/);d.summary.a.mean='12';assert.equal(r.groups.a.mean,10);});
test('L037 完整Markdown安全包含未选原始记录与全部中间项',async()=>{const m=await model(),d=m.example();d.raw.a='<script>`````';const r=m.derive(d),md=m.reportMarkdown({draft:d,result:r});assert.match(md,/&lt;script&gt;/);assert.doesNotMatch(md,/<script>/);assert.match(md,/`{6}json/);assert.match(md,/"numerator": 152/);assert.match(md,/"denominator": 38/);assert.match(m.reportMarkdown({draft:d,result:null}),/尚无有效/);});
test('L037 实际组件默认Δ2d1中间项/JSONMD预览/严格新副本',async t=>{const calls=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});const root=new NodeStub('div'),tool=(await import('../src/renderer/features/L037/index.js')).default,life=tool.create(root,{});await button(root,'计算中间项').fire('click');assert.match(root.textContent,/Δmean = 2 · Cohen d = 1/);assert.match(root.textContent,/合并方差 = \(76 \+ 76\) \/ 38 = 4/);assert.equal(walk(root).filter(n=>n.className==='l037-preview').length,2);await button(root,'导出完整 JSON').fire('click');await button(root,'导出完整 Markdown').fire('click');assert.equal(JSON.parse(calls[0].content).result.d.value,1);assert.equal(calls[1].copyOnly,true);assert.match(root.textContent,/含两种输入草稿/);life.destroy();});
test('L037 模式真实切换禁用来源、保留输入、编辑旧结果失效',async t=>{dom(t,{});const root=new NodeStub('div'),tool=(await import('../src/renderer/features/L037/index.js')).default,life=tool.create(root,{});assert.equal(control(root,'A组原始数据').disabled,true);assert.equal(control(root,'A组均值').disabled,false);await button(root,'计算中间项').fire('click');await fill(root,'计算来源','raw');assert.equal(walk(root).some(n=>n.className==='l037-summary'),false);assert.equal(control(root,'A组均值').disabled,true);assert.equal(control(root,'A组原始数据').disabled,false);await fill(root,'A组原始数据','7,9,11');await fill(root,'B组原始数据','1,3,5');await button(root,'计算中间项').fire('click');assert.match(root.textContent,/Δmean = 6 · Cohen d = 3/);await fill(root,'计算来源','summary');assert.equal(control(root,'A组原始数据').value,'7,9,11');assert.equal(control(root,'A组均值').value,'10');life.destroy();});
test('L037 零SD未定义与配对/异方差拒绝是真实事件，示例按钮',async t=>{dom(t,{});const root=new NodeStub('div'),tool=(await import('../src/renderer/features/L037/index.js')).default,life=tool.create(root,{});await fill(root,'A组样本SD','0');await fill(root,'B组样本SD','0');await fill(root,'A组均值','8');await button(root,'计算中间项').fire('click');assert.match(root.textContent,/Cohen d = 未定义/);await fill(root,'分组结构（人工声明）','paired');await button(root,'计算中间项').fire('click');assert.match(root.textContent,/配对.*不适用/);assert.equal(walk(root).some(n=>n.className==='l037-summary'),false);await button(root,'载入原始数据示例').fire('click');assert.equal(control(root,'计算来源').value,'raw');await fill(root,'方差设定（人工声明）','unequal');await button(root,'计算中间项').fire('click');assert.match(root.textContent,/方差不等.*不适用/);await button(root,'载入10\/8汇总示例').fire('click');assert.equal(control(root,'计算来源').value,'summary');life.destroy();});
test('L037 立即草稿保存/恢复无derived/无定时器与容量版本拒绝',async t=>{dom(t,{});const saved=[],old=global.setTimeout;global.setTimeout=()=>{throw Error('no timer');};t.after(()=>global.setTimeout=old);const root=new NodeStub('div'),tool=(await import('../src/renderer/features/L037/index.js')).default,life=tool.create(root,{config:{set:(_key,value)=>saved.push(value)}});await fill(root,'A组均值','12');await button(root,'计算中间项').fire('click');life.deactivate();const stored=saved.at(-1);assert.equal(stored.schemaVersion,1);assert.equal(Object.hasOwn(stored,'result'),false);life.destroy();const restoreRoot=new NodeStub('div'),restored=tool.create(restoreRoot,{config:{get:()=>stored}});assert.equal(control(restoreRoot,'A组均值').value,'12');assert.equal(walk(restoreRoot).some(n=>n.className==='l037-summary'),false);restored.destroy();for(const raw of[{...stored,schemaVersion:2},{...stored,extra:'x'.repeat(65536)}]){const node=new NodeStub('div'),instance=tool.create(node,{config:{get:()=>raw}});assert.match(node.textContent,/草稿未恢复/);instance.destroy();}});
test('L037 cap/严格ok/取消覆盖失败/超长整份不导出与销毁异步',async t=>{const calls=[];let response={ok:'true'};dom(t,{saveTextSupportsCopyOnly:false,saveText:async p=>{calls.push(p);return response;}});const root=new NodeStub('div'),tool=(await import('../src/renderer/features/L037/index.js')).default,life=tool.create(root,{});await button(root,'导出完整 JSON').fire('click');assert.equal(calls.length,0);window.toolbox.files.saveTextSupportsCopyOnly=true;for(const next of[{ok:'true'},{canceled:true},{ok:false,error:'EEXIST'}]){response=next;await button(root,'导出完整 JSON').fire('click');assert.equal(calls.at(-1).copyOnly,true);assert.equal(JSON.parse(calls.at(-1).content).result,null);assert.doesNotMatch(root.textContent,/已导出完整新副本/);}await fill(root,'A组均值','x'.repeat(33));const count=calls.length;await button(root,'导出完整 JSON').fire('click');assert.equal(calls.length,count);assert.match(root.textContent,/整份导出拒绝/);await fill(root,'A组均值','10');let resolve;window.toolbox.files.saveText=()=>new Promise(done=>resolve=done);const pending=button(root,'导出完整 JSON').fire('click');life.destroy();resolve({ok:true});await pending;assert.equal(root.children.length,0);});
