const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib');globalThis.crypto||=crypto.webcrypto;const model=import('../src/renderer/features/T036/model.mjs'),codec=import('../src/renderer/features/T036/png.mjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function independentCRC(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let k=0;k<8;k++)crc=crc&1?(crc>>>1)^0xedb88320:crc>>>1;}return(crc^0xffffffff)>>>0;}
function chunk(tag,bytes){const out=Buffer.alloc(bytes.length+12);out.writeUInt32BE(bytes.length);out.write(tag,4);Buffer.from(bytes).copy(out,8);out.writeUInt32BE(independentCRC(out.subarray(4,-4)),out.length-4);return out;}
const paeth=(a,b,c)=>{const target=a+b-c,da=Math.abs(target-a),db=Math.abs(target-b),dc=Math.abs(target-c);return da<=db&&da<=dc?a:db<=dc?b:c;};
function png(w,h,type,pixels,extras=[],filter=0){const channels=({0:1,2:3,3:1,4:2,6:4})[type],n=w*channels,head=Buffer.alloc(13);head.writeUInt32BE(w);head.writeUInt32BE(h,4);head[8]=8;head[9]=type;const scan=Buffer.alloc((n+1)*h);for(let y=0;y<h;y++){const f=typeof filter==='function'?filter(y):filter;scan[y*(n+1)]=f;for(let x=0;x<n;x++){const i=y*n+x,a=x>=channels?pixels[i-channels]:0,b=y?pixels[i-n]:0,c=y&&x>=channels?pixels[i-n-channels]:0,base=f===0?0:f===1?a:f===2?b:f===3?Math.floor((a+b)/2):paeth(a,b,c);scan[y*(n+1)+1+x]=(pixels[i]-base)&255;}}return new Uint8Array(Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),...extras.map(([tag,b])=>chunk(tag,b)),chunk('IDAT',zlib.deflateSync(scan)),chunk('IEND',Buffer.alloc(0))]));}
function rgba(w,h){const a=new Uint8Array(w*h*4);for(let i=0;i<w*h;i++)a.set([(i*31)%256,(i*47)%256,(i*73)%256,0],i*4);return a;}
function area(a,width,x,y,w,h,alpha){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)a[(j*width+i)*4+3]=alpha;}
test('T036 metadata, private lossless codec and fixed worker only',()=>{const p=path.join(__dirname,'../src/renderer/features/T036'),m=JSON.parse(fs.readFileSync(path.join(p,'meta.json'),'utf8'));assert.equal(m.id,'T036');assert.equal(m.category,'工具');const s=fs.readFileSync(path.join(p,'model.mjs'),'utf8');assert.ok(s.includes('cropPixels'));assert.ok(!s.includes('drawImage'));});
test('T036 all five PNG filters decoded from independent zlib fixtures exact original RGBA including alpha0 RGB',async()=>{const c=await codec,p=rgba(15,9);for(let i=3;i<p.length;i+=4)p[i]=i%256;for(let f=0;f<5;f++){const out=await c.decode(png(15,9,6,p,[],f));assert.deepEqual(out.rgba,p);}assert.deepEqual((await c.decode(png(15,9,6,p,[],y=>y%5))).rgba,p);assert.equal(c.crc32(new TextEncoder().encode('123456789')),0xcbf43926);});
test('T036 gray/RGB/palette/grayAlpha with transparency expansion exact source pixels',async()=>{const c=await codec;assert.deepEqual((await c.decode(png(2,1,0,new Uint8Array([3,7]),[['tRNS',new Uint8Array([0,3])]]))).rgba,new Uint8Array([3,3,3,0,7,7,7,255]));assert.deepEqual((await c.decode(png(2,1,2,new Uint8Array([1,2,3,4,5,6]),[['tRNS',new Uint8Array([0,1,0,2,0,3])]]))).rgba,new Uint8Array([1,2,3,0,4,5,6,255]));assert.deepEqual((await c.decode(png(2,1,3,new Uint8Array([0,1]),[['PLTE',new Uint8Array([20,30,40,50,60,70])],['tRNS',new Uint8Array([128,0])]]))).rgba,new Uint8Array([20,30,40,128,50,60,70,0]));assert.deepEqual((await c.decode(png(2,1,4,new Uint8Array([30,60,80,120])))).rgba,new Uint8Array([30,30,30,60,80,80,80,120]));});
test('T036 center40 square in100, zero margin yields exact40 and independently copied raw RGBA',async()=>{const m=await model,p=rgba(100,100);area(p,100,30,30,40,40,255);const source=png(100,100,6,p),before=hash(source),r=await m.batch([{name:'square.png',bytes:source}],{threshold:1,margin:0});assert.deepEqual(r.report.counts,{total:1,success:1,failed:0});assert.deepEqual(r.report.items[0].crop,{x:30,y:30,width:40,height:40});const c=await codec,d=await c.decode(r.outputs[0].bytes),expected=new Uint8Array(40*40*4);for(let y=0;y<40;y++)for(let x=0;x<40;x++)expected.set(p.slice(((y+30)*100+x+30)*4,((y+30)*100+x+30)*4+4),(y*40+x)*4);assert.deepEqual(d.rgba,expected);assert.equal(d.width,40);assert.equal(d.height,40);assert.equal(hash(source),before);});
test('T036 partial alpha and invisible RGB inside preserved exactly, threshold only affects external bounds',async()=>{const m=await model,p=rgba(10,10);area(p,10,3,3,4,4,128);p[(4*10+4)*4+3]=0;p[(1*10+1)*4+3]=1;const a=m.bounds(10,10,p,{threshold:1,margin:0}),b=m.bounds(10,10,p,{threshold:2,margin:0});assert.deepEqual(a.crop,{x:1,y:1,width:6,height:6});assert.deepEqual(b.crop,{x:3,y:3,width:4,height:4});const r=await m.batch([{name:'partial.png',bytes:png(10,10,6,p)}],{threshold:2,margin:0}),d=await(await codec).decode(r.outputs[0].bytes);assert.deepEqual([...d.rgba.slice((1*4+1)*4,(1*4+1)*4+4)],[...p.slice((4*10+4)*4,(4*10+4)*4+4)]);assert.equal(d.rgba[3],128);});
test('T036 margins clamp to original boundary no synthetic padding, absent subject fails no fake file',async()=>{const m=await model,p=rgba(10,10);area(p,10,1,2,3,2,255);assert.deepEqual(m.bounds(10,10,p,{threshold:1,margin:3}).crop,{x:0,y:0,width:7,height:7});assert.deepEqual(m.bounds(10,10,p,{threshold:1,margin:128}).crop,{x:0,y:0,width:10,height:10});assert.throws(()=>m.bounds(10,10,rgba(10,10),{threshold:1,margin:0}),/主体/);const r=await m.batch([{name:'empty.png',bytes:png(10,10,6,rgba(10,10))}],{threshold:1,margin:0});assert.equal(r.report.counts.failed,1);assert.equal(r.outputs.length,0);const b=await m.bundle(r);assert.deepEqual(b.files.map(x=>x.path),['crop-report.json']);});
test('T036 deterministic every1–16binary alpha grid threshold independently scan bounds',async()=>{const m=await model;for(let mask=1;mask<65536;mask+=31){const p=rgba(4,4),xs=[],ys=[];for(let i=0;i<16;i++)if(mask&(1<<i)){p[i*4+3]=255;xs.push(i%4);ys.push(Math.floor(i/4));}const r=m.bounds(4,4,p,{threshold:128,margin:0});assert.deepEqual(r.crop,{x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs)+1,height:Math.max(...ys)-Math.min(...ys)+1});}});
test('T036 output native zlib decoded filter0scanlines match every raw byte; selected color/density chunks copied exact',async()=>{const c=await codec,p=rgba(9,7);area(p,9,0,0,9,7,200);const gamma=Buffer.alloc(4);gamma.writeUInt32BE(45455);const phys=Buffer.alloc(9);phys.writeUInt32BE(2835);phys.writeUInt32BE(2835,4);phys[8]=1;const input=png(9,7,6,p,[['gAMA',gamma],['pHYs',phys],['tEXt',Buffer.from('source\0private')]]),d=await c.decode(input),out=await c.encode(9,7,d.rgba,d.colorChunks),info=c.inspect(out),rows=zlib.inflateSync(info.idat);for(let y=0;y<7;y++){assert.equal(rows[y*37],0);assert.deepEqual(new Uint8Array(rows.subarray(y*37+1,y*37+37)),p.subarray(y*36,(y+1)*36));}assert.deepEqual(info.colorChunks,d.colorChunks);assert.equal(info.chunks.some(v=>v.tag==='tEXt'),false);});
test('T036 malformed PNG CRC/interlace/16bit/animation/missing data and over-inflate reject complete',async()=>{const c=await codec,p=rgba(2,2),b=png(2,2,6,p);const bad=b.slice();bad[bad.length-1]^=1;assert.throws(()=>c.inspect(bad),/CRC/);const mutate=(index,value)=>{const x=b.slice();x[index]=value;new DataView(x.buffer).setUint32(29,independentCRC(x.subarray(12,29)));return x;};for(const x of[mutate(24,16),mutate(28,1),png(2,2,6,p,[['acTL',new Uint8Array(8)]])])assert.throws(()=>c.inspect(x));const head=Buffer.from(b.slice(8,33)),bomb=new Uint8Array(Buffer.concat([Buffer.from(b.slice(0,8)),head,chunk('IDAT',zlib.deflateSync(Buffer.alloc(100000))),chunk('IEND',Buffer.alloc(0))]));await assert.rejects(c.decode(bomb),/容量/);await assert.rejects(c.decode(png(2,2,6,p,[],5)),/过滤/);});
test('T036 settings fullselection totalpixels limits and invalid types whole rejection',async()=>{const m=await model;for(const s of[{threshold:0,margin:0},{threshold:256,margin:0},{threshold:1,margin:129},{threshold:1.5,margin:0},{threshold:1,margin:0,x:1}])assert.throws(()=>m.settings(s));assert.throws(()=>m.select([]));assert.throws(()=>m.select(Array.from({length:21},()=>({name:'x',size:1}))));assert.throws(()=>m.select([{name:'x',size:20971520},{name:'y',size:1}]));assert.throws(()=>m.select([{name:'x\n',size:1}]));const source=png(2048,2048,6,new Uint8Array(2048*2048*4));await assert.rejects(m.batch(Array.from({length:5},(_,i)=>({name:i+'.png',bytes:source})),{threshold:1,margin:0}),/像素/);});
test('T036 mixed wholebatch allitems failures retained, source hashes, deterministicPNG and fullbundle copies',async()=>{const m=await model,p=rgba(8,8);area(p,8,2,2,3,4,255);const b=png(8,8,6,p),source=[{name:'good.png',bytes:b},{name:'broken.png',bytes:new Uint8Array([1,2])},{name:'empty.png',bytes:png(4,4,6,rgba(4,4))}],r=await m.batch(source,{threshold:1,margin:1}),again=await m.batch(source,{threshold:1,margin:1});assert.deepEqual(r.report.counts,{total:3,success:1,failed:2});assert.deepEqual(r.report.items.map(x=>x.index),[1,2,3]);assert.deepEqual(r.outputs[0].bytes,again.outputs[0].bytes);assert.equal(r.report.items[0].sourceSHA256,hash(b));const pack=await m.bundle(r);assert.equal(pack.copyOnly,true);assert.equal(pack.files.length,2);assert.equal(JSON.parse(Buffer.from(pack.files.at(-1).base64,'base64')).items.length,3);for(const f of pack.files)assert.equal(hash(Buffer.from(f.base64,'base64')),f.sha256);});
