const test=require('node:test');const assert=require('node:assert/strict');const model=()=>import('../src/renderer/features/L026/model.mjs');
function single(operations,resources='fh'){return{resources,entry:'only',nodes:[{id:'only',operations,successors:''}]};}
function chain(count){return{resources:'fh',entry:'n1',nodes:Array.from({length:count},(_,i)=>({id:`n${i+1}`,operations:'Noop',successors:i+1<count?`n${i+2}`:''}))};}
test('L026 默认两分支，仅Use后Exit未释放支泄漏',async()=>{const{audit,example}=await model();const r=audit(example());assert.equal(r.total,2);assert.equal(r.leaking,1);assert.equal(r.operationViolationPaths,0);assert.deepEqual(r.paths.map(row=>row.path),[['open','close','exit'],['open','use','exit']]);assert.deepEqual(r.paths.map(row=>row.leaks),[[],['fh']]);assert.deepEqual(r.paths.map(row=>row.passed),[true,false]);assert.equal(r.paths[0].final.fh,'released');assert.equal(r.paths[1].final.fh,'held');});
test('L026 泄漏只在统一退出检查，不在Acquire/Use中途误判',async()=>{const{audit,example}=await model();const r=audit(example());const leak=r.paths[1];assert.equal(leak.trace.slice(0,-1).some(step=>step.failed),false);assert.equal(leak.trace.at(-1).type,'泄漏');assert.equal(leak.firstFailureStep,4);assert.equal(leak.trace.at(-1).after.fh,'held');assert.equal(r.shortestFailure.step,4);});
test('L026 首次获得前使用/释放，重复Acquire/Release/释放后Use均明确',async()=>{const{audit,example}=await model();const r=audit(example('errors'));assert.deepEqual(r.paths[0].violations.map(v=>v.type),['获得前使用','获得前释放','重复Acquire','重复Release','释放后使用']);assert.equal(r.paths[0].firstFailureStep,1);assert.equal(r.paths[0].trace[3].after.fh,'held');assert.equal(r.paths[0].trace[5].after.fh,'released');assert.equal(r.leaking,0);assert.equal(r.failed,1);});
test('L026 非法操作状态不变但后续合法Release释放，不假报泄漏',async()=>{const{audit}=await model();const r=audit(single('Acquire fh\nAcquire fh\nRelease fh\nExit'));assert.equal(r.paths[0].violations.length,1);assert.equal(r.paths[0].violations[0].type,'重复Acquire');assert.equal(r.paths[0].trace[1].before.fh,'held');assert.equal(r.paths[0].trace[1].after.fh,'held');assert.equal(r.paths[0].trace[2].after.fh,'released');assert.equal(r.leaking,0);assert.equal(r.paths[0].trace.length,5);});
test('L026 从未Acquire的资源不算泄漏，错误Release不造持有状态',async()=>{const{audit}=await model();const clean=audit(single('Noop\nExit'));assert.equal(clean.passed,1);assert.deepEqual(clean.paths[0].leaks,[]);const bad=audit(single('Use fh\nRelease fh\nExit'));assert.equal(bad.leaking,0);assert.equal(bad.paths[0].final.fh,'not-acquired');assert.equal(bad.paths[0].violations.length,2);});
test('L026 Release后可重新Acquire，新周期遗漏Release才泄漏',async()=>{const{audit}=await model();const clean=audit(single('Acquire fh\nRelease fh\nAcquire fh\nRelease fh'));assert.equal(clean.failed,0);const leak=audit(single('Acquire fh\nRelease fh\nAcquire fh\nExit'));assert.equal(leak.leaking,1);assert.equal(leak.paths[0].violations.length,0);assert.match(leak.paths[0].trace[2].reason,/新生命周期/);});
test('L026 多资源独立，只有末尾held者泄漏',async()=>{const{audit,example}=await model();const r=audit(example('multi'));assert.deepEqual(r.paths[0].leaks,['second']);assert.deepEqual(r.paths[0].final,{first:'released',second:'held'});const four={resources:'a,b,c,d',entry:'open',nodes:[{id:'open',operations:'Acquire a\nAcquire b\nAcquire c\nAcquire d',successors:'end'},{id:'end',operations:'Release a\nRelease b\nRelease c\nRelease d',successors:''}]};assert.equal(audit(four).passed,1);assert.throws(()=>audit({...four,resources:'a,b,c,d,e'}),/1–4/);});
test('L026 全路径最短失败按操作数而非首条失败路径选择',async()=>{const{audit}=await model();const r=audit({resources:'fh',entry:'root',nodes:[{id:'root',operations:'Noop',successors:'late,early'},{id:'late',operations:'Acquire fh\nRelease fh\nUse fh\nExit',successors:''},{id:'early',operations:'Use fh\nExit',successors:''}]});assert.equal(r.paths[0].firstFailureStep,4);assert.equal(r.paths[1].firstFailureStep,2);assert.equal(r.shortestFailure.pathIndex,2);assert.equal(r.shortestFailure.step,2);assert.deepEqual(r.shortestFailure.prefix.nodes,['root','early']);assert.equal(r.shortestFailure.trace.length,2);});
test('L026 路径顺序可复现，重汇合节点在每条分支独立执行',async()=>{const{audit,example}=await model();const r=audit(example());assert.equal(r.paths[0].trace[2].before.fh,'released');assert.equal(r.paths[1].trace[2].before.fh,'held');assert.equal(r.paths[0].trace[2].node,'exit');assert.equal(r.paths[1].trace[2].node,'exit');});
test('L026 12节点/48操作完整，13节点或33以上边拒绝',async()=>{const{audit}=await model();const d=chain(12);d.nodes.forEach(node=>{node.operations='Noop\nNoop\nNoop\nNoop';});const r=audit(d);assert.equal(r.total,1);assert.equal(r.paths[0].trace.length,49);assert.equal(r.passed,1);assert.throws(()=>audit(chain(13)),/1–12/);const dense=chain(9);dense.nodes.forEach((node,i)=>{node.successors=dense.nodes.slice(i+1).map(n=>n.id).join(',');});assert.throws(()=>audit(dense),/超过32/);});
test('L026 三层分支独立oracle全路径与预算拒绝不截断',async()=>{const{audit,parseGraph,enumeratePaths}=await model();const d={resources:'fh',entry:'root',nodes:[{id:'root',operations:'Noop',successors:'a,b,c'},...['a','b','c'].map(id=>({id,operations:'Noop',successors:'x,y,z'})),...['x','y','z'].map(id=>({id,operations:'Exit',successors:''}))]};const r=audit(d);const expected=['a','b','c'].flatMap(a=>['x','y','z'].map(b=>['root',a,b]));assert.equal(r.total,9);assert.deepEqual(r.paths.map(p=>p.path),expected);assert.throws(()=>enumeratePaths(parseGraph(d),1),/预算.*不截断/);assert.throws(()=>enumeratePaths(parseGraph(d),2049),/1–2048/);});
test('L026 未知/重复边、节点ID、资源、入口/循环/不可达拒绝',async()=>{const{audit,example}=await model();for(const[value,pattern]of [['missing',/未知后继/],['close,close',/重复/],['open',/循环/]]){const d=example();d.nodes[0].successors=value;assert.throws(()=>audit(d),pattern);}const unknown=example();unknown.nodes[0].operations='Acquire other';assert.throws(()=>audit(unknown),/未知资源/);const unreachable=example();unreachable.nodes.push({id:'unused',operations:'Noop',successors:''});assert.throws(()=>audit(unreachable),/不可达.*拒绝部分/);const duplicate=example();duplicate.nodes[1].id='open';assert.throws(()=>audit(duplicate),/重复节点/);assert.throws(()=>audit({...example(),entry:'other'}),/未知入口/);assert.throws(()=>audit({...example(),resources:'fh,fh'}),/重复/);});
test('L026 操作有限/Exit只叶末/未知类型和文本容量拒绝代码',async()=>{const{audit,example}=await model();for(const text of ['','Noop\n\nExit','Noop\nNoop\nNoop\nNoop\nExit','Exit\nNoop','process.exit()','Acquire fh;','acquire fh','x'.repeat(513)])assert.throws(()=>audit(single(text)));const internal=example();internal.nodes[0].operations='Exit';assert.throws(()=>audit(internal),/叶节点最后/);for(const patch of [{resources:''},{resources:'汉'},{entry:null},{nodes:[]}])assert.throws(()=>audit({...example(),...patch}));});
test('L026 所有结果和草稿确定，快照/路径互不污染',async()=>{const{audit,example}=await model();const d=example();const before=structuredClone(d);const r=audit(d);assert.deepEqual(d,before);assert.deepEqual(r,audit(d));r.paths[0].trace[0].after.fh='changed';assert.equal(r.paths[0].trace[1].before.fh,'held');assert.equal(r.paths[1].trace[0].after.fh,'held');assert.equal(r.paths[0].final.fh,'released');d.nodes[0].operations='Noop';assert.equal(r.graph.nodes[0].operations[0].op,'Acquire');assert.equal(r.input.nodes[0].operations,'Acquire fh');});
test('L026 草稿schema/完整raw64KiB/字段UTF8/JSON重算和完整MD',async()=>{const{audit,example,prepareStoredState,validateStoredState,reportMarkdown}=await model();const draft=example();const stored=prepareStoredState(draft);assert.deepEqual(validateStoredState(stored),stored);assert.throws(()=>validateStoredState({schemaVersion:2}),/版本/);assert.throws(()=>validateStoredState({...stored,hidden:'汉'.repeat(22000)}),/64KiB/);for(const n of [171,22000]){const d=example();d.nodes[0].operations='汉'.repeat(n);assert.throws(()=>prepareStoredState(d),n===171?/512字节/:/64KiB/);}const wrong=example();wrong.nodes[0].id=1;assert.throws(()=>prepareStoredState(wrong),/字段类型/);const payload=JSON.parse(JSON.stringify({draft,result:audit(draft)}));assert.deepEqual(audit(payload.draft),payload.result);const md=reportMarkdown(payload);assert.match(md,/泄漏路径1/);assert.match(md,/路径2 open → use → exit：失败/);assert.match(md,/EndPath/);assert.match(md,/首次违规/);assert.match(reportMarkdown({draft,result:null}),/尚无有效审计/);assert.doesNotMatch(reportMarkdown({draft:{...draft,entry:'<script>'},result:null}),/<script>/);});
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

test('L026 实际组件默认仅一泄漏/路径过滤不截断JSON-MD',async(t)=>{const exported=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{exported.push(p);return{ok:true};}});const{default:feature}=await import('../src/renderer/features/L026/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/完整路径 2 · 通过 1 · 失败 1 · 泄漏路径 1 · 操作违规路径 0/);await button(root,'查看最短失败路径').fire('click');assert.match(root.textContent,/当前路径#2：open → use → exit · 失败/);assert.match(root.textContent,/退出泄漏：fh/);assert.equal(button(root,'下条路径').disabled,true);await button(root,'上条路径').fire('click');assert.match(root.textContent,/退出泄漏：无/);await fill(root,'查看路径','1');await fill(root,'路径筛选','leaks');assert.match(root.textContent,/当前列出1条/);await button(root,'查看路径2').fire('click');await button(root,'导出完整 JSON').fire('click');const p=JSON.parse(exported[0].content);assert.equal(p.result.paths.length,2);assert.deepEqual(p.result.paths[1].leaks,['fh']);assert.equal(exported[0].copyOnly,true);await button(root,'导出完整 Markdown').fire('click');assert.match(exported[1].content,/路径2 open → use → exit：失败/);assert.equal(exported[1].copyOnly,true);assert.doesNotMatch(root.textContent,/\[object Object\]|null/);});
test('L026 UI异常后完整继续、重新Acquire和多资源真实输入',async(t)=>{dom(t,{});const{default:feature}=await import('../src/renderer/features/L026/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'载入状态违规示例').fire('click');await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/退出泄漏：无；操作违规：5次；首次失败步骤：1/);assert.match(root.textContent,/最终资源状态：fh:已释放/);assert.match(root.textContent,/释放后使用/);await fill(root,'路径筛选','leaks');assert.match(root.textContent,/筛选下没有路径/);await fill(root,'路径筛选','violations');assert.match(root.textContent,/当前列出1条/);await fill(root,'节点1操作','Acquire fh\nRelease fh\nAcquire fh');await fill(root,'节点2操作','Release fh\nExit');assert.match(root.textContent,/旧路径和结论已清空/);await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/完整路径 1 · 通过 1 · 失败 0/);await button(root,'载入多资源示例').fire('click');await fill(root,'资源ID列表','first,second,unused');await fill(root,'入口节点ID','open');await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/退出泄漏：second/);assert.match(root.textContent,/unused:从未获得/);});
test('L026 UI表格增删上限和不可达/未知/循环/重复引用拒绝',async(t)=>{dom(t,{});const{default:feature}=await import('../src/renderer/features/L026/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());for(let i=0;i<8;i++)await button(root,'增加节点').fire('click');assert.equal(button(root,'增加节点').disabled,true);await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/不可达节点.*拒绝部分审计/);await button(root,'删除节点12').fire('click');assert.equal(button(root,'增加节点').disabled,false);await button(root,'载入分支释放示例').fire('click');for(const[value,pattern]of [['close,close',/重复/],['unknown',/未知后继/],['open',/循环/]]){await fill(root,'节点1后继',value);await button(root,'审计全部路径').fire('click');assert.match(root.textContent,pattern);assert.match(root.textContent,/尚无有效审计/);}await button(root,'载入分支释放示例').fire('click');await fill(root,'节点1ID','<img>');await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/ID不合法/);await button(root,'载入分支释放示例').fire('click');await button(root,'删除节点1').fire('click');await button(root,'审计全部路径').fire('click');assert.match(root.textContent,/未知入口open/);});
test('L026 UI版本/64KiB/字段容量与严格防覆盖成功契约',async(t)=>{const stored=new Map();let saves=0;dom(t,{saveTextSupportsCopyOnly:1,saveText:async()=>{saves++;return{ok:'true'};}});const{default:feature}=await import('../src/renderer/features/L026/index.js');const config={get:key=>stored.get(key),set:(key,value)=>stored.set(key,value)};const root=new NodeStub('div');const handle=feature.create(root,{config});t.after(()=>handle.destroy());await button(root,'导出完整 JSON').fire('click');assert.equal(saves,0);assert.match(root.textContent,/缺少防覆盖/);window.toolbox.files.saveTextSupportsCopyOnly=true;await button(root,'导出完整 JSON').fire('click');assert.match(root.textContent,/未确认保存成功/);window.toolbox.files.saveText=async()=>({canceled:true});await button(root,'导出完整 Markdown').fire('click');assert.match(root.textContent,/已取消导出/);window.toolbox.files.saveText=async()=>{throw new Error('磁盘失败');};await button(root,'导出完整 JSON').fire('click');assert.match(root.textContent,/导出失败：磁盘失败/);await button(root,'审计全部路径').fire('click');handle.deactivate();const saved=structuredClone(stored.get('features.L026.state'));assert.equal(saved.schemaVersion,1);assert.equal(Object.hasOwn(saved,'result'),false);const r=new NodeStub('div');const restored=feature.create(r,{config});assert.match(r.textContent,/已恢复输入草稿/);assert.match(r.textContent,/尚无有效审计/);assert.equal(control(r,'节点1操作').value,'Acquire fh');restored.destroy();await fill(root,'节点1操作','汉'.repeat(22000));handle.deactivate();assert.deepEqual(stored.get('features.L026.state'),saved);assert.match(root.textContent,/当前草稿未写入全局配置/);await fill(root,'节点1操作','汉'.repeat(171));handle.deactivate();assert.match(root.textContent,/512字节/);for(const raw of [{schemaVersion:2},{...saved,hidden:'汉'.repeat(22000)},{...saved,nodes:[{...saved.nodes[0],id:1}]}]){const invalid=new NodeStub('div');const h=feature.create(invalid,{config:{get:()=>raw}});assert.match(invalid.textContent,/草稿未能恢复/);h.destroy();}});
test('L026 lifecycle清计时器/销毁后异步导出不重建界面',async(t)=>{let resolveSave;dom(t,{saveTextSupportsCopyOnly:true,saveText:()=>new Promise(resolve=>{resolveSave=resolve;})});const originalSet=global.setTimeout;const originalClear=global.clearTimeout;const callbacks=new Map();let next=1;global.setTimeout=fn=>{const id=next++;callbacks.set(id,fn);return id;};global.clearTimeout=id=>callbacks.delete(id);t.after(()=>{global.setTimeout=originalSet;global.clearTimeout=originalClear;});const{default:feature}=await import('../src/renderer/features/L026/index.js');const root=new NodeStub('div');const handle=feature.create(root,{config:{set:()=>{}}});t.after(()=>handle.destroy());await fill(root,'节点1操作','Noop');assert.equal(callbacks.size,1);handle.deactivate();assert.equal(callbacks.size,0);handle.activate();assert.equal(callbacks.size,0);await fill(root,'节点2操作','Noop');const saving=button(root,'导出完整 JSON').fire('click');handle.destroy();assert.equal(callbacks.size,0);resolveSave({ok:true});await saving;assert.equal(root.children.length,0);handle.destroy();assert.doesNotMatch(root.className,/feature-l026/);});
