const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), os = require('node:os'), vm = require('node:vm'), crypto = require('node:crypto'), { pathToFileURL, fileURLToPath } = require('node:url'), { execFileSync, spawn } = require('node:child_process');
const folder = path.resolve(__dirname, '../src/renderer/features/T042'), model = import(pathToFileURL(path.join(folder, 'model.mjs')).href), { createHost } = require(path.join(folder, 'host.cjs'));
const rawProbe = () => ({ streams: [{ index: 0, codec_type: 'video', codec_name: 'h264', width: 320, height: 180, avg_frame_rate: '30/1', pix_fmt: 'yuv420p', sample_aspect_ratio: '1:1', start_time: '0.000000', disposition: { attached_pic: 0 } }, { index: 1, codec_type: 'audio', codec_name: 'aac', sample_rate: '48000', channels: 1, start_time: '0.000000' }], format: { format_name: 'mov,mp4,m4a,3gp,3g2,mj2', duration: '60.000000' }, chapters: [] });
async function source() { return { name: 'fixture.mp4', bytes: 1234, sha256: 'a'.repeat(64), media: (await model).parseProbe(JSON.stringify(rawProbe())) }; }
class Element {
  constructor(tag) { this.nodeType = 1; this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.events = new Map(); this.style = {}; this._text = ''; this.disabled = false; this.value = ''; this.checked = false; this.duration = NaN; }
  setAttribute(k, v) { this.attributes[k] = String(v); if (k === 'value') this.value = String(v); } getAttribute(k) { return this.attributes[k]; } removeAttribute(k) { delete this.attributes[k]; } append(...xs) { for (const x of xs) { this.children.push(x); x.parent = this; } } replaceChildren(...xs) { this.children = []; this._text = ''; this.append(...xs); } insertBefore(x, before) { x.remove(); this.children.splice(this.children.indexOf(before), 0, x); x.parent = this; } remove() { if (this.parent) this.parent.children.splice(this.parent.children.indexOf(this), 1); this.parent = null; } get previousElementSibling() { return this.parent?.children[this.parent.children.indexOf(this) - 1]; } get nextElementSibling() { return this.parent?.children[this.parent.children.indexOf(this) + 1]; }
  addEventListener(t, f) { this.events.set(t, f); } removeEventListener(t) { this.events.delete(t); } emit(t) { return this.events.get(t)?.({ target: this }); } click() { if (!this.disabled) return this.emit('click'); } get textContent() { return this._text + this.children.map(c => c.textContent || '').join(''); } set textContent(v) { this._text = String(v); this.children = []; } querySelectorAll(s) { const tags = s.split(',').map(t => t.toUpperCase()); return this.children.flatMap(c => c.nodeType === 1 ? [c, ...c.querySelectorAll(s)] : []).filter(c => tags.includes(c.tagName)); } pause() { this.paused = true; } load() { this.loaded = true; }
}
async function mount(options = {}) {
  const m = await model, root = new Element('div'), document = { hidden: false, events: new Map(), createElement: t => new Element(t), createTextNode: t => ({ nodeType: 3, textContent: String(t) }), addEventListener(t, f) { this.events.set(t, f); }, removeEventListener(t) { this.events.delete(t); } }, calls = [], cancels = []; let resolveRun, resolveSave;
  const s = await source(), p = m.buildPlan(s, {targetBytes:20000000,width:320,height:180}), output = m.verifyOutput(p, s.media, 1000, 'b'.repeat(64));
  const bridge = { callHostSupported: options.capability !== false, async callHost(id, op, payload) { calls.push({ id, op, payload }); if (op === 'choose_engine') return {ok:false,code:'ENGINE_UNAVAILABLE'}; if (op === 'engine_plan') return { ok: true, engine: { token: 'engine', plannedQueries: ['versions'] } }; if (op === 'engine_confirm') return { ok: true, versions: { ffmpeg: '6.1' } }; if (op === 'choose_source') return { ok: true, source: { ...s, id: 'source', media: null } }; if (op === 'inspect_source') return { ok: true, source: { ...s, id: 'source', previewURL: 'file:///controlled/source-preview.mp4' } }; if (op === 'plan') return { ok: true, plan: { id: 'plan', report: options.infeasible ? m.buildPlan(s,{targetBytes:1,width:320,height:180}) : p } }; if (op === 'run') { const r = { ok: true, result: { id: 'result', previewURL: 'file:///controlled/attempt-1.mp4', report: { output: options.over ? {...output,bytes:20000001,targetBytes:20000000,qualified:false} : output, qualified:!options.over, attempts:[output] } } }; if (options.hold) return new Promise(resolve => { resolveRun = () => resolve(r); }); return r; } if (op === 'save') { if(options.holdSave) return new Promise(resolve=>{resolveSave=resolve;}); if (options.reply instanceof Error) throw options.reply; return options.reply === 'undefined' ? undefined : options.reply || { ok: true, path: 'NEW_COPY' }; } return { ok: true }; }, async cancelHost(id, jobId) { cancels.push({ id, jobId }); return { ok: true }; } };
  const context = vm.createContext({ document, window: { toolbox: { features: bridge } }, ...m, URL, crypto: crypto.webcrypto, module: { exports: {} } }); vm.runInContext(fs.readFileSync(path.join(folder, '../../core/ui.js'), 'utf8').replace(/export /g, '') + '\nmodule.exports={h};', context); context.h = context.module.exports.h; vm.runInContext(fs.readFileSync(path.join(folder, 'index.js'), 'utf8').replace(/^import.*;\r?$/gm, '').replace('export default', 'module.exports=').replaceAll('import.meta.url', JSON.stringify(pathToFileURL(path.join(folder, 'index.js')).href)), context); const lifecycle = context.module.exports.create(root, { config: { set() { assert.fail('must not store sources/config'); } } }); const all = (e = root) => [e, ...e.children.flatMap(c => c.nodeType === 1 ? all(c) : [])], button = label => all().find(e => e.tagName === 'BUTTON' && e.textContent === label), field = label => all().find(e => e.getAttribute?.('aria-label') === label), tick = () => new Promise(r => setImmediate(r));
  async function click(label) { await button(label).click(); await tick(); }
  async function ready() { await click('预览默认引擎查询计划'); await click('确认运行3次版本和编码器查询'); await click('选择本次允许读取的MP4'); await click('确认一次只读媒体检查'); const v=field('只读源副本抽样预览');v.duration=60;v.videoWidth=320;v.videoHeight=180;v.emit('loadedmetadata');const review=field('已抽样核对源视频');review.checked=true;review.emit('change');await click('预览体积与固定尺寸编码计划'); }
  return { root, document, lifecycle, calls, cancels, button, field, tick, click, ready, text: () => root.textContent, finish: () => resolveRun?.(), finishSave: () => resolveSave?.({ok:false,canceled:true}) };
}
test('independent 120sec/20MB budget oracle and exact fixed dimensions', async()=>{const m=await model,s=await source();s.media.durationMs=120000;const p=m.buildPlan(s,{targetBytes:20000000,width:320,height:180});assert.equal(p.reserveBytes,1000000);assert.equal(p.output.video.bitsPerSecond,1170000);assert.equal(p.expectedDurationMs,120000);assert.deepEqual(p.samplePositionsMs,[12000,60000,108000]);assert.equal(p.feasible,true);});
test('insufficient budget gives explicit infeasible; cannot encode or silently shrink',async()=>{const m=await model,p=m.buildPlan(await source(),{targetBytes:1,width:320,height:180});assert.equal(p.feasible,false);assert.equal(p.output.video.width,320);assert.throws(()=>m.encodeArgs(p,'S','O'),/PLAN_INFEASIBLE/);});
test('dimensions require explicit proportion/even/no upscale and finite exact payload',async()=>{const m=await model,s=await source();for(const c of [{targetBytes:20000001,width:320,height:180},{targetBytes:0,width:320,height:180},{targetBytes:1.5,width:320,height:180},{targetBytes:20000000,width:319,height:180},{targetBytes:20000000,width:640,height:360},{targetBytes:20000000,width:160,height:100},{targetBytes:20000000,width:320,height:180,crf:1}])assert.throws(()=>m.buildPlan(s,c));const p=m.buildPlan(s,{targetBytes:20000000,width:160,height:90});assert.equal(p.output.video.width,160);assert.equal(p.output.video.height,90);});
test('actual target equal allowed, one byte over unqualified; no target prediction success',async()=>{const m=await model,s=await source(),p=m.buildPlan(s,{targetBytes:2000000,width:320,height:180});assert.equal(m.verifyOutput(p,s.media,2000000,'b'.repeat(64)).qualified,true);const over=m.verifyOutput(p,s.media,2000001,'b'.repeat(64));assert.equal(over.qualified,false);assert.equal(over.status,'UNQUALIFIED_SIZE_EXCEEDED');assert.equal(over.actualTotalBitsPerSecond,2000001*8/60);});
test('second actual oversize correction remains exact dimensions and below first bitrate, no third',async()=>{const m=await model,s=await source(),c={targetBytes:2000000,width:320,height:180},p=m.buildPlan(s,c),first=m.verifyOutput(p,s.media,2200000,'b'.repeat(64)),q=m.buildPlan(s,c,first);assert.equal(q.attempt,2);assert.equal(q.output.video.bitsPerSecond,Math.floor(p.output.video.bitsPerSecond*2000000/2200000*.85/1000)*1000);assert.equal(q.output.video.width,320);const second=m.verifyOutput(q,s.media,2200000,'c'.repeat(64));assert.throws(()=>m.buildPlan(s,c,second));assert.throws(()=>m.buildPlan(s,c,m.verifyOutput(p,s.media,1000,'b'.repeat(64))));});
test('complete output shape/hash/duration/audio validation refuses metadata truncation',async()=>{const m=await model,s=await source(),p=m.buildPlan(s,{targetBytes:20000000,width:320,height:180});for(const out of [{...s.media,durationMs:59900-1},{...s.media,video:{...s.media.video,width:160}},{...s.media,audio:null}])assert.throws(()=>m.verifyOutput(p,out,1000,'b'.repeat(64)));assert.throws(()=>m.verifyOutput(p,s.media,m.LIMITS.outputBytes,'b'.repeat(64)));assert.throws(()=>m.verifyOutput(p,s.media,1,'bad'));});
test('silent plan stays silent and actual argv has ABR, no CRF/two-pass/nal-hrd/shrink/retry',async()=>{const m=await model,s=await source();s.media.audio=null;const p=m.buildPlan(s,{targetBytes:20000000,width:320,height:180}),a=m.encodeArgs(p,'S','O');assert.equal(p.output.audio,null);assert.ok(a.includes('-an'));assert.equal(a[a.indexOf('-vf')+1],'scale=320:180,setsar=1,fps=30,format=yuv420p');assert.ok(a.includes('-b:v'));for(const bad of ['-crf','-pass','-nal-hrd','-y'])assert.ok(!a.includes(bad));assert.equal(a[a.indexOf('-protocol_whitelist')+1],'file');assert.ok(m.decodeArgs('O').includes('-xerror'));assert.deepEqual(m.decodeArgs('O').slice(-3),['-f','null','-']);});
test('strict source scope rejects HDR/rotation/multi-track/offset/odd dims and unknown container',async()=>{const m=await model;for(const change of [p=>p.streams[0].width=321,p=>p.streams[0].pix_fmt='yuv420p10le',p=>p.streams[0].side_data_list=[{rotation:90}],p=>p.streams[0].start_time='1',p=>p.streams.push({...p.streams[1],index:2}),p=>p.format.format_name='matroska']){const p=rawProbe();change(p);assert.throws(()=>m.parseProbe(JSON.stringify(p)));}assert.throws(()=>m.parseProbe('x'.repeat(131073)));assert.throws(()=>m.parseProbe('{'));});
test('finite engine version and exact encoder support required',async()=>{const m=await model;assert.equal(m.versionBanner('ffmpeg version 6.1-full_build','ffmpeg'),'6.1');assert.throws(()=>m.versionBanner('ffmpeg version 7.0','ffmpeg'));assert.deepEqual(m.encoderSupport(' V....D libx264 H264\n A..... aac AAC'),['libx264','aac']);assert.throws(()=>m.encoderSupport(' V....D h264_nvenc'));});
test('Host real early intent sender isolation operation allowlist renderer paths rejected',async()=>{const h=createHost(),ctx={senderId:742};assert.equal(h.cancel('early-cancel-T042',ctx).ok,true);assert.equal((await h.invoke('engine_plan',{jobId:'early-cancel-T042'},ctx)).canceled,true);assert.equal((await h.invoke('engine_plan',{jobId:'early-cancel-T042'},ctx)).code,'DUPLICATE_JOB_ID');assert.equal((await h.invoke('choose_source',{jobId:'bad-path-T042-01',path:'C:\\other.mp4'},ctx)).code,'INVALID_PAYLOAD');assert.equal((await h.invoke('run',{jobId:'other-T042-001',planId:'foreign',confirmed:true},{senderId:743})).code,'ENGINE_CONFIRM_REQUIRED');assert.equal((await h.invoke('shell',{},ctx)).code,'UNSUPPORTED_OPERATION');h.disposeSender(742);h.disposeSender(743);});
test('UI zero actions at mount source preview ack required',async()=>{const u=await mount();assert.equal(u.calls.length,0);await u.ready();assert.equal(u.calls.at(-1).op,'plan');assert.equal(u.calls.at(-1).payload.sourcePreviewConfirmed,true);const v=u.field('只读源副本抽样预览');assert.equal(v.videoWidth,320);u.lifecycle.destroy();});
async function readyResult(u){await u.ready();await u.click('确认本次完整编码（最多两次）');const v=u.field('完整实际交付成片预览');v.duration=60;v.videoWidth=320;v.videoHeight=180;v.emit('loadedmetadata');const r=u.field('已核对完整成片及交付报告');r.checked=true;r.emit('change');}
test('UI actual metadata and human report review both required before save',async()=>{const u=await mount();await u.ready();await u.click('确认本次完整编码（最多两次）');assert.equal(u.button('预览后创建视频和报告新目录副本').disabled,true);const v=u.field('完整实际交付成片预览');v.duration=60;v.videoWidth=319;v.videoHeight=180;v.emit('loadedmetadata');assert.equal(u.button('预览后创建视频和报告新目录副本').disabled,true);v.videoWidth=320;v.emit('loadedmetadata');u.field('已核对完整成片及交付报告').checked=true;u.field('已核对完整成片及交付报告').emit('change');await u.click('预览后创建视频和报告新目录副本');assert.ok(u.text().includes('已创建新目录副本'));u.lifecycle.destroy();});
test('UI save canceled false undefined throw never claims success and retains full preview',async()=>{for(const reply of [{ok:false,canceled:true},{ok:false,code:'SAVE_REJECTED'},'undefined',new Error('PRIVATE_SENTINEL')]){const u=await mount({reply});await readyResult(u);await u.click('预览后创建视频和报告新目录副本');assert.ok(!u.text().includes('已创建新目录副本'));assert.ok(u.text().includes('actualDurationMs'));assert.ok(!u.text().includes('PRIVATE_SENTINEL'));assert.equal(u.button('预览后创建视频和报告新目录副本').disabled,false);u.lifecycle.destroy();}});
test('UI parameter editing invalidates stale output and never stores media config',async()=>{const u=await mount();await readyResult(u);const i=u.field('目标体积字节');i.value='3000000';i.emit('input');await u.tick();assert.equal(u.button('预览后创建视频和报告新目录副本').disabled,true);assert.ok(!u.text().includes('actualDurationMs'));assert.equal(u.calls.at(-1).op,'discard_result');u.lifecycle.destroy();});
test('UI cancellation late encoder receipt cannot restore old result',async()=>{const u=await mount({hold:true});await u.ready();u.button('确认本次完整编码（最多两次）').click();await u.tick();u.button('取消当前操作').click();u.finish();await u.tick();assert.ok(!u.text().includes('actualDurationMs'));assert.ok(u.cancels.length);u.lifecycle.destroy();});
test('UI hidden/exit pauses both preview videos and destroys listeners no resume source',async()=>{const u=await mount();await readyResult(u);u.document.hidden=true;u.document.events.get('visibilitychange')();await u.tick();assert.ok(u.field('只读源副本抽样预览').paused);assert.ok(u.field('完整实际交付成片预览').paused);assert.ok(!u.text().includes('actualDurationMs'));u.lifecycle.activate();assert.equal(u.button('预览体积与固定尺寸编码计划').disabled,true);u.lifecycle.destroy();assert.equal(u.document.events.size,0);});
test('UI failed engine reselection clears engine source result and pending save cancel keeps preview',async()=>{const u=await mount();await readyResult(u);await u.click('选择可信引擎目录');assert.equal(u.button('确认运行3次版本和编码器查询').disabled,true);assert.ok(!u.text().includes('actualDurationMs'));u.lifecycle.destroy();const v=await mount({holdSave:true});await readyResult(v);v.button('预览后创建视频和报告新目录副本').click();await v.tick();await v.tick();v.button('取消当前操作').click();v.finishSave();await v.tick();assert.ok(v.text().includes('actualDurationMs'));assert.ok(!v.text().includes('已创建新目录副本'));v.lifecycle.destroy();});

test('UI impossible plan clearly unqualified and run button disabled',async()=>{const u=await mount({infeasible:true});await u.ready();assert.equal(u.button('确认本次完整编码（最多两次）').disabled,true);assert.ok(u.text().includes('不合格：目标预算不足'));assert.ok(!u.calls.some(c=>c.op==='run'));u.lifecycle.destroy();});
test('UI actual oversize summary and copied candidate never falsely marked qualified',async()=>{const u=await mount({over:true});await readyResult(u);assert.ok(u.text().includes('不合格：实际超限'));assert.ok(u.text().includes('20000001 / 20000000'));await u.click('预览后创建视频和报告新目录副本');assert.ok(u.text().includes('不合格候选，未标为达标'));u.lifecycle.destroy();});
