const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),{pathToFileURL}=require('node:url');const folder=path.resolve(__dirname,'../src/renderer/features/T022'),model=import(pathToFileURL(path.join(folder,'model.mjs')).href);
function crc(b){let c=0xffffffff;for(const n of b){c^=n;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;}
function chunk(tag,data){const b=Buffer.concat([Buffer.from(tag),data]),size=Buffer.alloc(4),sum=Buffer.alloc(4);size.writeUInt32BE(data.length);sum.writeUInt32BE(crc(b));return Buffer.concat([size,b,sum]);}
function png(width=16,height=20){const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=2;const rgb=Buffer.from(Array.from({length:width*height*3},(_,i)=>(i*17+31)%256)),scan=Buffer.concat(Array.from({length:height},(_,y)=>Buffer.concat([Buffer.from([0]),rgb.subarray(y*width*3,(y+1)*width*3)])));return{rgb,bytes:new Uint8Array(Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('tEXt',Buffer.from('Comment\0SECRET_PNG_METADATA')),chunk('IDAT',zlib.deflateSync(scan)),chunk('IEND',Buffer.alloc(0))]))};}
test('T022 private fixed library bytes licenses and production catalog discover proper category',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(folder,'vendor/manifest.json'),'utf8')),bytes=fs.readFileSync(path.join(folder,'vendor/pdf-lib.esm.min.mjs'));assert.equal(bytes.length,manifest.bundleBytes);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),manifest.bundleSHA256);for(const p of manifest.packages)assert.ok(fs.readFileSync(path.join(folder,'vendor',p.licenseFile)).length>100);const list=require('../src/main/feature-catalog').listFeatures(path.dirname(folder));assert.equal(list.errors.length,0);assert.equal(list.features.find(f=>f.id==='T022').category,'工具');});
test('T022 independent exhaustive6x5RGBA coordinate oracle overlapping opaque masks source unchanged',async()=>{const m=await model,width=6,height=5,input=new Uint8ClampedArray(Array.from({length:120},(_,i)=>i%4===3?255:(i*13)%256)),before=input.slice(),rs=[{x:1,y:1,width:3,height:2},{x:3,y:2,width:2,height:2}],output=m.maskPixels(input,width,height,rs);for(let y=0;y<5;y++)for(let x=0;x<6;x++)for(let channel=0;channel<4;channel++){const inside=(x>=1&&x<4&&y>=1&&y<3)||(x>=3&&x<5&&y>=2&&y<4);assert.equal(output[(y*6+x)*4+channel],inside?(channel===3?255:0):input[(y*6+x)*4+channel]);}assert.deepEqual(input,before);});
test('T022 no transparent underlying samples survive, bad buffers coordinates whole reject',async()=>{const m=await model,b=new Uint8ClampedArray(16);assert.throws(()=>m.maskPixels(b,2,2,[]),/不透明/);b.fill(255);for(const r of[{x:-1,y:0,width:1,height:1},{x:0,y:0,width:0,height:1},{x:1,y:1,width:2,height:1},{x:.5,y:0,width:1,height:1}])assert.throws(()=>m.maskPixels(b,2,2,[r]));assert.throws(()=>m.maskPixels(new Uint8Array(16),2,2,[]));assert.throws(()=>m.maskPixels(b,2,1,[]));});
test('T022 exact pointer floor/ceil outward coverage reverse drag and page boundary clipping',async()=>{const m=await model;assert.deepEqual(m.pointerRect([1.2,2.4],[5.3,6.8],10,10),{x:1,y:2,width:5,height:5});assert.deepEqual(m.pointerRect([5.3,6.8],[1.2,2.4],10,10),{x:1,y:2,width:5,height:5});assert.deepEqual(m.pointerRect([-10,-10],[20,20],10,10),{x:0,y:0,width:10,height:10});assert.throws(()=>m.pointerRect([10,10],[20,20],10,10));assert.throws(()=>m.pointerRect([1,1],[1,1],10,10));assert.throws(()=>m.pointerRect([NaN,1],[2,2],10,10));});
test('T022 strict full100rectangle audit geometry unknown duplicate page refs and all-page budgets',async()=>{const m=await model,pages=[{width:20,height:20}],rects=Array.from({length:100},(_,i)=>({id:i+1,page:1,x:i%20,y:Math.floor(i/20),width:1,height:1}));assert.equal(m.validateRects(pages,rects).length,100);for(const r of[[...rects,rects[0]],[{...rects[0],extra:1}],[{...rects[0],page:2}],[{...rects[0],id:0}],[{...rects[0],width:21}]])assert.throws(()=>m.validateRects(pages,r));assert.throws(()=>m.validateRects(Array.from({length:5},()=>({width:2048,height:2048})),[]));assert.throws(()=>m.geometry(4097,1));assert.throws(()=>m.geometry(4096,1025));assert.throws(()=>m.validateRects([],[]));});
test('T022 freshPDF only RGB image originalPNG metadata not copied, exact independently inflated pixels',async()=>{const m=await model,p=png(),r=await m.build([{width:16,height:20,widthPt:8,heightPt:10,png:p.bytes}]),b=Buffer.from(r.bytes),s=b.toString('latin1');assert.equal(r.pageCount,1);assert.equal((s.match(/\/Type\s*\/Page\b/g)||[]).length,1);assert.equal((s.match(/\/Subtype\s*\/Image\b/g)||[]).length,1);for(const word of['SECRET_PNG_METADATA','/Font','/Annots','/EmbeddedFiles','/Metadata','/JavaScript','/AcroForm','/Info'])assert.equal(s.includes(word),false,word);const at=s.indexOf('/Subtype /Image'),head=s.lastIndexOf('obj',at),stream=s.indexOf('stream\n',at)+7,end=s.indexOf('\nendstream',stream);assert.ok(head>=0);assert.deepEqual(zlib.inflateSync(b.subarray(stream,end)),p.rgb);assert.equal(r.sha256,crypto.createHash('sha256').update(b).digest('hex'));});
test('T022 all8fresh pages persist independent exactPage count with no text objects',async()=>{const m=await model,p=png(),r=await m.build(Array.from({length:8},()=>({width:16,height:20,widthPt:8,heightPt:10,png:p.bytes})));assert.equal(r.pageCount,8);assert.equal((Buffer.from(r.bytes).toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length,8);assert.equal(Buffer.from(r.bytes).includes(Buffer.from('BT')),false);});
test('T022 builder refuses originalPDF bytes, false raster identity unknown fields invalid and oversized input',async()=>{const m=await model,p=png(),valid={width:16,height:20,widthPt:8,heightPt:10,png:p.bytes};for(const pages of[[],Array(9).fill(valid),[{...valid,png:new Uint8Array(Buffer.from('%PDF-1.7\nSECRET'))}],[{...valid,width:17}],[{...valid,widthPt:NaN}],[{...valid,sourcePDF:'secret'}],[{...valid,png:new Uint8Array(10485761)}]])await assert.rejects(m.build(pages));});
test('T022 canonical complete binary reports include all100mask rows no original secret text',async()=>{const m=await model,report={format:'T022-raster-redaction-audit',rects:Array.from({length:100},(_,i)=>({id:i+1,page:1,x:0,y:i,width:2,height:1}))};assert.equal(JSON.parse(m.reportText(report,'json')).rects.at(-1).id,100);assert.ok(m.reportText(report,'md').includes('100'));assert.throws(()=>m.reportText(report,'html'));assert.throws(()=>m.reportText({x:'a'.repeat(1048576)},'json'));const b=new Uint8Array([0,1,255]);assert.deepEqual(Buffer.from(m.base64(b),'base64'),Buffer.from(b));});

class Element{
constructor(tag){this.nodeType=1;this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.events=new Map();this.style={};this.dataset={};this.classList={add(){},remove(){}};this.value='';this.disabled=false;this._text='';this.width=this.height=1;}
setAttribute(k,v){this.attributes[k]=String(v);if(k==='value')this.value=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}
getAttribute(k){return this.attributes[k];}append(...items){for(const item of items){item.parentNode=this;this.children.push(item);}}replaceChildren(...items){this.children=[];this._text='';this.append(...items);}addEventListener(t,f){this.events.set(t,f);}removeEventListener(t){this.events.delete(t);}emit(t,p={}){if(this.disabled)return;return this.events.get(t)?.({target:this,preventDefault(){},...p});}click(){return this.emit('click');}get textContent(){return this._text+this.children.map(c=>c.textContent||'').join('');}set textContent(v){this._text=String(v);this.children=[];}getContext(){return{};}
querySelectorAll(s){const nodes=this.children.flatMap(c=>c.nodeType===1?[c,...c.querySelectorAll('*')]:[]);return s==='*'?nodes:nodes.filter(n=>s.startsWith('[')?n.getAttribute(s.slice(1,s.indexOf('=')))===s.slice(s.indexOf('="')+2,-2):n.tagName===s.toUpperCase());}querySelector(s){return this.querySelectorAll(s)[0]||null;}
}
async function mount(options={}){
const m=await model,timers=new Map(),workers=[],saved=[],encodes=[],renders=[];let timerID=0;
class Canvas extends Element{getContext(){const self=this;function data(){if(!self.pixels||self.pixels.length!==self.width*self.height*4)self.pixels=new Uint8ClampedArray(self.width*self.height*4);return self.pixels;}return{fillRect(){data().fill(255);},getImageData(){return{data:data().slice(),width:self.width,height:self.height};},putImageData(image){self.pixels=new Uint8ClampedArray(image.data);}};}getBoundingClientRect(){return{left:0,top:0,width:this.width,height:this.height};}setPointerCapture(){}releasePointerCapture(){}toBlob(callback){const width=this.width,height=this.height,rgba=this.getContext().getImageData().data,head=Buffer.alloc(13);head.writeUInt32BE(width);head.writeUInt32BE(height,4);head[8]=8;head[9]=2;const scan=Buffer.concat(Array.from({length:height},(_,y)=>{const row=Buffer.alloc(1+width*3);for(let x=0;x<width;x++)for(let c=0;c<3;c++)row[1+x*3+c]=rgba[(y*width+x)*4+c];return row;})),bytes=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',zlib.deflateSync(scan)),chunk('IEND',Buffer.alloc(0))]),finish=()=>callback(new Blob([bytes],{type:'image/png'}));if(options.holdEncode)encodes.push(finish);else finish();}}
const root=new Element('div'),document={hidden:false,events:new Map(),createElement:t=>t==='canvas'?new Canvas(t):new Element(t),createTextNode:text=>({nodeType:3,textContent:String(text)}),addEventListener(t,f){this.events.set(t,f);},removeEventListener(t){this.events.delete(t);}};
const parser={getDocument(){return{destroy:async()=>{},promise:Promise.resolve({numPages:2,getPage:async n=>({rotate:n===2?90:0,view:[0,0,8,10],getViewport:({scale})=>({width:8*scale,height:10*scale}),render(){const r={cancel(){r.reject?.(Error('render canceled'));},promise:options.holdRender?new Promise((resolve,reject)=>{r.resolve=resolve;r.reject=reject;}):options.renderFailure?Promise.reject(Error('render fixture')):Promise.resolve()};renders.push(r);return r;},cleanup(){}}),destroy:async()=>{}})};}};
class WorkerMock{constructor(){workers.push(this);}terminate(){this.stopped=true;}postMessage(p){this.request=p;if(options.holdWorker)return;m.build(p.pages).then(result=>this.onmessage?.({data:{ok:true,result}}),e=>this.onmessage?.({data:{ok:false,error:e.message}}));}}
const files={saveBinarySupportsCopyOnly:options.capability!==false,saveTextSupportsCopyOnly:options.capability!==false};for(const method of['saveBinary','saveText'])files[method]=async p=>{saved.push({method,p});if(options.saveReply instanceof Error)throw options.saveReply;return options.saveReply==='undefined'?undefined:options.saveReply||{ok:true};};
const vm=require('node:vm'),context=vm.createContext({document,window:{toolbox:{files}},...m,TextEncoder,Uint8Array,Uint8ClampedArray,ArrayBuffer,URL,Blob,ImageData:class{constructor(data,width,height){this.data=data;this.width=width;this.height=height;}},crypto:crypto.webcrypto,setTimeout:(f,ms)=>{const id=++timerID;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),module:{exports:{}}});vm.runInContext(fs.readFileSync(path.resolve(folder,'../../core/ui.js'),'utf8').replace(/export /g,'')+'\nmodule.exports={h};',context);context.h=context.module.exports.h;vm.runInContext(fs.readFileSync(path.join(folder,'index.js'),'utf8').replace(/^import.*;\r?$/gm,'').replace('export default','module.exports=').replace(/import\.meta\.url/g,JSON.stringify(pathToFileURL(path.join(folder,'index.js')).href)),context);
const lifecycle=context.module.exports.create(root,{workerFactory:()=>new WorkerMock(),pdfjs:async()=>parser,config:{set(){assert.fail('No source PDF or bitmap in config');}}}),all=()=>[root,...root.querySelectorAll('*')],button=t=>all().find(e=>e.tagName==='BUTTON'&&e.textContent===t),field=l=>all().find(e=>e.getAttribute?.('aria-label')===l),tick=()=>new Promise(r=>setImmediate(r));
async function wait(){for(let i=0;i<3000;i++){if(!field('选择待遮盖PDF').disabled)return;await tick();}throw Error('UI did not settle');}async function select(){const bytes=new Uint8Array(Buffer.from('%PDFfixture'));field('选择待遮盖PDF').files=[{name:'source.pdf',size:bytes.length,arrayBuffer:async()=>bytes.slice().buffer}];field('选择待遮盖PDF').emit('change');await wait();}async function click(t){await button(t).click();await wait();}async function rectangle(){for(const[l,v]of[['遮盖X','1'],['遮盖Y','2'],['遮盖宽度','3'],['遮盖高度','4']])field(l).value=v;await click('添加当前页遮盖框');}function confirm(){field('已核对全部最终页与未遮盖内容').checked=true;field('已核对全部最终页与未遮盖内容').emit('change');}
lifecycle.activate();return{root,document,lifecycle,button,field,workers,saved,timers,encodes,renders,tick,wait,select,click,rectangle,confirm,text:()=>root.textContent};
}
const buildLabel='生成并预览全部纯图像PDF页',pdfLabel='另存永久遮盖纯图像PDF新副本',textLabel='另存当前遮盖审计新副本';
test('T022 UI explicit source and pointer/numeric masks final all-page review checkbox gate, edit invalidates',async()=>{const ui=await mount();assert.equal(ui.workers.length,0);assert.equal(ui.button(buildLabel).disabled,true);await ui.select();const c=ui.field('框选遮盖区域的页面');c.emit('pointerdown',{button:0,pointerId:1,clientX:1.2,clientY:2.4});c.emit('pointerup',{button:0,pointerId:1,clientX:5.3,clientY:6.8});await ui.click(buildLabel);const audit=JSON.parse(ui.field('完整遮盖审计报告').textContent);assert.deepEqual(audit.rects.map(({x,y,width,height})=>[x,y,width,height]),[[1,2,5,5]]);assert.equal(ui.field('完整最终纯图像PDF预览').querySelectorAll('canvas').length,2);assert.equal(ui.button(pdfLabel).disabled,true);ui.confirm();assert.equal(ui.button(pdfLabel).disabled,false);await ui.click('删除遮盖框 R1');assert.equal(ui.field('完整遮盖审计报告').textContent,'');assert.equal(ui.button(pdfLabel).disabled,true);assert.equal(ui.field('已核对全部最终页与未遮盖内容').checked,false);ui.lifecycle.destroy();});
test('T022 UI source identity hashes full reports and binary copyOnly, strict all save replies',async()=>{for(const saveReply of[{ok:true},{ok:false,error:'EEXIST'},'undefined',{canceled:true},Error('fixture')]){const ui=await mount({saveReply});await ui.select();await ui.rectangle();await ui.click(buildLabel);ui.confirm();const report=JSON.parse(ui.field('完整遮盖审计报告').textContent);await ui.click(pdfLabel);const b=ui.saved[0].p;assert.equal(b.copyOnly,true);assert.equal(b.sha256,report.output.sha256);assert.equal(crypto.createHash('sha256').update(Buffer.from(b.base64,'base64')).digest('hex'),b.sha256);assert.equal(ui.text().includes('新副本保存成功'),saveReply?.ok===true);for(const ext of['JSON','Markdown']){await ui.click('预览完整'+ext+'遮盖审计');const text=ui.field('完整遮盖审计报告').textContent;await ui.click(textLabel);assert.equal(ui.saved.at(-1).p.copyOnly,true);assert.equal(ui.saved.at(-1).p.content,text);assert.equal(ui.field('完整遮盖审计报告').textContent,text);}ui.lifecycle.destroy();}});
test('T022 UI absent copyOnly capability disables exports while audit remains usable',async()=>{const ui=await mount({capability:false});await ui.select();await ui.rectangle();await ui.click(buildLabel);ui.confirm();assert.equal(ui.button(pdfLabel).disabled,true);assert.equal(ui.button(textLabel).disabled,true);assert.equal(ui.saved.length,0);assert.equal(JSON.parse(ui.field('完整遮盖审计报告').textContent).pages.length,2);ui.lifecycle.destroy();});
test('T022 UI malformed numeric bounds whole reject no stale results or extra mask',async()=>{const ui=await mount();await ui.select();await ui.rectangle();await ui.click(buildLabel);ui.field('遮盖宽度').value='99';await ui.click('添加当前页遮盖框');assert.ok(ui.text().includes('遮盖框拒绝'));assert.equal(JSON.parse(ui.field('完整遮盖审计报告').textContent).rects.length,1);ui.field('遮盖宽度').value='01';await ui.click('添加当前页遮盖框');assert.ok(ui.text().includes('十进制整数'));ui.lifecycle.destroy();});
test('T022 UI cancel late PNG encoding callback ignored, no worker or report starts',async()=>{const ui=await mount({holdEncode:true});await ui.select();await ui.rectangle();const pending=ui.button(buildLabel).click();assert.equal(ui.encodes.length,1);await ui.button('取消本次遮盖处理').click();ui.encodes[0]();await pending;await ui.wait();assert.equal(ui.workers.length,0);assert.equal(ui.field('完整遮盖审计报告').textContent,'');assert.equal(ui.button(pdfLabel).disabled,true);ui.lifecycle.destroy();});
test('T022 UI worker30second deadline kills worker and keeps no completed output',async()=>{const ui=await mount({holdWorker:true});await ui.select();await ui.rectangle();const pending=ui.button(buildLabel).click();for(let i=0;i<3000&&!ui.workers.length;i++)await ui.tick();assert.equal(ui.timers.size,1);const t=[...ui.timers.values()][0];assert.equal(t.ms,30000);t.f();await pending;await ui.wait();assert.equal(ui.workers[0].stopped,true);assert.ok(ui.text().includes('超过30秒'));assert.equal(ui.timers.size,0);assert.equal(ui.button(pdfLabel).disabled,true);ui.lifecycle.destroy();});
test('T022 UI failed source rendering gives no partial source canvas controls',async()=>{const ui=await mount({renderFailure:true});await ui.select();assert.ok(ui.text().includes('来源拒绝'));assert.equal(ui.field('遮盖页码').children.length,0);assert.equal(ui.button(buildLabel).disabled,true);assert.equal(ui.timers.size,0);ui.lifecycle.destroy();});
test('T022 UI leave during build terminates old worker and ignores response, source/bitmap cleared',async()=>{const ui=await mount({holdWorker:true});await ui.select();await ui.rectangle();const pending=ui.button(buildLabel).click();for(let i=0;i<3000&&!ui.workers.length;i++)await ui.tick();const w=ui.workers[0];ui.lifecycle.deactivate();await pending;assert.equal(w.stopped,true);assert.equal(ui.field('遮盖页码').children.length,0);assert.equal(ui.field('框选遮盖区域的页面').width,1);w.onmessage({data:{ok:true,result:{}}});await ui.tick();ui.lifecycle.activate();assert.equal(ui.button(buildLabel).disabled,true);assert.equal(ui.field('完整遮盖审计报告').textContent,'');assert.equal(ui.timers.size,0);ui.lifecycle.destroy();assert.equal(ui.document.events.size,0);assert.equal(ui.root.children.length,0);});
