const test = require('node:test'); const assert = require('node:assert/strict'); const model = () => import('../src/renderer/features/L028/model.mjs');
test('L028 核心Aset x1 BassertMissing独跑过A→B败且定位x/A#1', async () => { const m = await model(), r = m.analyze(m.example()); assert.deepEqual(r.isolated.map(row => row.passed), [true, true]); assert.deepEqual(r.shared.map(row => row.passed), [true, false]); assert.deepEqual(r.summary, { tests: 2, pairs: 2, isolatedFailed: 0, sharedFailed: 1, newlyFailingTests: 1, introducedAssertions: 1 }); assert.equal(r.earliestDifferenceFailure.key, 'x'); assert.equal(r.earliestDifferenceFailure.source.first.test, 'A'); assert.equal(r.earliestDifferenceFailure.source.last.step, 1); assert.deepEqual(r.shared[1].initialDiff, [{ key: 'x', before: { exists: false }, after: { exists: true, value: 1 } }]); });
test('L028 反序B→A共享全过，但有向矩阵独立保持A→B败', async () => { const m = await model(), r = m.analyze({ ...m.example(), order: 'B A' }); assert.equal(r.summary.sharedFailed, 0); assert.equal(r.earliestDifferenceFailure, null); assert.deepEqual(r.pairs.map(pair => [pair.from, pair.to, pair.target.passed]), [['A', 'B', false], ['B', 'A', true]]); assert.deepEqual(r.final, { x: 1 }); });
test('L028 断言失败后继续delete，前序败但后序不受污染', async () => { const m = await model(), r = m.analyze(m.example('cleanup')); assert.equal(r.shared[0].passed, false); assert.equal(r.shared[0].trace.length, 3); assert.equal(r.shared[0].trace[1].assertion.passed, false); assert.equal(r.shared[0].trace[2].op, 'delete'); assert.deepEqual(r.shared[0].final, {}); assert.equal(r.shared[1].passed, true); assert.equal(r.pairs[0].source.passed, false); assert.equal(r.pairs[0].target.passed, true); assert.equal(r.summary.newlyFailingTests, 0); });
test('L028 独跑自有失败不直接归因污染，状态差异仍展示', async () => { const m = await model(), r = m.analyze(m.example('ownbug')); assert.equal(r.isolated[1].passed, false); assert.equal(r.shared[1].passed, false); assert.equal(r.summary.newlyFailingTests, 0); assert.match(r.shared[1].classification, /不能直接归因/); assert.equal(r.shared[1].assertionDifferences.length, 1); assert.equal(r.shared[1].introducedFailures.length, 0); });
test('L028 前序状态也可掩盖独跑失败，不能当修复证明', async () => { const m = await model(), draft = m.example(); draft.tests[1].operations = 'assertEqual x 1'; const r = m.analyze(draft); assert.equal(r.isolated[1].passed, false); assert.equal(r.shared[1].passed, true); assert.match(r.shared[1].classification, /被掩盖/); assert.equal(r.summary.newlyFailingTests, 0); });
test('L028 来源首次A最近C覆盖、delete/reset后新一代来源', async () => { const m = await model(), r = m.analyze(m.example('overwrite')); const s = r.earliestDifferenceFailure.source; assert.equal(s.first.test, 'A'); assert.equal(s.last.test, 'C'); assert.equal(r.earliestDifferenceFailure.shared.actual.value, 2); const d = m.example('overwrite'); d.tests[1].operations = 'delete x\nset x 2'; const next = m.analyze(d); assert.equal(next.earliestDifferenceFailure.source.first.test, 'C'); assert.equal(next.earliestDifferenceFailure.source.first.step, 2); d.tests[1].operations = 'reset\nset x 2'; assert.equal(m.analyze(d).earliestDifferenceFailure.source.first.test, 'C'); });
test('L028 reset清全部/delete不存在无操作，失败断言不改变状态', async () => { const m = await model(); const d = { order: 'A B', tests: [{ id: 'A', operations: 'set x 1\nset y "hi"\nassertEqual x false\nreset\ndelete x' }, { id: 'B', operations: 'assertMissing x\nassertMissing y' }] }; const r = m.analyze(d); assert.equal(r.shared[1].passed, true); assert.deepEqual(r.shared[0].trace[2].before, r.shared[0].trace[2].after); assert.equal(r.shared[0].trace[3].changes.length, 2); assert.equal(r.shared[0].trace[4].changes.length, 0); });
test('L028 assertEqual要求存在和类型相同，空字符串/false/0不是缺失', async () => { const m = await model(); for (const [set, expected, passed] of [['0', 'false', false], ['false', 'false', true], ['"1"', '1', false], ['""', '""', true]]) { const d = m.example(); d.tests[0].operations = `set x ${set}\nassertEqual x ${expected}\nassertMissing x`; const r = m.analyze(d); assert.equal(r.isolated[0].trace[1].assertion.passed, passed); assert.equal(r.isolated[0].trace[2].assertion.passed, false); } const d = m.example(); d.tests[0].operations = 'assertEqual x 0'; assert.equal(m.analyze(d).isolated[0].passed, false); });
test('L028 六测试有向30格独立oracle，未枚举全720排列', async () => { const m = await model(); const tests = Array.from({ length: 6 }, (_, i) => ({ id: `T${i}`, operations: i < 3 ? `set x ${i}` : 'assertMissing x' })); const r = m.analyze({ order: tests.map(t => t.id).join(' '), tests }); assert.equal(r.pairs.length, 30); assert.equal(r.summary.sharedFailed, 3); for (const pair of r.pairs) { const source = Number(pair.from.slice(1)), target = Number(pair.to.slice(1)); assert.equal(pair.target.passed, !(source < 3 && target >= 3)); assert.deepEqual(pair.source.initial, {}); } assert.equal(r.summary.newlyFailingTests, 3); });
test('L028 六测试各8操作完整576steps有界输出，不截断轨迹', async () => { const m = await model(); const tests = Array.from({ length: 6 }, (_, i) => ({ id: `T${i}`, operations: Array.from({ length: 8 }, (_, j) => `set k${i}_${j} "${'汉'.repeat(64)}"`).join('\n') })); const r = m.analyze({ order: tests.map(t => t.id).join(' '), tests }); assert.equal(Object.keys(r.final).length, 48); assert.equal(r.shared.at(-1).trace.at(-1).runStep, 48); const steps = [...r.isolated, ...r.shared, ...r.pairs.flatMap(pair => [pair.source, pair.target])].reduce((n, row) => n + row.trace.length, 0); assert.equal(steps, 576); assert.ok(JSON.stringify(r).length < 30 * 1024 * 1024); });
test('L028 未知操作/代码/null/对象/原型key和ID/重复ID/order拒绝', async () => { const m = await model(); for (const operations of ['eval(1)', 'Set x 1', 'set x null', 'set x {}', 'set x [1]', 'set x 1.5', 'set x 1e3', 'set x NaN', 'set x 1; process.exit()', 'set constructor 1', 'set __proto__ 1', 'assertMissing x 1', 'delete x y', 'reset x', 'set x', 'set x "bad']) { const d = m.example(); d.tests[0].operations = operations; assert.throws(() => m.analyze(d)); } for (const order of ['A A', 'A Unknown', 'A', 'A B C', 'null A']) assert.throws(() => m.analyze({ ...m.example(), order })); const duplicate = m.example(); duplicate.tests[1].id = 'A'; assert.throws(() => m.analyze(duplicate), /重复测试/); for (const id of [null, 'prototype', '汉', '0123', 'toolongabcdefg']) { const d = m.example(); d.tests[0].id = id; assert.throws(() => m.analyze(d)); } });
test('L028 DSL容量/值边界/空行拒绝，标准JSON转义字符串接受', async () => { const m = await model(); for (const operations of ['', 'set x 1\n\nreset', Array(9).fill('reset').join('\n'), 'set x ' + '1'.repeat(2048), 'set x 1000000001', 'set x "' + 'a'.repeat(65) + '"', 'set x "\\ud800"']) { const d = m.example(); d.tests[0].operations = operations; assert.throws(() => m.analyze(d)); } const d = m.example(); d.tests[0].operations = 'set x "a\\n\\u263a"\nassertEqual x "a\\n☺"'; assert.equal(m.analyze(d).isolated[0].passed, true); assert.throws(() => m.analyze({ order: 'A', tests: [d.tests[0]] }), /2–6/); assert.throws(() => m.analyze({ order: '', tests: Array(7).fill(d.tests[0]) }), /2–6/); assert.throws(() => m.analyze({ ...d, order: 'x'.repeat(129) }), /128/); });
test('L028 多断言既有bug和新增差异失败分别计，最早按共享step', async () => { const m = await model(); const d = m.example(); d.tests[1].operations = 'assertEqual y 1\nassertMissing x\nassertMissing x'; const r = m.analyze(d); assert.equal(r.summary.newlyFailingTests, 0); assert.equal(r.summary.introducedAssertions, 2); assert.equal(r.earliestDifferenceFailure.step, 2); assert.equal(r.earliestDifferenceFailure.runStep, 3); assert.equal(r.shared[1].failedAssertions, 3); });
test('L028 快照互不污染、重算确定性、版本raw64KiB和完整MD', async () => { const m = await model(), d = m.example(), before = structuredClone(d), r = m.analyze(d); assert.deepEqual(d, before); assert.deepEqual(r, m.analyze(d)); r.shared[0].final.x = 999; assert.equal(r.shared[1].initial.x, 1); assert.equal(r.pairs[0].source.final.x, 1); const state = m.prepareStoredState(d); assert.deepEqual(m.validateStoredState(state), state); assert.equal(Object.hasOwn(state, 'result'), false); assert.throws(() => m.validateStoredState({ ...state, schemaVersion: 2 }), /版本/); assert.throws(() => m.validateStoredState({ ...state, hidden: '汉'.repeat(22000) }), /64KiB/); assert.throws(() => m.prepareStoredState({ ...d, tests: [{ ...d.tests[0], operations: '汉'.repeat(1000) }, d.tests[1]] }), /2048/); const payload = JSON.parse(JSON.stringify({ draft: d, result: m.analyze(d) })); assert.deepEqual(payload.result, m.analyze(payload.draft)); const md = m.reportMarkdown(payload); assert.match(md, /"from": "A"/); assert.match(md, /"to": "B"/); assert.match(md, /assertMissing x/); assert.match(m.reportMarkdown({ draft: d, result: null }), /尚无有效/); assert.doesNotMatch(m.reportMarkdown({ draft: { ...d, order: '<script>' }, result: null }), /<script>/); });
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

test('L028 真实组件默认分析→有向矩阵→完整导出→反序', async t => {
  const saved = []; dom(t, { saveTextSupportsCopyOnly: true, saveText: async payload => { saved.push(payload); return { ok: true }; } }); const root = new NodeStub('main'), handle = (await import('../src/renderer/features/L028/index.js')).default.create(root); t.after(() => handle.destroy());
  await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('独跑失败0/2 · 共享失败1/2')); assert.ok(root.textContent.includes('测试B#1，键x')); assert.ok(root.textContent.includes('首次来源 A#1'));
  await button(root, '查看 A→B').fire('click'); assert.ok(root.textContent.includes('后序继承前序最终状态')); await button(root, '查看独跑B').fire('click'); assert.ok(root.textContent.includes('独跑基线完整轨迹'));
  await button(root, '导出完整 JSON').fire('click'); await button(root, '导出完整 Markdown').fire('click'); const r = JSON.parse(saved[0].content).result; assert.equal(r.pairs.length, 2); assert.equal(r.shared[1].passed, false); assert.equal(saved[0].copyOnly, true); assert.match(saved[1].content, /"from": "A"/);
  await fill(root, '共享运行顺序', 'B A'); assert.ok(root.textContent.includes('尚无有效矩阵')); await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('共享失败0/2')); await button(root, '查看 A→B').fire('click'); assert.ok(root.textContent.includes('独跑通过→共享失败'));
});
test('L028 组件cleanup/独跑bug/来源覆盖模板与轨迹选择', async t => {
  dom(t, {}); const root = new NodeStub('main'), handle = (await import('../src/renderer/features/L028/index.js')).default.create(root); t.after(() => handle.destroy());
  await button(root, '载入失败后清理示例').fire('click'); await button(root, '分析隔离与共享').fire('click'); await button(root, '查看 A→B').fire('click'); assert.ok(root.textContent.includes('后序通过 / 前序失败')); assert.ok(root.textContent.includes('delete x')); assert.ok(root.textContent.includes('新增失败测试0'));
  await button(root, '载入独跑失败示例').fire('click'); await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('不能直接归因污染'));
  await button(root, '载入来源覆盖示例').fire('click'); await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('首次来源 A#1；最近修改 C#1')); assert.ok(root.textContent.includes('有向对6'));
});
test('L028 组件增删编辑到6测试30有向格，错误顺序清结果', async t => {
  dom(t, {}); const root = new NodeStub('main'), handle = (await import('../src/renderer/features/L028/index.js')).default.create(root); t.after(() => handle.destroy());
  for (let i = 0; i < 4; i++) await button(root, '增加测试').fire('click'); assert.equal(button(root, '增加测试').disabled, true); await button(root, '分析隔离与共享').fire('click'); assert.equal(walk(root).filter(node => node.tagName === 'button' && /^查看 .+→/.test(node.textContent)).length, 30);
  await fill(root, '测试3操作', 'reset\nassertMissing x'); await button(root, '分析隔离与共享').fire('click'); await button(root, '查看共享T1').fire('click'); assert.ok(root.textContent.includes('reset'));
  await button(root, '删除测试6').fire('click'); assert.equal(control(root, '共享运行顺序').value, 'A B T1 T2 T3'); await fill(root, '共享运行顺序', 'A A'); await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('重复ID')); assert.ok(root.textContent.includes('尚无有效矩阵'));
});
test('L028 组件用户DSL按文本显示，代码与原型键拒绝，不执行HTML', async t => {
  dom(t, {}); const root = new NodeStub('main'), handle = (await import('../src/renderer/features/L028/index.js')).default.create(root); t.after(() => handle.destroy());
  await fill(root, '测试1操作', 'set x "<script>"'); await fill(root, '测试2操作', 'assertEqual x "<script>"'); await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('<script>'));
  for (const input of ['set constructor 1', 'process.exit()', 'set x null']) { await fill(root, '测试1操作', input); await button(root, '分析隔离与共享').fire('click'); assert.ok(root.textContent.includes('尚无有效矩阵')); }
});
test('L028 严格copyOnly能力/ok/取消/异常与销毁后导出回调', async t => {
  dom(t, {}); const root = new NodeStub('main'), handle = (await import('../src/renderer/features/L028/index.js')).default.create(root); t.after(() => handle.destroy()); await button(root, '导出完整 JSON').fire('click'); assert.ok(root.textContent.includes('缺少防覆盖'));
  global.window.toolbox.files = { saveTextSupportsCopyOnly: true, saveText: async () => ({ ok: 'true' }) }; await button(root, '导出完整 JSON').fire('click'); assert.ok(root.textContent.includes('未确认保存成功'));
  global.window.toolbox.files.saveText = async () => ({ canceled: true }); await button(root, '导出完整 JSON').fire('click'); assert.ok(root.textContent.includes('已取消'));
  global.window.toolbox.files.saveText = async () => ({ ok: false, error: 'EEXIST' }); await button(root, '导出完整 JSON').fire('click'); assert.ok(root.textContent.includes('EEXIST'));
  let resolve; global.window.toolbox.files.saveText = () => new Promise(done => { resolve = done; }); const pending = button(root, '导出完整 JSON').fire('click'); handle.destroy(); resolve({ ok: true }); await pending; assert.equal(root.children.length, 0);
});
test('L028 lifecycle清计时器、草稿有界恢复、超限不保存、无结果持久化', async t => {
  const oldSet = global.setTimeout, oldClear = global.clearTimeout, timers = new Map(); let serial = 0; global.setTimeout = callback => { timers.set(++serial, callback); return serial; }; global.clearTimeout = id => timers.delete(id); t.after(() => { global.setTimeout = oldSet; global.clearTimeout = oldClear; }); dom(t, {});
  const saved = [], feature = (await import('../src/renderer/features/L028/index.js')).default, root = new NodeStub('main'), handle = feature.create(root, { config: { set: (_key, state) => saved.push(structuredClone(state)) } });
  await fill(root, '共享运行顺序', 'B A'); assert.equal(timers.size, 1); handle.deactivate(); assert.equal(timers.size, 0); assert.equal(saved.at(-1).order, 'B A'); await button(root, '分析隔离与共享').fire('click'); assert.equal(Object.hasOwn(saved.at(-1), 'result'), false);
  const count = saved.length; await fill(root, '测试1操作', '汉'.repeat(1000)); handle.deactivate(); assert.equal(saved.length, count); assert.ok(root.textContent.includes('未写入全局配置')); handle.destroy(); assert.equal(timers.size, 0); assert.equal(root.children.length, 0);
  for (const [raw, text] of [[saved.at(-1), '已恢复'], [{ schemaVersion: 2 }, '草稿未恢复'], [{ ...(await model()).prepareStoredState((await model()).example()), hidden: 'x'.repeat(65536) }, '草稿未恢复']]) { const fresh = new NodeStub('main'), instance = feature.create(fresh, { config: { get: () => raw } }); assert.ok(fresh.textContent.includes(text)); assert.ok(fresh.textContent.includes('尚无有效矩阵')); instance.destroy(); }
});
