const test=require('node:test'),assert=require('node:assert/strict'),model=import('../src/renderer/features/T086/model.mjs');
test('T086 adds meters and centimeters and rejects length/time addition',async()=>{const{calculate}=await model;assert.equal(calculate('1米 + 100厘米','米').value,2);assert.throws(()=>calculate('1m+1s'),/量纲不一致/);});
test('T086 distance/time converts to km/h with derived dimensions',async()=>{const{calculate}=await model,r=calculate('100m / 10s','km/h');assert.equal(r.value,36);assert.deepEqual(r.dimensions,[1,0,-1]);});
test('T086 area, volume and energy honor integer powers and derived SI units',async()=>{const{calculate}=await model;assert.equal(calculate('2m * 3m','m^2').value,6);assert.equal(calculate('2m^2','m2').value,2);assert.equal(calculate('(2m)^2','m2').value,4);assert.equal(calculate('1L + 500mL','m3').value,.0015);assert.equal(calculate('2 kg * (3 m / 1 s)^2','J').value,18);assert.equal(calculate('1W * 60s','J').value,60);});
test('T086 precedence and unary signs are deterministic without evaluation',async()=>{const{calculate}=await model;assert.equal(calculate('-2^2 + 3 * 4','1').value,8);assert.equal(calculate('(2m + 100cm) / 3s','m/s').value,1);assert.equal(calculate('1s^-1','Hz').value,1);});
test('T086 unknown units, assignments, function calls and non-integer powers are rejected',async()=>{const{calculate}=await model;for(const input of ['process.exit()','1°C','x=1','1m^0.5','1m^7','2(3m)','1m 2s'])assert.throws(()=>calculate(input));});
test('T086 wrong target dimensions and non-unit target coefficients are rejected',async()=>{const{calculate}=await model;assert.throws(()=>calculate('1m','s'),/目标量纲/);assert.throws(()=>calculate('1m','2m'),/目标单位/);assert.throws(()=>calculate('1m','-m'));assert.throws(()=>calculate('1m','m+cm'));});
test('T086 zero divisors, negative powers of zero, overflow and parser limits refuse unsafe results',async()=>{const{calculate}=await model;for(const input of ['1m/0s','0^-1','1e12^6','('.repeat(17)+'1'+')'.repeat(17),'1+'.repeat(130)+'1','1'.repeat(1201)])assert.throws(()=>calculate(input));});
test('T086 compound target, dimensionless cancellation and report retain full operation trace',async()=>{const{calculate,reportMarkdown}=await model;const r=calculate('1 km / 1000 m','scalar');assert.equal(r.value,1);assert.deepEqual(r.dimensions,[0,0,0]);assert.ok(r.steps.length>=3);assert.match(reportMarkdown(r),/量纲\[m,kg,s\]：0,0,0/);});
