const test = require('node:test');
const assert = require('node:assert/strict');
const model = () => import('../src/renderer/features/L019/model.mjs');
function independent(root){const values=[];const depths=[];function visit(n,min,max,d){assert.ok(n.keys.length===1||n.keys.length===2);assert.ok(n.keys.every((v,i)=>v>min&&v<max&&(i===0||n.keys[i-1]<v)));if(!n.children.length){depths.push(d);values.push(...n.keys);return;}assert.equal(n.children.length,n.keys.length+1);n.keys.forEach((key,i)=>{visit(n.children[i],i? n.keys[i-1]:min,key,d+1);values.push(key);});visit(n.children.at(-1),n.keys.at(-1),max,d+1);}visit(root,-Infinity,Infinity,0);assert.equal(new Set(depths).size,1);return values;}
test('L019 核心10/20/30中位根与左右叶',async()=>{const{buildTree,example}=await model();const r=buildTree(example());assert.deepEqual(r.finalTree.keys,[20]);assert.deepEqual(r.finalTree.children.map(c=>c.keys),[[10],[30]]);assert.deepEqual(r.finalTree.children.map(c=>c.children),[[],[]]);assert.equal(r.finalCheck.leafDepth,1);assert.equal(r.finalCheck.height,2);assert.deepEqual(independent(r.finalTree),[10,20,30]);});
test('L019 核心包含分裂前/三键暂态/提升后/完成独立帧',async()=>{const{buildTree,example}=await model();const r=buildTree(example());const rows=r.frames.filter(f=>f.key===30);assert.deepEqual(rows.map(f=>f.phase),['before','overflow','split','complete']);assert.deepEqual(rows[0].tree.keys,[10,20]);assert.deepEqual(rows[1].tree.keys,[10,20,30]);assert.equal(rows[1].check.stable,false);assert.equal(rows[2].split.median,20);assert.equal(rows[2].split.rootSplit,true);assert.equal(rows[3].check.stable,true);});
test('L019 单键与两个键不分裂，负数和0保留',async()=>{const{buildTree}=await model();const one=buildTree({sequence:'0'});assert.deepEqual(one.finalTree.keys,[0]);assert.equal(one.finalCheck.leafDepth,0);const two=buildTree({sequence:'0 -1'});assert.deepEqual(two.finalTree.keys,[-1,0]);assert.equal(two.frames.some(f=>f.split),false);});
test('L019 1..7父递归分裂独立手算树',async()=>{const{buildTree,example}=await model();const r=buildTree(example('cascade'));assert.deepEqual(r.finalTree.keys,[4]);assert.deepEqual(r.finalTree.children.map(c=>c.keys),[[2],[6]]);assert.deepEqual(r.finalTree.children.flatMap(c=>c.children.map(leaf=>leaf.keys)),[[1],[3],[5],[7]]);assert.equal(r.finalCheck.leafDepth,2);const seven=r.frames.filter(f=>f.key===7);assert.equal(seven.filter(f=>f.split).length,2);assert.ok(seven.some(f=>f.split&&!f.split.rootSplit&&!f.check.stable));});
test('L019 中间子树插入与下降范围跟踪',async()=>{const{buildTree}=await model();const r=buildTree({sequence:'10 20 30 25'});assert.deepEqual(r.finalTree.keys,[20]);assert.deepEqual(r.finalTree.children.map(c=>c.keys),[[10],[25,30]]);const descent=r.frames.find(f=>f.key===25&&f.phase==='descend');assert.match(descent.reason,/第2个孩子/);assert.equal(descent.focus.length,2);});
test('L019 每帧检查暂态容量，完成帧严格通过',async()=>{const{buildTree,example,checkTree}=await model();const r=buildTree(example('mixed'));for(const frame of r.frames){assert.equal(frame.check.ok,true);assert.deepEqual(checkTree(frame.tree,{allowOverflow:true}),frame.check);if(frame.check.stable)assert.equal(checkTree(frame.tree).stable,true);else{assert.equal(frame.check.overflowNodeIds.length,1);assert.throws(()=>checkTree(frame.tree),/键数/);}}for(const item of r.insertions)assert.equal(item.check.keyCount,r.insertions.indexOf(item)+1);});
test('L019 排序/范围/孩子数/叶同深/ID故障可被独立拒绝',async()=>{const{checkTree}=await model();const leaf=(id,keys)=>({id,keys,children:[]});for(const tree of [leaf(1,[]),leaf(1,[2,1]),leaf(1,[1,1]),{id:1,keys:[2],children:[leaf(2,[1])]}, {id:1,keys:[2],children:[leaf(2,[3]),leaf(3,[4])]}, {id:1,keys:[2],children:[leaf(2,[1]),leaf(2,[3])]}, {id:1,keys:[2],children:[leaf(2,[1]),{id:3,keys:[4],children:[leaf(4,[3]),leaf(5,[5])]}]}])assert.throws(()=>checkTree(tree));assert.deepEqual(checkTree(null),{ok:true,stable:true,keyCount:0,leafDepth:0,height:0,overflowNodeIds:[]});});
test('L019 不允许两个同时溢出节点',async()=>{const{checkTree}=await model();const n=(id,keys)=>({id,keys,children:[]});assert.throws(()=>checkTree({id:1,keys:[5],children:[n(2,[1,2,3]),n(3,[6,7,8])]},{allowOverflow:true}),/单个/);});
test('L019 重复整数明确拒绝，不隐式去重',async()=>{const{parseSequence}=await model();for(const seq of ['1 1','0 -0','01 1','1,2,1'])assert.throws(()=>parseSequence(seq),/重复键/);});
test('L019 严格语法/数值域/输入类型拒绝代码',async()=>{const{parseSequence}=await model();for(const seq of ['', '1e2','1.5','Infinity','1+2','console.log(1)','[1,2]','1000001','-1000001',null,[],false])assert.throws(()=>parseSequence(seq));assert.deepEqual(parseSequence(' -1000000，0\n1000000 '),[-1000000,0,1000000]);assert.throws(()=>parseSequence(' '.repeat(4097)),/4096/);});
test('L019 64键升降序完整，65键拒绝不截断',async()=>{const{buildTree}=await model();for(const seq of [Array.from({length:64},(_,i)=>i),Array.from({length:64},(_,i)=>63-i)]){const r=buildTree({sequence:seq.join(' ')});assert.equal(r.finalCheck.keyCount,64);assert.ok(r.frames.length<1024);assert.deepEqual(independent(r.finalTree),Array.from({length:64},(_,i)=>i));assert.equal(r.frames.at(-1).phase,'complete');}assert.throws(()=>buildTree({sequence:Array.from({length:65},(_,i)=>i).join(' ')}),/64/);});
test('L019 20个确定性随机排列由独立遍历校验每次完成树',async()=>{const{buildTree}=await model();for(let seed=1;seed<=20;seed++){const keys=Array.from({length:32},(_,i)=>i-16);let x=seed;for(let i=31;i>0;i--){x=(x*1664525+1013904223)>>>0;const j=x%(i+1);[keys[i],keys[j]]=[keys[j],keys[i]];}const r=buildTree({sequence:keys.join(',')});for(let i=0;i<32;i++)assert.deepEqual(independent(r.insertions[i].tree),keys.slice(0,i+1).sort((a,b)=>a-b));}});
test('L019 输入、帧、每次完成及最终树独立且确定',async()=>{const{buildTree,example}=await model();const draft=example();const original=structuredClone(draft);const r=buildTree(draft);assert.deepEqual(r,buildTree(draft));assert.deepEqual(draft,original);r.frames.at(-1).tree.keys[0]=999;assert.deepEqual(r.finalTree.keys,[20]);assert.deepEqual(r.insertions.at(-1).tree.keys,[20]);draft.sequence='7';assert.equal(r.input.sequence,'10, 20, 30');});
test('L019 草稿schema/raw64KiB/UTF8/4096边界校验',async()=>{const{prepareStoredState,validateStoredState,example}=await model();const exact=prepareStoredState({sequence:'汉'.repeat(1365)+'a'});assert.equal(new TextEncoder().encode(exact.sequence).byteLength,4096);assert.deepEqual(validateStoredState(exact),exact);assert.throws(()=>prepareStoredState({sequence:exact.sequence+'a'}),/4096/);assert.throws(()=>prepareStoredState({sequence:'汉'.repeat(22000)}),/64KiB/);assert.throws(()=>validateStoredState({...prepareStoredState(example()),hidden:'汉'.repeat(22000)}),/64KiB/);assert.throws(()=>validateStoredState({schemaVersion:2}),/版本/);assert.throws(()=>validateStoredState({schemaVersion:1,sequence:1}),/字段类型/);});
test('L019 完整JSON可重算，Markdown含暂态/提升/完成与HTML转义',async()=>{const{buildTree,example,reportMarkdown}=await model();const draft=example('cascade');const r=buildTree(draft);const exported=JSON.parse(JSON.stringify({draft,result:r,selected:0}));assert.deepEqual(buildTree(exported.draft),exported.result);const md=reportMarkdown(exported);assert.match(md,/溢出暂态/);assert.match(md,/提升4/);assert.match(md,/完整模型记录/);assert.match(md,/complete/);assert.match(md,/当前界面查看帧为1/);const raw=reportMarkdown({draft:{sequence:'<script>alert(1)</script>'},result:null});assert.doesNotMatch(raw,/<script>/);assert.match(raw,/&lt;script&gt;/);assert.match(raw,/尚未生成/);});
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

test('L019 实际组件核心逐次插入/暂态图节点/末帧与完整副本',async(t)=>{
  const exported=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async(payload)=>{exported.push(payload);return{ok:true};}});const{default:feature}=await import('../src/renderer/features/L019/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'生成 / 重置演示').fire('click');assert.match(root.textContent,/空树：尚未插入/);await button(root,'完成下一次插入').fire('click');await button(root,'完成下一次插入').fire('click');await button(root,'下一帧').fire('click');assert.match(root.textContent,/第3次插入 30 · 插入前/);await button(root,'下一帧').fire('click');assert.match(root.textContent,/3键溢出暂态，不是有效2-3树/);assert.equal(walk(root).filter(n=>n.className.includes('l019-node')&&n.className.includes('is-overflow')).length,1);await button(root,'下一帧').fire('click');assert.match(root.textContent,/本步提升中间键20/);await button(root,'下一帧').fire('click');assert.equal(button(root,'下一帧').disabled,true);const nodeLabels=walk(root).filter(n=>n.className.includes('l019-node')).map(n=>n.attributes['aria-label']);assert.deepEqual(nodeLabels,['节点3，键20，2个孩子','节点1，键10，0个孩子','节点2，键30，0个孩子']);
  await button(root,'导出完整 JSON').fire('click');const payload=JSON.parse(exported[0].content);assert.equal(payload.schemaVersion,1);assert.deepEqual(payload.result.finalTree.keys,[20]);assert.equal(exported[0].copyOnly,true);await button(root,'导出完整 Markdown').fire('click');assert.match(exported[1].content,/根分裂：提升20/);assert.equal(exported[1].copyOnly,true);assert.doesNotMatch(root.textContent,/\[object Object\]|null/);
});
test('L019 UI真实序列编辑/模板/帧选择/重置清旧结果',async(t)=>{
  dom(t,{});const{default:feature}=await import('../src/renderer/features/L019/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'载入父递归分裂示例').fire('click');await button(root,'生成 / 重置演示').fire('click');await button(root,'查看末帧').fire('click');assert.match(root.textContent,/最终树高3/);await button(root,'查看插入3完成帧').fire('click');assert.match(root.textContent,/当前帧已完成3次插入/);await fill(root,'查看演示帧','0');assert.match(root.textContent,/空树：/);await button(root,'查看末帧').fire('click');await button(root,'上一帧').fire('click');assert.equal(button(root,'下一帧').disabled,false);await button(root,'返回首帧').fire('click');assert.equal(button(root,'上一帧').disabled,true);
  await fill(root,'插入键序列','-5 0 3');assert.match(root.textContent,/旧结果和播放已清空/);assert.match(root.textContent,/尚无有效结果/);await button(root,'生成 / 重置演示').fire('click');await button(root,'查看末帧').fire('click');assert.ok(walk(root).some(n=>n.attributes['aria-label']?.includes('键0，2个孩子')));await button(root,'生成 / 重置演示').fire('click');assert.match(root.textContent,/当前帧已完成0次插入/);await button(root,'载入混合顺序示例').fire('click');await button(root,'生成 / 重置演示').fire('click');assert.match(root.textContent,/完整结果已预计算：11键/);
});
test('L019 UI重复/代码/超限明确拒绝，错误保持文本',async(t)=>{
  dom(t,{});const{default:feature}=await import('../src/renderer/features/L019/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());for(const[value,message]of [['10,20,10',/重复键 10/],['<img src=x>',/非法键 <img/],[Array.from({length:65},(_,i)=>i).join(' '),/最多64个键/],['1000001',/范围/]]){await fill(root,'插入键序列',value);await button(root,'生成 / 重置演示').fire('click');assert.match(root.textContent,message);assert.match(root.textContent,/尚无有效结果/);}
});
test('L019 UI播放逐帧、暂停/切走/编辑/销毁均释放定时资源',async(t)=>{
  dom(t,{});const originalSet=global.setInterval;const originalClear=global.clearInterval;const callbacks=new Map();let next=1;global.setInterval=fn=>{const id=next++;callbacks.set(id,fn);return id;};global.clearInterval=id=>callbacks.delete(id);t.after(()=>{global.setInterval=originalSet;global.clearInterval=originalClear;});const{default:feature}=await import('../src/renderer/features/L019/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'生成 / 重置演示').fire('click');await button(root,'播放演示').fire('click');assert.equal(callbacks.size,1);[...callbacks.values()][0]();assert.match(root.textContent,/当前帧已完成1次插入/);await button(root,'暂停播放').fire('click');assert.equal(callbacks.size,0);await button(root,'播放演示').fire('click');handle.deactivate();assert.equal(callbacks.size,0);await button(root,'播放演示').fire('click');assert.equal(callbacks.size,0);handle.activate();assert.equal(callbacks.size,0);await button(root,'播放演示').fire('click');await fill(root,'插入键序列','1 2');assert.equal(callbacks.size,0);await button(root,'生成 / 重置演示').fire('click');await button(root,'播放演示').fire('click');while(callbacks.size)[...callbacks.values()][0]();assert.equal(button(root,'下一帧').disabled,true);await button(root,'播放演示').fire('click');assert.equal(callbacks.size,1);handle.destroy();assert.equal(callbacks.size,0);assert.equal(root.children.length,0);handle.destroy();
});
test('L019 UI版本/容量草稿恢复与严格ok/copyOnly导出契约',async(t)=>{
  const stored=new Map();const exported=[];dom(t,{saveTextSupportsCopyOnly:1,saveText:async(payload)=>{exported.push(payload);return{ok:'true'};}});const{default:feature}=await import('../src/renderer/features/L019/index.js');const config={get:key=>stored.get(key),set:(key,value)=>stored.set(key,value)};const root=new NodeStub('div');const handle=feature.create(root,{config});t.after(()=>handle.destroy());await button(root,'导出完整 JSON').fire('click');assert.equal(exported.length,0);assert.match(root.textContent,/缺少防覆盖/);window.toolbox.files.saveTextSupportsCopyOnly=true;await button(root,'导出完整 JSON').fire('click');assert.equal(exported[0].copyOnly,true);assert.match(root.textContent,/未确认保存成功/);window.toolbox.files.saveText=async()=>({canceled:true});await button(root,'导出完整 Markdown').fire('click');assert.match(root.textContent,/已取消导出/);window.toolbox.files.saveText=async()=>{throw new Error('磁盘失败');};await button(root,'导出完整 JSON').fire('click');assert.match(root.textContent,/导出失败：磁盘失败/);
  await fill(root,'插入键序列','1 2 3');await button(root,'生成 / 重置演示').fire('click');handle.deactivate();assert.deepEqual(stored.get('features.L019.state'),{schemaVersion:1,sequence:'1 2 3'});const restoredRoot=new NodeStub('div');const restored=feature.create(restoredRoot,{config});assert.match(restoredRoot.textContent,/已恢复输入草稿/);assert.match(restoredRoot.textContent,/尚无有效结果/);assert.equal(control(restoredRoot,'插入键序列').value,'1 2 3');restored.destroy();const before=structuredClone(stored.get('features.L019.state'));await fill(root,'插入键序列','汉'.repeat(22000));handle.deactivate();assert.deepEqual(stored.get('features.L019.state'),before);assert.match(root.textContent,/当前输入未写入全局配置/);await fill(root,'插入键序列','汉'.repeat(1400));handle.deactivate();assert.deepEqual(stored.get('features.L019.state'),before);assert.match(root.textContent,/4096/);
  for(const raw of [{schemaVersion:2},{schemaVersion:1,sequence:'1',hidden:'汉'.repeat(22000)},{schemaVersion:1,sequence:[] }]){const r=new NodeStub('div');const h=feature.create(r,{config:{get:()=>raw}});assert.match(r.textContent,/草稿未能恢复/);h.destroy();}
});
