const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');const folder=path.resolve(__dirname,'../src/renderer/features/T021'),model=import(pathToFileURL(path.join(folder,'model.mjs')).href);
function pdf(labels=['A1','A2']){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids ['+labels.map((_,i)=>(3+i*2)+' 0 R').join(' ')+'] /Count '+labels.length+' >>'];for(let i=0;i<labels.length;i++){const stream='BT /F1 20 Tf 40 120 Td ('+labels[i]+') Tj ET';objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+(200+i*10)+' '+(300+i*10)+'] /Resources << /Font << /F1 '+(3+labels.length*2)+' 0 R >> >> /Contents '+(4+i*2)+' 0 R >>');objects.push('<< /Length '+Buffer.byteLength(stream)+' >>\nstream\n'+stream+'\nendstream');}objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let text='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(text));text+=(i+1)+' 0 obj\n'+objects[i]+'\nendobj\n';}const xref=Buffer.byteLength(text);text+='xref\n0 '+offsets.length+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+offsets.length+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';return new Uint8Array(Buffer.from(text));}
const sources=()=>[{id:'F001',name:'A.pdf',bytes:pdf(['A1','A2'])},{id:'F002',name:'B.pdf',bytes:pdf(['B1','B2'])}],plan={mode:'merged',groupSize:1,rows:[{id:'P002',sourceId:'F001',page:2},{id:'P001',sourceId:'F001',page:1},{id:'P004',sourceId:'F002',page:2},{id:'P003',sourceId:'F002',page:1}]};
test('T021 catalog and exact pinned original bundle SHA, complete upstream license inventory',()=>{const catalog=require('../src/main/feature-catalog').listFeatures(path.dirname(folder));assert.equal(catalog.errors.length,0);assert.ok(catalog.features.some(f=>f.id==='T021'));const manifest=JSON.parse(fs.readFileSync(path.join(folder,'vendor/manifest.json'),'utf8')),b=fs.readFileSync(path.join(folder,'vendor/pdf-lib.esm.min.mjs'));assert.equal(b.length,manifest.bundleBytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),manifest.bundleSHA256);assert.equal(manifest.packages.length,6);for(const item of manifest.packages)assert.ok(fs.readFileSync(path.join(folder,'vendor',item.licenseFile),'utf8').length>100);});
test('T021 independent handwritten PDFs input page counts media geometry and original hash',async()=>{const m=await model,input=sources(),r=await m.loadSources(input);assert.deepEqual(r.sources.map(s=>s.pages.length),[2,2]);assert.deepEqual(r.sources[0].pages.map(p=>[p.mediaBox.width,p.mediaBox.height]),[[200,300],[210,310]]);assert.equal(r.sources[0].sha256,crypto.createHash('sha256').update(input[0].bytes).digest('hex'));assert.deepEqual(m.rowsFor(r.sources).map(r=>[r.id,r.sourceId,r.page]),[['P001','F001',1],['P002','F001',2],['P003','F002',1],['P004','F002',2]]);});
test('T021 2-1-4-3 copy independent raw stream markers and4actual Page objects correct map',async()=>{const m=await model,input=sources(),before=input.map(s=>Buffer.from(s.bytes)),r=await m.build(input,plan);assert.equal(r.files.length,1);assert.equal(r.files[0].pages,4);assert.deepEqual(r.report.pageMap.map(p=>p.sourceName+':'+p.sourcePage),['A.pdf:2','A.pdf:1','B.pdf:2','B.pdf:1']);const text=Buffer.from(r.files[0].bytes).toString('latin1');assert.equal((text.match(/\/Type\s*\/Page\b/g)||[]).length,4);assert.deepEqual([...text.matchAll(/\((A[12]|B[12])\) Tj/g)].map(m=>m[1]),['A2','A1','B2','B1']);for(let i=0;i<input.length;i++)assert.deepEqual(Buffer.from(input[i].bytes),before[i]);assert.deepEqual(r.report.pageMap.map(p=>[p.mediaBox.width,p.mediaBox.height]),[[210,310],[200,300],[210,310],[200,300]]);});
test('T021 split into2new PDFs and complete bundle retains outputs plus JSON MD source map',async()=>{const m=await model,r=await m.build(sources(),{...plan,mode:'split',groupSize:2});assert.deepEqual(r.files.map(f=>[f.name,f.pages]),[['part-01.pdf',2],['part-02.pdf',2]]);assert.deepEqual(r.report.pageMap.map(p=>p.outputPage),[1,2,1,2]);const b=await m.bundle(r);assert.equal(b.length,4);assert.deepEqual(Buffer.from(b[0].base64,'base64'),Buffer.from(r.files[0].bytes));assert.deepEqual(JSON.parse(Buffer.from(b[2].base64,'base64').toString('utf8')),r.report);assert.ok(Buffer.from(b[3].base64,'base64').toString('utf8').includes('P004'));});
test('T021 plan strict unknown fields missing refs duplicate stableIDs bounds and valid subset',async()=>{const m=await model,{sources:s}=await m.loadSources(sources());for(const p of[{...plan,extra:true},{...plan,rows:[]},{...plan,mode:'execute'},{...plan,groupSize:0},{...plan,groupSize:1.5},{...plan,rows:[plan.rows[0],plan.rows[0]]},{...plan,rows:[{...plan.rows[0],sourceId:'F009'}]},{...plan,rows:[{...plan.rows[0],page:3}]}])assert.throws(()=>m.validatePlan(s,p));assert.equal(m.validatePlan(s,{...plan,rows:[plan.rows[0]]}).rows.length,1);assert.deepEqual(m.move(plan.rows,0,3).map(r=>r.id),['P001','P004','P003','P002']);assert.throws(()=>m.move(plan.rows,-1,0));});
test('T021 source capacity malformed PDFs and form structure rejected no partial file',async()=>{const m=await model;for(const raw of[[],Array.from({length:5},(_,i)=>({id:'F00'+(i+1),name:'x',bytes:pdf()})),[{id:'F001',name:'x',bytes:new Uint8Array(2097153)}],[sources()[0],sources()[0]]])assert.throws(()=>m.checkSources(raw));await assert.rejects(m.loadSources([{id:'F001',name:'bad.pdf',bytes:new Uint8Array(Buffer.from('notpdf'))}]));await assert.rejects(m.loadSources([{id:'F001',name:'81.pdf',bytes:pdf(Array.from({length:81},(_,i)=>'p'+i))}]));const lib=await import(pathToFileURL(path.join(folder,'vendor/pdf-lib.esm.min.mjs')).href),form=await lib.PDFDocument.create();form.addPage();form.getForm().createTextField('field');await assert.rejects(m.loadSources([{id:'F001',name:'form.pdf',bytes:await form.save()}]),/表单/);});
test('T021 full80pages output/report with duplicate source pages explicit stable IDs and no truncation',async()=>{const m=await model,rows=Array.from({length:80},(_,i)=>({id:'P'+String(i+1).padStart(3,'0'),sourceId:'F001',page:1})),r=await m.build([sources()[0]],{mode:'merged',groupSize:80,rows});assert.equal(r.files[0].pages,80);assert.equal(r.report.pageMap.at(-1).globalOutputPage,80);assert.equal(JSON.parse(m.reportText(r.report,'json')).pageMap.length,80);assert.ok(m.reportText(r.report,'md').includes('P080'));assert.throws(()=>m.reportText(r.report,'html'));assert.equal((Buffer.from(r.files[0].bytes).toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length,80);});
test('T021 canonical binary copy and actual output SHA matches all bytes, oversized bundle refuses',async()=>{const m=await model,r=await m.build(sources(),plan),b=m.binaryFile(r.files[0]);assert.equal(b.sha256,crypto.createHash('sha256').update(Buffer.from(b.base64,'base64')).digest('hex'));assert.deepEqual(Buffer.from(b.base64,'base64'),Buffer.from(r.files[0].bytes));await assert.rejects(m.bundle({...r,files:[{...r.files[0],bytes:new Uint8Array(2097153)}]}));});

class Element{
constructor(tag){this.nodeType=1;this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.events=new Map();this.style={};this.dataset={};this.classList={add(){},remove(){}};this.value='';this.disabled=false;this._text='';this.width=this.height=1;}
setAttribute(k,v){this.attributes[k]=String(v);if(k==='value')this.value=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}
getAttribute(k){return this.attributes[k];}append(...items){for(const item of items){item.parentNode=this;this.children.push(item);}}replaceChildren(...items){this.children=[];this._text='';this.append(...items);}addEventListener(t,f){this.events.set(t,f);}removeEventListener(t){this.events.delete(t);}emit(t,p={}){if(this.disabled)return;return this.events.get(t)?.({target:this,preventDefault(){},...p});}click(){return this.emit('click');}get textContent(){return this._text+this.children.map(c=>c.textContent||'').join('');}set textContent(v){this._text=String(v);this.children=[];}getContext(){return{};}
querySelectorAll(s){const nodes=this.children.flatMap(c=>c.nodeType===1?[c,...c.querySelectorAll('*')]:[]);return s==='*'?nodes:nodes.filter(n=>s.startsWith('[')?n.getAttribute(s.slice(1,s.indexOf('=')))===s.slice(s.indexOf('="')+2,-2):n.tagName===s.toUpperCase());}querySelector(s){return this.querySelectorAll(s)[0]||null;}
}
async function mount(options={}){
const m=await model,root=new Element('div'),document={hidden:false,events:new Map(),createElement:t=>new Element(t),createTextNode:text=>({nodeType:3,textContent:String(text)}),addEventListener(t,f){this.events.set(t,f);},removeEventListener(t){this.events.delete(t);}},saved=[],workers=[],renders=[],destroyed=[],timers=new Map();let timerID=0;
class WorkerMock{constructor(){workers.push(this);this.stopped=false;}terminate(){this.stopped=true;}postMessage(p){this.request=p;if(options.holdWorker?.(p))return;Promise.resolve(p.op==='inspect'?m.loadSources(p.sources):m.build(p.sources,p.plan)).then(result=>this.onmessage?.({data:{ok:true,result}}),e=>this.onmessage?.({data:{ok:false,error:e.message}}));}}
const parser={getDocument(){const loading={destroy:()=>{destroyed.push('loading');return options.destroyFailure?Promise.reject(Error('disposed')):Promise.resolve();}};loading.promise=Promise.resolve({getPage:async page=>({getViewport:({scale})=>({width:200*scale,height:300*scale}),render(){const item={page,canceled:false,cancel(){this.canceled=true;item.reject?.(Error('render canceled'));}};item.promise=options.holdRender?new Promise((resolve,reject)=>{item.resolve=resolve;item.reject=reject;}):options.renderFailure?Promise.reject(Error('fixture render failure')):Promise.resolve();renders.push(item);return item;},cleanup(){}}),destroy:async()=>{destroyed.push('doc');}});return loading;}};
const files={saveBinarySupportsCopyOnly:options.capability!==false,exportBundleSupportsCopyOnly:options.capability!==false,saveTextSupportsCopyOnly:options.capability!==false};for(const method of['saveBinary','exportBundle','saveText'])files[method]=async p=>{saved.push({method,p});if(options.saveReply instanceof Error)throw options.saveReply;return options.saveReply==='undefined'?undefined:options.saveReply||{ok:true};};
const vm=require('node:vm'),context=vm.createContext({document,window:{toolbox:{files}},...m,TextEncoder,Uint8Array,ArrayBuffer,URL,crypto:crypto.webcrypto,setTimeout:(f,ms)=>{const id=++timerID;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),module:{exports:{}}});vm.runInContext(fs.readFileSync(path.resolve(folder,'../../core/ui.js'),'utf8').replace(/export /g,'')+'\nmodule.exports={h};',context);context.h=context.module.exports.h;
let source=fs.readFileSync(path.join(folder,'index.js'),'utf8').replace(/^import .*;\r?$/gm,'').replace('export default','module.exports=');source=source.replace(/import\.meta\.url/g,JSON.stringify(pathToFileURL(path.join(folder,'index.js')).href));vm.runInContext(source,context);
const lifecycle=context.module.exports.create(root,{workerFactory:()=>new WorkerMock(),pdfjs:async()=>parser,config:{set(){assert.fail('PDF bytes must not enter config');}}}),all=()=>[root,...root.querySelectorAll('*')],button=t=>all().find(e=>e.tagName==='BUTTON'&&e.textContent===t),field=l=>all().find(e=>e.getAttribute?.('aria-label')===l),tick=()=>new Promise(r=>setImmediate(r));
async function wait(){for(let i=0;i<3000;i++){if(!field('选择PDF来源文件').disabled)return;await tick();}throw Error('UI did not settle');}async function select(input=sources()){field('选择PDF来源文件').files=input.map(s=>({name:s.name,size:s.bytes.length,arrayBuffer:async()=>s.bytes.slice().buffer}));field('选择PDF来源文件').emit('change');await wait();}async function click(t){const p=button(t).click();await p;await wait();}
lifecycle.activate();return{root,document,lifecycle,button,field,workers,renders,destroyed,saved,timers,tick,wait,select,click,text:()=>root.textContent};
}
const prepareLabel='生成并预览全部输出PDF页',singleLabel='另存已预览单份PDF新副本',bundleLabel='另存全部PDF及来源表新目录',reportLabel='另存当前逐页来源表新副本';
test('T021 UI explicit input all pages rendered before export, drag and keyboard order with exact map',async()=>{const ui=await mount();assert.equal(ui.workers.length,0);assert.equal(ui.button(prepareLabel).disabled,true);await ui.select();await ui.click('渲染当前源页缩略图');assert.equal(ui.renders.length,4);const list=ui.field('可拖动页面顺序'),second=list.children[1];second.emit('dragstart',{dataTransfer:{setData(){}}});list.children[0].emit('drop');await ui.click('上移 P004');await ui.click(prepareLabel);const report=JSON.parse(ui.field('完整逐页来源报告').textContent);assert.deepEqual(report.pageMap.map(p=>p.sourcePage),[2,1,2,1]);assert.deepEqual(report.pageMap.map(p=>p.sourceId),['F001','F001','F002','F002']);assert.equal(ui.renders.length,8);assert.equal(ui.button(singleLabel).disabled,false);await ui.click('排除此页 P002');assert.equal(ui.field('完整逐页来源报告').textContent,'');assert.equal(ui.button(singleLabel).disabled,true);ui.lifecycle.destroy();assert.equal(ui.root.children.length,0);});
test('T021 UI exact binary bundle JSON Markdown copyOnly and strict success across failure replies',async()=>{for(const saveReply of[{ok:true},{ok:false,error:'EEXIST'},'undefined',{canceled:true},Error('write fixture')]){const ui=await mount({saveReply});await ui.select();await ui.click(prepareLabel);for(const label of[singleLabel,bundleLabel,reportLabel]){const before=ui.field('完整逐页来源报告').textContent;await ui.click(label);assert.equal(ui.saved.at(-1).p.copyOnly,true);assert.equal(ui.field('完整逐页来源报告').textContent,before);assert.equal(ui.text().includes('新副本保存成功'),saveReply?.ok===true);}await ui.click('预览完整Markdown逐页来源表');const md=ui.field('完整逐页来源报告').textContent;await ui.click(reportLabel);assert.equal(ui.saved.at(-1).p.content,md);assert.equal(ui.saved.at(-1).p.extension,'md');const binary=ui.saved.find(x=>x.method==='saveBinary').p;assert.equal(binary.sha256,crypto.createHash('sha256').update(Buffer.from(binary.base64,'base64')).digest('hex'));ui.lifecycle.destroy();}});
test('T021 UI unavailable copyOnly capabilities disable all disk export but preserve usable preview',async()=>{const ui=await mount({capability:false});await ui.select();await ui.click(prepareLabel);for(const label of[singleLabel,bundleLabel,reportLabel])assert.equal(ui.button(label).disabled,true);assert.equal(JSON.parse(ui.field('完整逐页来源报告').textContent).pageMap.length,4);assert.equal(ui.saved.length,0);ui.lifecycle.destroy();});
test('T021 UI splitting renders each output, malformed grouping and source leave no partial output',async()=>{const ui=await mount();await ui.select();ui.field('合并或按页数拆分').value='split';ui.field('合并或按页数拆分').emit('change');await ui.click(prepareLabel);assert.equal(ui.renders.length,4);assert.equal(ui.button(singleLabel).disabled,true);await ui.click(bundleLabel);assert.equal(ui.saved[0].p.files.length,6);ui.field('每份拆分页数').value='01';ui.field('每份拆分页数').emit('input');await ui.click(prepareLabel);assert.ok(ui.text().includes('1–80整数'));assert.equal(ui.button(bundleLabel).disabled,true);await ui.select([{id:'F001',name:'bad.pdf',bytes:new Uint8Array([1,2,3])}]);assert.ok(ui.text().includes('载入拒绝'));assert.equal(ui.field('可拖动页面顺序').children.length,4);assert.equal(ui.field('已生成PDF输出预览').children.length,0);ui.lifecycle.destroy();});
test('T021 UI failed output rendering clears whole result and prevents partial save',async()=>{const ui=await mount({renderFailure:true});await ui.select();await ui.click(prepareLabel);assert.ok(ui.text().includes('生成/预览未完成'));assert.equal(ui.field('已生成PDF输出预览').children.length,0);assert.equal(ui.field('完整逐页来源报告').textContent,'');assert.equal(ui.button(singleLabel).disabled,true);assert.equal(ui.destroyed.filter(x=>x==='doc').length,1);ui.lifecycle.destroy();});
test('T021 UI actual deadline callback terminates trusted worker no success and no timer survives',async()=>{const ui=await mount({holdWorker:p=>p.op==='build'});await ui.select();const pending=ui.button(prepareLabel).click();assert.equal(ui.timers.size,1);const timer=[...ui.timers.values()][0];assert.equal(timer.ms,15000);timer.f();await pending;await ui.wait();assert.ok(ui.text().includes('超过15秒'));assert.equal(ui.workers.at(-1).stopped,true);assert.equal(ui.timers.size,0);assert.equal(ui.button(singleLabel).disabled,true);ui.lifecycle.destroy();});
test('T021 UI canceled worker late response discarded, retained sources usable next run',async()=>{let hold=true;const ui=await mount({holdWorker:p=>p.op==='build'&&hold});await ui.select();const pending=ui.button(prepareLabel).click(),w=ui.workers.at(-1);await ui.button('取消本次PDF处理').click();await pending;await ui.wait();assert.equal(w.stopped,true);assert.equal(ui.timers.size,0);w.onmessage({data:{ok:true,result:await(await model).build(sources(),plan)}});await ui.tick();assert.equal(ui.field('完整逐页来源报告').textContent,'');assert.equal(ui.button(singleLabel).disabled,true);hold=false;await ui.click(prepareLabel);assert.equal(ui.button(singleLabel).disabled,false);ui.lifecycle.destroy();});
test('T021 UI render cancellation handles resource cleanup rejection without stale canvas or result',async()=>{const ui=await mount({holdRender:true,destroyFailure:true});await ui.select();const pending=ui.button(prepareLabel).click();for(let i=0;i<3000&&!ui.renders.length;i++)await ui.tick();assert.equal(ui.renders.length,1);await ui.button('取消本次PDF处理').click();await pending;await ui.wait();assert.equal(ui.renders[0].canceled,true);assert.equal(ui.field('已生成PDF输出预览').children.length,0);assert.equal(ui.button(singleLabel).disabled,true);ui.lifecycle.destroy();await ui.tick();});
test('T021 UI leave and hidden clear bytes DOM callbacks config and resume requires explicit reselect',async()=>{for(const hidden of[false,true]){const ui=await mount({holdWorker:p=>p.op==='build'});await ui.select();const pending=ui.button(prepareLabel).click();if(hidden){ui.document.hidden=true;ui.document.events.get('visibilitychange')();}else ui.lifecycle.deactivate();await pending;assert.equal(ui.workers.at(-1).stopped,true);assert.equal(ui.field('可拖动页面顺序').children.length,0);assert.equal(ui.timers.size,0);ui.document.hidden=false;ui.lifecycle.activate();assert.equal(ui.button(prepareLabel).disabled,true);assert.equal(ui.workers.length,2);ui.lifecycle.destroy();assert.equal(ui.document.events.size,0);}});
