const test=require('node:test'),assert=require('node:assert/strict');
const model=import('../src/renderer/features/T085/model.mjs');
test('T085: 100W ×5h ×30d yields15kWh and15CNY',async()=>{const{simpleExample,calculateScenarios}=await model;const r=calculateScenarios(simpleExample());assert.equal(r.scenarios[0].totalKWh,'15.000000');assert.equal(r.scenarios[0].cost,'15.00');assert.equal(r.scenarios[0].standbyKWh,'0.000000');});
test('T085: peak/offpeak and standby are charged in their own periods',async()=>{const{tariffExample,calculateScenarios}=await model;const r=calculateScenarios(tariffExample());assert.deepEqual(r.scenarios.map(s=>s.totalKWh),['17.850000','17.850000']);assert.deepEqual(r.scenarios.map(s=>s.cost),['24.38','10.13']);assert.equal(r.comparisons[0].costDelta,'-14.25');assert.equal(r.scenarios[0].devices[0].entries[0].standbyHoursPerDay,'3.000');});
test('T085: sums exact before rounding displayed components',async()=>{const{simpleExample,calculateScenarios}=await model;const input=simpleExample();input[0].days=1;input[0].devices=Array.from({length:2},(_,i)=>({name:'d'+i,powerW:'1',standbyW:'0',activeHours:['5']}));const r=calculateScenarios(input);assert.deepEqual(r.scenarios[0].devices.map(d=>d.cost),['0.01','0.01']);assert.equal(r.scenarios[0].cost,'0.01');});
test('T085: different currency or days cannot silently yield saving',async()=>{const{tariffExample,calculateScenarios}=await model;for(const override of [{currency:'USD'},{days:31}]){const input=tariffExample();Object.assign(input[1],override);const r=calculateScenarios(input);assert.equal(r.comparisons[0].comparable,false);assert.equal(r.comparisons[0].costDelta,undefined);}});
test('T085: missing24h, overlapping hours, negative/empty/precision input reject whole batch',async()=>{const{simpleExample,calculateScenarios}=await model;for(const edit of [i=>i[0].periods[0].hours='23',i=>i[0].devices[0].activeHours=['25'],i=>i[0].devices[0].powerW='-1',i=>i[0].periods[0].price='',i=>i[0].devices[0].powerW='0.0001',i=>i[0].devices[0].activeHours=[],i=>i[0].days=1.5]){const input=simpleExample();edit(input);assert.throws(()=>calculateScenarios(input));}});
test('T085: exact maximum products serialize as strings and never Infinity',async()=>{const{simpleExample,calculateScenarios}=await model;const input=simpleExample();input[0].days=3660;input[0].periods[0].price='1000';input[0].devices=Array.from({length:20},(_,i)=>({name:'d'+i,powerW:'1000000',standbyW:'1000000',activeHours:['24']}));const r=calculateScenarios(input);assert.equal(r.scenarios[0].totalKWh,'1756800000.000000');assert.equal(r.scenarios[0].cost,'1756800000000.00');assert.ok(BigInt(r.scenarios[0].energyExact.numerator)>BigInt(Number.MAX_SAFE_INTEGER));assert.doesNotThrow(()=>JSON.stringify(r));});
test('T085: duplicate scenario names and cardinality limits enforced, inputs copied',async()=>{const{simpleExample,calculateScenarios}=await model;assert.throws(()=>calculateScenarios([]));const input=simpleExample();assert.throws(()=>calculateScenarios([input[0],input[0]]),/不同/);const r=calculateScenarios(input);input[0].devices[0].powerW='999';assert.equal(r.inputs[0].devices[0].powerW,'100');assert.match(r.assumptions[0],/估计/);});
