const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=path.resolve(__dirname,'../src/renderer/features/T034'),model=()=>import('../src/renderer/features/T034/model.mjs'),host=require('../src/renderer/features/T034/host.cjs'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const xs=[20,400,790,1180],ys=[20,150,280,410,540],expected=[['Item','Count','Cost'],['Apple','12','2.50'],['Pear','7','1.20'],['Plum','3','0.80']];
test('T034 PNG header dimensions and original bytes budget before decode',async()=>{const m=await model(),png=fs.readFileSync(path.join(base,'fixtures/table-3x4.png'));assert.deepEqual(m.pngInfo(png),{width:1200,height:560});for(const bytes of[Buffer.alloc(33),png.subarray(0,32),Buffer.alloc(8388609)])assert.throws(()=>m.pngInfo(bytes));for(const [w,h]of[[0,560],[8193,1],[4000,4000]]){const b=Buffer.from(png);b.writeUInt32BE(w,16);b.writeUInt32BE(h,20);assert.throws(()=>m.pngInfo(b));}});
test('T034 strict sorted boundary parsing no duplicate/unknown/coercion',async()=>{const m=await model();assert.deepEqual(m.parseCuts(' 20, 400,790,1180 ',1200),xs);for(const v of['','1','0,0','2,1','0,1201','0,1.5','0,1e2','0,,100','0,-1'])assert.throws(()=>m.parseCuts(v,1200));});
test('T034 row-major rectangles independent pixel subtraction oracle',async()=>{const m=await model(),g=m.grid({xs,ys},{width:1200,height:560},4);assert.equal(g.rows,4);assert.equal(g.columns,3);assert.equal(g.cells.length,12);assert.deepEqual(g.cells[4],{id:'R2C2',row:1,column:1,rectangle:{left:404,top:154,width:382,height:122}});assert.deepEqual(g.cells.map(c=>c.id),Array.from({length:12},(_,i)=>`R${Math.floor(i/3)+1}C${i%3+1}`));});
test('T034 complete budget refusal not silent clipped grid',async()=>{const m=await model();for(const [g,info,margin]of[[{xs:[0,15],ys:[0,100]},{width:100,height:100},4],[{xs:Array.from({length:10},(_,i)=>i*20),ys:[0,100]},{width:200,height:100},0],[{xs:[0,3000],ys:[0,2001]},{width:3000,height:2001},0],[{xs:[0,2000,4000],ys:[0,1000,2000,3000]},{width:4000,height:3000},0],[{xs:[0,20],ys:[0,20]},{width:NaN,height:40},0],[{xs:[0,20],ys:[0,20]},{width:40,height:40},-1]])assert.throws(()=>m.grid(g,info,margin));});
function pixels(w,h,xs,ys,alpha=255){const p=new Uint8ClampedArray(w*h*4);p.fill(255);for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(xs.includes(x)||ys.includes(y)){const i=(y*w+x)*4;p[i]=p[i+1]=p[i+2]=0;p[i+3]=alpha;}return p;}
test('T034 line projection independent synthetic 3x4 pixel oracle',async()=>{const m=await model(),x=[2,22,42,62],y=[2,22,42,62,82],p=pixels(65,85,x,y),r=await m.detectLines(p,65,85,{left:0,top:0,right:65,bottom:85});assert.deepEqual(r.xs,x);assert.deepEqual(r.ys,y);assert.equal(m.grid(r,{width:65,height:85},2).cells.length,12);});
test('T034 alpha composites to white and incomplete lines do not invent grid',async()=>{const m=await model(),roi={left:0,top:0,right:50,bottom:50};await assert.rejects(()=>m.detectLines(pixels(50,50,[1,48],[1,48],0),50,50,roi),/没有检测/);const p=pixels(50,50,[],[]);for(let y=0;y<20;y++){const i=(y*50+5)*4;p[i]=p[i+1]=p[i+2]=0;}await assert.rejects(()=>m.detectLines(p,50,50,roi),/没有检测/);});
test('T034 detection cancellation observed during cooperative yield',async()=>{const m=await model();let canceled=false,yields=0;await assert.rejects(()=>m.detectLines(pixels(100,100,[1,98],[1,98]),100,100,{left:0,top:0,right:100,bottom:100},{canceled:()=>canceled,yieldControl:async()=>{yields++;canceled=true;}}),/已取消/);assert.equal(yields,1);});
async function cellFixture(){const m=await model(),g=m.grid({xs:[0,100],ys:[0,100]},{width:100,height:100},4),raw={text:'甲😀',words:[{text:'甲',confidence:90,bbox:{x0:10,y0:10,x1:30,y1:40}},{text:'😀',confidence:80,bbox:{x0:31,y0:10,x1:50,y1:40}}]};return{m,g,raw};}
test('T034 minimum word confidence threshold strict boundary and empty unknown',async()=>{const{m,g,raw}=await cellFixture();assert.equal(m.cellResult(g.cells[0],raw,80).lowConfidence,false);const c=m.cellResult(g.cells[0],raw,81);assert.equal(c.confidence,80);assert.equal(c.lowConfidence,true);assert.equal(c.review,'pending');assert.equal(c.rawText,'甲😀');const e=m.cellResult(g.cells[0],{text:'',words:[]},90);assert.equal(e.confidence,null);assert.equal(e.unrecognized,true);assert.equal(e.lowConfidence,false);});
test('T034 malformed bbox/control/Unicode/word capacity all refused',async()=>{const{m,g,raw}=await cellFixture();for(const patch of[{bbox:{}},{bbox:{x0:0,y0:10,x1:30,y1:40}},{bbox:{x0:10,y0:10,x1:101,y1:40}},{confidence:101},{confidence:NaN},{text:'\ud800'}])assert.throws(()=>m.cellResult(g.cells[0],{text:'x',words:[{...raw.words[0],...patch}]},90));assert.throws(()=>m.cellResult(g.cells[0],{text:'x',words:Array(65).fill(raw.words[0])},90));assert.equal(m.text('😀'.repeat(512)).length,1024);for(const s of['😀'.repeat(513),'\u0000','\ud800'])assert.throws(()=>m.text(s));});
test('T034 manual review required unknown distinct from confirmed empty',async()=>{const{m,g,raw}=await cellFixture(),c=m.cellResult(g.cells[0],raw,90);assert.throws(()=>m.table(g,[c],{requireReviewed:true}),/人工/);c.review='unknown';assert.deepEqual(m.table(g,[c],{requireReviewed:true}),[['']]);assert.equal(c.rawText,'甲😀');c.review='confirmed';c.value='';assert.deepEqual(m.table(g,[c],{requireReviewed:true}),[['']]);assert.throws(()=>m.table(g,[{...c,row:1}],{requireReviewed:true}));assert.throws(()=>m.table(g,[]));});
// Independent state-machine reader: exercises generated quoting, rather than mirroring its implementation.
function readDelimited(s,d){const rows=[],row=[];let value='',quoted=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(c==='"'&&s[i+1]==='"'){value+='"';i++;}else if(c==='"')quoted=false;else value+=c;}else if(c==='"')quoted=true;else if(c===d){row.push(value);value='';}else if(c==='\r'&&s[i+1]==='\n'){row.push(value);rows.push(row.splice(0));value='';i++;}else value+=c;}assert.equal(quoted,false);return rows;}
test('T034 exact CSV/quoted TSV independent roundtrip including multiline and leading zeros',async()=>{const m=await model(),rows=[['003','2.50','逗号,引号"\n下一行'],['<script>','Tab\tvalue',''],['😀','\r\n','true']];for(const delimiter of[',','\t'])assert.deepEqual(readDelimited(m.delimited(rows,delimiter),delimiter),rows);assert.equal(m.delimited(expected),expected.map(r=>r.join(',')).join('\r\n')+'\r\n');});
test('T034 report snapshot all cells provenance and safe Markdown no raw HTML',async()=>{const{m,g,raw}=await cellFixture(),c=m.cellResult(g.cells[0],raw,90);c.review='unknown';c.value='<img>|x';const r=m.report({name:'<svg>',sha256:'a'.repeat(64)},m.settings(),g,[c],{method:'manual'},true);c.value='changed';assert.equal(r.cells[0].value,'<img>|x');assert.deepEqual(r.unknownCellIds,['R1C1']);assert.equal(r.values[0][0],'');assert.ok(m.markdown(r).includes('&lt;img&gt;\\|x'));assert.equal(m.markdown(r).includes('<svg>'),false);assert.throws(()=>m.report({},m.settings(),g,[c],{},false));});
test('T034 settings strict version scalar limits no source/derived archive',async()=>{const m=await model();for(const s of[{...m.settings(),schemaVersion:2},{...m.settings(),source:'secret'},{...m.settings(),threshold:100.1},{...m.settings(),threshold:-1},{...m.settings(),margin:13},{...m.settings(),language:'fra'}])assert.throws(()=>m.settings(s));assert.deepEqual(Object.keys(m.settings()).sort(),['language','margin','schemaVersion','threshold']);});
test('T034 maximum96-cell report complete rowmajor no output truncation',async()=>{const m=await model(),layout=m.grid({xs:Array.from({length:9},(_,i)=>i*30),ys:Array.from({length:13},(_,i)=>i*30)},{width:240,height:360},0),cells=layout.cells.map(c=>({...m.cellResult(c,{text:c.id,words:[]},90),review:'confirmed'})),r=m.report({name:'max.png',sha256:'a'.repeat(64)},m.settings(),layout,cells,{method:'manual'},true);assert.equal(r.cells.length,96);assert.equal(r.values.length,12);assert.equal(r.values[11].length,8);assert.equal(r.values[11][7],'R12C8');assert.equal(readDelimited(m.delimited(r.values),',').flat().length,96);assert.ok(m.markdown(r).includes('|R12C8|'));});
test('T034 all independently packaged fixed files SHA and licensing metadata',()=>{const v=JSON.parse(fs.readFileSync(path.join(base,'vendor/manifest.json')));assert.equal(v.files.length,209);for(const f of v.files){const b=fs.readFileSync(path.join(base,'vendor',f.path));assert.equal(b.length,f.bytes);assert.equal(sha(b),f.sha256);}for(const p of v.packages){assert.match(p.integrity,/^sha512-/);assert.match(p.url,/^https:\/\/registry.npmjs.org\//);}assert.equal(v.models.length,2);assert.ok(v.files.some(f=>/LICENSE/.test(f.path)));assert.equal(v.files.some(f=>['pdf','font','fontkit','noto'].some(k=>f.path.startsWith(k+'/')||f.path===k+'.cjs')),false);});
let sender=200;async function begin(t){const bytes=fs.readFileSync(path.join(base,'fixtures/table-3x4.png')),context={senderId:++sender},r=await host.invoke('begin',{source:{name:'sample.png',bytes:bytes.length,sha256:sha(bytes),width:1200,height:560},settings:(await model()).settings(),grid:{xs,ys},gridConfirmed:true,method:{method:'test-manual'}},context);assert.equal(r.ok,true,r.error);t.after(()=>host.disposeSender(context.senderId));return{bytes,id:r.jobId,context,call:(op,p={})=>host.invoke(op,{jobId:r.jobId,...p},context)};}
async function upload(e){for(let n=0;n<e.bytes.length;n+=24000)assert.equal((await e.call('append',{sequence:n/24000,base64:e.bytes.subarray(n,n+24000).toString('base64')})).ok,true);return e.call('seal');}
test('T034 genuine offline engine readiness without arbitrary executable',async()=>{assert.equal((await host.invoke('status',{}, {senderId:199})).offline,true);assert.equal((await host.invoke('exec',{command:'not-run'}, {senderId:199})).ok,false);});
test('T034 sender-bound exact chunk sequence and incomplete source refuse OCR/export',async t=>{const e=await begin(t);for(const p of[{sequence:1,base64:'QQ=='},{sequence:0,base64:'Q!=='}])assert.equal((await e.call('append',p)).ok,false);assert.equal((await host.invoke('append',{jobId:e.id,sequence:0,base64:'QQ=='},{senderId:999})).ok,false);for(const op of['seal','cell','build','choose','write'])assert.equal((await e.call(op,{cellId:'R1C1',format:'csv',copyOnly:true})).ok,false);assert.equal((await upload(e)).ok,true);assert.equal((await e.call('cell',{cellId:'R1C2'})).ok,false);});
test('T034 original source SHA mismatch refuses seal and arbitrary path writes',async t=>{const e=await begin(t);e.bytes=Buffer.from(e.bytes);e.bytes[40]^=1;assert.equal((await upload(e)).ok,false);assert.equal((await e.call('write',{path:'C:\\not-run.csv',copyOnly:true})).ok,false);});
test('T034 actual canceled OCR child owner result never appended',async t=>{const e=await begin(t);assert.equal((await upload(e)).ok,true);const pending=e.call('cell',{cellId:'R1C1'});await new Promise(r=>setTimeout(r,30));await host.cancel(e.id,e.context);assert.equal((await pending).ok,false);assert.equal((await e.call('build')).ok,false);});
test('T034 genuine 12-cell OCR oracle manual review atomic and full exports',async t=>{const e=await begin(t);assert.equal((await upload(e)).ok,true);const records=[];for(let r=0;r<4;r++)for(let c=0;c<3;c++){const result=await e.call('cell',{cellId:`R${r+1}C${c+1}`});assert.equal(result.ok,true,result.error);records.push(result.cell);assert.equal(result.cell.rawText,expected[r][c]);for(const word of result.cell.words){assert.ok(word.bbox.x0>=xs[c]+4);assert.ok(word.bbox.y0>=ys[r]+4);assert.ok(word.bbox.x1<=xs[c+1]-4);assert.ok(word.bbox.y1<=ys[r+1]-4);}}assert.equal((await e.call('build')).ok,false);assert.equal((await e.call('review',{cells:[{id:'R1C1',value:'changed',review:'confirmed'},{id:'bad',value:'x',review:'confirmed'}]})).ok,false);assert.equal((await e.call('review',{cells:records.map(c=>({id:c.id,value:c.rawText,review:'confirmed'}))})).ok,true);const result=await e.call('build');assert.equal(result.ok,true,result.error);assert.deepEqual(result.report.values,expected);assert.equal(result.previews.csv,expected.map(r=>r.join(',')).join('\r\n')+'\r\n');assert.equal(result.report.cells[0].rawText,'Item');assert.equal(result.report.source.sha256,sha(e.bytes));assert.equal((await e.call('review',{cells:[{id:'R2C1',value:'a,b"\n😀',review:'confirmed'},{id:'R4C3',value:'0.80',review:'unknown'}]})).ok,true);const changed=await e.call('build');assert.equal(changed.report.values[3][2],'');assert.deepEqual(changed.report.unknownCellIds,['R4C3']);assert.equal(changed.report.cells[3].rawText,'Apple');assert.equal(changed.report.cells[3].value,'a,b"\n😀');assert.deepEqual(readDelimited(changed.previews.csv,','),changed.report.values);});
class N{constructor(tag='',t=null){this.tagName=tag;this.nodeType=t===null?1:3;this.text=t;this.children=[];this.attributes={};this.events={};this.style={};this.value='';this.disabled=false;}append(...xs){this.children.push(...xs.map(x=>x?.nodeType?x:new N('',String(x))))}replaceChildren(...xs){this.children=[];this.append(...xs)}setAttribute(k,v){this.attributes[k]=String(v);if(k==='value')this.value=String(v)}getAttribute(k){return this.attributes[k]}addEventListener(k,cb){(this.events[k]??=[]).push(cb)}get textContent(){return this.text===null?this.children.map(x=>x.textContent).join(''):this.text}set textContent(x){this.text=null;this.replaceChildren(String(x))}querySelectorAll(q){return walk(this).filter(x=>q.split(',').includes(x.tagName))}remove(){this.removed=true}replaceWith(n){this.replacement=n}async fire(type){for(const f of this.events[type]??[])await f({target:this})}}const walk=n=>[n,...n.children.flatMap(walk)],control=(e,l)=>walk(e.root).find(n=>n.attributes['aria-label']===l),button=(e,l)=>walk(e.root).find(n=>n.tagName==='button'&&n.textContent===l);
async function mount(t,config={}){const old={document:global.document,window:global.window};global.document={createElement:t=>new N(t),createElementNS:(_s,t)=>new N(t),createTextNode:s=>new N('',s)};global.window={toolbox:{features:{cancelHost:async()=>({ok:true}),callHost:async()=>({ok:false,error:'not fixture'})}}};t.after(()=>Object.assign(global,old));const root=new N('div'),life=(await import('../src/renderer/features/T034/index.js')).default.create(root,{config:{get:()=>null,...config}});return{root,life};}const tick=()=>new Promise(r=>setImmediate(r));
test('T034 actual DOM blank numeric settings rejected no silent zero',async t=>{const saved=[],e=await mount(t,{set:async(k,v)=>saved.push(v)});for(const label of['低置信阈值','格内边线内缩像素']){control(e,label).value='';await control(e,label).fire('input');assert.ok(e.root.textContent.includes('非空整数'));assert.equal(saved.length,0);control(e,label).value=label==='低置信阈值'?'90':'4';}assert.equal(button(e,'逐格离线OCR').disabled,true);assert.equal(button(e,'选择CSV新副本路径').disabled,true);});
test('T034 actual DOM file capacity before arrayBuffer or decode',async t=>{const e=await mount(t),n=control(e,'选择表格PNG截图');let reads=0;n.files=[{size:8388609,name:'large.png',arrayBuffer:async()=>{reads++;}}];await n.fire('change');assert.equal(reads,0);assert.ok(e.root.textContent.includes('8MiB'));});
test('T034 late file read after leave cannot revive source or outputs',async t=>{const e=await mount(t),n=control(e,'选择表格PNG截图');let resolve;n.files=[{size:50,name:'late.png',arrayBuffer:()=>new Promise(r=>resolve=r)}];const pending=n.fire('change');e.life.deactivate();resolve(new Uint8Array(50).buffer);await pending;e.life.activate();assert.equal(button(e,'逐格离线OCR').disabled,true);assert.equal(button(e,'选择CSV新副本路径').disabled,true);assert.ok(e.root.textContent.includes('已释放图像'));e.life.destroy();assert.equal(e.root.children[0].removed,true);});
test('T034 invalid restored schema preserved without implicit overwrite',async t=>{let count=0;const e=await mount(t,{get:()=>({schemaVersion:2,source:'do not copy'}),set:async()=>count++});control(e,'表格识别语言').value='chi_sim';await control(e,'表格识别语言').fire('change');await tick();assert.equal(count,0);assert.ok(button(e,'使用当前设置覆盖不可读草稿…'));});
test('T034 queued setting snapshots retain latest order across deactivate',async t=>{const saves=[];let release;const e=await mount(t,{set:async(k,v)=>{saves.push(v);if(saves.length===1)await new Promise(r=>release=r)}});control(e,'表格识别语言').value='eng';await control(e,'表格识别语言').fire('change');await tick();control(e,'表格识别语言').value='chi_sim';await control(e,'表格识别语言').fire('change');e.life.deactivate();release();await tick();await tick();assert.deepEqual(saves.map(v=>v.language),['eng','chi_sim']);assert.deepEqual(Object.keys(saves[1]).sort(),['language','margin','schemaVersion','threshold']);});
