const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');globalThis.crypto||=crypto.webcrypto;const model=import('../src/renderer/features/E011/model.mjs'),clone=v=>JSON.parse(JSON.stringify(v));
// Independent BFS scans all cells for Manhattan-distance1 neighbors on an immutable original image.
function bfs(p,n,seed){const target=p[seed],seen=new Set([seed]),q=[seed],out=[];while(q.length){const i=q.shift();out.push(i);for(let k=0;k<p.length;k++)if(!seen.has(k)&&p[k]===target&&Math.abs(k%n-i%n)+Math.abs(Math.floor(k/n)-Math.floor(i/n))===1){seen.add(k);q.push(k);}}return out;}
function reflected(indices,n,mode){const inside=new Set(indices),out=[];for(let i=0;i<n*n;i++){const x=i%n,y=Math.floor(i/n),h=y*n+n-1-x,v=(n-1-y)*n+x,b=n*n-1-i;if(inside.has(i)||['horizontal','both'].includes(mode)&&inside.has(h)||['vertical','both'].includes(mode)&&inside.has(v)||mode==='both'&&inside.has(b))out.push(i);}return out;}
function opaque(p){const out=Buffer.alloc(p.length*4);p.forEach((c,i)=>{if(c){out[i*4]=parseInt(c.slice(1,3),16);out[i*4+1]=parseInt(c.slice(3,5),16);out[i*4+2]=parseInt(c.slice(5,7),16);out[i*4+3]=255;}});return out;}
if(!process.versions.electron){const test=require('node:test');
test('E011 16/32 complete transparent source; onepixel RGB and exactall alpha, hex normalization rejects invalid',async()=>{const m=await model;for(const n of[16,32]){const g=m.createProject(n);assert.equal(g.pixels.length,n*n);assert.equal(m.count(g),0);assert.deepEqual(Buffer.from(m.rgba(g)),opaque(g.pixels));const tx=m.begin(g);m.dot(g,tx,3,4,'#123456');assert.deepEqual(m.commit(g,tx),{changed:1,dropped:0});assert.equal(g.pixels[4*n+3],'#123456');assert.deepEqual(Buffer.from(m.rgba(g)),opaque(g.pixels));assert.equal(m.rgba(g)[(4*n+3)*4+3],255);assert.equal(m.rgba(g)[0],0);assert.equal(m.rgba(g)[3],0);}assert.equal(m.color('#ABCDEF'),'#abcdef');for(const v of['red','#fff','#ffffff80','#ff00gg','ffffff',null])assert.throws(()=>m.color(v));assert.throws(()=>m.createProject(64));});
test('E011 mirror staticcorner/centerpairs and duplicate reflected stroke targets writtenonce; wholetransaction undo',async()=>{const m=await model,g=m.createProject();for(const[mode,expected]of[['none',[0]],['horizontal',[0,15]],['vertical',[0,240]],['both',[0,15,240,255]]]){g.mirror=mode;assert.deepEqual(m.mirrored(g,0,0).sort((a,b)=>a-b),expected);}g.mirror='both';assert.deepEqual(m.mirrored(g,7,7).sort((a,b)=>a-b),[119,120,135,136]);const tx=m.begin(g);m.dot(g,tx,0,0);m.dot(g,tx,15,15);m.dot(g,tx,0,15);assert.equal(m.commit(g,tx).changed,4);assert.equal(m.count(g),4);assert.equal(g.history.length,1);assert.equal(m.undo(g),true);assert.equal(m.count(g),0);assert.equal(m.undo(g),false);});
test('E011 dragline independent horizontal/vertical/diagonal oracle, wholepen undo/rollback/no-op and boundedhistory100',async()=>{const m=await model,g=m.createProject(32),tx=m.begin(g);m.line(g,tx,1,2,8,2);m.line(g,tx,8,2,8,9);const expect=Array(1024).fill(null);for(let x=1;x<=8;x++)expect[2*32+x]=g.ink;for(let y=2;y<=9;y++)expect[y*32+8]=g.ink;assert.deepEqual(g.pixels,expect);assert.equal(m.commit(g,tx).changed,15);assert.equal(g.history.length,1);m.undo(g);assert.equal(m.count(g),0);const diag=m.begin(g);m.line(g,diag,0,0,31,31);assert.equal(m.count(g),32);for(let i=0;i<32;i++)assert.equal(g.pixels[i*33],g.ink);assert.equal(m.rollback(g,diag),true);assert.equal(m.count(g),0);assert.equal(m.rollback(g,diag),false);assert.throws(()=>m.dot(g,diag,1,1));const noop=m.begin(g);m.dot(g,noop,0,0,null);assert.equal(m.commit(g,noop).changed,0);for(let i=0;i<101;i++){const t=m.begin(g);m.dot(g,t,0,0,i%2?'#000000':'#ffffff');const r=m.commit(g,t);if(i===100)assert.ok(r.dropped>0);}assert.equal(g.history.length,100);for(let i=0;i<100;i++)assert.equal(m.undo(g),true);assert.equal(m.undo(g),false);assert.equal(g.pixels[0],'#ffffff');});
test('E011 fill independent BFS connectedonly originalcolor/no diagonal/no rowwrap; mirror applies region not chain',async()=>{const m=await model;for(const n of[16,32])for(const mode of['none','horizontal','vertical','both']){const g=m.createProject(n);for(let y=0;y<n;y++)g.pixels[y*n+Math.floor(n/2)]='#000000';g.pixels[n+1]='#e4583f';g.pixels[2*n+2]='#e4583f';const before=[...g.pixels],region=bfs(before,n,0),targets=reflected(region,n,mode);g.mirror=mode;const tx=m.begin(g),r=m.fill(g,tx,0,0,'#2b8a78');assert.equal(r.region,region.length);assert.equal(r.targets,targets.length);const expected=before.map((v,i)=>targets.includes(i)?'#2b8a78':v);assert.deepEqual(g.pixels,expected);assert.equal(m.commit(g,tx).changed,targets.filter(i=>before[i]!=='#2b8a78').length);m.undo(g);assert.deepEqual(g.pixels,before);}const g=m.createProject();g.pixels[1]='#34515a';g.pixels[16]='#34515a';const tx=m.begin(g);assert.equal(m.fill(g,tx,0,0).region,1);m.commit(g,tx);assert.equal(g.pixels[17],null);});
test('E011 strict complete1024 source fits64KiB and restores settings/colors not ephemeralundo; malformed rejects',async()=>{const m=await model,g=m.createProject(32);g.pixels=g.pixels.map((_,i)=>i%3?null:'#123456');g.tool='fill';g.mirror='both';g.ink='#abcdef';const v=m.source(g),text=m.encode(v),r=m.parse(text);assert.deepEqual(r,g);assert.ok(Buffer.byteLength(text)<65536);const tx=m.begin(g);m.dot(g,tx,1,1);m.commit(g,tx);assert.equal(m.restore(m.source(g)).history.length,0);for(const bad of[{...v,schema:2},{...v,size:17},{...v,pixels:v.pixels.slice(1)},{...v,pixels:[...v.pixels,0]},{...v,pixels:Array(1024).fill('#FFFFFF')},{...v,pixels:Array(1024).fill('#123456ff')},{...v,tool:'eval'},{...v,mirror:'random'},{...v,ink:null},{...v,history:[]}])assert.throws(()=>m.restore(bad));const holes=Array(1024);assert.throws(()=>m.restore({...v,pixels:holes}));for(const text of['{"schema":1,"schema":1}',String.raw`{"schema":1,"\u0073chema":1}`,m.encode(v).replace('"schema": 1','"schema": 1e0'),' '.repeat(65537),'{"size":9007199254740993}'])assert.throws(()=>m.parse(text));const md=m.markdown(g);assert.equal(md.split('\n').filter(s=>/^\|\d+\|/.test(s)).length,1024);assert.deepEqual(JSON.parse(md.match(/```json\n([\s\S]*?)\n```/)[1]),m.source(g));});
class Element{constructor(tag){this.nodeType=1;this.tagName=tag;this.children=[];this.attributes={};this.listeners={};this.style={};this.value='';this.checked=false;this.disabled=false;this.capture=new Set();}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(t,f){(this.listeners[t]||=[]).push(f);}removeEventListener(t,f){this.listeners[t]=(this.listeners[t]||[]).filter(x=>x!==f);}append(...a){this.children.push(...a);}replaceChildren(...a){this.children=[];this.append(...a);}get textContent(){return this.children.map(n=>n.textContent).join('');}set textContent(v){this.replaceChildren({nodeType:3,textContent:String(v)});}focus(){document.activeElement=this;}getBoundingClientRect(){return{left:10,top:20,right:522,bottom:532,width:512,height:512};}setPointerCapture(id){this.capture.add(id);}hasPointerCapture(id){return this.capture.has(id);}releasePointerCapture(id){this.capture.delete(id);}async fire(t,e={}){if(this.disabled)return;for(const f of [...(this.listeners[t]||[])])await f({target:this,preventDefault(){},button:0,buttons:1,isPrimary:true,pointerId:1,...e});}}
const all=r=>r.children.flatMap(n=>n.nodeType===1?[n,...all(n)]:[]),ctl=(r,t)=>all(r).find(n=>n.attributes['aria-label']===t),btn=(r,t)=>all(r).find(n=>n.tagName==='button'&&n.textContent===t);async function idle(){for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));}
const at=(x,y,n=16)=>({clientX:10+(x+.5)*512/n,clientY:20+(y+.5)*512/n});
async function withUI(initialValue,fn,options={}){const m=await model,old={document:global.document,window:global.window,requestAnimationFrame:global.requestAnimationFrame,setInterval:global.setInterval},events={},calls=[],writes=[],canvases=[];let stored=initialValue===undefined?m.source(m.createProject()):initialValue;global.document={hidden:false,activeElement:null,createElement:t=>{const e=new Element(t);if(t==='canvas'){canvases.push(e);e.getContext=()=>({fillRect(){},strokeRect(){},createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(image){e.lastImage=new Uint8ClampedArray(image.data);}});e.toBlob=cb=>setImmediate(()=>cb(new Blob([Uint8Array.of(137,80,78,71,1)])));}return e;},createTextNode:s=>({nodeType:3,textContent:String(s)}),addEventListener:(k,f)=>(events[k]||=[]).push(f),removeEventListener:(k,f)=>{events[k]=(events[k]||[]).filter(x=>x!==f);}};global.window={toolbox:{files:options.files||{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};},saveBinarySupportsCopyOnly:true,saveBinary:async p=>{calls.push(p);return{ok:true};}}}};global.requestAnimationFrame=()=>assert.fail('noRAF');global.setInterval=()=>assert.fail('notimer');const root=new Element('main'),config=options.config||{get:()=>stored,set:async(_k,v)=>{stored=clone(v);writes.push(stored);}},life=(await import('../src/renderer/features/E011/index.js')).default.create(root,{config});life.activate();await idle();try{await fn(root,life,{events,calls,writes,canvases,stored:()=>stored,hidden:v=>{document.hidden=v;for(const f of events.visibilitychange||[])f();}});}finally{life.destroy();for(const[k,v]of Object.entries(old))if(v===undefined)delete global[k];else global[k]=v;}}
async function gesture(r,points,n=16){const c=ctl(r,'像素画布');await c.fire('pointerdown',at(...points[0],n));for(const p of points.slice(1))await c.fire('pointermove',at(...p,n));await c.fire('pointerup',at(...points.at(-1),n));await idle();}
async function tool(r,value){ctl(r,'像素工具').value=value;await ctl(r,'像素工具').fire('change');await idle();}
test('E011 UI freshsave/mouse3cells/keyboard reachable/eraser/picker/undo and numeric alternative',async()=>{await withUI(null,async(_r,_l,e)=>{assert.equal(e.writes.length,1);assert.equal(e.stored().pixels.length,256);});await withUI(undefined,async(r,_l,e)=>{await gesture(r,[[1,1],[3,1]]);assert.equal(e.stored().pixels.filter(Boolean).length,3);assert.match(ctl(r,'像素统计').textContent,/撤销1\/100/);const c=ctl(r,'像素画布');c.focus();await c.fire('keydown',{key:'ArrowDown'});await c.fire('keydown',{key:' ',repeat:true});assert.equal(e.stored().pixels.filter(Boolean).length,3);await c.fire('keydown',{key:' '});await idle();assert.equal(e.stored().pixels[2*16+3],'#e4583f');await btn(r,'撤销最近整笔').fire('click');await idle();assert.equal(e.stored().pixels.filter(Boolean).length,3);await tool(r,'eraser');await gesture(r,[[2,1]]);assert.equal(e.stored().pixels[18],null);await tool(r,'picker');await gesture(r,[[1,1]]);assert.equal(e.stored().tool,'pencil');assert.equal(e.stored().ink,'#e4583f');await tool(r,'picker');await gesture(r,[[0,0]]);assert.equal(e.stored().tool,'eraser');await tool(r,'pencil');ctl(r,'像素列x').value='5';ctl(r,'像素行y').value='6';await btn(r,'在坐标格执行工具').fire('click');await idle();assert.equal(e.stored().pixels[6*16+5],'#e4583f');ctl(r,'像素列x').value='';await btn(r,'在坐标格执行工具').fire('click');assert.match(ctl(r,'操作状态').textContent,/整数/);});});
test('E011 UI capture exactdrag/secondary ignored/outsidecancel/lostcapture hidden and deactivate rollback no stale events',async()=>{await withUI(undefined,async(r,life,e)=>{let c=ctl(r,'像素画布');await c.fire('pointerdown',{...at(1,1),pointerId:9});assert.equal(c.hasPointerCapture(9),true);assert.equal(ctl(r,'像素工具').disabled,true);await c.fire('pointerdown',{...at(10,10),pointerId:10,isPrimary:false});await c.fire('pointermove',{...at(5,1),pointerId:10});await c.fire('pointerup',{...at(5,1),pointerId:10});assert.equal(e.writes.length,0);await c.fire('pointermove',{...at(2,1),pointerId:9});await c.fire('pointermove',{clientX:600,clientY:40,pointerId:9});assert.equal(c.hasPointerCapture(9),false);assert.match(ctl(r,'像素统计').textContent,/已画0/);await c.fire('pointerup',{...at(5,1),pointerId:9});assert.equal(e.writes.length,0);await c.fire('pointerdown',at(1,1));await c.fire('lostpointercapture');assert.match(ctl(r,'像素统计').textContent,/已画0/);await c.fire('pointerdown',at(1,1));e.hidden(true);await idle();e.hidden(false);assert.ok(e.stored().pixels.every(v=>v===null));c=ctl(r,'像素画布');await c.fire('pointerdown',at(1,1));life.deactivate();await idle();life.activate();assert.ok(e.stored().pixels.every(v=>v===null));assert.equal(c.hasPointerCapture(1),false);await c.fire('pointerup',at(2,2));assert.ok(e.stored().pixels.every(v=>v===null));const old=ctl(r,'像素画布');life.destroy();assert.equal(old.width,0);assert.equal(old.listeners.pointerdown.length,0);assert.equal(e.events.visibilitychange.length,0);assert.equal(r.children.length,0);});});
test('E011 UI mirror and originalfill one undo, color validation and confirmed16/32newcanvas',async()=>{await withUI(undefined,async(r,_l,e)=>{ctl(r,'自定义像素HEX').value='#ABCDEF';await btn(r,'应用自定义颜色').fire('click');await idle();assert.equal(e.stored().ink,'#abcdef');ctl(r,'自定义像素HEX').value='#ff00gg';await btn(r,'应用自定义颜色').fire('click');assert.match(ctl(r,'操作状态').textContent,/#RRGGBB/);ctl(r,'像素镜像').value='both';await ctl(r,'像素镜像').fire('change');await idle();await gesture(r,[[0,0]]);assert.equal(e.stored().pixels.filter(Boolean).length,4);await btn(r,'撤销最近整笔').fire('click');await idle();assert.equal(e.stored().pixels.filter(Boolean).length,0);await tool(r,'fill');await gesture(r,[[1,1]]);assert.equal(e.stored().pixels.filter(Boolean).length,256);assert.match(ctl(r,'像素统计').textContent,/撤销1\/100/);await btn(r,'撤销最近整笔').fire('click');await idle();assert.equal(e.stored().pixels.filter(Boolean).length,0);ctl(r,'新建像素尺寸').value='32';await btn(r,'确认新建空像素画布').fire('click');assert.equal(e.stored().size,16);ctl(r,'确认放弃像素当前作品').checked=true;await btn(r,'确认新建空像素画布').fire('click');await idle();assert.equal(e.stored().size,32);assert.equal(e.stored().pixels.length,1024);});});
test('E011 UI FileAPI restores all1024 colors/settings withconfirmation, sizeUTF8/futureversion rejects; savefailure retry',async()=>{const m=await model,g=m.createProject(32);g.pixels[0]='#123456';g.pixels[1023]='#abcdef';g.tool='fill';g.mirror='both';const bytes=Buffer.from(m.encode(m.source(g)));await withUI(undefined,async(r,_l,e)=>{ctl(r,'像素工程JSON').files=[{size:bytes.length,arrayBuffer:async()=>new Uint8Array(bytes).buffer}];await ctl(r,'像素工程JSON').fire('change');await idle();await btn(r,'应用像素工程').fire('click');assert.equal(e.writes.length,0);ctl(r,'确认替换像素全部工程').checked=true;await btn(r,'应用像素工程').fire('click');await idle();assert.deepEqual(e.stored(),m.source(g));assert.match(ctl(r,'像素统计').textContent,/撤销0\/100/);for(const f of[{size:65537,arrayBuffer:()=>assert.fail('oversize read')},{size:1,arrayBuffer:async()=>Uint8Array.of(255).buffer}]){ctl(r,'像素工程JSON').files=[f];await ctl(r,'像素工程JSON').fire('change');await idle();assert.equal(btn(r,'应用像素工程').disabled,true);assert.deepEqual(e.stored(),m.source(g));}});await withUI({schema:2},async(r,_l,e)=>{await btn(r,'从空像素工程开始').fire('click');assert.equal(e.writes.length,0);ctl(r,'确认清空无效像素工程').checked=true;await btn(r,'从空像素工程开始').fire('click');await idle();assert.equal(e.stored().schema,1);});let fail=true;await withUI(undefined,async r=>{await gesture(r,[[1,1]]);assert.match(ctl(r,'像素保存状态').textContent,/失败.*临时/);fail=false;await btn(r,'重试本地保存').fire('click');assert.match(ctl(r,'像素保存状态').textContent,/已保存/);},{config:{get:()=>m.source(m.createProject()),set:async()=>{if(fail)throw Error('disk');}}});});
test('E011 UI JSONMDPNGcopyOnly allpixels exactalpha imageData/hash/release strictresponse and late sourcecallback',async()=>{await withUI(undefined,async(r,_l,e)=>{await gesture(r,[[1,1],[3,1]]);for(const label of['另存像素JSON新副本','另存完整像素Markdown','另存原尺寸透明PNG'])await btn(r,label).fire('click');assert.ok(e.calls.every(p=>p.copyOnly===true));assert.deepEqual(JSON.parse(e.calls[0].content),e.stored());assert.equal(e.calls[2].sha256,crypto.createHash('sha256').update(Buffer.from(e.calls[2].base64,'base64')).digest('hex'));const out=e.canvases.find(c=>c.lastImage);assert.deepEqual(Buffer.from(out.lastImage),opaque(e.stored().pixels));assert.equal(out.width,0);assert.equal(out.height,0);});let response;await withUI(undefined,async r=>{for(response of[{ok:'true'},{canceled:true},{ok:false,error:'exists'},{ok:false,partialPath:'manual'}]){await btn(r,'另存原尺寸透明PNG').fire('click');assert.match(ctl(r,'操作状态').textContent,response.canceled?/已取消/:response.partialPath?/人工核对 manual/:/另存失败/);}},{files:{saveBinarySupportsCopyOnly:true,saveBinary:async()=>response}});await withUI(undefined,async r=>{assert.equal(btn(r,'另存原尺寸透明PNG').disabled,true);assert.equal(btn(r,'另存像素JSON新副本').disabled,true);},{files:{}});let finish;await withUI(undefined,async(r,life)=>{const pending=btn(r,'另存像素JSON新副本').fire('click');await idle();life.deactivate();await idle();life.activate();await gesture(r,[[5,5]]);finish({ok:true});await pending;assert.ok(!ctl(r,'操作状态').textContent.includes('已另存'));assert.match(ctl(r,'像素统计').textContent,/已画1/);},{files:{saveTextSupportsCopyOnly:true,saveText:()=>new Promise(r=>{finish=r;})}});});
test('E011 pendingdisk locks brush/settings, lifecycle retains onlycommitted paint no rendering onreturn',async()=>{const m=await model;let finish,writes=0,stored;await withUI(undefined,async(r,life)=>{const c=ctl(r,'像素画布');await c.fire('pointerdown',at(1,1));await c.fire('pointerup',at(1,1));assert.equal(ctl(r,'像素工具').disabled,true);life.deactivate();life.activate();finish();await idle();assert.equal(writes,2);assert.equal(stored.pixels.filter(Boolean).length,1);assert.match(ctl(r,'操作状态').textContent,/已离开/);},{config:{get:()=>m.source(m.createProject()),set:async(_k,v)=>{stored=clone(v);writes++;if(writes===1)await new Promise(r=>{finish=r;});}}});});
test('E011 full1024cell colors and100 maximalfill undo transactions bounded, source remains small and complete',async()=>{const m=await model,g=m.createProject(32);for(let i=0;i<101;i++){const tx=m.begin(g);m.fill(g,tx,0,0,i%2?'#000000':'#ffffff');m.commit(g,tx);}assert.equal(g.history.length,100);assert.equal(g.history.reduce((n,v)=>n+v.length,0),102400);const source=m.source(g),text=m.encode(source);assert.equal(source.pixels.length,1024);assert.ok(source.pixels.every(c=>c==='#ffffff'));assert.ok(Buffer.byteLength(text)<65536);assert.deepEqual(m.source(m.parse(text)),source);for(let i=0;i<100;i++)m.undo(g);assert.ok(g.pixels.every(c=>c==='#ffffff'));assert.equal(m.undo(g),false);});
test('E011 UI Escape rolls back capture; outofbounds numeric rejects withoutchanging cursor or source',async()=>{await withUI(undefined,async(r,_l,e)=>{const c=ctl(r,'像素画布');await c.fire('pointerdown',at(1,1));await c.fire('pointermove',at(5,1));await c.fire('keydown',{key:'Escape'});assert.equal(c.hasPointerCapture(1),false);assert.match(ctl(r,'像素统计').textContent,/已画0/);assert.equal(e.writes.length,0);const old=ctl(r,'像素统计').textContent;ctl(r,'像素列x').value='16';ctl(r,'像素行y').value='0';await btn(r,'在坐标格执行工具').fire('click');assert.match(ctl(r,'操作状态').textContent,/画布内整数/);assert.equal(ctl(r,'像素统计').textContent,old);assert.equal(e.writes.length,0);});});
}else nativeCheck().catch(e=>{console.error(e);require('electron').app.exit(1);});

async function nativeCheck(){
 const{app,BrowserWindow,ipcMain,session,nativeImage}=require('electron'),os=require('node:os'),{pathToFileURL}=require('node:url'),rootDir=path.resolve(__dirname,'..'),evidence=fs.mkdtempSync(path.join(os.tmpdir(),'agent-toolbox-E011-native-'));
 app.setPath('userData',path.join(evidence,'profile'));app.disableHardwareAcceleration();const m=await model;await app.whenReady();const{Store}=require('../src/main/store'),store=new Store(app.getPath('userData')),writes=[],texts=[],binaries=[],requests=[],permissions=[];
 ipcMain.handle('config:all',()=>store.all());ipcMain.handle('config:set',(_e,k,v)=>{writes.push(clone(v));return store.set(k,v);});ipcMain.handle('features:list',()=>require('../src/main/feature-catalog').listFeatures(path.join(rootDir,'src/renderer/features')));
 ipcMain.handle('files:saveText',(_e,p)=>{const target=path.join(evidence,p.defaultName),result=require('../src/main/text-export').writeText(target,p.content,p.copyOnly===true);texts.push({target,result});return result;});ipcMain.handle('files:saveBinary',(_e,p)=>{const target=path.join(evidence,p.defaultName),result=require('../src/main/feature-binary').writeBinaryCopy(target,p);binaries.push({target,result});return result;});
 session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(d,cb)=>{requests.push(d.url);cb({cancel:true});});session.defaultSession.setPermissionRequestHandler((_wc,p,cb)=>{permissions.push(p);cb(false);});
 const url=p=>pathToFileURL(path.join(rootDir,p)).href,fixture=path.join(evidence,'fixture.html');fs.writeFileSync(fixture,`<html><head><meta charset="UTF-8"><style>body{font:15px sans-serif;margin:0;background:white}button,input,select{margin:5px}</style></head><body><main id="root"></main><script type="module">
 import feature from ${JSON.stringify(url('src/renderer/features/E011/index.js'))};import{Config}from ${JSON.stringify(url('src/renderer/core/config.js'))};window.root=document.getElementById('root');window.config=await Config.load();window.rafRequests=0;window.intervalRequests=0;const raf=requestAnimationFrame.bind(window),si=setInterval.bind(window);window.requestAnimationFrame=f=>{rafRequests++;return raf(f);};window.setInterval=(f,n)=>{intervalRequests++;return si(f,n);};window.life=feature.create(root,{config});life.activate();window.ctl=t=>root.querySelector('[aria-label="'+t+'"]');window.btn=t=>[...root.querySelectorAll('button')].find(n=>n.textContent===t);window.wait=async f=>{for(let i=0;i<2000;i++){if(f())return;await new Promise(r=>setTimeout(r,10));}throw Error('native timeout: '+ctl('操作状态').innerText);};window.pointerId=null;root.addEventListener('pointerdown',e=>{if(e.target.tagName==='CANVAS')pointerId=e.pointerId;});window.ready=true;</script></body></html>`,{flag:'wx'});
 const win=new BrowserWindow({show:false,width:1050,height:1400,webPreferences:{preload:path.join(rootDir,'src/main/preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,offscreen:true,backgroundThrottling:false}}),js=s=>win.webContents.executeJavaScript(s);win.webContents.setFrameRate(60);
 async function ready(){await js(`(async()=>{for(let i=0;i<2000;i++){if(window.ready)return;await new Promise(r=>setTimeout(r,10));}throw Error('ready timeout');})()`);}await win.loadFile(fixture);await ready();assert.ok((await js('toolbox.features.list()')).features.some(f=>f.id==='E011'));
 async function point(expression){return js(`(()=>{const b=${expression};if(!b||b.disabled)throw Error('disabled');b.scrollIntoView({block:'center'});const r=b.getBoundingClientRect();return{x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);}
 async function send(type,p,held=false){win.webContents.sendInputEvent({type,...p,...(type==='mouseMove'?held?{modifiers:['leftButtonDown']}:{ }:{button:'left',clickCount:1,...(type==='mouseDown'?{modifiers:['leftButtonDown']}:{})})});await js('new Promise(r=>setTimeout(r,20))');}
 async function click(label,control=false){const p=await point(`${control?'ctl':'btn'}(${JSON.stringify(label)})`);await send('mouseMove',p);await send('mouseDown',p);await send('mouseUp',p);}
 const idle=()=>js(`wait(()=>!ctl('像素工具').disabled)`),key='featureLab.E011.project';await idle();
 async function reload(){const done=new Promise(r=>win.webContents.once('did-finish-load',r));win.reload();await done;await ready();await idle();}
 async function xy(x,y){const n=store.get(key).size;return js(`(()=>{const c=ctl('像素画布');c.scrollIntoView({block:'center'});const r=c.getBoundingClientRect();return{x:Math.round(r.x+(${x}+.5)*r.width/${n}),y:Math.round(r.y+(${y}+.5)*r.height/${n})};})()`);}
 let captureChecks=0;async function pen(points){await send('mouseMove',await xy(...points[0]));await send('mouseDown',await xy(...points[0]));assert.equal(await js(`ctl('像素画布').hasPointerCapture(pointerId)`),true);captureChecks++;for(const p of points.slice(1))await send('mouseMove',await xy(...p),true);await send('mouseUp',await xy(...points.at(-1)));await idle();}
 async function cell(x,y){const p=await xy(x,y);await send('mouseMove',p);await send('mouseDown',p);await send('mouseUp',p);await idle();}
 async function setting(label,value){await js(`ctl(${JSON.stringify(label)}).value=${JSON.stringify(value)};ctl(${JSON.stringify(label)}).dispatchEvent(new Event('change'))`);await idle();}
 async function exportPNG(expected,n){await click('另存原尺寸透明PNG');await js(`wait(()=>ctl('操作状态').innerText.includes('已另存完整新副本'))`);const file=binaries.at(-1);assert.equal(file.result.ok,true);const image=nativeImage.createFromPath(file.target);assert.deepEqual(image.getSize(),{width:n,height:n});const b=image.getBitmap(),reference=opaque(expected);for(let i=0;i<n*n;i++)assert.deepEqual([b[i*4+2],b[i*4+1],b[i*4],b[i*4+3]],[...reference.subarray(i*4,i*4+4)],`independent RGBA ${n}/${i}`);assert.equal(file.result.sha256,crypto.createHash('sha256').update(fs.readFileSync(file.target)).digest('hex'));return file.target;}
 async function exportText(){for(const label of['另存像素JSON新副本','另存完整像素Markdown']){await click(label);await js(`wait(()=>ctl('操作状态').innerText.includes('已另存完整新副本'))`);}return texts.at(-2).target;}
 async function capture(name){await js(`ctl('像素画布').scrollIntoView({block:'center'});new Promise(r=>setTimeout(r,80))`);const r=await js(`(()=>{const r=ctl('像素画布').getBoundingClientRect();return{x:Math.round(r.x),y:Math.round(r.y),width:Math.round(r.width),height:Math.round(r.height)};})()`),file=path.join(evidence,name);fs.writeFileSync(file,(await win.webContents.capturePage(r)).toPNG(),{flag:'wx'});return file;}
 const expected16=Array(256).fill(null);[17,18,19].forEach(i=>{expected16[i]='#e4583f';});await pen([[1,1],[3,1]]);assert.deepEqual(store.get(key).pixels,expected16);assert.match(await js(`ctl('像素统计').innerText`),/撤销1\/100/);
 await js(`ctl('像素画布').focus()`);for(const keyCode of['Down','Space']){win.webContents.sendInputEvent({type:'keyDown',keyCode});win.webContents.sendInputEvent({type:'keyUp',keyCode});await js('new Promise(r=>setTimeout(r,20))');await idle();}assert.equal(store.get(key).pixels[35],'#e4583f');await click('撤销最近整笔');await idle();assert.deepEqual(store.get(key).pixels,expected16);
 await setting('像素工具','eraser');await cell(2,1);assert.equal(store.get(key).pixels[18],null);await click('撤销最近整笔');await idle();await setting('像素工具','picker');await cell(1,1);assert.equal(store.get(key).tool,'pencil');await setting('像素工具','picker');await cell(0,0);assert.equal(store.get(key).tool,'eraser');await setting('像素工具','pencil');
 await setting('像素镜像','both');await pen([[0,0]]);assert.equal(store.get(key).pixels.filter(Boolean).length,7);await click('撤销最近整笔');await idle();await setting('像素镜像','none');await setting('像素工具','fill');await cell(0,0);assert.equal(store.get(key).pixels.filter(Boolean).length,256);await click('撤销最近整笔');await idle();await setting('像素工具','pencil');assert.deepEqual(store.get(key).pixels,expected16);
 // Genuine capture then move outside, not a clamped stroke; source must stay unchanged.
 const beforeOutside=clone(store.get(key));await send('mouseMove',await xy(1,5));await send('mouseDown',await xy(1,5));assert.equal(await js(`ctl('像素画布').hasPointerCapture(pointerId)`),true);await send('mouseMove',await xy(5,5),true);const outside=await js(`(()=>{const r=ctl('像素画布').getBoundingClientRect();return{x:Math.round(r.x-6),y:Math.round(r.y+20)};})()`);await send('mouseMove',outside,true);await send('mouseUp',outside);await idle();assert.deepEqual(store.get(key),beforeOutside);assert.equal(await js(`ctl('像素画布').hasPointerCapture(pointerId)`),false);assert.match(await js(`ctl('操作状态').innerText`),/回滚/);
 await send('mouseMove',await xy(8,8));await send('mouseDown',await xy(8,8));assert.equal(await js(`ctl('像素画布').hasPointerCapture(pointerId)`),true);await js(`life.deactivate();wait(()=>ctl('像素保存状态').innerText.includes('已保存'))`);await js('life.activate()');await send('mouseUp',await xy(8,8));await idle();assert.deepEqual(store.get(key),beforeOutside);await reload();assert.deepEqual(store.get(key).pixels,expected16);assert.match(await js(`ctl('像素统计').innerText`),/撤销0\/100/);
 const png16=await exportPNG(expected16,16),json16=await exportText(),source16=clone(store.get(key)),preview16=await capture('preview-16.png');assert.equal(nativeImage.createFromPath(png16).getBitmap().filter((_v,i)=>i%4===3&&nativeImage.createFromPath(png16).getBitmap()[i]===0).length,253);
 await js(`ctl('新建像素尺寸').value='32'`);await click('确认新建空像素画布');assert.equal(store.get(key).size,16);await click('确认放弃像素当前作品',true);await click('确认新建空像素画布');await idle();assert.equal(store.get(key).size,32);
 const expected32=Array(1024).fill(null);for(let y=4;y<=27;y++)for(let x=4;x<=27;x++)if(x===4||x===27||y===4||y===27)expected32[y*32+x]='#e4583f';await pen([[4,4],[27,4],[27,27],[4,27],[4,4]]);assert.deepEqual(store.get(key).pixels,expected32);assert.equal(expected32.filter(Boolean).length,92);
 await click('#2b8a78');await idle();await setting('像素工具','fill');const region=bfs(expected32,32,16*32+16);assert.equal(region.length,484);region.forEach(i=>{expected32[i]='#2b8a78';});await cell(16,16);assert.deepEqual(store.get(key).pixels,expected32);
 await setting('像素工具','picker');await cell(4,4);assert.equal(store.get(key).ink,'#e4583f');await click('#f5c557');await idle();await setting('像素镜像','horizontal');await pen([[10,10]]);expected32[10*32+10]=expected32[10*32+21]='#f5c557';await js(`ctl('像素画布').focus()`);for(const keyCode of['Down','Space']){win.webContents.sendInputEvent({type:'keyDown',keyCode});win.webContents.sendInputEvent({type:'keyUp',keyCode});await js('new Promise(r=>setTimeout(r,20))');await idle();}expected32[11*32+10]=expected32[11*32+21]='#f5c557';assert.deepEqual(store.get(key).pixels,expected32);
 await setting('像素工具','eraser');await pen([[15,20]]);expected32[20*32+15]=expected32[20*32+16]=null;assert.deepEqual(store.get(key).pixels,expected32);const source32=clone(store.get(key)),png32=await exportPNG(expected32,32),json32=await exportText(),preview32=await capture('preview-32.png');assert.equal(source32.pixels.filter(Boolean).length,574);await reload();assert.deepEqual(store.get(key),source32);assert.match(await js(`ctl('像素统计').innerText`),/撤销0\/100/);
 const pngSHA=crypto.createHash('sha256').update(fs.readFileSync(png32)).digest('hex'),jsonSHA=crypto.createHash('sha256').update(fs.readFileSync(json32)).digest('hex');await click('另存原尺寸透明PNG');await js(`wait(()=>ctl('操作状态').innerText.includes('另存失败'))`);assert.equal(binaries.at(-1).result.ok,false);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(png32)).digest('hex'),pngSHA);await click('另存像素JSON新副本');await js(`wait(()=>ctl('操作状态').innerText.includes('另存失败'))`);assert.equal(texts.at(-1).result.ok,false);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(json32)).digest('hex'),jsonSHA);
 async function importFile(file,expected){const bytes=fs.readFileSync(file);await js(`(()=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(${JSON.stringify([...bytes])})],'像素工程.json',{type:'application/json'}));ctl('像素工程JSON').files=dt.files;ctl('像素工程JSON').dispatchEvent(new Event('change'));})();wait(()=>ctl('像素导入预览').innerText.includes('已校验'))`);const before=clone(store.get(key));await click('应用像素工程');assert.deepEqual(store.get(key),before);await click('确认替换像素全部工程',true);await click('应用像素工程');await idle();assert.deepEqual(store.get(key),expected);await reload();assert.deepEqual(store.get(key),expected);}
 await importFile(json16,source16);await importFile(json32,source32);for(const f of texts.filter(t=>t.target.endsWith('.md')&&t.result.ok)){const data=fs.readFileSync(f.target,'utf8'),s=JSON.parse(data.match(/```json\n([\s\S]*?)\n```/)[1]);assert.deepEqual(s,s.size===16?source16:source32);assert.equal(data.split('\n').filter(l=>/^\|\d+\|/.test(l)).length,s.size*s.size);}
 await js('life.deactivate();wait(()=>ctl("像素保存状态").innerText.includes("已保存"));');const frozen=clone(store.get(key)),writeCount=writes.length;await js('life.activate();new Promise(r=>setTimeout(r,400))');assert.deepEqual(store.get(key),frozen);assert.equal(writes.length,writeCount);assert.equal(await js('rafRequests'),0);assert.equal(await js('intervalRequests'),0);await js('life.destroy();new Promise(r=>setTimeout(r,100))');assert.equal(await js('root.childNodes.length'),0);assert.equal(await js('rafRequests'),0);assert.deepEqual(requests,[]);assert.deepEqual(permissions,[]);
 console.log(JSON.stringify({evidence,pngs:[png16,png32],previews:[preview16,preview32],actualCaptureChecks:captureChecks,threeCells16:true,transparent16Pixels:253,all1280RGBA:true,actualKeyboardDownSpace:true,wholeStrokeUndo:true,realOutsideCaptureRollback:true,deactivateCaptureRollback:true,realToolOperations:['pencil','eraser','fill','picker','mirror'],independentBFS32Interior:484,painted32:574,transparent32:450,fullFileAPIRoundtrip:true,actualReloadBothSizes:true,source32Tool:source32.tool,source32Mirror:source32.mirror,pngSHA256:pngSHA,jsonSHA256:jsonSHA,textSaves:texts,binarySaves:binaries,configBytes:fs.statSync(store.file).size,returnNoAutodraw:true,rafRequests:0,intervalRequests:0,networkRequests:0,permissions:0,boundary:'Hidden/offscreen production Electron/preload/catalog/Config/Store/text/binary WX, actualmouse capture/drag+keyboard and FileAPI/reload. Tool selectors use native DOM change; IPC isolated targets replace OSdialog. PNG all original RGBA exact; previews are complete canvas crops, not whole-page screenshots. Fullapp/crossOS untested.'}));win.destroy();app.quit();
}
