const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const model=()=>import('../src/renderer/features/L046/model.mjs');
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type, extra = {}) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this, preventDefault() {}, stopPropagation() {}, ...extra }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }
const tick=()=>new Promise(r=>setImmediate(r));async function until(fn){for(let i=0;i<1000;i++){if(fn())return;await tick();}throw Error('timeout');}
async function mount(t, files={saveTextSupportsCopyOnly:true,saveText:async()=>({ok:true})},config={}){dom(t,files);const tool=(await import('../src/renderer/features/L046/index.js')).default;const root=new NodeStub('div'),life=tool.create(root,{config:{get:()=>null,...config}});return{root,life,tool};}
const copy=x=>JSON.parse(JSON.stringify(x));const build=e=>button(e.root,'生成完整人工链报告').fire('click');
async function checkCandidate(root,id,entity,value){const node=control(root,`${id}候选${entity}`);node.checked=value;await node.fire('change');}
function select(root,start,end){const node=control(root,'原文');node.selectionStart=start;node.selectionEnd=end;}
test('L046 independent3-reference oracle exactly2 bindings and1 unknown list',async()=>{const m=await model(),d=m.exampleDraft(),p=m.makeReport(d);assert.deepEqual(p.totals,{entities:2,references:3,declaredBound:2,effectiveBound:2,unbound:1,explicitUnknown:1,ambiguous:0,conflicts:0,staleAnnotations:0});assert.deepEqual(p.unbound,[{id:'R3',quote:'这',resolution:'unknown',candidates:['E1','E2'],boundEntityId:null,reasons:['unknown']}]);assert.deepEqual(p.chains,[{entityId:'E1',entityName:'机器人',current:true,boundReferenceIds:['R1'],candidateReferenceIds:['R1','R3']},{entityId:'E2',entityName:'研究员',current:true,boundReferenceIds:['R2'],candidateReferenceIds:['R1','R2','R3']}]);assert.equal(p.input.source.text,d.source.text);});
test('L046 multi candidate is unresolved once, explicit unknown remains even one candidate',async()=>{const m=await model(),d=m.exampleDraft();d.references[2].resolution='ambiguous';let p=m.makeReport(d);assert.equal(p.unbound.length,1);assert.deepEqual(p.unbound[0].reasons,['ambiguous']);assert.equal(p.totals.conflicts,0);d.references[2].resolution='unknown';d.references[2].candidates=['E1'];p=m.makeReport(d);assert.equal(p.unbound.length,1);assert.equal(p.unbound[0].resolution,'unknown');assert.equal(p.totals.effectiveBound,2);});
test('L046 all3 explicit manual bindings linked, no auto merge equal entity names',async()=>{const m=await model(),d=m.exampleDraft();d.entities[1].name='机器人';d.references[2].resolution='bound';d.references[2].boundEntityId='E1';const p=m.makeReport(d);assert.equal(p.unbound.length,0);assert.deepEqual(p.chains[0].boundReferenceIds,['R1','R3']);assert.deepEqual(p.chains[1].boundReferenceIds,['R2']);assert.equal(p.entities.length,2);assert.equal(p.entities[0].name,p.entities[1].name);});
test('L046 conflict definitions exactly overlap/outside/few candidates not semantic guesses',async()=>{const m=await model(),d=m.exampleDraft();d.references[0].candidates=['E2'];d.references[2].resolution='ambiguous';d.references[2].candidates=['E1'];let p=m.makeReport(d);assert.deepEqual(p.conflicts.map(c=>c.kind),['binding-outside-candidates','ambiguous-with-fewer-than-two-candidates']);assert.equal(p.unbound.length,1);assert.equal(p.totals.effectiveBound,2);const overlap=m.addAnnotation(m.exampleDraft(),'reference',9,10);p=m.makeReport(overlap);assert.equal(p.conflicts.length,1);assert.deepEqual(p.conflicts[0].ids,['R1','R4']);assert.equal(p.conflicts[0].kind,'span-overlap');assert.equal(p.unbound.length,2);const adjacent=m.addAnnotation(m.exampleDraft(),'reference',10,11);assert.equal(m.makeReport(adjacent).conflicts.length,0);});
test('L046 source edit invalidates all even same substrings and old positions never drift',async()=>{const m=await model(),d=m.exampleDraft(),frozen=copy(d),next=m.changeText(d,'前缀'+d.source.text),p=m.makeReport(next);assert.equal(next.source.revision,2);assert.deepEqual(next.entities,d.entities);assert.deepEqual(next.references,d.references);assert.equal(p.staleAnnotations.length,5);assert.equal(p.totals.effectiveBound,0);assert.equal(p.unbound.length,3);assert.ok(p.chains.every(c=>c.boundReferenceIds.length===0&&c.candidateReferenceIds.length===0));assert.deepEqual(d,frozen);const appendix=m.changeText(d,d.source.text+'附加');assert.equal(m.makeReport(appendix).staleAnnotations.length,5);assert.equal(m.changeText(d,d.source.text).source.revision,1);});
test('L046 reanchor explicit indices restores links while old binding preserved and new quote full',async()=>{const m=await model(),old=m.exampleDraft();let d=m.changeText(old,'前缀'+old.source.text);for(const row of old.entities)d=m.reanchor(d,'entity',row.id,row.start+2,row.end+2);for(const row of old.references)d=m.reanchor(d,'reference',row.id,row.start+2,row.end+2);const p=m.makeReport(d);assert.equal(p.staleAnnotations.length,0);assert.equal(p.unbound.length,1);assert.equal(d.references[0].boundEntityId,'E1');assert.equal(d.references[0].start,11);assert.equal(d.references[0].quote,'它');assert.equal(old.references[0].start,9);});
test('L046 short text stale out-of-bounds stored/report complete not auto discard',async()=>{const m=await model(),d=m.changeText(m.exampleDraft(),'短');assert.ok(m.validateDraft(d,{forStorage:true}));const p=m.makeReport(d);assert.equal(p.staleAnnotations.length,5);assert.equal(p.unbound.length,3);assert.equal(p.input.references[2].quote,'这');assert.equal(p.input.references[2].start,16);assert.ok(p.staleAnnotations.some(row=>row.reasons.includes('outside-current-text')));assert.throws(()=>m.reanchor(d,'reference','R1',9,10),/越过/);});
test('L046 current quote mismatch flagged stale not silently searched and bound target stale unresolved',async()=>{const m=await model(),d=m.exampleDraft();d.entities[0].quote='错误实体';let p=m.makeReport(d);assert.equal(p.staleAnnotations.length,1);assert.equal(p.unbound.length,2);assert.deepEqual(p.unbound.find(row=>row.id==='R1').reasons,['bound-entity-anchor-stale']);assert.equal(p.chains[0].boundReferenceIds.length,0);d.references[1].quote='它';p=m.makeReport(d);assert.equal(p.unbound.length,3);assert.deepEqual(p.references[1].anchor.reasons,['quote-mismatch']);});
test('L046 UTF16 emoji boundaries/CRLF/LF/CR and full source positions independent oracle',async()=>{const m=await model(),d={schemaVersion:1,source:{label:'',location:'',text:'🙂甲\r\n它\n乙\r他',revision:1},entities:[],references:[]};const added=m.addAnnotation(d,'entity',0,2);assert.equal(added.entities[0].quote,'🙂');assert.throws(()=>m.addAnnotation(d,'entity',1,2),/代理/);assert.throws(()=>m.addAnnotation(d,'reference',0,1),/代理/);const r=m.addAnnotation(m.addAnnotation(added,'reference',5,6),'reference',9,10),p=m.makeReport(r);assert.deepEqual(p.references.map(n=>[n.quote,n.anchor.lineNumber,n.anchor.columnUtf16]),[['它',2,1],['他',4,1]]);assert.deepEqual(m.sourceSelectionRange(d.source.text,'🙂甲\n它\n乙\n他',4,5),[5,6]);assert.deepEqual(m.sourceSelectionRange(d.source.text,'🙂甲\n它\n乙\n他',8,9),[9,10]);assert.throws(()=>m.sourceSelectionRange(d.source.text,'wrong',0,1),/不符/);assert.equal(m.spanQuote(d.source.text,2,3),'甲');assert.throws(()=>m.spanQuote(d.source.text,3,5),/非空/);});
test('L046 exact20entities40references complete capacity21/41 refusal no truncation',async()=>{const m=await model();let d={schemaVersion:1,source:{label:'',location:'',text:'甲'.repeat(100),revision:1},entities:[],references:[]};for(let i=0;i<20;i++)d=m.addAnnotation(d,'entity',i,i+1);for(let i=0;i<40;i++)d=m.addAnnotation(d,'reference',20+i,21+i);const p=m.makeReport(d);assert.equal(p.entities.length,20);assert.equal(p.references.length,40);assert.equal(p.unbound.length,40);assert.equal(p.conflicts.length,0);assert.throws(()=>m.addAnnotation(d,'entity',60,61),/最多20/);assert.throws(()=>m.addAnnotation(d,'reference',60,61),/最多40/);assert.equal(JSON.parse(m.reportJson(p)).references.length,40);});
test('L046 removal protects candidate/binding references and user manually clears before delete',async()=>{const m=await model(),d=m.exampleDraft();assert.throws(()=>m.removeAnnotation(d,'entity','E1'),/先人工解除/);assert.equal(m.removeAnnotation(d,'reference','R3').references.length,2);for(const row of d.references){row.candidates=row.candidates.filter(id=>id!=='E1');if(row.boundEntityId==='E1'){row.resolution='unknown';row.boundEntityId=null;}}const next=m.removeAnnotation(d,'entity','E1');assert.equal(next.entities.length,1);assert.equal(m.makeReport(next).unbound.length,2);assert.throws(()=>m.removeAnnotation(next,'other','E2'),/未知/);});
test('L046 schema unknown/duplicate/null resolution/UTF limits and64KiB whole no derived',async()=>{const m=await model(),d=m.exampleDraft();for(const change of[x=>x.schemaVersion=2,x=>x.extra='report',x=>x.entities[1].id='E1',x=>x.references[1].id='R1',x=>x.references[0].candidates=['E1','E1'],x=>x.references[0].candidates=['MISSING'],x=>x.references[0].boundEntityId=null,x=>x.references[2].boundEntityId='E1',x=>x.entities[0].textRevision=2,x=>x.references[0].start=-1]){const next=copy(d);change(next);assert.throws(()=>m.validateDraft(next));}const big=m.changeText(d,'🙂'.repeat(16000));big.source.label='🙂'.repeat(160);big.source.location='🙂'.repeat(320);assert.ok(m.validateDraft(big));assert.throws(()=>m.validateDraft(big,{forStorage:true}),/64KiB/);assert.throws(()=>m.changeText(d,'🙂'.repeat(16001)),/16000/);assert.throws(()=>m.spanQuote('甲'.repeat(241),0,241),/240/);});
test('L046 UI core exact1unbound full chains and JSONMD strict original source preserved',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});await build(e);assert.equal(walk(e.root).filter(n=>n.dataset.unbound==='R3').length,1);assert.equal(walk(e.root).filter(n=>n.dataset.unbound).length,1);await button(e.root,'导出完整 JSON').fire('click');await button(e.root,'导出完整 Markdown').fire('click');const p=JSON.parse(calls[0].content);assert.equal(p.unbound.length,1);assert.equal(p.input.source.text,'机器人见到研究员。它递给他报告，这让人意外。');assert.ok(calls.every(c=>c.copyOnly===true));e.life.destroy();});
test('L046 UI multi candidates/unknown/bind and conflict outside candidate interactively work',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});await fill(e.root,'R3人工绑定','ambiguous');await build(e);await button(e.root,'导出完整 JSON').fire('click');assert.equal(JSON.parse(calls[0].content).unbound.length,1);await fill(e.root,'R3人工绑定','E1');await checkCandidate(e.root,'R3','E1',false);await build(e);assert.match(e.root.textContent,/binding-outside-candidates/);await button(e.root,'导出完整 JSON').fire('click');assert.equal(JSON.parse(calls[1].content).unbound.length,0);assert.equal(JSON.parse(calls[1].content).conflicts.length,1);await fill(e.root,'R3人工绑定','unknown');await checkCandidate(e.root,'R3','E1',true);await build(e);assert.match(e.root.textContent,/未绑定1处/);e.life.destroy();});
test('L046 UI source edit stale complete and explicit confirm/reselect restores without guessing',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});await fill(e.root,'原文','前缀机器人见到研究员。它递给他报告，这让人意外。');await build(e);await button(e.root,'导出完整 JSON').fire('click');let p=JSON.parse(calls[0].content);assert.equal(p.staleAnnotations.length,5);assert.equal(p.unbound.length,3);for(const [id,start,end]of[['E1',2,5],['E2',7,10],['R1',11,12],['R2',14,15],['R3',18,19]]){await fill(e.root,id+'起点',String(start));await fill(e.root,id+'终点',String(end));await button(e.root,'确认'+id+'区间').fire('click');}await build(e);await button(e.root,'导出完整 JSON').fire('click');p=JSON.parse(calls[1].content);assert.equal(p.staleAnnotations.length,0);assert.equal(p.unbound.length,1);assert.equal(p.references[0].quote,'它');e.life.destroy();});
test('L046 UI real textarea selection adds spans and delete protection, raw HTML remains text',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});select(e.root,0,3);await button(e.root,'将原文选区添加为实体').fire('click');await fill(e.root,'E3名称','<script>人工名</script>');select(e.root,9,10);await button(e.root,'将原文选区添加为指代').fire('click');await fill(e.root,'R4人工绑定','E3');await checkCandidate(e.root,'R4','E3',true);await button(e.root,'删除E3').fire('click');assert.match(e.root.textContent,/先人工解除/);await build(e);await button(e.root,'导出完整 JSON').fire('click');const p=JSON.parse(calls[0].content);assert.equal(p.entities.length,3);assert.equal(p.references.length,4);assert.ok(p.conflicts.some(c=>c.kind==='span-overlap'));assert.match(e.root.textContent,/<script>/);await button(e.root,'删除R4').fire('click');await button(e.root,'删除E3').fire('click');await build(e);e.life.destroy();});
test('L046 pending numeric range refuses report/save until explicit confirmation, invalid no partial',async t=>{const writes=[],e=await mount(t,undefined,{set:(_k,v)=>writes.push(v)});await fill(e.root,'来源名','来源');await tick();const count=writes.length;await fill(e.root,'R1起点','');await build(e);assert.match(e.root.textContent,/数字未确认/);assert.equal(writes.length,count);assert.equal(walk(e.root).some(n=>n.tagName==='button'&&n.textContent==='导出完整 JSON'),false);await button(e.root,'确认R1区间').fire('click');assert.match(e.root.textContent,/整项拒绝/);await fill(e.root,'R1起点','9');await button(e.root,'确认R1区间').fire('click');await build(e);assert.ok(button(e.root,'导出完整 JSON'));e.life.destroy();});
test('L046 configuration whole input/stale restored, largeinputskip and no derived config',async t=>{const writes=[],e=await mount(t,undefined,{set:(_k,v)=>writes.push(v)});await fill(e.root,'原文','短');await tick();const saved=writes.at(-1);assert.equal(saved.source.text,'短');assert.equal(saved.references[0].quote,'它');assert.equal(saved.references[0].textRevision,1);assert.equal('chains' in saved,false);e.life.destroy();const root=new NodeStub('div'),life=e.tool.create(root,{config:{get:()=>saved}});assert.match(root.textContent,/旧区间失效/);assert.equal(walk(root).some(n=>n.tagName==='button'&&n.textContent==='导出完整 JSON'),false);await button(root,'生成完整人工链报告').fire('click');assert.match(root.textContent,/未绑定3处/);life.destroy();});
test('L046 strict copyOnly capability/ok/cancel and unsafe schema restore no false success',async t=>{const calls=[];let response={ok:'true'};const e=await mount(t,{saveTextSupportsCopyOnly:false,saveText:async p=>{calls.push(p);return response;}});await build(e);await button(e.root,'导出完整 JSON').fire('click');assert.equal(calls.length,0);window.toolbox.files.saveTextSupportsCopyOnly=true;for(const r of[{ok:'true'},{canceled:true},{ok:false,error:'EEXIST'}]){response=r;await button(e.root,'导出完整 JSON').fire('click');assert.doesNotMatch(e.root.textContent,/新副本已保存/);}e.life.destroy();const root=new NodeStub('div'),life=e.tool.create(root,{config:{get:()=>({schemaVersion:2})}});assert.match(root.textContent,/草稿未恢复/);life.destroy();});
test('L046 lifecycle inactive events ignored/pending export destroyed and stale config callback not mask input',async t=>{let finish;const e=await mount(t,undefined,{set:()=>new Promise(r=>finish=r)});await fill(e.root,'来源名','first');await fill(e.root,'R1起点','');finish();await tick();assert.match(e.root.textContent,/区间数字正在编辑/);await fill(e.root,'R1起点','9');await button(e.root,'确认R1区间').fire('click');finish();await tick();await build(e);e.life.deactivate();await fill(e.root,'R3人工绑定','E1');e.life.activate();await build(e);assert.match(e.root.textContent,/未绑定1处/);let finishExport;window.toolbox.files={saveTextSupportsCopyOnly:true,saveText:()=>new Promise(r=>finishExport=r)};const pending=button(e.root,'导出完整 JSON').fire('click');e.life.destroy();finishExport({ok:true});await pending;assert.equal(e.root.children.length,0);});