const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const model = import('../src/renderer/features/E030/model.mjs');
const immediate = { yieldControl: async () => {} };
const config = (extra = {}) => ({ players: ['甲', '乙', '丙'], wildOnes: false, ...extra });
const roller = faces => { let i = 0; return () => faces[i++ % faces.length]; };
async function inspect(game) { const m = await model; while (m.publicView(game).phase === 'inspect') { m.showDice(game); m.finishInspection(game); } m.showDice(game); }
async function loseByChallenge(game, quantity = 1, face = 6) { const m = await model; await inspect(game); m.makeBid(game, quantity, face); m.showDice(game); return m.challenge(game); }

if (!process.versions.electron) {
const test = require('node:test');
test('E030: discovery exact metadata, 3-6 players five private dice, detached public view', async () => { const m = await model, game = m.createGame(config(), { roll: () => 4 }); const meta = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/renderer/features/E030/meta.json'), 'utf8')); assert.deepEqual(Object.keys(meta).sort(), ['category','description','group','id','title']); assert.equal(meta.category, '娱乐'); const view = m.publicView(game); assert.equal(view.totalDice, 15); assert.equal(view.phase, 'inspect'); assert.ok(!JSON.stringify(view).includes('faces')); view.players[0].remaining = 0; assert.equal(m.publicView(game).players[0].remaining, 5); assert.throws(() => m.privateDice(game), /遮盖/u); });
test('E030: random rejection sampling equal six outcomes and rejects252-255 without modulo bias', async () => { const { randomDie } = await model; const counts = Array(6).fill(0); for (let n = 0; n < 252; n++) counts[randomDie(bytes => bytes.fill(n)) - 1]++; assert.deepEqual(counts, Array(6).fill(42)); let calls = 0; assert.equal(randomDie(bytes => bytes.fill(calls++ === 0 ? 255 : 5)), 6); assert.equal(calls, 2); assert.throws(() => randomDie(bytes => bytes.fill(252)), /拒绝区/u); assert.throws(() => randomDie(() => { throw Error('rng unavailable'); }), /unavailable/u); });
test('E030: rejects invalid players names options and dice source', async () => { const { createGame } = await model; for (const players of [[], ['甲','乙'], Array(7).fill('甲'), ['甲','甲','丙'], ['é','e\u0301','丙'], [' 甲','乙','丙'], ['\ud800','乙','丙'], ['x'.repeat(21),'乙','丙'], ['a\n','乙','丙']]) assert.throws(() => createGame(config({ players }))); for (const roll of [() => 0, () => 7, () => 1.5, () => '4', null]) assert.throws(() => createGame(config(), { roll })); assert.throws(() => createGame(config({ wildOnes: 'true' }))); assert.equal(createGame(config({ players: ['😀'.repeat(20),'乙','丙'] }), { roll: () => 1 }).feature, 'E030'); });
test('E030: inspection handoff sees only viewer, demands view, then starter bids', async () => { const m = await model, game = m.createGame(config(), { roll: roller([4,4,2,2,2,1,1,1,1,1,6,6,6,6,6]) }); assert.throws(() => m.finishInspection(game)); for (let i = 0; i < 3; i++) { assert.equal(m.publicView(game).current, i); const faces = m.showDice(game); assert.equal(faces.length, 5); faces[0] = 9; assert.ok(!m.privateDice(game).includes(9)); m.finishInspection(game); assert.throws(() => m.privateDice(game)); } assert.equal(m.publicView(game).current, 0); assert.equal(m.publicView(game).phase, 'turn'); assert.throws(() => m.makeBid(game, 1, 1), /查看/u); });
test('E030: three4 actualtwo4 challenge succeeds bidder loses one', async () => { const m = await model, game = m.createGame(config(), { roll: roller([4,4,2,2,2,2,2,2,2,2,2,2,2,2,2]) }); await inspect(game); m.makeBid(game, 3, 4); assert.equal(m.publicView(game).current, 1); m.showDice(game); const result = m.challenge(game); assert.equal(result.actual, 2); assert.equal(result.challengeSucceeded, true); assert.equal(result.loser, 0); assert.deepEqual(result.after, [4,5,5]); assert.equal(result.nextStarter, 0); assert.equal(m.publicView(game).phase, 'revealed'); assert.throws(() => m.privateDice(game)); });
test('E030: exact count and greater count reject challenge and deduct challenger', async () => { const m = await model; for (const quantity of [14,15]) { const game = m.createGame(config(), { roll: () => 4 }); const result = await loseByChallenge(game, quantity, 4); assert.equal(result.actual, 15); assert.equal(result.challengeSucceeded, false); assert.equal(result.loser, 1); assert.deepEqual(result.after, [5,4,5]); assert.equal(result.nextStarter, 1); } });
test('E030: wild ones counts towards2-6, face1 onlyones, default no wild', async () => { const m = await model; for (const [wildOnes, face, expected] of [[false,4,2],[true,4,5],[true,1,3]]) { const game = m.createGame(config({ wildOnes }), { roll: roller([4,4,1,1,1,2,2,2,2,2,2,2,2,2,2]) }); assert.equal((await loseByChallenge(game, 6, face)).actual, expected); } });
test('E030: lexicographic increase validates quantities/face and maximum forces challenge', async () => { const m = await model, game = m.createGame(config(), { roll: () => 2 }); await inspect(game); m.makeBid(game, 3, 4); m.showDice(game); for (const [q,f] of [[3,4],[2,6],[3,3],[0,1],[16,1],[3,7],[3.5,6],['4',1]]) assert.throws(() => m.makeBid(game,q,f), /递增/u); m.makeBid(game,3,5); m.showDice(game); m.makeBid(game,4,1); m.showDice(game); m.makeBid(game,15,6); m.showDice(game); for (let q=1;q<=15;q++) for(let f=1;f<=6;f++) assert.equal(m.legalBid(game,q,f),false); assert.ok(m.challenge(game)); });
test('E030: zero dice exit skipped, failed player successor starts next round', async () => { const m = await model, game = m.createGame(config(), { roll: () => 2 }); for (let i=0;i<5;i++) { const r=await loseByChallenge(game); assert.equal(r.loser,0); assert.equal(r.eliminated,i===4); if(i<4)m.nextRound(game); } const r=m.publicView(game).latestRevealed; assert.equal(r.nextStarter,1); m.nextRound(game); assert.equal(m.publicView(game).current,1); assert.equal(m.publicView(game).inspectCount,2); await inspect(game); assert.equal(m.publicView(game).current,1); m.makeBid(game,1,6); assert.equal(m.publicView(game).current,2); });
test('E030: bounded rounds reaches winner and forbids all game actions after final', async () => { const m = await model, game = m.createGame(config(), { roll: () => 2 }); for (let i=0;i<10;i++) { await loseByChallenge(game); if(i<9)m.nextRound(game); } const v=m.publicView(game); assert.equal(v.phase,'finished'); assert.equal(v.winner,2); assert.deepEqual(v.players.map(p=>p.remaining),[0,0,5]); for(const fn of [()=>m.nextRound(game),()=>m.showDice(game),()=>m.makeBid(game,1,1),()=>m.challenge(game),()=>m.finishInspection(game)])assert.throws(fn); assert.equal(m.revealedReport(game).complete,true); });
test('E030: next round rolls remaining dice only, failed RNG commits no partial reroll', async () => { const m=await model;let fails=false,calls=0;const game=m.createGame(config(),{roll:()=>{calls++;if(fails)throw Error('failedrng');return 2;}});await loseByChallenge(game);assert.equal(calls,15);const old=m.publicView(game);fails=true;assert.throws(()=>m.nextRound(game),/failedrng/u);assert.deepEqual(m.publicView(game),old);fails=false;m.nextRound(game);assert.equal(calls,30);assert.equal(m.publicView(game).totalDice,14); });
test('E030: six players maximum29 rounds retain exact losses and bounded complete history', async()=>{const m=await model,game=m.createGame(config({players:Array.from({length:6},(_,i)=>`玩家${i+1}`)}),{roll:()=>2});for(let round=0;round<29;round++){await inspect(game);let v=m.publicView(game),target=v.players.find(p=>p.remaining>1)?.id??v.players.find(p=>p.remaining>0).id,face=1;while(m.publicView(game).current!==target){m.makeBid(game,1,face++);m.showDice(game);}m.makeBid(game,1,6);m.showDice(game);const result=m.challenge(game);assert.equal(result.loser,target);if(round<28)m.nextRound(game);}const report=m.revealedReport(game);assert.equal(report.revealedRounds,29);assert.equal(report.complete,true);assert.equal(report.players.filter(p=>p.remaining).length,1);assert.equal(report.rounds.reduce((n,r)=>n+r.before.reduce((a,b)=>a+b,0)-r.after.reduce((a,b)=>a+b,0),0),29);for(const format of ['json','md'])assert.ok(Buffer.byteLength(await m.serializeGame(game,format,immediate))<m.LIMITS.exportBytes);});
test('E030: export excludes entire current private round; escaping and cancellation', async () => { const m=await model,game=m.createGame(config({players:['<甲>*','乙','丙']}),{roll:()=>2}); await assert.rejects(m.serializeGame(game,'json',immediate),/尚无/u);await loseByChallenge(game);m.nextRound(game);m.showDice(game);const report=JSON.parse(await m.serializeGame(game,'json',immediate));assert.equal(report.rounds.length,1);assert.equal(report.currentUnrevealedRoundExcluded,true);assert.equal(report.phase,'ongoing');assert.ok(!JSON.stringify(report).includes('inspect'));assert.ok((await m.serializeGame(game,'md',immediate)).includes('&lt;甲&gt;\\*'));const controller=new AbortController();await assert.rejects(m.serializeGame(game,'json',{signal:controller.signal,yieldControl:async()=>controller.abort()}),{name:'AbortError'});await assert.rejects(m.serializeGame(game,'html',immediate),/只支持/u);m.destroyGame(game);assert.throws(()=>m.publicView(game)); });

// Lightweight DOM fixture exercises production module wiring; actual Electron below is separate evidence.
class Element {
  constructor(tag) { this.nodeType=1;this.tagName=tag;this.children=[];this.attributes={};this.dataset={};this.style={};this.listeners={};this.value='';this.disabled=false; }
  get childNodes(){return this.children;}
  setAttribute(key,value){this.attributes[key]=String(value);if(key==='value')this.value=String(value);if(key==='disabled')this.disabled=true;}
  addEventListener(type,fn){(this.listeners[type]||=[]).push(fn);}
  removeEventListener(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(other=>other!==fn);}
  append(...nodes){this.children.push(...nodes.map(node=>node.nodeType?node:{nodeType:3,textContent:String(node)}));if(this.tagName==='select'&&!this.value)this.value=this.children[0]?.value||'';}
  replaceChildren(...nodes){this.children=[];this.append(...nodes);}
  get textContent(){return this.children.map(n=>n.textContent).join('');}
  set textContent(value){this.replaceChildren(String(value));}
  querySelectorAll(selector){return descendants(this).filter(n=>selector==='[data-private-dice]'?Object.hasOwn(n.attributes,'data-private-dice'):selector.split(',').includes(n.tagName));}
  async fire(type){if(this.disabled)return;for(const fn of [...(this.listeners[type]||[])])await fn({target:this,currentTarget:this});}
}
function descendants(root){return root.children.flatMap(n=>n.nodeType===1?[n,...descendants(n)]:[]);}
const btn=(root,text)=>descendants(root).find(n=>n.tagName==='button'&&n.textContent===text);
const ctl=(root,text)=>descendants(root).find(n=>n.attributes['aria-label']===text);
const domData=root=>[root,...descendants(root)].map(n=>n.textContent+n.value+JSON.stringify(n.attributes)+JSON.stringify(n.dataset)).join('\n');
const files=calls=>({saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true,path:'dice-copy'};}});
async function withUI(bridge,fn){const old={document:global.document,window:global.window},cryptoDescriptor=Object.getOwnPropertyDescriptor(global,'crypto');let i=0;Object.defineProperty(global,'crypto',{configurable:true,value:{getRandomValues(bytes){bytes.fill(i++<2?3:1);return bytes;}}});global.document={createElement:tag=>new Element(tag),createTextNode:text=>({nodeType:3,textContent:String(text)})};global.window={toolbox:{files:bridge}};const root=new Element('main'),life=(await import('../src/renderer/features/E030/index.js')).default.create(root,{});try{await fn(root,life);}finally{life.destroy();for(const [k,v]of Object.entries(old))if(v===undefined)delete global[k];else global[k]=v;if(cryptoDescriptor)Object.defineProperty(global,'crypto',cryptoDescriptor);else delete global.crypto;}}
const start=root=>btn(root,'建立本局并开始看骰').fire('click');
const show=(root,name)=>btn(root,`我是${name}，私密查看自己的骰子`).fire('click');
async function inspection(root){for(const name of ['甲','乙','丙']){await show(root,name);await btn(root,'记住骰子，遮盖并交接').fire('click');}}
async function bidThree4(root){await show(root,'甲');ctl(root,'叫价数量').value='3';ctl(root,'叫价点数').value='4';await btn(root,'确认叫价并遮盖交接').fire('click');await show(root,'乙');await btn(root,'质疑上一叫价并亮全部骰').fire('click');}
test('E030 UI: actual contract handoff removes private DOM and old nodes, three4 actualtwo4',async()=>{const calls=[];await withUI(files(calls),async root=>{await start(root);assert.equal(ctl(root,'万能1规则'),undefined);assert.equal(ctl(root,'本人私密骰子'),undefined);await show(root,'甲');const old=ctl(root,'本人私密骰子'),hide=btn(root,'记住骰子，遮盖并交接');assert.equal(old.textContent,'4 · 4 · 2 · 2 · 2');await hide.fire('click');assert.equal(old.textContent,'');assert.equal(hide.listeners.click.length,0);assert.ok(!domData(root).includes('4 · 4 · 2 · 2 · 2'));for(const name of ['乙','丙']){await show(root,name);await btn(root,'记住骰子，遮盖并交接').fire('click');}await bidThree4(root);assert.match(root.textContent,/实际2；质疑成功；甲扣1骰/u);assert.match(root.textContent,/甲：4骰/u);await btn(root,'保存已揭示 JSON 历史副本').fire('click');assert.equal(JSON.parse(calls[0].content).rounds[0].actual,2);assert.equal(calls[0].copyOnly,true);});});
test('E030 UI: hide/pause must explicitly re-view, resume never auto exposes dice',async()=>{await withUI(files([]),async(root,life)=>{await start(root);await show(root,'甲');const old=ctl(root,'本人私密骰子');life.deactivate();assert.equal(old.textContent,'');assert.ok(!domData(root).includes('4 · 4 · 2 · 2 · 2'));life.activate();assert.equal(ctl(root,'本人私密骰子'),undefined);await show(root,'甲');await btn(root,'立即遮盖自己的骰子').fire('click');assert.equal(ctl(root,'本人私密骰子'),undefined);assert.equal(btn(root,'记住骰子，遮盖并交接'),undefined);});});
test('E030 UI: invalid bids stay same player; challenge absent before bid and capped inputs',async()=>{await withUI(files([]),async root=>{await start(root);await inspection(root);await show(root,'甲');assert.equal(btn(root,'质疑上一叫价并亮全部骰').disabled,true);for(const q of ['0','16','1.5','']){ctl(root,'叫价数量').value=q;await btn(root,'确认叫价并遮盖交接').fire('click');assert.match(root.textContent,/递增/u);assert.ok(ctl(root,'本人私密骰子'));}ctl(root,'叫价数量').value='3';ctl(root,'叫价点数').value='4';await btn(root,'确认叫价并遮盖交接').fire('click');await show(root,'乙');ctl(root,'叫价数量').value='3';ctl(root,'叫价点数').value='3';await btn(root,'确认叫价并遮盖交接').fire('click');assert.match(root.textContent,/递增/u);assert.match(root.textContent,/交给 乙/u);});});
test('E030 UI: new-game confirmation covers private dice; cancellation preserves rule; reset fresh',async()=>{await withUI(files([]),async root=>{ctl(root,'万能1规则').value='on';await ctl(root,'万能1规则').fire('change');await start(root);await show(root,'甲');await btn(root,'建立新局').fire('click');assert.equal(ctl(root,'本人私密骰子'),undefined);await btn(root,'返回当前局并保持遮盖').fire('click');assert.match(root.textContent,/万能1开启/u);assert.equal(ctl(root,'本人私密骰子'),undefined);await btn(root,'建立新局').fire('click');await btn(root,'确认清空，进入新局设置').fire('click');assert.ok(ctl(root,'万能1规则'));assert.equal(ctl(root,'万能1规则').value,'off');});});
test('E030 UI: player bounded inputs names unique and locking setup',async()=>{await withUI(files([]),async root=>{for(let i=3;i<6;i++)await btn(root,'添加玩家').fire('click');assert.equal(btn(root,'添加玩家').disabled,true);for(let i=6;i>3;i--)await btn(root,'移除最后一位玩家').fire('click');assert.equal(btn(root,'移除最后一位玩家').disabled,true);ctl(root,'骰子玩家1名称').value='乙';await ctl(root,'骰子玩家1名称').fire('input');await start(root);assert.match(root.textContent,/唯一/u);ctl(root,'骰子玩家1名称').value='甲';await ctl(root,'骰子玩家1名称').fire('input');await start(root);assert.equal(ctl(root,'骰子玩家1名称'),undefined);});});
test('E030 UI: no early exporter; next private round exports only prior complete reveal',async()=>{const calls=[];await withUI(files(calls),async root=>{await start(root);assert.equal(btn(root,'保存已揭示 JSON 历史副本'),undefined);await inspection(root);await bidThree4(root);await btn(root,'下一轮重新掷骰并遮盖').fire('click');await show(root,'甲');await btn(root,'保存已揭示 JSON 历史副本').fire('click');assert.equal(ctl(root,'本人私密骰子'),undefined);const report=JSON.parse(calls[0].content);assert.equal(report.rounds.length,1);assert.equal(report.currentUnrevealedRoundExcluded,true);await btn(root,'保存已揭示 Markdown 历史副本').fire('click');assert.equal(calls[1].extension,'md');});});
test('E030 UI: exports enforce capability/strict ok/cancel/errors',async()=>{await withUI({saveText:async()=>assert.fail('unsafe')},async root=>{await start(root);await inspection(root);await bidThree4(root);assert.equal(btn(root,'保存已揭示 JSON 历史副本').disabled,true);assert.match(root.textContent,/缺少copyOnly/u);});let response;await withUI({saveTextSupportsCopyOnly:true,saveText:async()=>{if(response instanceof Error)throw response;return response;}},async root=>{await start(root);await inspection(root);await bidThree4(root);for(response of [{ok:false,error:'已有文件'},{ok:'true'},undefined,new Error('bad')]){await btn(root,'保存已揭示 JSON 历史副本').fire('click');assert.match(root.textContent,/保存失败/u);}response={canceled:true};await btn(root,'保存已揭示 JSON 历史副本').fire('click');assert.match(root.textContent,/已取消另存/u);});});
test('E030 UI: cancel generation and pause prevent IPC; pending native dialog blocks mutation',async()=>{const calls=[];await withUI(files(calls),async(root,life)=>{await start(root);await inspection(root);await bidThree4(root);const task=btn(root,'保存已揭示 JSON 历史副本').fire('click');await btn(root,'取消报告生成').fire('click');await task;assert.equal(calls.length,0);const paused=btn(root,'保存已揭示 JSON 历史副本').fire('click');life.deactivate();await paused;assert.equal(calls.length,0);life.activate();});let finish;await withUI({saveTextSupportsCopyOnly:true,saveText:()=>new Promise(r=>{finish=r;})},async root=>{await start(root);await inspection(root);await bidThree4(root);const task=btn(root,'保存已揭示 JSON 历史副本').fire('click');while(!finish)await new Promise(r=>setTimeout(r,0));assert.equal(btn(root,'取消报告生成').disabled,true);assert.equal(btn(root,'下一轮重新掷骰并遮盖').disabled,true);finish({canceled:true});await task;});});
test('E030 UI: destroy scrubs dice/listeners and old controls cannot mutate another module',async()=>{await withUI(files([]),async(root,life)=>{await start(root);await show(root,'甲');const old=ctl(root,'本人私密骰子'),oldNext=btn(root,'记住骰子，遮盖并交接');life.destroy();assert.equal(old.textContent,'');assert.equal(oldNext.listeners.click.length,0);await oldNext.fire('click');life.activate();assert.equal(root.children.length,0);});});
test('E030 UI: eliminate skips exited handoff, final winner forbids actions and exports complete history',async()=>{const calls=[];await withUI(files(calls),async root=>{await start(root);for(let round=0;round<10;round++){while(descendants(root).some(n=>n.tagName==='h3'&&n.textContent.includes('看骰'))){const who=descendants(root).find(n=>n.tagName==='h3').textContent.match(/交给 (.+) ·/u)[1];await show(root,who);await btn(root,'记住骰子，遮盖并交接').fire('click');}let who=descendants(root).find(n=>n.tagName==='h3').textContent.match(/交给 (.+) ·/u)[1];await show(root,who);ctl(root,'叫价数量').value='1';ctl(root,'叫价点数').value='6';await btn(root,'确认叫价并遮盖交接').fire('click');who=descendants(root).find(n=>n.tagName==='h3').textContent.match(/交给 (.+) ·/u)[1];await show(root,who);await btn(root,'质疑上一叫价并亮全部骰').fire('click');if(round<9)await btn(root,'下一轮重新掷骰并遮盖').fire('click');if(round===4){assert.match(root.textContent,/甲：0骰（退出）/u);assert.match(root.textContent,/交给 乙/u);}}assert.match(root.textContent,/本局结束，胜者：丙/u);assert.equal(btn(root,'下一轮重新掷骰并遮盖'),undefined);assert.equal(ctl(root,'本人私密骰子'),undefined);await btn(root,'保存已揭示 JSON 历史副本').fire('click');const report=JSON.parse(calls[0].content);assert.equal(report.complete,true);assert.equal(report.rounds.length,10);assert.equal(report.winner,2);});});
} else nativeCheck().catch(error=>{console.error(error);require('electron').app.exit(1);});

async function nativeCheck(){
 const {app,BrowserWindow,ipcMain,session}=require('electron'),os=require('node:os'),{pathToFileURL}=require('node:url'),worktree=path.resolve(__dirname,'..'),evidence=fs.mkdtempSync(path.join(os.tmpdir(),'agent-toolbox-E030-native-'));app.setPath('userData',path.join(evidence,'profile'));await app.whenReady();const saves=[],requests=[];session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(details,cb)=>{requests.push(details.url);cb({cancel:true});});ipcMain.handle('features:list',()=>require('../src/main/feature-catalog').listFeatures(path.join(worktree,'src/renderer/features')));ipcMain.handle('files:saveText',(_event,payload)=>{assert.equal(payload.copyOnly,true);const target=path.join(evidence,payload.defaultName),result=require('../src/main/text-export').writeText(target,payload.content,true);saves.push({target,result});return result;});
 const fixture=path.join(evidence,'fixture.html');fs.writeFileSync(fixture,`<html><head><meta charset="UTF-8"></head><body><main id="root"></main><script type="module">import feature from ${JSON.stringify(pathToFileURL(path.join(worktree,'src/renderer/features/E030/index.js')).href)};window.life=feature.create(document.getElementById('root'),{});window.qaReady=true;</script></body></html>`,{flag:'wx'});const win=new BrowserWindow({show:false,webPreferences:{preload:path.join(worktree,'src/main/preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});await win.loadFile(fixture);
 const result=await win.webContents.executeJavaScript(`(async()=>{const wait=async test=>{for(let i=0;i<1000;i++){if(test())return;await new Promise(r=>setTimeout(r,10));}throw Error('timeout');};await wait(()=>window.qaReady);const root=document.getElementById('root'),btn=t=>[...root.querySelectorAll('button')].find(n=>n.textContent===t),ctl=t=>root.querySelector('[aria-label="'+t+'"]');if(!(await window.toolbox.features.list()).features.some(f=>f.id==='E030'))throw Error('catalog');btn('建立本局并开始看骰').click();let viewed=[];for(const name of ['甲','乙','丙']){if(ctl('本人私密骰子'))throw Error('early private');btn('我是'+name+'，私密查看自己的骰子').click();const old=ctl('本人私密骰子');viewed.push(old.textContent.split(' · ').map(Number));btn('记住骰子，遮盖并交接').click();if(old.textContent||ctl('本人私密骰子')||root.innerHTML.includes('data-private-dice'))throw Error('handoff leak');}btn('我是甲，私密查看自己的骰子').click();const old=ctl('本人私密骰子');window.life.deactivate();if(old.textContent||ctl('本人私密骰子'))throw Error('pause leak');window.life.activate();if(ctl('本人私密骰子'))throw Error('resume leak');btn('我是甲，私密查看自己的骰子').click();ctl('叫价数量').value='1';ctl('叫价点数').value='1';btn('确认叫价并遮盖交接').click();if(ctl('本人私密骰子'))throw Error('bid leak');btn('我是乙，私密查看自己的骰子').click();btn('质疑上一叫价并亮全部骰').click();const actual=viewed.flat().filter(n=>n===1).length;if(!root.textContent.includes('实际'+actual))throw Error('count');btn('保存已揭示 JSON 历史副本').click();await wait(()=>root.textContent.includes('已保存已揭示历史副本'));btn('保存已揭示 Markdown 历史副本').click();await wait(()=>root.textContent.includes('liars-dice-revealed-copy.md'));btn('保存已揭示 JSON 历史副本').click();await wait(()=>root.textContent.includes('保存失败'));btn('下一轮重新掷骰并遮盖').click();if(ctl('本人私密骰子'))throw Error('reroll leak');window.life.destroy();if(root.children.length)throw Error('destroy');return{actualDOM:true,realCrypto:true,viewed,actual,pauseCovered:true,handoffCovered:true};})()`);
 assert.equal(saves.length,3);assert.equal(saves[0].result.ok,true);assert.equal(saves[1].result.ok,true);assert.equal(saves[2].result.ok,false);const report=JSON.parse(fs.readFileSync(saves[0].target,'utf8'));assert.equal(report.rounds.length,1);assert.equal(report.rounds[0].actual,result.actual);assert.deepEqual(report.rounds[0].dice.map(d=>d.faces),result.viewed);assert.equal(report.complete,false);assert.deepEqual(requests,[]);delete result.viewed;console.log(JSON.stringify({...result,evidence,saves:saves.map(s=>({...s,bytes:s.result.ok?fs.statSync(s.target).size:undefined})),networkRequests:0,boundary:'Hidden Electron actual DOM/crypto + production preload/catalog/text writer; test handler chooses target, no native save dialog/full app/packaging.'}));win.destroy();app.quit();
}
