const test=require('node:test');const assert=require('node:assert/strict');const model=()=>import('../src/renderer/features/L025/model.mjs');
function events(n){return Array.from({length:n},(_,i)=>({id:`e${i+1}`,version:String(i+1),value:`结果${i+1}`,dependencies:''}));}
test('L025 核心两事件两顺序、旧覆盖新唯一失败',async()=>{const{enumerate,example}=await model();const r=enumerate(example());assert.equal(r.total,2);assert.equal(r.failed,1);assert.equal(r.passed,1);assert.deepEqual(r.schedules.map(row=>row.order),[['old','new'],['new','old']]);assert.deepEqual(r.schedules.map(row=>row.final.version),[2,1]);assert.deepEqual(r.shortestFailure.prefix,['new','old']);assert.equal(r.shortestFailure.scheduleIndex,2);});
test('L025 最终约束只终点检查，中间旧值允许后续恢复',async()=>{const{enumerate,example}=await model();const r=enumerate(example());const passing=r.schedules[0];assert.equal(passing.trace[0].after.version,1);assert.equal(passing.trace[0].constraintChecked,false);assert.equal(passing.trace[0].failed,false);assert.equal(passing.trace[1].constraintChecked,true);assert.equal(passing.passed,true);assert.equal(r.schedules[1].failurePrefix.length,2);assert.match(r.prefixScope,/完整顺序/);});
test('L025 逐次写约束最短失败前缀1，后续修复不撤销违反',async()=>{const{enumerate,example}=await model();const r=enumerate(example('writes'));assert.equal(r.failed,2);assert.deepEqual(r.shortestFailure.prefix,['old']);assert.equal(r.schedules[0].final.version,2);assert.equal(r.schedules[0].passed,false);assert.equal(r.schedules[0].failureStep,1);assert.equal(r.schedules[0].trace.length,2);});
test('L025 最新请求守卫在两约束下都全通过，旧回调不写',async()=>{const{enumerate,example}=await model();for(const constraint of ['final-latest','no-stale-writes']){const r=enumerate({...example('guard'),constraint});assert.equal(r.failed,0);assert.equal(r.shortestFailure,null);for(const row of r.schedules){assert.equal(row.final.version,2);assert.equal(row.trace.find(step=>step.event==='old').wrote,false);}}});
test('L025 单调写最终全通过但先旧后新违反逐次要求',async()=>{const{enumerate,example}=await model();const final=enumerate({...example(),rule:'monotonic'});assert.equal(final.failed,0);const writes=enumerate({...example(),rule:'monotonic',constraint:'no-stale-writes'});assert.equal(writes.failed,1);assert.equal(writes.schedules[0].passed,false);assert.equal(writes.schedules[1].passed,true);assert.equal(writes.schedules[1].trace[1].wrote,false);});
test('L025 前置依赖消除旧覆盖顺序，但不证明逐次写成立',async()=>{const{enumerate,example}=await model();const r=enumerate(example('ordered'));assert.equal(r.total,1);assert.equal(r.failed,0);assert.deepEqual(r.schedules[0].order,['old','new']);const writes=enumerate({...example('ordered'),constraint:'no-stale-writes'});assert.equal(writes.failed,1);});
test('L025 反向依赖使失败前缀必须先执行new',async()=>{const{enumerate,example}=await model();const draft=example('writes');draft.events[0].dependencies='new';const r=enumerate(draft);assert.equal(r.total,1);assert.deepEqual(r.shortestFailure.prefix,['new','old']);assert.equal(r.shortestFailure.trace[0].failed,false);assert.equal(r.shortestFailure.trace[1].failed,true);});
test('L025 六独立事件完整720/最终失败600，用排列oracle比较',async()=>{const{enumerate}=await model();const r=enumerate({events:events(6),rule:'naive',constraint:'final-latest'});function permute(xs){if(!xs.length)return[[]];return xs.flatMap((value,i)=>permute(xs.filter((_,j)=>i!==j)).map(tail=>[value,...tail]));}const oracle=permute(['e1','e2','e3','e4','e5','e6']);assert.equal(r.total,720);assert.equal(r.failed,600);assert.equal(r.passed,120);assert.equal(new Set(r.schedules.map(row=>row.order.join(','))).size,720);assert.deepEqual(r.schedules.map(row=>row.order),oracle);for(const row of r.schedules)assert.equal(row.passed,row.order.at(-1)==='e6');});
test('L025 菱形与链依赖按独立排列过滤得到全部顺序',async()=>{const{enumerate}=await model();const ev=events(4);ev[1].dependencies='e1';ev[2].dependencies='e1';ev[3].dependencies='e2,e3';const r=enumerate({events:ev,rule:'latest-request',constraint:'final-latest'});assert.deepEqual(r.schedules.map(row=>row.order),[['e1','e2','e3','e4'],['e1','e3','e2','e4']]);const chain=events(6);chain.forEach((row,i)=>{if(i)row.dependencies=`e${i}`;});assert.equal(enumerate({events:chain,rule:'naive',constraint:'final-latest'}).total,1);});
test('L025 事件结果相同仍依据请求版本判断失败',async()=>{const{enumerate,example}=await model();const draft=example();draft.events.forEach(row=>{row.value='相同内容';});const r=enumerate(draft);assert.equal(r.failed,1);assert.equal(r.schedules[1].final.value,'相同内容');assert.equal(r.schedules[1].final.event,'old');});
test('L025 最新版本不等于输入末行，空结果仍可写',async()=>{const{enumerate,example}=await model();const draft=example();draft.events[0].version='6';draft.events[0].value='';const r=enumerate(draft);assert.equal(r.latest.id,'old');assert.equal(r.schedules[0].passed,false);assert.equal(r.schedules[1].passed,true);assert.equal(r.schedules[1].final.value,'');});
test('L025 一事件两约束均通过，无失败前缀',async()=>{const{enumerate}=await model();for(const constraint of ['final-latest','no-stale-writes']){const r=enumerate({events:events(1),rule:'naive',constraint});assert.equal(r.total,1);assert.equal(r.failed,0);assert.equal(r.shortestFailure,null);}});
test('L025 重复ID/版本/依赖、未知依赖、自环/多节点循环拒绝',async()=>{const{enumerate,example}=await model();for(const[k,value,pattern]of [['id','old',/重复事件/],['version','1',/重复请求版本/],['dependencies','old,old',/重复依赖/],['dependencies','unknown',/未知依赖/],['dependencies','new',/循环/]]){const d=example();d.events[1][k]=value;assert.throws(()=>enumerate(d),pattern);}const cycle=example();cycle.events[0].dependencies='new';cycle.events[1].dependencies='old';assert.throws(()=>enumerate(cycle),/循环/);});
test('L025 数量/字段类型/ID/版本/容量/规则边界拒绝不执行代码',async()=>{const{enumerate,example}=await model();for(const ev of [[],events(7)])assert.throws(()=>enumerate({...example(),events:ev}),/1–6/);for(const[k,value]of [['id','process.exit()'],['id','汉'],['version','7'],['version','1e0'],['version',1],['value','汉'.repeat(43)],['dependencies','x'.repeat(257)]]){const d=example();d.events[0][k]=value;assert.throws(()=>enumerate(d));}for(const patch of [{rule:'__proto__'},{rule:'code'},{constraint:'toString'},{events:null}])assert.throws(()=>enumerate({...example(),...patch}));});
test('L025 模型确定、输入和顺序轨迹快照独立',async()=>{const{enumerate,example}=await model();const draft=example();const before=structuredClone(draft);const r=enumerate(draft);assert.deepEqual(draft,before);assert.deepEqual(r,enumerate(draft));r.schedules[0].trace[0].after.value='修改';assert.equal(r.schedules[0].trace[1].before.value,'旧请求结果');assert.equal(r.schedules[1].trace[1].after.value,'旧请求结果');assert.equal(r.shortestFailure.trace[1].after.value,'旧请求结果');draft.events[0].value='外部变化';assert.equal(r.events[0].value,'旧请求结果');});
test('L025 草稿schema/raw64KiB/UTF8字段上限和完整报告重算',async()=>{const{enumerate,example,prepareStoredState,validateStoredState,reportMarkdown}=await model();const draft=example();const stored=prepareStoredState(draft);assert.deepEqual(validateStoredState(stored),stored);assert.throws(()=>validateStoredState({schemaVersion:2}),/版本/);assert.throws(()=>validateStoredState({...stored,extra:'汉'.repeat(22000)}),/64KiB/);for(const length of [43,22000]){const d=example();d.events[0].value='汉'.repeat(length);assert.throws(()=>prepareStoredState(d),length===43?/128字节/:/64KiB/);}const wrong=example();wrong.events[0].version=1;assert.throws(()=>prepareStoredState(wrong),/字段类型/);const payload=JSON.parse(JSON.stringify({draft,result:enumerate(draft)}));assert.deepEqual(enumerate(payload.draft),payload.result);const md=reportMarkdown(payload);assert.match(md,/合法2，通过1，失败1/);assert.match(md,/顺序2 new → old：失败/);assert.match(md,/最短失败前缀/);assert.match(md,/不是删事件后的因果最小/);assert.match(reportMarkdown({draft,result:null}),/尚未完成有效/);const html=example();html.events[0].value='<img src=x>';assert.doesNotMatch(reportMarkdown({draft:html,result:enumerate(html)}),/<img/);});
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

test('L025 实际组件核心全部顺序/最短前缀/筛选与完整副本',async(t)=>{const exported=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{exported.push(p);return{ok:true};}});const{default:feature}=await import('../src/renderer/features/L025/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/全部合法顺序 2 · 通过 1 · 失败 1/);await button(root,'查看最短失败所在顺序').fire('click');assert.match(root.textContent,/当前顺序#2：new → old · 失败/);assert.equal(button(root,'下个顺序').disabled,true);await button(root,'上个顺序').fire('click');assert.match(root.textContent,/当前顺序#1：old → new · 通过/);await fill(root,'查看合法顺序','1');const filter=control(root,'只列失败顺序');filter.checked=true;await filter.fire('change');assert.match(root.textContent,/当前列出1个/);await button(root,'查看顺序2').fire('click');await button(root,'导出完整 JSON').fire('click');const p=JSON.parse(exported[0].content);assert.equal(p.schemaVersion,1);assert.equal(p.result.total,2);assert.equal(p.result.schedules.length,2);assert.deepEqual(p.result.shortestFailure.prefix,['new','old']);assert.equal(exported[0].copyOnly,true);await button(root,'导出完整 Markdown').fire('click');assert.match(exported[1].content,/顺序2 new → old：失败/);assert.equal(exported[1].copyOnly,true);assert.doesNotMatch(root.textContent,/\[object Object\]|null/);});
test('L025 UI真实依赖/规则/约束编辑，守卫与单调差异',async(t)=>{dom(t,{});const{default:feature}=await import('../src/renderer/features/L025/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());await button(root,'载入依赖顺序示例').fire('click');await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/全部合法顺序 1 · 通过 1 · 失败 0/);await fill(root,'事件2依赖','');assert.match(root.textContent,/旧枚举及轨迹已清空/);await fill(root,'写入规则','monotonic');await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/全部合法顺序 2 · 通过 2 · 失败 0/);await fill(root,'结果约束','no-stale-writes');await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/全部合法顺序 2 · 通过 1 · 失败 1/);assert.match(root.textContent,/old（1步/);await button(root,'载入最新版守卫示例').fire('click');await fill(root,'结果约束','no-stale-writes');await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/失败 0/);assert.match(root.textContent,/不是最新请求版本，跳过写入/);await fill(root,'事件1ID','earlier');await fill(root,'事件1版本','6');await fill(root,'事件1结果','<img src=x>');await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/最新请求 earlier\/版本6/);assert.match(root.textContent,/<img src=x>/);});
test('L025 UI增删表格/六事件720全列出/引用与循环错误',async(t)=>{dom(t,{});const{default:feature}=await import('../src/renderer/features/L025/index.js');const root=new NodeStub('div');const handle=feature.create(root);t.after(()=>handle.destroy());for(let i=0;i<4;i++)await button(root,'增加事件').fire('click');assert.equal(button(root,'增加事件').disabled,true);await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/全部合法顺序 720 · 通过 120 · 失败 600/);assert.equal(walk(root).filter(n=>n.tagName==='button'&&/^查看顺序\d+$/.test(n.textContent)).length,720);await button(root,'删除事件6').fire('click');assert.match(root.textContent,/尚无有效枚举/);assert.equal(button(root,'增加事件').disabled,false);await button(root,'载入旧覆盖新示例').fire('click');for(const[dependency,pattern]of [['old old',/重复依赖/],['unknown',/未知依赖/],['new',/循环/]]){await fill(root,'事件2依赖',dependency);await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,pattern);assert.match(root.textContent,/尚无有效枚举/);}await fill(root,'事件2依赖','old');await fill(root,'事件1依赖','new');await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/循环/);await button(root,'载入依赖顺序示例').fire('click');await button(root,'删除事件1').fire('click');assert.equal(button(root,'删除事件1').disabled,true);await button(root,'枚举全部合法顺序').fire('click');assert.match(root.textContent,/未知依赖old/);});
test('L025 UI版本/字段容量恢复与严格安全副本成功契约',async(t)=>{const stored=new Map();let saves=0;dom(t,{saveTextSupportsCopyOnly:1,saveText:async()=>{saves++;return{ok:'true'};}});const{default:feature}=await import('../src/renderer/features/L025/index.js');const config={get:key=>stored.get(key),set:(key,value)=>stored.set(key,value)};const root=new NodeStub('div');const handle=feature.create(root,{config});t.after(()=>handle.destroy());await button(root,'导出完整 JSON').fire('click');assert.equal(saves,0);assert.match(root.textContent,/缺少防覆盖/);window.toolbox.files.saveTextSupportsCopyOnly=true;await button(root,'导出完整 JSON').fire('click');assert.match(root.textContent,/未确认保存成功/);window.toolbox.files.saveText=async()=>({canceled:true});await button(root,'导出完整 Markdown').fire('click');assert.match(root.textContent,/已取消导出/);window.toolbox.files.saveText=async()=>{throw new Error('磁盘失败');};await button(root,'导出完整 JSON').fire('click');assert.match(root.textContent,/导出失败：磁盘失败/);await fill(root,'事件1结果','');await button(root,'枚举全部合法顺序').fire('click');handle.deactivate();const saved=structuredClone(stored.get('features.L025.state'));assert.equal(saved.schemaVersion,1);assert.equal(Object.hasOwn(saved,'result'),false);const r=new NodeStub('div');const restored=feature.create(r,{config});assert.match(r.textContent,/已恢复输入草稿/);assert.match(r.textContent,/尚无有效枚举/);assert.equal(control(r,'事件1结果').value,'');restored.destroy();await fill(root,'事件1结果','汉'.repeat(22000));handle.deactivate();assert.deepEqual(stored.get('features.L025.state'),saved);assert.match(root.textContent,/当前草稿未写入全局配置/);await fill(root,'事件1结果','汉'.repeat(43));handle.deactivate();assert.match(root.textContent,/128字节/);for(const raw of [{schemaVersion:2},{...saved,hidden:'汉'.repeat(22000)},{...saved,events:[{...saved.events[0],version:1}]}]){const invalidRoot=new NodeStub('div');const h=feature.create(invalidRoot,{config:{get:()=>raw}});assert.match(invalidRoot.textContent,/草稿未能恢复/);h.destroy();}});
test('L025 生命周期清计时器/销毁后的异步返回不重建DOM',async(t)=>{let resolveSave;dom(t,{saveTextSupportsCopyOnly:true,saveText:()=>new Promise(resolve=>{resolveSave=resolve;})});const originalSet=global.setTimeout;const originalClear=global.clearTimeout;const callbacks=new Map();let next=1;global.setTimeout=fn=>{const id=next++;callbacks.set(id,fn);return id;};global.clearTimeout=id=>callbacks.delete(id);t.after(()=>{global.setTimeout=originalSet;global.clearTimeout=originalClear;});const{default:feature}=await import('../src/renderer/features/L025/index.js');const root=new NodeStub('div');const handle=feature.create(root,{config:{set:()=>{}}});t.after(()=>handle.destroy());await fill(root,'事件1结果','测试');assert.equal(callbacks.size,1);handle.deactivate();assert.equal(callbacks.size,0);handle.activate();assert.equal(callbacks.size,0);await fill(root,'事件2结果','另一结果');const saving=button(root,'导出完整 JSON').fire('click');handle.destroy();assert.equal(callbacks.size,0);resolveSave({ok:true});await saving;assert.equal(root.children.length,0);handle.destroy();assert.doesNotMatch(root.className,/feature-l025/);});
