const test=require('node:test');const assert=require('node:assert/strict');const model=()=>import('../src/renderer/features/L036/model.mjs');
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

const source=(id,upstream='',original=false)=>({id,label:id,upstream,original,location:''});
const graph=(nodes,supports='A')=>({nodes,claims:[{id:'Q1',text:'人工论断',supports}]});
test('L036 三篇同源独立oracle支持3原始1共享E',async()=>{const m=await model(),r=m.derive(m.example()),c=r.claims[0];assert.equal(c.supportCount,3);assert.equal(c.originalSourceCount,1);assert.deepEqual(c.originalIds,['E']);assert.equal(c.unknownTerminalCount,0);assert.deepEqual(c.sharedUpstreamGroups[0].supportIds,['A','B','C']);assert.deepEqual(c.supports.map(s=>s.witnesses[0].path),[['A','E'],['B','E'],['C','E']]);assert.match(r.boundaries[0],/不证明统计独立/);});
test('L036 diamond多上游同源仅计一次，完整reachset与最短见证',async()=>{const m=await model(),c=m.derive(graph([source('A','B,C'),source('B','D'),source('C','D,E'),source('D','',true),source('E','',true)])).claims[0];assert.deepEqual(c.supports[0].reachableIds,['A','B','C','D','E']);assert.deepEqual(c.originalIds,['D','E']);assert.equal(c.originalSourceCount,2);assert.deepEqual(c.supports[0].witnesses.map(w=>w.path),[['A','B','D'],['A','C','E']]);assert.equal(c.supports[0].witnesses.length,2);});
test('L036 unmarked终点是未知，标题叫原始也不自动计数',async()=>{const m=await model(),d=graph([source('A','U'),{...source('U'),label:'原始实验（但没有标记）'}]),c=m.derive(d).claims[0];assert.equal(c.originalSourceCount,0);assert.deepEqual(c.unknownTerminalIds,['U']);assert.equal(c.supports[0].witnesses[0].type,'未知终点');assert.match(m.derive(d).boundaries[1],/0个已标原始.*不等于/);});
test('L036 显式原始自支持计自己、重复支持集合去重、共享跨支持',async()=>{const m=await model(),c=m.derive(graph([source('A','E'),source('E','',true)],'A,E,A,E')).claims[0];assert.equal(c.supportCount,2);assert.equal(c.duplicateSupportCount,2);assert.equal(c.originalSourceCount,1);assert.deepEqual(c.supports[1].reachableIds,['E']);assert.deepEqual(c.supports[1].witnesses[0].path,['E']);assert.deepEqual(c.sharedUpstreamGroups[0].supportIds,['A','E']);});
test('L036 原始/未知混合共享群组、不同论断分别去重不互串',async()=>{const m=await model(),d=graph([source('A','E,U'),source('B','E,U'),source('C','F'),source('E','',true),source('F','',true),source('U')],'A,B');d.claims.push({id:'Q2',text:'第二论断',supports:'C'});const r=m.derive(d);assert.deepEqual(r.claims[0].originalIds,['E']);assert.deepEqual(r.claims[0].unknownTerminalIds,['U']);assert.deepEqual(r.claims[0].sharedUpstreamGroups.map(g=>g.type),['用户标记原始来源','未知终点']);assert.deepEqual(r.claims[1].originalIds,['F']);assert.equal(r.claims[1].sharedUpstreamGroups.length,0);});
test('L036 整图未选支循环/未知边/原始出边/重复边全拒绝',async()=>{const m=await model();for(const nodes of[[source('A','E'),source('E','',true),source('H','I'),source('I','H')],[source('A','E'),source('E','',true),source('H','Missing')],[source('A','E'),source('E','A',true)],[source('A','E,E'),source('E','',true)],[source('A','A')]])assert.throws(()=>m.derive(graph(nodes)));assert.throws(()=>m.derive(graph([source('A'),source('A')])));assert.throws(()=>m.derive(graph([source('A')],'B')));assert.throws(()=>m.derive(graph([source('A')],'A,')));});
test('L036 图语义严格ID/标题/论断/支持；未完成图只作草稿',async()=>{const m=await model();for(const d of[graph([source('1A')],'1A'),graph([{...source('A'),label:''}]),graph([source('A')],''),{...graph([source('A')]),claims:[{id:'Q1',text:' ',supports:'A'}]},{...graph([source('A')]),claims:[{id:'Q1',text:'a',supports:'A'},{id:'Q1',text:'b',supports:'A'}]}])assert.throws(()=>m.derive(d));assert.equal(m.prepareStoredState(m.emptyDraft()).nodes[0].label,'');assert.throws(()=>m.derive(m.emptyDraft()),/标题/);});
test('L036 seeded DAG独立递归集合oracle100图，BFS完整原始未知集合',async()=>{const m=await model();let seed=27;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};for(let run=0;run<100;run++){const nodes=Array.from({length:8},(_,i)=>source('N'+i));for(let i=0;i<8;i++){const deps=nodes.slice(i+1).filter(()=>random()<.3).map(row=>row.id);nodes[i].upstream=deps.join(',');nodes[i].original=!deps.length&&random()<.5;}const r=m.derive(graph(nodes,'N0,N1,N2')).claims[0],seenAll=new Set();for(const s of r.supports){const reachable=new Set();function walk(id){reachable.add(id);for(const next of nodes.find(n=>n.id===id).upstream.split(',').filter(Boolean))walk(next);}walk(s.supportId);assert.deepEqual(s.reachableIds,nodes.filter(n=>reachable.has(n.id)).map(n=>n.id));for(const id of reachable)seenAll.add(id);}assert.deepEqual(r.originalIds,nodes.filter(n=>seenAll.has(n.id)&&n.original).map(n=>n.id));assert.deepEqual(r.unknownTerminalIds,nodes.filter(n=>seenAll.has(n.id)&&!n.original&&!n.upstream).map(n=>n.id));}});
test('L036 指数路径DAG保留reachability而不枚举所有路径',async()=>{const m=await model(),nodes=[source('A','L1a,L1b')];for(let layer=1;layer<=18;layer++)for(const suffix of['a','b'])nodes.push(source('L'+layer+suffix,layer===18?'E':`L${layer+1}a,L${layer+1}b`));nodes.push(source('E','',true));const r=m.derive(graph(nodes)).claims[0];assert.equal(r.supports[0].reachableIds.length,38);assert.equal(r.supports[0].witnesses.length,1);assert.equal(r.supports[0].witnesses[0].path.length,20);assert.equal(r.originalSourceCount,1);});
test('L036 节点/边/论断/支持容量明确拒绝且上界有效',async()=>{const m=await model(),nodes=Array.from({length:40},(_,i)=>source('N'+i,'',true)),d=graph(nodes,nodes.slice(0,20).map(n=>n.id).join(','));d.claims=Array.from({length:10},(_,i)=>({id:'Q'+i,text:'claim',supports:d.claims[0].supports}));assert.equal(m.derive(d).claims.length,10);assert.equal(m.derive(d).claims[9].originalSourceCount,20);assert.throws(()=>m.derive({...d,nodes:[...nodes,source('Extra')]}),/40/);assert.throws(()=>m.derive({...d,claims:[...d.claims,{id:'Q99',text:'x',supports:'N0'}]}),/10/);assert.throws(()=>m.derive(graph(nodes,nodes.slice(0,21).map(n=>n.id).join(','))),/20/);const dense=Array.from({length:16},(_,i)=>source('N'+i,Array.from({length:15-i},(_,j)=>'N'+(i+j+1)).join(',')));assert.throws(()=>m.derive(graph(dense,'N0')),/100/);});
test('L036 文本/类型/UTF8原始容量/版本校验，配置不存derived',async()=>{const m=await model(),d=m.example(),stored=m.prepareStoredState({...d,result:{fake:true}});assert.equal(Object.hasOwn(stored,'result'),false);assert.equal(stored.schemaVersion,1);assert.deepEqual(m.validateStoredState(stored),stored);assert.throws(()=>m.validateStoredState({...stored,schemaVersion:2}),/版本/);assert.throws(()=>m.validateStoredState({...stored,extra:'x'.repeat(65536)}),/64KiB/);for(const patch of[{label:'a'.repeat(201)},{original:'true'},{location:null},{label:'\ud800'},{upstream:'a'.repeat(1301)}])assert.throws(()=>m.derive({...d,nodes:[{...d.nodes[0],...patch},...d.nodes.slice(1)]}));const full={nodes:Array.from({length:40},(_,i)=>({...source('N'+i),label:'汉'.repeat(200),location:'汉'.repeat(300)})),claims:Array.from({length:10},(_,i)=>({id:'Q'+i,text:'汉'.repeat(1000),supports:'N0'}))};assert.throws(()=>m.derive(full),/64KiB/);});
test('L036 snapshot/完整Markdown图和分组无注入，无遗漏未选节点',async()=>{const m=await model(),d=m.example();d.nodes.push({...source('Unused'),label:'<script>`````'});const before=structuredClone(d),r=m.derive(d),md=m.reportMarkdown({draft:d,result:r});assert.deepEqual(d,before);assert.equal(r.nodes.length,5);assert.equal(r.edges.length,3);assert.match(md,/Unused/);assert.match(md,/&lt;script&gt;/);assert.doesNotMatch(md,/<script>/);assert.match(md,/`{6}json/);assert.match(md,/"sharedUpstreamGroups"/);assert.match(md,/A → E/);d.nodes[0].label='changed';assert.notEqual(r.nodes[0].label,'changed');});
test('L036 真实默认UI3/1/共享列表/完整预览与JSONMD副本',async t=>{const calls=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});const tool=(await import('../src/renderer/features/L036/index.js')).default,root=new NodeStub('div'),life=tool.create(root,{});await button(root,'核对来源').fire('click');assert.match(root.textContent,/支持文献 3.*原始来源 1.*未知终点 0/);assert.match(root.textContent,/支持 A, B, C/);assert.match(root.textContent,/A → E/);assert.equal(walk(root).filter(n=>n.className==='l036-preview').length,2);await button(root,'导出完整 JSON').fire('click');await button(root,'导出完整 Markdown').fire('click');assert.equal(JSON.parse(calls[0].content).result.claims[0].originalSourceCount,1);assert.equal(calls[1].copyOnly,true);assert.match(calls[1].content,/共享|sharedUpstreamGroups/);life.destroy();});
test('L036 真实original勾选影响未知终点；编辑失效与重复支持去重',async t=>{dom(t,{});const tool=(await import('../src/renderer/features/L036/index.js')).default,root=new NodeStub('div'),life=tool.create(root,{});await button(root,'核对来源').fire('click');const original=control(root,'来源4原始标记');original.checked=false;await original.fire('change');assert.equal(walk(root).some(n=>n.className==='l036-stat'),false);await fill(root,'论断1支持','A,B,C,A');await button(root,'核对来源').fire('click');assert.match(root.textContent,/支持文献 3.*原始来源 0.*未知终点 1/);assert.match(root.textContent,/重复支持去除 1/);assert.match(root.textContent,/未知终点：A → E/);life.destroy();});
test('L036 实际增删来源/论断完整图未知边拒绝，不自动改ID引用',async t=>{dom(t,{});const tool=(await import('../src/renderer/features/L036/index.js')).default,root=new NodeStub('div'),life=tool.create(root,{});await button(root,'添加来源').fire('click');await fill(root,'来源5标题','未选支');await fill(root,'来源5上游','Missing');await button(root,'核对来源').fire('click');assert.match(root.textContent,/未知来源Missing/);await control(root,'删除来源5').fire('click');await button(root,'添加论断').fire('click');await fill(root,'论断2文本','第二论断');await fill(root,'论断2支持','E');await button(root,'核对来源').fire('click');assert.equal(walk(root).filter(n=>n.className==='l036-stat').length,2);await control(root,'删除论断2').fire('click');await fill(root,'来源4ID','F');await button(root,'核对来源').fire('click');assert.match(root.textContent,/未知来源E/);life.destroy();});
test('L036 空白/示例按钮、安全文本和合法未完成草稿export结果null',async t=>{const calls=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});const tool=(await import('../src/renderer/features/L036/index.js')).default,root=new NodeStub('div'),life=tool.create(root,{});await button(root,'新建空白图').fire('click');await button(root,'导出完整 JSON').fire('click');assert.equal(JSON.parse(calls[0].content).result,null);await fill(root,'来源1标题','<img onerror=alert(1)>');await fill(root,'论断1文本','人工论断');await fill(root,'论断1支持','S1');await button(root,'核对来源').fire('click');assert.match(root.textContent,/<img onerror/);assert.equal(walk(root).some(n=>n.tagName==='img'),false);assert.match(root.textContent,/原始来源 0.*未知终点 1/);await button(root,'载入三篇同源示例').fire('click');assert.equal(control(root,'来源1ID').value,'A');life.destroy();});
test('L036 生命周期schema原输入恢复无derived/无计时器，容量整份拒绝',async t=>{dom(t,{});const saved=[],old=global.setTimeout;global.setTimeout=()=>{throw Error('no timer');};t.after(()=>global.setTimeout=old);const m=await model(),tool=(await import('../src/renderer/features/L036/index.js')).default,root=new NodeStub('div'),life=tool.create(root,{config:{set:(key,value)=>saved.push(value)}});await fill(root,'来源1位置','第8页');await button(root,'核对来源').fire('click');life.deactivate();const stored=saved.at(-1);assert.equal(stored.schemaVersion,1);assert.equal(Object.hasOwn(stored,'result'),false);life.destroy();const restoredRoot=new NodeStub('div'),restored=tool.create(restoredRoot,{config:{get:()=>stored}});assert.equal(control(restoredRoot,'来源1位置').value,'第8页');assert.equal(walk(restoredRoot).some(n=>n.className==='l036-stat'),false);await fill(restoredRoot,'来源1标题','x'.repeat(201));await button(restoredRoot,'核对来源').fire('click');assert.match(restoredRoot.textContent,/整份核对失败/);restored.destroy();for(const state of[{...stored,schemaVersion:2},{...stored,noise:'x'.repeat(65536)}]){const node=new NodeStub('div'),instance=tool.create(node,{config:{get:()=>state}});assert.match(node.textContent,/草稿未恢复/);instance.destroy();}assert.equal(m.derive(stored).claims[0].supportCount,3);});
test('L036 副本capability/ok严格/取消/失败/销毁异步',async t=>{let response={ok:'true'};const calls=[];dom(t,{saveTextSupportsCopyOnly:false,saveText:async p=>{calls.push(p);return response;}});const tool=(await import('../src/renderer/features/L036/index.js')).default,root=new NodeStub('div'),life=tool.create(root,{});await button(root,'导出完整 JSON').fire('click');assert.equal(calls.length,0);window.toolbox.files.saveTextSupportsCopyOnly=true;for(const next of[{ok:'true'},{canceled:true},{ok:false,error:'EEXIST'}]){response=next;await button(root,'导出完整 JSON').fire('click');assert.equal(calls.at(-1).copyOnly,true);assert.doesNotMatch(root.textContent,/已导出完整新副本/);}assert.match(root.textContent,/EEXIST/);await fill(root,'来源1标题','x'.repeat(201));const count=calls.length;await button(root,'导出完整 JSON').fire('click');assert.equal(calls.length,count);assert.match(root.textContent,/整份导出拒绝/);await fill(root,'来源1标题','合法');let resolve;window.toolbox.files.saveText=()=>new Promise(done=>resolve=done);const pending=button(root,'导出完整 JSON').fire('click');life.destroy();resolve({ok:true});await pending;assert.equal(root.children.length,0);});
