const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {pathToFileURL}=require('node:url');
const feature=path.resolve(__dirname,'../src/renderer/features/E027');
const modelPromise=import(pathToFileURL(path.join(feature,'model.mjs')).href);
const questionsPromise=import(pathToFileURL(path.join(feature,'questions.mjs')).href);
const OPTIONS={players:['小明','小红','小蓝'],questionCount:1};
async function make(options=OPTIONS,bank){const {Estimate}=await modelPromise;return new Estimate(options,bank?{bank}:undefined);}
function submit(game,value){const v=game.view();game.enter(v.questionNo,v.player);return game.submit(value,v.questionNo,v.player);}
function reveal(game,values=['80','110','140']){const q=game.view().questionNo;game.start(q);values.forEach(value=>submit(game,value));game.reveal(q);}
const SMALL=[{id:'MY1',prompt:'假定一盒放100颗珠子，估计共有多少颗？',unit:'颗',reference:'100',explanation:'题设固定100颗。'},{id:'MY2',prompt:'假定一根彩带长0.3米，估计长度。',unit:'米',reference:'0.3',explanation:'题设长度固定为0.30米。'}];

test('thirty original fixed-value questions are unique, validated and explain references without live price claims',async()=>{const {QUESTIONS}=await questionsPromise;const {validateBank}=await modelPromise;assert.equal(QUESTIONS.length,30);assert.equal(new Set(QUESTIONS.map(q=>q.id)).size,30);assert.equal(new Set(QUESTIONS.map(q=>q.prompt)).size,30);assert.equal(validateBank(QUESTIONS).length,30);assert.ok(QUESTIONS.filter(q=>q.unit==='元').every(q=>q.prompt.includes('本题假定')&&q.explanation.includes('虚构价格')));assert.equal(QUESTIONS[0].reference,'100');});
test('integer scaling parses two decimal places exactly, including maximum and rejects ambiguous or nonfinite forms',async()=>{const {parseValue,formatValue}=await modelPromise;for(const [s,n] of [['0',0],['0.1',10],['0.01',1],['0.30',30],['999999.99',99999999],['1000000.00',100000000],[' 2.5 ',250]])assert.equal(parseValue(s),n);assert.equal(formatValue(30),'0.30');assert.equal(formatValue(100000000),'1000000.00');for(const s of [0,null,'NaN','Infinity','1e2','-1','+1','1,000','01','.5','1.','0.001','1000000.01','1000001',' '.repeat(33)+'1'])assert.throws(()=>parseValue(s));for(const n of [NaN,-1,0.1,100000001])assert.throws(()=>formatValue(n));});
test('reference100 guesses80/110/140 rank errors10/20/40, with explicit points3/2/1',async()=>{const p=await make();reveal(p);const round=p.view().round;assert.equal(round.reference,'100.00');assert.deepEqual(round.ranking.map(p=>[p.player,p.error,p.rank,p.points]),[[1,'10.00',1,3],[0,'20.00',2,2],[2,'40.00',3,1]]);assert.deepEqual(round.scoresAfter,[2,3,1]);});
test('decimal ties use exact integer errors and competition ranking gaps, never floating cancellation',async()=>{const {rankGuesses,parseValue}=await modelPromise;const rows=rankGuesses(parseValue('0.30'),['0.20','0.40','0.60'].map(parseValue));assert.deepEqual(rows.map(r=>[r.errorScaled,r.rank,r.points]),[[10,1,3],[10,1,3],[30,3,1]]);assert.throws(()=>rankGuesses(1,[1]));assert.throws(()=>rankGuesses(0,[1,Infinity]));});
test('bank imports require version, exact fields, unique IDs/prompts, units, explanation and string reference within bounds',async()=>{const {parseBank}=await modelPromise;const raw=questions=>JSON.stringify({version:1,questions});assert.equal(parseBank(raw(SMALL)).length,2);for(const s of ['{',JSON.stringify({version:2,questions:SMALL}),JSON.stringify({version:1,questions:SMALL,extra:1}),raw([]),raw(Array(101).fill(SMALL[0])),raw([SMALL[0],SMALL[0]]),raw([{...SMALL[0],reference:100}]),raw([{...SMALL[0],unit:''}]),raw([{...SMALL[0],explanation:' '}]),raw([{...SMALL[0],prompt:'x'.repeat(241)}]),raw([{...SMALL[0],id:'bad id'}]),raw([{...SMALL[0],reference:'0.001'}]),raw([{...SMALL[0],extra:1}]),raw([SMALL[0],{...SMALL[0],id:'other',prompt:` ${SMALL[0].prompt} `}]),' '.repeat(65537)])assert.throws(()=>parseBank(s));});
test('player counts, normalized distinct names and whole bounded question counts are enforced',async()=>{const {validateOptions}=await modelPromise;for(const o of [{...OPTIONS,players:['A']},{...OPTIONS,players:Array(9).fill('A')},{...OPTIONS,players:['A','ａ']},{...OPTIONS,players:['A\nB','C']},{...OPTIONS,questionCount:0},{...OPTIONS,questionCount:31},{...OPTIONS,questionCount:1.2}])assert.throws(()=>validateOptions(o,30));assert.equal(validateOptions({players:['A','B'],questionCount:30},30).questionCount,30);});
test('each player must explicitly enter and submit once, and public views do not expose guesses or host reference',async()=>{const p=await make();assert.equal(p.reveal(1),false);assert.equal(p.submit('80',1,0),false);p.start(1);assert.equal(p.enter(1,1),false);p.enter(1,0);p.submit('80',1,0);const v=p.view();assert.deepEqual(v.submittedPlayers,[0]);assert.equal(v.guesses,undefined);assert.equal(v.reference,undefined);assert.equal(v.round,null);assert.equal(p.submit('99',1,0),false);assert.equal(p.reveal(1),false);submit(p,'110');submit(p,'140');assert.equal(p.view().phase,'sealed');assert.equal(p.view().round,null);assert.deepEqual(p.view().scores,[0,0,0]);assert.equal(p.reveal(1),true);assert.equal(p.reveal(1),false);});
test('invalid current guess is rejected without consuming the player, and pause keeps sealed guesses while returning input to handoff',async()=>{const p=await make();p.start(1);p.enter(1,0);assert.throws(()=>p.submit('NaN',1,0));assert.equal(p.view().player,0);p.submit('80',1,0);p.enter(1,1);p.pause();assert.equal(p.submit('110',1,1),false);assert.equal(p.reveal(1),false);p.resume();assert.equal(p.view().phase,'handoff');assert.equal(p.view().player,1);assert.deepEqual(p.view().submittedPlayers,[0]);submit(p,'110');submit(p,'140');p.pause();assert.equal(p.reveal(1),false);p.resume();assert.equal(p.reveal(1),true);});
test('next-round input order rotates, past round data is hidden and cumulative totals combine points across distinct units only',async()=>{const p=await make({...OPTIONS,questionCount:2},SMALL);reveal(p);p.next(1);p.start(2);assert.equal(p.view().player,1);assert.equal(p.view().round,null);submit(p,'0.30');submit(p,'0.20');submit(p,'0.60');p.reveal(2);p.next(2);const r=p.result();assert.equal(r.rounds[0].unit,'颗');assert.equal(r.rounds[1].unit,'米');assert.deepEqual(r.ranking.map(p=>[p.player,p.points]),[[1,6],[0,3],[2,3]]);assert.deepEqual(r.ranking.map(p=>p.rank),[1,2,2]);assert.equal(r.totalError,undefined);});
test('stale question/player tokens and duplicate reveal/next cannot submit twice or add duplicate points',async()=>{const p=await make({...OPTIONS,questionCount:2},SMALL);reveal(p);assert.equal(p.reveal(1),false);p.next(1);assert.equal(p.next(1),false);assert.equal(p.start(1),false);p.start(2);assert.equal(p.enter(1,1),false);p.enter(2,1);assert.equal(p.submit('50',1,1),false);assert.equal(p.submit('50',2,0),false);assert.equal(p.view().submittedPlayers.length,0);});
test('ending an unrevealed round suppresses all entered guesses and reference, while retaining already revealed rounds',async()=>{const p=await make({...OPTIONS,questionCount:2},SMALL);reveal(p);p.next(1);p.start(2);submit(p,'0.44');assert.equal(p.end(2),true);const r=p.result();assert.equal(r.rounds.length,1);assert.equal(r.abandoned.reference,undefined);assert.equal(r.abandoned.guesses,undefined);assert.equal(JSON.stringify(r).includes('0.44'),false);assert.deepEqual(r.abandoned.submittedPlayers,[1]);assert.equal(p.pause(),false);});
test('recent history is version-independent validator with ten small entries and rejects oversized or invalid point totals',async()=>{const {cleanHistory}=await modelPromise;const row={options:OPTIONS,finishedAt:'2026-10-03',completedRounds:1,points:[2,3,1],rounds:SMALL};assert.equal(cleanHistory(Array(15).fill(row)).length,10);assert.equal(cleanHistory([row])[0].rounds,undefined);for(const bad of [{...row,completedRounds:2},{...row,points:[4,1,1]},{...row,points:[-1,0,0]},null])assert.equal(cleanHistory([bad]).length,0);});

class Element{
  constructor(tag,doc){this.nodeType=1;this.tagName=tag.toUpperCase();this.doc=doc;this.children=[];this.attributes={};this.style={};this.dataset={};this.events=new Map();this.value='';this.disabled=false;this._text='';}
  setAttribute(k,v){this.attributes[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;}
  getAttribute(k){return this.attributes[k];}
  append(...items){for(const item of items){item.parentNode=this;this.children.push(item);}}
  replaceChildren(...items){this.children.forEach(x=>{x.parentNode=null;});this.children=[];this._text='';this.append(...items);}
  addEventListener(t,fn){const list=this.events.get(t)||[];list.push(fn);this.events.set(t,list);}
  emit(t,props={}){if(this.disabled&&t==='click')return;const e={target:this,detail:1,preventDefault(){this.defaultPrevented=true;},...props};for(const fn of this.events.get(t)||[])fn(e);}
  click(){this.emit('click');}
  focus(){this.doc.activeElement=this;}
  set textContent(v){this.replaceChildren();this._text=String(v);}
  get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}
}
async function mount({activate=true,files=null,saved=null,failSave=false}={}){
  const modules={...await modelPromise,...await questionsPromise};const doc={hidden:false,activeElement:null,events:new Map(),createElement(tag){return new Element(tag,this);},createTextNode(v){return {nodeType:3,textContent:String(v)};},addEventListener(t,fn){this.events.set(t,fn);},removeEventListener(t){this.events.delete(t);}};doc.body=doc.createElement('body');const root=doc.createElement('main');doc.body.append(root);const windows=new Map();const writes=[];const win={toolbox:{files},addEventListener(t,fn){windows.set(t,fn);},removeEventListener(t){windows.delete(t);}};const context=vm.createContext({document:doc,window:win,URL,Date,Math,Promise,structuredClone,console,...modules,module:{exports:{}}});vm.runInContext(fs.readFileSync(path.resolve(feature,'../../core/ui.js'),'utf8').replace(/export /g,'')+'\nmodule.exports={h};',context);context.h=context.module.exports.h;const source=fs.readFileSync(path.join(feature,'index.js'),'utf8').replace(/^import .*;\r?$/gm,'').replace('export default','module.exports =').replace(/import\.meta\.url/g,JSON.stringify(pathToFileURL(path.join(feature,'index.js')).href));vm.runInContext(source,context);const lifecycle=context.module.exports.create(root,{config:{get(){return saved;},async set(key,value){if(failSave)throw new Error('disk full');writes.push({key,value});}}});
  const all=(node=root)=>[node,...node.children.flatMap(x=>x.nodeType===1?all(x):[])];const button=text=>all().find(e=>e.tagName==='BUTTON'&&e.textContent===text);const field=label=>all().find(e=>e.getAttribute('aria-label')===label);function setup(options=OPTIONS){field('玩家名称').value=options.players.join('\n');field('题数').value=String(options.questionCount);button('建立新局').click();}function enter(name,value){button(`我是${name}，独处输入`).click();const input=field('我的密封猜测');if(value!==undefined)input.value=value;return input;}function submitGuess(name,value){const input=enter(name,value);button('密封提交，交给下一位').click();return input;}if(activate){lifecycle.activate();setup();}return {root,doc,windows,lifecycle,all,button,field,writes,setup,enter,submitGuess,text(){return root.textContent;},dom(){return all().map(e=>`${e.textContent} ${e.value} ${JSON.stringify(e.attributes)}`).join('\n');}};
}
function complete(ui){ui.button('开始本题').click();ui.submitGuess('小明','80');ui.submitGuess('小红','110');ui.submitGuess('小蓝','140');ui.button('统一揭晓').click();ui.button('结算本局').click();}

test('inactive create, explicit handoff and sealed guesses keep host reference and others guesses out of all DOM nodes',async()=>{const ui=await mount({activate:false});ui.button('建立新局').click();assert.equal(ui.button('开始本题'),undefined);ui.lifecycle.activate();ui.setup();ui.button('开始本题').click();assert.equal(ui.dom().includes('100.00'),false);const old=ui.submitGuess('小明','80.25');assert.equal(old.value,'');assert.equal(ui.dom().includes('80.25'),false);assert.equal(ui.button('统一揭晓'),undefined);ui.submitGuess('小红','110.50');assert.equal(ui.dom().includes('110.50'),false);assert.equal(ui.dom().includes('100.00'),false);ui.submitGuess('小蓝','140.75');assert.ok(ui.button('统一揭晓'));assert.equal(ui.dom().includes('140.75'),false);assert.equal(ui.dom().includes('100.00'),false);ui.button('统一揭晓').click();assert.match(ui.text(),/100.00 个/);assert.match(ui.text(),/80.25 个/);ui.lifecycle.destroy();});
test('accepted three-player example produces table order小红/小明/小蓝 and cumulative points3/2/1',async()=>{const ui=await mount();complete(ui);const reportRows=ui.all().filter(e=>e.tagName==='TR').slice(1);assert.equal(reportRows[0].textContent,'1小红110.00 个10.00 个3');assert.equal(reportRows[1].textContent,'2小明80.00 个20.00 个2');assert.equal(reportRows[2].textContent,'3小蓝140.00 个40.00 个1');assert.match(ui.text(),/第 1 名 · 小红 · 3 积分/);ui.lifecycle.destroy();});
test('invalid guess retains private input, Enter submit works and repeated/stale submit cannot change the next player',async()=>{const ui=await mount();ui.button('开始本题').click();const input=ui.enter('小明','1e2');const old=ui.button('密封提交，交给下一位');old.click();assert.match(ui.text(),/不接受指数/);assert.equal(input.value,'1e2');input.value='80';input.emit('keydown',{key:'Enter',repeat:true});assert.ok(ui.button('密封提交，交给下一位'));input.emit('keydown',{key:'Enter'});assert.equal(input.value,'');old.click();assert.ok(ui.button('我是小红，独处输入'));ui.lifecycle.destroy();});
test('pause/blur/hiding scrub unsubmitted guess and require re-handoff while preserving already sealed players',async()=>{const ui=await mount();ui.button('开始本题').click();ui.submitGuess('小明','80');const input=ui.enter('小红','110.77');ui.windows.get('blur')();assert.equal(input.value,'');assert.equal(ui.dom().includes('110.77'),false);ui.button('继续').click();assert.ok(ui.button('我是小红，独处输入'));ui.submitGuess('小红','110');const third=ui.enter('小蓝','140');ui.doc.hidden=true;ui.doc.events.get('visibilitychange')();assert.equal(third.value,'');ui.doc.hidden=false;ui.button('继续').click();assert.ok(ui.button('我是小蓝，独处输入'));ui.submitGuess('小蓝','140');assert.ok(ui.button('统一揭晓'));ui.lifecycle.deactivate();ui.lifecycle.activate();assert.ok(ui.button('继续'));ui.button('继续').click();ui.button('统一揭晓').click();assert.match(ui.text(),/110.00 个/);ui.lifecycle.destroy();assert.equal(ui.doc.events.size,0);assert.equal(ui.windows.size,0);});
test('host reference is created only inside explicit editor and closing or hiding clears reference/draft/list DOM',async()=>{const ui=await mount();assert.equal(ui.dom().includes('100.00'),false);ui.button('主持人独处，编辑题库').click();assert.match(ui.text(),/参考 100 个/);ui.field('主持人参考值').value='12345.67';ui.field('主持人题库 JSON').value='private reference 987.65';ui.button('隐藏参考值，关闭编辑').click();assert.equal(ui.field('主持人参考值').value,'');assert.equal(ui.field('主持人题库 JSON').value,'');assert.equal(ui.dom().includes('12345.67'),false);assert.equal(ui.dom().includes('987.65'),false);assert.equal(ui.text().includes('参考 100 个'),false);ui.button('主持人独处，编辑题库').click();ui.field('主持人参考值').value='456.78';ui.windows.get('blur')();assert.equal(ui.dom().includes('456.78'),false);assert.equal(ui.text().includes('参考 100 个'),false);ui.lifecycle.destroy();});
test('custom reference/JSON imports validate strictly, render text safely and modify only the next game',async()=>{const ui=await mount();ui.button('开始本题').click();ui.button('主持人独处，编辑题库').click();ui.field('主持人题库 JSON').value='{';ui.button('校验并替换题库').click();assert.match(ui.text(),/不是有效 JSON/);const q={id:'SAFE',prompt:'<img src=x onerror=boom> 自建数量题',unit:'个',reference:'100',explanation:'固定参考100。'};ui.field('主持人题库 JSON').value=JSON.stringify({version:1,questions:[q]});ui.button('校验并替换题库').click();assert.equal(ui.all().some(e=>e.tagName==='IMG'),false);ui.button('隐藏参考值，关闭编辑').click();ui.button('继续').click();assert.match(ui.text(),/10 行小积木/);assert.equal(ui.text().includes('固定参考100'),false);ui.setup();ui.button('开始本题').click();assert.match(ui.text(),/<img src=x onerror=boom> 自建数量题/);ui.submitGuess('小明','80');ui.submitGuess('小红','110');ui.submitGuess('小蓝','140');ui.button('统一揭晓').click();assert.match(ui.text(),/固定参考100/);ui.lifecycle.destroy();});
test('self-built decimal value is manual, bounded and canonicalized; duplicate and invalid settings errors preserve current game',async()=>{const ui=await mount();ui.button('主持人独处，编辑题库').click();ui.field('自建题题面').value='自建彩带长度';ui.field('自建题单位').value='米';ui.field('主持人参考值').value='0.333';ui.field('参考值说明').value='手填固定参考';ui.button('添加自建题').click();assert.match(ui.text(),/最多两位小数/);ui.field('主持人参考值').value='0.3';ui.button('添加自建题').click();assert.match(ui.text(),/0.30 米/);ui.button('隐藏参考值，关闭编辑').click();ui.button('继续').click();ui.field('玩家名称').value='A\nA';ui.button('建立新局').click();assert.match(ui.text(),/名称不可重复/);assert.ok(ui.button('开始本题'));ui.lifecycle.destroy();});
test('double-click reveal and stale next controls cannot award or skip twice',async()=>{const ui=await mount();ui.button('开始本题').click();ui.submitGuess('小明','80');ui.submitGuess('小红','110');ui.submitGuess('小蓝','140');const reveal=ui.button('统一揭晓');reveal.emit('click',{detail:2});assert.ok(ui.button('统一揭晓'));reveal.click();reveal.click();assert.match(ui.text(),/小红3 积分/);const next=ui.button('结算本局');next.click();next.click();assert.match(ui.text(),/已统一揭晓 1 轮/);ui.lifecycle.destroy();});
test('JSON report honors copyOnly and records decimal/scaled errors, while successful export requires ok===true',async()=>{const calls=[];const ui=await mount({files:{saveTextSupportsCopyOnly:true,async saveText(arg){calls.push(arg);return {ok:true};}}});complete(ui);ui.button('导出完整报告 JSON 副本').click();await new Promise(r=>setImmediate(r));assert.equal(calls[0].copyOnly,true);const r=JSON.parse(calls[0].content);assert.equal(r.precision,2);assert.equal(r.scale,100);assert.equal(r.rounds[0].ranking[0].errorScaled,1000);assert.equal(r.rounds[0].ranking[0].error,'10.00');assert.match(ui.text(),/已保存为新 JSON 副本/);ui.lifecycle.destroy();});
test('resolved ok:false, missing ok, canceled and thrown save outcomes never produce a false success message',async()=>{for(const outcome of [{ok:false,error:'拒绝写入'},undefined,{canceled:true},new Error('故障')]){const ui=await mount({files:{saveTextSupportsCopyOnly:true,async saveText(){if(outcome instanceof Error)throw outcome;return outcome;}}});complete(ui);ui.button('导出完整报告 JSON 副本').click();await new Promise(r=>setImmediate(r));assert.equal(ui.text().includes('已保存为新 JSON 副本'),false);assert.match(ui.text(),outcome?.canceled?/已取消保存/:/保存失败/);if(outcome?.error)assert.match(ui.text(),/拒绝写入/);ui.lifecycle.destroy();}});
test('old unsafe bridge prevents text writes; private bank export round-trips with copyOnly and strict success checks',async()=>{let calls=0;const blocked=await mount({files:{async saveText(){calls++;}}});complete(blocked);blocked.button('导出完整报告 JSON 副本').click();assert.equal(calls,0);assert.match(blocked.text(),/支持副本保护/);blocked.lifecycle.destroy();const args=[];const ui=await mount({files:{saveTextSupportsCopyOnly:true,async saveText(arg){args.push(arg);return {ok:true};}}});ui.button('主持人独处，编辑题库').click();ui.button('导出题库 JSON 副本').click();await new Promise(r=>setImmediate(r));const {parseBank}=await modelPromise;assert.equal(parseBank(args[0].content).length,30);assert.equal(args[0].copyOnly,true);ui.lifecycle.destroy();});
test('early end suppresses unrevealed numbers from output, bounded draft/history and persistence failures preserve report access',async()=>{const calls=[];const ui=await mount({failSave:true,files:{saveTextSupportsCopyOnly:true,async saveText(arg){calls.push(arg);return {ok:true};}}});ui.button('开始本题').click();ui.submitGuess('小明','812.34');ui.button('结束本局，保留已揭晓轮').click();await new Promise(r=>setImmediate(r));assert.match(ui.text(),/历史保存失败/);ui.button('导出完整报告 JSON 副本').click();await new Promise(r=>setImmediate(r));const raw=calls[0].content;assert.equal(raw.includes('812.34'),false);assert.equal(raw.includes('100.00'),false);assert.equal(JSON.parse(raw).rounds.length,0);ui.button('主持人独处，编辑题库').click();const draft=ui.field('主持人题库 JSON');draft.value='x'.repeat(70000);draft.emit('input');assert.equal(draft.value.length,65536);ui.lifecycle.destroy();});
test('small versioned history records once, keeps ten and never stores question banks, guesses or references',async()=>{const saved={version:1,recent:Array(10).fill({options:OPTIONS,finishedAt:'2026-10-03',completedRounds:1,points:[2,3,1]})};const ui=await mount({saved});complete(ui);ui.lifecycle.deactivate();ui.lifecycle.activate();await new Promise(r=>setImmediate(r));assert.equal(ui.writes.length,1);assert.equal(ui.writes[0].value.recent.length,10);const raw=JSON.stringify(ui.writes[0]);assert.equal(raw.includes('reference'),false);assert.equal(raw.includes('guess'),false);assert.equal(raw.includes('rounds'),false);ui.lifecycle.destroy();});
test('eight players and one hundred custom questions complete within bounded records and exact maximum cumulative points',async()=>{const bank=Array.from({length:100},(_,i)=>({id:`LIMIT${i}`,prompt:`第${i+1}个固定数量题`,unit:'个',reference:String(i),explanation:'题面指定的固定数量。'}));const players=Array.from({length:8},(_,i)=>`P${i+1}`);const p=await make({players,questionCount:100},bank);for(let n=1;n<=100;n++){p.start(n);for(let i=0;i<8;i++)submit(p,String(n-1));p.reveal(n);p.next(n);}const r=p.result();assert.equal(r.rounds.length,100);assert.ok(r.rounds.every(round=>round.ranking.length===8));assert.ok(r.ranking.every(row=>row.points===800&&row.rank===1));assert.equal(p.next(100),false);});
test('starting another round removes prior revealed DOM data and future history version is ignored',async()=>{const saved={version:2,recent:[{options:OPTIONS,finishedAt:'2099-01-01',completedRounds:1,points:[2,3,1]}]};const ui=await mount({saved});assert.equal(ui.text().includes('2099-01-01'),false);ui.setup({...OPTIONS,questionCount:2});ui.button('开始本题').click();ui.submitGuess('小明','80');ui.submitGuess('小红','110');ui.submitGuess('小蓝','140');ui.button('统一揭晓').click();assert.equal(ui.dom().includes('100.00'),true);ui.button('下一题').click();assert.equal(ui.dom().includes('100.00'),false);assert.equal(ui.dom().includes('110.00'),false);ui.button('开始本题').click();assert.ok(ui.button('我是小红，独处输入'));ui.lifecycle.destroy();});
