const test=require('node:test');const assert=require('node:assert/strict');const model=()=>import('../src/renderer/features/L030/model.mjs');
const domain100=Array.from({length:100},(_,i)=>String(i)).join(' ');
function one(left,right,values='1'){return{left,right,variables:[{name:'x',values}]};}
test('L030 核心x*x vs x完整4行，仅-1与2反例',async()=>{const m=await model(),r=await m.analyze(m.example());assert.equal(r.complete,true);assert.equal(r.checked,4);assert.equal(r.matches,2);assert.equal(r.errors,0);assert.deepEqual(r.rows.filter(row=>row.kind==='counterexample').map(row=>row.input.x.value),['-1','2']);assert.deepEqual(r.rows.map(row=>row.left.value),['1','0','1','4']);});
test('L030 三布尔德摩根8行独立真值oracle与Cartesian顺序',async()=>{const m=await model(),r=await m.analyze(m.example('demorgan'));assert.equal(r.total,8);assert.equal(r.counterexamples,0);const expected=[true,true,true,true,true,false,false,false];assert.deepEqual(r.rows.map(row=>row.left.value),expected);assert.deepEqual(r.rows.map(row=>row.right.value),expected);assert.deepEqual(r.rows[1].input,{x:{type:'bool',value:false},y:{type:'bool',value:false},z:{type:'bool',value:true}});assert.match(r.conclusion,/不证明域外/);});
test('L030 优先级/左结合/一元/比较/逻辑完整手算',async()=>{const m=await model();for(const[left,right]of [['1+2*3','7'],['(1+2)*3','9'],['10-3-2','5'],['-x * +2','-2'],['!false && false || true','true'],['1+2<4 && 2*3==6','true'],['false==true || true!=false','true'],['3>=3 && 2<=3 && 3>2 && 2!=3','true']]){const r=await m.analyze(one(left,right));assert.equal(r.matches,1,left);}const r=await m.analyze(m.example('precedence'));assert.deepEqual(r.rows.filter(row=>row.kind==='match').map(row=>row.input.x.value),['0']);});
test('L030 跨表达式bool/int输出不同类型算反例不coerce',async()=>{const m=await model(),r=await m.analyze(one('x==1','x','0 1'));assert.equal(r.counterexamples,2);assert.equal(r.rows[0].left.type,'bool');assert.equal(r.rows[0].right.type,'int');assert.equal(r.errors,0);});
test('L030 静态类型检查未执行分支，bool+int/逻辑int/链比较拒绝',async()=>{const m=await model();for(const left of ['false && (true+1==2)','true || (1&&false)','!1','-true','true<false','1==true','x<2<3','x&&true'])await assert.rejects(m.analyze(one(left,'true')),/类型不匹配/);});
test('L030 纯布尔短路允许跳过合法类型但会超界的右侧',async()=>{const m=await model(),large=Array(22).fill('x').join('*');for(const left of [`false && (${large}>0)`,`true || (${large}>0)`]){const r=await m.analyze(one(left,left.startsWith('false')?'false':'true','1000000'));assert.equal(r.matches,1);assert.equal(r.errors,0);}const r=await m.analyze(one(`true && (${large}>0)`,'true','1000000'));assert.equal(r.errors,1);});
test('L030 双边相同超界错误单独分类，绝不错误=等价',async()=>{const m=await model(),expr=Array(22).fill('x').join('*'),r=await m.analyze(one(expr,expr,'1000000'));assert.equal(r.errors,1);assert.equal(r.matches,0);assert.equal(r.counterexamples,0);assert.equal(r.rows[0].kind,'runtimeError');assert.equal(r.rows[0].left.ok,false);assert.equal(r.rows[0].right.ok,false);assert.match(r.conclusion,/不能判定/);});
test('L030 BigInt精确超过Number安全域仍区分相邻整数',async()=>{const m=await model(),r=await m.analyze(one('x*x*x','x*x*x+1','1000000'));assert.equal(r.rows[0].left.value,'1000000000000000000');assert.equal(r.rows[0].right.value,'1000000000000000001');assert.equal(r.counterexamples,1);});
test('L030 无JS/除法/浮点/属性/赋值/调用与语法错误拒绝',async()=>{const m=await model();for(const expr of ['x/1','x%2','x**2','x=1','x===1','x!==1','x.foo','x[0]','eval(1)','constructor','function(){}','1.5','1e3','01','1000001','x ? 1 : 2','(x','x x','','1 & 1','true | false'])await assert.rejects(m.analyze(one(expr,'x')));await assert.rejects(m.analyze(one('y','x')),/未声明变量/);});
test('L030 token128/AST32/括号32/表达式UTF8有界拒绝',async()=>{const m=await model();for(const[expr,pattern]of [['!'.repeat(128)+'true',/token/],['-'.repeat(32)+'x',/AST深度/],['('.repeat(33)+'x'+')'.repeat(33),/括号/],['x+'.repeat(32)+'x',/AST深度/],[' '.repeat(2049),/2048/]])await assert.rejects(m.analyze(one(expr,'x')),pattern);const r=await m.analyze(one('('.repeat(32)+'x'+')'.repeat(32),'x'));assert.equal(r.matches,1);});
test('L030 有限唯一变量域/类型/输入整数/字节/10000Cartesian拒绝',async()=>{const m=await model();for(const values of ['','true 1','1 1','-0 0','1.5','1e3','1000001','-1000001','null','[1]','01',Array(101).fill('1').join(' '),'汉'.repeat(700)])await assert.rejects(m.analyze(one('x','x',values)));for(const variables of [[],Array(4).fill({name:'x',values:'1'}),[{name:'__proto__',values:'1'}],[{name:'x',values:'1'},{name:'x',values:'2'}],['x','y','z'].map(name=>({name,values:domain100}))])await assert.rejects(m.analyze({left:'x',right:'x',variables}));});
test('L030 完整10000域与让出次数，结果不截断',async()=>{const m=await model();let yields=0;const r=await m.analyze({left:'x+y',right:'y+x',variables:['x','y'].map(name=>({name,values:domain100}))},{yieldControl:async()=>{yields++;}});assert.equal(r.checked,10000);assert.equal(r.rows.length,10000);assert.equal(r.matches,10000);assert.equal(yields,199);assert.deepEqual(r.rows.at(-1).input,{x:{type:'int',value:'99'},y:{type:'int',value:'99'}});});
test('L030 取消保留50已检查与完整域，零检查取消不宣称等价',async()=>{const m=await model(),draft={left:'x+y',right:'y+x',variables:['x','y'].map(name=>({name,values:domain100}))};const controller=new AbortController();const r=await m.analyze(draft,{signal:controller.signal,yieldControl:async()=>controller.abort()});assert.equal(r.status,'cancelled');assert.equal(r.checked,50);assert.equal(r.total,10000);assert.equal(r.complete,false);assert.match(r.conclusion,/未完成/);controller.abort();const none=await m.analyze(draft,{signal:controller.signal});assert.equal(none.checked,0);assert.equal(none.status,'cancelled');});
test('L030 快照与输入不变、schema/raw64KiB/noDerived/完整MD',async()=>{const m=await model(),d=m.example(),before=structuredClone(d),r=await m.analyze(d);assert.deepEqual(d,before);assert.deepEqual(r,await m.analyze(d));const saved=m.prepareStoredState(d);assert.deepEqual(m.validateStoredState(saved),saved);assert.equal(Object.hasOwn(saved,'compiled'),false);assert.throws(()=>m.validateStoredState({...saved,schemaVersion:2}),/版本/);assert.throws(()=>m.validateStoredState({...saved,hidden:'汉'.repeat(22000)}),/64KiB/);assert.throws(()=>m.prepareStoredState({...d,left:'汉'.repeat(700)}),/2048/);const payload=JSON.parse(JSON.stringify({draft:d,result:r}));assert.equal(payload.result.rows.length,4);assert.match(m.reportMarkdown(payload),/"counterexamples": 2/);assert.match(m.reportMarkdown({draft:d,result:null}),/尚无结果/);assert.doesNotMatch(m.reportMarkdown({draft:{...d,left:'<script>'},result:null}),/<script>/);});
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }

test('L030 真实组件核心反例筛选/全部4行导出/AST/编辑失效',async t=>{const saved=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async payload=>{saved.push(payload);return{ok:true};}});const root=new NodeStub('main'),handle=(await import('../src/renderer/features/L030/index.js')).default.create(root);t.after(()=>handle.destroy());await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('已完整检查 4/4'));assert.ok(root.textContent.includes('一致2 · 反例2 · 运行错误0'));assert.ok(root.textContent.includes('x=-1 [int]'));assert.ok(root.textContent.includes('x=2 [int]'));assert.ok(root.textContent.includes('左：3 tokens / int'));await fill(root,'结果筛选','all');assert.ok(root.textContent.includes('当前4行'));await fill(root,'结果筛选','counterexample');await button(root,'导出完整 JSON').fire('click');await button(root,'导出完整 Markdown').fire('click');assert.equal(JSON.parse(saved[0].content).result.rows.length,4);assert.equal(saved[0].copyOnly,true);assert.match(saved[1].content,/"counterexamples": 2/);await fill(root,'右表达式','x*x');assert.ok(root.textContent.includes('尚无有效穷举结果'));await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('仅指定有限域内全部结果一致'));});
test('L030 组件德摩根8真值/优先级示例与变量增删重复拒绝',async t=>{dom(t,{});const root=new NodeStub('main'),handle=(await import('../src/renderer/features/L030/index.js')).default.create(root);t.after(()=>handle.destroy());await button(root,'载入德摩根真值表').fire('click');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('一致8 · 反例0 · 运行错误0'));await fill(root,'结果筛选','all');assert.ok(root.textContent.includes('当前8行'));await button(root,'删除变量3').fire('click');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('未声明变量'));await button(root,'载入整数反例').fire('click');await button(root,'增加变量').fire('click');await fill(root,'变量2名称','x');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('不可重复'));await button(root,'载入优先级示例').fire('click');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('一致1 · 反例3'));});
test('L030 组件静态类型拒绝/双超界不是一致/精确整数可读',async t=>{dom(t,{});const root=new NodeStub('main'),handle=(await import('../src/renderer/features/L030/index.js')).default.create(root);t.after(()=>handle.destroy());await fill(root,'左表达式','false && (true+1==2)');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('类型不匹配'));assert.ok(root.textContent.includes('尚无有效穷举结果'));const expr=Array(22).fill('x').join('*');await fill(root,'左表达式',expr);await fill(root,'右表达式',expr);await fill(root,'变量1输入域','1000000');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('一致0 · 反例0 · 运行错误1'));await fill(root,'结果筛选','runtimeError');assert.ok(root.textContent.includes('中间整数超过128十进制位'));await fill(root,'左表达式','x*x*x');await fill(root,'右表达式','x*x*x+1');await button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('1000000000000000000'));assert.ok(root.textContent.includes('1000000000000000001'));});
test('L030 组件分页不截断100行导出，取消50行partial和切走/销毁释放',async t=>{const oldSet=global.setTimeout,oldClear=global.clearTimeout,timers=new Map();let serial=0;global.setTimeout=(callback,delay)=>{timers.set(++serial,{callback,delay});return serial;};global.clearTimeout=id=>timers.delete(id);t.after(()=>{global.setTimeout=oldSet;global.clearTimeout=oldClear;});const saved=[];dom(t,{saveTextSupportsCopyOnly:true,saveText:async payload=>{saved.push(payload);return{ok:true};}});const root=new NodeStub('main'),feature=(await import('../src/renderer/features/L030/index.js')).default,handle=feature.create(root);await fill(root,'变量1输入域',domain100);const pending=button(root,'开始完整穷举').fire('click');assert.ok(root.textContent.includes('进行中 50/100'));assert.equal(button(root,'开始完整穷举').disabled,true);await button(root,'取消穷举').fire('click');await pending;assert.equal(timers.size,0);assert.ok(root.textContent.includes('已取消，仅部分 50/100'));await fill(root,'结果筛选','all');await button(root,'导出完整 JSON').fire('click');assert.equal(JSON.parse(saved[0].content).result.rows.length,50);assert.equal(JSON.parse(saved[0].content).result.complete,false);
  const complete=button(root,'开始完整穷举').fire('click');const timer=[...timers.entries()].find(([,value])=>value.delay===0);assert.ok(timer);timer[1].callback();await complete;assert.ok(root.textContent.includes('已完整检查 100/100'));await fill(root,'结果筛选','all');await button(root,'下一页').fire('click');assert.ok(root.textContent.includes('第2/5页'));await button(root,'导出完整 JSON').fire('click');assert.equal(JSON.parse(saved[1].content).result.rows.length,100);
  const stopped=button(root,'开始完整穷举').fire('click');handle.deactivate();await stopped;assert.equal(timers.size,0);assert.ok(root.textContent.includes('已取消，仅部分'));const destroyed=button(root,'开始完整穷举').fire('click');handle.destroy();await destroyed;assert.equal(timers.size,0);assert.equal(root.children.length,0);
});
test('L030 严格副本导出ok/取消/异常/销毁异步guard',async t=>{dom(t,{});const root=new NodeStub('main'),handle=(await import('../src/renderer/features/L030/index.js')).default.create(root);t.after(()=>handle.destroy());await button(root,'导出完整 JSON').fire('click');assert.ok(root.textContent.includes('缺少防覆盖'));global.window.toolbox.files={saveTextSupportsCopyOnly:true,saveText:async()=>({ok:'true'})};await button(root,'导出完整 JSON').fire('click');assert.ok(root.textContent.includes('未确认保存成功'));global.window.toolbox.files.saveText=async()=>({canceled:true});await button(root,'导出完整 JSON').fire('click');assert.ok(root.textContent.includes('已取消'));global.window.toolbox.files.saveText=async()=>({ok:false,error:'EEXIST'});await button(root,'导出完整 JSON').fire('click');assert.ok(root.textContent.includes('EEXIST'));let resolve;global.window.toolbox.files.saveText=()=>new Promise(done=>{resolve=done;});const pending=button(root,'导出完整 JSON').fire('click');handle.destroy();resolve({ok:true});await pending;assert.equal(root.children.length,0);});
test('L030 草稿noDerived/版本容量恢复/超限不写config与保存计时器',async t=>{const oldSet=global.setTimeout,oldClear=global.clearTimeout,timers=new Map();let serial=0;global.setTimeout=callback=>{timers.set(++serial,callback);return serial;};global.clearTimeout=id=>timers.delete(id);t.after(()=>{global.setTimeout=oldSet;global.clearTimeout=oldClear;});dom(t,{});const stored=[],feature=(await import('../src/renderer/features/L030/index.js')).default,root=new NodeStub('main'),handle=feature.create(root,{config:{set:(_key,value)=>stored.push(structuredClone(value))}});await fill(root,'左表达式','x+x');assert.equal(timers.size,1);handle.deactivate();assert.equal(timers.size,0);await button(root,'开始完整穷举').fire('click');assert.equal(Object.hasOwn(stored.at(-1),'rows'),false);assert.equal(Object.hasOwn(stored.at(-1),'compiled'),false);const count=stored.length;await fill(root,'左表达式','汉'.repeat(700));handle.deactivate();assert.equal(stored.length,count);assert.ok(root.textContent.includes('未写入配置'));handle.destroy();assert.equal(timers.size,0);for(const[raw,text]of [[stored.at(-1),'已恢复'],[{schemaVersion:2},'草稿未恢复'],[{...(await model()).prepareStoredState((await model()).example()),hidden:'汉'.repeat(22000)},'草稿未恢复']]){const fresh=new NodeStub('main'),instance=feature.create(fresh,{config:{get:()=>raw}});assert.ok(fresh.textContent.includes(text));assert.ok(fresh.textContent.includes('尚无有效穷举结果'));instance.destroy();}});
