const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const model=()=>import('../src/renderer/features/L048/model.mjs');
class NodeStub {
  constructor(tag = '', text = null) { this.tagName = tag; this.nodeType = text === null ? 1 : 3; this.text = text; this.children = []; this.attributes = {}; this.style = {}; this.dataset = {}; this.className = ''; this.events = {}; this.value = ''; this.checked = false; this.disabled = false; this.classList = { add: (name) => { this.className += ` ${name}`; }, remove: (name) => { this.className = this.className.split(' ').filter((item) => item !== name).join(' '); }, toggle: (name, yes) => { this.classList.remove(name); if (yes) this.classList.add(name); } }; }
  append(...items) { this.children.push(...items.map((item) => item?.nodeType ? item : new NodeStub('', String(item)))); }
  replaceChildren(...items) { this.children = []; this.append(...items); }
  setAttribute(key, value) { this.attributes[key] = String(value); if (key === 'disabled') this.disabled = true; }
  addEventListener(type, callback) { (this.events[type] ||= []).push(callback); }
  get textContent() { return this.text === null ? this.children.map((child) => child.textContent).join('') : this.text; }
  set textContent(value) { this.text = null; this.replaceChildren(String(value)); }
  set innerHTML(_value) { throw new Error('User input must be rendered as text'); }
  async fire(type, extra = {}) { if (type === 'click' && this.disabled) return; for (const callback of this.events[type] || []) await callback({ target: this, preventDefault() {}, stopPropagation() {}, ...extra }); }
}
const walk = (node) => [node, ...node.children.flatMap(walk)];
const button = (root, label) => { const node = walk(root).find((item) => item.tagName === 'button' && item.textContent === label); assert.ok(node, label); return node; };
const control = (root, label) => { const node = walk(root).find((item) => item.attributes['aria-label'] === label); assert.ok(node, label); return node; };
async function fill(root, label, value) { const node = control(root, label); node.value = value; await node.fire(node.tagName === 'select' ? 'change' : 'input'); }
function dom(t, files) { const oldDocument = global.document; const oldWindow = global.window; global.document = { createElement: (tag) => new NodeStub(tag), createTextNode: (value) => new NodeStub('', value) }; global.window = { toolbox: { files } }; t.after(() => { global.document = oldDocument; global.window = oldWindow; }); }
const tick=()=>new Promise(r=>setImmediate(r));async function until(fn){for(let i=0;i<1000;i++){if(fn())return;await tick();}throw Error('timeout');}
async function mount(t, files={saveTextSupportsCopyOnly:true,saveText:async()=>({ok:true})},config={}){dom(t,files);const tool=(await import('../src/renderer/features/L048/index.js')).default;const root=new NodeStub('div'),life=tool.create(root,{config:{get:()=>null,...config}});return{root,life,tool};}
const copy=x=>JSON.parse(JSON.stringify(x));const run=e=>button(e.root,'分析两版人工覆盖').fire('click');async function required(root,id,value){const n=control(root,id+'必保');n.checked=value;await n.fire('change');}function select(root,kind,start,end){const n=control(root,kind+'文本');n.selectionStart=start;n.selectionEnd=end;}

test('L048 independent oracle three beginner terms onlyB3 pending and separate3/3 vs2/3',async()=>{const m=await model(),p=m.makeReport(m.exampleDraft());assert.deepEqual(p.versions.beginner.pendingTermIds,['B3']);assert.deepEqual(p.versions.expert.pendingTermIds,[]);assert.equal(p.versions.expert.coverage.fraction,'3/3');assert.equal(p.versions.beginner.coverage.fraction,'2/3');assert.deepEqual(p.differences,[{id:'F3',expertBound:true,beginnerBound:false}]);assert.equal(p.versions.expert.codePoints,32);assert.equal(p.versions.beginner.codePoints,46);assert.equal(p.facts.length,3);});
test('L048 independent bindings preserve other version; explicit explanation not occurrence',async()=>{const m=await model();let d=m.clearSpan(m.exampleDraft(),'expert','fact','F1');let p=m.makeReport(d);assert.equal(p.versions.expert.coverage.fraction,'2/3');assert.equal(p.versions.beginner.coverage.fraction,'2/3');assert.equal(p.facts[0].statuses.beginner.current,true);d=m.bindSpan(d,'beginner','fact','F3',28,35);p=m.makeReport(d);assert.equal(p.versions.beginner.coverage.fraction,'3/3');assert.equal(p.facts[2].anchors.beginner.quote,'命中时直接复用');d=m.bindSpan(d,'beginner','term','B3',39,45);assert.deepEqual(m.makeReport(d).versions.beginner.pendingTermIds,[]);assert.deepEqual(m.makeReport(d).versions.expert.pendingTermIds,[]);});
test('L048 optional/zero denominator all rows remain and blank source unknown independent ratio',async()=>{const m=await model(),d=m.exampleDraft();d.facts[0].source={label:'',location:'',quote:''};let p=m.makeReport(d);assert.deepEqual(p.sourceReviewFactIds,['F1']);assert.equal(p.versions.expert.coverage.fraction,'3/3');d.facts[2].required=false;p=m.makeReport(d);assert.equal(p.versions.beginner.coverage.fraction,'2/2');assert.equal(p.facts.length,3);d.facts.forEach(f=>f.required=false);p=m.makeReport(d);for(const k of m.KINDS){assert.equal(p.versions[k].coverage.fraction,null);assert.equal(p.versions[k].coverage.ratio,null);}assert.equal(p.facts.length,3);});
test('L048 version edits stale only affected version no drift and shortened old quotes retained',async()=>{const m=await model(),d=m.exampleDraft();d.versions.beginner.text='短';d.versions.beginner.revision++;const p=m.makeReport(d);assert.equal(p.versions.expert.coverage.fraction,'3/3');assert.equal(p.versions.beginner.coverage.fraction,'0/3');assert.deepEqual(p.versions.beginner.pendingTermIds,['B1','B2','B3']);assert.equal(p.versions.beginner.terms[0].explanation.start,3);assert.equal(p.versions.beginner.terms[0].explanation.quote,'临时存储的副本');assert.equal(p.versions.expert.terms[0].status.current,true);});
test('L048 fact meaning edit invalidates both; term name edit only its explanation',async()=>{const m=await model(),d=m.exampleDraft();d.facts[0].statement='新事实';d.facts[0].revision++;d.versions.beginner.terms[0].name='缓存修订';d.versions.beginner.terms[0].revision++;const p=m.makeReport(d);assert.equal(p.versions.expert.coverage.fraction,'2/3');assert.equal(p.versions.beginner.coverage.fraction,'1/3');assert.deepEqual(p.versions.beginner.pendingTermIds,['B1','B3']);assert.equal(p.versions.beginner.terms[1].status.current,true);});
test('L048 literal quote mismatch stays unknown until explicit rebind and shared span permitted',async()=>{const m=await model(),d=m.exampleDraft();d.facts[0].anchors.expert.quote='用户不匹配旧句';assert.equal(m.makeReport(d).facts[0].statuses.expert.current,false);let next=m.bindSpan(d,'expert','fact','F1',0,6);assert.equal(m.makeReport(next).facts[0].statuses.expert.current,true);next=m.bindSpan(next,'expert','term','E1',0,6);assert.equal(m.makeReport(next).versions.expert.terms[0].status.current,true);assert.equal(m.makeReport(next).versions.expert.terms[0].explanation.quote,'缓存存储副本');});
test('L048 UTF16 exact surrogate/CRLF source mapping bounded spans',async()=>{const m=await model(),raw='🙂甲\r\n乙\r他';assert.deepEqual(m.selectionRange(raw,'🙂甲\n乙\n他',4,5),[5,6]);assert.equal(m.spanQuote(raw,5,6),'乙');assert.throws(()=>m.spanQuote(raw,1,2),/代理/);assert.throws(()=>m.spanQuote(raw,0,0),/非空/);assert.throws(()=>m.spanQuote('甲'.repeat(241),0,241),/240/);assert.throws(()=>m.selectionRange(raw,'不匹配',0,1),/不符/);});
test('L048 schema/IDs/invalid versions/future revisions/control and capacity reject whole',async()=>{const m=await model();for(const mutate of[d=>d.schemaVersion=2,d=>d.versions.extra={},d=>d.facts.push(copy(d.facts[0])),d=>d.versions.beginner.terms[0].id='E1',d=>d.facts[0].required=1,d=>d.facts[0].id=['F1'],d=>d.versions.beginner.terms[0].id=['B1'],d=>d.facts[0].anchors.expert.textRevision=2,d=>d.versions.expert.text='x\u0000',d=>d.versions.expert.text='甲'.repeat(16001),d=>d.versions.expert.label='甲'.repeat(161),d=>d.versions.beginner.terms[0].name='']){const d=m.exampleDraft();mutate(d);assert.throws(()=>m.validateDraft(d));}const d=m.exampleDraft();d.versions.expert.text='🙂'.repeat(16000);d.versions.beginner.text='🙂'.repeat(16000);assert.ok(m.validateDraft(d));assert.throws(()=>m.validateDraft(d,{forStorage:true}),/64KiB/);});
test('L048 maximum20facts 10each terms complete and21/11 refuses not truncates',async()=>{const m=await model();let d=m.exampleDraft();for(let i=0;i<17;i++)d=m.addFact(d);for(let i=0;i<9;i++)d=m.addTerm(d,'expert');for(let i=0;i<7;i++)d=m.addTerm(d,'beginner');const p=m.makeReport(d);assert.equal(p.facts.length,20);assert.equal(p.versions.expert.terms.length,10);assert.equal(p.versions.beginner.terms.length,10);assert.equal(p.versions.expert.coverage.fraction,'3/20');assert.equal(p.versions.beginner.coverage.fraction,'2/20');assert.deepEqual(p.versions.beginner.pendingTermIds,['B3','B4','B5','B6','B7','B8','B9','B10']);assert.throws(()=>m.addFact(d),/20/);assert.throws(()=>m.addTerm(d,'expert'),/10/);assert.throws(()=>m.addTerm(d,'beginner'),/10/);});
test('L048 full JSONMD exact snapshots escaped HTML and bounded code fence',async()=>{const m=await model(),d=m.exampleDraft();d.facts[0].note='<script> ````';const p=m.makeReport(d);assert.deepEqual(JSON.parse(m.reportJson(p)).input,d);assert.match(m.reportMarkdown(p),/`{5}json/);assert.doesNotMatch(m.reportMarkdown(p),/<script>/);assert.equal(p.versions.beginner.terms.length,3);});
test('L048 async cancel at each checkpoint no partial and immutable snapshot',async()=>{const m=await model();for(let point=1;point<=4;point++){let calls=0;await assert.rejects(m.analyze(m.exampleDraft(),{yieldControl:async()=>{calls++;},canceled:()=>calls>=point}),/取消/);}const d=m.exampleDraft(),p=await m.analyze(d,{yieldControl:async()=>d.versions.expert.text='外部已改'});assert.equal(p.versions.expert.codePoints,32);assert.equal(p.input.versions.expert.text,m.exampleDraft().versions.expert.text);});
test('L048 direct actual component analysis single pendingB3 and strict full copies',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});await run(e);assert.match(e.root.textContent,/专家稿事实绑定 3\/3/);assert.match(e.root.textContent,/入门稿事实绑定 2\/3/);const pending=walk(e.root).filter(n=>n.dataset.termStatus==='pending');assert.deepEqual(pending.map(n=>n.dataset.term),['B3']);await button(e.root,'导出完整 JSON').fire('click');await button(e.root,'导出完整 Markdown').fire('click');assert.equal(calls.length,2);assert.ok(calls.every(c=>c.copyOnly===true));assert.deepEqual(JSON.parse(calls[0].content).versions.beginner.pendingTermIds,['B3']);e.life.destroy();});
test('L048 UI text selection and explicit positions independently bind fact/term',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});select(e.root,'入门稿',28,35);await button(e.root,'用入门稿选区绑定F3').fire('click');await fill(e.root,'B3入门稿起点','39');await fill(e.root,'B3入门稿终点','45');await run(e);assert.match(e.root.textContent,/数字未确认/);await button(e.root,'确认B3入门稿区间').fire('click');await run(e);await button(e.root,'导出完整 JSON').fire('click');const p=JSON.parse(calls[0].content);assert.equal(p.versions.beginner.coverage.fraction,'3/3');assert.deepEqual(p.versions.beginner.pendingTermIds,[]);assert.equal(p.versions.beginner.terms[2].explanation.quote,'选择替换对象');e.life.destroy();});
test('L048 UI change fact/term/text clears reports; source fields unknown no auto inference',async t=>{const calls=[],e=await mount(t,{saveTextSupportsCopyOnly:true,saveText:async p=>{calls.push(p);return{ok:true};}});await run(e);await fill(e.root,'F1事实','人工新事实');assert.equal(walk(e.root).some(n=>n.tagName==='button'&&n.textContent==='导出完整 JSON'),false);await fill(e.root,'B1术语','人工新术语');await fill(e.root,'F2来源原句','');await run(e);await button(e.root,'导出完整 JSON').fire('click');let p=JSON.parse(calls.at(-1).content);assert.equal(p.versions.expert.coverage.fraction,'2/3');assert.equal(p.versions.beginner.coverage.fraction,'1/3');assert.deepEqual(p.versions.beginner.pendingTermIds,['B1','B3']);assert.deepEqual(p.sourceReviewFactIds,['F2']);await fill(e.root,'专家稿文本','短');await run(e);await button(e.root,'导出完整 JSON').fire('click');p=JSON.parse(calls.at(-1).content);assert.equal(p.versions.expert.coverage.fraction,'0/3');assert.equal(p.versions.beginner.coverage.fraction,'1/3');e.life.destroy();});
test('L048 UI optional zero denominator add/remove ownlists and whole replacement confirmation',async t=>{const e=await mount(t);await fill(e.root,'专家稿来源名','用户来源');await button(e.root,'用三术语示例替换草稿…').fire('click');assert.equal(control(e.root,'专家稿来源名').value,'用户来源');await button(e.root,'保留当前输入').fire('click');assert.equal(control(e.root,'专家稿来源名').value,'用户来源');await button(e.root,'添加共同事实').fire('click');await button(e.root,'添加专家稿术语').fire('click');await button(e.root,'添加入门稿术语').fire('click');await button(e.root,'删除事实F4').fire('click');await button(e.root,'删除术语E2').fire('click');await button(e.root,'删除术语B4').fire('click');for(const id of['F1','F2','F3'])await required(e.root,id,false);await run(e);assert.match(e.root.textContent,/专家稿事实绑定 未定义（0必保）/);assert.match(e.root.textContent,/入门稿事实绑定 未定义（0必保）/);await button(e.root,'用三术语示例替换草稿…').fire('click');await button(e.root,'确认用示例替换当前草稿').fire('click');assert.equal(control(e.root,'专家稿来源名').value,'专家练习稿');e.life.destroy();});
test('L048 UI cancel/edited/inactive/destroyed run does not publish late result',async t=>{const e=await mount(t);let task=run(e);await button(e.root,'取消当前分析').fire('click');await task;assert.equal(walk(e.root).some(n=>n.dataset.fact),false);task=run(e);await fill(e.root,'入门稿文本','新');await task;assert.equal(walk(e.root).some(n=>n.dataset.fact),false);await run(e);assert.match(e.root.textContent,/入门稿事实绑定 0\/3/);task=run(e);e.life.deactivate();await task;e.life.activate();assert.equal(walk(e.root).some(n=>n.dataset.fact),false);task=run(e);e.life.destroy();await task;assert.equal(e.root.children.length,0);});
test('L048 config versioned confirmed input only restore stale and reject oversize/schema',async t=>{const writes=[],e=await mount(t,undefined,{set:(_k,v)=>writes.push(v)});await fill(e.root,'入门稿文本','短');await tick();const stored=writes.at(-1);assert.equal('coverage' in stored,false);assert.equal(stored.versions.beginner.terms[0].explanation.quote,'临时存储的副本');await fill(e.root,'专家稿文本','🙂'.repeat(16000));await fill(e.root,'入门稿文本','🙂'.repeat(16000));assert.match(e.root.textContent,/完整草稿超过64KiB/);e.life.destroy();let root=new NodeStub('div'),life=e.tool.create(root,{config:{get:()=>stored}});assert.equal(control(root,'入门稿文本').value,'短');await button(root,'分析两版人工覆盖').fire('click');assert.match(root.textContent,/入门稿事实绑定 0\/3/);life.destroy();root=new NodeStub('div');life=e.tool.create(root,{config:{get:()=>({...stored,schemaVersion:2})}});assert.match(root.textContent,/草稿未恢复/);assert.equal(control(root,'入门稿文本').value,(await model()).exampleDraft().versions.beginner.text);life.destroy();});
test('L048 config serialized latest writes old callbacks cannot mask pending/oversize warnings',async t=>{const writes=[],resolve=[],initial=(await model()).exampleDraft();initial.versions.expert.location='🙂'.repeat(320);const e=await mount(t,undefined,{get:()=>initial,set:(_k,v)=>{writes.push(v);return new Promise(r=>resolve.push(r));}});await fill(e.root,'专家稿来源名','first');await fill(e.root,'专家稿来源名','latest');assert.equal(writes.length,1);await fill(e.root,'B3入门稿起点','39');resolve.shift()();await until(()=>writes.length===2);assert.equal(writes[1].versions.expert.label,'latest');resolve.shift()();await tick();assert.match(e.root.textContent,/区间数字未确认且不保存/);await fill(e.root,'B3入门稿终点','45');await button(e.root,'确认B3入门稿区间').fire('click');assert.equal(writes.length,3);await fill(e.root,'专家稿文本','🙂'.repeat(16000));assert.match(e.root.textContent,/完整草稿超过64KiB/);resolve.shift()();await tick();assert.match(e.root.textContent,/完整草稿超过64KiB/);assert.equal(writes.length,3);e.life.destroy();});
test('L048 strict capability ok/cancel failures and held export destruction',async t=>{const calls=[];let response={ok:'true'};const e=await mount(t,{saveTextSupportsCopyOnly:false,saveText:async p=>{calls.push(p);return response;}});await run(e);await button(e.root,'导出完整 JSON').fire('click');assert.equal(calls.length,0);window.toolbox.files.saveTextSupportsCopyOnly=true;for(const value of[{ok:'true'},{canceled:true},{ok:false,error:'EEXIST'}]){response=value;await button(e.root,'导出完整 JSON').fire('click');assert.doesNotMatch(e.root.textContent,/新副本已保存/);}let finish;window.toolbox.files.saveText=()=>new Promise(r=>finish=r);const task=button(e.root,'导出完整 JSON').fire('click');e.life.destroy();finish({ok:true});await task;assert.equal(e.root.children.length,0);});
test('L048 empty fact/term lists remain explicit zero denominator, no inference and Unicode count',async()=>{const m=await model(),d=m.exampleDraft();d.facts=[];d.versions.expert.terms=[];d.versions.beginner.terms=[];d.versions.beginner.text='🙂e\u0301\r\n';d.versions.beginner.revision++;const p=m.makeReport(d);assert.equal(p.versions.beginner.codePoints,5);assert.equal(p.versions.beginner.coverage.fraction,null);assert.equal(p.versions.expert.coverage.fraction,null);assert.deepEqual(p.versions.beginner.pendingTermIds,[]);assert.equal(p.versions.beginner.terms.length,0);assert.equal(p.facts.length,0);assert.deepEqual(p.differences,[]);});
