const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{Worker}=require('node:worker_threads');const base=path.resolve(__dirname,'../src/renderer/features/T023'),m=()=>import('../src/renderer/features/T023/model.mjs'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),host=require('../src/renderer/features/T023/host.cjs'),copy=x=>JSON.parse(JSON.stringify(x));
const word={text:'hello',confidence:90,line:0,bbox:{x0:100,y0:200,x1:120,y1:220}};
test('T023 precise unique ranges sorted no truncation',async()=>{const x=await m();assert.deepEqual(x.parseRange('5, 1-3',5),[1,2,3,5]);for(const range of['','0','2-1','1,1','1-2,2','21','1..3','1,,2','foo'])assert.throws(()=>x.parseRange(range,20));assert.throws(()=>x.parseRange('1-11',20),/10页/);assert.throws(()=>x.parseRange('1',21),/20页/)});
test('T023 selected pixels independent multiplication edge limits',async()=>{const x=await m();assert.equal(x.rasterBudget(3000,2000),6000000);assert.equal(x.rasterBudget(3000,2000,18000000),24000000);for(const args of[[3001,2000],[3000,2000,18000001],[0,100],[1.1,2],[12001,1],[NaN,5]])assert.throws(()=>x.rasterBudget(...args));});
test('T023 inverse four axis orientations affine oracle exact roundtrip',async()=>{const x=await m();for(const v of[[2,0,0,-2,0,800],[0,2,2,0,-20,-10],[-3,0,0,3,400,-12],[0,-1,-1,0,300,600]]){const inv=x.inverse(v);for(const p of[[0,0],[30,180],[-8,24]]){const a=v[0]*p[0]+v[2]*p[1]+v[4],b=v[1]*p[0]+v[3]*p[1]+v[5];assert.ok(Math.abs(inv[0]*a+inv[2]*b+inv[4]-p[0])<1e-8);assert.ok(Math.abs(inv[1]*a+inv[3]*b+inv[5]-p[1])<1e-8);}}assert.throws(()=>x.inverse([1,1,1,1,0,0]));assert.throws(()=>x.inverse([NaN,0,0,1,0,0]));});
test('T023 baseline placement independent coordinate and word advance oracle',async()=>{const x=await m(),v=[2,0,0,-2,0,800],matrix=x.textMatrix(v,word.bbox,5,1);assert.deepEqual(matrix.map(x=>x===0?0:x),[2,0,0,10,50,291.5]);const endX=matrix[4]+5*matrix[0];assert.equal(endX,60);assert.equal(endX*2,word.bbox.x1);assert.equal(800-matrix[5]*2,217);});
test('T023 Unicode codepoint bound bbox invalid/blank confidence neveraccuracy',async()=>{const x=await m(),w=x.validateWords([{...word,text:'中😀'}],400,400);assert.equal(w[0].editedText,'中😀');assert.deepEqual(x.validateWords([],10,10),[]);assert.equal(x.validateWords([{...word,text:'😀'.repeat(128)}],400,400).length,1);for(const patch of[{text:'x'.repeat(129)},{text:'\ud800'},{text:'x\n'},{confidence:101},{confidence:NaN},{line:-1},{bbox:{x0:10,y0:10,x1:5,y1:12}},{bbox:{x0:10,y0:10,x1:501,y1:12}}])assert.throws(()=>x.validateWords([{...word,...patch}],400,400));assert.throws(()=>x.validateWords(Array(2001).fill(word),400,400),/2000/)});
test('T023 edited lines full preview original preserved blank edits omitted',async()=>{const x=await m(),words=x.validateWords([{...word,text:'甲'},{...word,text:'乙'},{...word,text:'下一行',line:1}],400,400);words[0].editedText='改';words[1].editedText='';assert.equal(x.pageText(words),'改\n下一行');assert.equal(words[0].text,'甲')});
test('T023 strict settings schema no file or derived content',async()=>{const x=await m();assert.deepEqual(x.settings(),{schemaVersion:1,language:'eng',dpi:200,range:'1'});for(const s of[false,{...x.settings(),schemaVersion:2},{...x.settings(),pdf:'x'},{...x.settings(),dpi:201},{...x.settings(),language:'fra'},{...x.settings(),range:'x'.repeat(121)}])assert.throws(()=>x.settings(s));});
test('T023 complete records escaped Markdown no raw HTML labels',async()=>{const x=await m(),pages=[{page:1,words:x.validateWords([{...word,text:'<img>'}],400,400),imageSha256:'abc'}],r=x.report({name:'<svg>',sha256:'def'},x.settings(),pages,{sha256:'ghi'});pages[0].words[0].text='changed';assert.equal(r.pages[0].words[0].text,'<img>');assert.ok(x.markdown(r).includes('&lt;img&gt;'));assert.equal(x.markdown(r).includes('<svg>'),false);assert.ok(r.notes.some(n=>n.includes('不是准确率')))});
test('T023 all fixed vendor files hashes and package integrity present',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(base,'vendor/manifest.json')));assert.ok(manifest.files.length>200);for(const f of manifest.files){const bytes=fs.readFileSync(path.join(base,'vendor',f.path));assert.equal(bytes.length,f.bytes);assert.equal(sha(bytes),f.sha256)}for(const p of manifest.packages){assert.match(p.integrity,/^sha512-/);assert.match(p.url,/^https:\/\/registry.npmjs.org\//)}assert.equal(manifest.models.length,3);assert.ok(fs.readFileSync(path.join(base,'vendor/font/LICENSE'),'utf8').includes('SIL OPEN FONT LICENSE'));});
let sender=100;async function begin(t,bytes=fs.readFileSync(path.join(base,'fixtures/printed-sentence.pdf'))){const context={senderId:++sender},r=await host.invoke('begin',{name:'scan.pdf',size:bytes.length,sha256:sha(bytes),settings:(await m()).settings()},context);assert.equal(r.ok,true);t.after(()=>host.disposeSender(context.senderId));return{context,id:r.jobId,bytes,call:(op,p={})=>host.invoke(op,{jobId:r.jobId,...p},context)};}
async function append(e){for(let n=0;n<e.bytes.length;n+=24000){const r=await e.call('append',{sequence:n/24000,base64:e.bytes.subarray(n,n+24000).toString('base64')});assert.equal(r.ok,true)}}
test('T023 genuine bundled host ready no external engine executable required',async()=>{const r=await host.invoke('status',{}, {senderId:99});assert.equal(r.ok,true);assert.equal(r.offline,true);assert.deepEqual(r.languages,['eng','chi_sim','chi_sim+eng'])});
test('T023 sender-bound chunks sequence/canonical/length reject prior to seal',async t=>{const e=await begin(t);assert.equal((await e.call('append',{sequence:1,base64:'QQ=='})).ok,false);assert.equal((await e.call('append',{sequence:0,base64:'Q!=='})).ok,false);assert.equal((await host.invoke('append',{jobId:e.id,sequence:0,base64:'QQ=='},{senderId:e.context.senderId+100})).ok,false);assert.equal((await e.call('seal')).ok,false);assert.equal((await e.call('recognize')).ok,false);await append(e);const sealed=await e.call('seal');assert.equal(sealed.ok,true);assert.equal(sealed.sourceSha256,sha(e.bytes));assert.equal(sealed.pageCount,1)});
test('T023 hash mismatch prevents PDFinspect and arbitrary paths/ops unused',async t=>{const e=await begin(t);e.bytes=Buffer.from(e.bytes);e.bytes[20]^=1;await append(e);assert.equal((await e.call('seal')).ok,false);assert.equal((await e.call('exec',{command:'not-run'})).ok,false);assert.equal((await e.call('write',{target:'/tmp/not-run',copyOnly:true})).ok,false)});
test('T023 page order/pixel/PNG size and incomplete upload no fake build',async t=>{const e=await begin(t);await append(e);assert.equal((await e.call('seal')).ok,true);const p={page:1,width:1200,height:450,transform:[2,0,0,-2,0,450],size:100,sha256:'a'.repeat(64)};assert.equal((await e.call('page_begin',{...p,page:2})).ok,false);assert.equal((await e.call('page_begin',{...p,width:12000,height:12000})).ok,false);assert.equal((await e.call('page_begin',p)).ok,true);assert.equal((await e.call('recognize')).ok,false);assert.equal((await e.call('build')).ok,false);assert.equal((await e.call('choose',{format:'pdf'})).ok,false)});
test('T023 cancel/sender dispose rejects late oldjob newjob IDs do not reuse',async t=>{const e=await begin(t);assert.equal((await host.cancel(e.id,e.context)).ok,true);assert.equal((await e.call('append',{sequence:0,base64:'QQ=='})).ok,false);const e2=await begin(t);assert.notEqual(e.id,e2.id);host.disposeSender(e2.context.senderId);assert.equal((await e2.call('seal')).ok,false)});
test('T023 actual local OCR fixture independent known sentence, no remote fetch',async()=>{const worker=new Worker(path.join(base,'ocr-worker.cjs'));try{const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('OCRfixture timeout')),20000);worker.once('error',e=>{clearTimeout(timer);reject(e)});worker.once('message',r=>{clearTimeout(timer);resolve(r)});worker.postMessage({language:'eng',png:fs.readFileSync(path.join(base,'fixtures/printed-sentence.png'))});});assert.equal(result.ok,true,result.error);const text=result.words.map(w=>w.text).join(' ');assert.ok(text.includes('The quick brown fox jumps over the lazy dog.'));assert.ok(result.words.every(w=>w.bbox.x0>=0&&w.bbox.x1<=1200));}finally{await worker.terminate();}});
class N{constructor(tag='',text=null){this.tagName=tag;this.nodeType=text===null?1:3;this.text=text;this.children=[];this.attributes={};this.events={};this.style={};this.value='';this.disabled=false;}append(...xs){this.children.push(...xs.map(x=>x?.nodeType?x:new N('',String(x))))}replaceChildren(...xs){this.children=[];this.append(...xs)}setAttribute(k,v){this.attributes[k]=String(v)}getAttribute(k){return this.attributes[k]}addEventListener(k,cb){(this.events[k]??=[]).push(cb)}get textContent(){return this.text===null?this.children.map(x=>x.textContent).join(''):this.text}set textContent(x){this.text=null;this.replaceChildren(String(x))}querySelectorAll(q){return walk(this).filter(x=>x.tagName===q)}remove(){this.removed=true}replaceWith(n){this.replacement=n}async fire(type){for(const f of this.events[type]??[])await f({target:this})}}const walk=n=>[n,...n.children.flatMap(walk)],control=(e,l)=>walk(e.root).find(n=>n.attributes['aria-label']===l),button=(e,l)=>walk(e.root).find(n=>n.tagName==='button'&&n.textContent===l);async function mount(t,config={}){const old={document:global.document,window:global.window};global.document={createElement:t=>new N(t),createTextNode:s=>new N('',s)};global.window={toolbox:{features:{cancelHost:async()=>({ok:true}),callHost:async()=>({ok:false,error:'not fixture'})}}};t.after(()=>{global.document=old.document;global.window=old.window});const root=new N('div'),life=(await import('../src/renderer/features/T023/index.js')).default.create(root,{config:{get:()=>null,...config}});return{root,life};}
const tick=()=>new Promise(r=>setImmediate(r));
test('T023 DOM actual settings controls safe input and disabled output without PDF',async t=>{const saved=[],e=await mount(t,{set:async(k,v)=>saved.push({k,v})});assert.equal(button(e,'逐页离线OCR').disabled,true);assert.equal(button(e,'选择PDF新副本路径').disabled,true);control(e,'识别语言').value='chi_sim';await control(e,'识别语言').fire('change');control(e,'渲染DPI').value='150';await control(e,'渲染DPI').fire('change');control(e,'识别页范围').value='1-2';await control(e,'识别页范围').fire('input');await tick();assert.equal(saved.at(-1).v.range,'1-2');assert.deepEqual(Object.keys(saved.at(-1).v).sort(),['dpi','language','range','schemaVersion']);});
test('T023 DOM source pre-read capacity refusal no decode/host request',async t=>{const e=await mount(t),n=control(e,'选择扫描PDF');let reads=0;n.files=[{size:6291457,name:'large.pdf',arrayBuffer:async()=>{reads++;return new ArrayBuffer(0)}}];await n.fire('change');assert.equal(reads,0);assert.ok(e.root.textContent.includes('6MiB'));assert.equal(button(e,'逐页离线OCR').disabled,true)});
test('T023 DOM late File read after deactivate ignored no source restore on activate',async t=>{const e=await mount(t),n=control(e,'选择扫描PDF');let resolve;n.files=[{size:20,name:'late.pdf',arrayBuffer:()=>new Promise(r=>resolve=r)}];const pending=n.fire('change');e.life.deactivate();resolve(new Uint8Array(20).buffer);await pending;e.life.activate();assert.equal(button(e,'逐页离线OCR').disabled,true);assert.ok(e.root.textContent.includes('文件与OCR结果已释放'));e.life.destroy();assert.equal(e.root.children[0].removed,true)});
test('T023 DOM invalid version preserved no silent persistence explicit overwrite only',async t=>{let count=0;const e=await mount(t,{get:()=>({schemaVersion:2,language:'eng'}),set:async()=>count++});control(e,'识别语言').value='eng';await control(e,'识别语言').fire('change');await tick();assert.equal(count,0);assert.ok(button(e,'使用当前设置覆盖不可读草稿…'));});
test('T023 DOM queued settings retain order including leave, errors honest',async t=>{const saved=[];let release;const e=await mount(t,{set:async(k,v)=>{saved.push(v);if(saved.length===1)await new Promise(r=>release=r)}});control(e,'识别语言').value='eng';await control(e,'识别语言').fire('change');await tick();control(e,'识别语言').value='chi_sim';await control(e,'识别语言').fire('change');e.life.deactivate();release();await tick();await tick();assert.deepEqual(saved.map(x=>x.language),['eng','chi_sim']);});
async function fullPipeline(t,source=fs.readFileSync(path.join(base,'fixtures/printed-sentence.pdf')),png=fs.readFileSync(path.join(base,'fixtures/printed-sentence.png'))){const e=await begin(t,source);await append(e);assert.equal((await e.call('seal')).ok,true);assert.equal((await e.call('page_begin',{page:1,width:1200,height:450,transform:[2,0,0,-2,0,450],size:png.length,sha256:sha(png)})).ok,true);const src=e.bytes;e.bytes=png;await append(e);e.bytes=src;const r=await e.call('recognize');assert.equal(r.ok,true,r.error);e.page=r.page;return e;}
async function pdfBytes(e){const built=await e.call('build');assert.equal(built.ok,true,built.error);const chunks=[];for(let offset=0;offset<built.output.bytes;offset+=24000){const r=await e.call('read_pdf',{offset});assert.equal(r.ok,true);chunks.push(Buffer.from(r.base64,'base64'))}const bytes=Buffer.concat(chunks);assert.equal(sha(bytes),built.output.sha256);return{bytes,built};}
async function extract(bytes){const pdfjs=await import('../node_modules/pdfjs-dist/legacy/build/pdf.mjs'),d=await pdfjs.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,disableFontFace:true}).promise;try{const results=[];for(let n=1;n<=d.numPages;n++)results.push((await(await d.getPage(n)).getTextContent()).items.map(x=>x.str).join(''));return results;}finally{await d.destroy();}}
test('T023 realOCR transparentPDF genuine searchable sentence edits/revert and outputdigest',async t=>{const e=await fullPipeline(t),a=await pdfBytes(e);assert.equal((await extract(e.bytes))[0],'');assert.ok((await extract(a.bytes))[0].includes('The quick brown fox jumps over the lazy dog.'));assert.equal(a.built.report.source.sha256,sha(e.bytes));assert.equal(a.built.report.pages[0].words[0].text,'The');assert.equal((await e.call('edit',{page:1,edits:[{index:0,text:'A'}]})).ok,true);const b=await pdfBytes(e);assert.ok((await extract(b.bytes))[0].includes('A quick'));assert.equal((await e.call('edit',{page:1,edits:[{index:0,text:'The'}]})).ok,true);const c=await pdfBytes(e);assert.ok((await extract(c.bytes))[0].includes('The quick'));assert.equal(c.built.report.pages[0].words[0].editedText,'The');});
test('T023 unsupported glyph refuses complete newPDF and no stale target to save',async t=>{const e=await fullPipeline(t);assert.equal((await e.call('edit',{page:1,edits:[{index:0,text:'😀'}]})).ok,true);const built=await e.call('build');assert.equal(built.ok,false);assert.match(built.error,/不支持/);assert.equal((await e.call('choose',{format:'pdf'})).ok,false);assert.equal((await e.call('edit',{page:1,edits:[{index:0,text:'\ud800'}]})).ok,false)});
test('T023 multi-page source retains original pagecount nonselected images no text',async t=>{const pdf=require(path.join(base,'vendor/pdf-lib.cjs')),d=await pdf.PDFDocument.load(fs.readFileSync(path.join(base,'fixtures/printed-sentence.pdf')));d.addPage([321,456]);const source=Buffer.from(await d.save({useObjectStreams:false})),e=await fullPipeline(t,source),out=await pdfBytes(e),parsed=await pdf.PDFDocument.load(out.bytes),texts=await extract(out.bytes);assert.equal(parsed.getPageCount(),2);assert.deepEqual(parsed.getPage(2-1).getSize(),{width:321,height:456});assert.equal(texts[1],'');assert.equal(out.built.report.pages.length,1);assert.equal(out.built.report.source.pageCount,2);});
test('T023 deliberately empty edited layer has no searchable text and no fake words',async t=>{const e=await fullPipeline(t);assert.equal((await e.call('edit',{page:1,edits:e.page.words.map((w,index)=>({index,text:''}))})).ok,true);const out=await pdfBytes(e);assert.equal((await extract(out.bytes))[0],'');assert.equal(out.built.report.pages[0].words.filter(w=>w.editedText).length,0);});
test('T023 actual pending OCR canceled no result and old senderjob unusable',async t=>{const e=await begin(t);await append(e);assert.equal((await e.call('seal')).ok,true);const bytes=fs.readFileSync(path.join(base,'fixtures/printed-sentence.png'));assert.equal((await e.call('page_begin',{page:1,width:1200,height:450,transform:[2,0,0,-2,0,450],size:bytes.length,sha256:sha(bytes)})).ok,true);e.bytes=bytes;await append(e);const pending=e.call('recognize');await new Promise(r=>setTimeout(r,30));await host.cancel(e.id,e.context);const result=await pending;assert.equal(result.ok,false);assert.match(result.error,/取消/);assert.equal((await e.call('build')).ok,false);});
