const test=require('node:test'),assert=require('node:assert/strict'),model=import('../src/renderer/features/T007/model.mjs');
test('T007: external/internal DTD and entity rejected before parser construction',async()=>{const{parseXML}=await model;let called=0;class Parser{constructor(){called++;}}for(const text of ['<!DOCTYPE r SYSTEM "https://example.com/a.dtd"><r/>','<!DOCTYPE r [<!ENTITY x SYSTEM "file:///secret">]><r>&x;</r>','<!ENTITY x "a"><r/>'])assert.throws(()=>parseXML(text,{DOMParser:Parser}),/拒绝DTD/);assert.equal(called,0);});
test('T007: only initial XML declaration allowed; SVG resources remain inert source text',async()=>{const{validateSource}=await model;assert.equal(validateSource('<?xml version="1.0"?><r/>'),'<?xml version="1.0"?><r/>');assert.equal(validateSource('<svg><image href="https://example.com/a.png"/></svg>'),'<svg><image href="https://example.com/a.png"/></svg>');for(const text of ['<?xml-stylesheet href="https://example.com/a.xsl"?><r/>','<r><?test value?></r>','<r/>\0',' ','a'.repeat(1048577)])assert.throws(()=>validateSource(text));});
test('T007: namespace alias validation rejects non-objects, reserved and invalid bindings',async()=>{const{namespaceMap}=await model;assert.deepEqual(namespaceMap('{"c":"urn:catalog"}'),{c:'urn:catalog'});for(const text of ['[]','null','{"xml":"wrong"}','{"xmlns":"urn:x"}','{"":"urn:x"}','{"a:b":"urn:x"}','{"c":"bad space"}','{"c":3}'])assert.throws(()=>namespaceMap(text));});
function tree(){const doc={nodeType:9,nodeName:'#document',childNodes:[]},root={nodeType:1,nodeName:'r',localName:'r',namespaceURI:'urn:r',parentNode:doc,childNodes:[],attributes:[]};doc.childNodes=[root];doc.documentElement=root;doc.getElementsByTagNameNS=()=>[];for(let i=0;i<2;i++){const n={nodeType:1,nodeName:'i',localName:'i',namespaceURI:'urn:r',parentNode:root,childNodes:[],attributes:[],textContent:'x'+i};const a={nodeType:2,nodeName:'id',localName:'id',namespaceURI:null,ownerElement:n,childNodes:[],value:'ID'+i};n.attributes=[a];root.childNodes.push(n);}return doc;}
test('T007: namespace-expanded descriptive paths distinguish sibling elements and attribute ownership',async()=>{const{nodePath,summarize}=await model;const doc=tree(),second=doc.documentElement.childNodes[1];assert.equal(nodePath(second),'/{urn:r}r[1]/{urn:r}i[2]');assert.equal(nodePath(second.attributes[0]),'/{urn:r}r[1]/{urn:r}i[2]/@{}id');const stats=summarize(doc);assert.equal(stats.nodes,6);assert.equal(stats.elements,3);assert.equal(stats.attributes,2);assert.equal(stats.maxDepth,3);});
test('T007: tree node and depth limits fail completely without partial returned statistics',async()=>{const{summarize}=await model;const doc=tree();doc.documentElement.childNodes=Array.from({length:5000},()=>({nodeType:1,nodeName:'x',parentNode:doc.documentElement,attributes:[],childNodes:[]}));assert.throws(()=>summarize(doc),/5000/);let node=doc.documentElement;node.childNodes=[];for(let i=0;i<33;i++){const child={nodeType:1,nodeName:'x',parentNode:node,attributes:[],childNodes:[]};node.childNodes=[child];node=child;}assert.throws(()=>summarize(doc),/32层/);});
test('T007: scalar result adapter preserves numeric special text, Boolean and string',async()=>{const{query}=await model;class Serializer{}const doc=tree();for(const [value,expected]of [[{resultType:1,numberValue:Infinity},{kind:'number',value:'Infinity'}],[{resultType:1,numberValue:NaN},{kind:'number',value:'NaN'}],[{resultType:2,stringValue:'茶'},{kind:'string',value:'茶'}],[{resultType:3,booleanValue:false},{kind:'boolean',value:false}]]){doc.evaluate=()=>value;assert.deepEqual(query({doc,stats:{},sourceBytes:20},'1',{}, {XMLSerializer:Serializer}).result,expected);}});
test('T007: iterator adapter records every node/path and refuses over500, oversized data or invalid XPath',async()=>{const{query}=await model;class Serializer{serializeToString(n){return'<i>'+n.textContent+'</i>';}}const doc=tree(),nodes=doc.documentElement.childNodes;let at=0;doc.evaluate=()=>({resultType:4,iterateNext:()=>nodes[at++]||null});const r=query({doc,stats:{},sourceBytes:20},'//i',{}, {XMLSerializer:Serializer});assert.equal(r.result.count,2);assert.equal(r.result.nodes[1].text,'x1');assert.match(r.result.nodes[1].path,/i\[2\]/);at=0;doc.evaluate=()=>({resultType:4,iterateNext:()=>at++<501?nodes[0]:null});assert.throws(()=>query({doc,stats:{},sourceBytes:20},'//i',{}, {XMLSerializer:Serializer}),/500/);doc.evaluate=()=>{throw Error('invalid');};assert.throws(()=>query({doc,stats:{},sourceBytes:20},'[',{}, {XMLSerializer:Serializer}),/XPath语法/);assert.throws(()=>query({doc,stats:{},sourceBytes:20},'',{}, {XMLSerializer:Serializer}));});
test('T007: malformed XML rejects parsererror document and never permits partial query',async()=>{const{parseXML}=await model;class Parser{parseFromString(){return{documentElement:{},getElementsByTagNameNS:()=>[{}]};}}assert.throws(()=>parseXML('<r>',{DOMParser:Parser}),/语法不合法/);});
test('T007: Markdown escapes active markup while preserving complete result as text',async()=>{const{markdown}=await model;const text=markdown({policy:'policy',input:{xpath:'//x',sourceBytes:1},stats:{nodes:2},result:{kind:'nodes',nodes:[{path:'/x',serialized:'<script>bad</script>'}]}});assert.equal(text.includes('<script>'),false);assert.match(text,/&lt;script&gt;/);assert.match(text,/完整统计/);});

test('T007: Chromium embedded XHTML parsererror and Firefox parsererror both block partial documents',async()=>{const{parseXML}=await model;for(const ns of ['http://www.w3.org/1999/xhtml','http://www.mozilla.org/newlayout/xml/parsererror.xml']){class Parser{parseFromString(){const doc=tree();doc.getElementsByTagNameNS=(uri,name)=>uri===ns&&name==='parsererror'?[{}]:[];return doc;}}assert.throws(()=>parseXML('<broken>',{DOMParser:Parser}),/语法不合法/);}class Parser{parseFromString(){return tree();}}assert.equal(parseXML('<r/>',{DOMParser:Parser}).stats.elements,3);});
