const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url'),{createHash}=require('node:crypto'),{spawnSync}=require('node:child_process'),H=require('../src/renderer/features/T015/host.cjs');
const load=()=>import(pathToFileURL(path.join(__dirname,'../src/renderer/features/T015/model.mjs')).href);
const example=['D {{project}}/src/components','D {{project}}/docs/empty','F {{project}}/README.md\t'+JSON.stringify('# {{project}}\n😀\n'),'F {{project}}/src/index.txt\t'+JSON.stringify('')].join('\n');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'T015-tests-'));assert.equal(path.dirname(path.resolve(root)),path.resolve(os.tmpdir()));assert.match(path.basename(root),/^T015-tests-/);t.after(()=>fs.rm(root,{recursive:true,force:true}));return root;}
test('T015 renderer actual ESM parses',async()=>{const r=spawnSync(process.execPath,['--input-type=module','--check'],{input:await fs.readFile(path.join(__dirname,'../src/renderer/features/T015/index.js'),'utf8'),encoding:'utf8'});assert.equal(r.status,0,r.stderr);});
test('T015 expands variables and includes every implicit parent with explicit empty leaf',async()=>{const m=await load(),p=m.buildPlan(example,'project=demo');assert.deepEqual(p.directories.map(d=>d.path),['demo','demo/docs','demo/src','demo/docs/empty','demo/src/components']);assert.equal(p.files[0].content,'# demo\n😀\n');assert.equal(p.files[1].utf8Bytes,0);assert.equal(p.totalTextBytes,Buffer.byteLength('# demo\n😀\n'));assert.equal(p.directories.find(d=>d.path==='demo/docs/empty').explicit,true);});
test('T015 rejects traversal absolute reserved control and duplicate/case/NFC paths before creation',async()=>{const m=await load();for(const p of['../outside','/absolute','C:/absolute','A\\B','a/../b','a/CON.txt','a/tail.','a/tail ','a//b','a/\ud800'])assert.throws(()=>m.buildPlan('D '+p,''));for(const t of['D Foo\nD foo','D café\nD café','F a\t""\nD a/b','D A\nD a/b','D a/b\nD a/B'])assert.throws(()=>m.buildPlan(t,''));});
test('T015 missing nested duplicate and invalid variables rejected while literal equals preserved',async()=>{const m=await load();for(const v of['project=x\nproject=y','bad name=x','project={{other}}','project=x\u0000'])assert.throws(()=>m.buildPlan(example,v));assert.throws(()=>m.buildPlan(example,''));assert.throws(()=>m.buildPlan('D {{wrong syntax}}',''));assert.equal(m.buildPlan('F a\t"{{x}}"','x=a=b').files[0].content,'a=b');});
test('T015 only explicit JSON string text not script number or malformed escape',async()=>{const m=await load();for(const line of['F a\ttrue','F a\t{}','F a\t"bad\\x"','F a plain','RUN a','F a\t"\\u0000"'])assert.throws(()=>m.buildPlan(line,''));assert.equal(m.buildPlan('F a.js\t"process.exit(99)"','').files[0].content,'process.exit(99)');});
test('T015 bounded templates and text fail wholly without truncation',async()=>{const m=await load();assert.throws(()=>m.buildPlan('D '+('a/'.repeat(12))+'b',''));assert.throws(()=>m.buildPlan(Array.from({length:101},(_,i)=>'D d'+i).join('\n'),''));assert.throws(()=>m.buildPlan('F a\t'+JSON.stringify('x'.repeat(8193)),''));assert.throws(()=>m.buildPlan('D a','x='+('v'.repeat(4097))));assert.throws(()=>m.buildPlan('D a\n#'+'x'.repeat(24576),''));const p=m.buildPlan('F a\t'+JSON.stringify('x'.repeat(8192)),'');assert.equal(p.files[0].utf8Bytes,8192);});
test('T015 actual tree matches plan directories and files with independent bytes/hash; empty dirs stay empty',async t=>{const root=await fixture(t),m=await load(),target=path.join(root,'new'),p=m.buildPlan(example,'project=demo'),r=await H.writeSkeleton(target,p);assert.equal(r.ok,true);assert.equal(r.report.complete,true);assert.equal(r.report.manifest.length,p.directories.length+p.files.length);for(const dir of p.directories)assert.equal((await fs.lstat(path.join(target,dir.path))).isDirectory(),true);for(const f of p.files){const actual=await fs.readFile(path.join(target,f.path));assert.deepEqual(actual,Buffer.from(f.content,'utf8'));assert.equal(r.report.manifest.find(x=>x.path===f.path).sha256,createHash('sha256').update(actual).digest('hex'));}assert.deepEqual(await fs.readdir(path.join(target,'demo/docs/empty')),[]);assert.deepEqual(await fs.readdir(path.join(target,'demo/src/components')),[]);});
test('T015 existing target stops before changes preserving sentinel bytes and mtime',async t=>{const root=await fixture(t),m=await load(),target=path.join(root,'existing');await fs.mkdir(target);const sentinel=path.join(target,'keep.txt');await fs.writeFile(sentinel,'UNRELATED_EXISTING');const before=await fs.stat(sentinel),r=await H.writeSkeleton(target,m.buildPlan('D a',''));assert.equal(r.ok,false);assert.equal(r.partialPath,null);assert.equal(await fs.readFile(sentinel,'utf8'),'UNRELATED_EXISTING');assert.equal((await fs.stat(sentinel)).mtimeMs,before.mtimeMs);assert.deepEqual(await fs.readdir(target),['keep.txt']);});
test('T015 partial write failure retains owned partial directory and never claims completed',async t=>{const root=await fixture(t),m=await load(),target=path.join(root,'partial'),p=m.buildPlan('D empty\nF first\t"one"\nF second\t"two"','');let calls=0;const r=await H.writeSkeleton(target,p,{writeFile:async(...args)=>{if(++calls===2)throw Object.assign(Error('test write failure'),{code:'EACCES'});return fs.writeFile(...args);}});assert.equal(r.ok,false);assert.equal(r.complete,false);assert.equal(r.partialPath,target);assert.equal(r.completedEntries.filter(e=>e.kind==='file').length,1);assert.equal(await fs.readFile(path.join(target,'first'),'utf8'),'one');assert.equal((await fs.stat(path.join(target,'empty'))).isDirectory(),true);await assert.rejects(fs.stat(path.join(target,'second')),e=>e.code==='ENOENT');});
test('T015 cancellation before create makes no directory and mid-write stops later files with partial manifest',async t=>{const root=await fixture(t),m=await load(),p=m.buildPlan('F first\t"one"\nF second\t"two"',''),c=new AbortController();c.abort();const target=path.join(root,'before');assert.equal((await H.writeSkeleton(target,p,{signal:c.signal})).partialPath,null);await assert.rejects(fs.stat(target));const d=new AbortController(),second=path.join(root,'mid');const r=await H.writeSkeleton(second,p,{signal:d.signal,writeFile:async(...args)=>{await fs.writeFile(...args);d.abort();}});assert.equal(r.ok,false);assert.equal(r.completedEntries.length,1);await assert.rejects(fs.stat(path.join(second,'second')));});
test('T015 expired deadline stops before any target mutation',async t=>{const root=await fixture(t),m=await load(),target=path.join(root,'expired'),r=await H.writeSkeleton(target,m.buildPlan('D x',''),{deadline:0});assert.equal(r.ok,false);assert.equal(r.partialPath,null);await assert.rejects(fs.stat(target));});
test('T015 actual Host choose/plan do not mutate; create only accepts stored confirmed plan from its sender',async t=>{const root=await fixture(t),target=path.join(root,'new'),host=H.createHost({chooseTarget:async()=>({filePath:target,canceled:false})}),ctx={senderId:1};const chosen=await host.invoke('choose_target',{},ctx);assert.equal(chosen.ok,true);await assert.rejects(fs.stat(target));const planned=await host.invoke('plan',{targetId:chosen.target.id,template:example,variables:'project=demo'},ctx);await assert.rejects(fs.stat(target));await assert.rejects(host.invoke('create',{planId:planned.plan.planId,jobId:'job',confirmed:false},ctx));await assert.rejects(host.invoke('create',{planId:planned.plan.planId,jobId:'job',confirmed:true},{senderId:2}));await assert.rejects(host.invoke('create',{planId:planned.plan.planId,jobId:'job',confirmed:true,target:'/outside'},ctx));const done=await host.invoke('create',{planId:planned.plan.planId,jobId:'job',confirmed:true},ctx);assert.equal(done.ok,true);await assert.rejects(host.invoke('create',{planId:planned.plan.planId,jobId:'replay',confirmed:true},ctx));});
test('T015 target appearing after preview is never overwritten',async t=>{const root=await fixture(t),target=path.join(root,'appeared'),host=H.createHost({chooseTarget:async()=>({filePath:target})}),ctx={senderId:1},chosen=await host.invoke('choose_target',{},ctx),planned=await host.invoke('plan',{targetId:chosen.target.id,template:'D child',variables:''},ctx);await fs.writeFile(target,'EXISTING_FILE');const r=await host.invoke('create',{planId:planned.plan.planId,jobId:'create',confirmed:true},ctx);assert.equal(r.ok,false);assert.equal(r.partialPath,null);assert.equal(await fs.readFile(target,'utf8'),'EXISTING_FILE');});
test('T015 concurrent chooser is rejected and disposed sender ignores late dialog result',async()=>{let release,calls=0;const host=H.createHost({chooseTarget:()=>{calls++;return new Promise(r=>release=r);}}),ctx={senderId:1},pending=host.invoke('choose_target',{},ctx);await new Promise(r=>setImmediate(r));await assert.rejects(host.invoke('choose_target',{},ctx));assert.equal(calls,1);host.disposeSender(1);release({canceled:true});assert.deepEqual(await pending,{ok:false,canceled:true});});
