export const MODEL_VERSION='L058-selected-files-four-finite-checks-v1';
export const KINDS=['exists','json-field','count','manual'];
export const LABELS={'exists':'文件存在','json-field':'JSON顶层字段','count':'字数','manual':'人工证据提交'};
export const LIMITS={rules:40,files:8,productBytes:262144,attachmentBytes:131072,totalBytes:3145728,inputBytes:262144,storageBytes:65536,reportBytes:2097152};
const clone=x=>JSON.parse(JSON.stringify(x));export const bytes=s=>new TextEncoder().encode(s).length;
function keys(x,allowed,label){if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).length!==allowed.length||Object.keys(x).some(k=>!allowed.includes(k)))throw Error(`${label}字段无效`)}
function text(x,max,label){if(typeof x!=='string'||[...x].length>max||/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(x)||/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(x))throw Error(`${label}最多${max}Unicode码点且无非法字符`)}
export function nameKey(name){return name.normalize('NFC').toLowerCase()}
export function safeName(name){text(name,120,'文件名');if(!name||name.length>120||/[\x00-\x1f\x7f<>:"|?*\\/]/u.test(name)||/[. ]$/u.test(name)||name==='.'||name==='..'||/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(name))throw Error('文件名须安全单段≤120UTF16单位，禁止路径/保留名');return name}
function revision(n){if(!Number.isInteger(n)||n<1||n>1000000)throw Error('量规版本须1–1000000')}
function bound(s){if(typeof s!=='string'||!/^\d{1,6}$/.test(s)||Number(s)>262144)throw Error('字数界限须明确0–262144整数');return Number(s)}
export function newRule(id='R001',kind='exists'){if(!KINDS.includes(kind))throw Error('未知量规类别');return{id,kind,label:'',target:'',field:'',min:'0',max:'262144',note:'',evidence:[]}}
export function exampleDraft(){const rules=[{...newRule('R001'),label:'报告文件已提交',target:'report.md'},{...newRule('R002','json-field'),label:'数据具有result顶层字段',target:'data.json',field:'result'},{...newRule('R003','count'),label:'报告字数在范围内',target:'report.md',min:'10',max:'100'},{...newRule('R004','manual'),label:'人工作者证据已提交',note:'用户声明已核对产物出处；这里仅检查说明与附件存在。',evidence:['proof.txt']}];return{schemaVersion:1,rubricVersion:1,task:'交付一份报告和数据，保存可复核证据。',source:{label:'用户自编作业量规',location:'本地演示，不证明能力'},rules}}
export function validateDraft(raw,{forStorage=false,forRun=false}={}){if(bytes(JSON.stringify(raw))>(forStorage?LIMITS.storageBytes:LIMITS.inputBytes))throw Error(forStorage?'完整量规草稿超过64KiB，不写配置；请导出报告，关闭只能恢复较早合法输入':'完整量规输入超过256KiB，整份拒绝');keys(raw,['schemaVersion','rubricVersion','task','source','rules'],'草稿');if(raw.schemaVersion!==1)throw Error('仅schemaVersion1');revision(raw.rubricVersion);text(raw.task,2000,'真实任务描述');keys(raw.source,['label','location'],'人工来源');text(raw.source.label,160,'来源名');text(raw.source.location,320,'来源位置');if(!Array.isArray(raw.rules)||raw.rules.length<1||raw.rules.length>40)throw Error('量规须1–40条');const ids=new Set();for(const r of raw.rules){keys(r,['id','kind','label','target','field','min','max','note','evidence'],'规则');if(typeof r.id!=='string'||!/^R\d{3}$/.test(r.id)||ids.has(r.id)||!KINDS.includes(r.kind))throw Error('规则ID唯一且类别须已支持');ids.add(r.id);text(r.label,200,'规则说明');text(r.target,120,'产物文件名');text(r.field,80,'顶层JSON字段');text(r.min,6,'字数下界');text(r.max,6,'字数上界');text(r.note,1800,'人工说明');if(!Array.isArray(r.evidence)||r.evidence.length>8)throw Error('人工附件须≤8个');const names=new Set();for(const name of r.evidence){safeName(name);if(names.has(nameKey(name)))throw Error('重复附件名');names.add(nameKey(name))}if(forRun){if(r.kind!=='manual')safeName(r.target);if(r.kind==='json-field'&&(!r.field||['__proto__','prototype','constructor'].includes(r.field)))throw Error('JSON字段须非空且不使用原型保留名，只查顶层自有字段');if(r.kind==='count'&&bound(r.min)>bound(r.max))throw Error('字数下界不能大于上界')}}return clone(raw)}
export function changeRule(raw,id,key,value){const d=validateDraft(raw),r=d.rules.find(x=>x.id===id);if(!r||!['kind','label','target','field','min','max','note','evidence'].includes(key))throw Error('规则或字段未知');if(d.rubricVersion>=1000000)throw Error('量规版本到上限，未修改');r[key]=clone(value);d.rubricVersion++;return validateDraft(d)}
export function addRule(raw,kind='exists'){const d=validateDraft(raw);if(d.rules.length>=40)throw Error('最多40量规');if(d.rubricVersion>=1000000)throw Error('量规版本到上限');let n=1;while(d.rules.some(r=>r.id==='R'+String(n).padStart(3,'0')))n++;d.rules.push(newRule('R'+String(n).padStart(3,'0'),kind));d.rubricVersion++;return validateDraft(d)}
export function removeRule(raw,id){const d=validateDraft(raw);if(d.rules.length<=1)throw Error('至少保留1条量规');if(d.rubricVersion>=1000000)throw Error('量规版本到上限');if(!d.rules.some(r=>r.id===id))throw Error('规则未知');d.rules=d.rules.filter(r=>r.id!==id);d.rubricVersion++;return d}
export function toBase64(data){let s='';for(let i=0;i<data.length;i+=32768)s+=String.fromCharCode(...data.subarray(i,i+32768));return btoa(s)}
export function fromBase64(value){if(typeof value!=='string'||value.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(value)||value.length>349528)throw Error('文件Base64格式/容量无效');const raw=atob(value),data=Uint8Array.from(raw,c=>c.charCodeAt(0));if(toBase64(data)!==value)throw Error('Base64不是规范编码');return data}
export async function hashBytes(data){const h=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export function validateAssets(raw){if(!Array.isArray(raw)||raw.length>16)throw Error('产物/附件总数最多16');const counts={product:0,attachment:0},names={product:new Set(),attachment:new Set()};let total=0;const assets=raw.map(a=>{keys(a,['role','origin','name','byteLength','sha256','base64'],'文件');if(!['product','attachment'].includes(a.role)||!['selected-file','teaching'].includes(a.origin))throw Error('未知文件角色/来源方式');safeName(a.name);const data=fromBase64(a.base64),limit=a.role==='product'?LIMITS.productBytes:LIMITS.attachmentBytes;if(data.length>limit||a.byteLength!==data.length||!Number.isInteger(a.byteLength)||!/^[a-f0-9]{64}$/.test(a.sha256))throw Error('文件大小/哈希元数据无效');if(++counts[a.role]>8||names[a.role].has(nameKey(a.name)))throw Error('同角色最多8文件，名称NFC及大小写去重');names[a.role].add(nameKey(a.name));total+=data.length;return clone(a)});if(total>LIMITS.totalBytes)throw Error('全部原字节超过3MiB，整批拒绝');return assets}
export async function makeAsset(name,role,buffer,{origin='selected-file'}={}){if(!['product','attachment'].includes(role)||!['selected-file','teaching'].includes(origin))throw Error('文件角色/来源方式未知');safeName(name);const data=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer);if(data.length>(role==='product'?LIMITS.productBytes:LIMITS.attachmentBytes))throw Error(role==='product'?'单产物超过256KiB':'单附件超过128KiB');return{role,origin,name,byteLength:data.length,sha256:await hashBytes(data),base64:toBase64(data)}}
export function utf8Text(asset){const value=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(fromBase64(asset.base64));text(value,262144,'产物文本');return value}
export function countCharacters(value){return[...value].filter(c=>!/^\s$/u.test(c)).length}
export function parseJson(value){const parsed=JSON.parse(value);const pending=[[parsed,0]];let count=0;while(pending.length){const[x,depth]=pending.pop();if(depth>32||++count>20000)throw Error('JSON深度≤32且值节点≤20000，整条解析拒绝');if(typeof x==='number'&&!Number.isFinite(x))throw Error('JSON非有限数拒绝');if(x&&typeof x==='object')for(const v of Object.values(x))pending.push([v,depth+1])}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error('JSON顶层须对象，只检查自有字段');return parsed}
export function evaluate(rule,assets){const product=assets.find(a=>a.role==='product'&&nameKey(a.name)===nameKey(rule.target));const outcome={id:rule.id,kind:rule.kind,label:rule.label,status:'fail',reason:'',artifact:null,details:null};if(rule.kind==='manual'){const attached=rule.evidence.map(name=>assets.find(a=>a.role==='attachment'&&nameKey(a.name)===nameKey(name))),missing=rule.evidence.filter((_,i)=>!attached[i]);outcome.status=rule.note.trim()&&rule.evidence.length&&!missing.length?'pass':'unknown';outcome.reason=outcome.status==='pass'?'人工说明与指定附件存在，只验提交条件，不认证内容或能力':'人工说明/附件待补，结论未知';outcome.details={note:rule.note,evidence:attached.filter(Boolean).map(a=>({name:a.name,sha256:a.sha256,byteLength:a.byteLength})),missing,explanationMissing:!rule.note.trim(),noAttachmentRequested:!rule.evidence.length};return outcome}if(!product){outcome.reason='产物不在本次用户选定集合，未扫描其他路径';return outcome}outcome.artifact={name:product.name,sha256:product.sha256,byteLength:product.byteLength};if(rule.kind==='exists'){outcome.status='pass';outcome.reason='选定集合中存在该文件，不代表内容合格';return outcome}try{const value=utf8Text(product);if(rule.kind==='json-field'){const object=parseJson(value),present=Object.hasOwn(object,rule.field);outcome.status=present?'pass':'fail';outcome.reason=present?'顶层自有字段存在（null/false/0也算存在），不验值':'缺少指定顶层自有字段';outcome.details={field:rule.field,present,duplicateKeyRule:'JSON.parse后项覆盖；这里只验字段存在，不验值'}}else if(rule.kind==='count'){const count=countCharacters(value),min=bound(rule.min),max=bound(rule.max);outcome.status=count>=min&&count<=max?'pass':'fail';outcome.reason='Unicode码点字数去ECMAScript空白，含标点/emoji；不是分词/写作质量';outcome.details={count,min,max,below:Math.max(0,min-count),above:Math.max(0,count-max)}}else throw Error('未支持规则')}catch(e){outcome.status='error';outcome.reason='该条文本/JSON解析未完成：'+e.message}return outcome}
export async function analyze(raw,rawAssets,{canceled=()=>false,yieldControl=()=>new Promise(r=>setTimeout(r,0))}={}){const d=validateDraft(raw,{forRun:true}),assets=validateAssets(rawAssets),results=[];for(const a of assets){if(canceled())throw Error('验收已取消');await yieldControl();if(canceled())throw Error('验收已取消');if(await hashBytes(fromBase64(a.base64))!==a.sha256)throw Error('文件原字节与SHA-256不符，整份拒绝')}for(const rule of d.rules){if(canceled())throw Error('验收已取消');await yieldControl();if(canceled())throw Error('验收已取消');results.push(evaluate(rule,assets))}const rubricHash=await hashBytes(new TextEncoder().encode(JSON.stringify({rubricVersion:d.rubricVersion,rules:d.rules})));if(canceled())throw Error('验收已取消');const p={feature:'L058',schemaVersion:1,modelVersion:MODEL_VERSION,input:d,rubricHash,files:assets.map(({base64,...a})=>({...a,packagePath:(a.role==='product'?'products/':'attachments/')+a.name})),results,summary:{total:results.length,pass:results.filter(r=>r.status==='pass').length,fail:results.filter(r=>r.status==='fail').length,error:results.filter(r=>r.status==='error').length,unknown:results.filter(r=>r.status==='unknown').length},failedRuleIds:results.filter(r=>r.status==='fail').map(r=>r.id),sourceUnknown:['label','location'].filter(k=>!d.source[k].trim()),definitions:['只验本次用户选定文件集合；文件名按NFC及不区分大小写匹配，不扫描目录或执行脚本。','四类有限条件：存在、顶层JSON自有字段、Unicode码点去空白字数、人工说明与附件提交；不自动认定能力/质量。','每条独立pass/fail/error/unknown，单字段缺失不抹其它通过；JSON解析/UTF8失败只使相关条目error。','人工证据仅验说明与附件存在，缺项unknown，不核真、不认证人工陈述或附件语义。','量规本地修订号与摘要随报告保存，不是可信外部时间线/不可篡改认证；修改输入或文件必须重新验收。','报告副本只含文件元数据，完整验收包另外包含每个产物/附件原字节和JSON/Markdown报告；重载需重新选文件，不恢复原字节。']};reportJson(p);reportMarkdown(p);return p}
export function reportJson(p){const s=JSON.stringify(p,null,2);if(bytes(s)>LIMITS.reportBytes)throw Error('完整JSON超过2MiB，整份拒绝');return s}
export function reportMarkdown(p){const raw=reportJson(p).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),fence='`'.repeat(Math.max(3,...[...raw.matchAll(/`+/g)].map(m=>m[0].length+1)));const s=`# L058 综合作业验收报告\n\n通过${p.summary.pass}、失败${p.summary.fail}、解析错误${p.summary.error}、未知${p.summary.unknown}；只验有限条件，不认定能力。原字节附件在另行导出的完整验收包中。\n\n${fence}json\n${raw}\n${fence}`;if(bytes(s)>LIMITS.reportBytes)throw Error('完整Markdown超过2MiB，整份拒绝');return s}
export async function bundlePayload(p,rawAssets,{canceled=()=>false}={}){const assets=validateAssets(rawAssets);if(assets.length!==p.files.length||assets.some(a=>!p.files.some(f=>f.role===a.role&&f.name===a.name&&f.sha256===a.sha256&&f.byteLength===a.byteLength)))throw Error('报告与当前原文件集合不一致，不能打包');const files=[];for(const a of assets){const data=fromBase64(a.base64);if(await hashBytes(data)!==a.sha256)throw Error('原字节哈希不匹配');if(canceled())throw Error('打包已取消');files.push({path:(a.role==='product'?'products/':'attachments/')+a.name,base64:a.base64,sha256:a.sha256})}for(const[path,content]of[['report.json',reportJson(p)],['report.md',reportMarkdown(p)]]){const data=new TextEncoder().encode(content);files.push({path,base64:toBase64(data),sha256:await hashBytes(data)});if(canceled())throw Error('打包已取消')}return{defaultName:'L058-acceptance-copy',copyOnly:true,files}}
