import{h}from'../../core/ui.js';
import{LIMITS,clone,createGame,generate,stats,press,undo,Clock,completion,source,validateSource,encode,parse,report,markdown,coordinate}from'./model.mjs';
export default{id:'E010',create(root,ctx={}){
 const key='featureLab.E010.progress',clock=new Clock(ctx.now||(()=>performance.now()));let game=createGame(3,'4','fallback'),completed=[],active=false,alive=true,invalid=false,fresh=false,saving=false,reading=false,exporting=false,resave=false,generation=0,interval=null,candidate=null,focusIndex=0,page=0,auditCache=null,auditKey='';
 let message='点击开始，再按灯格；翻转自身及四个正交邻格。',storageText='尚无续玩档。',newSize,confirmReset,confirmImport,confirmInvalid,file,summary,status,storage,startButton;const listeners=[],buttons=[],cells=new Map(),canvases=new Set();
 const random=n=>generate(n,ctx.randomFill||undefined).game;
 try{const v=ctx.config?.get?.(key,null);if(v!=null){({game,completed}=validateSource(v));storageText='完整生成/按键/撤销与首次记录已恢复，保持暂停。';page=Math.max(0,Math.ceil(game.actions.length/50)-1);}else{game=random(3);fresh=true;}}catch(e){invalid=true;message='恢复或随机生成拒绝：'+e.message;storageText='旧档不覆盖，请确认清空或导入。';}clock.restore(game.elapsed);
 const busy=()=>saving||reading||exporting,usable=()=>alive&&active&&!document.hidden&&!busy()&&!invalid,canPlay=()=>usable()&&clock.running&&!stats(game).won&&stats(game).trace<LIMITS.trace;
 const on=(n,t,f)=>{n.addEventListener(t,f);listeners.push([n,t,f]);};function clear(){for(const[n,t,f]of listeners)n.removeEventListener(t,f);listeners.length=0;buttons.length=0;cells.clear();root.replaceChildren();}
 function stop(){if(interval!==null){clearInterval(interval);interval=null;}}function pause(){game.elapsed=clock.pause();stop();}function sync(){game.elapsed=clock.value();}
 function update(){if(!alive)return;const s=stats(game),disabled=!active||document.hidden||busy();summary.textContent=`${game.size}×${game.size} · 亮${s.lit}灯 · 当前${s.presses}按 · 用户日志${s.actions}次 · 生成+用户${s.trace}/10000 · ${(clock.value()/1000).toFixed(1)}秒 · ${s.won?'通关！':clock.running?'计时中':'暂停'} · 首次完成${completed.length}/3`;status.textContent=message;storage.textContent=storageText;newSize.disabled=file.disabled=disabled;confirmReset.disabled=confirmImport.disabled=confirmInvalid.disabled=busy();for(const b of buttons)b.node.disabled=disabled||(invalid&&!['invalidReset','import'].includes(b.kind))||(b.kind==='start'&&(s.won||s.trace>=LIMITS.trace||clock.value()>=LIMITS.elapsed))||(b.kind==='undo'&&(s.won||!game.path.length||s.trace>=LIMITS.trace))||(b.kind==='import'&&!candidate)||(b.kind==='text'&&window.toolbox?.files?.saveTextSupportsCopyOnly!==true)||(b.kind==='png'&&window.toolbox?.files?.saveBinarySupportsCopyOnly!==true);for(const[i,c]of cells)c.disabled=!canPlay();startButton.textContent=clock.running?'暂停计时':'开始 / 继续计时';}
 function audit(){const key=game.size+':'+game.generation+':'+game.actions;if(auditKey!==key||!auditCache){auditKey=key;auditCache=report(game,completed).history;}return auditCache;}
 function render(focus=false){clear();const s=stats(game),n=game.size;newSize=h('select',{'aria-label':'新局灯盘尺寸'});for(const size of[3,4,5])newSize.append(h('option',{value:String(size)},`${size}×${size}`));newSize.value=String(n);confirmReset=h('input',{type:'checkbox','aria-label':'确认放弃当前熄灯局'});confirmImport=h('input',{type:'checkbox','aria-label':'确认替换熄灯全部进度'});confirmInvalid=h('input',{type:'checkbox','aria-label':'确认清空无效熄灯档'});file=h('input',{type:'file',accept:'.json,application/json','aria-label':'熄灯续玩JSON'});on(file,'change',()=>read(file.files?.[0]));
 const grid=h('div',{role:'grid','aria-label':'熄灯棋盘',style:{display:'grid',gridTemplateColumns:`26px repeat(${n},minmax(44px,1fr))`,gap:'7px',padding:'14px',maxWidth:'550px',background:'#233f47',borderRadius:'14px',boxSizing:'border-box'}}),head=h('div',{role:'row',style:{display:'contents'}});head.append(h('span'));for(let x=0;x<n;x++)head.append(h('div',{role:'columnheader',style:{textAlign:'center',color:'#fff7e5'}},'ABCDE'[x]));grid.append(head);
 for(let y=0;y<n;y++){const row=h('div',{role:'row',style:{display:'contents'}});row.append(h('div',{role:'rowheader',style:{alignSelf:'center',textAlign:'center',color:'#fff7e5'}},y+1));for(let x=0;x<n;x++){const i=y*n+x,c=h('button',{type:'button',role:'gridcell','data-index':i,tabindex:i===focusIndex?'0':'-1','aria-label':`${coordinate(i,n)} ${game.board[i]?'亮灯':'已灭'}`,style:{aspectRatio:'1',minWidth:'44px',width:'100%',padding:'0',margin:'0',background:game.board[i]?'#f5c557':'#34515a',color:game.board[i]?'#423321':'#e5eae8',border:'2px solid '+(game.board[i]?'#fce5a0':'#70878d'),borderRadius:'12px',boxShadow:game.board[i]?'inset 0 0 18px #fff4':'none',fontSize:'24px'}},h('span',{'aria-hidden':'true'},game.board[i]?'●':'○'));on(c,'focus',()=>{focusIndex=i;});on(c,'click',()=>choose(i));on(c,'keydown',e=>{if(!canPlay()||e.ctrlKey||e.metaKey||e.altKey)return;const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();const xx=x+delta[0],yy=y+delta[1];if(xx>=0&&xx<n&&yy>=0&&yy<n){focusIndex=yy*n+xx;cells.forEach((v,k)=>v.setAttribute('tabindex',k===focusIndex?'0':'-1'));cells.get(focusIndex)?.focus();}}else if([' ','Enter'].includes(e.key)){e.preventDefault();if(!e.repeat)choose(i);}});cells.set(i,c);row.append(c);}grid.append(row);}
 function button(t,f,kind){const b=h('button',{type:'button'},t);on(b,'click',f);buttons.push({node:b,kind});return b;}
 startButton=button(clock.running?'暂停计时':'开始 / 继续计时',()=>{if(!usable()||s.won)return;if(clock.running){pause();message='已暂停，灯格禁用；继续后再按。';save();}else{clock.start();stop();interval=setInterval(()=>{if(!active||document.hidden||!clock.running){stop();return;}sync();if(game.elapsed>=LIMITS.elapsed){pause();message='七天用时上限，另存后确认新局。';}update();},250);message='计时开始：每次按键翻转自己及四个正交邻格。';update();}},'start');summary=h('p',{'aria-label':'熄灯统计'});status=h('p',{role:'status','aria-label':'操作状态'});storage=h('p',{'aria-label':'熄灯保存状态'});
 const logs=audit(),pages=Math.max(1,Math.ceil(logs.length/50));page=Math.max(0,Math.min(page,pages-1));const table=h('table',{'aria-label':'熄灯操作预览',style:{width:'100%'}}),body=h('tbody');table.append(h('thead',{},h('tr',{},...['操作','类型','格子','亮灯数'].map(v=>h('th',{},v)))));for(const l of logs.slice(page*50,page*50+50))body.append(h('tr',{},...[l.action,l.type==='undo'?'撤销':'按键',l.cell,l.lit].map(v=>h('td',{},v))));table.append(body);
 const progress=h('ul',{'aria-label':'三尺寸首次完成'});for(const size of[3,4,5]){const rec=completed.find(r=>r.size===size);progress.append(h('li',{},`${size}×${size}：${rec?`首次通关 ${(rec.elapsed/1000).toFixed(1)}秒，生成${rec.generation.length}次/用户日志${rec.actions.length}次`:'未通关'}`));}
 const gen=[...game.generation].map(c=>coordinate(parseInt(c,36),n));root.append(h('section',{style:{maxWidth:'860px',padding:'18px',margin:'0 auto',lineHeight:'1.6'}},h('h2',{},'熄灯谜题'),h('p',{},'3×3、4×4、5×5。按一格只翻转自己及四个正交邻格；边界不绕行、不含对角。所有灯灭才通关，通关冻结，每种尺寸只记首次。初始谜题来自全灭状态的记录随机按键，保证有解；生成逆序是已知解例，未声称最短或唯一解。'),h('p',{},'鼠标按格；键盘方向键移动焦点，空格/Enter按格（长按重复不连按）。暂停时不能改变灯格。新局/重开需要勾确认。'),h('div',{},startButton,button('撤销最近一次按键',()=>{if(!usable())return;try{if(undo(game)){pause();message='已撤销最近按键，用时不倒退；保持暂停。';page=Math.max(0,Math.ceil(game.actions.length/50)-1);save(true);}}catch(e){message=e.message;update();}},'undo')),summary,grid,
 h('details',{'aria-label':'熄灯生成解例'},h('summary',{},'查看生成记录与初始局解例'),h('p',{},`${game.method==='fallback'?'4次随机尝试抵消为全灭，已使用确定中心单按fallback':'crypto独立随机位选取按键（升序记录）'}。生成：${gen.join(' → ')}。初始局解例：${[...gen].reverse().join(' → ')}。`),h('p',{},'逆序只适用于本局初始棋盘；已经按过时先勾确认重开当前谜题，再使用这条解例。按到全灭就停止，即使解例有剩余后缀（可能互相抵消）。它不是当前棋盘的自动求解提示，也不证明最短。')),
 h('div',{},h('label',{},'新局尺寸 ',newSize),h('label',{},confirmReset,' 确认放弃当前局'),button('确认生成所选尺寸新局',()=>reset(true),'reset'),button('确认重开当前谜题',()=>reset(false),'reset')),storage,invalid?h('div',{},h('label',{},confirmInvalid,' 确认清空无效熄灯档'),button('从空熄灯进度开始',()=>{if(!confirmInvalid.checked){message='先勾确认，旧档未覆盖。';update();return;}try{const next=random(3);pause();invalid=false;game=next;completed=[];clock.restore(0);page=focusIndex=0;save();}catch(e){message=e.message;update();}},'invalidReset')):null,
 h('h3',{},'完整续玩与副本'),h('p',{},'当前及每种尺寸首次记录分别保留完整生成+按键/撤销源迹≤10000次；总源档64KiB，超限拒绝不截断。当前有效按数可因撤销减少，完整日志保留撤销；累计主动用时≤七天。离开/隐藏/销毁暂停，返回/重载不自启。预览50行一页，导出全部。'),h('div',{},button('重试本地保存',()=>save(),'retry'),button('另存熄灯JSON新副本',()=>exportText('json'),'text'),button('另存完整熄灯Markdown',()=>exportText('md'),'text'),button('另存完整熄灯PNG',exportPNG,'png')),file,h('p',{'aria-label':'熄灯导入预览'},candidate?`已校验 ${candidate.game.size}×${candidate.game.size} · 亮${stats(candidate.game).lit} · 用户日志${candidate.game.actions.length}次 · 首次${candidate.completed.length}/3；尚未替换。`:'选择≤64KiB schema1 JSON，重放生成与每次按键/撤销。'),h('label',{},confirmImport,' 确认替换熄灯全部进度'),button('应用熄灯续玩',()=>{if(!alive||!active||document.hidden||busy()||!candidate)return;if(!confirmImport.checked){message='先勾确认替换。';update();return;}pause();({game,completed}=candidate);candidate=null;invalid=false;clock.restore(game.elapsed);focusIndex=0;page=Math.max(0,Math.ceil(game.actions.length/50)-1);message='完整恢复，保持暂停。';save();},'import'),status,progress,h('h3',{},`全部用户操作 ${page+1}/${pages}页 · ${logs.length}行`),h('div',{},button('上一页操作',()=>{page=Math.max(0,page-1);render();},'page'),button('下一页操作',()=>{page=Math.min(pages-1,page+1);render();},'page')),table));update();if(focus&&active&&clock.running)cells.get(focusIndex)?.focus();
 }
 function reset(newPuzzle){if(!usable())return;if(!confirmReset.checked){message='先勾确认放弃，当前局未改变。';update();return;}try{const next=newPuzzle?random(Number(newSize.value)):createGame(game.size,game.generation,game.method);pause();generation++;game=next;clock.restore(0);candidate=null;focusIndex=page=0;message='已建立新局，保持暂停；首次完成保留。';save();}catch(e){message='新局拒绝：'+e.message;update();}}
 function choose(i){if(!canPlay())return;try{focusIndex=i;press(game,i);sync();candidate=null;page=Math.max(0,Math.ceil(game.actions.length/50)-1);if(stats(game).won){pause();if(!completed.some(r=>r.size===game.size))completed.push(completion(game));message='通关！全部灯灭；每种尺寸首次记录仅一次，本局冻结。';}else message=`按${coordinate(i,game.size)}，亮${stats(game).lit}灯。`;save(true);}catch(e){message=e.message;update();}}
 async function save(focus=false){if(!alive||saving)return;sync();const value=source(game,completed);saving=true;storageText='正在保存完整源迹…';render(focus);try{if(typeof ctx.config?.set!=='function')throw Error('本地配置接口不可用');await ctx.config.set(key,value);if(alive)storageText='已保存，重载恢复且保持暂停。';}catch(e){if(alive)storageText='保存失败：'+e.message+'；当前临时保留，可另存或重试。';}finally{saving=false;if(alive){update();if(focus&&active&&clock.running)cells.get(focusIndex)?.focus();if(resave){resave=false;save();}}}}
 async function read(f){if(!f||!active||busy())return;pause();const token=++generation;reading=true;candidate=null;update();try{if(f.size>LIMITS.bytes)throw Error('JSON最多64KiB。');const bytes=await f.arrayBuffer();if(!alive||token!==generation)return;if(bytes.byteLength>LIMITS.bytes)throw Error('实际JSON超过64KiB。');candidate=parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));message='完整重放验证通过，尚未替换。';}catch(e){if(alive&&token===generation)message='导入拒绝：'+e.message;}finally{if(alive&&token===generation){reading=false;render();}}}
 const response=r=>r?.ok===true?'已另存完整新副本。':r?.canceled?'已取消另存。':`另存失败：${r?.error||'未确认成功'}${r?.partialPath?'；请人工核对 '+r.partialPath:''}`;
 async function exportText(ext){if(!usable())return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message='需要文本copyOnly基础接口。';update();return;}pause();const token=generation;exporting=true;render();try{await save();if(!alive||token!==generation)return;const result=await files.saveText({copyOnly:true,extension:ext,defaultName:`lights-${game.size}-${stats(game).won?'complete':'draft'}-copy.${ext}`,content:ext==='json'?encode(source(game,completed)):markdown(report(game,completed))});if(alive&&token===generation)message=response(result);}catch(e){if(alive&&token===generation)message='另存失败：'+e.message;}finally{if(alive&&token===generation){exporting=false;update();}}}
 async function exportPNG(){if(!usable())return;const files=window.toolbox?.files;if(files?.saveBinarySupportsCopyOnly!==true){message='需要二进制copyOnly基础接口。';update();return;}pause();const token=generation;exporting=true;render();const canvas=document.createElement('canvas');canvases.add(canvas);try{await save();if(!alive||token!==generation)return;drawPNG(canvas,game);const blob=await new Promise((r,j)=>canvas.toBlob(v=>v?r(v):j(Error('PNG编码失败。')),'image/png'));if(!alive||token!==generation)return;if(blob.size>LIMITS.pngBytes)throw Error('PNG超过10MiB。');const bytes=new Uint8Array(await blob.arrayBuffer()),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));if(!alive||token!==generation)return;let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await files.saveBinary({copyOnly:true,defaultName:`lights-${game.size}-${stats(game).won?'complete':'draft'}-copy.png`,base64:btoa(binary),sha256:[...hash].map(v=>v.toString(16).padStart(2,'0')).join('')});if(alive&&token===generation)message=response(result);}catch(e){if(alive&&token===generation)message='PNG另存失败：'+e.message;}finally{canvas.width=canvas.height=0;canvases.delete(canvas);if(alive&&token===generation){exporting=false;update();}}}
 function suspend(text){pause();generation++;reading=exporting=false;candidate=null;message=text;if(!invalid&&!saving)save();else{if(saving&&!invalid)resave=true;update();}}
 const visibility=()=>{if(document.hidden)suspend('页面隐藏，计时停止；返回需明确继续。');else update();};document.addEventListener('visibilitychange',visibility);render();return{activate(){if(alive){active=true;if(fresh&&!invalid){fresh=false;save();}else update();}},deactivate(){if(alive){active=false;suspend('已离开，计时冻结；返回不会自启。');}},destroy(){if(!alive)return;pause();const value=invalid?null:source(game,completed);alive=false;active=false;generation++;stop();if(value&&typeof ctx.config?.set==='function')Promise.resolve(ctx.config.set(key,value)).catch(()=>{});document.removeEventListener('visibilitychange',visibility);for(const c of canvases)c.width=c.height=0;canvases.clear();clear();game=completed=candidate=auditCache=null;}};
}};
export function drawPNG(canvas,g){canvas.width=820;canvas.height=820;const c=canvas.getContext('2d');if(!c)throw Error('Canvas不可用。');const n=g.size,s=stats(g),step=560/n;c.fillStyle='#fff8e8';c.fillRect(0,0,820,820);c.fillStyle='#233f47';c.font='bold 26px sans-serif';c.fillText('熄灯谜题 · '+n+'×'+n,26,38);c.font='17px sans-serif';c.fillText(`亮${s.lit}灯 · 当前${s.presses}按 · 用户日志${s.actions}次 · ${(g.elapsed/1000).toFixed(1)}秒 · ${s.won?'通关':'未通关（导出暂停）'}`,26,72);c.textAlign='center';for(let i=0;i<n;i++){c.fillText('ABCDE'[i],120+(i+.5)*step,114);c.fillText(String(i+1),88,134+(i+.5)*step+6);}for(let i=0;i<n*n;i++){const x=120+i%n*step,y=134+Math.floor(i/n)*step;c.fillStyle=g.board[i]?'#f5c557':'#34515a';c.fillRect(x+3,y+3,step-6,step-6);c.strokeStyle=g.board[i]?'#db9f36':'#70878d';c.lineWidth=2;c.strokeRect(x+4,y+4,step-8,step-8);}c.textAlign='left';c.fillStyle='#233f47';c.font='16px sans-serif';c.fillText('仅翻转自身及四正交邻格，边界不绕行；全部灯灭才通关。',26,750);c.fillText('生成记录提供初始局解例，不声称最短；每种尺寸只记首次。',26,780);c.fillText('完整生成、按键、撤销与首次记录请另存JSON或Markdown。',26,808);}
