export const LIMITS=Object.freeze({bytes:65536,trace:10000,elapsed:604800000,pngBytes:10485760});
export const clone=v=>JSON.parse(JSON.stringify(v)),coordinate=(i,n)=>'ABCDE'[i%n]+(Math.floor(i/n)+1);
function size(n){if(![3,4,5].includes(n))throw Error('尺寸仅3、4或5。');}
export function neighbors(n,i){size(n);if(!Number.isInteger(i)||i<0||i>=n*n)throw Error('格子索引无效。');const x=i%n,y=Math.floor(i/n),out=[i];if(y>0)out.push(i-n);if(x+1<n)out.push(i+1);if(y+1<n)out.push(i+n);if(x>0)out.push(i-1);return out;}
export function flip(board,n,i){if(!Array.isArray(board)||board.length!==n*n||board.some(v=>v!==0&&v!==1))throw Error('灯格必须完整0/1。');for(const k of neighbors(n,i))board[k]^=1;return board;}
const char=i=>i.toString(36),index=c=>parseInt(c,36);
export function createGame(n,generation,method='crypto'){size(n);if(!['crypto','fallback'].includes(method)||typeof generation!=='string'||!generation.length||generation.length>n*n||![...generation].every((c,i)=>/^[0-9a-o]$/.test(c)&&index(c)<n*n&&(i===0||index(c)>index(generation[i-1]))))throw Error('生成序列须尺寸内、升序唯一的规范base36格子。');if(method==='fallback'&&generation!==char(Math.floor(n/2)*(n+1)))throw Error('fallback须确定中心单按。');const board=Array(n*n).fill(0);for(const c of generation)flip(board,n,index(c));if(!board.includes(1))throw Error('初始棋盘不得全灭。');return{size:n,generation,method,board,path:[],actions:'',elapsed:0};}
export function generate(n,fill=b=>crypto.getRandomValues(b)){size(n);for(let tries=1;tries<=4;tries++){const bytes=new Uint8Array(n*n);fill(bytes);let generation='';for(let i=0;i<bytes.length;i++)if(bytes[i]&1)generation+=char(i);if(generation){try{return{game:createGame(n,generation),attempts:tries};}catch(e){if(!/全灭/.test(e.message))throw e;}}}return{game:createGame(n,char(Math.floor(n/2)*(n+1)),'fallback'),attempts:4};}
export function stats(g){const lit=g.board.reduce((s,v)=>s+v,0);return{lit,presses:g.path.length,actions:g.actions.length,trace:g.generation.length+g.actions.length,won:lit===0};}
export function press(g,i){neighbors(g.size,i);if(stats(g).won)throw Error('已通关，确认新局才可继续。');if(stats(g).trace>=LIMITS.trace)throw Error('源轨迹已达10000次，未截断；另存后确认新局。');flip(g.board,g.size,i);g.path.push(i);g.actions+=char(i);return stats(g);}
export function undo(g){if(stats(g).won||!g.path.length)return false;if(stats(g).trace>=LIMITS.trace)throw Error('源轨迹已达10000次，另存后确认新局。');flip(g.board,g.size,g.path.pop());g.actions+='-';return true;}
export class Clock{constructor(now=()=>performance.now()){this.now=now;this.elapsed=0;this.base=0;this.running=false;}restore(ms){if(!Number.isInteger(ms)||ms<0||ms>LIMITS.elapsed)throw Error('用时须0至七天整数毫秒。');this.elapsed=ms;this.running=false;}start(){if(!this.running){this.base=this.now();this.running=true;}}value(){return Math.min(LIMITS.elapsed,this.elapsed+(this.running?Math.max(0,Math.floor(this.now()-this.base)):0));}pause(){this.elapsed=this.value();this.running=false;return this.elapsed;}}
const exact=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join(',')!==[...keys].sort().join(','))throw Error('字段不完整或未知。');};
export function replay(n,generation,method,actions){const g=createGame(n,generation,method);if(typeof actions!=='string'||generation.length+actions.length>LIMITS.trace)throw Error('生成加用户源轨迹最多10000次。');for(const c of actions){if(c==='-'){if(!undo(g))throw Error('无有效按键可撤销，或通关后撤销。');}else{if(!/^[0-9a-o]$/.test(c))throw Error('源按键编码无效。');press(g,index(c));}}return g;}
export function completion(g){if(!stats(g).won)throw Error('尚未通关。');return{size:g.size,generation:g.generation,method:g.method,actions:g.actions,elapsed:g.elapsed};}
export function source(g,completed=[]){const v={schema:1,current:{size:g.size,generation:g.generation,method:g.method,actions:g.actions,elapsed:g.elapsed},completed:clone(completed)};validateSource(v);return v;}
export function validateSource(v){if(new TextEncoder().encode(JSON.stringify(v)).length>LIMITS.bytes)throw Error('存档超过64KiB，未截断。');exact(v,['schema','current','completed']);if(v.schema!==1)throw Error('仅支持schema1。');exact(v.current,['size','generation','method','actions','elapsed']);const g=replay(v.current.size,v.current.generation,v.current.method,v.current.actions),clock=new Clock(()=>0);clock.restore(v.current.elapsed);g.elapsed=v.current.elapsed;if(!Array.isArray(v.completed)||v.completed.length>3)throw Error('仅3种尺寸的首次记录。');const completed=v.completed.map(r=>{exact(r,['size','generation','method','actions','elapsed']);clock.restore(r.elapsed);if(!stats(replay(r.size,r.generation,r.method,r.actions)).won)throw Error('完成记录重放未全灭。');return clone(r);});if(new Set(completed.map(r=>r.size)).size!==completed.length)throw Error('同尺寸首次通关不可重复。');if(stats(g).won&&!completed.some(r=>r.size===g.size))throw Error('当前全灭却缺首次记录。');return{game:g,completed};}
export function encode(v){validateSource(v);return JSON.stringify(v,null,2);}
// Standalone bounded parser, same strict integer/duplicate-key policy as E009, no runtime feature dependency.
export function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>LIMITS.bytes)throw Error('JSON最多64KiB。');let p=0;const ws=()=>{while(p<text.length&&/[ \t\r\n]/.test(text[p]))p++;};function string(){const start=p++;while(p<text.length){if(text[p]==='\\'){p+=2;continue;}if(text[p++]==='"')return JSON.parse(text.slice(start,p));}throw Error('字符串未闭合。');}function value(depth=0){if(depth>8)throw Error('JSON层级超限。');ws();if(text[p]==='"')return string();if(text[p]==='{'||text[p]==='['){const obj=text[p++]==='{',out=obj?Object.create(null):[],seen=new Set();ws();if(text[p]===(obj?'}':']')){p++;return out;}while(true){ws();let key;if(obj){if(text[p]!=='"')throw Error('键无效。');key=string();if(seen.has(key))throw Error('重复JSON键。');seen.add(key);ws();if(text[p++]!==':')throw Error('缺冒号。');}const v=value(depth+1);if(obj)out[key]=v;else out.push(v);ws();const c=text[p++];if(c===(obj?'}':']'))return out;if(c!==',')throw Error('JSON结构无效。');}}const t=text.slice(p).match(/^(?:null|true|false|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/)?.[0];if(!t)throw Error('JSON值无效。');p+=t.length;if(/^-?\d/.test(t)){if(!/^-?(?:0|[1-9]\d*)$/.test(t)||!Number.isSafeInteger(Number(t)))throw Error('只接受安全整数词法。');return Number(t);}return JSON.parse(t);}const v=value();ws();if(p!==text.length)throw Error('JSON尾部无效。');return validateSource(v);}
export function report(g,completed){const sim=createGame(g.size,g.generation,g.method),history=[];for(let i=0;i<g.actions.length;i++){const c=g.actions[i];if(c==='-'){const target=sim.path.at(-1);undo(sim);history.push({action:i+1,type:'undo',cell:coordinate(target,g.size),lit:stats(sim).lit});}else{press(sim,index(c));history.push({action:i+1,type:'press',cell:coordinate(index(c),g.size),lit:stats(sim).lit});}}return{feature:'E010',source:source(g,completed),...stats(g),board:[...g.board],generation:[...g.generation].map(c=>coordinate(index(c),g.size)),inverse:[...g.generation].reverse().map(c=>coordinate(index(c),g.size)),history,elapsed:g.elapsed,rules:{toggle:'自身及四正交邻格；边界不绕行',win:'全部灯灭',inverse:'仅初始局的已知解例；非最短解主张',first:'每种尺寸只记首次，共3'}};}
export function markdown(r){return '# 熄灯谜题\n\n'+`${r.source.current.size}×${r.source.current.size} · 亮${r.lit} · 当前${r.presses}按 · 用户日志${r.actions}次 · 生成+用户${r.trace}/10000 · ${(r.elapsed/1000).toFixed(1)}秒 · ${r.won?'已通关':'未通关（导出暂停）'}\n\n`+'生成按键：'+r.generation.join(' → ')+'\n\n初始局已知解例（逆生成，仅从初始局使用）：'+r.inverse.join(' → ')+'\n\n## 全部用户操作\n\n|操作|类型|格子|亮灯数|\n|---:|---|---|---:|\n'+r.history.map(h=>`|${h.action}|${h.type}|${h.cell}|${h.lit}|`).join('\n')+'\n\n## 完整棋盘（1亮0灭）\n\n```\n'+Array.from({length:r.source.current.size},(_,y)=>r.board.slice(y*r.source.current.size,(y+1)*r.source.current.size).join(' ')).join('\n')+'\n```\n\n首次记录：'+r.source.completed.map(c=>`${c.size}×${c.size}`).join('、')+'\n\n## 完整源存档\n\n```json\n'+encode(r.source)+'\n```\n';}
