import {h} from '../../core/ui.js';
import {createSession,report,markdown} from './model.mjs';
const names={confirmed:'主动确认已观察',skipped:'已跳过',unobserved:'未观察'};
export default{id:'E039',create(root,ctx={}){
  const clock=typeof ctx.clock==='function'?ctx.clock:()=>performance.now();let session=createSession(clock),active=false,alive=true,timer=null,saving=false,generation=0,displayedIndex=0,message='可以先读提示，再主动开始建议计时；不计时也能确认或跳过。';
  const listeners=[],buttons=[];let title,prompt,alternative,number,counter,summary,rows,status,confirm,ending;
  function on(n,t,f){n.addEventListener(t,f);listeners.push([n,t,f]);}
  function stop(){if(timer!==null)clearInterval(timer);timer=null;}
  function draw(){if(!alive)return;const s=session.snapshot(),ended=s.phase==='ended',row=s.steps[s.index??4];displayedIndex=s.index;if(s.timerState!=='running')stop();number.textContent=ended?'○':String(s.index+1);title.textContent=ended?'这次观察到这里就好':`${s.index+1}/5 · ${row.title}`;prompt.textContent=ended?'可以回到手头的事情，也可以再停留一会儿。每一步是否确认，都由你决定。':row.prompt;alternative.textContent=ended?'未确认的步骤不会算完成；记录只包含选择和计时，没有感官内容。':row.alternative;
    counter.textContent=ended?`本次观察已结束 · 建议计时已运行 ${(s.timedMs/1000).toFixed(1)}秒。`:s.timerState==='expired'?'建议的3分钟已到；可以继续、跳过或结束，步骤没有自动确认。':`建议计时剩余 ${Math.ceil(s.suggestedUnspentMs/1000)} 秒 · ${s.timerState==='running'?'计时中':s.timerState==='paused'?'已暂停，需要主动继续':s.timerState==='ready'?'尚未开始': '已停止'}`;
    summary.textContent=`主动确认 ${s.counts.confirmed}/5 · 跳过 ${s.counts.skipped}/5 · 未观察 ${s.counts.unobserved}/5；建议计时已运行 ${(s.timedMs/1000).toFixed(1)}秒。`;
    ending.textContent=ended?'本次已结束；无需把所有步骤都做完。':'固定顺序：颜色 → 表面 → 声音 → 轮廓 → 空间。每步建议36秒，按自己节奏确认或跳过。';
    rows.replaceChildren(...s.steps.map((r,i)=>h('tr',{},h('td',{},`${i+1}. ${r.title}`),h('td',{},names[r.status]),h('td',{},`${(r.timedMs/1000).toFixed(1)}秒`))));
    const enabled=active&&!document.hidden&&!saving;for(const b of buttons)b.node.disabled=!enabled||(b.kind==='start'&&(ended||['running','expired'].includes(s.timerState)))||(b.kind==='pause'&&s.timerState!=='running')||(['decide','finish'].includes(b.kind)&&ended)||(b.kind==='export'&&window.toolbox?.files?.saveTextSupportsCopyOnly!==true);confirm.disabled=saving;status.textContent=message;
  }
  function schedule(){stop();if(alive&&active&&!document.hidden&&session.snapshot().timerState==='running')timer=setInterval(()=>{try{draw();}catch(e){stop();status.textContent=e.message;}},200);}
  function pause(reason='manual'){session.pause(reason);stop();message=reason==='manual'?'计时暂停；观察选择仍由你决定。':'计时已停止；返回或保存后不会自动继续。';draw();}
  function decide(value){if(!active||saving||!alive||document.hidden)return;const result=session.decide(value,displayedIndex);message=result.reason;draw();schedule();}
  async function save(format){if(!active||saving||!alive||document.hidden)return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message='需要支持新副本的公共文件接口。';draw();return;}pause('export');const token=generation,value=report(session.snapshot());saving=true;message='另存期间计时停止，观察状态不会自动改变。';draw();try{const response=await files.saveText({copyOnly:true,content:format==='json'?JSON.stringify(value,null,2):markdown(value),extension:format,defaultName:`sensory-observation-record-copy.${format}`});if(!alive||token!==generation)return;message=response?.ok===true?'已保存新副本；需要时主动继续。':response?.canceled?'已取消另存，观察状态保持。':`保存失败：${response?.error||'未确认成功'}${response?.partialPath?'；请人工核对 '+response.partialPath:''}`;}catch(e){if(alive&&token===generation)message='保存失败：'+e.message;}finally{if(alive&&token===generation){saving=false;draw();}}}
  function button(text,fn,kind){const n=h('button',{type:'button'},text);on(n,'click',fn);buttons.push({node:n,kind});return n;}
  number=h('div',{'aria-label':'当前观察序号',style:{fontSize:'52px',color:'#7E8E75',fontWeight:'600'}});title=h('h3',{'aria-label':'当前观察提示'});prompt=h('p',{'aria-label':'观察说明',style:{fontSize:'20px',lineHeight:'1.9'}});alternative=h('p',{'aria-label':'可跳过说明',style:{lineHeight:'1.8'}});counter=h('p',{'aria-label':'建议倒计时',style:{fontVariantNumeric:'tabular-nums',fontSize:'18px'}});summary=h('p',{'aria-label':'观察选择统计'});ending=h('p',{'aria-label':'流程结束状态'});rows=h('tbody');status=h('p',{'aria-label':'操作状态',role:'status'});confirm=h('input',{type:'checkbox','aria-label':'确认替换当前观察记录'});
  root.append(h('section',{style:{maxWidth:'900px',margin:'0 auto',padding:'20px'}},h('h2',{},'感官观察'),h('p',{},'把注意力放到身边的一件小事。无需输入文字，也不会打开摄像头或麦克风。'),h('div',{style:{padding:'20px 28px',background:'#F3F0E7',borderRadius:'14px'}},number,title,prompt,alternative),ending,counter,h('div',{},button('开始 / 继续建议计时',()=>{if(!active||saving||!alive||document.hidden)return;session.resume();message='计时仅作建议；到期也不会自动标记观察完成。';draw();schedule();},'start'),button('暂停建议计时',()=>pause(),'pause')),h('div',{},button('确认这一步已观察',()=>decide('confirmed'),'decide'),button('跳过这一步（不算完成）',()=>decide('skipped'),'decide'),button('现在结束（其余保留未观察）',()=>{if(!active||saving||!alive||document.hidden)return;session.finish();stop();message='本次已结束，所有选择保留，未观察仍不算完成。';draw();},'finish')),summary,h('table',{style:{width:'100%',textAlign:'left'}},h('thead',{},h('tr',{},h('th',{},'五步顺序'),h('th',{},'用户选择'),h('th',{},'本步建议计时累计'))),rows),h('p',{},'确认只代表你的主动选择，没有感官活动核验。跳过和未观察都不算完成，不需要调整呼吸。'),h('div',{},button('保存完整JSON记录副本',()=>save('json'),'export'),button('保存完整Markdown记录副本',()=>save('md'),'export')),h('label',{},confirm,' 确认替换当前记录（请先主动另存）'),h('div',{},button('重新开始五步观察',()=>{if(!active||saving||!alive||document.hidden)return;const s=session.snapshot();if((s.timedMs>0||s.counts.confirmed+s.counts.skipped>0||s.phase==='ended')&&!confirm.checked){message='请先勾选确认；重新开始会替换当前记录。';draw();return;}stop();session=createSession(clock);generation++;confirm.checked=false;message='新观察已准备，建议计时尚未开始。';draw();},'reset')),status,h('p',{},'全程离线、不录音录像、不保存观察内容。离开或隐藏会暂停；销毁或重新打开不恢复临时记录。')));
  const hidden=()=>{if(document.hidden){generation++;saving=false;pause('hidden');}else draw();};document.addEventListener('visibilitychange',hidden);draw();
  return{activate(){if(alive){active=true;draw();}},deactivate(){if(!alive)return;active=false;generation++;saving=false;pause('left');},destroy(){if(!alive)return;session.pause('left');active=false;alive=false;generation++;stop();for(const[n,t,f]of listeners)n.removeEventListener(t,f);listeners.length=0;document.removeEventListener('visibilitychange',hidden);session=null;root.replaceChildren();}};
}};
