'use strict';
const path=require('node:path'),fs=require('node:fs/promises'),cp=require('node:child_process'),net=require('node:net'),{pathToFileURL}=require('node:url');const model=import(pathToFileURL(path.join(__dirname,'model.mjs')).href);
function createHost({platform=process.platform,environment=process.env,fileSystem=fs,spawn=cp.spawn}={}){const states=new Map();let running=0;
 function state(id){if(!Number.isSafeInteger(id)||id<1)throw Error('窗口无效。');if(!states.has(id)){if(states.size>=32)throw Error('窗口数量已满。');states.set(id,{job:null,seen:new Set()});}return states.get(id);}
 function stop(job,reason){if(!job.reason)job.reason=reason;if(job.child){job.terminationRequested=true;try{job.child.kill('SIGKILL');}catch{}}}
 async function query(job,m,port){if(running>=4)throw Error('当前系统查询数量已满。');const systemRoot=Object.keys(environment).find(k=>k.toUpperCase()==='SYSTEMROOT'),base=environment[systemRoot];if(typeof base!=='string'||! /^[A-Za-z]:[\\/]/.test(base)||base.startsWith('\\\\'))throw Error('本应用继承的Windows系统目录不可用。');const binary=path.win32.join(base,'System32','WindowsPowerShell','v1.0','powershell.exe'),resolved=await fileSystem.realpath(binary);if(job.reason)return{reason:job.reason};const st=await fileSystem.stat(resolved);if(!st.isFile()||! /^[A-Za-z]:[\\/]/.test(resolved))throw Error('系统只读查询程序不可用。');if(job.reason)return{reason:job.reason};if(running>=4)throw Error('当前系统查询数量已满。');running++;
 return new Promise(resolve=>{let child,bytes=0,errBytes=0,chunks=[],done=false,started=false,timer;const finish=(code,signal)=>{if(done)return;done=true;clearTimeout(timer);running--;job.child=null;job.terminationObserved=started;let observation=null,problem=null;if(!job.reason&&code===0){try{let text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(Buffer.concat(chunks));if(text.startsWith('\ufeff'))text=text.slice(1);const raw=JSON.parse(text);if(Array.isArray(raw.rows)&&raw.rows.some(r=>!net.isIP(String(r.address).split('%')[0])))throw Error('bad address');observation=m.observation(raw,port);}catch{problem='invalid_system_output';}}else if(!job.reason)problem=started?'system_query_failed':'system_query_unavailable';chunks=[];resolve({reason:job.reason,observation,problem,utility:resolved,terminationRequested:job.terminationRequested===true,terminationObserved:job.terminationObserved===true,exitCode:Number.isInteger(code)?code:null,signal:typeof signal==='string'?signal:null});};try{child=spawn(resolved,['-NoLogo','-NoProfile','-NonInteractive','-EncodedCommand',Buffer.from(m.script(port),'utf16le').toString('base64')],{shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...environment}});job.child=child;started=true;timer=setTimeout(()=>stop(job,'timeout'),m.LIMITS.queryMs);child.stdout.on('data',chunk=>{bytes+=chunk.length;if(bytes>m.LIMITS.stdoutBytes){chunks=[];stop(job,'stdout_limit');}else if(!job.reason)chunks.push(Buffer.from(chunk));});child.stderr.on('data',chunk=>{errBytes+=chunk.length;if(errBytes>m.LIMITS.stderrBytes)stop(job,'stderr_limit');});child.once('error',()=>{if(!job.reason)job.reason='spawn_error';});child.once('close',finish);if(job.reason)stop(job,job.reason);}catch{finish(null,null);}});
 }
 return{async invoke(op,p,{senderId}={}){let s,job;try{s=state(senderId);if(s.job)throw Error('本窗口仍在等待系统查询结束。');if(op!=='inspect'||!p||typeof p!=='object'||Object.keys(p).sort().join('|')!=='input|jobId'||typeof p.jobId!=='string'||!/^[-A-Za-z0-9_]{12,64}$/.test(p.jobId)||s.seen.has(p.jobId)||s.seen.size>=128)throw Error('只接受唯一有限端口查询任务。');job={id:p.jobId,reason:null,child:null};s.job=job;s.seen.add(job.id);const began=new Date().toISOString(),m=await model,plan=m.input(p.input);let observed=null,result=null;if(platform==='win32'&&!job.reason&&states.get(senderId)===s){result=await query(job,m,plan.port);observed=result.observation??null;}const report={format:'T074-port-owner-report',version:1,jobId:job.id,port:plan.port,platform,startedAtUTC:began,completedAtUTC:new Date().toISOString(),status:job.reason||result?.problem||(platform!=='win32'?'not_supported':observed?'observed':'not_run'),protocols:observed?.protocols??[{protocol:'TCP',status:'not_observed',count:null},{protocol:'UDP',status:'not_observed',count:null}],rows:observed?.rows??[],systemObservation:observed?{startedAtUTC:observed.startedAtUTC,completedAtUTC:observed.completedAtUTC}:null,query:result?{utility:result.utility??null,terminationRequested:result.terminationRequested??false,terminationObserved:result.terminationObserved??false,exitCode:result.exitCode??null,signal:result.signal??null}:null,scope:'Windows只读Get-NetTCPConnection Listen / Get-NetUDPEndpoint，按单一端口过滤，再查各PID的Win32_Process Name/ExecutablePath/CreationDate。不读取命令行/凭据、不连接该端口、不扫描远端、不提权、不停止拥有端口的进程或改系统配置。查询不是原子快照，PID可能退出/复用；监听不证明服务正常/远端可达，无观察项不保证可绑定。其它平台未实现，明确不支持。12秒为拥有查询子进程的取消期限，只有观察close后释放槽，不保证OS立即终止。系统程序路径取本应用继承SystemRoot并规范化，不经PATH搜索。'};m.reportText(report,'json');m.reportText(report,'md');return{ok:true,report};}catch{return{ok:false,error:'只读端口查询失败；输入/系统程序/容量条件未通过，不回显内部异常。'};}finally{if(s&&s.job===job)s.job=null;}},cancel(jobId,{senderId}={}){const s=states.get(senderId);if(!s?.job||s.job.id!==jobId)return{ok:true,canceled:false};stop(s.job,'canceled');return{ok:true,canceled:true};},disposeSender(id){const s=states.get(id);if(s?.job)stop(s.job,'canceled');states.delete(id);}};
}
module.exports={...createHost(),createHost};
