import{parseSubtitles as parseRaw}from'./subtitles.mjs';
export function parseSubtitles(text,format){if(typeof text!=='string'||new TextEncoder().encode(text).length>32768)throw Error('字幕UTF-8最多32KiB。');const p=parseRaw(text,format);if(p.cues.length>24)throw Error('最多24条字幕。');return p;}
export{versionBanner,parseProbe,probeArgs,actualTimestamp,pngInfo}from'./media.mjs';
export const LIMITS=Object.freeze({sourceBytes:64*1024*1024,subtitleBytes:32768,outputBytes:20*1024*1024,cues:24,points:300,lines:4,durationMs:60000,frameBytes:1048576});
const fail=s=>{throw Error(s);};
export function settings(v={schemaVersion:1,font:'NotoSansCJKsc-Regular',fontSize:28,margin:32,position:'bottom'}){if(!v||v.schemaVersion!==1||Object.keys(v).some(k=>!['schemaVersion','font','fontSize','margin','position'].includes(k))||v.font!=='NotoSansCJKsc-Regular'||!Number.isInteger(v.fontSize)||v.fontSize<16||v.fontSize>64||!Number.isInteger(v.margin)||v.margin<16||v.margin>96||!['top','middle','bottom'].includes(v.position)||new TextEncoder().encode(JSON.stringify(v)).length>65536)fail('字号16–64、安全边距16–96、上/中/下位置及schemaVersion1无效。仅固定可信Noto字体。');return{...v};}
export function wrap(text,width,measure){if(typeof text!=='string'||!text.trim()||[...text].length>LIMITS.points||/\p{Surrogate}|[\p{Mark}\p{Format}]|[\u0000-\u0009\u000b-\u001f\u007f]/u.test(text))fail('每条正文1–300码点；仅无组合/控制/双向格式字符的纯文本，允许换行。');const lines=[];for(const paragraph of text.split('\n')){let current='';for(const point of paragraph){if(measure(point)>width)fail('单个字形超出安全区，请减字号或边距。');if(current&&measure(current+point)>width){const split=current.lastIndexOf(' ');if(split>=0&&split<current.length-1){lines.push(current.slice(0,split+1));current=current.slice(split+1);}else{lines.push(current);current='';}if(current&&measure(current+point)>width){lines.push(current);current='';}}current+=point;}lines.push(current);}if(lines.length>LIMITS.lines)fail('换行超过4行，整条拒绝；减小字号/边距或人工修订来源副本。');return lines;}
export function layout(cues,media,config,measure){const s=settings(config),{width,height}=media.video;if(!Array.isArray(cues)||!cues.length||cues.length>24||width>1280||height>720||width<160||height<120||width%2||height%2||media.durationMs>60000)fail('仅偶数160×120至1280×720，60秒、1–24条字幕。');const safe={left:s.margin,top:s.margin,right:width-s.margin,bottom:height-s.margin},padding=8,budget=width-2*s.margin-2*padding;if(budget<16)fail('安全区过窄。');let lastEnd=0;const rows=cues.map(c=>{if(c.start<lastEnd||c.end>media.durationMs||c.end-c.start<100)fail('字幕须原顺序不重叠、每条≥100ms且不越视频时长；不裁剪或隐藏重叠。');lastEnd=c.end;const lines=wrap(c.text,budget,measure),step=Math.ceil(s.fontSize*1.5)+8,blockHeight=lines.length*step;if(blockHeight>height-2*s.margin-2*padding)fail('字幕块超过安全区高度；整份拒绝。');const y0=s.position==='top'?safe.top+padding:s.position==='bottom'?safe.bottom-padding-blockHeight:Math.floor((height-blockHeight)/2);return{...c,lines:lines.map((text,i)=>({text,advancePixels:measure(text),y:y0+i*step,heightBudget:step,name:`cue-${String(c.id).padStart(3,'0')}-line-${String(i+1).padStart(2,'0')}.txt`})),block:{top:y0,bottom:y0+blockHeight,widthBudget:budget,lineStep:step},sampleRequestedMs:Math.floor((c.start+c.end)/2)};});const samples=[...rows].sort((a,b)=>b.lines.length-a.lines.length||[...b.text].length-[...a.text].length||a.id-b.id).slice(0,3).map((r,i)=>({id:r.id,requestedMs:r.sampleRequestedMs,name:`sample-${String(i+1).padStart(2,'0')}.png`,afterName:`after-${String(i+1).padStart(2,'0')}.png`}));return{schemaVersion:1,feature:'T047',settings:s,safe,padding,sourceMedia:structuredClone(media),cues:rows,samples,notes:['纯文本逐字形保守换行，优先空格边界；长单词可按码点拆行。','原字幕保留；换行由输出报告记录，不修改原文本。','时间使用源PTS，启用区间start≤t<end；样帧为请求之后第一帧，必须仍在该字幕内。','安全区预算不是自动完整可见证明：必须查看实际渲染样帧。']};}
export function encoderSupport(s){if(typeof s!=='string'||s.length>131072||!/^\s*V[^\s]{5}\s+libx264\s/m.test(s)||!/^\s*V[^\s]{5}\s+png\s/m.test(s)||!/^\s*A[^\s]{5}\s+aac\s/m.test(s))fail('需要libx264/png/aac编码器。');return['libx264','png','aac'];}
export function drawGraph(plan){return plan.cues.flatMap(c=>c.lines.filter(l=>l.text.length).map(l=>`drawtext=fontfile=font.otf:textfile=${l.name}:expansion=none:text_shaping=0:fontsize=${plan.settings.fontSize}:fontcolor=white:borderw=2:bordercolor=black:x=(w-text_w)/2:y=${l.y}:enable='gte(t,${(c.start/1000).toFixed(3)})*lt(t,${(c.end/1000).toFixed(3)})'`)).join(',');}
function input(source){return['-hide_banner','-loglevel','info','-nostdin','-n','-threads','2','-filter_threads','1','-protocol_whitelist','file','-f','mov','-enable_drefs','0','-use_absolute_path','0','-noautorotate','-copyts','-i',source];}
export function frameArgs(plan,request,source,output,after=false){return[...input(source),'-map','0:v:0','-an','-sn','-dn','-vf',`${after?'':drawGraph(plan)+','}select=gte(t\\,${(request.requestedMs/1000).toFixed(3)}),showinfo,format=rgb24`,'-frames:v','1','-fps_mode','passthrough','-c:v','png','-threads','1','-map_metadata','-1','-update','1','-fs',String(LIMITS.frameBytes),'-f','image2',output];}
export function burnArgs(plan,source,output){return[...input(source),'-vf',drawGraph(plan),'-map','0:v:0',...(plan.sourceMedia.audio?['-map','0:a:0','-c:a','aac','-b:a','96k','-ar','48000','-ac',String(plan.sourceMedia.audio.channels)]:['-an']),'-sn','-dn','-c:v','libx264','-preset','veryfast','-crf','20','-maxrate','1500k','-bufsize','3000k','-pix_fmt','yuv420p','-r','30','-threads','2','-map_metadata','-1','-map_chapters','-1','-movflags','+faststart','-fs',String(LIMITS.outputBytes),'-f','mp4',output];}
export function verifyOutput(plan,actual,bytes){const src=plan.sourceMedia;if(!Number.isInteger(bytes)||bytes<1||bytes>=LIMITS.outputBytes||Math.abs(actual.durationMs-src.durationMs)>100||actual.video.width!==src.video.width||actual.video.height!==src.video.height||actual.video.fps!==30||!!actual.audio!==!!src.audio||actual.audio&&(actual.audio.channels!==src.audio.channels||actual.audio.sampleRate!==48000))fail('输出时长/尺寸/帧率/音轨或20MiB完整容量核验失败。');return{actual,differenceMs:actual.durationMs-src.durationMs,bytes};}
export function markdown(r){const escape=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\|/g,'\\|');return`# 字幕排版与烧录\n\n视频：${escape(r.video.name)} SHA ${r.video.sha256}\n\n字幕：${escape(r.subtitle.name)} SHA ${r.subtitle.sha256}\n\n固定字体：${r.font.name} SHA ${r.font.sha256}\n\n字号${r.plan.settings.fontSize}、位置${r.plan.settings.position}、安全边距${r.plan.settings.margin}。样帧确认是人工声明。\n\n`+r.plan.cues.map(c=>`## 字幕${c.id} ${c.start}–${c.end}ms\n\n原文：\n\n${escape(c.text)}\n\n排版：\n\n${c.lines.map(l=>escape(l.text)).join('\n\n')}\n\n`).join('')+'\n完整来源/时间/布局/样帧SHA/输出SHA与原字幕全文见JSON报告及original-subtitles副本。\n';}
