export const LIMITS=Object.freeze({timeoutMs:3000,enumeratedEntries:100,labelBytes:512});
function abort(signal){if(signal?.aborted)throw Object.assign(Error('已取消，未生成权限报告。'),{name:'AbortError'});}
async function bounded(operation,signal,ms){abort(signal);let timer,handler;try{return await Promise.race([Promise.resolve().then(()=>{abort(signal);return operation();}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(Error('公开接口等待超时。'),{name:'TimeoutError'})),ms);handler=()=>reject(Object.assign(Error('已取消，未生成权限报告。'),{name:'AbortError'}));signal?.addEventListener('abort',handler,{once:true});})]);}finally{clearTimeout(timer);if(handler)signal?.removeEventListener('abort',handler);}}
export async function queryBrowserPermission(type,{navigator:nav=globalThis.navigator,signal,timeoutMs=3000}={}){
 if(!['camera','microphone'].includes(type))throw Error('设备类型无效。');if(typeof nav?.permissions?.query!=='function')return{state:'unknown',reason:'permissions_query_unavailable',source:'navigator.permissions.query'};
 try{const result=await bounded(()=>nav.permissions.query({name:type}),signal,timeoutMs);abort(signal);return['granted','denied','prompt'].includes(result?.state)?{state:result.state,reason:null,source:'navigator.permissions.query'}:{state:'unknown',reason:'unsupported_return_state',source:'navigator.permissions.query'};}catch(e){if(e.name==='AbortError')throw e;return{state:'unknown',reason:e.name==='TimeoutError'?'query_timeout':'query_unsupported_or_failed',source:'navigator.permissions.query'};}
}
export async function enumerateVisible(type,{navigator:nav=globalThis.navigator,document:doc=globalThis.document,includeLabels=false,signal,timeoutMs=3000}={}){
 if(!['camera','microphone'].includes(type))throw Error('设备类型无效。');const source='navigator.mediaDevices.enumerateDevices';if(doc?.visibilityState!==undefined&&doc.visibilityState!=='visible')return{state:'unknown',reason:'document_not_visible',source,entries:[]};if(typeof nav?.mediaDevices?.enumerateDevices!=='function')return{state:'unknown',reason:'enumerate_devices_unavailable',source,entries:[]};
 try{const devices=await bounded(()=>nav.mediaDevices.enumerateDevices(),signal,timeoutMs);abort(signal);if(!Array.isArray(devices)||devices.length>100)throw Error('设备返回格式/数量超限。');const kind=type==='camera'?'videoinput':'audioinput',entries=[];for(const d of devices){if(!['videoinput','audioinput','audiooutput'].includes(d?.kind))throw Error('设备kind未知。');if(d.kind!==kind)continue;const label=typeof d.label==='string'?d.label:'';if(new TextEncoder().encode(label).length>512||/[\x00-\x1f\x7f]/u.test(label)||[...label].some(c=>{const n=c.codePointAt(0);return n>=0xd800&&n<=0xdfff;}))throw Error('设备label容量/字符无效。');entries.push({ordinal:entries.length+1,kind,labelAvailable:label.length>0,...includeLabels&&label?{label}:{}});}return{state:'observed',reason:null,source,entries,totalReturnedEntries:devices.length,matchingReturnedEntries:entries.length,labelDisclosure:includeLabels?'explicit_labels_if_available':'labels_omitted',deviceIdentifiersOmitted:true,scope:'仅浏览器当前可枚举条目，可能被权限/策略过滤；default/communications等别名可能是同一物理设备，不按条目数推断硬件数。零条目不证明无设备，标签空不证明拒绝，未测设备占用。'};
 }catch(e){if(e.name==='AbortError')throw e;return{state:'unknown',reason:e.name==='TimeoutError'?'enumeration_timeout':'enumeration_failed_or_invalid_result',source,entries:[]};}
}
export async function inspectMedia({deviceType='camera',includeLabels=false},hooks={}){
 if(!['camera','microphone'].includes(deviceType)||typeof includeLabels!=='boolean')throw Error('设备类型/标签披露选项无效。');abort(hooks.signal);let system;
 try{system=await bounded(()=>hooks.readSystem(deviceType),hooks.signal,hooks.timeoutMs??3000);abort(hooks.signal);if(system?.ok!==true||system.deviceType!==deviceType||!['not-determined','granted','denied','restricted','unknown'].includes(system.systemPermission?.state))throw Error('系统状态无效。');}catch(e){if(e.name==='AbortError')throw e;system={platform:'unknown',deviceType,systemPermission:{state:'unknown',reason:e.name==='TimeoutError'?'host_timeout':'host_unavailable_or_invalid_result',source:'Electron getMediaAccessStatus'},settings:{path:'系统平台未知；请查看当前系统媒体隐私设置。',uri:null,opened:false}};}
 const browserPermission=await queryBrowserPermission(deviceType,hooks),enumeration=await enumerateVisible(deviceType,{...hooks,includeLabels});abort(hooks.signal);
 const observations=[];if(['denied','restricted'].includes(system.systemPermission.state))observations.push('system_api_reports_blocked');if(browserPermission.state==='denied')observations.push('browser_query_reports_denied_may_include_policy');if(browserPermission.state==='prompt')observations.push('browser_query_reports_prompt_no_request_was_made');if(enumeration.state==='observed'&&enumeration.entries.length===0)observations.push('no_entries_visible_not_proof_of_absent_hardware');if(enumeration.entries?.length&&enumeration.entries.every(e=>!e.labelAvailable))observations.push('all_visible_labels_unavailable_not_proof_of_denial');
 return{feature:'T079',version:1,deviceType,includeLabels,platform:system.platform,systemPermission:system.systemPermission,settings:system.settings,browserPermission,enumeration,observations,captureStarted:false,permissionRequested:false,deviceBusy:'unknown_not_tested',deviceUsable:'unknown_not_tested',scope:'三种来源分别保留，不合并为许可/可用总判定。只读公开状态和可枚举设备；不调用getUserMedia/getDisplayMedia/askForMediaAccess、不启动音视频流、不打开系统设置、不改变权限。不支持/失败/超时保留unknown，不能据此猜测拒绝。没有验证设备占用、实际采集、图像或声音质量。'};
}
