export const LIMITS=Object.freeze({bytes:65536,undo:100,pngBytes:10485760});
export const TOOLS=Object.freeze(['pencil','eraser','fill','picker']),MIRRORS=Object.freeze(['none','horizontal','vertical','both']);
export const clone=v=>JSON.parse(JSON.stringify(v));
const validColor=c=>c===null||typeof c==='string'&&/^#[0-9a-f]{6}$/.test(c);
export function color(c){if(typeof c!=='string'||!/^#[0-9a-fA-F]{6}$/.test(c))throw Error('颜色须#RRGGBB，透明由橡皮表示。');return c.toLowerCase();}
function size(n){if(n!==16&&n!==32)throw Error('画布仅16×16或32×32。');}
function point(g,x,y){if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=g.size||y>=g.size)throw Error('坐标须画布内整数。');}
export function createProject(n=16){size(n);return{size:n,pixels:Array(n*n).fill(null),tool:'pencil',ink:'#e4583f',mirror:'none',history:[]};}
export function mirrored(g,x,y){point(g,x,y);if(!MIRRORS.includes(g.mirror))throw Error('镜像设置无效。');const xs=['horizontal','both'].includes(g.mirror)?[x,g.size-1-x]:[x],ys=['vertical','both'].includes(g.mirror)?[y,g.size-1-y]:[y];return[...new Set(ys.flatMap(yy=>xs.map(xx=>yy*g.size+xx)))];}
export function begin(g){return{project:g,before:new Map(),open:true};}
function write(g,tx,indices,value){if(!tx?.open||tx.project!==g)throw Error('笔画事务已结束或不属于画布。');if(!validColor(value))throw Error('像素色无效。');for(const i of indices){if(!Number.isInteger(i)||i<0||i>=g.pixels.length)throw Error('像素位置无效。');if(g.pixels[i]!==value){if(!tx.before.has(i))tx.before.set(i,g.pixels[i]);g.pixels[i]=value;}}}
export function dot(g,tx,x,y,value=g.tool==='eraser'?null:g.ink){write(g,tx,mirrored(g,x,y),value);}
// Integer Bresenham connects sampled pointer cells, inclusive endpoints, bounded <=32 iterations.
export function line(g,tx,x0,y0,x1,y1,value=g.tool==='eraser'?null:g.ink){point(g,x0,y0);point(g,x1,y1);const dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1;let err=dx+dy;while(true){dot(g,tx,x0,y0,value);if(x0===x1&&y0===y1)break;const e=2*err;if(e>=dy){err+=dy;x0+=sx;}if(e<=dx){err+=dx;y0+=sy;}}}
export function fill(g,tx,x,y,value=g.ink){point(g,x,y);const original=[...g.pixels],target=original[y*g.size+x],stack=[y*g.size+x],seen=new Set(),region=[];while(stack.length){const i=stack.pop();if(seen.has(i))continue;seen.add(i);if(original[i]!==target)continue;region.push(i);const xx=i%g.size,yy=Math.floor(i/g.size);if(xx>0)stack.push(i-1);if(xx+1<g.size)stack.push(i+1);if(yy>0)stack.push(i-g.size);if(yy+1<g.size)stack.push(i+g.size);}const indices=new Set(region.flatMap(i=>mirrored(g,i%g.size,Math.floor(i/g.size))));write(g,tx,indices,value);return{region:region.length,targets:indices.size};}
export function commit(g,tx){if(!tx?.open||tx.project!==g)throw Error('事务无效。');const changes=[...tx.before].filter(([i,v])=>g.pixels[i]!==v);tx.open=false;tx.before.clear();if(!changes.length)return{changed:0,dropped:0};g.history.push(changes);const dropped=g.history.length>LIMITS.undo?g.history.shift().length:0;return{changed:changes.length,dropped};}
export function rollback(g,tx){if(!tx?.open||tx.project!==g)return false;for(const[i,v]of tx.before)g.pixels[i]=v;tx.open=false;tx.before.clear();return true;}
export function undo(g){const changes=g.history.pop();if(!changes)return false;for(const[i,v]of changes)g.pixels[i]=v;return true;}
export function count(g){return g.pixels.filter(c=>c!==null).length;}
export function rgba(g){const out=new Uint8ClampedArray(g.pixels.length*4);for(let i=0;i<g.pixels.length;i++){const c=g.pixels[i];if(c!==null){out[i*4]=parseInt(c.slice(1,3),16);out[i*4+1]=parseInt(c.slice(3,5),16);out[i*4+2]=parseInt(c.slice(5,7),16);out[i*4+3]=255;}}return out;}
const exact=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join(',')!==[...keys].sort().join(','))throw Error('工程字段不完整或未知。');};
export function source(g){const v={schema:1,size:g.size,pixels:[...g.pixels],tool:g.tool,ink:g.ink,mirror:g.mirror};restore(v);return v;}
export function restore(v){if(new TextEncoder().encode(JSON.stringify(v)).length>LIMITS.bytes)throw Error('工程超过64KiB，未截断。');exact(v,['schema','size','pixels','tool','ink','mirror']);if(v.schema!==1)throw Error('仅支持schema1。');size(v.size);if(!Array.isArray(v.pixels)||v.pixels.length!==v.size*v.size||Array.from(v.pixels).some(c=>!validColor(c)))throw Error('每格必须完整规范小写#RRGGBB或null透明。');if(!TOOLS.includes(v.tool)||!MIRRORS.includes(v.mirror)||v.ink===null||!validColor(v.ink))throw Error('工具、颜色或镜像无效。');return{size:v.size,pixels:[...v.pixels],tool:v.tool,ink:v.ink,mirror:v.mirror,history:[]};}
export function encode(v){restore(v);return JSON.stringify(v,null,2);}
// Own bounded strict parser, matching E010 duplicate-key/integer policy without runtime feature dependency.
export function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>LIMITS.bytes)throw Error('JSON最多64KiB。');let p=0;const ws=()=>{while(p<text.length&&/[ \t\r\n]/.test(text[p]))p++;};function string(){const start=p++;while(p<text.length){if(text[p]==='\\'){p+=2;continue;}if(text[p++]==='"')return JSON.parse(text.slice(start,p));}throw Error('字符串未闭合。');}function value(depth=0){if(depth>8)throw Error('JSON层级超限。');ws();if(text[p]==='"')return string();if(text[p]==='{'||text[p]==='['){const obj=text[p++]==='{',out=obj?Object.create(null):[],seen=new Set();ws();if(text[p]===(obj?'}':']')){p++;return out;}while(true){ws();let key;if(obj){if(text[p]!=='"')throw Error('键无效。');key=string();if(seen.has(key))throw Error('重复JSON键。');seen.add(key);ws();if(text[p++]!==':')throw Error('缺冒号。');}const v=value(depth+1);if(obj)out[key]=v;else out.push(v);ws();const c=text[p++];if(c===(obj?'}':']'))return out;if(c!==',')throw Error('JSON结构无效。');}}const t=text.slice(p).match(/^(?:null|true|false|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/)?.[0];if(!t)throw Error('JSON值无效。');p+=t.length;if(/^-?\d/.test(t)){if(!/^-?(?:0|[1-9]\d*)$/.test(t)||!Number.isSafeInteger(Number(t)))throw Error('只接受安全整数词法。');return Number(t);}return JSON.parse(t);}const v=value();ws();if(p!==text.length)throw Error('JSON尾部无效。');return restore(v);}
export function markdown(g){return '# 像素画工程\n\n'+`${g.size}×${g.size} · 已画${count(g)} / ${g.size*g.size}格。颜色#RRGGBB完全不透明，null完全透明；PNG原尺寸无插值。\n\n会话撤销最近100笔/填充，工程仅保存当前像素和工具设置，恢复撤销栈为空。\n\n`+'|x（0起）|y（0起）|颜色或透明|\n|---:|---:|---|\n'+g.pixels.map((c,i)=>`|${i%g.size}|${Math.floor(i/g.size)}|${c||'transparent'}|`).join('\n')+'\n\n## 完整源工程\n\n```json\n'+encode(source(g))+'\n```\n';}
