import { h } from '../../core/ui.js';
import { KINDS, LIMITS, newScene, addStone, moveStone, frame, geometry, supportInfo, moving, archive, restore, sceneSVG, pngBlob, pngPayload } from './model.mjs';
export default {id:'E035',create(root){
  let state=newScene(),selected=null,alive=true,active=true,raf=null,lastTime=null,accumulator=0,drag=null,busy=false,nativePending=false,generation=0,message='',draft='',kind=0,confirmReset=false,svg=null,summary=null;
  const undo=[],bindings=[],urls=new Set(),host=h('div',{'aria-label':'完整石堆景观',tabIndex:0,style:{maxWidth:'800px',width:'100%',touchAction:'none',outline:'none'}});
  const modeText={falling:'缓慢下落',resting:'堆叠支撑',grounded:'已落地',tipping:'失衡倾倒'};
  function cancelFrame(){if(raf!==null)cancelAnimationFrame(raf);raf=null;lastTime=null;accumulator=0;}
  function remember(){undo.push(archive(state));if(undo.length>20)undo.shift();}
  function release(){if(!drag)return;const id=drag.pointerId;drag=null;try{if(host.hasPointerCapture?.(id))host.releasePointerCapture(id);}catch{}}
  function freeze(text=''){state.frozen=true;cancelFrame();release();if(text)message=text;}
  function paint(){const source=sceneSVG(state,selected);if(!svg){host.innerHTML=source;svg=host.querySelector('svg');if(svg){svg.style.width='100%';svg.style.height='auto';svg.style.display='block';}}else svg.innerHTML=source.slice(source.indexOf('>')+1,source.lastIndexOf('</svg>'));if(summary)summary.textContent=`${state.frozen?'已冻结（坐标不推进）':'准静态下落中'} · ${state.stones.length}/20块 · ${state.stones.filter(p=>p.mode==='resting'||p.mode==='grounded').length}块有支撑 · ${state.stones.filter(p=>p.mode==='tipping').length}块倾倒`;}
  function schedule(){if(alive&&active&&!busy&&!document.hidden&&!state.frozen&&moving(state)&&raf===null)raf=requestAnimationFrame(draw);}
  function draw(t){raf=null;if(!alive||!active||busy||document.hidden||state.frozen)return;if(!drag&&lastTime!==null){const result=frame(state,Math.max(0,t-lastTime),accumulator);state=result.state;accumulator=result.accumulator;if(result.events.length){const e=result.events.at(-1);message=`石块${e.id}失衡：合成重心${e.loadX.toFixed(2)}超出支撑[${e.segment.map(n=>n.toFixed(2)).join(', ')}]，进入有限步倾倒。`;render();}}lastTime=t;paint();schedule();}
  function on(node,type,fn){const guarded=async event=>{if(!alive||!active||busy)return;try{await fn(event);}catch(error){message=error.message||'操作失败';render();}};node.addEventListener(type,guarded);bindings.push([node,type,guarded]);return node;}
  const button=(text,fn,disabled=false)=>on(h('button',{type:'button',class:'btn',disabled},text),'click',fn);
  function select(label,choices,value,fn){const node=h('select',{'aria-label':label},...choices.map(([v,text])=>h('option',{value:String(v)},text)));node.value=String(value);on(node,'change',()=>fn(node.value));return h('label',{},label+' ',node);}
  function number(label,value,min,max){const node=h('input',{type:'number','aria-label':label,value,min,max,step:.1,disabled:state.frozen});return h('label',{},label+' ',node);}
  function scrub(){for(const[node,type,fn]of bindings.splice(0))node.removeEventListener(type,fn);root.replaceChildren();}
  function check(token){if(!alive||!active||document.hidden||token!==generation)throw new DOMException('已取消本地生成','AbortError');}
  function report(result){message=result?.canceled===true?'已取消另存':result?.ok===true?`已保存新副本：${result.path||''}`:`保存失败：${result?.error||'未返回成功结果'}${result?.partialPath?'；请人工核对：'+result.partialPath:''}`;}
  async function save(type){const files=window.toolbox?.files,name=type==='json'?'saveText':'saveBinary';if(files?.[name+'SupportsCopyOnly']!==true||typeof files[name]!=='function')throw Error('缺少安全副本接口');freeze('保存已冻结坐标；保存后需明确继续。');busy=true;nativePending=false;const token=++generation;paint();render();let image,url;try{let payload;if(type==='json')payload={content:archive(state),extension:'json',defaultName:'balance-stones-archive-copy.json',copyOnly:true};else{url=URL.createObjectURL(new Blob([sceneSVG(state,selected,true)],{type:'image/svg+xml'}));urls.add(url);image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('石堆SVG解码失败'));image.src=url;});check(token);const canvas=document.createElement('canvas');canvas.width=800;canvas.height=600;const context=canvas.getContext('2d');if(!context)throw Error('Canvas 2D不可用');context.drawImage(image,0,0,800,600);payload=await pngPayload(await pngBlob(canvas));check(token);}nativePending=true;render();const result=await files[name](payload);check(token);report(result);}catch(error){if(alive&&active)message=error.name==='AbortError'?'已取消本地生成，未提交结果已忽略':`保存失败：${error.message}`;}finally{if(image){image.onload=image.onerror=null;image.src='';}if(url){URL.revokeObjectURL(url);urls.delete(url);}busy=nativePending=false;if(alive&&active)render();}}
  async function readFile(file){if(!file)return;if(file.size>65536)throw Error('存档限64KiB');freeze();busy=true;const token=++generation;render();try{const buffer=await file.arrayBuffer();check(token);if(buffer.byteLength!==file.size)throw Error('文件大小发生变化');const text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);restore(text);draft=text;message='存档已校验放入草稿，点击恢复才替换。';}catch(error){if(alive&&active)message=error.name==='AbortError'?'已取消读取':`读取失败：${error.message}`;}finally{busy=false;if(alive&&active)render();}}
  function render(){if(!alive)return;scrub();root.append(h('h2',{},'平衡石头'),h('p',{},'二维准静态小游戏，不是通用刚体物理。石块均匀密度，橙点为面积重心；支撑面以石块水平投影包围区间近似，金线为接触重叠段，小竖线为含上方石块的合成重心投影。重心在含端点区间内稳定，超出则倾倒。无随机晃动、计时、排行或关卡。'));
    if(!active){root.append(h('p',{},'已离开并冻结；返回不自动下落。'));return;}if(message)root.append(h('p',{role:'status'},message));summary=h('p',{'aria-label':'石堆状态'});root.append(summary,h('div',{},select('石块种类',KINDS.map((k,i)=>[i,k.name]),kind,value=>{kind=Number(value);}),button('加入所选石块（中央上方）',()=>{remember();state=addStone(state,kind,400,75,0);selected=state.stones.at(-1).id;message='已加入石块；冻结时保持位置，继续后缓慢下落。';render();schedule();},state.stones.length>=20),button(state.frozen?'继续下落 / 启用摆放':'冻结坐标与下落',()=>{if(state.frozen){state.frozen=false;message='可拖放、数值编辑或用键盘移动。';render();schedule();}else{freeze('已冻结；不能拖放或旋转，需明确继续。');render();}}),button('撤销上次摆放（保持冻结）',()=>{if(!undo.length)throw Error('没有可撤销的摆放');freeze();state=restore(undo.pop());state.frozen=true;if(!state.stones.some(p=>p.id===selected))selected=state.stones.at(-1)?.id??null;message='已还原操作前实际坐标并冻结；动画过程不逐帧入撤销栈。';render();},!undo.length)),host);
    if(state.stones.length){root.append(select('选择石块',state.stones.map(p=>[p.id,`${p.id} ${KINDS[p.kind].name}（${modeText[p.mode]}）`]),selected??state.stones[0].id,value=>{selected=Number(value);render();}));const p=state.stones.find(p=>p.id===selected);if(p){root.append(h('div',{},number('石块X',p.x,80,720),number('石块Y',p.y,-200,800),number('石块角度',p.angle,-180,180),button('应用位置 / 角度',()=>{const value=label=>{const raw=root.querySelector(`[aria-label="${label}"]`).value;if(!raw.trim())throw Error(label+'不能为空');return Number(raw);};const next=moveStone(state,p.id,value('石块X'),value('石块Y'),value('石块角度'));remember();state=next;message='位置或角度已改变重心/水平支撑范围；上方依赖重新下落。';render();schedule();},state.frozen)));const g=geometry(p);root.append(h('p',{},`选中${p.id}：${modeText[p.mode]}，面积重心(${g.cx.toFixed(2)},${g.cy.toFixed(2)})。${p.mode==='resting'?` 支撑${p.supportId}；合成重心${supportInfo(state,p).loadX.toFixed(2)}；依赖${supportInfo(state,p).dependents}块。`:''}`));}}
    root.append(h('p',{},'拖放只在继续状态启用：点击石块并拖动，使用SVG坐标和Pointer Capture。也可先选择石块，用数值框；景观获焦点时方向键每次移动8单位，R旋转15°。场地X限制80–720，Y限制-200–800，角度-180–180；X坐标限幅；Y可处于画外，用数值找回。预览固定800×600，PNG会缩放容纳全部石块（含画外位置）。'),h('p',{},'最多20块；撤销最近20次加入/拖放/数值修改/恢复/重置，撤销后冻结。倾倒块和其上方依赖按有限步直接落到地面，可能互相重叠，不模拟摩擦、弹性或连续多体碰撞；正常下降遇到稳定石块水平顶面会接触并判定支撑。'));
    const input=h('textarea',{'aria-label':'场景JSON草稿',rows:5,maxLength:65536,style:{width:'100%'}});input.value=draft;on(input,'input',()=>{if(input.value.length>65536||new TextEncoder().encode(input.value).length>65536)throw Error('草稿限64KiB UTF-8');draft=input.value;});const file=h('input',{type:'file',accept:'.json,application/json','aria-label':'导入石堆存档'});on(file,'change',()=>readFile(file.files?.[0]));root.append(h('h3',{},'存档schema1（恢复保持冻结）'),input,file,button('恢复草稿（替换并冻结）',()=>{const candidate=restore(draft);remember();freeze();state=candidate;state.frozen=true;selected=state.stones.at(-1)?.id??null;message='已恢复实际几何和下落/支撑状态，保持冻结；明确继续才推进。';render();}),button('当前场景放入草稿',()=>{draft=archive(state);message='场景已放入草稿，尚未写磁盘。';render();}));const files=window.toolbox?.files;root.append(button('保存场景JSON副本（冻结）',()=>save('json'),files?.saveTextSupportsCopyOnly!==true||typeof files?.saveText!=='function'),button('保存完整石堆PNG副本（冻结）',()=>save('png'),files?.saveBinarySupportsCopyOnly!==true||typeof files?.saveBinary!=='function'));
    const confirm=h('input',{type:'checkbox','aria-label':'确认清空石堆',checked:confirmReset});on(confirm,'change',()=>{confirmReset=confirm.checked;});root.append(h('label',{},confirm,'确认清空当前未保存石堆'),button('建立空场景',()=>{if(!confirmReset)throw Error('请先确认清空；建议先另存旧场景');remember();freeze();state=newScene();selected=null;confirmReset=false;message='已建立空场景，保持冻结。';render();}));paint();
    if(busy){const cancel=h('button',{type:'button',disabled:nativePending},'取消本地生成/读取'),fn=()=>{generation++;message='已请求取消，忽略未提交的结果。';render();};cancel.addEventListener('click',fn);bindings.push([cancel,'click',fn]);root.append(cancel,h('p',{},nativePending?'原生另存处理中，请在对话框取消。':'正在读取/生成本地文件。'));for(const node of root.querySelectorAll('button,input,select,textarea'))if(node!==cancel)node.disabled=true;}
  }
  function point(event){if(!svg)throw Error('SVG景观不可用');const matrix=svg.getScreenCTM();if(!matrix)throw Error('景观坐标矩阵不可用');const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const result=p.matrixTransform(matrix.inverse());return{x:result.x,y:result.y};}
  const down=event=>{if(!alive||!active||busy||state.frozen||event.button!==0)return;const group=event.target.closest?.('g[data-stone]'),id=Number(group?.getAttribute('data-stone')),p=state.stones.find(s=>s.id===id);if(!p)return;try{const start=point(event);remember();selected=id;drag={pointerId:event.pointerId,x:p.x,y:p.y,start,angle:p.angle};host.setPointerCapture(event.pointerId);host.focus();event.preventDefault();paint();}catch(error){release();message=error.message;render();}};
  const move=event=>{if(!drag||event.pointerId!==drag.pointerId||state.frozen||!alive||!active)return;try{const at=point(event),x=Math.max(80,Math.min(720,drag.x+at.x-drag.start.x)),y=Math.max(-200,Math.min(800,drag.y+at.y-drag.start.y));state=moveStone(state,selected,x,y,drag.angle);paint();event.preventDefault();}catch(error){release();freeze(error.message);render();}};
  const up=event=>{if(!drag||event.pointerId!==drag.pointerId)return;release();lastTime=null;accumulator=0;render();host.focus();schedule();};
  const key=event=>{if(!alive||!active||busy||state.frozen||drag)return;const p=state.stones.find(s=>s.id===selected);if(!p||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','r','R'].includes(event.key))return;event.preventDefault();remember();const x=Math.max(80,Math.min(720,p.x+({'ArrowLeft':-8,'ArrowRight':8}[event.key]||0))),y=Math.max(-200,Math.min(800,p.y+({'ArrowUp':-8,'ArrowDown':8}[event.key]||0))),angle=event.key.toLowerCase()==='r'?(p.angle+15>180?p.angle-345:p.angle+15):p.angle;state=moveStone(state,p.id,x,y,angle);render();host.focus();schedule();};
  for(const[type,fn]of[['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['lostpointercapture',up],['keydown',key]])host.addEventListener(type,fn);
  const visibility=()=>{if(!alive||!document.hidden)return;generation++;freeze('页面隐藏已冻结，返回需明确继续。');if(active)render();};document.addEventListener('visibilitychange',visibility);render();
  return{activate(){if(!alive)return;active=true;render();},deactivate(){if(!alive)return;active=false;generation++;freeze();render();},destroy(){if(!alive)return;freeze();alive=false;active=false;generation++;scrub();for(const[type,fn]of[['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['lostpointercapture',up],['keydown',key]])host.removeEventListener(type,fn);document.removeEventListener('visibilitychange',visibility);for(const url of urls)URL.revokeObjectURL(url);urls.clear();host.innerHTML='';state=null;draft='';undo.length=0;svg=summary=null;}};
}};
