export const LIMITS=Object.freeze({stones:20,undo:20,archiveBytes:65536,width:800,height:600,ground:540,maxFrameSteps:4,stepMs:1000/60,pngBytes:10*1024*1024});
export const KINDS=Object.freeze(Array.from({length:10},(_,i)=>Object.freeze({name:['扁青石','圆灰石','长砂石','高岩石','小卵石','斜纹石','宽河石','细页岩','暖砾石','厚玄石'][i],width:[112,88,126,74,66,102,130,116,82,98][i],height:[44,62,42,88,40,64,46,34,58,76][i],color:['#7c9993','#939c99','#b5a58a','#80928b','#a9b5a3','#899b9b','#92a99d','#a0aaa0','#b2a092','#778d8c'][i]})));
const clone=s=>JSON.parse(JSON.stringify(s)),finite=(n,a,b)=>typeof n==='number'&&Number.isFinite(n)&&n>=a&&n<=b;
function exact(s,keys){if(!s||typeof s!=='object'||Array.isArray(s)||Object.keys(s).sort().join('|')!==keys.slice().sort().join('|'))throw Error('存档字段/结构不符');}
export function shape(kind){if(!Number.isInteger(kind)||kind<0||kind>=10)throw Error('石块种类无效');const{width:w,height:h}=KINDS[kind],shift=(kind%3-1)*.08;return[[-w*.5,0],[-w*.48,-h*.67],[-w*(.18+shift),-h],[w*(.32+shift),-h*.91],[w*.5,-h*.31],[w*.42,0]];}
export function polygonMass(points){let cross=0,cx=0,cy=0;for(let i=0;i<points.length;i++){const p=points[i],q=points[(i+1)%points.length],k=p[0]*q[1]-q[0]*p[1];cross+=k;cx+=(p[0]+q[0])*k;cy+=(p[1]+q[1])*k;}if(!Number.isFinite(cross)||Math.abs(cross)<1e-9)throw Error('石块面积无效');return{mass:Math.abs(cross)/2,x:cx/(3*cross),y:cy/(3*cross)};}
export function geometry(stone){const points=shape(stone.kind),a=stone.angle*Math.PI/180,c=Math.cos(a),s=Math.sin(a),convert=([x,y])=>[stone.x+x*c-y*s,stone.y+x*s+y*c],world=points.map(convert),m=polygonMass(points),center=convert([m.x,m.y]);return{points:world,mass:m.mass,cx:center[0],cy:center[1],left:Math.min(...world.map(p=>p[0])),right:Math.max(...world.map(p=>p[0])),top:Math.min(...world.map(p=>p[1])),bottom:Math.max(...world.map(p=>p[1]))};}
export function balance(x,segment){if(!Number.isFinite(x)||!Array.isArray(segment)||segment.length!==2||!segment.every(Number.isFinite)||segment[0]>segment[1])throw Error('重心/支撑区间无效');return x>=segment[0]&&x<=segment[1];}
export function newScene(){return{schema:1,frozen:true,nextId:1,stones:[]};}
export function validate(s){exact(s,['schema','frozen','nextId','stones']);if(s.schema!==1)throw Error('只接受存档schema1');if(typeof s.frozen!=='boolean'||!Number.isInteger(s.nextId)||s.nextId<1||s.nextId>100001||!Array.isArray(s.stones)||s.stones.length>20)throw Error('场景数量/状态无效');const ids=new Set();for(const stone of s.stones){exact(stone,['id','kind','x','y','angle','mode','supportId','ticks','tipDirection']);if(!Number.isInteger(stone.id)||stone.id<1||stone.id>=s.nextId||ids.has(stone.id)||!Number.isInteger(stone.kind)||stone.kind<0||stone.kind>9||!finite(stone.x,80,720)||!finite(stone.y,-200,800)||!finite(stone.angle,-180,180)||!['falling','resting','grounded','tipping'].includes(stone.mode)||!Number.isInteger(stone.ticks)||stone.ticks<0||stone.ticks>360||![-1,0,1].includes(stone.tipDirection))throw Error('石块编号/几何/阶段无效');ids.add(stone.id);if(stone.mode==='resting'){if(!Number.isInteger(stone.supportId)||stone.supportId<=0||stone.supportId===stone.id)throw Error('支撑引用无效');}else if(stone.mode==='grounded'){if(stone.supportId!==0)throw Error('落地引用无效');}else if(stone.supportId!==null)throw Error('空中石块不能带支撑');if(stone.mode==='tipping'&&(stone.tipDirection===0||stone.ticks>180))throw Error('倾倒方向/步数无效');if(stone.mode!=='tipping'&&stone.tipDirection!==0)throw Error('非倾倒石块方向须0');if(['resting','grounded'].includes(stone.mode)&&stone.ticks!==0)throw Error('稳定石块步数须0');}
  for(const stone of s.stones){if(stone.mode==='grounded'&&Math.abs(geometry(stone).bottom-LIMITS.ground)>1e-6)throw Error('落地位置无效');if(stone.mode==='resting'){const base=s.stones.find(v=>v.id===stone.supportId);if(!base||!['resting','grounded'].includes(base.mode))throw Error('支撑依赖不存在/不稳定');const a=geometry(stone),b=geometry(base);if(Math.abs(a.bottom-b.top)>1e-6||Math.max(a.left,b.left)>Math.min(a.right,b.right))throw Error('支撑接触不符');const seen=new Set([stone.id]);let current=base;while(current?.supportId>0){if(seen.has(current.id))throw Error('支撑循环');seen.add(current.id);current=s.stones.find(v=>v.id===current.supportId);}}}return s;}
export function addStone(input,kind,x=400,y=100,angle=0){validate(input);if(input.stones.length>=20)throw Error('最多20块石头');if(input.nextId>100000)throw Error('编号上限，请另存并建立新场景');const s=clone(input);s.stones.push({id:s.nextId++,kind,x,y,angle,mode:'falling',supportId:null,ticks:0,tipDirection:0});validate(s);return s;}
export function descendants(s,id){const ids=new Set([id]);for(let i=0;i<s.stones.length;i++)for(const p of s.stones)if(ids.has(p.supportId))ids.add(p.id);return ids;}
export function moveStone(input,id,x,y,angle){validate(input);if(input.frozen)throw Error('冻结时不能移动或旋转，先继续');const s=clone(input),stone=s.stones.find(p=>p.id===id);if(!stone)throw Error('未选择石块');for(const p of s.stones)if(descendants(input,id).has(p.id)){p.mode='falling';p.supportId=null;p.ticks=0;p.tipDirection=0;}Object.assign(stone,{x,y,angle});validate(s);return s;}
export function supportInfo(s,stone){const own=geometry(stone),base=stone.supportId>0?s.stones.find(p=>p.id===stone.supportId):null,b=base?geometry(base):{left:0,right:800};const segment=[Math.max(own.left,b.left),Math.min(own.right,b.right)],ids=descendants(s,stone.id);let mass=0,weighted=0;for(const p of s.stones)if(ids.has(p.id)){const g=geometry(p);mass+=g.mass;weighted+=g.mass*g.cx;}const loadX=weighted/mass;return{segment,loadX,mass,stable:segment[0]<=segment[1]&&balance(loadX,segment),dependents:ids.size-1};}
function ground(stone){stone.y+=LIMITS.ground-geometry(stone).bottom;stone.mode='grounded';stone.supportId=0;stone.ticks=0;stone.tipDirection=0;}
export function step(input){validate(input);if(input.frozen)return{state:clone(input),events:[]};const s=clone(input),events=[];
  for(const stone of s.stones){if(stone.mode==='tipping'){stone.ticks++;stone.angle=Math.max(-180,Math.min(180,stone.angle+stone.tipDirection*(stone.ticks<=45?1.2:0)));stone.x=Math.max(80,Math.min(720,stone.x+stone.tipDirection*(stone.ticks<=45?1.2:0)));stone.y+=5;const bottom=geometry(stone).bottom;if(bottom>=LIMITS.ground){stone.y+=LIMITS.ground-bottom;if(stone.ticks>=30)ground(stone);}if(stone.ticks>=180)ground(stone);continue;}if(stone.mode!=='falling')continue;const before=geometry(stone);stone.y+=2.5;stone.ticks++;const after=geometry(stone),candidates=s.stones.filter(p=>p.id!==stone.id&&['resting','grounded'].includes(p.mode)).map(p=>({p,g:geometry(p)})).filter(({g})=>before.bottom<=g.top+1e-6&&after.bottom>=g.top&&Math.max(after.left,g.left)<=Math.min(after.right,g.right)).sort((a,b)=>a.g.top-b.g.top||a.p.id-b.p.id);if(candidates.length){const{p,g}=candidates[0];stone.y+=g.top-after.bottom;stone.mode='resting';stone.supportId=p.id;stone.ticks=0;}else if(after.bottom>=LIMITS.ground||stone.ticks>=360)ground(stone);}
  for(const stone of s.stones){if(stone.mode!=='resting')continue;const info=supportInfo(s,stone);if(info.stable)continue;const ids=descendants(s,stone.id),direction=info.loadX<(info.segment[0]+info.segment[1])/2?-1:1;for(const p of s.stones)if(ids.has(p.id)){p.mode='tipping';p.supportId=null;p.ticks=0;p.tipDirection=direction;}events.push({id:stone.id,loadX:info.loadX,segment:info.segment,reason:'石块及上方依赖的合成重心超出支撑区间'});}
  validate(s);return{state:s,events};}
export function frame(input,elapsedMs,accumulator=0){if(!finite(elapsedMs,0,Number.MAX_VALUE)||!finite(accumulator,0,LIMITS.stepMs))throw Error('帧间隔无效');validate(input);if(input.frozen)return{state:clone(input),events:[],accumulator:0,steps:0};const pending=accumulator+Math.min(elapsedMs,LIMITS.stepMs*4),steps=Math.min(4,Math.floor((pending+1e-9)/LIMITS.stepMs));let state=input,events=[];for(let i=0;i<steps;i++){const result=step(state);state=result.state;events.push(...result.events);}return{state,events,steps,accumulator:Math.max(0,Math.min(pending-steps*LIMITS.stepMs,LIMITS.stepMs-1e-9))};}
export function moving(s){return s.stones.some(p=>p.mode==='falling'||p.mode==='tipping'||(p.mode==='resting'&&!supportInfo(s,p).stable));}
export function archive(s){validate(s);const text=JSON.stringify(s,null,2);if(new TextEncoder().encode(text).length>65536)throw Error('场景存档限64KiB');return text;}
export function restore(text){if(typeof text!=='string'||text.length>65536||new TextEncoder().encode(text).length>65536)throw Error('场景存档限64KiB UTF-8');let s;try{s=JSON.parse(text);}catch{throw Error('JSON存档无效');}const tokens=text.match(/"(?:\\.|[^"\\])*"|[{}:[\],]/g)||[],stack=[];for(let i=0;i<tokens.length;i++){const t=tokens[i];if(t==='{'||t==='['){stack.push(t==='{'?new Set():null);if(stack.length>8)throw Error('存档嵌套过深');}else if(t==='}'||t===']')stack.pop();else if(t.startsWith('"')&&tokens[i+1]===':'){const key=JSON.parse(t),set=stack.at(-1);if(!(set instanceof Set)||set.has(key))throw Error('存档重复字段');set.add(key);}}return clone(validate(s));}
const num=n=>+n.toFixed(3);
export function sceneSVG(s,selected=null,full=false){validate(s);if(typeof full!=='boolean')throw Error('完整场景参数无效');let blocks='';for(const p of s.stones){const g=geometry(p),center=`<circle cx="${num(g.cx)}" cy="${num(g.cy)}" r="3" fill="#c58a60"/>`;blocks+=`<g data-stone="${p.id}"><polygon points="${g.points.map(point=>point.map(num).join(',')).join(' ')}" fill="${KINDS[p.kind].color}" stroke="${p.id===selected?'#ad7549':'#617c73'}" stroke-width="${p.id===selected?3:1.5}"/>${center}</g>`;if(p.mode==='resting'){const info=supportInfo(s,p);blocks+=`<path d="M${num(info.segment[0])} ${num(g.bottom+3)} H${num(info.segment[1])}" stroke="#bb9366" stroke-width="3"/><path d="M${num(info.loadX)} ${num(g.top-13)} v8" stroke="#a26943" stroke-width="2"/>`;}}
  const all=s.stones.map(geometry),left=full?Math.floor(Math.min(0,...all.map(g=>g.left-12))):0,top=full?Math.floor(Math.min(0,...all.map(g=>g.top-12))):0,right=full?Math.ceil(Math.max(800,...all.map(g=>g.right+12))):800,bottom=full?Math.ceil(Math.max(600,...all.map(g=>g.bottom+12))):600;return `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="${left} ${top} ${right-left} ${bottom-top}"><rect x="${left}" y="${top}" width="${right-left}" height="${bottom-top}" fill="#e6e9dc"/><path d="M0 352 Q168 291 319 369 T800 335 V540 H0Z" fill="#cad6c4"/><path d="M0 437 Q217 365 464 433 T800 410 V540 H0Z" fill="#d7deca"/><rect y="540" width="800" height="60" fill="#b8ac91"/><path d="M0 540 H800" stroke="#8a826e" stroke-width="3"/>${blocks}</svg>`;}
export function pngBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('PNG编码失败')),'image/png'));}
export async function pngPayload(blob){if(!blob||blob.type!=='image/png'||blob.size>LIMITS.pngBytes)throw Error('PNG限10MiB');const bytes=new Uint8Array(await blob.arrayBuffer());if(bytes.length!==blob.size||![137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))throw Error('PNG字节无效');const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');let raw='';for(let i=0;i<bytes.length;i+=16384)raw+=String.fromCharCode(...bytes.subarray(i,i+16384));return{copyOnly:true,defaultName:'balance-stones-copy.png',base64:btoa(raw),sha256};}
