export const LIMITS=Object.freeze({bodyBytes:2097152,keyBytes:4096,diffExamples:100});
const hashes={'SHA-256':32,'SHA-384':48,'SHA-512':64};
function text(s){if(typeof s!=='string'||[...s].some(c=>c.codePointAt(0)>=0xd800&&c.codePointAt(0)<=0xdfff))throw Error('输入须合法Unicode字符串，不自动修复孤立代理项。');return s;}
export function bytesFrom(value,encoding,max=LIMITS.bodyBytes){text(value);let bytes;if(encoding==='utf8')bytes=new TextEncoder().encode(value);else if(encoding==='hex'){if(value.length%2||!/^[0-9a-f]*$/i.test(value))throw Error('hex须完整偶数位、不含空格或前缀。');if(value.length/2>max)throw Error('字节容量超限。');bytes=Uint8Array.from(value.match(/../g)||[],v=>parseInt(v,16));}else if(encoding==='base64'){if(value.length>Math.ceil(max/3)*4||value!==''&&(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value)))throw Error('Base64须标准带padding的规范编码，无空格/URL变体。');let decoded;try{decoded=atob(value);}catch{throw Error('Base64解码失败。');}if(btoa(decoded)!==value)throw Error('Base64 padding位非规范。');bytes=Uint8Array.from(decoded,c=>c.charCodeAt(0));}else throw Error('字节编码不支持。');if(bytes.length>max)throw Error('字节容量超限。');return bytes;}
export function hex(bytes){return Array.from(bytes,n=>n.toString(16).padStart(2,'0')).join('');}
export function parseSignature(signature,format,algorithm){if(!Object.hasOwn(hashes,algorithm))throw Error('只支持SHA-256/384/512。');text(signature);if(signature.length>256)throw Error('签名输入超限。');let bytes;if(format==='github'){if(algorithm!=='SHA-256'||!signature.startsWith('sha256='))throw Error('GitHub格式只支持完整sha256=HMAC-SHA256头值。');bytes=bytesFrom(signature.slice(7),'hex',64);}else if(format==='hex'||format==='base64')bytes=bytesFrom(signature,format,64);else throw Error('签名格式不支持。');if(bytes.length!==hashes[algorithm])throw Error('签名字节数必须等于完整算法输出，不支持截断签名。');return bytes;}
function boundedBytes(value,max,label){if(!(value instanceof Uint8Array)||value.length>max)throw Error(`${label}须容量内Uint8Array。`);return value;}
export function compareBytes(actual,reference){boundedBytes(actual,LIMITS.bodyBytes,'消息');boundedBytes(reference,LIMITS.bodyBytes,'参考');let differenceCount=0;const offsets=[];for(let i=0;i<Math.max(actual.length,reference.length);i++)if(i>=actual.length||i>=reference.length||actual[i]!==reference[i]){differenceCount++;if(offsets.length<100)offsets.push(i);}return{actualBytes:actual.length,referenceBytes:reference.length,identical:differenceCount===0,differenceCount,firstDifferenceOffset:offsets[0]??null,offsetExamples:offsets,offsetExamplesLimit:100,offsetExamplesAreComplete:differenceCount<=100,scope:'按0起字节偏移逐位比较；插入/删除会令后续错位，不是最小编辑距离。示例最多100，差异总数覆盖完整集合；不输出字节值。'};}
function canceled(signal){if(signal?.aborted)throw Object.assign(Error('已取消，没有部分核验报告。'),{name:'AbortError'});}
export async function verifyHmac({body,keyText,keyEncoding='utf8',signature,signatureFormat='hex',algorithm='SHA-256',reference=null},hooks={}){
 boundedBytes(body,LIMITS.bodyBytes,'原始消息');if(reference!==null)boundedBytes(reference,LIMITS.bodyBytes,'参考消息');body=Uint8Array.from(body);reference=reference===null?null:Uint8Array.from(reference);const provided=parseSignature(signature,signatureFormat,algorithm),keyBytes=bytesFrom(keyText,keyEncoding,LIMITS.keyBytes);if(!keyBytes.length)throw Error('密钥须至少1字节，不使用空密钥。');const subtle=(hooks.crypto||globalThis.crypto)?.subtle;if(!subtle){keyBytes.fill(0);provided.fill(0);body.fill(0);reference?.fill(0);throw Error('本机WebCrypto不可用。');}let key;
 try{canceled(hooks.signal);key=await subtle.importKey('raw',keyBytes,{name:'HMAC',hash:algorithm},false,['verify']);canceled(hooks.signal);const match=await subtle.verify('HMAC',key,provided,body);canceled(hooks.signal);const bodyDigest=await subtle.digest('SHA-256',body);canceled(hooks.signal);let byteDifference=null;if(reference!==null){boundedBytes(reference,LIMITS.bodyBytes,'参考消息');byteDifference=compareBytes(body,reference);}return{feature:'T068',version:1,algorithm,signatureFormat,match,bodyBytes:body.length,bodySha256:hex(new Uint8Array(bodyDigest)),providedSignatureBytes:provided.length,keyOmitted:true,rawBodyOmitted:true,rawSignatureOmitted:true,byteDifference,scope:'离线HMAC核验完整原始字节；不发送请求。匹配仅证明本输入密钥/算法/签名字节与消息一致，不验证来源身份、时间戳新鲜度、重放、事件内容或供应商认证。失败不能单独区分密钥错误、消息字节错误或供应商签名串拼接规则错误。不解析JSON、不规范换行/Unicode、不自动解压；通用模式直接签body，GitHub只认sha256=头。Stripe/Slack等时间戳前缀方案不在本模式范围。'};}
 finally{keyBytes.fill(0);provided.fill(0);body.fill(0);reference?.fill(0);key=null;}
}
export async function readBytes(file,hooks={}){if(!file||!Number.isSafeInteger(file.size)||file.size<0||file.size>LIMITS.bodyBytes||typeof file.slice!=='function')throw Error('原始文件须≤2MiB。');const bytes=new Uint8Array(file.size);try{for(let at=0;at<file.size;at+=65536){canceled(hooks.signal);const end=Math.min(file.size,at+65536),b=await file.slice(at,end).arrayBuffer();if(!(b instanceof ArrayBuffer)||b.byteLength!==end-at)throw Error('原始文件读取长度不符。');bytes.set(new Uint8Array(b),at);await(hooks.yieldControl||(()=>new Promise(r=>setTimeout(r,0))))();}canceled(hooks.signal);return bytes;}catch(e){bytes.fill(0);throw e;}}
export const EXAMPLE=Object.freeze({body:'Hi There',keyEncoding:'hex',keyText:'0b'.repeat(20),signature:'b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7',algorithm:'SHA-256'});
