import {h} from '../../core/ui.js';
import {validateIndex,buildIndex,compare,select,reportText} from './model.mjs';
export default{id:'T018',create(root,{config}){
let alive=true,active=false,busy=false,epoch=0,job=null,selected=null,index=null,scan=null,delta=null,preview=null,page=0;const key='feature.T018.index.v1',buttons=[],status=h('p',{role:'status'}),source=h('p'),results=h('div'),rules=h('textarea',{rows:3,'aria-label':'索引排除相对路径'}),view=h('pre',{'aria-label':'完整索引报告预览',style:{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:'400px',overflow:'auto'}}),form={};
for(const [id,label]of[['name','名称或相对路径包含'],['minBytes','最小逻辑字节'],['maxBytes','最大逻辑字节'],['afterUTC','修改时间UTC下界'],['beforeUTC','修改时间UTC上界']])form[id]=h('input',{'aria-label':label,placeholder:id.includes('UTC')?'2026-10-03T00:00:00.000Z':'',style:{margin:'4px'}});
const live=()=>alive&&active&&!document.hidden,api=()=>window.toolbox?.features,message=t=>{if(alive)status.textContent=t;},raw=()=>Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v.value]));
function update(){for(const[b,kind]of buttons)b.disabled=!live()||(kind==='cancel'?!job:busy)||(kind==='scan'&&!selected)||(kind==='index'&&!index)||(kind==='preview'&&!scan&&!index)||(kind==='save'&&(!preview||window.toolbox?.files?.saveTextSupportsCopyOnly!==true));for(const n of[rules,...Object.values(form)])n.disabled=!live()||busy;}
const button=(name,fn,kind)=>{const b=h('button',{type:'button',onclick:fn,style:{margin:'4px'}},name);buttons.push([b,kind]);return b;};
try{const saved=config.get(key,null);if(saved!==null){index=validateIndex(saved);rules.value=index.exclusions.join('\n');message('已读取本地索引；它是过去观察，不是当前目录保证，需重新选择根才能刷新。');}}catch{message('本地索引无效，未采用；可选择目录重建，旧配置不自动覆盖。');}
function clearPreview(){preview=null;view.textContent='';}
function render(){results.replaceChildren();if(!index){update();return;}try{const rows=select(index,raw()),pages=Math.max(1,Math.ceil(rows.length/40));page=Math.min(page,pages-1);results.append(h('p',{},'索引根 '+index.rootPath+' · 观察UTC '+index.observedAtUTC+' · 全部 '+index.files.length+' 文件 · 筛选 '+rows.length+'，第'+(page+1)+'/'+pages+'页。快照可能已过期。'),h('p',{},delta?.comparable?'新增 '+delta.added.length+'、变化 '+delta.changed.length+'、移除 '+delta.removed.length+'、未变 '+delta.unchanged:'无可比较上一完整范围；不把全部文件冒称新增。'),h('table',{},h('thead',{},h('tr',{},['相对路径','逻辑字节','修改时间UTC','定位'].map(t=>h('th',{},t)))),h('tbody',{},rows.slice(page*40,page*40+40).map(f=>h('tr',{},h('td',{},f.relative),h('td',{},String(f.size)),h('td',{},new Date(f.mtimeMs).toISOString()),h('td',{},h('button',{type:'button',onclick:async()=>{if(!live()||busy)return;const sep=index.platform==='win32'?'\\':'/',absolute=index.rootPath.replace(/[\\/]$/,'')+sep+f.relative.split('/').join(sep);try{const result=await window.toolbox?.clipboard?.write(absolute);message(result===true?'完整文件路径已复制；文件是否仍存在需用户回源核对。':'复制未确认，完整路径：'+absolute);}catch{message('复制失败，完整路径：'+absolute);}}},'复制完整路径')))))),h('div',{},h('button',{type:'button',disabled:page===0,onclick:()=>{if(live()&&!busy&&page){page--;render();}}},'上一页索引'),h('button',{type:'button',disabled:page>=pages-1,onclick:()=>{if(live()&&!busy&&page<pages-1){page++;render();}}},'下一页索引')));}catch(e){message('筛选拒绝：'+e.message);}update();}
for(const n of Object.values(form))n.addEventListener('input',()=>{if(live()&&!busy){page=0;clearPreview();render();}});rules.addEventListener('input',()=>{if(live()&&!busy){scan=delta=null;clearPreview();message('范围规则已编辑，现有索引仍为旧范围；重新扫描才能更新。');update();}});
async function call(op,p){if(api()?.callHostSupported!==true)throw Error('缺少可信Host桥');return api().callHost('T018',op,p);}
async function choose(){if(!live()||busy)return;const token=epoch;selected=null;scan=delta=null;busy=true;clearPreview();update();try{const r=await call('choose_root',{});if(!alive||token!==epoch)return;if(r?.ok!==true)throw Error(r?.canceled?'选择取消':r?.error||'选择未确认');selected=r.root;source.textContent='本次明确选择根：'+selected.path;message('目录已选择，尚未读取文件元数据；手动扫描或增量刷新。');}catch(e){if(alive&&token===epoch)message(e.message);}finally{busy=false;update();}}
async function refresh(){if(!live()||busy||!selected)return;const token=epoch,id=crypto.randomUUID();job=id;scan=delta=null;busy=true;clearPreview();update();message('读取范围内元数据，尚未完成；正文不读取。');try{const r=await call('scan',{rootId:selected.id,input:{exclusions:rules.value},jobId:id});if(!alive||token!==epoch)return;if(r?.ok!==true)throw Error(r?.error||'扫描未确认');scan=r.report;if(scan.complete){const next=buildIndex(scan);delta=compare(index,next);index=next;page=0;render();message('完整支持域索引更新；增量对比完成。尚未保存本地索引。');}else{delta=null;message('扫描部分/未知：'+(scan.reason??'见目录与逐项错误')+'。旧完整索引保留；不判定删除，完整扫描报告可另存。');}}catch(e){if(alive&&token===epoch)message('索引未更新：'+e.message);}finally{if(job===id)job=null;busy=false;update();}}
function cancel(){if(job)api()?.cancelHost?.('T018',job).catch(()=>{});}
async function persist(){if(!live()||busy||!index)return;const token=epoch;busy=true;update();try{const frozen=validateIndex(index);await config.set(key,frozen);if(alive&&token===epoch)message('本地索引已保存；重载仅恢复快照，不扫描或保证文件仍存在。');}catch(e){if(alive&&token===epoch)message('保存本地索引失败：'+e.message);}finally{busy=false;update();}}
async function erase(){if(!live()||busy||!index||!window.confirm('删除T018本地索引及当前快照？不会删除目录文件或已导出的副本。'))return;const token=epoch;busy=true;update();try{await config.set(key,null);if(!alive||token!==epoch)return;index=scan=delta=null;clearPreview();results.replaceChildren();message('本地索引已删除，来源文件和导出副本保留。');}catch(e){if(alive&&token===epoch)message('删除索引未完成：'+e.message);}finally{busy=false;update();}}
function show(ext){if(!live()||busy||!scan&&!index)return;try{const selection=index?select(index,raw()):[];const report={format:'T018-index-report',version:1,index,scan,delta,filters:raw(),matchingRelativePaths:selection.map(f=>f.relative),scope:'完整快照/本次扫描/增量和筛选路径全部保留，显示分页不限制副本。新增/移除仅两个相同根与排除范围的完整观察之间，不是文件历史或正文变化证明。'};preview={extension:ext,content:reportText(report,ext)};view.textContent=preview.content;message('完整索引报告已预览，含全部本地路径，保存前核对。');}catch(e){clearPreview();message(e.message);}update();}
async function save(){if(!live()||busy||!preview||window.toolbox?.files?.saveTextSupportsCopyOnly!==true)return;const token=epoch,p=preview;busy=true;update();try{const r=await window.toolbox.files.saveText({copyOnly:true,extension:p.extension,defaultName:'directory-index-copy.'+p.extension,content:p.content});if(alive&&token===epoch)message(r?.ok===true?'完整索引报告新副本保存成功。':r?.canceled?'保存取消，预览保留。':'保存失败：'+(r?.error||'未确认成功'));}catch(e){if(alive&&token===epoch)message('保存失败：'+e.message);}finally{busy=false;update();}}
function leave(){epoch++;cancel();job=selected=null;source.textContent='';scan=delta=null;clearPreview();message('已离开，根选择与当前报告清除；旧索引仅为快照，返回不自动扫描。');update();}const visibility=()=>{if(document.hidden)leave();update();};document.addEventListener('visibilitychange',visibility);
root.classList.add('t018');root.append(h('section',{style:{padding:'18px',maxWidth:'1100px',margin:'0 auto',lineHeight:'1.6'}},h('h2',{},'大目录索引与定位'),h('p',{},'只读选定根内普通文件相对路径、逻辑大小、mtime，不读正文，不跟随链接。增量刷新仍遍历元数据，只按上次相同完整范围比较；不后台监视或修改目录。'),button('选择索引根目录',choose,'choose'),source,h('label',{},'每行精确排除相对路径（/分隔，包含子树，无glob）',rules),button('扫描或增量刷新索引',refresh,'scan'),button('取消本次索引扫描',cancel,'cancel'),status,h('div',{},Object.entries(form).map(([id,n])=>h('label',{},n.getAttribute('aria-label')+' ',n))),results,button('保存本地索引到配置',persist,'index'),button('删除本地索引',erase,'index'),h('p',{},'最多10000已读取项/1000目录/24层/1MiB路径/30秒协作期限；OS读取不能硬停。完整索引≤2MiB，显式保存到应用本地配置，包含路径，未加密。保存后才可重载恢复；删除只清此工具索引。变化仅大小/mtime/路径，不检测内容相同长度同时间的变化。'),button('预览完整JSON索引报告',()=>show('json'),'preview'),button('预览完整Markdown索引报告',()=>show('md'),'preview'),view,button('保存已预览索引报告新副本',save,'save')));render();update();return{activate(){if(alive){active=true;update();}},deactivate(){if(alive){active=false;leave();}},destroy(){if(!alive)return;active=false;leave();alive=false;index=scan=delta=preview=null;document.removeEventListener('visibilitychange',visibility);root.replaceChildren();root.classList.remove('t018');}};
}};
