export const LIMITS=Object.freeze({entries:10000,directories:1000,depth:24,pathBytes:1048576,runMs:30000,reportBytes:8388608});
export function input(raw,platform){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).join('|')!=='exclusions'||typeof raw.exclusions!=='string'||new TextEncoder().encode(raw.exclusions).length>4096)throw Error('排除规则须≤4096字节的完整文本。');const text=raw.exclusions.replaceAll('\r\n','\n');if(/[\x00-\x09\x0b-\x1f\x7f]/.test(text))throw Error('排除规则包含无效控制字符。');const rules=text.split('\n').map(x=>x.trim()).filter(Boolean);if(rules.length>32)throw Error('最多32条相对路径排除规则。');const seen=new Set();for(const rule of rules){const segments=rule.split('/');if(rule.length>512||segments.length>16||segments.some(s=>!s||['.','..'].includes(s)||s.length>128||/^[ .]|[ .]$/.test(s)||/[\\:*?"<>|]/.test(s)||/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(s)))throw Error('规则须安全相对路径/分隔，不含绝对路径、通配符、点段或保留名。');const key=platform==='win32'?rule.toLowerCase():rule;if(seen.has(key))throw Error('排除规则重复。');seen.add(key);}return{exclusions:rules,ruleType:'exact_relative_path_and_subtree',comparison:platform==='win32'?'case_insensitive':'case_sensitive',note:'每行一个根内相对路径，以/分隔，精确匹配该项及子树；不是glob/正则或任意同名目录规则。排除项不读取其内容/元数据。'};}
export function excluded(relative,rules,platform){const normalize=s=>platform==='win32'?s.toLowerCase():s;const value=normalize(relative);return rules.find(r=>value===normalize(r)||value.startsWith(normalize(r)+'/'))??null;}
export const INDEX_BYTES=2097152;
const size=v=>new TextEncoder().encode(JSON.stringify(v)).length;
function strict(v,keys){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join('|')!==[...keys].sort().join('|'))throw Error('索引字段无效');}
export function validateIndex(v){strict(v,['format','version','rootPath','platform','exclusions','observedAtUTC','files']);if(v.format!=='T018-directory-index'||v.version!==1||!['win32','linux','darwin'].includes(v.platform)||typeof v.rootPath!=='string'||!v.rootPath||v.rootPath.length>4096||!Array.isArray(v.exclusions)||v.exclusions.some(x=>typeof x!=='string')||typeof v.observedAtUTC!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v.observedAtUTC)||(!Number.isFinite(Date.parse(v.observedAtUTC))||new Date(v.observedAtUTC).toISOString()!==v.observedAtUTC)||!Array.isArray(v.files)||v.files.length>10000||size(v)>INDEX_BYTES)throw Error('本地索引版本/容量/来源无效');const rules=input({exclusions:v.exclusions.join('\n')},v.platform).exclusions;if(JSON.stringify(rules)!==JSON.stringify(v.exclusions))throw Error('排除规则不规范');const names=new Set();for(const f of v.files){strict(f,['relative','size','mtimeMs']);if(typeof f.relative!=='string'||!f.relative||f.relative.length>2048||f.relative.split('/').some(s=>!s||s==='.'||s==='..'||/[\x00-\x1f\x7f\\]/.test(s))||!Number.isSafeInteger(f.size)||f.size<0||(!Number.isFinite(f.mtimeMs)||Math.abs(f.mtimeMs)>8640000000000000)||excluded(f.relative,rules,v.platform))throw Error('文件元数据无效');const key=v.platform==='win32'?f.relative.toLowerCase():f.relative;if(names.has(key))throw Error('索引路径重复');names.add(key);}return JSON.parse(JSON.stringify(v));}
export function buildIndex(report){if(report?.format!=='T018-directory-index-scan'||report.version!==1||report.complete!==true||report.reason!==null)throw Error('只接受完整支持域扫描，部分结果不替换索引');return validateIndex({format:'T018-directory-index',version:1,rootPath:report.root.path,platform:report.platform,exclusions:report.plan.exclusions,observedAtUTC:report.completedAtUTC,files:report.files});}
export function compare(oldIndex,newIndex){const next=validateIndex(newIndex),old=oldIndex?validateIndex(oldIndex):null,key=s=>next.platform==='win32'?s.toLowerCase():s,comparable=old&&old.platform===next.platform&&key(old.rootPath)===key(next.rootPath)&&JSON.stringify(old.exclusions)===JSON.stringify(next.exclusions);if(!comparable)return{comparable:false,reason:old?'根目录/平台/排除范围不同':'无上次完整索引',added:[],changed:[],removed:[],unchanged:0};const previous=new Map(old.files.map(f=>[key(f.relative),f])),added=[],changed=[];let unchanged=0;for(const current of next.files){const id=key(current.relative),before=previous.get(id);previous.delete(id);if(!before)added.push(current);else if(before.size!==current.size||before.mtimeMs!==current.mtimeMs||before.relative!==current.relative)changed.push({before,after:current,fields:['relative','size','mtimeMs'].filter(k=>before[k]!==current[k])});else unchanged++;}return{comparable:true,reason:null,added,changed,removed:[...previous.values()],unchanged};}
export function filters(v){strict(v,['name','minBytes','maxBytes','afterUTC','beforeUTC']);if(typeof v.name!=='string'||v.name.length>200)throw Error('名称筛选过长');const number=s=>{if(typeof s!=='string'||s!==''&&!/^(0|[1-9]\d{0,15})$/.test(s)||s!==''&&!Number.isSafeInteger(Number(s)))throw Error('大小须完整非负整数或空');return s===''?null:Number(s);},date=s=>{if(typeof s!=='string'||s!==''&&(!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString()!==s))throw Error('时间须规范UTC ISO毫秒或空');return s===''?null:Date.parse(s);};const minBytes=number(v.minBytes),maxBytes=number(v.maxBytes),afterMs=date(v.afterUTC),beforeMs=date(v.beforeUTC);if(minBytes!==null&&maxBytes!==null&&minBytes>maxBytes||afterMs!==null&&beforeMs!==null&&afterMs>beforeMs)throw Error('筛选上下界颠倒');return{name:v.name,minBytes,maxBytes,afterMs,beforeMs};}
export function select(index,raw){const i=validateIndex(index),f=filters(raw),needle=f.name.toLowerCase();return i.files.filter(r=>r.relative.toLowerCase().includes(needle)&&(f.minBytes===null||r.size>=f.minBytes)&&(f.maxBytes===null||r.size<=f.maxBytes)&&(f.afterMs===null||r.mtimeMs>=f.afterMs)&&(f.beforeMs===null||r.mtimeMs<=f.beforeMs)).sort((a,b)=>a.relative<b.relative?-1:a.relative>b.relative?1:0);}
export function reportText(report,ext){const json=JSON.stringify(report,null,2),tick=String.fromCharCode(96);let text;if(ext==='json')text=json+'\n';else if(ext==='md')text='# T018 本地目录索引\n\n'+tick.repeat(3)+'json\n'+json.replaceAll(tick,'\\u0060')+'\n'+tick.repeat(3)+'\n';else throw Error('仅JSON/Markdown');if(new TextEncoder().encode(text).length>LIMITS.reportBytes)throw Error('完整报告超过8MiB，未截断');return text;}
