import {h} from '../../core/ui.js';
import {example,analyze,stored,restore,markdown} from './model.mjs';
export default{id:'L003',create(root,ctx={}){let draft=example(),result=null,alive=true,active=true,busy=false,nextC=4,nextS=5;const editor=h('div'),output=h('div'),status=h('p',{role:'status',class:'l003-status'}),files=window.toolbox?.files;const safe=()=>files?.saveTextSupportsCopyOnly===true&&typeof files.saveText==='function',say=s=>{if(alive)status.textContent=s;},invalidate=()=>{result=null;output.replaceChildren();say('标注已修改，旧组合结论清空，请重新枚举。');},button=(s,fn)=>h('button',{type:'button',class:'btn',onclick:()=>{if(alive&&active&&!busy)fn();}},s);
 function input(aria,value,setter,max){const el=h('input',{'aria-label':aria,maxlength:max,oninput:()=>{setter(el.value);invalidate();}});el.value=value;return el;}
 function render(){const conditions=draft.conditions.map((c,i)=>h('div',{class:'l003-row'},input(`条件${i+1}ID`,c.id,v=>c.id=v,12),input(`条件${i+1}描述`,c.description,v=>c.description=v,120),button(`删除条件${i+1}`,()=>{if(draft.conditions.length===1){say('至少一个条件。');return;}draft.conditions.splice(i,1);draft.samples.forEach(s=>s.values.splice(i,1));invalidate();render();})));
 const rows=draft.samples.map((s,i)=>{const label=h('select',{'aria-label':`${s.id}正反标签`,onchange:()=>{s.label=label.value;invalidate();}},h('option',{value:'positive'},'正例'),h('option',{value:'negative'},'反例'));label.value=s.label;return h('tr',{},h('td',{},input(`样本${i+1}ID`,s.id,v=>s.id=v,12)),h('td',{},input(`${s.id}名称`,s.name,v=>s.name=v,60)),h('td',{},label),...draft.conditions.map((c,j)=>{const select=h('select',{'aria-label':`${s.id}条件${c.id}`,onchange:()=>{s.values[j]=select.value===''?null:select.value==='true';invalidate();}},h('option',{value:''},'未填'),h('option',{value:'true'},'真'),h('option',{value:'false'},'假'));select.value=s.values[j]===null?'':String(s.values[j]);return h('td',{},select);}),h('td',{},button(`删除样本${i+1}`,()=>{draft.samples.splice(i,1);invalidate();render();})));});
 editor.replaceChildren(h('h3',{},'条件定义'),...conditions,button('添加条件',()=>{if(draft.conditions.length>=10){say('最多10条件。');return;}let id;do{id='C'+nextC++;}while(draft.conditions.some(c=>c.id===id));draft.conditions.push({id,description:'新条件'});draft.samples.forEach(s=>s.values.push(null));invalidate();render();}),h('h3',{},'正反例条件矩阵'),h('div',{class:'l003-scroll'},h('table',{},h('thead',{},h('tr',{},['ID','名称','标签',...draft.conditions.map(c=>c.id),'操作'].map(t=>h('th',{},t)))),h('tbody',{},rows))),button('添加样本',()=>{if(draft.samples.length>=64){say('最多64样本。');return;}let id;do{id='S'+nextS++;}while(draft.samples.some(s=>s.id===id));draft.samples.push({id,name:'新样本',label:'positive',values:draft.conditions.map(()=>null)});invalidate();render();}));}
 function run(){invalidate();try{result=analyze(draft);output.replaceChildren(h('h3',{},result.minimumSize===null?'存在无法区分的相反标签样本':`最小条件数 ${result.minimumSize} · ${result.minimumCombinations.length}个组合`),h('p',{},result.policy),h('p',{},`检查${result.checkedSubsets}个候选子集，正例${result.positiveCount}、反例${result.negativeCount}。`),h('ul',{class:'l003-combinations'},result.minimumCombinations.map(c=>h('li',{},c.conditionIds.join(' + '),h('ul',{},c.groups.map(g=>h('li',{},`${g.signature} → ${g.label==='positive'?'正例':'反例'}：${g.sampleIds.join('、')}`)))))),h('ul',{class:'l003-conflicts'},result.conflicts.map(c=>h('li',{},`${c.positive}与${c.negative}全部条件相同，标签相反；增加条件或核对标注。`))),h('h4',{},'条件覆盖表：正/反例真/假人数'),h('div',{class:'l003-scroll'},h('table',{},h('thead',{},h('tr',{},['条件','正例真','正例假','反例真','反例假'].map(t=>h('th',{},t)))),h('tbody',{},result.coverage.map(c=>h('tr',{},[c.id,c.positiveTrue,c.positiveFalse,c.negativeTrue,c.negativeFalse].map(v=>h('td',{},v))))))),...['json','md'].map(ext=>{const b=button(`导出 ${ext.toUpperCase()} 完整副本`,()=>save(ext));b.disabled=!safe();return b;}));say(result.minimumSize===null?`无法区分：${result.conflicts.length}对冲突。`:`最小组合仅需${result.minimumSize}个条件，共${result.minimumCombinations.length}组。`);}catch(e){say('枚举失败：'+e.message);}}
 async function save(extension){if(!result||!safe()||busy)return;busy=true;const snapshot=result;try{const r=await files.saveText({content:extension==='json'?JSON.stringify(snapshot,null,2):markdown(snapshot),extension,defaultName:`L003-boundary-report.${extension}`,copyOnly:true});say(r?.ok===true?'已保存完整新副本。':r?.canceled?'已取消保存。':'保存失败：'+(r?.error||'未确认成功'));}catch(e){say(e.message);}finally{busy=false;}}
 const pasted=h('textarea',{rows:4,maxlength:65536,'aria-label':'恢复反例JSON'});root.replaceChildren(h('section',{class:'l003'},h('link',{rel:'stylesheet',href:new URL('./style.css',import.meta.url).href}),h('h2',{},'反例边界工坊'),h('p',{},'手动标注布尔条件、正反例；找能够区分这些样本的最少条件。不替你标注或推断未见样本。'),status,button('载入四样本 C2 示例',()=>{draft=example();invalidate();render();}),editor,button('枚举全部最小组合',run),button('保存版本草稿',()=>{try{if(typeof ctx.config?.set!=='function')throw Error('当前没有配置接口。');Promise.resolve(ctx.config.set('features.L003.draft',stored(draft))).then(()=>say('已保存版本1草稿，结论需重算。')).catch(e=>say(e.message));}catch(e){say(e.message);}}),output,h('details',{},h('summary',{},'恢复JSON草稿或完整报告'),pasted,button('恢复反例样本',()=>{try{const next=restore(pasted.value);draft=next;invalidate();render();say('已恢复标注，旧派生结论不采用。');}catch(e){say('恢复失败，原标注保留：'+e.message);}})),h('p',{},'最多10条件、64样本，真/假必须全部明确。新增未填值阻止枚举，至少一个正例和反例。最小组合是条件值向量区分，不是所有条件都必须为真；存在完全相同而标签相反的样本时列冲突。保存草稿仅接受完整有效标注，版本JSON恢复64KiB UTF-8；切换前需保存或导出。')));
 try{const data=ctx.config?.get('features.L003.draft');if(data){draft=restore(JSON.stringify(data));say('已恢复完整草稿，请重算。');}}catch(e){say('旧草稿未恢复：'+e.message);}render();return{activate(){active=true;},deactivate(){active=false;},destroy(){alive=false;active=false;draft=null;result=null;pasted.value='';root.replaceChildren();}};
}};
