'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url'),{performance}=require('node:perf_hooks');const model=import(pathToFileURL(path.join(__dirname,'model.mjs')).href);
function strict(p,keys){if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).sort().join('|')!==[...keys].sort().join('|'))throw Error('请求字段无效。');}
function createHost({fileSystem=fs,platform=process.platform,environment=process.env}={}){const states=new Map(),pathAPI=platform==='win32'?path.win32:path.posix,compare=v=>platform==='win32'?v.toLowerCase():v;
 function state(id){if(!Number.isSafeInteger(id)||id<1)throw Error('窗口编号无效。');if(!states.has(id)){if(states.size>=32)throw Error('窗口数量已满。');states.set(id,{busy:false,job:null,seen:new Set()});}return states.get(id);}
 return{async invoke(op,p,{senderId}={}){let s,locked=false;try{s=state(senderId);if(s.busy)throw Error('当前窗口正在枚举，请等待文件读取结束。');s.busy=true;locked=true;if(op==='analyze'&&typeof p?.jobId==='string'&&/^[-A-Za-z0-9_]{12,64}$/.test(p.jobId))s.job={id:p.jobId,reason:null};const m=await model;if(states.get(senderId)!==s)throw Error('窗口已销毁。');
 if(op==='snapshot'){strict(p,[]);const key=name=>Object.keys(environment).find(k=>platform==='win32'?k.toUpperCase()===name:k===name),pathText=environment[key('PATH')]??'',pathext=platform==='win32'?(environment[key('PATHEXT')]??''):'';if(typeof pathText!=='string'||Buffer.byteLength(pathText)>m.LIMITS.pathBytes||typeof pathext!=='string'||Buffer.byteLength(pathext)>512)throw Error('完整环境快照超过容量，不截断。');return{ok:true,snapshot:{pathText,pathext,platform,source:'app_process_environment',capturedAtUTC:new Date().toISOString(),note:'当前应用进程的继承环境，不读取注册表，也不证明其它Shell会话相同。'}};}
 if(op!=='analyze')throw Error('只支持snapshot/analyze。');strict(p,['input','jobId']);if(!s.job||s.seen.has(p.jobId)||s.seen.size>=128)throw Error('任务编号无效/重复/数量已满。');const plan=m.input(p.input,platform);s.seen.add(p.jobId);const job=s.job,begin=performance.now(),beganUTC=new Date().toISOString(),timer=setTimeout(()=>{if(!job.reason)job.reason='deadline';},m.LIMITS.runMs),entries=plan.entries.map(e=>({...e,status:'not_run',code:null,canonicalDirectory:null,duplicateOf:null,matches:[],checks:[]})),directories=new Map(),found=new Map();let actualFileChecks=0;
 const check=()=>{if(performance.now()-begin>m.LIMITS.runMs&&!job.reason)job.reason='deadline';if(job.reason)throw Error('interrupted');};const sameFile=(a,b)=>a.dev===b.dev&&a.ino===b.ino&&a.mtimeMs===b.mtimeMs;const allowed=v=>platform!=='win32'||/^[A-Za-z]:[\\/]/.test(v);
 try{for(const row of entries){if(job.reason){row.code=job.reason;continue;}if(row.issue){row.status='unresolved';row.code=row.issue;continue;}try{check();const normalized=pathAPI.normalize(row.path),canonical=await fileSystem.realpath(normalized);check();if(!allowed(canonical)){row.status='unresolved';row.code='canonical_nonlocal_path';continue;}row.canonicalDirectory=canonical;const directory=await fileSystem.stat(canonical);check();if(!directory.isDirectory()){row.status='not_directory';continue;}const directoryKey=compare(canonical);if(directories.has(directoryKey)){row.status='duplicate_directory';row.duplicateOf=directories.get(directoryKey);continue;}directories.set(directoryKey,row.index);row.status='inspected';
   for(let extensionIndex=0;extensionIndex<plan.names.length;extensionIndex++){check();const name=plan.names[extensionIndex],candidate=pathAPI.join(canonical,name),item={extensionIndex,name,path:candidate,status:'missing',code:null};row.checks.push(item);actualFileChecks++;try{const info=await fileSystem.lstat(candidate);check();if(info.isSymbolicLink()){item.status='link_not_followed';const match={path:candidate,entryIndex:row.index,extensionIndex,kind:'link',size:null,executableVerified:false,flags:['link_target_unknown'],source:'lstat_only'};row.matches.push(match);found.set(compare(candidate),match);}else if(info.isFile()){item.status='file';const flags=[];if(info.size===0)flags.push('zero_byte_possible_placeholder');if(platform==='win32'&&canonical.split(/[\\/]/).some(part=>part.toLowerCase()==='windowsapps'))flags.push('possible_app_execution_alias_location');if(platform!=='win32'&&!(info.mode&0o111))flags.push('no_execute_mode_bit');const match={path:candidate,entryIndex:row.index,extensionIndex,kind:'file',size:info.size,mtimeMs:info.mtimeMs,modeExecuteBit:platform==='win32'?null:Boolean(info.mode&0o111),executableVerified:false,flags,source:'lstat_only'};row.matches.push(match);found.set(compare(candidate),match);}else item.status='not_regular_file';}catch(e){if(job.reason)throw e;if(e.code==='ENOENT'||e.code==='ENOTDIR')item.status='missing';else{item.status='unknown';item.code=['EACCES','EPERM','EIO'].includes(e.code)?e.code:'file_metadata_error';}}}
   const afterCanonical=await fileSystem.realpath(normalized);check();const after=await fileSystem.stat(canonical);check();if(compare(afterCanonical)!==compare(canonical)||!sameFile(directory,after)){row.status='changed_during_read';row.code='directory_changed';for(const match of row.matches)match.flags.push('directory_changed');}
  }catch(e){if(job.reason){row.status=job.reason==='canceled'?'canceled':'deadline';row.code=job.reason;}else if(['ENOENT','ENOTDIR'].includes(e.code)){row.status='missing_directory';row.code=e.code;}else{row.status='unknown';row.code=['EACCES','EPERM','EIO'].includes(e.code)?e.code:'directory_metadata_error';}}}
  const matches=[...found.values()].sort((a,b)=>a.entryIndex-b.entryIndex||a.extensionIndex-b.extensionIndex),firstObservedMatch=matches[0]??null,uncertain=e=>['unresolved','unknown','changed_during_read','canceled','deadline','not_run'].includes(e.status)||e.checks.some(c=>c.status==='unknown'||c.status==='link_not_followed'),priorityHasEarlierUnknown=firstObservedMatch?entries.some(e=>e.index<=firstObservedMatch.entryIndex&&uncertain(e)):entries.some(uncertain),suggestions=[];
  if(matches.length>1)suggestions.push('发现不同路径的同名匹配；先核对首项与预期安装，可使用明确完整路径。需改PATH时请自行复核后操作，本工具不修改。');if(entries.some(e=>e.status==='duplicate_directory'))suggestions.push('快照有重复规范目录，报告保留原顺序并指出首次项；可人工检查冗余，不自动删除。');if(matches.some(c=>c.flags.some(f=>f.includes('placeholder')||f.includes('alias'))))suggestions.push('零字节或WindowsApps位置仅是疑似占位/执行别名提示；实际别名启用状态未知，不据目录名断言无效。');if(priorityHasEarlierUnknown)suggestions.push('前置项/文件检查存在未知，不能保证首个观察匹配为完整PATH优先项；先补查这些项。');if(!matches.length)suggestions.push('本次没有观察到匹配；不代表任何终端都不存在该命令，别名/函数/当前目录或未支持路径仍需人工核对。');suggestions.push('PowerShell还可能先选择别名、函数、cmdlet；本工具未连接当前Shell。Windows扩展名匹配也不验证注册文件关联/执行策略；Unix执行位仅元数据，未验证ACL/挂载/脚本解释器。');
  const report={format:'T072-path-command-report',version:1,jobId:job.id,snapshot:plan,startedAtUTC:beganUTC,completedAtUTC:new Date().toISOString(),elapsedMs:Math.round(performance.now()-begin),reason:job.reason,complete:!job.reason&&entries.every(e=>!['unknown','unresolved','changed_during_read'].includes(e.status)&&!e.checks.some(c=>c.status==='unknown')),entries,matches,distinctMatches:matches.length,firstObservedMatch,priorityHasEarlierUnknown,actualFileChecks,suggestions,scope:'只读明确PATH/PATHEXT快照的有限目录和指定文件元数据；无readdir、递归、文件内容读取、命令/版本执行、PATH/注册表修改。所有候选都未认证可执行性。目录链接规范化后访问，最终候选链接仅lstat不跟随。取消/期限在文件await之间协作检查，不能终止OS文件调用或保证硬10秒。前后目录身份检查是普通变化检测，不锁文件或抵御恶意竞态。Windows拒显式UNC/设备路径，驱动器映射的实际存储本地性未知。'};m.reportText(report,'json');m.reportText(report,'md');return{ok:true,report};
 }finally{clearTimeout(timer);}
 }catch(e){return{ok:false,error:e.message};}finally{if(locked){s.busy=false;s.job=null;}}},cancel(jobId,{senderId}={}){const s=states.get(senderId);if(!s?.job||s.job.id!==jobId)return{ok:true,canceled:false};s.job.reason='canceled';return{ok:true,canceled:true};},disposeSender(id){const s=states.get(id);if(s?.job)s.job.reason='canceled';states.delete(id);}};
}
module.exports={...createHost(),createHost};
