import { h } from '../../core/ui.js';
import { MODEL_VERSION, POLICY, example, audit, prepareStoredState, validateStoredState, reportMarkdown } from './model.mjs';
const KEY='features.L026.state';const STATUS={'not-acquired':'从未获得',held:'持有',released:'已释放'};
const stateText=state=>Object.entries(state).map(([id,status])=>`${id}:${STATUS[status]}`).join('；');
export default{
  id:'L026',
  create(root,ctx={}){
    root.classList.add('feature-l026');let draft=example();let result=null;let selected=0;let filter='all';let timer=null;let destroyed=false;let exporting=false;let restored='';
    try{const raw=ctx.config?.get(KEY);if(raw){const state=validateStoredState(raw);draft={resources:state.resources,entry:state.entry,nodes:state.nodes};restored='已恢复输入草稿；审计结果/路径不保存，请重新审计。';}}catch(error){restored=`草稿未能恢复：${error.message}`;}
    const notice=h('div',{class:'l026-notice',role:'status','aria-live':'polite'},restored);const storage=h('div',{class:'l026-notice',role:'status'});const editor=h('div');const output=h('div',{class:'l026-output'});
    function replace(node,...children){node.replaceChildren(...children.flat(Infinity).filter(child=>child!==null&&child!==undefined&&child!==false));}
    function message(text,error=false){if(!destroyed){notice.textContent=text;notice.classList.toggle('is-error',error);}}
    function persist(){if(timer!==null)clearTimeout(timer);timer=null;if(!ctx.config?.set)return;let state;try{state=prepareStoredState(draft);}catch(error){if(!destroyed)storage.textContent=`${error.message} 当前草稿未写入全局配置，关闭后只能恢复较早草稿；请导出完整JSON。`;return;}if(!destroyed)storage.textContent='';try{Promise.resolve(ctx.config.set(KEY,state)).catch(error=>message(`草稿保存失败：${error.message} 请导出完整JSON。`,true));}catch(error){message(`草稿保存失败：${error.message} 请导出完整JSON。`,true);}}
    function changed(){result=null;selected=0;filter='all';renderOutput();message('输入已改变，旧路径和结论已清空，请重新审计。');if(timer!==null)clearTimeout(timer);timer=setTimeout(persist,250);}
    function load(kind){draft=example(kind);changed();renderEditor();persist();message('示例已载入，请审计全部路径。');}
    function topField(key,label,maxlength){const input=h('input',{class:'field',type:'text',maxlength:String(maxlength),'aria-label':label,oninput:()=>{draft[key]=input.value;changed();}});input.value=draft[key];return h('label',{class:'l026-field'},h('strong',{},label),input);}
    function nodeField(index,key,label,multiline,maxlength){const input=h(multiline?'textarea':'input',{class:'field',...(multiline?{rows:'4',spellcheck:'false'}:{type:'text'}),maxlength:String(maxlength),'aria-label':`节点${index+1}${label}`,oninput:()=>{draft.nodes[index][key]=input.value;changed();}});input.value=draft.nodes[index][key];return input;}
    function add(){if(draft.nodes.length>=12)return;const ids=new Set(draft.nodes.map(node=>node.id));let next=1;while(ids.has(`n${next}`))next++;draft.nodes.push({id:`n${next}`,operations:'Noop',successors:''});changed();renderEditor();message(`已新增n${next}；请连接至入口可达路径，不可达节点会拒绝审计。`);}
    function remove(index){if(draft.nodes.length<=1)return;draft.nodes.splice(index,1);changed();renderEditor();}
    function renderEditor(){replace(editor,h('div',{class:'l026-options'},topField('resources','资源ID列表',128),topField('entry','入口节点ID',12)),h('div',{class:'l026-scroll'},h('table',{},h('caption',{},'每节点1–4条有限操作，每个后继选择形成一条分支'),h('thead',{},h('tr',{},['节点ID','操作（每行一条）','后继ID（空白为叶）','操作'].map(label=>h('th',{scope:'col'},label)))),h('tbody',{},draft.nodes.map((node,index)=>h('tr',{},h('td',{},nodeField(index,'id','ID',false,12)),h('td',{},nodeField(index,'operations','操作',true,512)),h('td',{},nodeField(index,'successors','后继',false,256)),h('td',{},h('button',{class:'btn',disabled:draft.nodes.length===1,onclick:()=>remove(index)},`删除节点${index+1}`))))))),
      h('p',{},'资源1–4，以空格/逗号分隔；ID为1–12位且以英文字母开头。节点1–12、边≤32、路径≤2048。操作：Acquire fh、Use fh、Release fh、Noop、Exit（区分大小写）。Exit仅叶末，所有叶末都隐式统一退出检查。操作文本≤512字节，后继≤256字节，未知/重复/循环/不可达均拒绝。改ID/删行需手动修正入口和引用。'),h('div',{class:'l026-actions'},h('button',{class:'btn',disabled:draft.nodes.length===12,onclick:add},'增加节点'),[['branch','载入分支释放示例'],['errors','载入状态违规示例'],['multi','载入多资源示例']].map(([kind,label])=>h('button',{class:'btn',onclick:()=>load(kind)},label)),h('button',{class:'btn primary',onclick:run},'审计全部路径')));}
    function run(){try{result=audit(draft);selected=0;filter='all';persist();renderOutput();message(`已完整审计${result.total}条路径：泄漏${result.leaking}条，操作违规${result.operationViolationPaths}条。异常后已继续重放至退出。`);}catch(error){result=null;renderOutput();message(error.message,true);}}
    function pick(index){if(!result||!Number.isInteger(index)||index<0||index>=result.paths.length)return;selected=index;renderOutput();}
    function table(headers,rows,caption){return h('div',{class:'l026-scroll'},h('table',{},caption?h('caption',{},caption):null,h('thead',{},h('tr',{},headers.map(label=>h('th',{scope:'col'},label)))),h('tbody',{},rows.map(row=>h('tr',{},row.map(value=>h('td',{},String(value))))))));}
    function renderOutput(){const exports=h('div',{class:'l026-actions'},h('button',{class:'btn',onclick:()=>exportReport('json')},'导出完整 JSON'),h('button',{class:'btn',onclick:()=>exportReport('md')},'导出完整 Markdown'));if(!result){replace(output,h('p',{},'尚无有效审计；编辑图后审计，或导出当前草稿。'),exports);return;}
      const row=result.paths[selected];const selector=h('select',{class:'field','aria-label':'查看路径',onchange:()=>pick(Number(selector.value))},result.paths.map((item,index)=>h('option',{value:String(index)},`#${item.index} ${item.path.join(' → ')} ${item.passed?'通过':'失败'}`)));selector.value=String(selected);
      const filterControl=h('select',{class:'field','aria-label':'路径筛选',onchange:()=>{filter=filterControl.value;renderOutput();}},[['all','全部路径'],['failed','全部失败路径'],['leaks','仅泄漏路径'],['violations','仅操作违规路径']].map(([value,label])=>h('option',{value},label)));filterControl.value=filter;
      const listed=result.paths.filter(item=>filter==='all'||filter==='failed'&&!item.passed||filter==='leaks'&&item.leaks.length||filter==='violations'&&item.violations.length);const shortest=result.shortestFailure;
      replace(output,h('p',{class:'l026-summary'},`完整路径 ${result.total} · 通过 ${result.passed} · 失败 ${result.failed} · 泄漏路径 ${result.leaking} · 操作违规路径 ${result.operationViolationPaths}`),h('p',{},`已审计全部${result.graph.nodes.length}个入口可达节点、${result.graph.edgeCount}条边；无不可达节点被忽略。`),
        h('section',{class:'l026-prefix'},h('h3',{},'模型内最短首次失败前缀'),shortest?h('div',{},h('p',{},`路径#${shortest.pathIndex}，${shortest.step}个操作/检查步骤：${shortest.prefix.operations.join(' → ')}`),h('p',{},shortest.reason),h('button',{class:'btn',onclick:()=>pick(shortest.pathIndex-1)},'查看最短失败路径')):h('p',{},'没有失败前缀。'),h('p',{},result.prefixScope)),
        h('div',{class:'l026-actions'},selector,h('button',{class:'btn',disabled:selected===0,onclick:()=>pick(selected-1)},'上条路径'),h('button',{class:'btn',disabled:selected===result.paths.length-1,onclick:()=>pick(selected+1)},'下条路径')),
        h('h3',{},`当前路径#${row.index}：${row.path.join(' → ')} · ${row.passed?'通过':'失败'}`),h('p',{class:row.leaks.length?'l026-warning':''},`退出泄漏：${row.leaks.join('、')||'无'}；操作违规：${row.violations.length}次；首次失败步骤：${row.firstFailureStep??'无'}。`),h('p',{},`最终资源状态：${stateText(row.final)}`),table(['步骤/节点','操作','状态前','状态后','违规/说明'],row.trace.map(step=>[`${step.step} ${step.node}${step.operationIndex===null?'#退出检查':`#${step.operationIndex}`}`,step.instruction,stateText(step.before),stateText(step.after),`${step.type?step.type+'：':''}${step.reason}`]),'包含全部后续操作与统一退出检查；出错未停止或悄悄释放'),
        h('details',{open:true},h('summary',{},`全部根到叶路径（当前列出${listed.length}条）`),filterControl,h('p',{},'筛选只影响清单，统计和导出仍是全部路径。'),h('div',{class:'l026-path-list'},listed.length?h('table',{},h('thead',{},h('tr',{},['查看','完整节点路径','退出泄漏资源','操作违规次数','结论'].map(label=>h('th',{scope:'col'},label)))),h('tbody',{},listed.map(item=>h('tr',{},h('td',{},h('button',{class:'btn',onclick:()=>pick(item.index-1)},`查看路径${item.index}`)),h('td',{},item.path.join(' → ')),h('td',{},item.leaks.join('、')||'无'),h('td',{},String(item.violations.length)),h('td',{},item.passed?'通过':'失败'))))):h('p',{},'筛选下没有路径。'))),exports);
    }
    async function exportReport(extension){if(exporting)return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message('当前基础层缺少防覆盖导出能力，请升级后导出。',true);return;}exporting=true;try{const payload={feature:'L026',schemaVersion:1,modelVersion:MODEL_VERSION,exportedAt:new Date().toISOString(),draft:JSON.parse(JSON.stringify(draft)),selected,result};const response=await files.saveText({content:extension==='json'?JSON.stringify(payload,null,2):reportMarkdown(payload),extension,defaultName:`L026-resource-paths.${extension}`,copyOnly:true});message(response?.ok===true?'已导出新副本，包含完整输入、全部路径与资源状态/首次失败前缀。':response?.canceled===true?'已取消导出，草稿和审计保留。':`导出失败：${response?.error||'未确认保存成功'}`,response?.ok!==true&&response?.canceled!==true);}catch(error){message(`导出失败：${error.message}`,true);}finally{exporting=false;}}
    root.replaceChildren(h('link',{rel:'stylesheet',href:new URL('./style.css',import.meta.url).href}),h('h2',{},'资源生命周期审计'),h('p',{},'用有限分支图检查抽象文件句柄；首次状态违规与路径末泄漏分别报告。'),notice,storage,h('details',{},h('summary',{},'状态规则与保存范围'),h('p',{},POLICY),h('p',{},'资源状态为not-acquired/held/released。重复Acquire保持原held，不新增句柄；非法Use/Release保持状态但记录违规，后续操作继续。合法Release转released，之后Acquire允许开启新生命周期。从未获得的资源不算泄漏。'),h('p',{},'所有叶末统一检查，Exit仅是叶末标记，不能出现在中间节点或跳过后续操作。根到叶路径全部审计，不假定有异常就停止。无真实句柄、源扫描或运行时调试。'),h('p',{},'配置仅存schemaVersion=1输入草稿，JSON≤64KiB UTF-8且字段另有限额；路径和结论需重算。切走清保存计时器，无后台执行。')),editor,output);renderEditor();renderOutput();return{activate(){},deactivate(){persist();},destroy(){if(destroyed)return;persist();destroyed=true;root.replaceChildren();root.classList.remove('feature-l026');}};
  },
};
