export const LIMITS=Object.freeze({imagePixels:4194304,totalPixels:16777216,maxEdge:4096,jpegBytes:2097152});
export function jpegInfo(bytes){
 if(!(bytes instanceof Uint8Array)||bytes.length<4||bytes.length>LIMITS.jpegBytes||bytes[0]!==255||bytes[1]!==216)throw Error('JPEG_FORMAT');let at=2,frame=null,scan=false,jfif=false;
 while(at<bytes.length){if(bytes[at++]!==255)throw Error('JPEG_MARKER');while(bytes[at]===255)at++;const marker=bytes[at++];if(marker===217){if(!frame||!scan||!jfif||at!==bytes.length)throw Error('JPEG_END');return frame;}if(marker===0||marker===216||marker>=208&&marker<=215)throw Error('JPEG_MARKER');if(at+2>bytes.length)throw Error('JPEG_LENGTH');const len=bytes[at]*256+bytes[at+1],start=at+2,end=at+len;if(len<2||end>bytes.length)throw Error('JPEG_LENGTH');
 if(marker>=192&&marker<=207&&![196,200,204].includes(marker)){if(marker!==192||frame||len!==17)throw Error('JPEG_BASELINE_RGB_ONLY');const bits=bytes[start],height=bytes[start+1]*256+bytes[start+2],width=bytes[start+3]*256+bytes[start+4],components=bytes[start+5];if(bits!==8||components!==3||bytes[start+6]!==1||bytes[start+9]!==2||bytes[start+12]!==3||width<1||height<1||width>4096||height>4096||width*height>4194304)throw Error('JPEG_PIXELS_OR_COMPONENTS');frame={width,height,components,bits};}
 if(marker===224&&len>=16&&String.fromCharCode(...bytes.slice(start,start+5))==='JFIF\0')jfif=true;
 if(marker===225&&String.fromCharCode(...bytes.slice(start,start+4))==='Exif'||marker===226&&String.fromCharCode(...bytes.slice(start,start+11))==='ICC_PROFILE'||marker===238)throw Error('JPEG_COLOR_OR_ORIENTATION_UNSUPPORTED');
 if(marker===218){if(!frame||scan||len!==12||bytes[start]!==3||bytes[end-3]!==0||bytes[end-2]!==63||bytes[end-1]!==0)throw Error('JPEG_SINGLE_BASELINE_SCAN');scan=true;at=end;while(at<bytes.length){if(bytes[at++]!==255)continue;while(bytes[at]===255)at++;const v=bytes[at];if(v===0||v>=208&&v<=215){at++;continue;}at-=1;while(bytes[at-1]===255)at--;break;}continue;}at=end;
 }throw Error('JPEG_NO_END');
}
export function dimensions(width,height,maxEdge){const scale=Math.min(1,maxEdge/Math.max(width,height));return{width:Math.max(1,Math.round(width*scale)),height:Math.max(1,Math.round(height*scale))};}
export async function encodeJPEG(bytes,requested){let bitmap,canvas;try{bitmap=await createImageBitmap(new Blob([bytes],{type:'image/jpeg'}),{imageOrientation:'none',premultiplyAlpha:'none',colorSpaceConversion:'none'});if(bitmap.width!==requested.sourceWidth||bitmap.height!==requested.sourceHeight)throw Error('DECODER_DIMENSIONS');canvas=new OffscreenCanvas(requested.width,requested.height);const context=canvas.getContext('2d',{alpha:false,colorSpace:'srgb'});if(!context)throw Error('CANVAS_UNAVAILABLE');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(bitmap,0,0,requested.width,requested.height);const blob=await canvas.convertToBlob({type:'image/jpeg',quality:requested.quality});if(blob.type!=='image/jpeg'||blob.size>2097152)throw Error('ENCODER_TYPE_OR_BYTES');return stripEncoderICC(new Uint8Array(await blob.arrayBuffer()));}finally{bitmap?.close();if(canvas)canvas.width=canvas.height=1;}}
export function stripEncoderICC(bytes){if(!(bytes instanceof Uint8Array)||bytes.length<4||bytes.length>2097152||bytes[0]!==255||bytes[1]!==216)throw Error('ENCODER_JPEG');const chunks=[bytes.subarray(0,2)];let at=2,removed=0;while(at<bytes.length){const begin=at;if(bytes[at++]!==255)throw Error('ENCODER_MARKER');while(bytes[at]===255)at++;const marker=bytes[at++];if(marker===218){chunks.push(bytes.subarray(begin));break;}if(marker===217||marker===0||at+2>bytes.length)throw Error('ENCODER_MARKER');const length=bytes[at]*256+bytes[at+1],end=at+length;if(length<2||end>bytes.length)throw Error('ENCODER_LENGTH');const start=at+2;if(marker===226&&String.fromCharCode(...bytes.slice(start,start+12))==='ICC_PROFILE\0'){if(++removed>16)throw Error('ENCODER_ICC_COUNT');}else chunks.push(bytes.subarray(begin,end));at=end;}const total=chunks.reduce((n,b)=>n+b.length,0),out=new Uint8Array(total);let offset=0;for(const b of chunks){out.set(b,offset);offset+=b.length;}return out;}
