import{PDFDocument,PDFName,PDFDict,PDFArray,PDFNumber,PDFBool,PDFRawStream,PDFStream,EncryptedPDFError,ParseSpeeds}from'./vendor/pdf-lib.esm.min.mjs';
import{jpegInfo,dimensions,encodeJPEG}from'./codec.mjs';
export const LIMITS=Object.freeze({sourceBytes:2097152,outputBytes:2097152,pages:16,objects:3000,images:64,totalPixels:16777216,workerMs:30000,reportBytes:2097152});
export const PROFILES=Object.freeze({high:{maxEdge:1600,quality:0.85},medium:{maxEdge:1000,quality:0.65},low:{maxEdge:600,quality:0.45}});
const N=PDFName.of,enc=new TextEncoder(),fail=code=>{const e=new Error('PDF结构/图像/容量不支持');e.code=code;throw e;},check=o=>{if(o.signal?.aborted||o.isCanceled?.())fail('canceled');};
export async function sha(bytes){return[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export function settings(s){if(!s||typeof s!=='object'||Array.isArray(s)||Object.keys(s).sort().join('|')!=='profile|targetBytes'||!Object.hasOwn(PROFILES,s.profile)||!Number.isSafeInteger(s.targetBytes)||s.targetBytes<1024||s.targetBytes>2097152)fail('settings');return{...s};}
const num=(d,k)=>{const v=d.lookup(N(k));return v instanceof PDFNumber?v.asNumber():undefined;};
const nameOf=(d,k)=>{const v=d.lookup(N(k));return v instanceof PDFName?v.decodeText():null;};
function filterName(dict){const f=dict.lookup(N('Filter'));if(f instanceof PDFName)return f.decodeText();if(f instanceof PDFArray&&f.size()===1){const v=f.lookup(0);return v instanceof PDFName?v.decodeText():'unsupported';}return'unsupported';}
async function contents(page){const raw=page.node.Contents(),items=raw instanceof PDFArray?raw.asArray():raw?[raw]:[];if(items.length>100)fail('page_content_count');const rows=[];for(const r of items){const s=page.doc.context.lookup(r);if(!(s instanceof PDFStream))fail('page_content_structure');rows.push({bytes:s.getContents().length,sha256:await sha(s.getContents())});}return rows;}
async function pageRows(doc){const rows=[];for(const[p,page]of doc.getPages().entries()){const media=page.getMediaBox(),crop=page.getCropBox(),rotation=page.getRotation().angle;if(![...Object.values(media),...Object.values(crop),rotation].every(Number.isFinite)||media.width<=0||media.height<=0||crop.width<=0||crop.height<=0||rotation%90)fail('page_geometry');rows.push({page:p+1,mediaBox:media,cropBox:crop,rotation,contentStreams:await contents(page)});}return rows;}
function images(doc,objects){const rows=[],map=new Map();for(const[ref,obj]of objects)if(obj instanceof PDFStream&&obj.dict.lookupMaybe(N('Subtype'),PDFName)?.decodeText()==='Image'){const row={ref,stream:obj,id:ref.toString(),uses:[]};rows.push(row);map.set(obj,row);}let nodes=0;function walk(resources,page,path,depth,stack){if(!resources)return;if(depth>8||++nodes>512||stack.has(resources))fail('resource_depth_or_cycle');stack.add(resources);const x=resources.lookupMaybe(N('XObject'),PDFDict);if(x){if(x.keys().length>128)fail('xobject_count');for(const k of x.keys()){const obj=x.context.lookup(x.get(k));if(!(obj instanceof PDFStream))fail('xobject_structure');const kind=obj.dict.lookupMaybe(N('Subtype'),PDFName)?.decodeText();if(kind==='Image'){let row=map.get(obj);if(!row){row={ref:null,stream:obj,id:'direct-'+(rows.length+1),uses:[]};rows.push(row);map.set(obj,row);}if(row.uses.length>=256)fail('image_use_count');row.uses.push({page,path:path+'/'+k.decodeText()});}else if(kind==='Form')walk(obj.dict.lookupMaybe(N('Resources'),PDFDict),page,path+'/'+k.decodeText(),depth+1,stack);}}stack.delete(resources);}for(const[p,page]of doc.getPages().entries())walk(page.node.Resources(),p+1,'/XObject',0,new Set());if(rows.length>64)fail('image_count');return rows;}
function eligible(row){const d=row.stream.dict;if(!row.ref||!(row.stream instanceof PDFRawStream))return'direct_or_nonraw_preserved';if(!row.uses.length)return'not_referenced_by_page_preserved';if(nameOf(d,'ColorSpace')!=='DeviceRGB'||num(d,'BitsPerComponent')!==8||filterName(d)!=='DCTDecode')return'only_single_DCT_8bit_DeviceRGB_supported';for(const key of['Mask','SMask','Decode','DecodeParms','SMaskInData','Alternates','OPI','Intent','Metadata'])if(d.has(N(key)))return'unsupported_image_'+key;if(d.has(N('ImageMask'))&&d.lookup(N('ImageMask'))!==PDFBool.False)return'image_mask_preserved';const keys=new Set(['Type','Subtype','Width','Height','ColorSpace','BitsPerComponent','Filter','Length','Name','Interpolate','ImageMask']);if(d.keys().some(k=>!keys.has(k.decodeText())))return'unknown_image_dictionary_preserved';return null;}
export async function compress(bytes,name,raw,options={}){
 const rule=settings(raw);if(!(bytes instanceof Uint8Array)||bytes.length<8||bytes.length>2097152||new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-'||typeof name!=='string'||!name||name.length>240||/[\x00-\x1f\x7f]/.test(name))fail('source');check(options);let doc;try{doc=await PDFDocument.load(bytes.slice(),{ignoreEncryption:false,updateMetadata:false,throwOnInvalidObject:true,parseSpeed:ParseSpeeds.Slow});}catch(e){if(e instanceof EncryptedPDFError||e?.message===new EncryptedPDFError().message)fail('encrypted_unsupported');fail('pdf_parse');}check(options);const objects=doc.context.enumerateIndirectObjects();if(objects.length>3000||doc.getPageCount()<1||doc.getPageCount()>16)fail('document_capacity');if(doc.catalog.has(N('AcroForm'))||doc.catalog.has(N('Perms'))||objects.some(([,v])=>v instanceof PDFDict&&(nameOf(v,'FT')==='Sig'||nameOf(v,'Type')==='Sig')))fail('form_or_signature_unsupported');const before=await pageRows(doc),sourceHash=await sha(bytes),all=images(doc,objects),audit=[];let totalPixels=0,changed=0;
 for(const row of all){check(options);const contents=row.stream.getContents(),original={width:num(row.stream.dict,'Width')??null,height:num(row.stream.dict,'Height')??null,bytes:contents.length,sha256:await sha(contents)},item={id:row.id,uses:row.uses,original,status:'preserved_unsupported',reason:eligible(row),candidate:null,applied:false};audit.push(item);if(item.reason)continue;let info;try{info=jpegInfo(contents);}catch(e){item.reason='JPEG_validation_'+String(e.message).replace(/[^A-Z_]/g,'').slice(0,80);continue;}if(info.width!==original.width||info.height!==original.height){item.reason='JPEG_dictionary_dimensions_mismatch';continue;}if(totalPixels+info.width*info.height>16777216){item.reason='total_decode_pixels_budget_preserved';continue;}totalPixels+=info.width*info.height;const target=dimensions(info.width,info.height,PROFILES[rule.profile].maxEdge);let output;try{output=await(options.encodeJPEG||encodeJPEG)(contents,{sourceWidth:info.width,sourceHeight:info.height,...target,quality:PROFILES[rule.profile].quality});}catch{item.reason='JPEG_encoder_failed_preserved';continue;}check(options);let result;try{result=jpegInfo(output);}catch{item.reason='JPEG_encoder_result_invalid_preserved';continue;}if(result.width!==target.width||result.height!==target.height){item.reason='JPEG_encoder_dimensions_invalid_preserved';continue;}item.candidate={width:result.width,height:result.height,bytes:output.length,sha256:await sha(output),quality:PROFILES[rule.profile].quality};check(options);if(output.length>=contents.length){item.status='preserved_no_stream_gain';item.reason='encoded_stream_not_smaller';continue;}const dict=row.stream.dict.clone();dict.set(N('Width'),doc.context.obj(result.width));dict.set(N('Height'),doc.context.obj(result.height));dict.set(N('Filter'),N('DCTDecode'));doc.context.assign(row.ref,PDFRawStream.of(dict,output.slice()));item.status='candidate_reencoded';item.reason=null;changed++;
 }
 check(options);let candidate=changed?await doc.save({useObjectStreams:false,updateFieldAppearances:false,addDefaultPage:false,objectsPerTick:20}):bytes.slice();check(options);const after=await pageRows(doc);if(JSON.stringify(before)!==JSON.stringify(after))fail('page_content_or_geometry_changed');const reduced=candidate.length<bytes.length,chosen=reduced?candidate:bytes.slice();if(chosen.length>2097152)fail('output_capacity');for(const i of audit)if(i.status==='candidate_reencoded'){i.applied=reduced;i.status=reduced?'reencoded':'preserved_whole_pdf_no_gain';}const outputHash=await sha(chosen);check(options);
 const report={format:'T026-pdf-image-compression',version:1,source:{name,bytes:bytes.length,sha256:sourceHash},settings:rule,profile:PROFILES[rule.profile],output:{path:'compressed.pdf',bytes:chosen.length,sha256:outputHash,savedBytes:bytes.length-chosen.length,reductionPercent:Math.round((bytes.length-chosen.length)/bytes.length*10000)/100,targetMet:chosen.length<=rule.targetBytes,kind:reduced?'image-compressed-copy':'original-copy-no-gain',candidateBytes:candidate.length},pages:before,images:audit,imagesApplied:audit.filter(i=>i.applied).length,imagesPreserved:audit.filter(i=>!i.applied).length,preview:{status:'pending',manualQuality:'not-confirmed'},scope:'只重编码有限JPEG图像流，文字/向量页内容流与几何摘要相同；非全页栅格化。不重算文本或保证目标体积/无视觉损失，不支持图像保留原流，序列化会改变PDF容器字节。'};reportText(report);return{bytes:chosen,report};
}
export function reportText(report){const text=JSON.stringify(report,null,2)+'\n';if(enc.encode(text).length>2097152)fail('report_capacity');return text;}
function base64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
export async function bundle(result){if(!result||result.report.preview.status!=='all-source-and-output-pages-rendered')fail('preview_required');const report=enc.encode(reportText(result.report));return{copyOnly:true,defaultName:'PDF图像压缩副本',files:[{path:'compressed.pdf',base64:base64(result.bytes),sha256:await sha(result.bytes)},{path:'report.json',base64:base64(report),sha256:await sha(report)}]};}
