import {h} from '../../core/ui.js';
import {LIMITS,parseXML,namespaceMap,query,markdown} from './model.mjs';
export default{id:'T007',create(root){let parsed=null,report=null,alive=true,active=true,ticket=0,busy=false;const status=h('p',{role:'status',class:'t007-status'}),summary=h('div'),output=h('div'),files=window.toolbox?.files;const safe=()=>files?.saveTextSupportsCopyOnly===true&&typeof files.saveText==='function',say=v=>{if(alive)status.textContent=v;},button=(v,fn)=>h('button',{class:'btn',type:'button',onclick:()=>{if(alive&&active&&!busy)fn();}},v);
 const invalidate=(drop=false)=>{ticket++;report=null;output.replaceChildren();if(drop){parsed=null;summary.replaceChildren();}say(drop?'源文本已更改，请重新解析。':'查询已改变，请重新运行。');};
 const source=h('textarea',{rows:10,maxlength:LIMITS.input,'aria-label':'XML源文本',oninput:()=>invalidate(true)}),expression=h('input',{'aria-label':'XPath查询',maxlength:1024,oninput:()=>invalidate(false)});expression.value='//item[@price > 10]';const namespace=h('textarea',{rows:2,maxlength:4096,'aria-label':'命名空间别名JSON',oninput:()=>invalidate(false)});namespace.value='{}';
 const file=h('input',{type:'file',accept:'.xml,.svg,.txt','aria-label':'读取本地XML文件',onchange:async()=>{const selected=file.files?.[0];file.value='';if(!selected||!alive||!active)return;invalidate(true);const t=ticket;try{if(selected.size>LIMITS.input||typeof selected.arrayBuffer!=='function')throw Error('只读取≤1MiB的文件。');const buffer=await selected.arrayBuffer();if(!alive||!active||t!==ticket)return;let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch{throw Error('仅支持严格UTF-8文本，不猜测其他编码。');}source.value=text;say('文件已读入内存，请解析；未写源文件或全局配置。');}catch(e){if(t===ticket)say('读取失败：'+e.message);}}});
 function parse(){invalidate(true);try{parsed=parseXML(source.value);summary.replaceChildren(h('p',{},`解析成功：${parsed.stats.elements}元素、${parsed.stats.attributes}属性、${parsed.stats.nodes}总节点。最大DOM深度${parsed.stats.maxDepth}。`),h('details',{},h('summary',{},'节点路径预览（前100项，完整树见JSON报告）'),h('pre',{},parsed.stats.tree.slice(0,100).map(n=>n.path).join('\n'))));say('解析成功，请设置XPath和命名空间别名再查询。');}catch(e){say('解析失败：'+e.message);}}
 function run(){invalidate(false);if(!parsed){say('请先解析XML。');return;}try{report=query(parsed,expression.value,namespaceMap(namespace.value));output.replaceChildren(h('h3',{},report.result.kind==='nodes'?`匹配 ${report.result.count} 个节点`:`标量结果 ${report.result.kind}`),h('p',{},report.policy),report.result.kind==='nodes'?h('div',{},report.result.nodes.map(n=>h('section',{class:'t007-node'},h('strong',{},n.path),h('p',{},`${n.name} · DOM类型${n.type}`),h('pre',{},n.serialized)))):h('pre',{},String(report.result.value)),...['json','md'].map(ext=>{const b=button(`保存 ${ext.toUpperCase()} 查询报告副本`,()=>save(ext));b.disabled=!safe();return b;}));say('查询完成，尚未保存。');}catch(e){say('查询失败：'+e.message);}}
 async function save(extension){if(!report||!safe()||busy)return;busy=true;const snapshot=report;try{const r=await files.saveText({content:extension==='json'?JSON.stringify(snapshot,null,2):markdown(snapshot),extension,defaultName:`T007-xpath-report.${extension}`,copyOnly:true});say(r?.ok===true?'已保存报告新副本。':r?.canceled?'已取消保存。':'保存失败：'+(r?.error||'未确认成功'));}catch(e){say(e.message);}finally{busy=false;}}
 const sample=()=>{invalidate(true);source.value='<catalog><item id="A" price="8">茶</item><item id="B" price="20">书</item><item id="C" price="12">笔</item></catalog>';expression.value='//item[@price > 10]';namespace.value='{}';parse();};
 root.replaceChildren(h('section',{class:'t007'},h('link',{rel:'stylesheet',href:new URL('./style.css',import.meta.url).href}),h('h2',{},'XML 数据查询台'),h('p',{},'本地原生XML/XPath 1.0；DTD、实体和处理指令预先拒绝。输入不插入活动页面，不执行源HTML/SVG，不加载外部资源。'),status,file,source,button('载入三条商品示例',sample),button('解析 XML',parse),summary,h('label',{},'XPath',expression),h('label',{},'前缀→URI（默认命名空间也需自定义前缀）',namespace),button('运行 XPath 查询',run),button('清空源与结果',()=>{source.value='';invalidate(true);say('源文档和结果已清空。');}),output,h('p',{},'≤1MiB UTF-8、5000 DOM节点（含属性/文本）、32层、500匹配。单匹配64KiB、结果2MiB、完整报告8MiB；超限明确拒绝不截断。源码仅当前面板内存，不写配置。XML解析及XPath同步执行，复杂查询不能中途取消，请缩小输入/查询；后台文件读取结果以世代隔离，暂停/销毁后丢弃。默认命名空间查询示例 //c:item 配合 {"c":"urn:catalog"}。')));
 return{activate(){active=true;},deactivate(){active=false;ticket++;},destroy(){alive=false;active=false;ticket++;parsed=null;report=null;source.value='';root.replaceChildren();}};
}};
