// Private finite process/path/job foundation privately adapted from T044; no runtime cross-feature import.
'use strict';
const fs = require('node:fs'), fsp = fs.promises, path = require('node:path'), os = require('node:os');
const { spawn } = require('node:child_process'), { randomUUID, createHash } = require('node:crypto'), { pathToFileURL } = require('node:url');
const model = import(pathToFileURL(path.join(__dirname, 'model.mjs')).href);
const DEFAULT_ENGINE = 'C:\\ruanjian\\ffmpeg\\bin';
const fail = code => { throw Object.assign(new Error(code), { code }); };
const codeOf = e => /^[A-Z0-9_]{1,64}$/.test(e?.code || '') ? e.code : 'LOCAL_OPERATION_FAILED';
function shape(value, keys) { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).sort().join('|') !== [...keys].sort().join('|')) fail('INVALID_PAYLOAD'); }
function localPath(p) { if (typeof p !== 'string' || p.length > 240 || !/^[A-Za-z]:\\/.test(p) || p !== path.win32.normalize(p) || p.normalize('NFC') !== p || /[\x00-\x1f\x7f]/.test(p) || p.slice(3).split('\\').some(x => !x || /[<>:"|?*]/.test(x) || /[. ]$/.test(x) || /^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(x))) fail('UNSUPPORTED_PATH'); return p; }
function same(a, b) { return a.dev === b.dev && a.ino === b.ino && a.size === b.size && a.mtimeMs === b.mtimeMs && a.ctimeMs === b.ctimeMs; }
async function ordinary(p, directory = false) {
  localPath(p); let walk = path.parse(p).root;
  for (const item of p.slice(walk.length).split(path.sep)) { walk = path.join(walk, item); const s = await fsp.lstat(walk); if (s.isSymbolicLink() || (!s.isDirectory() && walk !== p) || walk === p && !(directory ? s.isDirectory() : s.isFile())) fail('LINK_OR_NONREGULAR_UNSUPPORTED'); const real = await fsp.realpath(walk); if (real.toLowerCase() !== walk.toLowerCase()) fail('LINK_OR_NONREGULAR_UNSUPPORTED'); }
  return fsp.lstat(p);
}
function electronDialog(kind,senderId){const{dialog,BrowserWindow,webContents}=require('electron'),owner=BrowserWindow.fromWebContents(webContents.fromId(senderId));if(kind==='engine')return dialog.showOpenDialog(owner,{title:'选择可信FFmpeg 6.x目录（固定ffmpeg.exe/ffprobe.exe）',properties:['openDirectory']});if(kind==='source')return dialog.showOpenDialog(owner,{title:'选择1个本机PCM WAV（每个≤128MiB）',properties:['openFile'],filters:[{name:'PCM WAV',extensions:['wav']}]});return dialog.showSaveDialog(owner,{title:'新建完整裁剪副本目录（已有目标拒绝）',defaultPath:'T045-trim-copy'});}
function createHost(deps = {}) {
  const launch = deps.spawn || spawn, choose = deps.choose || electronDialog, defaultEngine = deps.defaultEngine || DEFAULT_ENGINE, tempRoot = deps.tempRoot || os.tmpdir(), platform = deps.platform || process.platform;
  const states = new Map(); let children = 0;
  function state(ctx) { if (!Number.isSafeInteger(ctx?.senderId) || ctx.senderId < 1) fail('INVALID_SENDER'); if (!states.has(ctx.senderId)) { if (states.size >= 16) fail('SENDER_LIMIT'); states.set(ctx.senderId, { disposed: false, busy: false, job: null, seen: new Map(), intents: new Map(), engine: null, source: null, plan: null, result: null, expiry: null }); } const s = states.get(ctx.senderId); if (s.disposed) fail('SENDER_DESTROYED'); return s; }
  function reserve(s, id) { if (typeof id !== 'string' || !/^[-A-Za-z0-9_]{12,64}$/.test(id)) fail('INVALID_JOB_ID'); if (s.busy) fail('JOB_BUSY'); if (s.seen.has(id)) fail('DUPLICATE_JOB_ID'); if (s.seen.size >= 512) fail('JOB_LIMIT_REOPEN_WINDOW'); const job = { id, reason: s.intents.delete(id) ? 'CANCELED' : null, child: null }; s.seen.set(id, true); s.busy = true; s.job = job; return job; }
  function guard(s, j) { if (s.disposed || j.reason) fail(j.reason || 'CANCELED');if(j.deadline&&Date.now()>j.deadline)fail('BATCH_DEADLINE'); }
  function stop(j, reason) { j.reason ||= reason; if (j.child) { try { j.child.kill(); } catch {} } }
  async function clearResult(s) { clearTimeout(s.expiry); s.expiry = null; const r = s.result; s.result = null; if(r)try{await cleanTemp(r.dir);}catch{r.previewConfirmed=false;s.result=r;throw Object.assign(Error('TEMP_CLEANUP_FAILED'),{code:'TEMP_CLEANUP_FAILED',partialPath:r.dir});} }
  async function cleanTemp(dir) { if (path.dirname(dir) !== path.resolve(tempRoot) || !/^T045-[A-Za-z0-9_-]+$/.test(path.basename(dir))) fail('TEMP_SCOPE'); const stat = await fsp.lstat(dir).catch(e => { if (e.code === 'ENOENT') return null; throw e; }); if (!stat) return; if (!stat.isDirectory() || stat.isSymbolicLink() || (await fsp.realpath(dir)).toLowerCase() !== dir.toLowerCase()) fail('TEMP_IDENTITY'); for (const name of await fsp.readdir(dir)) { if (name !== 'trimmed-01.wav') fail('TEMP_UNKNOWN_FILE'); const p = path.join(dir, name), t = await fsp.lstat(p); if (!t.isFile() || t.isSymbolicLink()) fail('TEMP_IDENTITY'); await fsp.unlink(p); } await fsp.rmdir(dir); }
  async function hashFile(p, s, j, limit) { const before = await ordinary(p); if (before.size < 1 || before.size > limit) fail('FILE_SIZE_LIMIT'); const fd = await fsp.open(p, 'r'); const hash = createHash('sha256'); const chunk = Buffer.alloc(262144); let size = 0; try { if (!same(before, await fd.stat())) fail('SOURCE_CHANGED'); for (;;) { guard(s, j); const { bytesRead } = await fd.read(chunk, 0, chunk.length, null); guard(s, j); if (!bytesRead) break; size += bytesRead; if (size > limit) fail('FILE_SIZE_LIMIT'); hash.update(chunk.subarray(0, bytesRead)); } if (size !== before.size || !same(before, await fd.stat()) || !same(before, await ordinary(p))) fail('SOURCE_CHANGED'); return { identity: before, bytes: size, sha256: hash.digest('hex') }; } finally { await fd.close(); } }
  async function checkSource(s,j) { if(!s.source)fail('SOURCE_NOT_SELECTED'); for(const f of s.source.files){const h=await hashFile(f.path,s,j,128*1024*1024);if(!same(h.identity,f.identity)||h.sha256!==f.sha256)fail('SOURCE_CHANGED');} }
  async function selectEngine(dir) { await ordinary(dir, true); const files = {}; for (const name of ['ffmpeg', 'ffprobe']) { const p = path.join(dir, name + '.exe'); const identity = await ordinary(p); if (identity.size < 1 || identity.size > 256 * 1024 * 1024) fail('ENGINE_SIZE_LIMIT'); files[name] = { path: p, identity }; } return { token: randomUUID(), directory: dir, files, confirmed: false }; }
  async function engineFile(s, kind) { if (!s.engine) fail('ENGINE_NOT_SELECTED'); const f = s.engine.files[kind]; if (!same(f.identity, await ordinary(f.path))) fail('ENGINE_CHANGED'); return f.path; }
  function runProcess(s, j, exe, args, timeoutMs, outputFile = null, captureLog = false, outputLimit = 1024 * 1024) {
    return new Promise((resolve, reject) => {
      guard(s, j); if (children >= 4) { reject(Object.assign(new Error(), { code: 'PROCESS_LIMIT' })); return; }
      let child, total = 0, out = [], timer, grace, poll, done = false, spawnError = false;
      const close = exit => { clearTimeout(timer); clearTimeout(grace); clearInterval(poll); j.child = null; children--; if (done) { if (s.job === j) { s.busy = false; s.job = null; } return; } done = true; if (j.reason) reject(Object.assign(new Error(), { code: j.reason })); else if (spawnError || exit !== 0) reject(Object.assign(new Error(), { code: spawnError ? 'ENGINE_UNAVAILABLE' : 'ENGINE_PROCESS_FAILED' })); else resolve(Buffer.concat(out).toString('utf8')); };
      const kill = reason => { stop(j, reason); if (!grace) grace = setTimeout(() => { if (!done) { done = true; reject(Object.assign(new Error(), { code: 'PROCESS_TERMINATION_PENDING' })); } }, 5000); };
      try { const env = { SystemRoot: process.env.SystemRoot || 'C:\\Windows', WINDIR: process.env.WINDIR || 'C:\\Windows', TEMP: os.tmpdir(), TMP: os.tmpdir(), PATH: 'C:\\Windows\\System32' }; child = launch(exe, args, { shell: false, windowsHide: true, cwd: path.dirname(exe), env, stdio: ['ignore', 'pipe', 'pipe'] }); j.child = child; children++; child.on('error', () => { spawnError = true; }); child.once('close', close); child.stdout.on('data', b => { total += b.length; if (total > 131072) kill('ENGINE_OUTPUT_LIMIT'); else out.push(b); }); child.stderr.on('data', b => { total += b.length; if (total > 131072) kill('ENGINE_OUTPUT_LIMIT'); else if(captureLog)out.push(b); }); timer = setTimeout(() => kill(j.deadline && Date.now()>=j.deadline ? 'BATCH_DEADLINE' : 'PROCESS_DEADLINE'), Math.min(timeoutMs,j.deadline ? Math.max(1,j.deadline-Date.now()) : timeoutMs)); if (outputFile) poll = setInterval(() => { try { if (fs.statSync(outputFile).size >= outputLimit) kill('OUTPUT_SIZE_LIMIT'); } catch {} }, 100); if (j.reason) kill(j.reason); } catch { if (child) kill('ENGINE_UNAVAILABLE'); else reject(Object.assign(new Error(), { code: 'ENGINE_UNAVAILABLE' })); }
    });
  }
  async function waveFile(p,s,j,m){const total=(await ordinary(p)).size,fd=await fsp.open(p,'r');try{return await m.readWave(async(at,n)=>{guard(s,j);const b=Buffer.alloc(n);if((await fd.read(b,0,n,at)).bytesRead!==n)fail('SOURCE_CHANGED');return new Uint8Array(b.buffer,b.byteOffset,b.byteLength);},total);}finally{await fd.close();}}
  async function probe(s,j,p,wave,m){return m.parseProbe(await runProcess(s,j,await engineFile(s,'ffprobe'),m.probeArgs(p),5000),wave);}
  async function exportResult(s,j,senderId,m){const r=s.result;if(!r?.previewConfirmed)fail('COMPLETE_PREVIEW_REQUIRED');const picked=await choose('save',senderId);guard(s,j);if(picked.canceled)return{ok:false,canceled:true};const target=localPath(picked.filePath);await ordinary(path.dirname(target),true);for(const f of r.files){const h=await hashFile(f.path,s,j,m.LIMITS.outputBytes);if(!same(h.identity,f.identity)||h.sha256!==f.sha256)fail('OUTPUT_CHANGED');}await checkSource(s,j);guard(s,j);let identity=null,createdDirectory=false;const created=[];
   try{await fsp.mkdir(target);createdDirectory=true;identity=await fsp.lstat(target);const manifest=[];for(const f of r.files){guard(s,j);const p=path.join(target,f.name);await fsp.copyFile(f.path,p,fs.constants.COPYFILE_EXCL);created.push(f.name);const h=await hashFile(p,s,j,m.LIMITS.outputBytes);if(h.sha256!==f.sha256)fail('COPY_VERIFY_FAILED');manifest.push({path:f.name,bytes:h.bytes,sha256:h.sha256});}const report={...r.report,export:{copyOnly:true,targetDirectory:target,completePreviewAcknowledged:true,creation:'exclusive new directory / COPYFILE_EXCL / report wx; no crash transaction'}};const text=JSON.stringify(report,null,2);if(Buffer.byteLength(text)>262144)fail('REPORT_LIMIT');await fsp.writeFile(path.join(target,'trim-report.json'),text,{flag:'wx',encoding:'utf8'});created.push('trim-report.json');manifest.push({path:'trim-report.json',bytes:Buffer.byteLength(text),sha256:createHash('sha256').update(text).digest('hex')});guard(s,j);await checkSource(s,j);return{ok:true,copyOnly:true,path:target,files:manifest};}
   catch(e){if(!identity)return{ok:false,code:e.code==='EEXIST'?'TARGET_EXISTS':codeOf(e),...(createdDirectory?{partialPath:target,cleanup:'manual-review-required'}:{})};let clean=true;try{const t=await fsp.lstat(target);if(t.dev!==identity.dev||t.ino!==identity.ino||t.isSymbolicLink()||(await fsp.realpath(target)).toLowerCase()!==target.toLowerCase())fail('CLEANUP_IDENTITY');const names=await fsp.readdir(target);if(names.some(n=>!created.includes(n)))fail('CLEANUP_UNKNOWN');for(const n of names){const p=path.join(target,n),t=await fsp.lstat(p);if(!t.isFile()||t.isSymbolicLink())fail('CLEANUP_IDENTITY');await fsp.unlink(p);}await fsp.rmdir(target);}catch{clean=false;}return{ok:false,code:codeOf(e),...(e.code==='CANCELED'?{canceled:true}:{}),...(clean?{cleanup:'created-directory-removed'}:{partialPath:target,cleanup:'manual-review-required'})};}
  }

  async function scan(s,j,p,wave,config,m){const fd=await fsp.open(p,'r');try{return await m.scanPCM(async(at,n)=>{guard(s,j);const b=Buffer.alloc(n);const got=await fd.read(b,0,n,at);return new Uint8Array(b.buffer,b.byteOffset,got.bytesRead);},wave,config,()=>guard(s,j),()=>new Promise(r=>setImmediate(r)));}finally{await fd.close();}}
  async function comparePCM(s,j,source,out,wave,output,selection){const a=await fsp.open(source,'r'),b=await fsp.open(out,'r');let dst=output.dataOffset,bytes=0;try{for(const k of selection.keep){let at=wave.dataOffset+k.startFrame*wave.blockAlign,left=(k.endFrame-k.startFrame)*wave.blockAlign;while(left){guard(s,j);const n=Math.min(262144,left),x=Buffer.alloc(n),y=Buffer.alloc(n);if((await a.read(x,0,n,at)).bytesRead!==n||(await b.read(y,0,n,dst)).bytesRead!==n||!x.equals(y))fail('OUTPUT_PCM_NOT_EXACT');at+=n;dst+=n;left-=n;bytes+=n;await new Promise(r=>setImmediate(r));}}if(bytes!==output.dataBytes)fail('OUTPUT_PCM_NOT_EXACT');return{comparedBytes:bytes,everyRetainedFrame:true};}finally{await a.close();await b.close();}}

  const shapes={engine_plan:['jobId'],choose_engine:['jobId'],engine_confirm:['jobId','engineToken','confirmed'],choose_source:['jobId'],analyse:['jobId','sourceId','settings','confirmed'],run:['jobId','planId','removeIds','confirmed'],confirm_preview:['jobId','resultId','observations','confirmed'],save:['jobId','resultId','confirmed'],discard_result:['jobId'],invalidate_plan:['jobId'],clear:['jobId']};
  async function invoke(op,p,ctx){let s,j,ownTemp=null;try{s=state(ctx);if(platform!=='win32')return{ok:false,code:'WINDOWS_ONLY_UNSUPPORTED'};if(!shapes[op])fail('UNSUPPORTED_OPERATION');shape(p,shapes[op]);j=reserve(s,p.jobId);guard(s,j);const m=await model;guard(s,j);
   if(['clear','discard_result','invalidate_plan'].includes(op)){if(op==='clear')s.source=null;if(op!=='discard_result')s.plan=null;await clearResult(s);return{ok:true,cleared:true};}
   if(op==='engine_plan'||op==='choose_engine'){s.engine=null;s.source=null;s.plan=null;await clearResult(s);let dir=defaultEngine;if(op==='choose_engine'){const picked=await choose('engine',ctx.senderId);guard(s,j);if(picked.canceled)return{ok:false,canceled:true};if(!Array.isArray(picked.filePaths)||picked.filePaths.length!==1)fail('ENGINE_SELECTION_INVALID');dir=picked.filePaths[0];}const e=await selectEngine(dir);guard(s,j);s.engine=e;return{ok:true,engine:{token:e.token,directory:dir,paths:[e.files.ffmpeg.path,e.files.ffprobe.path],plannedQueries:['ffmpeg.exe -version','ffprobe.exe -version','ffmpeg.exe -hide_banner -filters','ffmpeg.exe -hide_banner -encoders'],count:4,timeoutMsEach:5000,boundary:'确认后运行自己信任的两个本地程序，仅固定版本/滤镜/编码器查询；未读取媒体。'}};}
   if(op==='engine_confirm'){if(p.confirmed!==true)fail('EXPLICIT_CONFIRMATION_REQUIRED');if(s.engine?.token!==p.engineToken)fail('ENGINE_NOT_OWNED');const versions={ffmpeg:m.versionBanner(await runProcess(s,j,await engineFile(s,'ffmpeg'),['-version'],5000),'ffmpeg'),ffprobe:m.versionBanner(await runProcess(s,j,await engineFile(s,'ffprobe'),['-version'],5000),'ffprobe'),filter:m.support(await runProcess(s,j,await engineFile(s,'ffmpeg'),['-hide_banner','-filters'],5000),'filter'),encoder:m.support(await runProcess(s,j,await engineFile(s,'ffmpeg'),['-hide_banner','-encoders'],5000),'encoder')};guard(s,j);s.engine.confirmed=true;s.engine.versions=versions;return{ok:true,versions};}
   if(!s.engine?.confirmed)fail('ENGINE_CONFIRM_REQUIRED');
   if(op==='choose_source'){s.source=null;s.plan=null;await clearResult(s);const picked=await choose('source',ctx.senderId);guard(s,j);if(picked.canceled)return{ok:false,canceled:true};if(!Array.isArray(picked.filePaths)||picked.filePaths.length<1||picked.filePaths.length>1)fail('SOURCE_COUNT_1_REQUIRED');const seen=new Set(),files=[];let total=0;for(const raw of picked.filePaths){const pth=localPath(raw),key=pth.toLowerCase();if(path.extname(pth).toLowerCase()!=='.wav'||seen.has(key))fail('UNIQUE_WAV_REQUIRED');seen.add(key);const h=await hashFile(pth,s,j,m.LIMITS.sourceBytes);total+=h.bytes;if(total>m.LIMITS.totalBytes)fail('TOTAL_SOURCE_SIZE_LIMIT');files.push({...h,path:pth,name:path.basename(pth)});}guard(s,j);s.source={id:randomUUID(),files};return{ok:true,source:{id:s.source.id,files:files.map(f=>({name:f.name,bytes:f.bytes,sha256:f.sha256,previewURL:pathToFileURL(f.path).href})),totalBytes:total,planned:'固定RIFF/PCM16结构检查、ffprobe与逐采样分析；未写源。'}};}

   if(op==='analyse'){if(p.confirmed!==true)fail('EXPLICIT_CONFIRMATION_REQUIRED');if(s.source?.id!==p.sourceId)fail('SOURCE_NOT_OWNED');const config=m.settings(p.settings);s.plan=null;await clearResult(s);j.deadline=Date.now()+m.LIMITS.batchMs;await checkSource(s,j);const f=s.source.files[0],wave=await waveFile(f.path,s,j,m),media=await probe(s,j,f.path,wave,m),analysis=await scan(s,j,f.path,wave,config,m);await checkSource(s,j);guard(s,j);const report={format:'T045-silence-plan',version:1,source:{name:f.name,bytes:f.bytes,sha256:f.sha256,media},analysis,engine:s.engine.versions,limits:m.LIMITS,notes:['阈值是每采样绝对幅度dBFS，不是LUFS或音量语义；微弱语音/尾音/环境声可能被当作静音。','全部声道同一帧同时不高于阈值才计静音；最短停顿用ceil毫秒换帧，区间左闭右开。','完整录音全部帧检查；波形为最多1000等时段最大绝对幅度，非每采样显示。','用户勾选的候选才删除；不做淡入淡出，不重采样、不改声道，不自动去点击声。','PCM16 WAV首版；拒绝MP3/M4A/浮点/24bit/多数据块/链接路径，不偷偷转换源。']};if(Buffer.byteLength(JSON.stringify(report))>262144)fail('REPORT_LIMIT');s.plan={id:randomUUID(),report};return{ok:true,plan:s.plan};}
   if(op==='run'){if(p.confirmed!==true)fail('EXPLICIT_CONFIRMATION_REQUIRED');if(s.plan?.id!==p.planId)fail('PLAN_NOT_OWNED');const plan=s.plan.report,selection=m.selectIntervals(plan.analysis,p.removeIds);await clearResult(s);j.deadline=Date.now()+m.LIMITS.batchMs;await checkSource(s,j);const source=s.source.files[0],wave=await waveFile(source.path,s,j,m);if(JSON.stringify(wave)!==JSON.stringify((({probeDurationMs,...v})=>v)(plan.source.media)))fail('SOURCE_CHANGED');await ordinary(path.resolve(tempRoot),true);ownTemp=await fsp.mkdtemp(path.join(path.resolve(tempRoot),'T045-'));const name='trimmed-01.wav',out=path.join(ownTemp,name);await runProcess(s,j,await engineFile(s,'ffmpeg'),m.trimArgs(source.path,out,wave,selection),60000,out,false,m.LIMITS.outputBytes);const h=await hashFile(out,s,j,m.LIMITS.outputBytes),ow=await waveFile(out,s,j,m),actual=await probe(s,j,out,ow,m),validation=m.verifyOutput(wave,selection,actual),comparison=await comparePCM(s,j,source.path,out,wave,ow,selection);await checkSource(s,j);guard(s,j);const report={...plan,format:'T045-trim-report',selection,output:{path:name,bytes:h.bytes,sha256:h.sha256,media:actual},validation:{...validation,...comparison},sourceUnchanged:true,complete:true,execution:{cut:'asplit / atrim start_sample,end_sample / asetpts / concat; fixed numeric filter graph',network:'none; forced WAV / protocol_whitelist file / shell=false',metadata:'source metadata removed; no resample, fade or extra gain',deadlineMs:m.LIMITS.batchMs}};if(Buffer.byteLength(JSON.stringify(report))>262144)fail('REPORT_LIMIT');s.result={id:randomUUID(),dir:ownTemp,files:[{path:out,name,identity:h.identity,bytes:h.bytes,sha256:h.sha256,durationMs:actual.durationMs}],report,previewConfirmed:false};ownTemp=null;const expire=()=>{if(s.busy){s.expiry=setTimeout(expire,1000);s.expiry.unref?.();}else clearResult(s).catch(()=>{});};s.expiry=setTimeout(expire,900000);s.expiry.unref?.();return{ok:true,result:{id:s.result.id,report,audios:[{path:name,durationMs:actual.durationMs,previewURL:pathToFileURL(out).href}],expiresAfterMs:900000}};}
   if(s.result?.id!==p.resultId)fail('RESULT_NOT_OWNED');if(op==='confirm_preview'){if(p.confirmed!==true||!Array.isArray(p.observations)||p.observations.length!==1)fail('COMPLETE_PREVIEW_REQUIRED');const o=p.observations[0],f=s.result.files[0];shape(o,['path','durationMs']);if(o.path!==f.name||!Number.isFinite(o.durationMs)||Math.abs(o.durationMs-f.durationMs)>20)fail('COMPLETE_PREVIEW_REQUIRED');s.result.previewConfirmed=true;return{ok:true,previewConfirmed:true};}if(op==='save'){if(p.confirmed!==true)fail('EXPLICIT_CONFIRMATION_REQUIRED');return await exportResult(s,j,ctx.senderId,m);}fail('UNSUPPORTED_OPERATION');
  }catch(e){return{ok:false,code:codeOf(e),...(e.code==='CANCELED'?{canceled:true}:{}),...(e.partialPath?{partialPath:e.partialPath}:{})};}finally{if(ownTemp&&!j?.child)await cleanTemp(ownTemp).catch(()=>{});else if(ownTemp&&j?.child)j.child.once('close',()=>cleanTemp(ownTemp).catch(()=>{}));if(s&&j&&!j.child&&s.job===j){s.job=null;s.busy=false;}}}
  function cancel(id,ctx){try{const s=state(ctx);if(typeof id!=='string'||!/^[-A-Za-z0-9_]{12,64}$/.test(id))fail('INVALID_JOB_ID');if(s.job?.id===id){stop(s.job,'CANCELED');return{ok:true,cancelRequested:true,terminationObserved:!s.job.child};}if(s.seen.has(id))return{ok:true,alreadyFinished:true};const at=Date.now();for(const[k,t]of s.intents)if(at-t>60000)s.intents.delete(k);if(s.intents.size>=32)fail('CANCEL_INTENT_LIMIT');s.intents.set(id,at);return{ok:true,cancelIntentRetained:true};}catch(e){return{ok:false,code:codeOf(e)};}}
  function disposeSender(id){const s=states.get(id);if(!s)return;s.disposed=true;clearTimeout(s.expiry);s.source=null;s.plan=null;s.intents.clear();if(s.job)stop(s.job,'CANCELED');const cleanup=()=>clearResult(s).catch(()=>{}).finally(()=>states.delete(id));if(s.job?.child)s.job.child.once('close',cleanup);else cleanup();}
  return{invoke,cancel,disposeSender};
}
const host=createHost();module.exports={...host,createHost};
