import {h} from '../../core/ui.js';
import {settings,selectIntervals} from './model.mjs';
export default{id:'T045',create(root){
 const bridge=window.toolbox?.features,supported=bridge?.callHostSupported===true;let active=false,destroyed=false,busy=false,job=null,generation=0,engine=null,source=null,plan=null,result=null,clearAfter=false,invalidation=Promise.resolve();const listeners=[],players=[],loaded=new Map(),removeIds=new Set(),choices=[];
 const on=(n,t,f)=>{n.addEventListener(t,f);listeners.push(()=>n.removeEventListener(t,f));},button=(t,f)=>{const n=h('button',{},t);on(n,'click',f);return n;},label=(t,n)=>h('label',{style:{display:'inline-flex',alignItems:'center',gap:'8px'}},t,n),status=h('p',{'aria-label':'操作状态','aria-live':'polite'},supported?'先确认可信FFmpeg运行时，再选择一份本地WAV。':'缺少有限Host接口，不能分析或裁剪。'),engineText=h('pre',{'aria-label':'运行时计划',style:{whiteSpace:'pre-wrap'}}),sourceText=h('pre',{'aria-label':'录音来源',style:{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}),threshold=h('input',{type:'number',min:-90,max:-6,step:1,value:-50,'aria-label':'静音阈值dBFS'}),minimum=h('input',{type:'number',min:100,max:30000,step:100,value:500,'aria-label':'最短停顿毫秒'}),canvas=h('canvas',{width:1000,height:240,'aria-label':'完整源波形与候选区间',style:{width:'100%',height:'240px',border:'1px solid #aaa'}}),candidateBox=h('div',{'aria-label':'逐段候选选择',style:{maxHeight:'420px',overflow:'auto'}}),intervalText=h('pre',{'aria-label':'预计保留区间',style:{whiteSpace:'pre-wrap'}}),report=h('pre',{'aria-label':'完整裁剪报告',style:{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:'420px',overflow:'auto'}}),original=h('div',{'aria-label':'原录音预览'}),output=h('div',{'aria-label':'实际裁剪预览'}),review=h('input',{type:'checkbox','aria-label':'我已试听并核对成品与全部实际区间'});
 const nextJob=()=>crypto.randomUUID(),can=()=>active&&!destroyed&&supported&&!busy;
 function stopPlayers(){for(const a of players){a.pause();a.removeAttribute('src');a.load();}players.length=0;loaded.clear();}
 function clearResult(){stopPlayers();original.replaceChildren();output.replaceChildren();result=null;review.checked=false;report.textContent=plan?JSON.stringify(plan.report,null,2):'';}
 function clearPlan(){clearResult();plan=null;removeIds.clear();choices.length=0;candidateBox.replaceChildren();intervalText.textContent='';report.textContent='';draw();}
 function clearSource(){clearPlan();source=null;sourceText.textContent='';}
 function player(title,url,path=null,expected=null){const a=h('audio',{controls:true,preload:'metadata','aria-label':title,style:{width:'100%'}});players.push(a);if(path){const token=result.id;on(a,'loadedmetadata',()=>{if(destroyed||result?.id!==token)return;const ms=a.duration*1000;if(Number.isFinite(ms)&&Math.abs(ms-expected)<=20)loaded.set(path,ms);else status.textContent='成品预览时长不符，禁止导出。';refresh();});on(a,'error',()=>{if(result?.id!==token)return;loaded.delete(path);status.textContent='成品预览无法读取，禁止导出。';refresh();});}a.src=url;return h('div',{},h('p',{},title),a);}
 function showOriginal(){if(source)original.append(player('原录音：'+source.files[0].name,source.files[0].previewURL));}
 function draw(){const c=canvas.getContext('2d');c.clearRect(0,0,1000,240);c.fillStyle='#f4f5f7';c.fillRect(0,0,1000,240);c.font='14px sans-serif';c.fillStyle='#333';if(!plan){c.fillText('分析后显示整份录音；横轴从0秒到录音结束',20,30);return;}const a=plan.report.analysis,left=20,right=980,top=38,bottom=200,x=f=>left+(right-left)*f/a.frames;for(const k of a.candidates){c.fillStyle=removeIds.has(k.id)?'#ed9a8a':'#b8d8ee';c.fillRect(x(k.startFrame),top,Math.max(1,x(k.endFrame)-x(k.startFrame)),bottom-top);}c.strokeStyle='#254b65';c.beginPath();a.envelope.forEach((v,i)=>{const px=left+(i+.5)*(right-left)/a.envelope.length,y=v*76;c.moveTo(px,119-y);c.lineTo(px,119+y);});c.stroke();c.strokeStyle='#777';c.beginPath();c.moveTo(left,119);c.lineTo(right,119);c.stroke();c.fillStyle='#333';c.fillText('整份源录音：最大绝对采样幅度；红=拟删除，蓝=用户保留候选',20,22);const seconds=a.frames/a.sampleRate;for(let i=0;i<=10;i++){const px=left+(right-left)*i/10;c.fillText((seconds*i/10).toFixed(2)+'s',Math.min(px,936),225);}}
 function showSelection(){draw();if(!plan)return;try{const s=selectIntervals(plan.report.analysis,[...removeIds]);intervalText.textContent='预计 '+(s.outputDurationMs/1000).toFixed(6)+' 秒；删除 '+s.removed.length+' 段，排除候选 '+s.excluded.length+' 段。\n'+s.keep.map(k=>'保留帧 ['+k.startFrame+', '+k.endFrame+') / 秒 ['+(k.startMs/1000).toFixed(6)+', '+(k.endMs/1000).toFixed(6)+')').join('\n');}catch{intervalText.textContent='选择将删除全部录音；禁止生成空成品。';}refresh();}
 function discardOnly(){generation++;clearResult();showOriginal();invalidation=invalidation.then(()=>bridge.callHost('T045','discard_result',{jobId:nextJob()})).catch(()=>{});showSelection();}
 function displayPlan(){report.textContent=JSON.stringify(plan.report,null,2);choices.length=0;candidateBox.replaceChildren();const a=plan.report.analysis;for(const k of a.candidates){removeIds.add(k.id);const check=h('input',{type:'checkbox',checked:true,'aria-label':'删除候选 '+k.id});choices.push(check);on(check,'change',()=>{if(busy)return;if(check.checked)removeIds.add(k.id);else removeIds.delete(k.id);discardOnly();});candidateBox.append(h('p',{},label('候选 '+k.id+'：'+(k.startMs/1000).toFixed(6)+'–'+(k.endMs/1000).toFixed(6)+' 秒 / '+(k.durationMs/1000).toFixed(6)+' 秒；取消勾选会完整保留此段',check)));}if(!a.candidates.length)candidateBox.append(h('p',{},'没有满足最短时长的候选，生成时完整保留录音。'));showSelection();}
 function refresh(){if(destroyed)return;const c=can();defaultEngine.disabled=chooseEngine.disabled=!c;confirmEngine.disabled=!c||!engine||engine.confirmed;chooseSource.disabled=!c||!engine?.confirmed;analyse.disabled=!c||!source;threshold.disabled=minimum.disabled=!c;for(const n of choices)n.disabled=!c;let valid=false;if(plan)try{selectIntervals(plan.report.analysis,[...removeIds]);valid=true;}catch{}run.disabled=!c||!valid;cancel.disabled=!busy||!active||!job;clear.disabled=busy||!active;review.disabled=!c||!result||loaded.size!==1;confirmPreview.disabled=!c||!result||!review.checked||loaded.size!==1;save.disabled=!c||!result?.confirmed||!review.checked;saveJSON.disabled=!c||(!plan&&!result);}
 async function action(op,payload,apply){if(!can())return;const ticket=generation,id=nextJob();job=id;busy=true;refresh();status.textContent='执行本地作业：'+op+'；未上传录音。';try{await invalidation;const r=await bridge.callHost('T045',op,{...payload,jobId:id});if(ticket!==generation||!active||destroyed){if(op==='run')bridge.callHost('T045','discard_result',{jobId:nextJob()}).catch(()=>{});return;}if(r?.ok!==true){status.textContent=r?.canceled?'已取消。':'操作失败：'+(r?.code||r?.error||'INVALID_HOST_RECEIPT')+(r?.partialPath?'；请人工核对 '+r.partialPath:'');return;}apply(r);status.textContent=op==='save'?'已创建新目录副本：'+r.path:op==='run'?'实际保留区间已拼接，全部保留PCM字节逐块核验；请试听成品。':'操作完成，请核对波形与候选。';}catch{if(ticket===generation&&!destroyed)status.textContent='操作失败：HOST_CALL_FAILED';}finally{if(job===id){job=null;busy=false;}if(clearAfter&&!busy){clearAfter=false;invalidation=invalidation.then(()=>bridge.callHost('T045','clear',{jobId:nextJob()})).catch(()=>{});}refresh();}}
 const defaultEngine=button('查看默认FFmpeg查询计划',()=>{clearSource();engine=null;engineText.textContent='';action('engine_plan',{},r=>{engine=r.engine;engineText.textContent=JSON.stringify(engine,null,2);});}),chooseEngine=button('选择可信FFmpeg目录',()=>{clearSource();engine=null;engineText.textContent='';action('choose_engine',{},r=>{engine=r.engine;engineText.textContent=JSON.stringify(engine,null,2);});}),confirmEngine=button('确认固定版本与裁剪能力查询',()=>action('engine_confirm',{engineToken:engine.token,confirmed:true},r=>{engine.confirmed=true;engineText.textContent=JSON.stringify({directory:engine.directory,versions:r.versions},null,2);})),chooseSource=button('选择一份本机PCM16 WAV',()=>{clearSource();action('choose_source',{},r=>{source=r.source;sourceText.textContent=JSON.stringify({files:source.files.map(({previewURL,...f})=>f),planned:source.planned},null,2);showOriginal();});}),analyse=button('确认分析完整波形与静音候选',()=>{let config;try{config=settings({thresholdDBFS:Number(threshold.value),minimumMs:Number(minimum.value)});}catch{status.textContent='阈值需-90至-6dBFS；最短停顿100至30000整毫秒。';return;}clearPlan();showOriginal();action('analyse',{sourceId:source.id,settings:{thresholdDBFS:config.thresholdDBFS,minimumMs:config.minimumMs},confirmed:true},r=>{plan=r.plan;displayPlan();});}),run=button('按当前选择生成实际裁剪预览',()=>{const id=plan.id,selected=[...removeIds];clearResult();showOriginal();action('run',{planId:id,removeIds:selected,confirmed:true},r=>{result=r.result;report.textContent=JSON.stringify(result.report,null,2);for(const a of result.audios)output.append(player('裁剪成品：'+a.path,a.previewURL,a.path,a.durationMs));});}),cancel=button('取消当前作业',()=>{if(!job)return;generation++;bridge.cancelHost('T045',job).catch(()=>{});clearSource();clearAfter=true;status.textContent='已请求取消，等待实际close后清理；未承诺立即终止。';refresh();}),clear=button('清空录音与临时成品',()=>{clearSource();action('clear',{},()=>{});}),confirmPreview=button('确认试听与完整保留区间',()=>action('confirm_preview',{resultId:result.id,observations:result.audios.map(a=>({path:a.path,durationMs:loaded.get(a.path)})),confirmed:true},()=>{result.confirmed=true;})),save=button('保存裁剪WAV与报告到新目录',()=>action('save',{resultId:result.id,confirmed:true},()=>{})),saveJSON=button('另存完整JSON分析或结果',async()=>{if(!can()||(!plan&&!result))return;const files=window.toolbox?.files,ticket=generation;if(files?.saveTextSupportsCopyOnly!==true){status.textContent='缺少安全文本副本接口。';return;}busy=true;refresh();try{const r=await files.saveText({content:JSON.stringify(result?.report??plan.report,null,2),extension:'json',defaultName:'T045-trim-report.json',copyOnly:true});if(ticket!==generation||!active||destroyed)return;status.textContent=r?.ok===true?'已保存JSON新副本。':r?.canceled?'取消保存报告。':'报告保存失败：'+(r?.error||'回执未明确ok=true')+(r?.partialPath?'；请人工核对 '+r.partialPath:'');}catch{if(ticket===generation&&!destroyed)status.textContent='报告保存失败。';}finally{busy=false;refresh();}});
 function inputChanged(){if(busy)return;generation++;clearPlan();showOriginal();invalidation=invalidation.then(()=>bridge.callHost('T045','invalidate_plan',{jobId:nextJob()})).catch(()=>{});refresh();}on(threshold,'input',inputChanged);on(minimum,'input',inputChanged);on(review,'change',()=>{if(result&&!review.checked)result.confirmed=false;refresh();});
 root.replaceChildren(h('section',{style:{maxWidth:'1080px',margin:'auto',padding:'16px'}},h('h2',{},'录音静音片段裁剪'),h('p',{},'本地Windows / 可信FFmpeg 6.x外部安装。一份PCM16 WAV，单/双声道，8/11.025/12/16/22.05/24/32/44.1/48/88.2/96kHz，最长600秒、≤128MiB；完整分析最多100候选，超限整体拒绝。首版不接受MP3/M4A或24bit/float，需用户自行转换后再选。'),h('p',{},'静音只指所有声道逐帧低于幅度阈值，可能误删弱声。红区勾选拟删除、蓝区取消后保留。先试听原录音，再逐段核对；成品保持采样率/声道/PCM16，边界不做淡入淡出，拼接点可能有点击声。'),status,h('div',{style:{display:'flex',gap:'8px',flexWrap:'wrap'}},defaultEngine,chooseEngine,confirmEngine),engineText,chooseSource,sourceText,h('div',{style:{display:'flex',gap:'16px',flexWrap:'wrap',padding:'12px 0'}},label('阈值 dBFS',threshold),label('最短停顿毫秒',minimum)),h('div',{},analyse,cancel,clear),canvas,h('p',{},'横轴覆盖完整源时长；每一波形列取相应时间段全部声道最大幅度，最多1000列。帧区间左闭右开，毫秒仅用于显示。勾选删除候选，取消勾选逐段排除；更改选择使旧成品失效。'),candidateBox,intervalText,run,original,output,label('手动核对完整成品与实际区间',review),h('div',{},confirmPreview,save,saveJSON),h('h3',{},'完整分析与采用区间报告'),report,h('p',{},'新目录包含trimmed-01.wav及trim-report.json；已有目录拒绝。临时成品15分钟后过期；离开/隐藏/销毁清空本批并停止播放，回来需重新选择，不保存到配置。')));draw();
 function suspend(){if(!active)return;active=false;generation++;clearSource();if(job)bridge?.cancelHost('T045',job).catch(()=>{});if(supported){if(busy&&job)clearAfter=true;else invalidation=invalidation.then(()=>bridge.callHost('T045','clear',{jobId:nextJob()})).catch(()=>{});}status.textContent='已停止播放并清空本批；返回后重新选择，不自动续播。';refresh();}on(document,'visibilitychange',()=>{if(document.hidden)suspend();});return{activate(){if(!destroyed){active=true;refresh();}},deactivate:suspend,destroy(){suspend();destroyed=true;stopPlayers();for(const off of listeners)off();root.replaceChildren();}};
}};
