export const KINDS=Object.freeze({export:'数据导出',unbind:'解绑事项',other:'其他准备'});
const clone=x=>JSON.parse(JSON.stringify(x));
function text(value,label,max,empty=false){if(typeof value!=='string'||value.length>max||/[\x00-\x1f\x7f]/.test(value)||(!empty&&!value.trim()))throw Error(`${label}须为${empty?'0':'1'}–${max}字符单行文本。`);return value.trim();}
export function link(value){const raw=text(value,'外链',500,true);if(!raw)return '';let url;try{url=new URL(raw);}catch{throw Error('外链须为完整http或https网址。');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('仅接受不带用户名/口令的http或https网址。');return url.href;}
export function example(){return{accounts:[{id:'A1',name:'演示账号',items:[{id:'I1',kind:'export',title:'导出相册副本',url:'https://example.com/export',note:'确认本地副本可读取后再标记完成。',done:false,confirmedAt:null},{id:'I2',kind:'export',title:'导出账单记录',url:'',note:'',done:false,confirmedAt:null},{id:'I3',kind:'unbind',title:'解绑第三方登录',url:'',note:'',done:false,confirmedAt:null}]}]};}
export function checklist(input){if(!input||!Array.isArray(input.accounts)||!input.accounts.length||input.accounts.length>20)throw Error('请配置1–20个账号。');const accountIds=new Set(),itemIds=new Set();let total=0;
 const accounts=input.accounts.map(a=>{const id=text(a?.id,'账号编号',32);if(accountIds.has(id))throw Error('账号编号重复。');accountIds.add(id);if(!Array.isArray(a.items)||!a.items.length||a.items.length>50||(total+=a.items.length)>200)throw Error('每账号1–50项，全部账号合计最多200项。');const name=text(a.name,'账号名称',120);
  const items=a.items.map(t=>{const itemId=text(t?.id,'事项编号',32);if(itemIds.has(itemId))throw Error('事项编号重复。');itemIds.add(itemId);if(!Object.hasOwn(KINDS,t.kind)||typeof t.done!=='boolean')throw Error('事项类型或完成标记无效。');if(t.done){if(typeof t.confirmedAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(t.confirmedAt)||!Number.isFinite(Date.parse(t.confirmedAt))||new Date(t.confirmedAt).toISOString()!==t.confirmedAt)throw Error('已完成事项需要真实ISO UTC人工确认时间。');}else if(t.confirmedAt!==null)throw Error('未完成事项不应含确认时间。');return{id:itemId,kind:t.kind,kindLabel:KINDS[t.kind],title:text(t.title,'事项标题',160),url:link(t.url),note:text(t.note,'事项备注',300,true),done:t.done,confirmedAt:t.confirmedAt,confirmation:'仅用户手工声明，未验证平台操作'};});
  return{id,name,items,total:items.length,done:items.filter(t=>t.done).length,byKind:Object.fromEntries(Object.keys(KINDS).map(k=>[k,items.filter(t=>t.kind===k).length]))};});
 const done=accounts.reduce((s,a)=>s+a.done,0);return{feature:'T099',schemaVersion:1,inputs:clone(input),accounts,total,done,pending:total-done,policy:'仅整理用户手填材料，完成记录为人工声明；外链只可显式复制，不自动访问、注销账号或发邮件。'};
}
export function restore(json){if(typeof json!=='string'||new TextEncoder().encode(json).length>65536)throw Error('JSON恢复最多64KiB UTF-8。');const data=JSON.parse(json);if(data?.feature!=='T099'||data.schemaVersion!==1)throw Error('仅支持T099版本1清单。');checklist(data.inputs);return clone(data.inputs);}
export function resetCompletion(item){item.done=false;item.confirmedAt=null;}
const safe=s=>String(s).replace(/[|`\r\n]/g,' ').replace(/</g,'&lt;').replace(/>/g,'&gt;');
export function markdown(report){return`# 账号注销材料清单\n\n${report.policy}\n\n共${report.accounts.length}账号、${report.total}项，人工完成${report.done}项、待处理${report.pending}项。\n\n`+report.accounts.map(a=>`## ${safe(a.name)} (${safe(a.id)})\n\n|编号|类别|准备事项|人工状态|确认时间UTC|外链文本|备注|\n|---|---|---|---|---|---|---|\n`+a.items.map(t=>`|${safe(t.id)}|${t.kindLabel}|${safe(t.title)}|${t.done?'人工完成':'待处理'}|${t.confirmedAt||'—'}|${safe(t.url)||'—'}|${safe(t.note)}|`).join('\n')).join('\n\n')+'\n';}
