import {h} from '../../core/ui.js';
import {buildReport,validateRequirements,serializeReport,TARGETS,FEATURES} from './model.mjs';
export default{id:'T080',create(root){
 let alive=true,active=false,busy=false,saving=false,epoch=0,jobId=null,report=null,preview=null;const bindings=[];
 const on=(n,t,f)=>{n.addEventListener(t,f);bindings.push([n,t,f]);return n;},status=h('p',{role:'status'}),result=h('pre',{'aria-label':'完整GPU报告'}),previewNode=h('pre',{'aria-label':'完整导出预览'}),say=s=>{if(alive)status.textContent=s;};
 const task=h('select',{'aria-label':'目标任务'},...TARGETS.map(v=>h('option',{value:v},v))),memory=h('input',{'aria-label':'最低专用显存GiB',placeholder:'例如8；留空不检查',type:'text',maxLength:7}),driver=h('input',{'aria-label':'要求精确驱动版本',placeholder:'原始字符串；留空不检查',maxLength:512}),feature=h('select',{'aria-label':'Chromium加速检查项'},...FEATURES.map(v=>h('option',{value:v},v==='none'?'不指定':v)));
 const requirements=()=>({task:task.value,minVramGiB:memory.value,exactDriver:driver.value,feature:feature.value}),current=n=>alive&&active&&epoch===n;
 const button=(name,fn)=>on(h('button',{type:'button',class:'btn'},name),'click',()=>{if(alive&&active&&!busy)fn();});
 const collect=button('只读采集本机 GPU',async()=>{
  invalidate();let chosen;try{chosen=requirements();validateRequirements(chosen);}catch(e){say(e.message);return;}const api=window.toolbox?.features;if(api?.callHostSupported!==true||typeof api.callHost!=='function'){say('生产宿主接口缺失，不能采集本机GPU。');return;}
  const own=epoch;jobId=crypto.randomUUID();const id=jobId;busy=true;update();say('只读采集中，最多5秒；没有安装驱动或启动目标任务。');
  try{const next=await api.callHost('T080','collect',{jobId:id});if(!current(own))return;if(next?.canceled===true){say('已取消，无部分报告。');return;}report=buildReport(next,chosen);result.textContent=JSON.stringify(report,null,2);say(`采集完成：${report.gpu.devices.length}个当前Chromium报告条目；专用显存及任务运行能力仍未知，尚未保存。`);}catch(e){if(current(own))say(`未生成GPU报告：${e.message}`);}finally{if(current(own)){busy=false;jobId=null;update();}}
 });
 const cancel=on(h('button',{type:'button',class:'btn'},'取消当前采集'),'click',()=>{if(!alive||!active||!busy||saving)return;leave();say('已取消等待并忽略晚返回；底层公开GPU查询不能被强制中断。');});
 const json=button('预览完整 JSON 报告',()=>show('json')),md=button('预览完整 Markdown 报告',()=>show('md')),clear=button('清空当前报告',()=>invalidate('报告及预览已清空。'));
 const save=button('保存已预览报告新副本',async()=>{const api=window.toolbox?.files;if(!preview||api?.saveTextSupportsCopyOnly!==true||typeof api.saveText!=='function')return;const own=epoch,chosen=preview;busy=saving=true;update();try{const r=await api.saveText({...chosen,copyOnly:true});if(current(own))say(r?.ok===true?'完整 GPU 报告新副本保存成功。':r?.canceled===true?'已取消另存，预览保留。':`保存失败：${r?.error||'未确认写入'}${r?.partialPath?'；请人工核对 '+r.partialPath:''}`);}catch{if(current(own))say('保存失败，预览保留。');}finally{if(current(own)){busy=saving=false;update();}}});
 function update(){if(!alive)return;for(const n of[task,memory,driver,feature,collect,clear])n.disabled=!active||busy;json.disabled=md.disabled=!active||busy||!report;save.disabled=!active||busy||!preview||window.toolbox?.files?.saveTextSupportsCopyOnly!==true;cancel.disabled=!active||!busy||saving;}
 function invalidate(message='目标要求改变，旧报告已失效。'){epoch++;report=preview=null;result.textContent=previewNode.textContent='';say(message);update();}
 function leave(){const old=jobId;invalidate();jobId=null;busy=saving=false;if(old)Promise.resolve(window.toolbox?.features?.cancelHost?.('T080',old)).catch(()=>{});update();}
 function show(kind){preview={content:serializeReport(report,kind),extension:kind,defaultName:`gpu-capability-report-copy.${kind}`};previewNode.textContent=preview.content;say('完整报告已预览，包含设备型号/驱动；分享前核对本机信息。');update();}
 for(const n of[task,memory,driver,feature])on(n,n.tagName==='INPUT'?'input':'change',()=>{if(alive&&active&&!busy)invalidate();});
 const hide=()=>{if(alive&&document.hidden){leave();say('窗口隐藏，当前采集/报告已清空；返回需手动采集。');}};document.addEventListener('visibilitychange',hide);
 root.replaceChildren(h('section',{class:'t080'},h('style',{},'.t080{display:grid;gap:12px;max-width:1000px;margin:auto}.t080 input,.t080 select,.t080 pre{padding:12px;background:var(--bg-raised);color:var(--text);border:1px solid var(--line)}.t080 pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:460px;overflow:auto}.t080-row{display:flex;gap:8px;flex-wrap:wrap}'),h('h2',{},'GPU 本地能力报告'),h('p',{},'只读Electron/Chromium当前GPU型号、驱动和加速状态；不安装驱动、不运行基准或目标任务。'),status,h('label',{},'目标任务',task),h('label',{},'最低专用显存（GiB）',memory),h('label',{},'要求精确驱动版本',driver),h('label',{},'Chromium加速检查项',feature),h('div',{class:'t080-row'},collect,cancel,clear),result,h('div',{class:'t080-row'},json,md),previewNode,save,h('p',{},'专用显存没有单位明确的公开GPU设备字段，因此保持未知。驱动仅按原始字符串精确比较；Chromium加速状态只有本次观察到gpu-info-update后读取，未观察到即未知。最多32个条目/单字符串2048字节，异常整体未知，未截断冒充完整。API等待最多5秒，取消仅停止等待；没有后台监控、自动草稿或联网。')));
 say('填写目标要求后手动采集；留空表示不指定。型号或加速状态不能证明目标任务可运行。');update();return{activate(){if(alive){active=true;update();}},deactivate(){if(alive){active=false;leave();}},destroy(){if(!alive)return;active=false;leave();alive=false;for(const[n,t,f]of bindings)n.removeEventListener(t,f);document.removeEventListener('visibilitychange',hide);root.replaceChildren();}};
}};
