import {h} from '../../core/ui.js';
import {LIMITS,clone,createGame,play,legal,counts,outcome,undoRound,source,restore,encode,parse,report,markdown,coordinate} from './model.mjs';
export default{id:'E008',create(root,ctx={}){
 const key='featureLab.E008.progress';let game=createGame(),focusIndex=19,newDifficulty='easy',active=false,alive=true,paused=true,invalid=false,saving=false,reading=false,exporting=false,generation=0,job=null,candidate=null;
 let message='你执黑先行，本机执白；点击开始后选择提示点。',storageText='尚无本地续玩。',selector,confirmNew,file,confirmImport,confirmInvalid,status,storage,summary,startButton;const listeners=[],buttons=[],cells=[],canvases=new Set();
 try{const saved=ctx.config?.get?.(key,null);if(saved!=null){game=restore(saved);newDifficulty=game.difficulty;storageText='完整步迹已恢复，保持暂停。';}}catch(e){invalid=true;message='旧档未接受：'+e.message;storageText='旧档尚未覆盖，请确认重置或导入。';}
 const busy=()=>saving||reading||exporting,usable=()=>alive&&active&&!document.hidden&&!busy()&&!invalid;
 function on(n,t,f){n.addEventListener(t,f);listeners.push([n,t,f]);}
 function clear(){for(const[n,t,f]of listeners)n.removeEventListener(t,f);listeners.length=0;buttons.length=0;cells.length=0;root.replaceChildren();}
 function cancelAI(){if(job){job.worker.terminate();clearTimeout(job.timer);job=null;}generation++;}
 function update(){if(!alive)return;const r=outcome(game),moves=new Set(legal(game.board,game.turn)),disabled=!active||document.hidden||busy();summary.textContent=`本局${game.difficulty==='easy'?'简单':'进阶'} · 黑${r.black} / 白${r.white} / 空${r.empty} · ${game.trace.length}/60落子 · ${game.ended?`结束：${r.winner==='draw'?'平局':r.winner==='black'?'黑方（你）胜':'白方（本机）胜'}`:paused?'暂停；需明确继续':game.turn===1?'轮到黑方（你）':job?'白方本地计算中':'轮到白方（本机）'}${game.passes.length?` · 自动跳过${game.passes.length}次`:''}`;status.textContent=message;storage.textContent=storageText;selector.disabled=file.disabled=disabled;confirmNew.disabled=confirmImport.disabled=confirmInvalid.disabled=busy();for(const b of buttons)b.node.disabled=disabled||(invalid&&!['invalidReset','import'].includes(b.kind))||(b.kind==='undo'&&(game.ended||!game.trace.length))||(b.kind==='start'&&game.ended)||(b.kind==='import'&&!candidate)||(b.kind==='text'&&window.toolbox?.files?.saveTextSupportsCopyOnly!==true)||(b.kind==='png'&&window.toolbox?.files?.saveBinarySupportsCopyOnly!==true);for(let i=0;i<64;i++){const c=cells[i];c.disabled=disabled||invalid||paused||game.ended||game.turn!==1;c.setAttribute('aria-disabled',String(c.disabled||!moves.has(i)));c.style.animationPlayState=!active||document.hidden||paused?'paused':'running';for(const child of c.children)if(child.style)child.style.animationPlayState=c.style.animationPlayState;}startButton.textContent=paused?'开始 / 继续对局':'暂停对局';}
 function render(animate=false,focus=false){clear();const r=outcome(game),moves=new Set(legal(game.board,game.turn)),changed=new Set(animate&&game.last?game.last.flipped:[]);selector=h('select',{'aria-label':'新局AI难度'});for(const[v,t]of[['easy','简单：即时最多翻子'],['hard','进阶：有限搜索与位置判断']])selector.append(h('option',{value:v},t));selector.value=newDifficulty;on(selector,'change',()=>{newDifficulty=selector.value;message='难度选择只影响勾确认后的新局，当前局规则保持。';update();});confirmNew=h('input',{type:'checkbox','aria-label':'确认放弃当前黑白棋重开'});confirmImport=h('input',{type:'checkbox','aria-label':'确认替换黑白棋续玩'});confirmInvalid=h('input',{type:'checkbox','aria-label':'确认清空无效黑白棋存档'});file=h('input',{type:'file',accept:'.json,application/json','aria-label':'黑白棋续玩JSON'});on(file,'change',()=>read(file.files?.[0]));
 const grid=h('div',{role:'grid','aria-label':'黑白棋棋盘',style:{display:'grid',gridTemplateColumns:'26px repeat(8,minmax(30px,1fr))',maxWidth:'610px',gap:'3px',background:'#e8e4d8',padding:'10px',borderRadius:'10px',boxSizing:'border-box'}}),header=h('div',{role:'row',style:{display:'contents'}});header.append(h('span',{},''));for(const a of 'ABCDEFGH')header.append(h('div',{role:'columnheader',style:{textAlign:'center'}},a));grid.append(header);
 for(let y=0;y<8;y++){const row=h('div',{role:'row',style:{display:'contents'}});row.append(h('div',{role:'rowheader',style:{alignSelf:'center',textAlign:'center'}},y+1));for(let x=0;x<8;x++){const i=y*8+x,v=game.board[i],label=`${coordinate(i)} ${['空','黑棋','白棋'][v]}${moves.has(i)?' 合法落子':''}`,disc=v?h('span',{class:`e008-disc${changed.has(i)?' e008-flip':''}`,style:{width:'74%',height:'74%',borderRadius:'50%',display:'block',background:v===1?'#26363a':'#fffdf5',border:v===1?'1px solid #14292c':'1px solid #bbc2b7',boxSizing:'border-box',boxShadow:'0 2px 3px #0003'}},''):moves.has(i)?h('span',{'aria-hidden':'true',style:{height:'9px',width:'9px',borderRadius:'50%',background:'#e8dfb5',display:'block'}},''):null,c=h('button',{type:'button',role:'gridcell','data-index':i,tabindex:i===focusIndex?'0':'-1','aria-label':label,style:{aspectRatio:'1',width:'100%',minWidth:'30px',padding:'0',margin:'0',display:'flex',alignItems:'center',justifyContent:'center',border:game.last?.index===i?'2px solid #dcc878':'1px solid #456a5a',background:'#628776',borderRadius:'3px',boxSizing:'border-box'}},disc);on(c,'focus',()=>{focusIndex=i;});on(c,'click',()=>human(i));on(c,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||!usable()||paused||game.turn!==1||game.ended)return;const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8}[e.key];if(delta!==undefined){e.preventDefault();const next=delta===-1&&x===0||delta===1&&x===7?i:Math.max(0,Math.min(63,i+delta));focusIndex=next;cells.forEach((n,k)=>n.setAttribute('tabindex',k===next?'0':'-1'));cells[next].focus();}else if([' ','Enter'].includes(e.key)){e.preventDefault();if(!e.repeat)human(i);}});cells.push(c);row.append(c);}grid.append(row);}
 function button(t,f,kind){const n=h('button',{type:'button'},t);on(n,'click',f);buttons.push({node:n,kind});return n;}
 startButton=button(paused?'开始 / 继续对局':'暂停对局',()=>{if(!usable()||game.ended)return;if(paused){paused=false;message='已继续对局，黑方选择提示点；白方自动本地计算。';update();startAI();}else{paused=true;cancelAI();message='已暂停，对手Worker已终止；继续后重新计算。';update();}},'start');summary=h('p',{'aria-label':'黑白棋统计'});status=h('p',{role:'status','aria-label':'操作状态'});storage=h('p',{'aria-label':'黑白棋保存状态'});
 const records=h('ol',{'aria-label':'完整黑白棋落子记录'});for(const step of report(game).moves)records.append(h('li',{},`${step.player==='black'?'黑':'白'} ${step.coordinate} · 翻${step.flippedCoordinates.join('、')}（${step.flipped.length}枚）${step.autoPassed.length?` · ${step.autoPassed[0]==='black'?'黑':'白'}无棋可下，自动跳过`:''}`));
 root.append(h('section',{style:{maxWidth:'860px',margin:'0 auto',padding:'18px',lineHeight:'1.6'}},h('style',{},'@keyframes e008-turn{0%{transform:scaleX(.2);opacity:.35}100%{transform:scaleX(1);opacity:1}}.e008-flip{animation:e008-turn .32s ease-out 1}@media(prefers-reduced-motion:reduce){.e008-flip{animation:none}}'),h('h2',{},'黑白棋'),h('p',{},'你执黑先行，本机执白。落在空格并沿横、竖、斜八方向夹住连续白棋，所有被夹棋翻成黑棋；白方同理。点是当前方合法落子，黄色边为最近落子。无棋可下一方自动跳过；双方都无棋可下立即按棋数结算，空格不计、同数平局。'),h('p',{},'鼠标单击提示点；聚焦棋盘后方向键选任意格，空格/Enter落子。非法位置不改变棋盘。两档算法均离线且确定，同分按行列；进阶最多3层/20000节点，不承诺最优棋力。'),h('div',{},startButton,button('撤销到上次黑方落子前',()=>{if(!usable()||game.ended)return;cancelAI();const next=undoRound(game);if(!next){message='没有可撤销的黑方落子。';update();return;}game=next;paused=true;message='撤销上次黑落子及其后所有白落子；保持暂停。';save(false,true);},'undo')),summary,grid,h('div',{},h('label',{},'新局难度 ',selector),h('label',{},confirmNew,' 确认放弃当前局'),button('按所选难度开启新局',()=>{if(!usable())return;if(!confirmNew.checked){message='需勾确认放弃当前局，再重开。';update();return;}cancelAI();game=createGame(newDifficulty);paused=true;candidate=null;focusIndex=19;message='已重开，点击开始对局；旧副本文件不删除。';save();},'new')),storage,invalid?h('div',{},h('label',{},confirmInvalid,' 确认清空无效黑白棋存档'),button('从标准开局重新开始',()=>{if(!confirmInvalid.checked){message='先确认，旧档尚未覆盖。';update();return;}cancelAI();invalid=false;game=createGame();newDifficulty='easy';paused=true;save();},'invalidReset')):null,h('h3',{},'完整续玩与副本'),h('p',{},'每次实际落子、撤销、新局与应用导入自动保存完整合法步迹。最多60次标准落子，自动跳过不占落子数。重载、隐藏或离开暂停且终止AI，返回不自启。当前只保存一局，旧局可先另存JSON/记录；难度改变需确认新局。'),h('div',{},button('重试本地保存',()=>save(),'retry'),button('另存续玩JSON新副本',()=>exportText('json'),'text'),button('另存完整Markdown记录',()=>exportText('md'),'text'),button('另存完整棋盘PNG',exportPNG,'png')),file,h('p',{'aria-label':'黑白棋导入预览'},candidate?`已校验 ${candidate.difficulty==='easy'?'简单':'进阶'} · ${candidate.trace.length}步 · 黑${counts(candidate.board).black}/白${counts(candidate.board).white}${candidate.ended?' · 已结束':''}；尚未替换。`:'选择≤64KiB schema1 JSON，仅接受从标准开局完整合法步迹，恢复重新计算翻子/跳过/胜负。'),h('label',{},confirmImport,' 确认替换黑白棋续玩'),button('应用黑白棋续玩',()=>{if(!alive||!active||document.hidden||busy()||!candidate)return;if(!confirmImport.checked){message='请先勾确认替换。';update();return;}cancelAI();game=candidate;candidate=null;invalid=false;newDifficulty=game.difficulty;paused=true;message='已恢复完整棋局，保持暂停。';save();},'import'),status,h('h3',{},'完整落子与自动跳过'),records));update();if(focus&&active&&!paused&&game.turn===1)cells[focusIndex]?.focus();
 }
 async function save(animate=false,focus=false){if(!alive||saving)return;saving=true;storageText='正在保存完整步迹…';render(animate,focus);try{if(typeof ctx.config?.set!=='function')throw Error('本地配置接口不可用');await ctx.config.set(key,source(game));if(alive)storageText='完整棋局已保存，重载保持暂停。';}catch(e){if(alive)storageText='保存失败：'+e.message+'；当前仅临时保留，可另存JSON或重试。';}finally{saving=false;if(alive){update();if(focus&&active&&!paused&&game.turn===1)cells[focusIndex]?.focus();startAI();}}}
 function human(i){if(!usable()||paused||game.turn!==1||game.ended)return;try{const step=play(game,i);focusIndex=i;candidate=null;generation++;message=`黑落${coordinate(i)}，翻${step.flipped.length}枚${step.passed.length?'；白无棋可下，自动跳过':''}${game.ended?'；双方无棋可下，已结算':''}。`;if(game.ended)paused=true;save(true,true);}catch(e){message=e.message;update();}}
 function startAI(){if(!usable()||paused||game.turn!==2||game.ended||job)return;const id=++generation;let worker;try{worker=ctx.workerFactory?ctx.workerFactory():new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});}catch(e){paused=true;message='对手Worker不可用：'+e.message+'；已暂停，可重试。';update();return;}const timer=setTimeout(()=>fail('计算超过5秒，已终止Worker；点击继续可重试。'),5000);job={id,worker,timer};function fail(text){if(!alive||!job||job.id!==id)return;cancelAI();paused=true;message='本机对手未落子：'+text;update();}
 worker.onerror=e=>{e.preventDefault?.();fail(e.message||'Worker失败');};worker.onmessage=e=>{if(!alive||!job||job.id!==id||id!==generation||!active||document.hidden||paused)return;if(e.data?.id!==id||e.data?.ok!==true){fail(e.data?.error||'无效Worker响应');return;}const result=e.data.result,index=result?.index;if(!Number.isInteger(index)||!legal(game.board,2).includes(index)){fail('返回非法落子，未改棋盘。');return;}clearTimeout(job.timer);worker.terminate();job=null;try{const step=play(game,index);focusIndex=index;message=`白落${coordinate(index)}，翻${step.flipped.length}枚；${game.difficulty==='easy'?'即时翻子算法':`完成${result.depth}层搜索/访问${result.nodes}节点`}${step.passed.length?'；黑无棋可下，自动跳过':''}${game.ended?'；双方无棋可下，已结算':''}。`;if(game.ended)paused=true;save(true,true);}catch(err){fail(err.message);}};try{worker.postMessage({id,board:[...game.board],player:2,difficulty:game.difficulty});}catch(e){fail(e.message||'Worker发送失败');}update();
 }
 async function read(f){if(!f||!active||busy())return;paused=true;cancelAI();const token=++generation;reading=true;candidate=null;update();try{if(f.size>LIMITS.bytes)throw Error('JSON最多64KiB。');const bytes=await f.arrayBuffer();if(!alive||token!==generation)return;if(bytes.byteLength>LIMITS.bytes)throw Error('实际JSON超过64KiB。');candidate=parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));message='全步迹重放合法，尚未替换。';}catch(e){if(alive&&token===generation)message='导入拒绝：'+e.message;}finally{if(alive&&token===generation){reading=false;render();}}}
 const response=r=>r?.ok===true?'已另存完整新副本。':r?.canceled?'已取消另存。':`另存失败：${r?.error||'未确认成功'}${r?.partialPath?'；请人工核对 '+r.partialPath:''}`;
 function beginExport(){paused=true;cancelAI();exporting=true;render();return generation;}
 async function exportText(ext){if(!usable())return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message='需要文本copyOnly基础接口。';update();return;}const token=beginExport();try{const result=await files.saveText({copyOnly:true,extension:ext,defaultName:`reversi-${game.trace.length}-${game.ended?'complete':'draft'}-copy.${ext}`,content:ext==='json'?encode(source(game)):markdown(report(game))});if(alive&&token===generation)message=response(result);}catch(e){if(alive&&token===generation)message='另存失败：'+e.message;}finally{if(alive&&token===generation){exporting=false;update();}}}
 async function exportPNG(){if(!usable())return;const files=window.toolbox?.files;if(files?.saveBinarySupportsCopyOnly!==true){message='需要二进制copyOnly基础接口。';update();return;}const token=beginExport(),canvas=document.createElement('canvas');canvases.add(canvas);try{drawPNG(canvas,game);const blob=await new Promise((r,j)=>canvas.toBlob(v=>v?r(v):j(Error('PNG编码失败。')),'image/png'));if(!alive||token!==generation)return;if(blob.size>LIMITS.pngBytes)throw Error('PNG超过10MiB，未写入。');const bytes=new Uint8Array(await blob.arrayBuffer()),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));if(!alive||token!==generation)return;let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await files.saveBinary({copyOnly:true,defaultName:`reversi-${game.trace.length}-${game.ended?'complete':'draft'}-copy.png`,base64:btoa(binary),sha256:[...hash].map(v=>v.toString(16).padStart(2,'0')).join('')});if(alive&&token===generation)message=response(result);}catch(e){if(alive&&token===generation)message='PNG另存失败：'+e.message;}finally{canvas.width=canvas.height=0;canvases.delete(canvas);if(alive&&token===generation){exporting=false;update();}}}
 const visibility=()=>{if(document.hidden){paused=true;cancelAI();reading=exporting=false;candidate=null;message='页面隐藏，已终止对手并暂停；返回需明确继续。';}update();};document.addEventListener('visibilitychange',visibility);render();return{activate(){if(alive){active=true;update();}},deactivate(){if(alive){active=false;paused=true;cancelAI();reading=exporting=false;candidate=null;message='已离开，Worker终止；返回保持暂停。';update();}},destroy(){if(!alive)return;alive=false;active=false;paused=true;cancelAI();document.removeEventListener('visibilitychange',visibility);for(const c of canvases)c.width=c.height=0;canvases.clear();clear();game=candidate=null;}};
}};
export function drawPNG(canvas,game){canvas.width=900;canvas.height=850;const c=canvas.getContext('2d');if(!c)throw Error('Canvas不可用。');const r=outcome(game),moves=new Set(legal(game.board,game.turn));c.fillStyle='#fffdf5';c.fillRect(0,0,900,850);c.fillStyle='#26363a';c.font='bold 26px sans-serif';c.fillText('黑白棋 · '+(game.difficulty==='easy'?'简单':'进阶'),30,40);c.font='18px sans-serif';c.fillText(`黑 ${r.black} / 白 ${r.white} / 空 ${r.empty} · ${game.trace.length}步 · ${game.ended?r.winner==='draw'?'平局':r.winner==='black'?'黑方胜':'白方胜':game.turn===1?'轮到黑方':'轮到白方'}（导出时暂停）`,30,74);c.textAlign='center';for(let i=0;i<8;i++){c.fillText('ABCDEFGH'[i],120+(i+.5)*80,116);c.fillText(String(i+1),90,136+(i+.5)*80+6);}for(let i=0;i<64;i++){const x=120+(i%8)*80,y=136+Math.floor(i/8)*80,v=game.board[i];c.fillStyle='#628776';c.fillRect(x,y,80,80);c.strokeStyle=game.last?.index===i?'#dcc878':'#456a5a';c.lineWidth=game.last?.index===i?3:1;c.strokeRect(x+.5,y+.5,79,79);if(v){c.beginPath();c.arc(x+40,y+40,29,0,Math.PI*2);c.fillStyle=v===1?'#26363a':'#fffdf5';c.fill();c.strokeStyle=v===1?'#14292c':'#bbc2b7';c.lineWidth=1;c.stroke();}else if(moves.has(i)){c.beginPath();c.arc(x+40,y+40,5,0,Math.PI*2);c.fillStyle='#e8dfb5';c.fill();}}c.textAlign='left';c.fillStyle='#26363a';c.font='16px sans-serif';c.fillText('黑=用户，白=本机；点=当前方合法位置，金色边=最近落子。',30,806);c.fillText('双方无棋可下按棋数结算；本地有限AI，不承诺最优。',30,832);}
