export const LIMITS=Object.freeze({bytes:65536,moves:60,aiNodes:20000,aiDepth:3,pngBytes:10485760});
export const DIRECTIONS=Object.freeze([-1,0,1].flatMap(y=>[-1,0,1].filter(x=>x||y).map(x=>Object.freeze([x,y]))));
export const clone=v=>JSON.parse(JSON.stringify(v));
export function initial(){const b=Array(64).fill(0);b[27]=b[36]=2;b[28]=b[35]=1;return b;}
function validBoard(b){if(!Array.isArray(b)||b.length!==64||b.some(v=>!Number.isInteger(v)||v<0||v>2))throw Error('需64格黑白空棋盘。');}
export function flips(board,index,player){validBoard(board);if(!Number.isInteger(index)||index<0||index>=64||![1,2].includes(player))throw Error('无效落子。');if(board[index])return[];const x=index%8,y=Math.floor(index/8),out=[];for(const[dx,dy]of DIRECTIONS){let xx=x+dx,yy=y+dy,line=[];while(xx>=0&&xx<8&&yy>=0&&yy<8&&board[yy*8+xx]===3-player){line.push(yy*8+xx);xx+=dx;yy+=dy;}if(line.length&&xx>=0&&xx<8&&yy>=0&&yy<8&&board[yy*8+xx]===player)out.push(...line);}return out;}
export function legal(board,player){validBoard(board);if(![1,2].includes(player))return[];const out=[];for(let i=0;i<64;i++)if(!board[i]&&flips(board,i,player).length)out.push(i);return out;}
export function counts(board){validBoard(board);return{black:board.filter(v=>v===1).length,white:board.filter(v=>v===2).length,empty:board.filter(v=>v===0).length};}
export function resolve(board,previous){const other=3-previous;if(legal(board,other).length)return{turn:other,passed:[],ended:false};if(legal(board,previous).length)return{turn:previous,passed:[other],ended:false};return{turn:0,passed:[],ended:true};}
export function createGame(difficulty='easy'){if(!['easy','hard'].includes(difficulty))throw Error('未知难度。');return{difficulty,trace:[],board:initial(),turn:1,ended:false,last:null,passes:[]};}
export function play(game,index){if(game.ended)throw Error('本局已结束。');if(game.trace.length>=60)throw Error('超过标准局60次落子上限。');const player=game.turn,changed=flips(game.board,index,player);if(!changed.length)throw Error('此点不合法：须沿至少一条方向夹住连续对方棋。');game.board[index]=player;changed.forEach(i=>{game.board[i]=player;});game.trace.push(index);const next=resolve(game.board,player);game.turn=next.turn;game.ended=next.ended;game.last={player,index,flipped:changed,passed:next.passed};if(next.passed.length)game.passes.push({after:game.trace.length,player:next.passed[0]});return game.last;}
export function outcome(game){const c=counts(game.board);return{...c,ended:game.ended,winner:!game.ended?null:c.black===c.white?'draw':c.black>c.white?'black':'white',reason:game.ended?'双方均无合法落子':''};}
export function restore(source){if(!source||typeof source!=='object'||Array.isArray(source)||Object.keys(source).sort().join(',')!=='difficulty,schema,trace'||source.schema!==1)throw Error('仅支持完整schema1源步迹。');if(!Array.isArray(source.trace)||source.trace.length>60||source.trace.some(i=>!Number.isInteger(i)||i<0||i>=64))throw Error('落子步迹须0–63整数，最多60步。');const game=createGame(source.difficulty);source.trace.forEach(i=>play(game,i));return game;}
export function source(game){return{schema:1,difficulty:game.difficulty,trace:[...game.trace]};}
export function encode(value){restore(value);const text=JSON.stringify(value,null,2);if(new TextEncoder().encode(text).length>LIMITS.bytes)throw Error('JSON超过64KiB，未截断。');return text;}
export function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>LIMITS.bytes)throw Error('JSON最多64KiB。');let p=0;const ws=()=>{while(/[ \t\r\n]/.test(text[p]||'')&&p<text.length)p++;};function string(){const start=p++;while(p<text.length){if(text[p]==='\\'){p+=2;continue;}if(text[p++]==='"')return JSON.parse(text.slice(start,p));}throw Error('字符串未闭合。');}function value(depth=0){if(depth>5)throw Error('JSON深度超限。');ws();if(text[p]==='"')return string();if(text[p]==='{'||text[p]==='['){const object=text[p++]==='{',v=object?Object.create(null):[],seen=new Set();ws();if(text[p]===(object?'}':']')){p++;return v;}while(true){ws();let k;if(object){if(text[p]!=='"')throw Error('键格式不合法。');k=string();if(seen.has(k))throw Error('重复JSON键。');seen.add(k);ws();if(text[p++]!==':')throw Error('缺冒号。');}const x=value(depth+1);if(object)v[k]=x;else v.push(x);ws();const c=text[p++];if(c===(object?'}':']'))return v;if(c!==',')throw Error('结构不合法。');}}const token=text.slice(p).match(/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/)?.[0];if(!token)throw Error('JSON值无效。');p+=token.length;if(/^-?\d/.test(token)){if(!/^-?(?:0|[1-9]\d*)$/.test(token))throw Error('源步迹只允许整数词法。');const n=Number(token);if(!Number.isSafeInteger(n))throw Error('整数不安全。');return n;}return JSON.parse(token);}const v=value();ws();if(p!==text.length)throw Error('JSON尾部无效。');return restore(v);}
export function undoRound(game){if(game.ended||!game.trace.length)return null;let replay=createGame(game.difficulty),lastHuman=-1;game.trace.forEach((i,k)=>{if(replay.turn===1)lastHuman=k;play(replay,i);});if(lastHuman<0)return null;return restore({schema:1,difficulty:game.difficulty,trace:game.trace.slice(0,lastHuman)});}
const weights=[100,-25,10,5,5,10,-25,100,-25,-40,-2,-2,-2,-2,-40,-25,10,-2,4,2,2,4,-2,10,5,-2,2,1,1,2,-2,5,5,-2,2,1,1,2,-2,5,10,-2,4,2,2,4,-2,10,-25,-40,-2,-2,-2,-2,-40,-25,100,-25,10,5,5,10,-25,100];
function evaluation(board,player){const mine=legal(board,player),other=legal(board,3-player),c=counts(board),diff=player===1?c.black-c.white:c.white-c.black;if(!mine.length&&!other.length)return diff===0?0:(Math.sign(diff)*100000+diff);return board.reduce((s,v,i)=>s+(v===player?weights[i]:v===3-player?-weights[i]:0),0)+4*(mine.length-other.length)+diff;}
export function chooseAI(board,player,difficulty='easy',budget=LIMITS.aiNodes){validBoard(board);if(!['easy','hard'].includes(difficulty)||!Number.isInteger(budget)||budget<1||budget>LIMITS.aiNodes)throw Error('AI参数无效。');const available=legal(board,player);if(!available.length)return{index:null,nodes:0,depth:0,reason:'无合法落子'};const greedy=available.reduce((best,i)=>flips(board,i,player).length>flips(board,best,player).length?i:best,available[0]);if(difficulty==='easy')return{index:greedy,nodes:available.length,depth:1,reason:'最大即时翻子，同分取行列靠前'};let nodes=0,completed=0,best=greedy;const exhausted={};function search(b,who,depth,alpha,beta,passes=0){if(++nodes>budget)throw exhausted;const moves=legal(b,who);if(!moves.length){if(passes)return evaluation(b,who);return-search(b,3-who,depth,-beta,-alpha,1);}if(depth===0)return evaluation(b,who);let value=-Infinity;for(const i of moves){const child=[...b];child[i]=who;flips(b,i,who).forEach(k=>{child[k]=who;});value=Math.max(value,-search(child,3-who,depth-1,-beta,-alpha));alpha=Math.max(alpha,value);if(alpha>=beta)break;}return value;}
 for(let depth=1;depth<=LIMITS.aiDepth;depth++){let candidate=available[0],score=-Infinity;try{for(const i of available){const child=[...board];child[i]=player;flips(board,i,player).forEach(k=>{child[k]=player;});const s=-search(child,3-player,depth-1,-Infinity,Infinity);if(s>score){score=s;candidate=i;}}best=candidate;completed=depth;}catch(e){if(e!==exhausted)throw e;break;}}return{index:best,nodes:Math.min(nodes,budget),depth:completed,reason:completed?'有限深度启发式搜索':'预算不足，使用合法即时翻子候选'};
}
export function report(game){const replay=createGame(game.difficulty),moves=[];for(const index of game.trace){const step=play(replay,index);moves.push({move:moves.length+1,player:step.player===1?'black':'white',index,coordinate:coordinate(index),flipped:[...step.flipped],flippedCoordinates:step.flipped.map(coordinate),autoPassed:step.passed.map(p=>p===1?'black':'white'),counts:counts(replay.board)});}return{feature:'E008',source:source(game),board:[...game.board],turn:game.turn===0?'ended':game.turn===1?'black':'white',...outcome(game),legalMoves:legal(game.board,game.turn).map(coordinate),moves,rules:{black:'用户先行',white:'本地算法',end:'双方均无合法落子，按现有棋数结算；空格不计',easy:'最大即时翻子；同分按行列',hard:'最大3层alpha-beta、20000节点；位置/行动力/棋数启发式，非最优承诺'}};}
export const coordinate=i=>'ABCDEFGH'[i%8]+(Math.floor(i/8)+1);
export function markdown(r){return '# 黑白棋\n\n'+`难度：${r.source.difficulty==='easy'?'简单':'进阶'}；黑${r.black} / 白${r.white} / 空${r.empty}；${r.ended?`结算 ${r.winner}`:`轮到 ${r.turn}`}。\n\n`+'|步|执子|位置|翻转|自动跳过|黑/白/空|\n|---:|---|---|---|---|---|\n'+r.moves.map(v=>`|${v.move}|${v.player}|${v.coordinate}|${v.flippedCoordinates.join(' ')}|${v.autoPassed.join(' ')}|${v.counts.black}/${v.counts.white}/${v.counts.empty}|`).join('\n')+'\n\n## 完整棋盘\n\n```\n  ABCDEFGH\n'+Array.from({length:8},(_,y)=>`${y+1} ${r.board.slice(y*8,y*8+8).map(v=>['.','B','W'][v]).join('')}`).join('\n')+'\n```\n\n黑先白后，八方向夹住连续对方棋才合法；无棋可下自动跳过，双方均无棋可下按现有棋子数结算，平局允许。两档AI为本地有限算法，不承诺最优。JSON源步迹为合法游戏恢复资料，不是AI真实性或防篡改认证。\n';}
