import {h} from '../../core/ui.js';
import {PICTURES,PALETTE,COLOR_KEY,newWork,color,paint,undo,choose,progress,archive,restore,svg,pngBlob,pngPayload} from './model.mjs';
export default{id:'E036',create(root,ctx={}){
  let state=newWork(),alive=true,active=true,selected=PICTURES[0].regions[0].id,custom=state.color,draft='',message='',saveNotice='',busy=false,nativePending=false,generation=0,persistVersion=0,saving=false,pending=null,permit=true,confirmReplace=false,status=null;
  const config=ctx.config,capable=config&&typeof config.get==='function'&&typeof config.set==='function',bindings=[],urls=new Set(),host=h('div',{'aria-label':'完整涂色作品',style:{width:'100%',maxWidth:'800px',touchAction:'manipulation'}});
  if(capable){try{const raw=config.get(COLOR_KEY,null);if(raw!==null&&raw!==undefined){state=restore(JSON.stringify(raw));selected=PICTURES.find(p=>p.id===state.active).regions[0].id;custom=state.color;saveNotice='已恢复上次全部12张作品与撤销记录。';}else saveNotice='尚无旧档；首次修改后自动保存。';}catch(error){permit=false;saveNotice=`旧自动档无效，未覆盖：${error.message}。可手动另存当前作品，或明确允许替换。`;}}else saveNotice='自动保存接口缺失，请用JSON副本手动保存和恢复。';
  function saveStatus(){if(status)status.textContent=saveNotice;}
  function persist(){if(!capable||!permit)return;pending={snapshot:JSON.parse(archive(state)),version:++persistVersion};saveNotice='正在本地自动保存…';saveStatus();void pump();}
  async function pump(){if(saving)return;saving=true;try{while(pending){const job=pending;pending=null;try{await config.set(COLOR_KEY,job.snapshot);if(alive&&job.version===persistVersion){saveNotice='已自动保存：12张作品、当前图/颜色、最近100步撤销。';saveStatus();}}catch(error){if(alive&&job.version===persistVersion){saveNotice=`自动保存失败：${error.message||'未知错误'}。当前作品仍在内存，请重试或另存JSON。`;saveStatus();}}}}finally{saving=false;}}
  function changed(next,text){state=next;generation++;message=text;const p=PICTURES.find(p=>p.id===state.active);if(!p.regions.some(r=>r.id===selected))selected=p.regions[0].id;custom=state.color;render();persist();}
  function on(node,type,fn){const guarded=async event=>{if(!alive||!active||nativePending)return;try{await fn(event);}catch(error){message=error.message||'操作失败';render();}};node.addEventListener(type,guarded);bindings.push([node,type,guarded]);return node;}
  const button=(text,fn,disabled=false)=>on(h('button',{type:'button',class:'btn',disabled},text),'click',fn);
  function select(label,choices,value,fn){const node=h('select',{'aria-label':label},...choices.map(([id,text])=>h('option',{value:id},text)));node.value=value;on(node,'change',()=>fn(node.value));return h('label',{},label+' ',node);}
  function scrub(){for(const[n,t,f]of bindings.splice(0))n.removeEventListener(t,f);root.replaceChildren();}
  function check(token){if(!alive||!active||document.hidden||token!==generation)throw new DOMException('源作品变化或操作已取消','AbortError');}
  function report(result){message=result?.canceled===true?'已取消另存':result?.ok===true?`已保存新副本：${result.path||''}`:`保存失败：${result?.error||'未返回成功结果'}${result?.partialPath?'；请人工核对：'+result.partialPath:''}`;}
  async function save(type){if(busy)throw Error('已有本地生成/读取，请先完成或取消');const files=window.toolbox?.files,method=type==='png'?'saveBinary':'saveText';if(files?.[method+'SupportsCopyOnly']!==true||typeof files[method]!=='function')throw Error('缺少安全副本导出接口');const frozen=restore(archive(state)),source=type==='json'?archive(frozen):svg(frozen),token=++generation;busy=true;nativePending=false;render();let url,image;try{let payload;if(type==='png'){image=new Image();url=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'}));urls.add(url);await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('作品SVG解码失败'));image.src=url;});check(token);const canvas=document.createElement('canvas');canvas.width=800;canvas.height=600;const context=canvas.getContext('2d');if(!context)throw Error('Canvas 2D不可用');context.drawImage(image,0,0,800,600);payload=await pngPayload(await pngBlob(canvas),frozen.active);check(token);}else payload={content:source,extension:type==='svg'?'svg':'json',defaultName:type==='svg'?`slow-color-${frozen.active}-copy.svg`:'slow-color-all-archive-copy.json',copyOnly:true};nativePending=true;render();const result=await files[method](payload);check(token);report(result);}catch(error){if(alive&&active)message=error.name==='AbortError'?'已取消旧作品生成：源输入变化或取消，未提交结果已忽略':`保存失败：${error.message}`;}finally{if(image){image.onload=image.onerror=null;image.src='';}if(url){URL.revokeObjectURL(url);urls.delete(url);}busy=nativePending=false;if(alive&&active)render();}}
  async function readFile(file){if(!file)return;if(busy)throw Error('已有本地生成/读取');if(file.size>65536)throw Error('作品档限64KiB');busy=true;const token=++generation;render();try{const bytes=await file.arrayBuffer();check(token);if(bytes.byteLength!==file.size)throw Error('文件大小变化');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);restore(text);draft=text;message='文件已校验，点击恢复后才替换全部作品。';}catch(error){if(alive&&active)message=error.name==='AbortError'?'已取消读取':`读取失败：${error.message}`;}finally{busy=false;if(alive&&active)render();}}
  function render(){if(!alive)return;scrub();root.append(h('h2',{},'慢慢涂色'),h('p',{},'十二张原创闭合矢量线稿，自由配色，没有计分或标准答案。点击一个区域只改变它；选择其他图会保留每张作品。所有颜色和记录保留在本机。'));if(!active){root.append(h('p',{},'已离开；自动保存的有效输入可在重开后继续。'));return;}if(message)root.append(h('p',{role:'status'},message));status=h('p',{'aria-label':'自动保存状态'},saveNotice);root.append(status,select('线稿主题',PICTURES.map(p=>[p.id,p.title]),state.active,id=>changed(choose(state,id),'已切换，全部作品的颜色保留。')));
    const p=PICTURES.find(p=>p.id===state.active),count=progress(state);root.append(h('p',{'aria-label':'上色进度'},`${p.title}：已涂${count.painted}/${count.total}区域；主动选白色也算已涂，清除会减少。`),h('div',{'aria-label':'调色板'},...PALETTE.map(value=>{const swatch=button(value,()=>changed({...state,color:value},`当前颜色${value}；点击区域上色。`));swatch.style.backgroundColor=value;swatch.style.color=value==='#6F756B'?'#FFFFFF':'#25342D';swatch.style.minWidth='82px';swatch.style.margin='3px';swatch.setAttribute('aria-pressed',String(state.color===value));return swatch;})));const picker=h('input',{type:'color','aria-label':'颜色选择器',value:state.color});on(picker,'input',()=>changed({...state,color:color(picker.value)},'已更改当前颜色。'));const hex=h('input',{type:'text','aria-label':'自定义颜色',maxLength:7,value:custom,placeholder:'#RRGGBB'});on(hex,'input',()=>{custom=hex.value;});root.append(h('label',{},'自定义颜色 ',hex),picker,button('使用自定义颜色',()=>changed({...state,color:color(custom)},'自定义颜色已选择；点击区域上色。')));
    root.append(select('选择区域',p.regions.map(r=>[r.id,r.label]),selected,value=>{if(!p.regions.some(r=>r.id===value))throw Error('区域无效');selected=value;render();}),button('给选中区域上色',()=>changed(paint(state,state.active,selected,state.color),'已给单个选中区域上色。')),button('清除选中区域颜色',()=>changed(paint(state,state.active,selected,null),'已清除该区域，保留其他区域。')),button('撤销最近上色（最多100步）',()=>changed(undo(state),'已撤销最近上色；切到受影响作品。'),!state.history.length),host);
    host.innerHTML=svg(state);const graphic=host.querySelector('svg');if(graphic){graphic.style.width='100%';graphic.style.height='auto';graphic.style.display='block';}root.append(h('p',{},'未涂区域显示白色；区域轮廓是固定描边。每幅图有独立颜色表，撤销为所有图合计最近100次真实颜色变化；同色重复点击不计一步。无动画、后台计时或网络资源。'));
    const input=h('textarea',{'aria-label':'作品JSON草稿',rows:5,maxLength:65536,style:{width:'100%'}});input.value=draft;on(input,'input',()=>{if(input.value.length>65536||new TextEncoder().encode(input.value).length>65536)throw Error('草稿限64KiB UTF-8');draft=input.value;});const file=h('input',{type:'file',accept:'.json,application/json','aria-label':'导入作品档'});on(file,'change',()=>readFile(file.files?.[0]));root.append(h('h3',{},'全部12张作品存档schema1（≤64KiB）'),input,file,button('恢复草稿（替换全部作品）',()=>changed(restore(draft),'已恢复全部区域颜色和撤销记录。')),button('全部作品放入草稿',()=>{draft=archive(state);message='全部作品已放入草稿，尚未另存副本。';render();}),button('重试自动保存',()=>persist(),!capable||!permit));
    if(!permit){const confirm=h('input',{type:'checkbox','aria-label':'确认替换无效自动档',checked:confirmReplace});on(confirm,'change',()=>{confirmReplace=confirm.checked;});root.append(h('label',{},confirm,'确认替换旧无效自动档（不恢复其未知数据）'),button('允许替换旧自动档并保存当前作品',()=>{if(!confirmReplace)throw Error('请先确认替换旧自动档');permit=true;message='已明确允许用当前有效作品替换旧自动档。';render();persist();},!capable));}
    const files=window.toolbox?.files,canText=files?.saveTextSupportsCopyOnly===true&&typeof files.saveText==='function',canBinary=files?.saveBinarySupportsCopyOnly===true&&typeof files.saveBinary==='function';root.append(button('保存全部作品JSON副本',()=>save('json'),!canText||busy),button('保存当前完整SVG副本',()=>save('svg'),!canText||busy),button('保存当前完整PNG副本',()=>save('png'),!canBinary||busy),h('p',{},'另存只创建新副本，已有目标拒绝。生成PNG期间继续上色、切换或更改输入会使旧生成失效，不提交旧图片；已进入原生保存对话框时输入锁定，请在那里取消。'));
    if(busy){const cancel=h('button',{type:'button',disabled:nativePending},'取消本地生成/读取'),fn=()=>{generation++;message='已请求取消，忽略未提交结果。';render();};cancel.addEventListener('click',fn);bindings.push([cancel,'click',fn]);root.append(cancel,h('p',{},nativePending?'原生另存处理中。':'本地生成/读取中；修改作品会取消旧结果。'));}if(nativePending)for(const node of root.querySelectorAll('button,input,select,textarea'))node.disabled=true;
  }
  const click=event=>{if(!alive||!active||nativePending)return;const path=event.target.closest?.('path[data-region]');if(!path)return;try{const id=path.getAttribute('data-region');selected=id;changed(paint(state,state.active,id,state.color),'已改变点击的单个区域。');}catch(error){message=error.message;render();}};host.addEventListener('click',click);const visibility=()=>{if(!alive||!document.hidden)return;generation++;};document.addEventListener('visibilitychange',visibility);render();
  return{activate(){if(!alive)return;active=true;render();},deactivate(){if(!alive)return;active=false;generation++;render();},destroy(){if(!alive)return;alive=false;active=false;generation++;scrub();host.removeEventListener('click',click);document.removeEventListener('visibilitychange',visibility);for(const url of urls)URL.revokeObjectURL(url);urls.clear();host.innerHTML='';state=null;draft='';status=null;}};
}};
