plugins {
    id 'com.android.application'
}

dependencies {
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}

android {
    namespace 'cn.macpe.agenttoolbox.remote'
    compileSdk 35

    defaultConfig {
        applicationId 'cn.macpe.agenttoolbox.remote'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
