export const MODEL_VERSION='L035-evidence-checklist-v1';
export const FIELDS=[{id:'exposure',label:'暴露'},{id:'outcome',label:'结局'},{id:'confounder',label:'候选混杂'},{id:'selection',label:'选择机制'}];
export const KINDS={record:'用户记录（未验证）',author:'作者声称（待核）',question:'待核假设/疑问'};
const clone=value=>JSON.parse(JSON.stringify(value));
const size=value=>new TextEncoder().encode(JSON.stringify(value)).length;
const emptyField=()=>({description:'',kind:'record',location:'',quote:'',question:''});
export function emptyDraft(){return{title:'',design:'',questions:'',fields:Object.fromEntries(FIELDS.map(({id})=>[id,emptyField()]))};}
export function example(){const draft=emptyDraft();draft.title='虚构教学案例：运动与睡眠';draft.design='仅为教学自造文本，并非真实论文或已核对引文。记录运动频次与睡眠自评的相关设计；年龄、工作压力及招募机制尚未核查。';draft.questions='是否控制年龄与工作压力？样本通过什么渠道进入研究？这些疑问不代表已经发现混杂或选择偏差。';draft.fields.exposure={description:'每周运动次数',kind:'author',location:'虚构材料：方法第1段',quote:'（教学自造句）问卷记录每周运动次数。',question:'频次如何测量、回忆期多长？'};draft.fields.outcome={description:'睡眠质量自评分',kind:'author',location:'虚构材料：方法第2段',quote:'（教学自造句）参与者填写睡眠质量自评分。',question:'量表与随访时间是否明确？'};return draft;}
function text(value,limit,label){if(typeof value!=='string'||value.length>limit)throw new Error(`${label}须文本且≤${limit}个UTF-16代码单元`);if(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(value)||/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(value))throw new Error(`${label}含不支持控制符/孤立代理项`);return value;}
export function validateDraft(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('草稿须对象');if(size(raw)>65536)throw new Error('整个草稿超过64KiB UTF-8，整份拒绝，不截断');const draft={title:text(raw.title,160,'研究名称'),design:text(raw.design,2000,'研究设计描述'),questions:text(raw.questions,2000,'整体待核疑问'),fields:{}};
  if(!raw.fields||typeof raw.fields!=='object'||Array.isArray(raw.fields))throw new Error('须四项设计字段');for(const{ id,label }of FIELDS){const row=raw.fields[id];if(!row||typeof row!=='object'||Array.isArray(row))throw new Error(`${label}字段缺失`);if(typeof row.kind!=='string'||!Object.hasOwn(KINDS,row.kind))throw new Error(`${label}记录性质无效`);draft.fields[id]={description:text(row.description,2000,`${label}描述`),kind:row.kind,location:text(row.location,300,`${label}作者证据位置`),quote:text(row.quote,2000,`${label}作者原句`),question:text(row.question,1000,`${label}待核问题`)};}return draft;}
export function derive(raw){const draft=validateDraft(raw);const rows=FIELDS.map(({id,label})=>{const row=clone(draft.fields[id]),unknown=!row.description.trim(),missing=[];if(!row.location.trim())missing.push('作者证据位置');if(!row.quote.trim())missing.push('作者原句');return{id,label,...row,unknown,status:unknown?'未知':'已填写（未验证）',recordType:KINDS[row.kind],evidence:{status:missing.length?'待补':'已填写（未核真）',missing},checks:[...(unknown?['描述缺失，不能判断该设计要素']:[]),...(missing.length?[`${missing.join('及')}待补，未自动生成引文`]:[]),...(id==='confounder'?['候选混杂是用户记录，不自动确定真实因果角色']:[]),...(id==='selection'?['选择机制记录不等于已经确认或排除选择偏差']:[])]};});return{modelVersion:MODEL_VERSION,title:draft.title,design:draft.design,questions:draft.questions,rows,unknownCount:rows.filter(row=>row.unknown).length,evidencePendingCount:rows.filter(row=>row.evidence.status==='待补').length,conclusion:'本表仅核对填写与证据缺口，不判定研究无偏差、因果效应或可信程度。',boundaries:['“用户记录”不是自动核实的事实；“作者声称”未自动核真。','填满四项不代表排除混杂/选择偏差；空项明确未知，不能自动视为不存在。','原句与位置由用户填写，不联网检索、不补造引文，不自动判断候选混杂。']};}
export function prepareStoredState(raw){const draft=validateDraft(raw),state={schemaVersion:1,...draft};if(size(state)>65536)throw new Error('版本化草稿超过64KiB UTF-8，整份拒绝');return state;}
export function validateStoredState(raw){if(size(raw)>65536)throw new Error('存储草稿超过64KiB UTF-8');if(raw?.schemaVersion!==1)throw new Error('草稿版本不支持');return prepareStoredState(raw);}
const escape=text=>String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function block(text){text=escape(text);const fence='`'.repeat(Math.max(3,...[...text.matchAll(/`+/g)].map(match=>match[0].length+1)));return`${fence}text\n${text}\n${fence}`;}
export function reportMarkdown(payload){const lines=['# L035 研究设计混杂检查',payload.result?.conclusion||'仅有输入草稿，尚未生成核对表。'];if(payload.result){const r=payload.result;lines.push(`未知：${r.unknownCount}/4；作者证据待补：${r.evidencePendingCount}/4`,'## 研究名称与设计',block(r.title+'\n'+r.design),'## 整体待核疑问',block(r.questions));for(const row of r.rows)lines.push(`## ${row.label} — ${row.status}`,`记录性质：${row.recordType}；证据：${row.evidence.status}`, '描述',block(row.description||'（空）'),'作者证据位置',block(row.location||'（空，待补）'),'作者原句（用户提供，未核真）',block(row.quote||'（空，待补）'),'用户待核问题',block(row.question||'（空）'),...row.checks.map(check=>'- '+check));lines.push('## 解释边界',...r.boundaries.map(line=>'- '+line));}lines.push('## 完整记录',block(JSON.stringify(payload,null,2)));return lines.join('\n\n');}
