'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const{Worker}=require('node:worker_threads');
const{writeBinaryCopy}=require('../../../main/feature-binary');
const jobs=new Map(),sha=b=>crypto.createHash('sha256').update(b).digest('hex');let assetChecked=false;
const fail=message=>{throw Error(message);};
function assetCheck(){if(assetChecked)return;const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'vendor/manifest.json'),'utf8'));for(const file of manifest.files){const full=path.join(__dirname,'vendor',file.path);if(!fs.existsSync(full)||fs.statSync(full).size!==file.bytes||sha(fs.readFileSync(full))!==file.sha256)fail('本地资源缺失或SHA不匹配：'+file.path+'。请恢复此功能的原版本资源；不会联网下载。');}assetChecked=true;}
function jobFor(payload,context){const job=jobs.get(context.senderId);if(!job||job.id!==payload.jobId||job.canceled)fail('任务已取消或不属于当前窗口。');return job;}
function dispose(job){if(!job)return;job.canceled=true;job.rejectPending?.(Error('已取消。'));job.ocrWorker?.terminate();job.worker?.terminate();clearTimeout(job.timer);job.source=null;job.upload=null;job.outputs=null;job.pages=[];job.targets.clear();}
function upload(size,hash,kind,meta=null){const max=kind==='pdf'?6291456:4194304;if(!Number.isInteger(size)||size<8||size>max||!/^\w{64}$/.test(hash)||!/^[a-f0-9]{64}$/.test(hash))fail('上传长度或SHA无效。');return{size,hash,kind,meta,chunks:[],received:0,sequence:0};}
function finishUpload(job){const u=job.upload;if(!u||u.received!==u.size)fail('文件分块尚未完整，不允许识别或生成。');const bytes=Buffer.concat(u.chunks);if(sha(bytes)!==u.hash)fail('完整文件SHA不匹配，未使用。');job.upload=null;return{bytes,u};}
async function workerCall(job,operation,pages){if(job.worker)fail('另一个PDF处理仍在运行。');const worker=new Worker(path.join(__dirname,'pdf-worker.cjs'));job.worker=worker;return await new Promise((resolve,reject)=>{let settled=false;const end=(error,result)=>{if(settled)return;settled=true;clearTimeout(job.timer);job.rejectPending=null;job.worker=null;worker.terminate();if(error)reject(error);else resolve(result);};job.rejectPending=error=>end(error);job.timer=setTimeout(()=>end(Error('PDF处理超过30秒，已终止；没有假完成。')),30000);worker.once('error',e=>end(e));worker.once('exit',code=>{if(!settled)end(Error('PDF线程提前退出：'+code));});worker.once('message',r=>r.ok===true?end(null,r):end(Error(r.error)));worker.postMessage({operation,source:job.source,pages});});}
async function recognize(job,bytes){if(!job.ocrWorker)job.ocrWorker=new Worker(path.join(__dirname,'ocr-worker.cjs'));const worker=job.ocrWorker;return await new Promise((resolve,reject)=>{let settled=false;const end=(err,result)=>{if(settled)return;settled=true;clearTimeout(job.timer);job.rejectPending=null;worker.removeListener('message',onMessage);worker.removeListener('error',onError);worker.removeListener('exit',onExit);if(err){worker.terminate();job.ocrWorker=null;reject(err);}else resolve(result);};const onMessage=r=>r.ok===true?end(null,r.words):end(Error(r.error)),onError=e=>end(e),onExit=()=>end(Error('OCR线程提前退出。'));job.rejectPending=error=>end(error);job.timer=setTimeout(()=>end(Error('单页OCR超过60秒，已终止；没有假完成。')),60000);worker.once('message',onMessage);worker.once('error',onError);worker.once('exit',onExit);worker.postMessage({language:job.config.language,png:bytes});});}
async function invoke(operation,payload,context){try{const m=await import('./model.mjs');if(operation==='status'){assetCheck();return{ok:true,engine:'Tesseract.js 6.0.1/core6.0.0',languages:['eng','chi_sim','chi_sim+eng'],offline:true};}
 if(operation==='begin'){assetCheck();dispose(jobs.get(context.senderId));const config=m.settings(payload.settings);if(typeof payload.name!=='string'||payload.name.length>120)fail('来源文件名超过120字符。');const id=crypto.randomBytes(16).toString('hex');const job={id,senderId:context.senderId,config,name:payload.name,upload:upload(payload.size,payload.sha256,'pdf'),pages:[],targets:new Map(),canceled:false,totalPixels:0,totalWords:0};jobs.set(context.senderId,job);return{ok:true,jobId:id};}
 const job=jobFor(payload,context);if(operation==='append'){const u=job.upload;if(!u||payload.sequence!==u.sequence||typeof payload.base64!=='string'||payload.base64.length>32000||payload.base64.length%4)fail('分块序号、容量或上传状态错误。');const bytes=Buffer.from(payload.base64,'base64');if(bytes.toString('base64')!==payload.base64||!bytes.length||bytes.length>24000||u.received+bytes.length>u.size)fail('分块不是规范编码或总长超限。');u.chunks.push(bytes);u.received+=bytes.length;u.sequence++;return{ok:true,received:u.received};}
 if(operation==='seal'){const{bytes,u}=finishUpload(job);if(u.kind!=='pdf'||bytes.subarray(0,5).toString()!=='%PDF-')fail('不是完整PDF。');job.source=bytes;job.sourceSha=sha(bytes);const result=await workerCall(job,'inspect');job.selected=m.parseRange(job.config.range,result.pageCount);job.pageCount=result.pageCount;return{ok:true,pageCount:result.pageCount,selected:job.selected,sourceSha256:job.sourceSha};}
 if(operation==='page_begin'){if(!job.source||job.upload||job.worker||job.busy||job.outputs)fail('页面上传状态无效。');if(job.pages.length>=10||payload.page!==job.selected[job.pages.length])fail('须按选择页顺序上传，不能重复或跳过。');const totalPixels=m.rasterBudget(payload.width,payload.height,job.totalPixels);m.inverse(payload.transform);job.upload=upload(payload.size,payload.sha256,'png',{page:payload.page,width:payload.width,height:payload.height,transform:payload.transform});job.totalPixels=totalPixels;return{ok:true};}
 if(operation==='recognize'){if(job.busy)fail('正在OCR。');const{bytes,u}=finishUpload(job);if(u.kind!=='png'||bytes.length<24||!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||bytes.readUInt32BE(16)!==u.meta.width||bytes.readUInt32BE(20)!==u.meta.height)fail('PNG签名、像素尺寸或数据无效。');job.busy=true;try{const words=await recognize(job,bytes);if(job.canceled)fail('已取消。');const record={...u.meta,imageSha256:u.hash,words:m.validateWords(words,u.meta.width,u.meta.height)};job.totalWords+=record.words.length;if(job.totalWords>10000)fail('累计超过10000词，整次停止，不截断。');job.pages.push(record);return{ok:true,page:record};}finally{job.busy=false;}}
 if(operation==='edit'){if(job.busy||job.worker||!Array.isArray(payload.edits)||payload.edits.length>100)fail('校对状态或批次无效。');const page=job.pages.find(p=>p.page===payload.page);if(!page)fail('未知页面。');const indices=new Set();for(const e of payload.edits){if(!Number.isInteger(e.index)||!page.words[e.index]||indices.has(e.index)||typeof e.text!=='string'||[...e.text].length>128||/[\u0000-\u001f\u007f]/u.test(e.text)||Buffer.from(e.text).toString('utf8')!==e.text)fail('校对索引或文字无效。');indices.add(e.index);}for(const e of payload.edits)page.words[e.index].editedText=e.text;job.outputs=null;job.targets.clear();return{ok:true};}
 if(operation==='build'){if(!job.source||!job.selected||job.busy||job.upload||job.pages.length!==job.selected.length)fail('选择页尚未全部OCR，不能生成。');const result=await workerCall(job,'build',job.pages);if(job.canceled)fail('任务已取消。');const bytes=Buffer.from(result.bytes),output={bytes:bytes.length,sha256:sha(bytes),invisibleTextRenderingMode:3};const r=m.report({name:job.name,sha256:job.sourceSha,bytes:job.source.length,pageCount:job.pageCount},job.config,job.pages,output);const text=job.pages.map(p=>`--- 第${p.page}页 ---\n${m.pageText(p.words)}`).join('\n\n');const outputs={pdf:bytes,json:Buffer.from(JSON.stringify(r,null,2)),md:Buffer.from(m.markdown(r)),txt:Buffer.from(text)};for(const format of ['json','md','txt'])if(outputs[format].length>1048576)fail('完整报告超过1MiB；整份拒绝，不截断。');job.outputs=outputs;job.targets.clear();return{ok:true,output,report:r};}
 if(operation==='read_pdf'){if(!job.outputs||!Number.isInteger(payload.offset)||payload.offset<0||payload.offset>=job.outputs.pdf.length)fail('副本读取位置无效。');return{ok:true,base64:job.outputs.pdf.subarray(payload.offset,payload.offset+24000).toString('base64'),total:job.outputs.pdf.length};}
 if(operation==='choose'){if(!job.outputs||!['pdf','json','md','txt'].includes(payload.format))fail('还没有完整副本。');const{dialog,BrowserWindow,webContents,app}=require('electron');const window=BrowserWindow.fromWebContents(webContents.fromId(context.senderId));if(!window)fail('窗口已关闭。');const format=payload.format,choice=await dialog.showSaveDialog(window,{title:'先选择新副本路径，返回预览后再写入',defaultPath:path.join(app.getPath('downloads'),'ocr-searchable-copy.'+format),filters:[{name:format.toUpperCase(),extensions:[format]}]});if(job.canceled)fail('任务已取消。');if(choice.canceled||!choice.filePath)return{ok:false,canceled:true};const token=crypto.randomBytes(16).toString('hex');job.targets.clear();job.targets.set(token,{format,target:choice.filePath,sha256:sha(job.outputs[format])});return{ok:true,targetToken:token,path:choice.filePath,format,size:job.outputs[format].length,sha256:sha(job.outputs[format]),copyOnly:true};}
 if(operation==='write'){if(payload.copyOnly!==true)fail('必须保存新副本。');const target=job.targets.get(payload.targetToken);if(!target||!job.outputs||sha(job.outputs[target.format])!==target.sha256)fail('路径预览已失效，请重新选择。');job.targets.delete(payload.targetToken);const bytes=job.outputs[target.format];return{...writeBinaryCopy(target.target,{copyOnly:true,base64:bytes.toString('base64'),sha256:target.sha256}),copyOnly:true};}
 fail('未知固定操作。');}catch(error){return{ok:false,error:String(error.message).slice(0,500)};}}
function cancel(jobId,context){const job=jobs.get(context.senderId);if(job?.id===jobId){dispose(job);jobs.delete(context.senderId);}return{ok:true,canceled:true};}
function disposeSender(senderId){dispose(jobs.get(senderId));jobs.delete(senderId);}
module.exports={invoke,cancel,disposeSender};
