'use strict';
const{parentPort}=require('node:worker_threads'),fs=require('node:fs'),path=require('node:path');
const pdf=require('./vendor/pdf-lib.cjs'),fontkit=require('./vendor/fontkit.cjs');
parentPort.on('message',async message=>{try{const m=await import('./model.mjs');const doc=await pdf.PDFDocument.load(new Uint8Array(message.source),{updateMetadata:false,ignoreEncryption:false});if(doc.isEncrypted||doc.catalog.has(pdf.PDFName.of('AcroForm'))||doc.catalog.has(pdf.PDFName.of('Perms')))throw Error('不支持加密、表单或签名 PDF；未生成副本。');if(doc.getPageCount()<1||doc.getPageCount()>20)throw Error('仅支持1–20页PDF。');const pages=doc.getPages();for(const page of pages){const box=page.getCropBox();if([box.x,box.y,box.width,box.height].some(n=>!Number.isFinite(n))||box.width<=0||box.height<=0||box.width>14400||box.height>14400||![0,90,180,270].includes(((page.getRotation().angle%360)+360)%360))throw Error('页面尺寸或旋转不支持。');}
 if(message.operation==='inspect'){parentPort.postMessage({ok:true,pageCount:pages.length});return;}
 if(message.operation!=='build')throw Error('操作无效。');if(!message.pages.some(p=>p.words.some(w=>w.editedText))){const bytes=await doc.save({useObjectStreams:false,addDefaultPage:false});if(bytes.length>m.LIMITS.outputBytes)throw Error('PDF副本超过10MiB。');parentPort.postMessage({ok:true,bytes},[bytes.buffer]);return;}doc.registerFontkit(fontkit);const font=await doc.embedFont(fs.readFileSync(path.join(__dirname,'vendor/font/NotoSansCJKsc-Regular.otf')),{subset:true});const supported=new Set(font.getCharacterSet());let count=0;
 for(const record of message.pages){const page=pages[record.page-1];if(!page)throw Error('未知页面。');const key=page.node.newFontDictionary('OCRText',font.ref);for(let index=0;index<record.words.length;index++){const word=record.words[index],next=record.words[index+1];const text=word.editedText;if(!text)continue;if([...text].some(c=>!supported.has(c.codePointAt(0))))throw Error('文字包含本地字体不支持的字符；请更正或清空该词，未用缺字替代。');if(++count>m.LIMITS.totalWords)throw Error('文字总数超过10000。');const matrix=m.textMatrix(record.transform,word.bbox,font.widthOfTextAtSize(text,1),font.heightAtSize(1));page.pushOperators(pdf.pushGraphicsState(),pdf.beginText(),pdf.setFontAndSize(key,1),pdf.setTextRenderingMode(pdf.TextRenderingMode.Invisible),pdf.setTextMatrix(...matrix),pdf.showText(font.encodeText(text+(next&&next.line===word.line&&!/[\u3400-\u9fff]/u.test(text+next.editedText)?' ':''))),pdf.endText(),pdf.popGraphicsState());}}
 const bytes=await doc.save({useObjectStreams:false,addDefaultPage:false});if(bytes.length>m.LIMITS.outputBytes)throw Error('PDF副本超过10MiB；整份拒绝，没有截断。');parentPort.postMessage({ok:true,bytes},[bytes.buffer]);
 }catch(error){parentPort.postMessage({ok:false,error:String(error.message).slice(0,500)});}});
