import { parseZip, preflight, verifyContents, toBundle } from './zip.mjs';
import { parseXML, decodeUTF8 } from './xml.mjs';

export const LIMITS = Object.freeze({ inputBytes: 2097152, expandedBytes: 2097152, sheets: 10, rows: 1000, columns: 50, cells: 50000, strings: 10000, cellChars: 4096, valueBytes: 1048576, issues: 2000, outputFileBytes: 2097152 });
export const S = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships', REL = 'http://schemas.openxmlformats.org/package/2006/relationships', CT = 'http://schemas.openxmlformats.org/package/2006/content-types', enc = new TextEncoder();
export class SheetError extends Error { constructor(code) { super('XLSX、工作表或容量不支持；未导出数据。'); this.code = code; } }
const fail = code => { throw new SheetError(code); };
const check = options => { if (options.signal?.aborted || options.isCanceled?.()) fail('canceled'); if (options.clock && options.deadline !== undefined && options.clock() >= options.deadline) fail('deadline'); };
export async function sha(data) { return [...new Uint8Array(await crypto.subtle.digest('SHA-256', data))].map(v => v.toString(16).padStart(2, '0')).join(''); }
function children(n, name) { return n.children.filter(c => c.uri === S && c.local === name); }
function only(n, names) { if (n.children.some(c => c.uri !== S || !names.includes(c.local)) || n.texts.some(t => t.text.trim())) fail('worksheet_structure'); }
function text(n) { if (n.children.length || n.texts.length > 1) fail('value_structure'); const value = n.texts.map(t => t.text).join(''); if (value.length > LIMITS.cellChars) fail('cell_text_limit'); return value; }
function decimal(s, max, min = 0) { if (typeof s !== 'string' || !/^(?:0|[1-9]\d*)$/.test(s) || !Number.isSafeInteger(Number(s)) || Number(s) < min || Number(s) > max) fail('integer_or_capacity'); return Number(s); }
export function columnName(index) { if (!Number.isInteger(index) || index < 1 || index > LIMITS.columns) fail('column'); let s = ''; while (index) { index--; s = String.fromCharCode(65 + index % 26) + s; index = Math.floor(index / 26); } return s; }
export function coordinate(value) { const m = /^([A-Z]{1,3})([1-9]\d{0,6})$/.exec(value || ''); if (!m) fail('coordinate'); let col = 0; for (const c of m[1]) col = col * 26 + c.charCodeAt(0) - 64; const row = Number(m[2]); if (col > LIMITS.columns || row > LIMITS.rows + 1) fail('worksheet_capacity'); return { column: col, row, ref: value }; }
function range(value) { const p = value?.split(':'); if (!p || p.length > 2) fail('range'); const start = coordinate(p[0]), end = coordinate(p[1] || p[0]); if (start.row > end.row || start.column > end.column) fail('range'); return { ref: value, start, end }; }
function relTarget(part, target) { if (typeof target !== 'string' || !target || /[\\%?#:\x00-\x20]/.test(target) ) fail('relationship_target'); const absolute = target.startsWith('/'), relative = absolute ? target.slice(1) : target; const base = absolute || part === '_rels/.rels' ? [] : part.slice(0, part.indexOf('/_rels/') + 1).split('/').filter(Boolean); for (const s of relative.split('/')) { if (!s || s === '.') fail('relationship_target'); if (s === '..') { if (!base.length) fail('relationship_target'); base.pop(); } else base.push(s); } return base.join('/'); }
function richString(n) { only(n, ['t', 'r']); let result = ''; for (const child of n.children) { if (child.local === 't') result += text(child); else { only(child, ['rPr', 't']); const ts = children(child, 't'); if (ts.length !== 1) fail('rich_string'); result += text(ts[0]); } } if (result.length > LIMITS.cellChars) fail('cell_text_limit'); return result; }
export async function loadWorkbook(bytes, options = {}) {
 if (!(bytes instanceof Uint8Array) || !bytes.length || bytes.length > LIMITS.inputBytes) fail('input_bytes'); const parsed = parseZip(bytes), pre = preflight(parsed, { allowedBytes: LIMITS.expandedBytes, maxRatio: 1000 }); if (pre.status === 'rejected') fail(pre.risks[0]?.code || 'zip_rejected'); const contents = await verifyContents(bytes, parsed, pre, options); check(options);
 const parts = new Map(contents.files.map(p => [p.path, p])), xmls = new Map(); for (const p of ['[Content_Types].xml', '_rels/.rels', 'xl/workbook.xml', 'xl/_rels/workbook.xml.rels']) if (!parts.has(p)) fail('required_part');
 for (const [path, p] of parts) { if (/vba|activex|embeddings|_xmlsignatures|externalLinks/i.test(path)) fail('active_or_external_workbook_unsupported'); if (/\.(xml|rels)$/i.test(path)) xmls.set(path, parseXML(decodeUTF8(p.data, 1048576))); check(options); }
 const ct = xmls.get('[Content_Types].xml'); if (ct.root.uri !== CT || ct.root.local !== 'Types' || ct.root.texts.some(t => t.text.trim())) fail('content_types'); const overrides = new Map(), defaults = new Map(); for (const n of ct.root.children) { if (n.uri !== CT || n.children.length || n.texts.some(t => t.text.trim()) || !['Default', 'Override'].includes(n.local) || !n.attrs.ContentType) fail('content_types'); if (n.local === 'Default') { const ext = n.attrs.Extension; if (!/^[a-z0-9]+$/i.test(ext || '') || defaults.has(ext.toLowerCase())) fail('content_types'); defaults.set(ext.toLowerCase(), n.attrs.ContentType); } else { const part = n.attrs.PartName; if (!part?.startsWith('/') || !parts.has(part.slice(1)) || overrides.has(part.slice(1))) fail('content_types'); overrides.set(part.slice(1), n.attrs.ContentType); } }
 for (const p of parts.keys()) { if (p === '[Content_Types].xml') continue; const mime = overrides.get(p) || defaults.get(p.split('.').at(-1).toLowerCase()); if (!mime || /macro|vba|oleObject|activex|signature/i.test(mime)) fail('content_type_unsupported'); } if (overrides.get('xl/workbook.xml') !== 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml') fail('xlsx_content_type');
 const allRels = new Map(); let office = 0; for (const [path, doc] of xmls) if (path.endsWith('.rels')) { if (doc.root.uri !== REL || doc.root.local !== 'Relationships' || doc.root.texts.some(t => t.text.trim())) fail('relationships'); let source = ''; if (path !== '_rels/.rels') { const m = /^(?:(.*)\/)?_rels\/([^/]+)\.rels$/.exec(path); if (!m) fail('relationship_source'); source = (m[1] ? m[1] + '/' : '') + m[2]; if (!parts.has(source)) fail('relationship_source'); } const ids = new Map(); allRels.set(source, ids); for (const n of doc.root.children) { if (n.uri !== REL || n.local !== 'Relationship' || n.children.length || n.texts.some(t => t.text.trim()) || !n.attrs.Id || ids.has(n.attrs.Id) || !n.attrs.Type || !n.attrs.Target) fail('relationships'); if (n.attrs.TargetMode === 'External') { if (source === '' || source === 'xl/workbook.xml' || n.attrs.Target.length > 2048) fail('external_relationship_unsupported'); ids.set(n.attrs.Id, { external: true, type: n.attrs.Type }); continue; } if (n.attrs.TargetMode && n.attrs.TargetMode !== 'Internal') fail('relationship_mode'); const target = relTarget(path, n.attrs.Target); if (!parts.has(target)) fail('relationship_missing_target'); ids.set(n.attrs.Id, { target, type: n.attrs.Type }); if (path === '_rels/.rels' && n.attrs.Type === R + '/officeDocument') { office++; if (target !== 'xl/workbook.xml') fail('main_relationship'); } } }
 if (office !== 1) fail('main_relationship'); const book = xmls.get('xl/workbook.xml'); if (book.root.uri !== S || book.root.local !== 'workbook') fail('workbook_root'); const groups = children(book.root, 'sheets'); if (groups.length !== 1) fail('sheets'); only(groups[0], ['sheet']); if (!groups[0].children.length || groups[0].children.length > LIMITS.sheets) fail('sheet_count'); const rels = allRels.get('xl/workbook.xml'), names = new Set(), ids = new Set();
 const sheets = groups[0].children.map(n => { const name = n.attrs.name, id = n.attrs.sheetId, rid = Object.entries(n.attrs).find(([q]) => q.includes(':') && n.ns[q.split(':')[0]] === R && q.split(':')[1] === 'id')?.[1]; if (!name || name.length > 31 || /[\x00-\x1f\[\]:*?\/\\]/.test(name) || names.has(name.toLowerCase()) || ids.has(id) || !['visible', 'hidden', 'veryHidden', undefined].includes(n.attrs.state) || n.children.length || !rels.has(rid)) fail('sheet_metadata'); decimal(id, 2147483647, 1); names.add(name.toLowerCase()); ids.add(id); const rel = rels.get(rid); if (rel.type !== R + '/worksheet' || rel.external || overrides.get(rel.target) !== 'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml') fail('sheet_type_unsupported'); return { id, name, path: rel.target, visibility: n.attrs.state || 'visible' }; });
 let shared = []; const sharedRel = [...rels.values()].filter(r => r.type === R + '/sharedStrings'); if (sharedRel.length > 1) fail('shared_strings'); if (sharedRel.length) { const p = sharedRel[0].target, doc = xmls.get(p); if (!doc || doc.root.uri !== S || doc.root.local !== 'sst') fail('shared_strings'); only(doc.root, ['si']); if (doc.root.children.length > LIMITS.strings) fail('shared_string_count'); shared = doc.root.children.map(richString); if (doc.root.attrs.uniqueCount !== undefined && decimal(doc.root.attrs.uniqueCount, LIMITS.strings) !== shared.length) fail('shared_string_count'); }
 let styleCount = 0; const stylesRel = [...rels.values()].filter(r => r.type === R + '/styles'); if (stylesRel.length > 1) fail('styles'); if (stylesRel.length) { const doc = xmls.get(stylesRel[0].target); if (!doc || doc.root.uri !== S || doc.root.local !== 'styleSheet') fail('styles'); const xfs = children(doc.root, 'cellXfs'); if (xfs.length !== 1 || xfs[0].children.some(n => n.uri !== S || n.local !== 'xf') || xfs[0].children.length > 10000) fail('styles'); styleCount = xfs[0].children.length; if (!styleCount) fail('styles'); if (xfs[0].attrs.count !== undefined && decimal(xfs[0].attrs.count, 10000) !== styleCount) fail('styles'); }
 const props = children(book.root, 'workbookPr'); if (props.length > 1 || props[0]?.attrs.date1904 !== undefined && !['0', '1', 'true', 'false'].includes(props[0].attrs.date1904)) fail('date_system'); const dateSystem = ['1', 'true'].includes(props[0]?.attrs.date1904) ? '1904' : '1900'; const digest = await sha(bytes); check(options); return { sheets, xmls, shared, styleCount, sourceSHA256: digest, sourceBytes: bytes.length, dateSystem };
}
function readCell(n, book) {
 if (Object.keys(n.attrs).some(k => !['r', 's', 't'].includes(k))) fail('cell_attributes_unsupported'); only(n, ['f', 'v', 'is']); const fs = children(n, 'f'), vs = children(n, 'v'), ins = children(n, 'is'); if (fs.length > 1 || vs.length > 1 || ins.length > 1 || vs.length && ins.length) fail('cell_structure'); const formula = !!fs.length, type = n.attrs.t || 'n', style = n.attrs.s === undefined ? 0 : decimal(n.attrs.s, 9999); if (style > 0 && style >= book.styleCount || book.styleCount && style >= book.styleCount) fail('style_reference'); if (formula) { if (Object.keys(fs[0].attrs).some(k => !['t', 'si', 'ref'].includes(k)) || !['normal', 'shared', undefined].includes(fs[0].attrs.t) || fs[0].attrs.si !== undefined && !/^\d{1,8}$/.test(fs[0].attrs.si) || fs[0].attrs.ref !== undefined && !range(fs[0].attrs.ref)) fail('formula_structure_unsupported'); if (fs[0].attrs.t === 'shared' ? fs[0].attrs.si === undefined : fs[0].attrs.si !== undefined || fs[0].attrs.ref !== undefined) fail('formula_structure_unsupported'); text(fs[0]); }
 if (!['inlineStr', 's', 'str', 'b', 'e', 'n'].includes(type)) fail('cell_type_unsupported'); if (formula && ins.length || ins.length && type !== 'inlineStr') fail('cell_structure');
 const raw = vs.length ? text(vs[0]) : null; const cell = { coordinate: n.attrs.r, kind: 'blank', text: '', styleIndex: style, formula, cache: formula ? raw === null || raw === '' && type !== 'str' ? 'missing' : 'stored_unverified_freshness' : 'not_formula', issue: null };
 if (formula && cell.cache === 'missing') { cell.issue = 'formula_cache_missing'; return cell; }
 if (type === 'inlineStr') { if (formula || !ins.length || vs.length) fail('inline_string'); cell.kind = 'string'; cell.text = richString(ins[0]); }
 else if (type === 's') { if (!vs.length || ins.length) fail('shared_string'); const index = decimal(raw, book.shared.length - 1); cell.kind = 'string'; cell.text = book.shared[index]; }
 else if (type === 'str') { if (ins.length) fail('cell_structure'); cell.kind = raw === null ? 'blank' : 'string'; cell.text = raw || ''; }
 else if (type === 'b') { if (!['0', '1'].includes(raw) || ins.length) fail('boolean_value'); cell.kind = 'boolean'; cell.text = raw; }
 else if (type === 'e') { if (!raw || ins.length) fail('error_value'); cell.kind = 'error'; cell.text = raw; cell.issue = formula ? 'cached_formula_error' : 'stored_cell_error'; }
 else if (type === 'n') { if (ins.length) fail('cell_structure'); if (raw !== null && raw !== '') { if (!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(raw) || !Number.isFinite(Number(raw))) fail('numeric_value'); cell.kind = 'number'; cell.text = raw; } }
 else fail('cell_type_unsupported'); if (cell.kind === 'string' && /_x[0-9a-f]{4}_/i.test(cell.text)) fail('escaped_spreadsheet_text_unsupported'); return cell;
}
export function readSheet(book, id, options = {}) {
 check(options); const info = book.sheets.find(s => s.id === id); if (!info) fail('sheet_selection'); const doc = book.xmls.get(info.path); if (!doc || doc.root.uri !== S || doc.root.local !== 'worksheet') fail('worksheet_root'); const data = children(doc.root, 'sheetData'); if (data.length !== 1) fail('sheet_data'); only(data[0], ['row']); const dimensions = children(doc.root, 'dimension'); if (dimensions.length > 1) fail('dimension'); if (dimensions.length) range(dimensions[0].attrs.ref);
 const merges = children(doc.root, 'mergeCells'); if (merges.length > 1) fail('merges'); const ranges = []; if (merges.length) { only(merges[0], ['mergeCell']); if (merges[0].children.length > 200) fail('merges'); for (const n of merges[0].children) { if (n.children.length || n.texts.some(t => t.text.trim())) fail('merges'); ranges.push(range(n.attrs.ref).ref); } if (merges[0].attrs.count !== undefined && decimal(merges[0].attrs.count, 200) !== ranges.length) fail('merges'); }
 const cells = new Map(); let rowBefore = 0, lastRow = 1, lastColumn = 0, bytes = 0; for (const row of data[0].children) { check(options); const r = decimal(row.attrs.r, LIMITS.rows + 1, 1); if (r <= rowBefore) fail('row_order_or_duplicate'); rowBefore = r; lastRow = Math.max(lastRow, r); only(row, ['c']); let columnBefore = 0; for (const n of row.children) { const c = coordinate(n.attrs.r); if (c.row !== r || c.column <= columnBefore || cells.has(c.ref)) fail('cell_order_or_duplicate'); columnBefore = c.column; lastColumn = Math.max(lastColumn, c.column); const cell = readCell(n, book); bytes += enc.encode(cell.text).length; if (bytes > LIMITS.valueBytes || cells.size >= LIMITS.cells) fail('expanded_cell_budget'); cells.set(c.ref, cell); } }
 if (!lastColumn) fail('empty_sheet'); return { ...info, cells, lastRow, lastColumn, merges: ranges, dateSystem: book.dateSystem };
}
const blank = ref => ({ coordinate: ref, kind: 'blank', text: '', styleIndex: 0, formula: false, cache: 'not_formula', issue: null });
function cellAt(sheet, col, row) { const ref = columnName(col) + row; return sheet.cells.get(ref) || blank(ref); }
export function headers(sheet) { return Array.from({ length: sheet.lastColumn }, (_, i) => { const cell = cellAt(sheet, i + 1, 1); return { column: i + 1, letter: columnName(i + 1), coordinate: cell.coordinate, name: cell.text, valid: cell.kind === 'string' && !!cell.text.trim() && cell.text.trim() === cell.text && !cell.formula && !cell.issue && cell.text.length <= 64 }; }); }
function csvField(s) { return '"' + s.replaceAll('"', '""') + '"'; }
function protect(s) { return /^[\s\u0000-\u001f]*[=+\-@]/u.test(s) || /^[\t\r\n]/.test(s) ? "'" + s : s; }
async function outputFile(path, data, options) { if (data.length > LIMITS.outputFileBytes) fail('output_file_budget'); const digest = await sha(data); check(options); return { path, data, bytes: data.length, sha256: digest }; }
export async function validateSheet(book, sheet, requiredColumns, options = {}) {
 if (!Array.isArray(requiredColumns) || requiredColumns.length > sheet.lastColumn || new Set(requiredColumns).size !== requiredColumns.length || requiredColumns.some(n => !Number.isInteger(n) || n < 1 || n > sheet.lastColumn)) fail('required_columns'); check(options); const cols = headers(sheet), issues = [], blockers = [], seen = new Map();
 const add = issue => { issues.push(issue); if (issues.length > LIMITS.issues) fail('issue_count'); };
 for (const h of cols) { if (!h.valid) blockers.push({ code: 'header_not_plain_nonempty_text', coordinate: h.coordinate }); else { const key = h.name.normalize('NFC').toLowerCase(); if (seen.has(key)) blockers.push({ code: 'duplicate_header', coordinate: h.coordinate, relatedCoordinate: seen.get(key) }); else seen.set(key, h.coordinate); } const cell = cellAt(sheet, h.column, 1); if (cell.issue) add({ coordinate: cell.coordinate, row: 1, column: h.column, code: cell.issue, storedError: cell.kind === 'error' ? cell.text : null }); }
 for (const ref of sheet.merges) blockers.push({ code: 'merged_cells_block_ready', range: ref }); const rows = [], accepted = [], protectedCoordinates = []; let formulaCount = 0;
 for (let row = 2; row <= sheet.lastRow; row++) { check(options); const values = [], rowIssues = []; for (let col = 1; col <= sheet.lastColumn; col++) { const c = cellAt(sheet, col, row); values.push({ coordinate: c.coordinate, kind: c.kind, text: c.text, styleIndex: c.styleIndex, formula: c.formula, cache: c.cache }); if (c.formula) formulaCount++; if (c.issue) { const issue = { coordinate: c.coordinate, row, column: col, code: c.issue, storedError: c.kind === 'error' ? c.text : null }; add(issue); rowIssues.push(issue); } else if (requiredColumns.includes(col) && (c.kind === 'blank' || c.kind === 'string' && !c.text.trim())) { const issue = { coordinate: c.coordinate, row, column: col, code: 'required_blank', storedError: null }; add(issue); rowIssues.push(issue); } }
  const record = { sourceRow: row, status: blockers.length ? 'blocked_by_sheet_structure' : rowIssues.length ? 'rejected' : 'ready_using_stored_values', values, issueCoordinates: rowIssues.map(i => i.coordinate) }; rows.push(record); if (record.status === 'ready_using_stored_values') accepted.push(record); }
 const dataset = { format: 'T029-ready-stored-data', version: 1, sheet: sheet.name, sourceSHA256: book.sourceSHA256, dateSystem: book.dateSystem, columns: cols.map(h => ({ column: h.column, coordinate: h.coordinate, name: h.name })), numberRepresentation: '原XML十进制文本；不转换日期/格式/二进制浮点，不执行公式或证明缓存新鲜。', rows: accepted };
 const files = []; if (accepted.length) { const json = enc.encode(JSON.stringify(dataset, null, 2) + '\n'); files.push(await outputFile('data.json', json, options)); const csvRows = [cols.map(h => { const safe = protect(h.name); if (safe !== h.name) protectedCoordinates.push(h.coordinate); return csvField(safe); }).join(',')]; for (const r of accepted) csvRows.push(r.values.map(v => { const safe = v.kind === 'string' ? protect(v.text) : v.text; if (safe !== v.text) protectedCoordinates.push(v.coordinate); return csvField(safe); }).join(',')); files.push(await outputFile('data.csv', enc.encode(csvRows.join('\r\n') + '\r\n'), options)); }
 const report = { format: 'T029-xlsx-data-validation', version: 1, sourceSHA256: book.sourceSHA256, sourceBytes: book.sourceBytes, sheet: { id: sheet.id, name: sheet.name, path: sheet.path, visibility: sheet.visibility, scope: '只检查选定工作表A1起始、第一行为表头；不检查其他工作表数据。' }, dateSystem: book.dateSystem, requiredColumns: requiredColumns.map(n => ({ column: n, name: cols[n - 1].name, headerCoordinate: cols[n - 1].coordinate })), headers: cols, blockers, issues, inputRows: rows.length, readyRows: accepted.length, excludedRows: rows.length - accepted.length, formulaCount, recalculated: false, cacheFreshness: 'unknown', csvFormulaProtection: { stringPrefix: '危险文本前加单引号；JSON保留原文', protectedCoordinates }, rows, outputs: files.map(({ path, bytes, sha256 }) => ({ path, bytes, sha256 })), scope: '不重算/执行公式。错误或必填空行完整留在report，只有明确合格行成为data副本；合并或表头问题整表不开放ready副本。数值为原始存储十进制字符串和样式编号；不进行日期/显示格式转换。' };
 const reportFile = await outputFile('report.json', enc.encode(JSON.stringify(report, null, 2) + '\n'), options); files.push(reportFile); check(options); return { report, dataset, files, totalBytes: files.reduce((n, f) => n + f.bytes, 0) };
}
export function bundle(result) { if (!result?.report?.readyRows || result.report.blockers.length) fail('no_ready_data'); return toBundle(result, 'Excel数据验收副本'); }
