export const LIMITS=Object.freeze({bytes:131072,strokes:100,points:4000,perStroke:512,strokeMs:30000,size:1000,pngBytes:10485760,gapMs:200});
export const clone=v=>JSON.parse(JSON.stringify(v));
const integer=(v,min,max)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
const exact=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))throw Error('工程字段不完整或未知。');};
export function color(c){if(typeof c!=='string'||!/^#[0-9a-fA-F]{6}$/.test(c))throw Error('颜色须#RRGGBB。');return c.toLowerCase();}
function brush(v){exact(v,['axes','mirror','width','color']);if(!integer(v.axes,2,12)||typeof v.mirror!=='boolean'||!integer(v.width,1,50)||color(v.color)!==v.color)throw Error('笔刷须2–12轴、镜像布尔、粗细1–50、规范小写颜色。');}
export function createProject(){return{schema:1,brush:{axes:6,mirror:false,width:12,color:'#2b8a78'},background:'#faf7ef',strokes:[]};}
export const count=v=>v.strokes.reduce((n,s)=>n+s.points.length,0);
export function validate(v){exact(v,['schema','brush','background','strokes']);if(v.schema!==1||color(v.background)!==v.background||!Array.isArray(v.strokes)||v.strokes.length>100)throw Error('schema1、背景及100笔上限无效。');brush(v.brush);let total=0;for(const s of Array.from(v.strokes)){exact(s,['axes','mirror','width','color','points']);brush({axes:s.axes,mirror:s.mirror,width:s.width,color:s.color});if(!Array.isArray(s.points)||s.points.length<1||s.points.length>512)throw Error('单笔须1–512点。');let prev=-1;for(const p of Array.from(s.points)){if(!Array.isArray(p)||p.length!==3||!integer(p[0],0,1000)||!integer(p[1],0,1000)||!integer(p[2],0,30000)||p[2]<prev)throw Error('点须[x,y,笔内ms]，0–1000整数/不倒序/≤30秒。');prev=p[2];}if(s.points[0][2]!==0)throw Error('每笔首点须时间0。');total+=s.points.length;}if(total>4000)throw Error('最多4000源点，整笔拒绝未截断。');if(new TextEncoder().encode(JSON.stringify(v)).length>131072)throw Error('完整工程超过128KiB，未截断。');return v;}
export function restore(v){return clone(validate(v));}
export const encode=v=>JSON.stringify(validate(v));
export function stroke(v,points){validate(v);const s={...v.brush,points:clone(points)},next={...v,strokes:[...v.strokes,s]};validate(next);v.strokes.push(s);return s;}
export function undo(v){validate(v);return v.strokes.pop()||null;}
export function paths(s,limit=s.points.length){const n=Math.min(s.points.length,limit),copies=[];for(let i=0;i<s.axes;i++){const a=2*Math.PI*i/s.axes,c=Math.cos(a),sin=Math.sin(a);for(const reflect of s.mirror?[1,-1]:[1])copies.push(s.points.slice(0,n).map(([x,y])=>{const dx=x-500,dy=(y-500)*reflect;return[500+dx*c-dy*sin,500+dx*sin+dy*c];}));}return copies;}
export function drawStroke(c,s,limit=s.points.length){if(!limit)return;c.strokeStyle=c.fillStyle=s.color;c.lineWidth=s.width;c.lineCap=c.lineJoin='round';for(const points of paths(s,limit)){if(points.every(p=>p[0]===points[0][0]&&p[1]===points[0][1])){c.beginPath();c.arc(points[0][0],points[0][1],s.width/2,0,2*Math.PI);c.fill();}else{c.beginPath();c.moveTo(...points[0]);for(let i=1;i<points.length;i++)c.lineTo(...points[i]);c.stroke();}}}
export function paint(canvas,v,n=v.strokes.length){canvas.width=canvas.height=1000;const c=canvas.getContext('2d');if(!c)throw Error('Canvas不可用。');c.fillStyle=v.background;c.fillRect(0,0,1000,1000);for(let i=0;i<n;i++)drawStroke(c,v.strokes[i]);}
export const duration=v=>v.strokes.reduce((n,s,i)=>n+Math.max(1,s.points.at(-1)[2])+(i?200:0),0);
export function position(v,ms){if(!Number.isFinite(ms)||ms<0)throw Error('重放时间无效。');let at=0;for(let i=0;i<v.strokes.length;i++){const s=v.strokes[i],end=at+Math.max(1,s.points.at(-1)[2]);if(ms<end){let n=0;while(n<s.points.length&&s.points[n][2]<=ms-at)n++;return{completed:i,index:i,points:n,done:false};}at=end;if(i+1<v.strokes.length){if(ms<at+200)return{completed:i+1,index:-1,points:0,done:false};at+=200;}}return{completed:v.strokes.length,index:-1,points:0,done:true};}
// Own strict bounded JSON parser, copied from own E014 integer/duplicate-key parser, no cross-feature runtime imports.
export function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>LIMITS.bytes)throw Error('JSON最多128KiB。');let p=0;const ws=()=>{while(p<text.length&&/[ \t\r\n]/.test(text[p]))p++;};function string(){const start=p++;while(p<text.length){if(text[p]==='\\'){p+=2;continue;}if(text[p++]==='"')return JSON.parse(text.slice(start,p));}throw Error('字符串未闭合。');}function value(depth=0){if(depth>8)throw Error('JSON层级超限。');ws();if(text[p]==='"')return string();if(text[p]==='{'||text[p]==='['){const obj=text[p++]==='{',out=obj?Object.create(null):[],seen=new Set();ws();if(text[p]===(obj?'}':']')){p++;return out;}while(true){ws();let key;if(obj){if(text[p]!=='"')throw Error('键无效。');key=string();if(seen.has(key))throw Error('重复JSON键。');seen.add(key);ws();if(text[p++]!==':')throw Error('缺冒号。');}const v=value(depth+1);if(obj)out[key]=v;else out.push(v);ws();const c=text[p++];if(c===(obj?'}':']'))return out;if(c!==',')throw Error('JSON结构无效。');}}const t=text.slice(p).match(/^(?:null|true|false|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/)?.[0];if(!t)throw Error('JSON值无效。');p+=t.length;if(/^-?\d/.test(t)){if(!/^-?(?:0|[1-9]\d*)$/.test(t)||!Number.isSafeInteger(Number(t)))throw Error('只接受安全整数词法。');return Number(t);}return JSON.parse(t);}const v=value();ws();if(p!==text.length)throw Error('JSON尾部无效。');return restore(v);}
export function markdown(v){validate(v);return '# 万花筒绘画\n\n'+`${v.strokes.length}笔 / ${count(v)}源点；1000×1000、背景${v.background}。旋转n轴每360/n度复制，镜像为中心水平轴反射后旋转；每笔独立参数快照。重放保留笔内时间，笔间200ms，不含发呆间隔。完整重放${duration(v)}ms。\n\n`+'|笔1起|轴|镜像|粗细|颜色|点数|笔内ms|\n|---:|---:|---|---:|---|---:|---:|\n'+v.strokes.map((s,i)=>`|${i+1}|${s.axes}|${s.mirror}|${s.width}|${s.color}|${s.points.length}|${s.points.at(-1)[2]}|`).join('\n')+'\n\n## 完整可重放源工程\n\n```json\n'+encode(v)+'\n```\n';}
