const clone=x=>JSON.parse(JSON.stringify(x));
const bytes=s=>new TextEncoder().encode(s).length;
export function minutes(value,label,{min=0,max=1440}={}){const text=String(value);if(!/^(0|[1-9]\d{0,4})$/.test(text)||+text<min||+text>max)throw Error(`${label}须为${min}–${max}整数分钟。`);return +text;}
export function date(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))throw Error('日期须为YYYY-MM-DD。');const year=+value.slice(0,4),month=+value.slice(5,7),day=+value.slice(8);const leap=year%4===0&&(year%100!==0||year%400===0);if(year<1900||year>2100||month<1||month>12||day<1||day>[31,leap?29:28,31,30,31,30,31,31,30,31,30,31][month-1])throw Error('日期须为1900–2100年的真实公历日期。');return value;}
function text(value,label,max){if(typeof value!=='string'||!value.trim()||value.length>max||/[\x00-\x1f\x7f]/.test(value))throw Error(`${label}须为1–${max}字符文本，不含控制字符。`);return value.trim();}
export function example(){return{days:Array.from({length:7},(_,i)=>({date:`2026-10-${String(5+i).padStart(2,'0')}`,available:i<5?'240':'0',fixed:'0'})),tasks:Array.from({length:5},(_,i)=>({id:'T'+(i+1),title:['撰写报告','整理资料','复核数据','完善方案','提交成果'][i],date:`2026-10-0${5+i}`,minutes:i?'180':'360',deferrable:i===0}))};}
export function calculateCapacity(input){
 if(!input||!Array.isArray(input.days)||input.days.length<1||input.days.length>31||!Array.isArray(input.tasks)||input.tasks.length>200)throw Error('需要1–31个日期、0–200项任务。');
 const dates=new Set(),ids=new Set();
 const days=input.days.map((d,i)=>{if(!d||typeof d!=='object')throw Error('日期行格式无效。');const key=date(d.date);if(dates.has(key))throw Error(`日期重复：${key}`);dates.add(key);return{date:key,availableMinutes:minutes(d.available,`日期${i+1}可用时长`),fixedMinutes:minutes(d.fixed,`日期${i+1}固定占用`),tasks:[]};}).sort((a,b)=>a.date.localeCompare(b.date));
 const map=new Map(days.map(d=>[d.date,d]));
 const tasks=input.tasks.map((t,i)=>{if(!t||typeof t!=='object')throw Error('任务行格式无效。');const id=text(t.id,`任务${i+1}编号`,32);if(ids.has(id))throw Error(`任务编号重复：${id}`);ids.add(id);const key=date(t.date);if(!map.has(key))throw Error(`任务${id}的日期${key}未列入容量表，请补齐日期或手动修改分配。`);if(typeof t.deferrable!=='boolean')throw Error(`任务${id}的可延后标记须为布尔值。`);const row={id,title:text(t.title,`任务${id}标题`,120),date:key,minutes:minutes(t.minutes,`任务${id}估时`,{min:1}),deferrable:t.deferrable};map.get(key).tasks.push(row);return row;});
 for(const day of days){day.taskMinutes=day.tasks.reduce((s,t)=>s+t.minutes,0);day.loadMinutes=day.fixedMinutes+day.taskMinutes;day.deficitMinutes=Math.max(0,day.loadMinutes-day.availableMinutes);day.spareMinutes=Math.max(0,day.availableMinutes-day.loadMinutes);}
 const sum=key=>days.reduce((s,d)=>s+d[key],0);
 const totals={availableMinutes:sum('availableMinutes'),fixedMinutes:sum('fixedMinutes'),taskMinutes:sum('taskMinutes'),loadMinutes:sum('loadMinutes'),dailyDeficitMinutes:sum('deficitMinutes'),dailySpareMinutes:sum('spareMinutes')};totals.netMinutes=totals.availableMinutes-totals.loadMinutes;
 const candidates=days.flatMap(d=>d.deficitMinutes?d.tasks.filter(t=>t.deferrable).map(t=>({...t,originalDate:t.date,originalEstimateMinutes:t.minutes,dayDeficitMinutes:d.deficitMinutes,deficitIfRemovedMinutes:Math.max(0,d.deficitMinutes-t.minutes)})):[]).sort((a,b)=>a.originalDate.localeCompare(b.originalDate)||b.minutes-a.minutes||a.id.localeCompare(b.id));
 return{feature:'T090',schemaVersion:1,inputs:clone(input),days,tasks,totals,overloadedDates:days.filter(d=>d.deficitMinutes>0).map(d=>d.date),candidates,policy:'仅核算手填日期、整数分钟、固定占用和任务估时。候选只列超负荷日中用户标记可延后的任务；移除后的缺口为单项独立试算，不代表新日期有容量，不自动修改日程。'};
}
export function restore(json){if(typeof json!=='string'||bytes(json)>65536)throw Error('导入草稿最多64KiB UTF-8。');const data=JSON.parse(json);if(data.feature!=='T090'||data.schemaVersion!==1)throw Error('仅支持T090版本1草稿或报告。');const input=data.inputs;calculateCapacity(input);return clone(input);}
export function duration(n){return`${Math.floor(n/60)}小时${n%60}分钟（${n}分钟）`;}
export function markdown(report){const safe=s=>String(s).replace(/[|\r\n]/g,' ').replace(/`/g,"'");return`# T090 计划工时与容量核算\n\n${report.policy}\n\n总可用${duration(report.totals.availableMinutes)}，总负荷${duration(report.totals.loadMinutes)}，总量净余${report.totals.netMinutes}分钟。逐日缺口合计${duration(report.totals.dailyDeficitMinutes)}；其他日期余量合计${duration(report.totals.dailySpareMinutes)}，两者不能自动抵消。\n\n|日期|可用分钟|固定占用|任务分钟|负荷|缺口|余量|\n|---|---:|---:|---:|---:|---:|---:|\n${report.days.map(d=>`|${d.date}|${d.availableMinutes}|${d.fixedMinutes}|${d.taskMinutes}|${d.loadMinutes}|${d.deficitMinutes}|${d.spareMinutes}|`).join('\n')}\n\n## 人工调整候选（逐项独立试算）\n\n${report.candidates.map(t=>`- ${safe(t.id)} ${safe(t.title)}：原日期${t.originalDate}，原估时${t.originalEstimateMinutes}分钟；若仅从原日期移走此项，该日缺口${t.dayDeficitMinutes}→${t.deficitIfRemovedMinutes}分钟。`).join('\n')||'无候选；未标记可延后的任务不在此表。'}\n\n## 完整原始输入\n\n\`\`\`json\n${JSON.stringify(report.inputs,null,2).replace(/`/g,'\\u0060')}\n\`\`\`\n`;}
