'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto'),{pathToFileURL}=require('node:url'),{performance}=require('node:perf_hooks');
const moduleReady=import(pathToFileURL(path.join(__dirname,'model.mjs')).href);
function createHost({fileSystem=fs,platform=process.platform,chooseFiles=async senderId=>{const{dialog,BrowserWindow,webContents}=require('electron');return dialog.showOpenDialog(BrowserWindow.fromWebContents(webContents.fromId(senderId)),{title:'选择需要修改时间副本的原文件',properties:['openFile','multiSelections','dontAddToRecent']});},chooseParent=async senderId=>{const{dialog,BrowserWindow,webContents}=require('electron');return dialog.showOpenDialog(BrowserWindow.fromWebContents(webContents.fromId(senderId)),{title:'选择新副本目录的父目录',properties:['openDirectory','dontAddToRecent']});}}={}){
 const states=new Map(),running=new Set(),same=(a,b)=>a.dev===b.dev&&a.ino===b.ino,unchanged=(a,b)=>same(a,b)&&a.size===b.size&&a.mtimeMs===b.mtimeMs&&a.ctimeMs===b.ctimeMs;
 function state(id){if(!Number.isSafeInteger(id)||id<1)throw Error('窗口无效');if(!states.has(id)){if(states.size>=32)throw Error('窗口容量');states.set(id,{busy:false,files:null,parent:null,plan:null,job:null,seen:new Set()});}return states.get(id);}
 async function ordinary(value,directory){if(typeof value!=='string'||value.length>4096||!path.isAbsolute(value)||platform==='win32'&&!/^[A-Za-z]:[\\/]/.test(value))throw Error('仅允许普通绝对路径');const first=await fileSystem.lstat(value);if(first.isSymbolicLink()||!(directory?first.isDirectory():first.isFile()))throw Error('最终链接或类型不支持');const canonical=await fileSystem.realpath(value),second=await fileSystem.lstat(canonical);if(!same(first,second)||second.isSymbolicLink()||!(directory?second.isDirectory():second.isFile()))throw Error('来源已改变');return{path:canonical,stat:second};}
 function exact(p,keys){if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).sort().join('|')!==keys.slice().sort().join('|'))throw Error('字段无效');}
 return{async invoke(op,p,{senderId}={}){let s,job,locked=false;try{s=state(senderId);if(s.busy)throw Error('本窗口任务未收尾');s.busy=true;locked=true;if(op==='copy'&&/^[-A-Za-z0-9_]{12,64}$/.test(p?.jobId||''))s.job=job={id:p.jobId,canceled:false,start:performance.now()};const m=await moduleReady;if(states.get(senderId)!==s)throw Error('窗口已离开');
 if(op==='choose_files'){exact(p,[]);s.plan=null;s.files=null;const r=await chooseFiles(senderId);if(states.get(senderId)!==s)throw Error('窗口已离开');if(r?.canceled)return{ok:false,canceled:true};if(!Array.isArray(r?.filePaths)||!r.filePaths.length||r.filePaths.length>m.LIMITS.files)throw Error('选择1–50文件');const entries=[];let bytes=0;for(const raw of r.filePaths){const e=await ordinary(raw,false);if(!Number.isSafeInteger(e.stat.size)||e.stat.size>m.LIMITS.fileBytes)throw Error('单文件超过32MiB');bytes+=e.stat.size;if(bytes>m.LIMITS.totalBytes)throw Error('总量超过128MiB');entries.push(e);}m.fileNames(entries.map(e=>path.basename(e.path)));s.files={id:randomUUID(),entries};return{ok:true,selection:{id:s.files.id,entries:entries.map(e=>({path:e.path,name:path.basename(e.path),bytes:e.stat.size,mtimeMs:e.stat.mtimeMs,mtimeUTC:new Date(e.stat.mtimeMs).toISOString()}))}};}
 if(op==='choose_parent'){exact(p,[]);s.plan=null;s.parent=null;const r=await chooseParent(senderId);if(states.get(senderId)!==s)throw Error('窗口已离开');if(r?.canceled)return{ok:false,canceled:true};if(r?.filePaths?.length!==1)throw Error('选择一个父目录');s.parent=await ordinary(r.filePaths[0],true);s.parent.id=randomUUID();return{ok:true,parent:{id:s.parent.id,path:s.parent.path}};}
 if(op==='preview'){exact(p,['selectionId','parentId','folder','offsetSeconds']);s.plan=null;if(p.selectionId!==s.files?.id||p.parentId!==s.parent?.id)throw Error('需要当前选择文件和父目录');m.offset(p.offsetSeconds);m.folderName(p.folder);const parent=await ordinary(s.parent.path,true);if(!same(parent.stat,s.parent.stat))throw Error('父目录变化');const destination=path.join(parent.path,p.folder);try{await fileSystem.lstat(destination);throw Error('目标已存在');}catch(e){if(e.code!=='ENOENT')throw e;}const entries=[];let total=0;for(const e of s.files.entries){const live=await ordinary(e.path,false);if(!unchanged(e.stat,live.stat))throw Error('来源自选择后改变，请重新选择');total+=live.stat.size;entries.push({name:path.basename(e.path),source:e.path,bytes:live.stat.size,originalMtimeMs:live.stat.mtimeMs,originalMtimeUTC:new Date(live.stat.mtimeMs).toISOString(),plannedMtimeMs:m.shifted(live.stat.mtimeMs,p.offsetSeconds).ms,plannedMtimeUTC:m.shifted(live.stat.mtimeMs,p.offsetSeconds).iso,originalAtimeMs:live.stat.atimeMs,stat:live.stat});}const id=randomUUID();s.plan={id,parent,destination,entries,offsetSeconds:p.offsetSeconds};const preview={format:'T019-time-copy-plan',version:1,planId:id,destination,offsetSeconds:p.offsetSeconds,totalBytes:total,entries:entries.map(({stat,...e})=>e),scope:'只调整副本mtime，保持副本atime为复制前来源值。原件不写；OS可能在读取原件时更新原atime。creation/birth/ctime不承诺复制。UTC绝对秒偏移，不是日历/DST调整。'};m.reportText(preview,'json');return{ok:true,preview};}
 if(op!=='copy')throw Error('操作不支持');exact(p,['planId','jobId','confirmed']);if(!job||p.confirmed!==true||p.planId!==s.plan?.id||s.seen.has(job.id)||s.seen.size>=128||running.size>=4)throw Error('需要完整当前计划和明确确认，或任务容量已满');s.seen.add(job.id);running.add(job);const plan=s.plan;s.plan=null;const report={format:'T019-time-copy-report',version:1,destination:plan.destination,offsetSeconds:plan.offsetSeconds,startedAtUTC:new Date().toISOString(),complete:false,canceled:false,created:false,entries:[],plan:plan.entries.map(({stat,...e})=>e),manifestWritten:false,scope:'只修改本次新目录副本mtime；原mtime/内容不写。源atime可能由OS读取更新，不回写。复制非原子事务，不锁住源或目录；失败留存本次部分副本以人工核对。'};
 const check=()=>{if(job.canceled)throw Error('已取消');if(performance.now()-job.start>m.LIMITS.runMs)throw Error('30秒协作期限');if(states.get(senderId)!==s)throw Error('窗口已销毁');};
 try{check();const parent=await ordinary(plan.parent.path,true);check();if(!same(parent.stat,plan.parent.stat))throw Error('父目录身份改变');await fileSystem.mkdir(plan.destination);report.created=true;const own=await ordinary(plan.destination,true);check();for(const e of plan.entries){let input=null,output=null;const record={name:e.name,source:e.source,originalMtimeMs:e.originalMtimeMs,plannedMtimeMs:e.plannedMtimeMs,status:'not_copied'};report.entries.push(record);try{check();const dir=await ordinary(plan.destination,true);if(!same(dir.stat,own.stat))throw Error('副本目录变化');const now=await ordinary(e.source,false);if(!unchanged(now.stat,e.stat))throw Error('来源在预览后改变');input=await fileSystem.open(e.source,'r');const opened=await input.stat();if(!unchanged(opened,e.stat))throw Error('源句柄身份变化');output=await fileSystem.open(path.join(plan.destination,e.name),'wx',0o600);record.status='partial';const hash=createHash('sha256'),buffer=Buffer.alloc(65536);let position=0;while(position<e.bytes){check();const read=await input.read(buffer,0,Math.min(buffer.length,e.bytes-position),position);check();if(!read.bytesRead)throw Error('来源提前结束');hash.update(buffer.subarray(0,read.bytesRead));let n=0;while(n<read.bytesRead){check();const write=await output.write(buffer,n,read.bytesRead-n,position+n);check();if(!write.bytesWritten)throw Error('副本写入停止');n+=write.bytesWritten;}position+=read.bytesRead;}const after=await input.stat();if(!unchanged(after,e.stat))throw Error('复制期间源元数据改变');check();await output.utimes(e.originalAtimeMs/1000,e.plannedMtimeMs/1000);check();const copied=await output.stat();if(copied.size!==e.bytes||Math.abs(copied.mtimeMs-e.plannedMtimeMs)>2)throw Error('副本大小或时间精度不支持');await output.close();output=null;await input.close();input=null;record.status='copied';record.bytes=e.bytes;record.sha256=hash.digest('hex');record.actualCopyMtimeMs=copied.mtimeMs;record.sourceMtimeAfterMs=after.mtimeMs;record.sourceAtimeAfterMs=after.atimeMs;}finally{const closed=await Promise.allSettled([output?output.close():Promise.resolve(),input?input.close():Promise.resolve()]);if(closed.some(r=>r.status==='rejected'))throw Error('副本或来源句柄关闭未确认');}}
 check();const finalDir=await ordinary(plan.destination,true);if(!same(finalDir.stat,own.stat))throw Error('副本目录变化');check();report.complete=true;report.completedAtUTC=new Date().toISOString();report.manifestWritten=true;const handle=await fileSystem.open(path.join(plan.destination,'timestamp-manifest.json'),'wx',0o600);try{await handle.writeFile(m.reportText(report,'json'),'utf8');}finally{await handle.close();}return{ok:true,report};}catch(e){report.complete=false;report.canceled=job.canceled;report.manifestWritten=false;report.error=job.canceled?'已取消；本次已创建的部分副本保留，需人工核对。':/^来源|^副本|^父目录|^源句柄|^复制|^30秒|^窗口/.test(e.message)?e.message:'副本或清单写入未完成，保留部分目录，不回显内部路径异常。';report.completedAtUTC=new Date().toISOString();return{ok:false,report,error:report.error};}finally{running.delete(job);}}
 catch(e){return{ok:false,error:/^字段|^需要|^选择|^仅允许|^最终|^来源|^单文件|^总量|^平铺|^新目录|^偏移|^目标|^父目录|^本窗口|^操作|^窗口/.test(e.message)?e.message:'选择或计划未完成；未确认复制成功。'};}finally{if(locked){s.busy=false;s.job=null;}}},cancel(id,{senderId}={}){const s=states.get(senderId);if(s?.job?.id===id){s.job.canceled=true;return{ok:true,canceled:true};}return{ok:true,canceled:false};},disposeSender(id){const s=states.get(id);if(s?.job)s.job.canceled=true;states.delete(id);}};
}
module.exports={...createHost(),createHost};
