export class LanError extends Error { constructor(code,message){super(message);this.code=code;} }
const fail=(code,message)=>{throw new LanError(code,message);};
export function ipv4(text){if(typeof text!=='string'||! /^(0|[1-9]\d{0,2})(\.(0|[1-9]\d{0,2})){3}$/.test(text))fail('ipv4','仅支持无前导零的四段 IPv4。');const a=text.split('.').map(Number);if(a.some(x=>x>255))fail('ipv4','IPv4 每段必须为0–255。');return a.reduce((n,x)=>n*256+x,0);}
export function ipv4Text(n){return [24,16,8,0].map(s=>Math.floor(n/2**s)%256).join('.');}
export function cidr(text){if(typeof text!=='string'||text.length>32||!/^([^/]+)\/(0|[1-9]|[12]\d|3[0-2])$/.test(text))fail('phone_cidr','手机网段仅支持 IPv4/CIDR，例如192.168.1.0/24；IPv6网段暂不支持。');const [address,bits]=text.split('/'),n=ipv4(address),prefix=Number(bits),width=2**(32-prefix),start=Math.floor(n/width)*width;return {input:text,canonical:ipv4Text(start)+'/'+prefix,prefix,start,end:start+width-1,hostBitsNormalized:n!==start};}
export function inputPayload(port,phone){if(typeof port!=='string'||!/^[1-9]\d{0,4}$/.test(port)||Number(port)>65535)fail('port','本地端口必须是1–65535整数。');if(typeof phone!=='string'||phone.length>32)fail('phone_cidr','手机网段最多32字符。');return {port:Number(port),phoneCIDR:phone.trim()?cidr(phone.trim()).canonical:''};}
export function classify(adapter){if(!adapter)return{kind:'unknown',wifi:'unknown',vpn:'unknown',evidence:[]};const evidence=[`InterfaceType=${adapter.interfaceType??'unknown'}`,`NdisPhysicalMedium=${adapter.physicalMedium??'unknown'}`,`Virtual=${adapter.virtual??'unknown'}`,`HardwareInterface=${adapter.hardware??'unknown'}`];const wifi=adapter.interfaceType===71||[1,9].includes(adapter.physicalMedium);return{kind:wifi?'wifi':adapter.interfaceType===131?'tunnel_hint':adapter.interfaceType===23?'ppp_hint':adapter.virtual===true?'virtual_hint':'unknown',wifi:wifi?'field_evidence':'unknown',vpn:'unknown',evidence,description:'名称不是VPN证明，隧道/PPP/虚拟也不等于VPN；需要用户核对实际连接用途。'};}
function v4OrNull(a){try{return ipv4(a);}catch{return null;}}
function rangeOf(ip,bits){const n=ipv4(ip),width=2**(32-bits),start=Math.floor(n/width)*width;return{start,end:start+width-1,prefix:bits,canonical:ipv4Text(start)+'/'+bits};}
const overlap=(a,b)=>Math.max(a.start,b.start)<=Math.min(a.end,b.end);
export function analyze(snapshot,input){if(snapshot?.format!=='T070-os-snapshot'||snapshot.version!==1||!Number.isSafeInteger(input.port)||input.port<1||input.port>65535)fail('snapshot','宿主快照格式或端口无效。');const groups=snapshot.groups;for(const name of['adapters','addresses','routes','listeners'])if(!groups?.[name]||!['ok','unknown'].includes(groups[name].status)||!Array.isArray(groups[name].rows))fail('snapshot','快照组不完整。');const phone=input.phoneCIDR?cidr(input.phoneCIDR):null;const listeners=groups.listeners.rows.filter(r=>r.port===input.port);let scope='unknown';if(groups.listeners.status==='ok'){if(!listeners.length)scope='not_observed';else if(listeners.some(r=>r.address==='0.0.0.0'))scope='ipv4_wildcard';else if(listeners.some(r=>{const n=v4OrNull(r.address);return n!==null&&Math.floor(n/16777216)!==127;}))scope='ipv4_specific';else if(listeners.some(r=>r.address==='::'||r.address==='0:0:0:0:0:0:0:0'))scope='ipv6_wildcard_ipv4_unknown';else if(listeners.some(r=>v4OrNull(r.address)===null&&r.address!=='::1'&&r.address!=='0:0:0:0:0:0:0:1'))scope='ipv6_specific_ipv4_unknown';else scope='loopback_only_not_direct_lan';}
const candidates=[];const ipv6Evidence=[];for(const address of groups.addresses.rows){const adapter=groups.adapters.rows.find(a=>a.index===address.index),kind=classify(adapter);const n=v4OrNull(address.address);if(n===null){ipv6Evidence.push({...address,classification:kind,support:'IPv6地址只列证据；手机IPv6网段、作用域与候选URL不推导。'});continue;}if(Math.floor(n/16777216)===127||n===0||n>=3758096384)continue;const range=rangeOf(address.address,address.prefix);const relation=phone?{computerAddressInsidePhoneRange:n>=phone.start&&n<=phone.end,subnetOverlap:overlap(range,phone),samePrefixRange:range.start===phone.start&&range.end===phone.end,computerSubnet:range.canonical,phoneSubnet:phone.canonical}:null;const matching=listeners.filter(l=>l.address==='0.0.0.0'||l.address===address.address);const ipv6Wildcard=listeners.some(l=>l.address==='::'||l.address==='0:0:0:0:0:0:0:0');candidates.push({address:address.address,index:address.index,adapterName:adapter?.name??null,adapterStatus:adapter?.status??null,addressState:address.state,classification:kind,network:range.canonical,relation,listenEvidence:groups.listeners.status!=='ok'?'unknown':matching.length?'direct_ipv4_listener_observed':ipv6Wildcard?'ipv6_wildcard_ipv4_unknown':'no_direct_ipv4_listener_observed',httpURL:`http://${address.address}:${input.port}/`,httpsURL:`https://${address.address}:${input.port}/`,protocol:'未验证协议，仅候选文字，不发送请求',remoteReachability:'待手机实际验证',caveat:Math.floor(n/65536)===0xa9fe?'IPv4链路本地地址，手机侧作用域/路由需独立核对':address.state!=='Preferred'?'地址状态不是Preferred，不能据此保证可用':adapter?.status!=='Up'?'网卡Up状态未确认，不能保证可用':null});}
const relevantRoutes=[];const unassessedRoutes=[];for(const route of groups.routes.rows){let range;try{range=cidr(route.destination);}catch{unassessedRoutes.push({...route,assessment:'IPv6/不支持的前缀只保留原样证据，不做路由结论。'});continue;}if(phone&&overlap(range,phone))relevantRoutes.push({...route,canonical:range.canonical,relationship:range.start<=phone.start&&range.end>=phone.end?'covers_entire_phone_range':'partial_phone_range_overlap',assessment:'只是路由表区间关系，不是实际选路；未合并接口metric/策略路由，不宣称最佳路径或远端可达。'});}
const meaning={unknown:'监听查询未知，不能判断本端口监听范围。',not_observed:'本次未观察到该TCP端口监听，不证明手机一定不可达（可能另有转发/代理或快照变化）。',ipv4_wildcard:'观察到0.0.0.0 IPv4通配监听，远端实际可达仍待手机验证。',ipv4_specific:'观察到具体IPv4非回环监听，只覆盖对应地址，手机实际可达待验证。',ipv6_wildcard_ipv4_unknown:'观察到IPv6通配::，IPv4双栈支持未知，不能等同0.0.0.0监听。',ipv6_specific_ipv4_unknown:'观察到IPv6具体地址监听（作用域未进一步判断），IPv4支持未知。',loopback_only_not_direct_lan:'本次仅观察到回环监听：未直接监听局域网地址；转发/反向代理等未检查，手机端实际可达仍待验证。'};
return {format:'T070-lan-report',version:1,input:{port:input.port,phoneCIDR:phone?.canonical??null},snapshot,listenerAnalysis:{scope,description:meaning[scope],listeners,ipv6DualStack:'unknown',remoteReachability:'待手机实际验证'},candidates,ipv6Evidence,relevantRoutes,unassessedRoutes,routeAssessment:phone?'IPv4路由表区间关系；不是实际最优路由或手机返程判定。':'未提供手机IPv4网段，路由仅保留快照，不做区间筛选。',recommendations:[scope==='loopback_only_not_direct_lan'?'在服务自己的配置中人工核对绑定地址；本工具不会改监听。':'在服务自己的配置中人工核对端口、绑定地址和HTTP/HTTPS协议。','在手机网络设置核对其实际IPv4网段；检查Wi-Fi隔离、VPN/虚拟网卡与返程路由。','用手机实际打开对应候选地址验证；本工具未连接手机或扫描网络。','若绑定符合预期仍无法访问，人工核对防火墙允许规则；本工具未读取规则或修改防火墙。'],scope:'只读本机OS网卡/地址/路由/TCP监听快照，未执行远端连接、扫网、抓包、服务HTTP校验、进程结束或系统配置修改。非原子快照，权限/容量/时间失败保留未知。所有IPv6、VPN用途、实际最优选路、防火墙和手机可达性边界明确。'};}
export function reportText(report,ext){if(report?.format!=='T070-lan-report'||report.version!==1)fail('report','没有完整结果。');const json=JSON.stringify(report,null,2);let content;if(ext==='json')content=json;else if(ext==='md')content=`# T070 局域网访问地址自检\n\n${report.listenerAnalysis.description}\n\n远端可达性：待手机实际验证。\n\n${report.scope}\n\n完整候选、组状态、源快照、路由关系与建议：\n\n\`\`\`json\n${json.replaceAll('`','\\u0060').replaceAll('<','\\u003c').replaceAll('>','\\u003e')}\n\`\`\`\n`;else fail('extension','仅JSON/MD。');if(new TextEncoder().encode(content).length>2097152)fail('output_limit','完整报告超过2MiB，拒绝截断。');return content;}
