export const LIMITS=Object.freeze({inputBytes:65536,depth:8,nodes:3000,tables:10,fields:20,rows:1000,outputBytes:2097152});
export class SyntheticError extends Error { constructor(code) { super('输入语法、规则或容量不支持；源内容和解析上下文未回显。'); this.name = 'SyntheticError'; this.code = code; } }
const fail = code => { throw new SyntheticError(code); }; const encoder = new TextEncoder();
function unicode(text) { for (let i = 0; i < text.length; i++) { const c = text.charCodeAt(i); if (c >= 0xd800 && c <= 0xdbff) { const n = text.charCodeAt(++i); if (!(n >= 0xdc00 && n <= 0xdfff)) fail('invalid_unicode'); } else if (c >= 0xdc00 && c <= 0xdfff) fail('invalid_unicode'); } }
export function checkText(text) { if (typeof text !== 'string' || text.length > LIMITS.inputBytes || encoder.encode(text).length > LIMITS.inputBytes) fail('input_limit'); unicode(text); if (/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(text) || /\r(?!\n)/.test(text)) fail('invalid_control'); return text; }
export function parseStrictJSON(text) {
  checkText(text); let at = 0; let nodes = 0; const ws = () => { while (/[\x20\t\r\n]/.test(text[at] || '\0')) at++; };
  function string() { const start = at++; while (at < text.length) { const c = text[at++]; if (c === '"') { try { const value = JSON.parse(text.slice(start, at)); unicode(value); return value; } catch (error) { if (error instanceof SyntheticError) throw error; fail('json_syntax'); } } if (c === '\\') at++; else if (c.charCodeAt(0) < 32) fail('json_syntax'); } fail('json_syntax'); }
  function value(depth = 0) { if (depth > LIMITS.depth || ++nodes > LIMITS.nodes) fail('structure_limit'); ws(); const c = text[at]; if (c === '"') return string(); if (c === '{') { at++; const out = Object.create(null); ws(); if (text[at] === '}') { at++; return out; } while (true) { ws(); if (text[at] !== '"') fail('json_syntax'); const key = string(); if (Object.hasOwn(out, key)) fail('json_duplicate_key'); ws(); if (text[at++] !== ':') fail('json_syntax'); out[key] = value(depth + 1); ws(); const next = text[at++]; if (next === '}') return out; if (next !== ',') fail('json_syntax'); } } if (c === '[') { at++; const out = []; ws(); if (text[at] === ']') { at++; return out; } while (true) { out.push(value(depth + 1)); ws(); const next = text[at++]; if (next === ']') return out; if (next !== ',') fail('json_syntax'); } } for (const [token, result] of [['true', true], ['false', false], ['null', null]]) if (text.slice(at, at + token.length) === token) { at += token.length; return result; } const match = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/.exec(text.slice(at)); if (!match) fail('json_syntax'); at += match[0].length; const n = Number(match[0]); if (!Number.isFinite(n)) fail('nonfinite_number'); if(Number.isInteger(n)&&!Number.isSafeInteger(n))fail('unsafe_integer_number'); return n; }
  const out = value(); ws(); if (at !== text.length) fail('json_syntax'); return out;
}
const NAME=/^[A-Za-z][A-Za-z0-9_]{0,31}$/;const RESERVED=/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/i;const lexical=(a,b)=>a<b?-1:a>b?1:0;
function exact(value,required,optional=[]){if(!value||typeof value!=='object'||Array.isArray(value)||required.some(k=>!Object.hasOwn(value,k))||Object.keys(value).some(k=>!required.includes(k)&&!optional.includes(k)))fail('schema_keywords');}
function identifier(name){if(typeof name!=='string'||!NAME.test(name)||RESERVED.test(name))fail('schema_identifier');return name;}
function boundedInteger(value,min,max){if(!Number.isSafeInteger(value)||value<min||value>max)fail('schema_integer_domain');return value;}
function smallString(value,max=120){if(typeof value!=='string'||value.length>max)fail('schema_string_domain');unicode(value);if(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value))fail('schema_string_domain');return value;}
export const EXAMPLE=JSON.stringify({format:'T054-schema',version:1,distribution:'uniform',boundaryRows:true,tables:[{name:'users',rows:3,primaryKey:'id',fields:[{name:'id',type:'id'},{name:'active',type:'boolean'},{name:'level',type:'integer',min:1,max:9},{name:'label',type:'text',prefix:'示例'}]},{name:'orders',rows:5,primaryKey:'id',fields:[{name:'id',type:'id'},{name:'user_id',type:'foreignKey',table:'users'},{name:'amount',type:'decimal',minUnits:100,maxUnits:9999,scale:2},{name:'state',type:'enum',values:['待处理','完成']}]}]},null,2);
export function parseSchema(text){const root=parseStrictJSON(text);exact(root,['format','version','distribution','boundaryRows','tables']);if(root.format!=='T054-schema'||root.version!==1||root.distribution!=='uniform'||typeof root.boundaryRows!=='boolean'||!Array.isArray(root.tables)||root.tables.length<1||root.tables.length>LIMITS.tables)fail('schema_version_or_tables');const seen=new Set();let total=0;
 const tables=root.tables.map(t=>{exact(t,['name','rows','primaryKey','fields']);const name=identifier(t.name);if(seen.has(name.toLowerCase()))fail('schema_duplicate_table');seen.add(name.toLowerCase());const rows=boundedInteger(t.rows,0,LIMITS.rows);total+=rows;if(total>LIMITS.rows)fail('schema_total_rows');const primaryKey=identifier(t.primaryKey);if(!Array.isArray(t.fields)||t.fields.length<1||t.fields.length>LIMITS.fields)fail('schema_fields_limit');const keys=new Set();const fields=t.fields.map(f=>{if(!f||typeof f!=='object'||Array.isArray(f))fail('schema_field');const name=identifier(f.name);if(keys.has(name.toLowerCase()))fail('schema_duplicate_field');keys.add(name.toLowerCase());if(f.type==='id'||f.type==='boolean'){exact(f,['name','type']);return{name,type:f.type};}if(f.type==='integer'){exact(f,['name','type','min','max']);const min=boundedInteger(f.min,-1000000,1000000),max=boundedInteger(f.max,-1000000,1000000);if(min>max)fail('schema_range');return{name,type:f.type,min,max};}if(f.type==='decimal'){exact(f,['name','type','minUnits','maxUnits','scale']);const minUnits=boundedInteger(f.minUnits,-1000000,1000000),maxUnits=boundedInteger(f.maxUnits,-1000000,1000000),scale=boundedInteger(f.scale,0,3);if(minUnits>maxUnits)fail('schema_range');return{name,type:f.type,minUnits,maxUnits,scale};}if(f.type==='enum'){exact(f,['name','type','values']);if(!Array.isArray(f.values)||!f.values.length||f.values.length>50)fail('schema_enum');const values=f.values.map(v=>{if(typeof v==='string')return smallString(v);if(typeof v==='boolean')return v;if(typeof v==='number')return boundedInteger(v,-1000000,1000000);fail('schema_enum');});if(new Set(values.map(v=>JSON.stringify(v))).size!==values.length)fail('schema_enum_duplicate');return{name,type:f.type,values};}if(f.type==='text'){exact(f,['name','type','prefix']);return{name,type:f.type,prefix:smallString(f.prefix,80)};}if(f.type==='foreignKey'){exact(f,['name','type','table']);return{name,type:f.type,table:identifier(f.table)};}fail('schema_type_unsupported');}).sort((a,b)=>lexical(a.name,b.name));if(fields.filter(f=>f.type==='id').length!==1||!fields.some(f=>f.name===primaryKey&&f.type==='id'))fail('schema_primary_key');return{name,rows,primaryKey,fields};}).sort((a,b)=>lexical(a.name,b.name));
 const byName=new Map(tables.map(t=>[t.name,t]));for(const t of tables)for(const f of t.fields)if(f.type==='foreignKey'){const target=byName.get(f.table);if(!target)fail('schema_foreign_table_missing');if(!target.rows)fail('schema_foreign_empty_target');}
 const visiting=new Set(),done=new Set(),order=[];function visit(t){if(done.has(t.name))return;if(visiting.has(t.name))fail('schema_foreign_cycle');visiting.add(t.name);for(const f of t.fields)if(f.type==='foreignKey')visit(byName.get(f.table));visiting.delete(t.name);done.add(t.name);order.push(t.name);}for(const t of tables)visit(t);return{schema:{format:'T054-schema',version:1,distribution:'uniform',boundaryRows:root.boundaryRows,tables},generationOrder:order,totalRows:total};}
export function seedState(seed){smallString(seed,64);if(!seed.length)fail('seed_required');let value=2166136261;for(const byte of encoder.encode(seed))value=Math.imul(value^byte,16777619)>>>0;return value||0x6d2b79f5;}
export function randomSource(seed){let state=seedState(seed);const uint=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return state>>>0;};return{uint,pick(n){if(!Number.isSafeInteger(n)||n<1||n>2000001)fail('random_domain');const cutoff=Math.floor(4294967296/n)*n;for(let i=0;i<64;i++){const value=uint();if(value<cutoff)return value%n;}fail('random_rejection_limit');}};}
function boundaryPick(n,row,boundaries,rng){return boundaries&&row===0?0:boundaries&&row===1?n-1:rng.pick(n);}
export function csvCell(value,protectStrings=typeof value==='string'){let text=String(value);let protectedValue=false;if(protectStrings&&(/^[\s]*[=+\-@]/u.test(text)||/^[\t\r\n]/.test(text))){text="'"+text;protectedValue=true;}return{cell:'"'+text.replace(/"/g,'""')+'"',protectedValue};}
export function tableCSV(table,rows){let protectedCells=0;const headers=['_synthetic',...table.fields.map(f=>f.name)];const lines=[headers.map(x=>csvCell(x).cell).join(',')];for(const row of rows){const values=['SYNTHETIC_T054',...table.fields.map(f=>f.type==='decimal'?row[f.name].toFixed(f.scale):row[f.name])];lines.push(values.map((v,i)=>{const original=i?row[table.fields[i-1].name]:v;const result=csvCell(v,typeof original==='string');protectedCells+=result.protectedValue?1:0;return result.cell;}).join(','));}return{content:lines.join('\r\n')+'\r\n',protectedCells};}
export async function sha256(bytes,options={}){const subtle=options.subtle||globalThis.crypto?.subtle;if(!subtle)fail('crypto_missing');const digest=await subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');}
function base64(bytes){let text='';for(const byte of bytes)text+=String.fromCharCode(byte);return btoa(text);}
export async function generate(schemaText,seed,options={}){const stopped=()=>{if(options.isCanceled?.())fail('canceled');};const yieldTask=options.yieldTask||(()=>new Promise(r=>setTimeout(r,0)));stopped();const parsed=parseSchema(schemaText);const rng=randomSource(seed);const byName=new Map(parsed.schema.tables.map(t=>[t.name,t]));const tables=new Map();let processed=0;
 for(const name of parsed.generationOrder){const table=byName.get(name),rows=[];for(let index=0;index<table.rows;index++){stopped();const row=Object.create(null);for(const f of table.fields){if(f.type==='id')row[f.name]=index+1;else if(f.type==='integer')row[f.name]=f.min+boundaryPick(f.max-f.min+1,index,parsed.schema.boundaryRows,rng);else if(f.type==='decimal'){const units=f.minUnits+boundaryPick(f.maxUnits-f.minUnits+1,index,parsed.schema.boundaryRows,rng);row[f.name]=units/10**f.scale;}else if(f.type==='boolean')row[f.name]=Boolean(boundaryPick(2,index,parsed.schema.boundaryRows,rng));else if(f.type==='enum')row[f.name]=f.values[boundaryPick(f.values.length,index,parsed.schema.boundaryRows,rng)];else if(f.type==='text')row[f.name]='SYNTHETIC_'+name+'_'+f.name+'_'+String(index+1).padStart(4,'0')+'_'+f.prefix+'_'+String(rng.pick(1000000)).padStart(6,'0');else if(f.type==='foreignKey'){const target=byName.get(f.table);const targetIndex=boundaryPick(target.rows,index,parsed.schema.boundaryRows,rng);row[f.name]=tables.get(target.name)[targetIndex][target.primaryKey];}}rows.push(row);if(++processed%50===0){options.onProgress?.({processed});await yieldTask();stopped();}}tables.set(name,rows);await yieldTask();stopped();}
 const data={format:'T054-data',version:1,synthetic:true,notice:'SYNTHETIC ONLY: generated mock records, not real people or transactions.',tables:parsed.schema.tables.map(t=>({name:t.name,primaryKey:t.primaryKey,rows:tables.get(t.name)}))};const files=[];async function add(path,content){const bytes=encoder.encode(content);if(bytes.length+files.reduce((sum,f)=>sum+f.bytes,0)>LIMITS.outputBytes)fail('output_limit');const hash=await sha256(bytes,options);stopped();files.push({path,content,bytes:bytes.length,sha256:hash,base64:base64(bytes)});}
 await add('synthetic-data.json',JSON.stringify(data,null,2)+'\n');const csvReports=[];for(const table of parsed.schema.tables){const csv=tableCSV(table,tables.get(table.name));await add('tables/'+table.name+'.csv',csv.content);csvReports.push({table:table.name,rows:table.rows,formulaProtectedCells:csv.protectedCells});}
 const manifest={format:'T054-generation-manifest',version:1,synthetic:true,seed,algorithm:'FNV1a32 UTF8 seed (zero fallback 0x6d2b79f5) + xorshift32(13,17,5); rejection sampling over discrete closed domains.',sorting:'Tables/fields code-unit alphabetical; deterministic dependency postorder; rows ascending id.',distribution:parsed.schema.boundaryRows?'Rows1/2 choose domain first/last; all other samples pseudo-uniform discrete. Not a statistical-distribution guarantee.':'All sampled values pseudo-uniform discrete. Not a statistical-distribution guarantee.',generationOrder:parsed.generationOrder,totalRows:parsed.totalRows,schema:parsed.schema,schemaSha256:await sha256(encoder.encode(JSON.stringify(parsed.schema)),options),csv:{encoding:'UTF-8 without BOM',delimiter:',',newlines:'CRLF',quoting:'All cells quoted; quotes doubled; original CR/LF in strings retained inside quotes.',syntheticColumn:'_synthetic=SYNTHETIC_T054',formulaProtection:'String cells starting with whitespace then = + - @ or initial TAB/CR/LF gain apostrophe. Numeric/boolean cells keep canonical values. Protected CSV text may differ from JSON; cannot guarantee all spreadsheet importers treat it identically.',tables:csvReports},files:files.map(f=>({path:f.path,bytes:f.bytes,sha256:f.sha256})),manifestSelfHash:'Not embedded; transport hashes every file including this manifest.'};stopped();await add('generation-manifest.json',JSON.stringify(manifest,null,2)+'\n');return{files,totalBytes:files.reduce((n,f)=>n+f.bytes,0),totalRows:parsed.totalRows,tables:parsed.schema.tables.length};}
export function bundlePayload(result){if(!result||!Array.isArray(result.files)||result.files.length<3||result.files.length>12||result.totalBytes>LIMITS.outputBytes||result.files[0].path!=='synthetic-data.json'||result.files.at(-1).path!=='generation-manifest.json')fail('preview_required');return{copyOnly:true,defaultName:'T054-synthetic-data-copy',files:result.files.map(({path,base64,sha256})=>({path,base64,sha256}))};}
