import { h } from '../../core/ui.js';
import { DnsError, inputPayload, reportText } from './model.mjs';

export default {
  id: 'T061',
  create(root) {
    let active = false; let destroyed = false; let generation = 0; let busy = false; let plan = null; let report = null; let preview = null; let runningJob = null; let cancelRequested = false;
    const status = h('p', { role: 'status', 'aria-live': 'polite' });
    const domain = h('input', { type: 'text', maxlength: '512', 'aria-label': '查询域名', placeholder: '例如 localhost 或 example.test；不填 URL', oninput: edited });
    const server = h('input', { type: 'text', maxlength: '100', 'aria-label': '指定 DNS 服务器', placeholder: 'IP[:端口]，IPv6 如 [::1]:53', oninput: edited });
    const type = h('select', { 'aria-label': '记录类型', onchange: edited }, h('option', { value: 'A' }, 'A（IPv4）'), h('option', { value: 'AAAA' }, 'AAAA（IPv6）')); type.value = 'A';
    const prepare = button('检查输入并显示请求计划', preparePlan); const cancel = button('取消当前任务', cancelTask);
    const planHost = h('section', {}); const resultHost = h('section', {}); const previewHost = h('section', {});
    root.append(h('link', { rel: 'stylesheet', href: new URL('./style.css', import.meta.url).href }), h('section', { class: 'feature-t061', 'aria-label': '域名解析路径诊断' }, h('h2', {}, '域名解析路径诊断'),
      h('p', {}, '确认目标后，分别查询系统名称服务与一个指定 DNS。只查 A 或 AAAA，不发 HTTP、不自动换 DNS、不修改系统设置。'),
      h('p', { class: 't061-rule' }, '每来源最多一次 API 调用，每次最多等待 5 秒；系统/底层 DNS 的报文、缓存、重传或 CNAME/TCP 行为不可观测，不能承诺总网络报文恰好两次。'),
      h('div', { class: 't061-inputs' }, field('域名（IDNA；单标签仅允许 localhost）', domain), field('用户选择的 DNS IP 与端口', server), field('只查询一种记录类型', type)),
      actions(prepare, cancel, button('填入本机示例（不查询）', example), button('清除输入和报告', clear)), status, planHost, resultHost, previewHost,
      h('p', { class: 't061-muted' }, '系统 lookup 可从 hosts/缓存/操作系统解析器取结果，来源与指定 DNS 不等价。缓存命中标 unknown；地址差异不证明劫持。只诊断域名与请求类型，未测 HTTP/TLS/站点可用性。系统 lookup 无可取消句柄：取消/超时停止等待并忽略晚回调，不能终止操作系统内部查询。每窗口最多 128 次诊断，不保存输入或报告到配置。')));
    update();
    function button(label, fn) { return h('button', { type: 'button', onclick: event => { if (!active || destroyed || document.hidden || event.detail > 1) return; fn(); } }, label); }
    function field(label, input) { return h('label', {}, h('span', {}, label), input); }
    function actions(...nodes) { return h('div', { class: 't061-actions' }, nodes); }
    function message(text) { if (!destroyed) status.textContent = text; }
    function host() { const api = window.toolbox?.features; if (api?.callHostSupported !== true || typeof api.callHost !== 'function' || typeof api.cancelHost !== 'function') throw new DnsError('host_unavailable', '当前宿主缺少可信功能后端接口，已阻止查询。'); return api; }
    function cancelHost() { if (!runningJob) return; const id = runningJob; try { const api = host(); Promise.resolve(api.cancelHost('T061', id)).catch(() => {}); } catch {} }
    function invalidate() { generation++; plan = null; report = null; preview = null; planHost.replaceChildren(); resultHost.replaceChildren(); previewHost.replaceChildren(); }
    function edited() { if (!active || destroyed) return; cancelHost(); invalidate(); message('输入已改变，旧计划、报告和预览已废弃，请重新检查目标。'); }
    function update() { if (destroyed) return; for (const control of [domain, server, type]) control.disabled = !active || busy; prepare.disabled = !active || busy; cancel.disabled = !active || !busy || cancelRequested; }
    async function task(fn) { if (busy) return; const owner = ++generation; busy = true; cancelRequested = false; update(); const options = { isCanceled: () => destroyed || !active || document.hidden || owner !== generation }; try { await fn(options); } catch (error) { if (!options.isCanceled()) message(error instanceof DnsError ? `${error.code}：${error.message}` : '宿主处理或保存失败；没有自动重试或暴露内部异常。'); } finally { runningJob = null; if (!destroyed) { busy = false; cancelRequested = false; update(); } } }
    function requireResult(result, key) { if (result?.ok !== true || !result[key]) throw new DnsError(typeof result?.code === 'string' && /^[a-z_]{1,40}$/.test(result.code) ? result.code : 'host_result', '宿主拒绝或未完成请求；请检查输入、确认状态及任务上限。'); return result[key]; }
    async function preparePlan() { if (busy) return; invalidate(); await task(async options => { const api = host(); const payload = inputPayload(domain.value, server.value, type.value); const next = requireResult(await api.callHost('T061', 'plan', payload), 'plan'); if (options.isCanceled()) return; plan = next; renderPlan(); message('请求计划已准备；尚未查询。请核对域名、指定 DNS 和请求次数，再点击确认。'); }); }
    function renderPlan() { planHost.replaceChildren(); if (!plan) return; const expected = plan; planHost.append(h('h3', {}, '待确认目标：尚未查询'), h('p', {}, `域名：${plan.domain} · ${plan.recordType} · 指定 DNS：${plan.dnsServer} · 每次期限 ${plan.timeoutMs} ms`), h('ul', {}, plan.targets.map(t => h('li', {}, `${t.source}：${t.target}；${t.operation}，最多 ${t.maxCalls} 次 API 调用`))), h('p', {}, plan.warning), button('确认以上目标并运行最多两次查询', () => run(expected))); }
    async function run(expected) { if (busy || plan !== expected) return; report = null; preview = null; resultHost.replaceChildren(); previewHost.replaceChildren(); planHost.replaceChildren(); plan = null; await task(async options => { const api = host(); if (typeof globalThis.crypto?.randomUUID !== 'function') throw new DnsError('random_unavailable', '宿主缺少随机任务 ID 能力，已阻止查询。'); const id = globalThis.crypto.randomUUID(); runningJob = id; message(`正在诊断 ${expected.domain}，任务 ${id}；每来源最多一次 API 调用。`); const result = await api.callHost('T061', 'run', { domain: expected.domain, dnsServer: expected.dnsServer, recordType: expected.recordType, jobId: id, confirmed: true }); if (options.isCanceled()) return; const next = requireResult(result, 'report'); report = next; renderResults(); message(next.canceled ? `任务 ${id} 已取消；两来源当前状态已记录，未测 HTTP。` : `诊断完成，对照：${next.difference}，耗时 ${next.elapsedMs} ms；未测 HTTP，缓存未知。`); }); }
    async function cancelTask() { if (!busy || cancelRequested) return; if (!runningJob) { generation++; message('当前计划或保存等待已取消，未自动查询；已完成写入无法撤回。'); return; } const owner = generation; const id = runningJob; cancelRequested = true; update(); message(`正在请求取消任务 ${id}；不会启动替代查询。`); try { const result = await host().cancelHost('T061', id); if (destroyed || !active || generation !== owner || runningJob !== id) return; if (result?.ok !== true) message('取消请求未确认；正在等待原任务的有限超时，没有自动重试。'); else if (result.canceled !== true) message('宿主任务已经结束或不再存在；以原任务返回结果为准。'); } catch { if (!destroyed && active && generation === owner && runningJob === id) message('取消请求失败；等待原任务最多 5 秒，不自动重试。'); } }
    function renderResults() { resultHost.replaceChildren(); if (!report) return; resultHost.append(h('h3', {}, '解析结果：来源分别测量'), h('p', {}, `${report.plan.domain} · ${report.plan.recordType} · ${report.difference} · 已取消 ${report.canceled}`), ...report.results.map(r => h('section', { class: 't061-result' }, h('h4', {}, `${r.source} · ${r.target}`), h('p', {}, `状态 ${r.status} · 分类 ${r.category} · code ${r.code || '—'} · ${r.elapsedMs} ms · 缓存 ${r.cached}`), h('p', {}, r.explanation), h('ul', {}, r.addresses.map(a => h('li', {}, `${a.address}（IPv${a.family}）`))), h('p', {}, `完整 ${r.addresses.length} 条地址；没有截断。`))), h('p', {}, report.caveat), actions(button('预览完整 JSON 报告', () => previewReport('json')), button('预览完整 MD 报告', () => previewReport('md')))); }
    function previewReport(extension) { if (!report || busy) return; previewHost.replaceChildren(); preview = null; generation++; try { preview = { content: reportText(report, extension), extension, defaultName: `T061-dns-path-report.${extension}` }; const expected = preview; const text = h('textarea', { rows: '14', readonly: true, 'aria-label': '完整 DNS 报告预览' }); text.value = preview.content; previewHost.append(h('h3', {}, '完整报告与目标新文件'), h('p', {}, `拟创建 ${preview.defaultName}；包含域名、DNS 目标及地址，分享前核对。实际路径由保存对话框确认，已有文件拒绝覆盖。`), text, button('保存已预览报告新副本', () => save(expected))); } catch (error) { message(error instanceof DnsError ? error.message : '完整报告预览失败，没有部分导出。'); } }
    async function save(expected) { if (busy || preview !== expected) return; const api = window.toolbox?.files; if (api?.saveTextSupportsCopyOnly !== true || typeof api.saveText !== 'function') { message('当前宿主缺少副本保护接口，已阻止保存。'); return; } await task(async options => { const result = await api.saveText({ ...expected, copyOnly: true }); if (options.isCanceled() || preview !== expected) return; if (result?.ok === true) message('已保存完整报告新副本，未修改 DNS 设置。'); else if (result?.canceled === true) message('已取消保存，完整预览保留。'); else message('保存失败，完整预览保留；不能覆盖已有文件。'); }); }
    function example() { if (busy) return; invalidate(); domain.value = 'localhost'; server.value = '127.0.0.1:5353'; type.value = 'A'; message('仅填入本机示例，尚未查询；需要你自己的本地 DNS 夹具监听该端口。'); }
    function clear() { cancelHost(); domain.value = ''; server.value = ''; type.value = 'A'; invalidate(); message('输入、计划和报告已清除；当前任务取消，不写配置。'); }
    function hide() { if (document.hidden && !destroyed) { cancelHost(); generation++; message('面板隐藏，任务取消且晚回调忽略；系统查询不可实际终止。'); } }
    document.addEventListener('visibilitychange', hide);
    return { activate() { if (destroyed) return; active = true; update(); }, deactivate() { if (destroyed) return; active = false; cancelHost(); generation++; update(); message('面板暂停，任务取消，未自动查询或保存。'); }, destroy() { if (destroyed) return; clear(); destroyed = true; active = false; generation++; document.removeEventListener('visibilitychange', hide); root.replaceChildren(); } };
  }
};
