import { h } from '../../core/ui.js';
import { DeliveryError, LIMITS, readDirectory, makeManifest, validateManifest, compare, exportManifest, exportReport } from './model.mjs';

const LABELS = { missing: '缺失', modified: '修改', extra: '额外', unchanged: '一致' };
export default {
  id: 'T013',
  create(root) {
    let active = false; let destroyed = false; let generation = 0; let busy = false; let sourceFiles = []; let targetFiles = []; let manifest = null; let report = null; let preview = null; let page = 0;
    const style = h('link', { rel: 'stylesheet', href: new URL('./style.css', import.meta.url).href });
    const status = h('p', { class: 't013-status', role: 'status', 'aria-live': 'polite' });
    const sourceDirectory = fileInput('源完整目录', true, files => selectSource(files)); const sourceFlat = fileInput('源平级文件备用', false, files => selectSource(files));
    const targetDirectory = fileInput('目标完整目录', true, files => selectTarget(files)); const targetFlat = fileInput('目标平级文件备用', false, files => selectTarget(files));
    const manifestText = h('textarea', { rows: '8', 'aria-label': '源清单 JSON', placeholder: '粘贴 T013-manifest v1 JSON，或先读取源目录', oninput: () => { if (!active || destroyed) return; invalidateSource('源清单文本已改变，旧清单、差异结果和预览全部废弃，请重新核验。'); } });
    const importFile = h('input', { type: 'file', accept: '.json', 'aria-label': '读取源清单 JSON 文件', onchange: event => readManifestFile(event.target) });
    const build = button('生成源目录清单', scanSource); const inspect = button('核验并导入源清单', importManifest); const verify = button('核对目标完整目录', scanTarget); const empty = button('按空目标集合核对（全部缺失）', () => { if (!manifest || busy) return; clearReport(); report = compare(manifest, []); render(); message('已按你明确声明的空目标集合核对；没有扫描目录，所有源文件标记缺失。'); }); const cancel = button('取消当前读取或核验', () => { generation++; message('当前任务已取消，无部分清单或差异结果；等待本次异步操作结束。'); });
    const summary = h('section', {}); const listHost = h('section', {}); const outputHost = h('section', {}); const previewHost = h('section', {});
    const shell = h('section', { class: 'feature-t013', 'aria-label': '文件交付校验清单' }, h('h2', {}, '文件交付校验清单'), h('p', {}, '固定使用 SHA-256，将完整所选目录生成相对路径清单，再核对另一份完整集合。只读取，不搬移、重命名或写入源/目标文件。'),
      h('p', { class: 't013-rule' }, '每个集合最多 500 个文件，单文件 8 MiB、总 20 MiB；剥除 File API 最外层选中目录名称，其余路径保持原拼写。不同根名称可以匹配；大小写/NFC 或文件/目录前缀冲突明确阻止。'),
      h('h3', {}, '1. 来源清单'), field('选择完整源目录', sourceDirectory), field('目录选择不兼容时：源平级集合', sourceFlat), actions(build, button('来源演示 A/B/C', sourceDemo)), field('读取 JSON 清单（最多 1 MiB UTF-8）', importFile), manifestText, actions(inspect),
      h('h3', {}, '2. 目标核对'), field('选择完整目标目录', targetDirectory), field('目录选择不兼容时：目标平级集合', targetFlat), actions(verify, empty, button('目标演示：改 A / 缺 B / 同 C / 增 D', targetDemo)),
      actions(cancel, button('清除输入、清单和报告', clear)), status, summary, listHost, outputHost, previewHost,
      h('p', { class: 't013-muted' }, '每页显示 50 项，导出包含全部文件。JSON 清单仅含相对路径、实际字节数、SHA-256；报告另外列出源/目标对照，不含文件内容，不写配置、不上传。哈希不是来源签名。'),
      h('p', { class: 't013-muted' }, 'File API 只提供用户实际选择的文件，不枚举空目录或保存链接/权限/时间戳；平级选择不保留未提供的子目录路径，同名文件会被拒绝。无需自有符号链接遍历；宿主交付的 File 按内容读取。不是运行中应用或全目录原子快照。'),
      h('p', { class: 't013-muted' }, '隐藏/暂停取消在途任务，返回后手动重试。切换具体功能清除当前内存，先导出需要的清单。已打开的保存对话框仍由用户处理；取消 UI 不能撤回已经确认的副本写入。'));
    root.append(style, shell); update();
    function button(text, fn) { return h('button', { type: 'button', onclick: event => { if (!active || destroyed || document.hidden || event.detail > 1) return; fn(); } }, text); }
    function actions(...nodes) { return h('div', { class: 't013-actions' }, nodes); }
    function field(text, control) { return h('label', {}, h('span', {}, text), control); }
    function fileInput(label, directory, fn) { return h('input', { type: 'file', multiple: true, ...(directory ? { webkitdirectory: '' } : {}), 'aria-label': label, onchange: event => { if (!active || destroyed) return; fn(Array.from(event.target.files || [])); } }); }
    function message(text) { if (!destroyed) status.textContent = text; }
    function clearPreview() { generation++; preview = null; previewHost.replaceChildren(); }
    function clearReport() { clearPreview(); report = null; page = 0; render(); }
    function invalidateSource(text) { manifest = null; clearReport(); update(); if (text) message(text); }
    function selectSource(files) { sourceFiles = files; manifestText.value = ''; invalidateSource(`已选择源 ${files.length} 个文件，尚未读取或哈希。未选文件不在本次清单范围。`); }
    function selectTarget(files) { targetFiles = files; clearReport(); update(); message(`已选择目标 ${files.length} 个文件；请确保这是完整交付集合，再核对。`); }
    function update() { if (destroyed) return; for (const control of [sourceDirectory, sourceFlat, targetDirectory, targetFlat, importFile, manifestText]) control.disabled = !active || busy; build.disabled = !active || busy || !sourceFiles.length; inspect.disabled = !active || busy; verify.disabled = !active || busy || !manifest || !targetFiles.length; empty.disabled = !active || busy || !manifest; cancel.disabled = !active || !busy; }
    async function task(fn) { if (busy) return; const owner = ++generation; busy = true; update(); const options = { isCanceled: () => destroyed || !active || document.hidden || owner !== generation, onProgress: p => { if (!destroyed && owner === generation) message(`SHA-256 核验 ${p.processed}/${p.total} 个文件，可取消。`); } }; try { await fn(options); } catch (error) { if (!destroyed && owner === generation) message(error instanceof DeliveryError ? error.message : '本地核验失败，没有部分清单或差异结果。'); } finally { if (!destroyed) { busy = false; update(); } } }
    async function scanSource() { if (busy || !sourceFiles.length) return; invalidateSource(); const input = [...sourceFiles]; await task(async options => { const files = await readDirectory(input, options); if (options.isCanceled()) return; assign(makeManifest(files), `源清单完成：${files.length} 个文件；源文件未修改，尚未导出。`); }); }
    function assign(value, text) { manifest = value; manifestText.value = exportManifest(value); report = null; page = 0; clearPreview(); render(); message(text); }
    async function importManifest() { if (busy) return; const text = manifestText.value; invalidateSource(); await task(async options => { const value = validateManifest(text); if (options.isCanceled()) return; assign(value, `源清单已严格核验：${value.files.length} 个文件。清单哈希为导入声明，需目标读取再核对。`); }); }
    async function readManifestFile(control) { const file = control.files?.[0]; control.value = ''; if (!active || destroyed || document.hidden || busy || !file) return; invalidateSource(); await task(async options => { if (!Number.isSafeInteger(file.size) || file.size < 0 || file.size > LIMITS.manifestBytes || typeof file.slice !== 'function') throw new DeliveryError('manifestLimit', '清单文件超过 1 MiB 或 File API 无效。'); const bytes = new Uint8Array(file.size); for (let pos = 0; pos < file.size; pos += LIMITS.chunkBytes) { if (options.isCanceled()) return; const end = Math.min(file.size, pos + LIMITS.chunkBytes); const buffer = await file.slice(pos, end).arrayBuffer(); if (options.isCanceled()) return; if (!(buffer instanceof ArrayBuffer) || buffer.byteLength !== end - pos) throw new DeliveryError('read', '清单读取字节数不一致。'); bytes.set(new Uint8Array(buffer), pos); await new Promise(resolve => setTimeout(resolve, 0)); } let text; try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { throw new DeliveryError('utf8', '清单不是严格 UTF-8，未猜测其他编码。'); } const value = validateManifest(text); if (options.isCanceled()) return; assign(value, `JSON 清单已读取并核验：${value.files.length} 个文件；未保留原路径。`); }); }
    async function scanTarget() { if (!manifest || busy || !targetFiles.length) return; clearReport(); const expected = manifest; const input = [...targetFiles]; await task(async options => { const files = await readDirectory(input, options); if (options.isCanceled() || manifest !== expected) return; report = compare(expected, files); render(); message('完整目标核对完成；源与目标均保持只读。'); }); }
    function demoFiles(kind) { const values = kind === 'source' ? [['A.txt', 'A旧内容'], ['B.txt', '待交付B'], ['sub/C.bin', new Uint8Array([0, 127, 255])]] : [['A.txt', 'A新内容'], ['sub/C.bin', new Uint8Array([0, 127, 255])], ['D.txt', 'D额外']]; return values.map(([path, bytes]) => { const file = new File([bytes], path.split('/').at(-1)); Object.defineProperty(file, 'webkitRelativePath', { value: `${kind === 'source' ? '发出根' : '收到根'}/${path}` }); return file; }); }
    function sourceDemo() { if (busy) return; selectSource(demoFiles('source')); scanSource(); }
    function targetDemo() { if (busy) return; if (!manifest) { message('请先生成或导入来源清单，再核对目标演示。'); return; } selectTarget(demoFiles('target')); scanTarget(); }
    function render() { summary.replaceChildren(); listHost.replaceChildren(); outputHost.replaceChildren(); if (!manifest) return; summary.append(h('h3', {}, report ? '完整差异结果' : '源路径与内容清单'), h('p', {}, `源 ${manifest.files.length} 个文件 / ${manifest.files.reduce((n, f) => n + f.size, 0)} 字节，SHA-256，相对路径规则 ${manifest.pathRule}。`)); if (report) summary.append(h('p', { class: 't013-counts' }, Object.entries(report.counts).map(([key, n]) => `${LABELS[key]} ${n}`).join(' / ')), h('p', {}, `目标 ${report.actualCount} 个文件 / ${report.actualBytes} 字节。`)); renderList(); outputHost.append(actions(button('预览源清单 JSON', () => showPreview('manifest', 'json')), button('预览源清单 Markdown', () => showPreview('manifest', 'md')))); if (report) outputHost.append(actions(button('预览差异报告 JSON', () => showPreview('report', 'json')), button('预览差异报告 Markdown', () => showPreview('report', 'md')))); }
    function renderList() { listHost.replaceChildren(); const records = report ? report.records : manifest.files; const max = Math.max(0, Math.ceil(records.length / 50) - 1); page = Math.min(page, max); const expectedReport = report; const expectedManifest = manifest; const before = button('上一页 50 项', () => { if (manifest !== expectedManifest || report !== expectedReport || page < 1) return; page--; renderList(); }); const after = button('下一页 50 项', () => { if (manifest !== expectedManifest || report !== expectedReport || page >= max) return; page++; renderList(); }); before.disabled = page === 0; after.disabled = page === max;
      const rows = records.slice(page * 50, page * 50 + 50).map(r => report ? h('tr', {}, h('td', {}, LABELS[r.status]), h('td', {}, r.path), h('td', {}, r.expected?.size ?? '—'), h('td', {}, r.actual?.size ?? '—'), h('td', {}, r.expected?.sha256 ?? '—'), h('td', {}, r.actual?.sha256 ?? '—'), h('td', {}, r.reason)) : h('tr', {}, h('td', {}, r.path), h('td', {}, r.size), h('td', {}, r.sha256)));
      listHost.append(actions(before, h('span', { class: 't013-page' }, `第 ${page + 1}/${max + 1} 页，共 ${records.length} 项；每页 50 项，导出包含全部项。`), after), h('div', { class: 't013-scroll' }, h('table', { class: 't013-data' }, h('thead', {}, h('tr', {}, (report ? ['类别', '相对路径', '源字节', '目标字节', '源 SHA-256', '目标 SHA-256', '原因'] : ['相对路径', '实际字节数', 'SHA-256']).map(text => h('th', {}, text)))), h('tbody', {}, rows)))); }
    function showPreview(kind, extension) { if (busy || !manifest || (kind === 'report' && !report)) return; clearPreview(); try { const content = kind === 'manifest' ? exportManifest(manifest, extension) : exportReport(report, extension); preview = { content, extension, defaultName: kind === 'manifest' ? `T013-manifest.${extension}` : `T013-delivery-report.${extension}` }; const text = h('textarea', { rows: '12', readonly: true, 'aria-label': '完整导出预览' }); text.value = content; const expected = preview; previewHost.append(h('h3', {}, '完整内容与新副本路径确认'), h('p', {}, `拟创建 ${preview.defaultName}；包含所有文件，实际新路径在保存对话框确认，不能覆盖源文件或已有目标。`), text, button('保存已预览的新副本', () => savePreview(expected))); message('完整预览已生成，核对后再保存新副本。'); } catch (error) { message(error instanceof DeliveryError ? error.message : '预览失败，无部分输出。'); } }
    async function savePreview(expected) { if (!preview || preview !== expected || busy) return; const api = window.toolbox?.files; if (api?.saveTextSupportsCopyOnly !== true || typeof api.saveText !== 'function') { message('宿主缺少文本新副本保护接口，已阻止保存。'); return; } await task(async options => { const result = await api.saveText({ ...expected, copyOnly: true }); if (options.isCanceled() || preview !== expected) return; if (result?.ok === true) message('已保存清单或报告新副本，源/目标文件未修改。'); else if (result?.canceled === true) message('已取消保存，完整预览保留。'); else message('保存失败，完整预览保留；已有文件不能被覆盖。'); }); }
    function clear() { sourceFiles = []; targetFiles = []; sourceDirectory.value = ''; sourceFlat.value = ''; targetDirectory.value = ''; targetFlat.value = ''; importFile.value = ''; manifestText.value = ''; invalidateSource('文件引用、源清单、差异结果及预览已清除。'); }
    function hide() { if (document.hidden && !destroyed) { generation++; message('面板隐藏，当前读取/核验已取消；回来后手动操作。'); } }
    document.addEventListener('visibilitychange', hide);
    return { activate() { if (destroyed) return; active = true; update(); }, deactivate() { if (destroyed) return; active = false; generation++; update(); message('面板暂停，任务已取消；已完成结果保留，恢复后手动操作。'); }, destroy() { if (destroyed) return; clear(); destroyed = true; active = false; generation++; document.removeEventListener('visibilitychange', hide); root.replaceChildren(); } };
  }
};
