import{pngJPEGMeta as header}from'./raster.mjs';
const int=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b,exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).sort().join('|')===[...keys].sort().join('|');
export const LIMITS=Object.freeze({sourceBytes:2097152,edge:4096,pixels:4194304,workerMs:15000,outputBytes:2097152});
export function inspect(bytes){if(!(bytes instanceof Uint8Array)||bytes.length<8||bytes.length>LIMITS.sourceBytes)throw Error('来源8字节–2MiB');const h=header(bytes);if(h.width>4096||h.height>4096||h.width*h.height>LIMITS.pixels)throw Error('来源边≤4096/≤4194304像素');return{...h,type:h.mime};}
export function color(c){if(typeof c!=='string'||!/^#[0-9a-fA-F]{6}$/.test(c))throw Error('实色须#RRGGBB');return c.toLowerCase();}
export function rules(raw,width,height){if(!exact(raw,['masks','arrows','color'])||!int(width,1,4096)||!int(height,1,4096)||width*height>LIMITS.pixels||!Array.isArray(raw.masks)||raw.masks.length>32||!Array.isArray(raw.arrows)||raw.arrows.length>20)throw Error('完整规则须masks/arrows/color，≤32遮盖/≤20编号箭头');const c=color(raw.color),point=(x,y)=>int(x,0,width-1)&&int(y,0,height-1);const masks=raw.masks.map(m=>{if(!exact(m,['x','y','width','height'])||!point(m.x,m.y)||!int(m.width,1,width)||!int(m.height,1,height)||m.x+m.width>width||m.y+m.height>height)throw Error('遮盖须图内完整整数矩形');return{...m};}),arrows=raw.arrows.map((a,i)=>{if(!exact(a,['x1','y1','x2','y2'])||!point(a.x1,a.y1)||!point(a.x2,a.y2)||a.x1===a.x2&&a.y1===a.y2)throw Error('箭头须图内两个不同整数点');return{...a,number:i+1};});if(!masks.length&&!arrows.length)throw Error('至少一个遮盖或编号箭头，空规则不冒充处理');return{masks,arrows,color:c};}
export function parse(text,width,height){if(typeof text!=='string'||new TextEncoder().encode(text).length>16384)throw Error('完整规则JSON≤16KiB');let r;try{r=JSON.parse(text);}catch{throw Error('完整JSON无效');}return rules(r,width,height);}
export function maskPixels(pixels,width,height,rule){if(!(pixels instanceof Uint8ClampedArray)||pixels.length!==width*height*4)throw Error('完整RGBA无效');const c=rule.color,rgb=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)),seen=new Uint8Array(width*height);let count=0;for(const m of rule.masks)for(let y=m.y;y<m.y+m.height;y++)for(let x=m.x;x<m.x+m.width;x++){const k=y*width+x;if(!seen[k]){seen[k]=1;count++;}pixels.set([...rgb,255],k*4);}return{pixels:count,rgb,alpha:255,scope:'矩形半开区间并集；箭头之后最终逐像素实色覆盖，框内不保留原像素或图层。'};}
export function verifyMasks(pixels,width,height,rule){const rgb=[1,3,5].map(i=>parseInt(rule.color.slice(i,i+2),16));for(const m of rule.masks)for(let y=m.y;y<m.y+m.height;y++)for(let x=m.x;x<m.x+m.width;x++){const k=(y*width+x)*4;if(![...rgb,255].every((v,i)=>pixels[k+i]===v))throw Error('输出遮盖区实际像素不全为指定不透明实色');}return true;}
export function drawArrows(ctx,arrows,width,height){ctx.strokeStyle='#e3342f';ctx.fillStyle='#e3342f';ctx.lineWidth=3;ctx.lineCap='round';for(const a of arrows){const angle=Math.atan2(a.y2-a.y1,a.x2-a.x1),length=Math.min(12,Math.hypot(a.x2-a.x1,a.y2-a.y1)/3);ctx.beginPath();ctx.moveTo(a.x1,a.y1);ctx.lineTo(a.x2,a.y2);ctx.stroke();ctx.beginPath();ctx.moveTo(a.x2,a.y2);ctx.lineTo(a.x2-length*Math.cos(angle-Math.PI/6),a.y2-length*Math.sin(angle-Math.PI/6));ctx.lineTo(a.x2-length*Math.cos(angle+Math.PI/6),a.y2-length*Math.sin(angle+Math.PI/6));ctx.closePath();ctx.fill();const x=Math.min(Math.max(12,a.x1),Math.max(12,width-13)),y=Math.min(Math.max(12,a.y1),Math.max(12,height-13));ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(a.number),x,y);ctx.fillStyle='#e3342f';}return{color:'#e3342f',numberColor:'#ffffff',lineWidth:3,numberRadius:11,numberFont:'bold 14px Arial',order:'arrows in list order numbered1..n, final masks override overlapping glyph/arrow pixels'};}
export async function sha(bytes){return[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export function reportText(r){const t=JSON.stringify(r,null,2)+'\n';if(new TextEncoder().encode(t).length>2097152)throw Error('完整报告超过2MiB');return t;}
export function base64(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s);}
export async function bundle(r){const a=[{path:'annotated-redacted.png',bytes:r.bytes},{path:'annotation-report.json',bytes:new TextEncoder().encode(reportText(r.report))}];if(a.some(o=>o.bytes.length>2097152))throw Error('完整副本超过2MiB');return{copyOnly:true,defaultName:'截图标注遮盖新副本',files:await Promise.all(a.map(async o=>({path:o.path,base64:base64(o.bytes),sha256:await sha(o.bytes)})))};}
