export const MODEL_VERSION = 'L020-binary64-rational-v1';
export const POLICY = '仅十进制数、科学计数法、括号、一元±与四则运算；乘除优先，同级从左到右。不执行代码。表达式≤2048 UTF-8字节、128 token、嵌套/一元深度24、计算64步骤；单数数字≤64位（含前导零与小数部分），指数绝对值≤324；每个有理数约分后分子/分母≤4096二进制位，临时整数≤8193位。除零、非有限Number或容量越界拒绝整个结果。';
const bytes = text => new TextEncoder().encode(text).byteLength;
const abs = n => n < 0n ? -n : n;
const bits = n => abs(n).toString(2).length;
function gcd(a,b){a=abs(a);b=abs(b);while(b){[a,b]=[b,a%b];}return a;}
export function rational(n,d=1n){if(d===0n)throw new Error('精确有理数除零');if(bits(n)>8193||bits(d)>8193)throw new Error('临时整数超过8193位');if(d<0n){n=-n;d=-d;}const divisor=gcd(n,d);n/=divisor;d/=divisor;if(bits(n)>4096||bits(d)>4096)throw new Error('有理数分子/分母超过4096位，拒绝结果');return{n,d};}
export function operate(op,a,b){if(op==='+')return rational(a.n*b.d+b.n*a.d,a.d*b.d);if(op==='-')return rational(a.n*b.d-b.n*a.d,a.d*b.d);if(op==='*')return rational(a.n*b.n,a.d*b.d);if(op==='/')return rational(a.n*b.d,a.d*b.n);throw new Error('未知运算');}
export function decimalRational(text){const match=/^(\d+(?:\.\d*)?|\.\d+)(?:[eE]([+-]?\d+))?$/.exec(text);if(!match)throw new Error('非法十进制数');const digits=match[1].replace('.','');if(digits.length>64)throw new Error('单数数字最多64位（含前导零）');if(match[2]&&match[2].replace(/^[+-]/,'').length>3)throw new Error('指数绝对值最多324');const exponent=Number(match[2]||0);if(Math.abs(exponent)>324)throw new Error('指数绝对值最多324');const decimals=match[1].includes('.')?match[1].split('.')[1].length:0;const scale=decimals-exponent;return scale>=0?rational(BigInt(digits),10n**BigInt(scale)):rational(BigInt(digits)*10n**BigInt(-scale));}
export function displayRational(value){const n=abs(value.n);let remainder=n%value.d;let suffix='';for(let i=0;i<24&&remainder;i++){remainder*=10n;suffix+=(remainder/value.d).toString();remainder%=value.d;}let denominator=value.d;while(denominator%2n===0n)denominator/=2n;while(denominator%5n===0n)denominator/=5n;const terminating=denominator===1n;const decimal=`${value.n<0n?'-':''}${n/value.d}${suffix?'.'+suffix:''}`;return{numerator:value.n.toString(),denominator:value.d.toString(),fraction:value.d===1n?value.n.toString():`${value.n}/${value.d}`,decimal,decimalExact:remainder===0n,terminating,decimalLabel:remainder===0n?'精确十进制':terminating?'有限十进制超过24位：截断到小数后24位，非舍入近似':'非终止十进制：截断到小数后24位，非舍入近似'};}
export function inspectDouble(value){if(typeof value!=='number'||!Number.isFinite(value))throw new Error('只接受有限Number');const view=new DataView(new ArrayBuffer(8));view.setFloat64(0,value,false);const raw=view.getBigUint64(0,false);const sign=Number(raw>>63n);const exponent=Number((raw>>52n)&2047n);const fraction=raw&((1n<<52n)-1n);const classification=exponent===0?(fraction===0n?'zero':'subnormal'):'normal';const significand=exponent===0?fraction:(1n<<52n)+fraction;const power=exponent===0?-1074:exponent-1023-52;const signed=sign?-significand:significand;const actual=power<0?rational(signed,1n<<BigInt(-power)):rational(signed<<BigInt(power));return{numberText:Object.is(value,-0)?'-0':String(value),sign,signBits:String(sign),exponent,exponentBits:exponent.toString(2).padStart(11,'0'),fractionBits:fraction.toString(2).padStart(52,'0'),hex:raw.toString(16).padStart(16,'0'),classification,unbiasedExponent:exponent===0?-1022:exponent-1023,implicitBit:exponent===0?0:1,actual:displayRational(actual)};}
function doubleRational(value){const info=inspectDouble(value);return rational(BigInt(info.actual.numerator),BigInt(info.actual.denominator));}
export function tokenize(text){if(typeof text!=='string'||bytes(text)>2048)throw new Error('表达式须为≤2048 UTF-8字节文本');const tokens=[];let offset=0;while(offset<text.length){if(/\s/.test(text[offset])){offset++;continue;}const rest=text.slice(offset);const match=/^(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/.exec(rest);if(match){tokens.push({type:'number',text:match[0]});offset+=match[0].length;}else if('+-*/()'.includes(text[offset])){tokens.push({type:text[offset],text:text[offset]});offset++;}else throw new Error(`位置${offset+1}有不支持字符；不接受变量、函数或代码`);if(tokens.length>128)throw new Error('最多128个token');}if(!tokens.length)throw new Error('请输入表达式');return tokens;}
export function parseExpression(text){const tokens=tokenize(text);let position=0;const peek=()=>tokens[position]?.type;function primary(depth){if(depth>24)throw new Error('括号/一元嵌套深度最多24');if(peek()==='+'||peek()==='-'){const op=tokens[position++].type;return{type:'unary',op,child:primary(depth+1)};}if(peek()==='('){position++;const result=expression(depth+1);if(peek()!==')')throw new Error('括号不匹配');position++;return result;}if(peek()==='number'){const token=tokens[position++];decimalRational(token.text);return{type:'literal',text:token.text};}throw new Error('缺少数值或括号；不支持隐式乘法');}function product(depth){let node=primary(depth);while(peek()==='*'||peek()==='/'){const op=tokens[position++].type;node={type:'binary',op,left:node,right:primary(depth)};}return node;}function expression(depth){let node=product(depth);while(peek()==='+'||peek()==='-'){const op=tokens[position++].type;node={type:'binary',op,left:node,right:product(depth)};}return node;}const ast=expression(0);if(position!==tokens.length)throw new Error('多余token或括号；不支持隐式乘法');return{ast,tokenCount:tokens.length};}
export function example(kind='sum'){return{expression:({sum:'0.1 + 0.2',cancel:'(1e16 + 1) - 1e16',fraction:'1 / 3',negativeZero:'-0 * 2',subnormal:'5e-324',underflow:'1e-324'})[kind]||'0.1 + 0.2'};}
export function evaluate(draft){const parsed=parseExpression(draft?.expression);const steps=[];function visit(node){if(steps.length>=64)throw new Error('计算最多64步骤，拒绝而不截断');let exact;let value;let local;let label;let operands=[];let kind;
    if(node.type==='literal'){exact=decimalRational(node.text);value=Number(node.text);if(!Number.isFinite(value))throw new Error('输入Number非有限（溢出），拒绝结果');local=operate('-',doubleRational(value),exact);label=node.text;kind='input';}
    else if(node.type==='unary'){const a=visit(node.child);value=node.op==='-'?-a.value:a.value;exact=node.op==='-'?rational(-a.exact.n,a.exact.d):a.exact;const fromOperands=node.op==='-'?rational(-a.actual.n,a.actual.d):a.actual;local=operate('-',doubleRational(value),fromOperands);label=`${node.op}步骤${a.step}`;operands=[a.step];kind='unary';}
    else{const a=visit(node.left);const b=visit(node.right);if(node.op==='/'&&(b.exact.n===0n||b.value===0))throw new Error('除零：精确分母或Number分母为零（含下溢零和负零），拒绝结果');exact=operate(node.op,a.exact,b.exact);if(node.op==='+')value=a.value+b.value;else if(node.op==='-')value=a.value-b.value;else if(node.op==='*')value=a.value*b.value;else value=a.value/b.value;if(!Number.isFinite(value))throw new Error('运算Number非有限（溢出），拒绝结果');const fromOperands=operate(node.op,a.actual,b.actual);local=operate('-',doubleRational(value),fromOperands);label=`步骤${a.step} ${node.op} 步骤${b.step}`;operands=[a.step,b.step];kind='operation';}
    if(steps.length>=64)throw new Error('计算最多64步骤，拒绝而不截断');const actual=doubleRational(value);const record={step:steps.length+1,kind,label,operands,double:inspectDouble(value),exact:displayRational(exact),localError:displayRational(local),totalError:displayRational(operate('-',actual,exact))};steps.push(record);return{step:record.step,value,exact,actual};}
  visit(parsed.ast);return{modelVersion:MODEL_VERSION,input:{expression:draft.expression},tokenCount:parsed.tokenCount,steps,final:steps.at(-1)};}
export function prepareStoredState(draft){if(typeof draft?.expression!=='string')throw new Error('草稿字段类型不合法');const state={schemaVersion:1,expression:draft.expression};if(bytes(JSON.stringify(state))>65536)throw new Error('草稿超过64KiB UTF-8限制');if(bytes(state.expression)>2048)throw new Error('表达式草稿超过2048字节');return state;}
export function validateStoredState(raw){if(bytes(JSON.stringify(raw))>65536)throw new Error('草稿超过64KiB UTF-8限制');if(raw?.schemaVersion!==1)throw new Error('草稿版本不支持');return prepareStoredState(raw);}
const escape=text=>String(text).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
export function reportMarkdown(payload){const sections=['# L020 浮点误差显微镜',POLICY,'## 完整输入',`\`\`\`json\n${escape(JSON.stringify(payload.draft,null,2))}\n\`\`\``,'## 误差定义','所有误差都是有符号差值。输入表示误差=实际double精确值−原十进制值；操作误差=结果double精确值−对实际double操作数做同一运算的精确值；总误差=实际double值−原十进制表达式精确值。Number文本是最短显示，不是其完整精确十进制。有理数零不区分符号，double位模式保留负零。'];if(!payload.result)sections.push('尚未生成有效结果。');else{sections.push('## 最终结果',`精确对照：${payload.result.final.exact.decimal}（${payload.result.final.exact.decimalLabel}）；Number：${payload.result.final.double.numberText}`);for(const row of payload.result.steps)sections.push(`### 步骤${row.step} ${row.kind} ${row.label}`,`\`\`\`json\n${escape(JSON.stringify(row,null,2))}\n\`\`\``);sections.push('## 完整模型记录',`\`\`\`json\n${escape(JSON.stringify(payload.result,null,2))}\n\`\`\``);}sections.push('## 范围与保存','有限表达式教学；有理数展示分数为精确值，未终止的十进制或超过24位显示为截断近似。配置仅存有界版本输入草稿，不存结果；结果重新计算。','参考：https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types-number-type','位模式参考：https://docs.oracle.com/cd/E19957-01/806-3568/ncg_math.html');return sections.join('\n\n');}
