export const LIMITS=Object.freeze({capsules:8,textPoints:2000,textBytes:8192,imageBytes:262144,side:1024,archiveBytes:2097152});
export function validText(text){if(typeof text!=='string'||text.length>4000)throw Error('正文最多2000码点/8KiB。');let points=0;for(let i=0;i<text.length;i++,points++){const c=text.charCodeAt(i);if(c>=0xD800&&c<=0xDBFF){const n=text.charCodeAt(++i);if(!(n>=0xDC00&&n<=0xDFFF))throw Error('无效Unicode正文。');}else if(c>=0xDC00&&c<=0xDFFF||(c<32&&![9,10,13].includes(c))||c===127)throw Error('无效Unicode或控制字符正文。');}const bytes=new TextEncoder().encode(text).length;if(points>2000||bytes>8192)throw Error('正文最多2000码点/8KiB。');return{points,bytes};}
export function day(date){if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/u.test(date))throw Error('日期须为YYYY-MM-DD。');const[y,m,d]=date.split('-').map(Number),n=Date.UTC(y,m-1,d),v=new Date(n);if(y<1900||y>9999||v.getUTCFullYear()!==y||v.getUTCMonth()!==m-1||v.getUTCDate()!==d)throw Error('日期不是有效1900至9999年日历日期。');return n/86400000;}
export function localToday(now=Date.now()){const d=new Date(now);if(!Number.isFinite(d.getTime()))throw Error('本机时钟无效。');const s=`${String(d.getFullYear()).padStart(4,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;day(s);return s;}
export const emptyArchive=()=>({schema:1,capsules:[]});
const fields=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join('|')!==[...keys].sort().join('|'))throw Error('档案字段不完整或含未知字段。');};
export function archiveJSON(value){const text=JSON.stringify(value,null,2);if(new TextEncoder().encode(text).length>LIMITS.archiveBytes)throw Error('完整档案超过2MiB UTF-8字节，未截断。');return text;}
// Limited schema reader: duplicate keys and non-integer numeric tokens rejected before JSON conversion.
export function parseArchiveJSON(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>LIMITS.archiveBytes)throw Error('备份最多2MiB UTF-8字节。');let p=0;const ws=()=>{while(/[\x20\t\r\n]/u.test(text[p]||'x'))p++;};function string(){const start=p++;for(;p<text.length;p++){if(text[p]==='\\'){p++;continue;}if(text[p]==='"'){p++;return JSON.parse(text.slice(start,p));}}throw Error('JSON字符串未结束。');}function value(depth=0){ws();if(depth>8)throw Error('JSON层级超过8。');const c=text[p];if(c==='"')return string();if(c==='{'){p++;ws();const o=Object.create(null),seen=new Set();if(text[p]==='}'){p++;return o;}while(true){ws();if(text[p]!=='"')throw Error('JSON对象键无效。');const k=string();if(seen.has(k))throw Error('JSON重复字段：'+k);seen.add(k);ws();if(text[p++]!==':')throw Error('JSON缺少冒号。');o[k]=value(depth+1);ws();const end=text[p++];if(end==='}')return o;if(end!==',')throw Error('JSON对象分隔无效。');}}if(c==='['){p++;ws();const a=[];if(text[p]===']'){p++;return a;}while(true){if(a.length>=16)throw Error('JSON数组过长。');a.push(value(depth+1));ws();const end=text[p++];if(end===']')return a;if(end!==',')throw Error('JSON数组分隔无效。');}}for(const[token,result]of[['null',null],['true',true],['false',false]])if(text.startsWith(token,p)){p+=token.length;return result;}const start=p;while(p<text.length&&!/[\x20\t\r\n,\]}]/u.test(text[p]))p++;const token=text.slice(start,p);if(!/^-?(?:0|[1-9]\d*)$/u.test(token)||!Number.isSafeInteger(Number(token)))throw Error('JSON数值须为安全十进制整数，不接受精度丢失/小数/指数。');return Number(token);}const root=value();ws();if(p!==text.length)throw Error('JSON尾部有额外数据。');return root;}
export function crc32(bytes){let crc=0xFFFFFFFF;for(const b of bytes){crc^=b;for(let n=0;n<8;n++)crc=(crc>>>1)^((crc&1)?0xEDB88320:0);}return(crc^0xFFFFFFFF)>>>0;}
export function pngHeader(bytes){if(!(bytes instanceof Uint8Array)||bytes.length<45||bytes.length>LIMITS.imageBytes||![137,80,78,71,13,10,26,10].every((b,i)=>bytes[i]===b))throw Error('只支持静态PNG，单图≤256KiB；不接受SVG或伪造扩展名。');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let p=8,width=0,height=0,idat=false,ended=false,totalData=0;const seen=new Set();while(p<bytes.length){if(p+12>bytes.length)throw Error('PNG块边界损坏。');const n=view.getUint32(p),type=String.fromCharCode(...bytes.subarray(p+4,p+8));if(n>bytes.length-p-12||!['IHDR','IDAT','IEND','PLTE','tRNS','sRGB','gAMA','cHRM','pHYs'].includes(type))throw Error('PNG块越界或含不支持的附加/动画块：'+type);if(crc32(bytes.subarray(p+4,p+8+n))!==view.getUint32(p+8+n))throw Error('PNG CRC不匹配。');if(type==='IHDR'){if(p!==8||n!==13||seen.has(type))throw Error('PNG头无效。');width=view.getUint32(p+8);height=view.getUint32(p+12);if(!width||!height||width>1024||height>1024||!({0:[1,2,4,8,16],2:[8,16],3:[1,2,4,8],4:[8,16],6:[8,16]}[bytes[p+17]]||[]).includes(bytes[p+16])||bytes[p+18]||bytes[p+19]||bytes[p+20]>1)throw Error('PNG须为≤1024×1024且位深/颜色类型符合规范。');}else if(!width)throw Error('PNG缺少首个IHDR。');if(type==='IDAT'){if(ended)throw Error('PNG数据顺序无效。');idat=true;totalData+=n;}else if(type==='IEND'){if(!idat||!totalData||n!==0||p+12!==bytes.length)throw Error('PNG末块/尾部无效。');ended=true;}else if(type!=='IHDR'){if(idat||seen.has(type)||!(type==='PLTE'?n>0&&n<=768&&n%3===0:type==='tRNS'?n>0&&n<=256:n===({sRGB:1,gAMA:4,cHRM:32,pHYs:9}[type])))throw Error('PNG附加块长度/顺序无效。');}seen.add(type);p+=n+12;}if(!ended)throw Error('PNG未完整结束。');return{mime:'image/png',width,height,bytes:bytes.length};}
export const imageURL=image=>`data:${image.mime};base64,${image.base64}`;
// T.81 marker framing, baseline/progressive 8-bit gray/RGB. Entropy decoding belongs to browser.
export function jpegHeader(bytes){if(!(bytes instanceof Uint8Array)||bytes.length<20||bytes.length>LIMITS.imageBytes||bytes[0]!==255||bytes[1]!==216)throw Error('JPEG签名/256KiB字节限额无效。');let p=2,width=0,height=0,scans=0,inScan=false;while(p<bytes.length){if(inScan){while(p<bytes.length&&bytes[p]!==255)p++;if(p>=bytes.length)throw Error('JPEG缺少EOI。');let q=p+1;while(bytes[q]===255)q++;if(bytes[q]===0||bytes[q]>=208&&bytes[q]<=215){p=q+1;continue;}inScan=false;}if(bytes[p++]!==255)throw Error('JPEG标记边界无效。');while(bytes[p]===255)p++;const marker=bytes[p++];if(marker===217){if(!width||!scans||p!==bytes.length)throw Error('JPEG末标记或尾部无效。');return{mime:'image/jpeg',width,height,bytes:bytes.length};}if(marker===216||marker===0||marker===1||marker>=208&&marker<=215)throw Error('JPEG标记顺序不支持。');if(p+2>bytes.length)throw Error('JPEG块截断。');const n=(bytes[p]<<8)|bytes[p+1];if(n<2||p+n>bytes.length)throw Error('JPEG块长度越界。');if(marker>=192&&marker<=207&&![196,200,204].includes(marker)){if(![192,194].includes(marker)||width||n<11||bytes[p+2]!==8||![1,3].includes(bytes[p+7])||n!==8+3*bytes[p+7])throw Error('JPEG仅支持8-bit基线/渐进灰度或RGB，不支持CMYK/算术/多帧。');height=(bytes[p+3]<<8)|bytes[p+4];width=(bytes[p+5]<<8)|bytes[p+6];if(!width||!height||width>1024||height>1024)throw Error('JPEG编码尺寸须≤1024×1024。');}if(marker===218){if(!width||n<6||n!==6+2*bytes[p+2])throw Error('JPEG扫描头无效。');scans++;inScan=true;}p+=n;}throw Error('JPEG未完整结束。');}
export async function inspectImage(bytes){const info=bytes[0]===255&&bytes[1]===216?jpegHeader(bytes):pngHeader(bytes),hash=new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes));let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return{...info,sha256:[...hash].map(v=>v.toString(16).padStart(2,'0')).join(''),base64:btoa(binary)};}
export async function validateArchive(value,{decodeImage=async()=>{},check=()=>{}}={}){fields(value,['schema','capsules']);if(value.schema!==1)throw Error('仅支持schema1，未知版本拒绝。');if(!Array.isArray(value.capsules)||value.capsules.length>8)throw Error('最多8个胶囊。');archiveJSON(value);const ids=new Set(),capsules=[];for(const c of value.capsules){check();fields(c,['id','createdDate','openDate','text','image']);if(typeof c.id!=='string'||!/^C00[1-8]$/u.test(c.id)||ids.has(c.id))throw Error('胶囊编号无效或重复。');ids.add(c.id);day(c.createdDate);if(day(c.openDate)<=day(c.createdDate)||day(c.openDate)-day(c.createdDate)>36600)throw Error('开启日期须在创建日之后100年范围内。');const metrics=validText(c.text);if(!metrics.points&&!c.image)throw Error('胶囊须有文字或图片。');let image=null;if(c.image!==null){fields(c.image,['mime','width','height','bytes','sha256','base64']);const b=c.image.base64;if(typeof b!=='string'||b.length>349528||b.length%4||!/^[A-Za-z0-9+/]*={0,2}$/u.test(b))throw Error('图片Base64无效。');let binary;try{binary=atob(b);}catch{throw Error('图片Base64无法解码。');}if(btoa(binary)!==b)throw Error('图片Base64不是规范编码。');image=await inspectImage(Uint8Array.from(binary,s=>s.charCodeAt(0)));if(Object.keys(image).some(k=>image[k]!==c.image[k]))throw Error('图片摘要、类型、尺寸或字节数不一致。');await decodeImage(image);check();}capsules.push({id:c.id,createdDate:c.createdDate,openDate:c.openDate,text:c.text,image});}return{schema:1,capsules};}
export async function seal(value,{text,openDate,image},today,hooks={}){day(today);if(day(openDate)<=day(today)||day(openDate)-day(today)>36600)throw Error('请选择今天之后100年范围内的开启日期。');if(value.capsules.length>=8)throw Error('已满8个胶囊，请先备份后明确删除。');const id=Array.from({length:8},(_,i)=>`C00${i+1}`).find(id=>!value.capsules.some(c=>c.id===id));return validateArchive({schema:1,capsules:[...value.capsules,{id,createdDate:today,openDate,text,image}]},hooks);}
export function mayReveal(capsule,today,early=false){day(today);if(day(today)<day(capsule.openDate)&&early!==true)throw Error('尚未到期，请明确勾选提前开启。');return true;}
