import{h}from'../../core/ui.js';
import{RULES,createGame,publicView,privateWord,finishCard,startVote,startTie,cast,stop,archive,restore,parse,report,destroyGame}from'./model.mjs';
export default{id:'E022',create(root,ctx={}){
 let alive=true,active=false,game=null,candidate=null,namesRaw='甲\n乙\n丙\n丁\n戊\n己',under=1,seen=false,privateNode=null,privateTimer=null,shown=false,reading=false,saving=false,version=0,ackArchive=false,ackRestore=false,ackStop=false,ackNew=false,message='交给当前玩家，其他人暂时避开屏幕。',bindings=[];
 const phases={deal:'逐人看词',talk:'发言',vote:'逐人投票',tie:'平票加赛',ended:'已结束'};const files=()=>window.toolbox?.files||{},usable=()=>alive&&active&&!document.hidden,editable=()=>usable()&&!reading&&!saving,scrub=()=>{clearTimeout(privateTimer);privateTimer=null;if(privateNode)privateNode.textContent='';privateNode=null;shown=false;for(const[n,t,f]of bindings)n.removeEventListener(t,f);bindings=[];for(const n of root.querySelectorAll('input,textarea,select'))n.value='';root.replaceChildren();},on=(n,t,f)=>{const handler=e=>{if(!alive)return;return f(e);};n.addEventListener(t,handler);bindings.push([n,t,handler]);return n;},button=(label,fn,disabled=false)=>on(h('button',{type:'button',disabled},label),'click',async()=>{if(!editable())return;try{await fn();}catch(e){message='未执行：'+e.message;render();}}),check=(label,value,fn)=>{const n=h('input',{type:'checkbox','aria-label':label,checked:value,disabled:!editable()});on(n,'change',()=>{if(editable()){fn(n.checked);render();}});return h('label',{},n,label);};
 function hide(text='词卡已遮挡；确认记住后再交给下一位。'){clearTimeout(privateTimer);privateTimer=null;if(privateNode)privateNode.textContent='';privateNode=null;shown=false;message=text;render();}
 function act(fn,text){fn();version++;seen=false;ackStop=ackNew=ackArchive=ackRestore=false;message=text;render();}
 function render(){if(!alive)return; // Never preserve a secret node across any rerender.
  scrub();const locked=!editable(),v=game?publicView(game):null,body=[h('h2',{},'谁是卧底'),h('p',{},RULES),h('p',{},'同一设备轮流查看，依靠参与者合作遮挡；不能抵御旁观、开发者工具或本机文件访问。未结束时只显示姓名，不公布身份/别人的词。')];
  if(!game){const names=h('textarea',{'aria-label':'玩家姓名',rows:6,disabled:locked,style:{display:'block',width:'300px'}});names.value=namesRaw;on(names,'input',()=>{if(editable())namesRaw=names.value;});const n=h('input',{'aria-label':'卧底人数',type:'number',min:1,max:4,value:under,disabled:locked});on(n,'input',()=>{if(editable())under=Number(n.value);});body.push(h('p',{},'4–10名玩家，一行一人，不留空行；1–24码点、姓名唯一。卧底少于平民，无白板玩家。'),names,n,button('建立本局并逐人看词',()=>{const next=createGame(namesRaw.split(/\r?\n/),under);game=next;act(()=>{},'本局配置已锁定，交给第1位玩家。');},locked));}
  if(v){body.push(h('p',{'aria-label':'本局公开状态'},`第${v.round}/30发言轮 · ${phases[v.phase]} · 初始卧底${v.undercover} · 存活${v.alive.length}/${v.names.length}`),h('p',{'aria-label':'存活玩家'},v.names.map((name,id)=>name+(v.alive.includes(id)?'（存活）':(v.phase==='ended'?'（出局）':'（出局，未揭示身份）'))).join('、')));
   if(v.phase==='deal'){const name=v.names[v.dealPlayer];body.push(h('h3',{},`请交给 ${name} · 第${v.dealPlayer+1}/${v.names.length}位`),h('p',{'aria-label':'词卡遮挡页'},'词卡遮挡。只看自己的词，不会告诉你是哪种身份。'),button('我是'+name+'，查看自己的词（8秒自动遮挡）',()=>{if(!editable())return;hide('当前玩家正在私密查看，其他人避开屏幕。');const word=privateWord(game);privateNode=h('p',{'aria-label':'本人私密词',style:{fontSize:'32px',fontWeight:'bold',padding:'25px',background:'#f6ecd0'}},word);root.querySelector('[data-private-slot]').append(privateNode);shown=true;seen=true;const handoff=[...root.querySelectorAll('button')].find(n=>n.textContent==='记住词，遮挡并交接');if(handoff)handoff.disabled=false;const cardVersion=version,cardNode=privateNode;privateTimer=setTimeout(()=>{if(alive&&shown&&version===cardVersion&&privateNode===cardNode)hide('8秒到，已自动回遮挡页。');},8000);},locked),h('div',{'data-private-slot':''}),button('遮挡自己的词',()=>hide(),locked),button('记住词，遮挡并交接',()=>{if(!seen)throw Error('请先本人查看并记住词');act(()=>finishCard(game),'旧词卡已清空，交给下一位；发完后进入发言。');},locked||!seen));}
   else if(v.phase==='talk'){body.push(h('h3',{},`第${v.round}轮发言`),h('p',{},'存活玩家按姓名列表顺序轮流描述；不要读出原词。发言由同桌口头完成，本工具不录音、不自动判断描述。'),button('大家发言完毕，开始逐人投票',()=>act(()=>startVote(game),'投票按存活姓名顺序，每人不能投自己。'),locked));}
   else if(v.phase==='vote'){const name=v.names[v.voter],target=h('select',{'aria-label':'本人的投票对象',disabled:locked});target.append(h('option',{value:''},'请选择其他候选'));for(const id of v.candidates)if(id!==v.voter)target.append(h('option',{value:id},v.names[id]));target.value='';body.push(h('h3',{},`请交给 ${name} 投票 · ${v.castCount+1}/${v.alive.length}`),h('p',{},v.attempt===1?'首轮投票：所有其他存活者可选。':'平票加赛：只能投最高票候选，仍不能投自己。'),target,button('确认本人投票并遮挡交接',()=>{if(target.value==='')throw Error('先选一个候选');act(()=>cast(game,Number(target.value)),'本票已记录，旧选择已清空；整次投票完才公布票数。');},locked));}
   else if(v.phase==='tie'){body.push(h('h3',{},'最高票平票'),h('p',{},'本次无人淘汰；一次加赛候选：'+v.candidates.map(id=>v.names[id]).join('、')+'。若仍平票，本发言轮无人出局进入下一轮。'),button('开始一次限定候选加赛',()=>act(()=>startTie(game),'加赛按存活姓名顺序逐人投票。'),locked));}
   else if(v.phase==='ended'){body.push(h('h3',{'aria-label':'终局结果'},v.complete?'本局完整结束，'+v.winner+'胜':'本局中断，没有胜者'),h('p',{},v.reason),h('h3',{},'结束后完整揭晓'),h('ul',{'aria-label':'终局身份与词'},...v.reveal.players.map(p=>h('li',{},`${p.name}：${p.role} / ${p.word}`))));}
   body.push(h('h3',{},'已完成投票记录'),h('div',{'aria-label':'完整已完成投票'},...v.history.map(r=>h('section',{},h('h4',{},`第${r.round}轮 第${r.attempt}次投票`),h('p',{},r.counts.map(c=>v.names[c.id]+' '+c.count+'票').join('、')),h('p',{},r.eliminated===null?'平票，没有淘汰':v.names[r.eliminated]+(v.phase==='ended'?'出局（身份见终局揭晓）':'出局；其身份到终局再公开')),h('details',{},h('summary',{},'公开本次完整票单'),...r.ballots.map(b=>h('p',{},v.names[b.player]+' → '+v.names[b.target])))))));
   body.push(button('另存公开JSON记录',()=>save('json'),locked||files().saveTextSupportsCopyOnly!==true),button('另存公开Markdown记录',()=>save('md'),locked||files().saveTextSupportsCopyOnly!==true),h('h3',{},'手动继续本局'),h('p',{},'完整存档包含所有词/身份和未完成票单，是未加密本机JSON；其他玩家不应打开。公开记录不能恢复秘密本局。不会自动写配置。'),check('我理解完整存档包含全部秘密，明确另存',ackArchive,v=>ackArchive=v),button('另存含秘密完整存档',()=>save('archive'),locked||!ackArchive||files().saveTextSupportsCopyOnly!==true));
   if(v.phase!=='ended')body.push(check('确认主动结束并揭晓全部秘密',ackStop,v=>ackStop=v),button('主动结束，标明中断并揭晓',()=>{if(!ackStop)return;act(()=>stop(game),'已明确主动结束，无胜者；现在可以揭晓。');},locked||!ackStop));body.push(check('确认丢弃当前局并设置新局',ackNew,v=>ackNew=v),button('返回设置并新建',()=>{if(!ackNew)return;destroyGame(game);game=null;seen=false;version++;ackNew=ackArchive=ackStop=false;message='当前局已明确丢弃；请设置新局。';render();},locked||!ackNew));}
  const input=h('input',{'aria-label':'含秘密完整存档JSON',type:'file',accept:'.json,application/json',disabled:locked});on(input,'change',()=>read(input.files?.[0]));const cv=candidate?publicView(candidate):null;body.push(h('h3',{},'从完整存档恢复'),h('p',{},'UTF8 schema1 ≤64KiB，全部事件回放校验；预览不显示秘密词/身份，应用后也先遮挡。'),input,h('p',{'aria-label':'待恢复公开摘要'},cv?`${cv.names.length}人：${cv.names.join('、')} · 第${cv.round}轮 · ${phases[cv.phase]} · ${cv.complete?'完整结束':'尚未完成或中断'}`:'无待恢复本局。'),check('确认用存档替换当前局',ackRestore,v=>ackRestore=v),button('应用完整存档并遮挡',()=>{if(!candidate||!ackRestore)return;if(game)destroyGame(game);game=candidate;candidate=null;version++;seen=false;ackRestore=ackArchive=ackStop=ackNew=false;message='完整事件与秘密已恢复，词卡保持遮挡，需要本人重新查看。';render();},locked||!candidate||!ackRestore));
  if(reading){const n=h('button',{type:'button',disabled:!usable()},'取消存档读取');on(n,'click',()=>{if(usable()){version++;message='读取结果已作废，等待读取结束。';render();}});body.push(n);}body.push(h('p',{'aria-label':'操作状态',role:'status'},message+(files().saveTextSupportsCopyOnly!==true?' 当前桥缺copyOnly安全副本能力。':'')));root.replaceChildren(h('section',{style:{padding:'18px',maxWidth:'1100px'}},...body));
 }
 async function save(format){if(!editable()||!game||files().saveTextSupportsCopyOnly!==true)return;if(format==='archive'&&!ackArchive)return;const token=version,current=()=>usable()&&token===version;hide('词卡已遮挡，正在另存…');saving=true;render();try{const content=format==='archive'?archive(game):report(game,format);if(!current())return;const r=await files().saveText({copyOnly:true,extension:format==='md'?'md':'json',defaultName:format==='archive'?'谁是卧底-含秘密完整存档.json':'谁是卧底-公开记录.'+format,content});if(!current())return;message=r?.ok===true?'完整新副本已保存。':r?.canceled?'保存取消，未报告成功。':'保存失败：'+(r?.error||'回执不是ok===true')+(r?.partialPath?'；人工核对 '+r.partialPath:'');}catch(e){if(current())message='保存失败：'+e.message;}finally{saving=false;ackArchive=false;if(alive)render();}}
 async function read(file){if(!editable()||!file)return;hide('读取完整存档，当前词卡已遮挡。');if(candidate)destroyGame(candidate);candidate=null;ackRestore=false;reading=true;const token=++version,current=()=>usable()&&version===token;render();try{if(!Number.isSafeInteger(file.size)||file.size<1||file.size>65536)throw Error('存档1字节至64KiB');const b=new Uint8Array(await file.arrayBuffer());if(!current())return;if(b.length!==file.size)throw Error('File字节数不符');const source=parse(new TextDecoder('utf-8',{fatal:true}).decode(b));if(!current())return;candidate=restore(source);message='完整存档已回放验证；只预览公开摘要，确认后替换。';}catch(e){if(current())message='恢复拒绝：'+e.message;}finally{reading=false;if(alive)render();}}
 const visibility=()=>{if(document.hidden){version++;seen=false;hide('页面隐藏，词卡已遮挡；回来需要重新本人查看。');}else render();};document.addEventListener('visibilitychange',visibility);render();return{activate(){if(alive){active=true;render();}},deactivate(){if(!alive)return;active=false;version++;seen=false;hide('已暂停并遮挡，回来不会自动显示秘密。');},destroy(){if(!alive)return;active=false;version++;scrub();alive=false;document.removeEventListener('visibilitychange',visibility);if(game)destroyGame(game);if(candidate)destroyGame(candidate);game=candidate=null;namesRaw='';root.replaceChildren();}};
}};
