import { h } from '../../core/ui.js';
import { SEASONS, TIMES, createSession, sceneSVG, pngBlob, pngPayload } from './model.mjs';

export default { id: 'E033', create(root) {
  const session = createSession(), host = h('div', { 'aria-label': '完整四季窗景', style: { width: '100%', maxWidth: '1000px' } });
  const media = window.matchMedia?.('(prefers-reduced-motion: reduce)'); let systemReduce = media?.matches === true, manualReduce = false, season = 'spring', time = 'day', alive = true, active = true, frame = null, timer = null, status = null, source = '', message = '', busy = false, nativePending = false, generation = 0;
  const bindings = [], urls = new Set(); const reduced = () => manualReduce || systemReduce;
  function cancelSchedules() { if (frame !== null) cancelAnimationFrame(frame); if (timer !== null) clearTimeout(timer); frame = timer = null; }
  function paint() { source = sceneSVG({ season, time, reduce: reduced(), elapsedMs: session.snapshot().elapsedMs }); host.innerHTML = source; const svg = host.querySelector('svg'); if (svg) { svg.style.width = '100%'; svg.style.height = 'auto'; svg.style.display = 'block'; } }
  function summary() { const s = session.snapshot(); if (s.complete) return `本次${s.minutes}分钟已结束，自动暂停。重新计时后可再次开始。`; if (s.running) return reduced() ? `静态休息计时中，累计播放满${s.minutes}分钟即结束；没有连续绘画。` : `缓慢播放中，还需约${Math.ceil(s.remainingMs / 1000)}秒。`; return `已暂停；累计播放${Math.floor(s.elapsedMs / 1000)}秒，还需${Math.ceil(s.remainingMs / 1000)}秒。暂停/离开不计入时长。`; }
  function stop(text = '') { session.pause(); cancelSchedules(); if (text) message = text; }
  function deadline() { timer = null; if (!alive || !active || document.hidden) return; const s = session.snapshot(); if (s.complete) { cancelSchedules(); message = '所选播放时长已到，已自动暂停。'; paint(); render(); } else if (s.running) timer = setTimeout(deadline, Math.ceil(s.remainingMs)); }
  function draw() { frame = null; if (!alive || !active || document.hidden || reduced()) return; const s = session.snapshot(); if (!s.running || s.complete) { cancelSchedules(); message = '所选播放时长已到，已自动暂停。'; paint(); render(); return; } paint(); if (status) status.textContent = summary(); frame = requestAnimationFrame(draw); }
  function start() { if (document.hidden) throw Error('页面隐藏，不能开始'); session.start(); cancelSchedules(); const s = session.snapshot(); timer = setTimeout(deadline, Math.ceil(s.remainingMs)); if (!reduced()) frame = requestAnimationFrame(draw); message = reduced() ? '已开始静态休息计时，减少动效不播放飘落粒子。' : ''; render(); }
  function on(node, type, fn) { const guarded = async e => { if (!alive || !active || busy) return; try { await fn(e); } catch (error) { message = error.message || '操作失败'; render(); } }; node.addEventListener(type, guarded); bindings.push([node, type, guarded]); return node; }
  function btn(text, fn, disabled = false) { return on(h('button', { type: 'button', class: 'btn', disabled }, text), 'click', fn); }
  function selector(label, choices, value, fn, disabled = false) { const node = h('select', { 'aria-label': label, disabled }, ...choices.map(([key, text]) => h('option', { value: key }, text))); node.value = value; on(node, 'change', () => fn(node.value)); return h('label', {}, label + ' ', node); }
  function scrub() { for (const [node, type, fn] of bindings.splice(0)) node.removeEventListener(type, fn); for (const node of root.querySelectorAll('input,select')) node.value = ''; root.replaceChildren(); }
  function check(token) { if (!alive || !active || document.hidden || token !== generation) throw new DOMException('已取消图片生成', 'AbortError'); }
  async function save() {
    const files = window.toolbox?.files; if (files?.saveBinarySupportsCopyOnly !== true || typeof files.saveBinary !== 'function') throw Error('缺少安全二进制副本接口'); stop('留影会暂停播放和计时，保存当前完整窗景。'); paint(); const svg = source, token = ++generation; busy = true; nativePending = false; render();
    const image = new Image(), url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' })); urls.add(url);
    try { await new Promise((resolve, reject) => { image.onload = resolve; image.onerror = () => reject(Error('窗景SVG解码失败')); image.src = url; }); check(token); const canvas = document.createElement('canvas'); canvas.width = 1000; canvas.height = 700; const context = canvas.getContext('2d'); if (!context) throw Error('Canvas 2D不可用'); context.drawImage(image, 0, 0, 1000, 700); const blob = await pngBlob(canvas); check(token); const payload = await pngPayload(blob, `season-window-${season}-${time}-copy.png`); check(token); nativePending = true; render(); const result = await files.saveBinary(payload); check(token); message = result?.canceled === true ? '已取消另存，仍暂停' : result?.ok === true ? `已保存完整窗景PNG副本：${result.path || ''}` : `保存失败：${result?.error || '未返回成功结果'}${result?.partialPath ? '；请人工核对：' + result.partialPath : ''}`; }
    catch (error) { if (alive && active) message = error.name === 'AbortError' ? '已取消图片生成，仍暂停' : `保存失败：${error.message}`; }
    finally { image.onload = image.onerror = null; image.src = ''; URL.revokeObjectURL(url); urls.delete(url); busy = nativePending = false; if (alive && active) render(); }
  }
  function render() {
    if (!alive) return; scrub(); root.append(h('h2', {}, '四季窗景'), h('p', {}, '程序矢量窗外景观，完全离线。先选季节与时段，再明确开始；没有声音、摄像头或联网。'));
    if (!active) { root.append(h('p', {}, '已离开并暂停，返回不自动播放。')); return; }
    if (message) root.append(h('p', { role: 'status' }, message)); const s = session.snapshot(); status = h('p', {}, summary()); root.append(status);
    root.append(h('div', {}, selector('窗景季节', Object.entries(SEASONS), season, value => { if (!Object.hasOwn(SEASONS, value)) throw Error('季节无效'); stop('切换季节已暂停，累计计时保留。'); season = value; paint(); render(); }), selector('窗景时段', Object.entries(TIMES), time, value => { if (!Object.hasOwn(TIMES, value)) throw Error('时段无效'); stop('切换时段已暂停，累计计时保留。'); time = value; paint(); render(); }), selector('累计播放分钟', Array.from({ length: 5 }, (_, i) => [String(i + 1), `${i + 1}分钟`]), String(s.minutes), value => { session.reset(Number(value)); cancelSchedules(); message = '更改时长已建立新计时并保持暂停。'; paint(); render(); }, s.running)));
    const reduceBox = h('input', { type: 'checkbox', checked: reduced(), disabled: systemReduce, 'aria-label': '减少动效' }); on(reduceBox, 'change', () => { stop('动效设置更改已暂停，累计计时保留。'); manualReduce = reduceBox.checked; paint(); render(); }); root.append(h('label', {}, reduceBox, '减少动效（静态完整景观，无RAF/飘落粒子）'), h('p', {}, systemReduce ? '系统偏好减少动效，已强制尊重，不能在本页取消。' : '减少动效仍可开始1–5分钟静态休息计时；画面不持续刷新。'));
    root.append(h('div', {}, btn(s.running ? '暂停窗景与计时' : '开始所选休息', () => { if (s.running) { stop('已暂停，画面和累计播放时间保留。'); paint(); render(); } else start(); }, s.complete), btn('重新计时（保持暂停）', () => { stop(); session.reset(); message = '计时归零，保持暂停；需明确开始。'; paint(); render(); })), host);
    const files = window.toolbox?.files, capable = files?.saveBinarySupportsCopyOnly === true && typeof files.saveBinary === 'function'; root.append(btn('保存完整窗景 PNG 副本（暂停）', save, !capable || busy)); if (!capable) root.append(h('p', {}, '缺少安全二进制副本接口，请更新应用后保存。')); root.append(h('p', {}, '暂停、离开、页面隐藏不计入播放时长。回来保持暂停。更改季节/时段/动效会暂停并保留累计时间；改时长或重新计时归零。留影1000×700包含窗框和完整场景。切换具体功能会丢失未保存计时。'));
    if (busy) { const cancel = h('button', { type: 'button', disabled: nativePending }, '取消图片生成'), fn = () => { generation++; message = '已请求取消，忽略后续本地编码结果。'; render(); }; cancel.addEventListener('click', fn); bindings.push([cancel, 'click', fn]); root.append(cancel, h('p', {}, nativePending ? '原生另存处理中，请在对话框取消。' : '正在生成完整图片。')); for (const node of root.querySelectorAll('button,input,select')) if (node !== cancel) node.disabled = true; }
  }
  const visibility = () => { if (!alive || !document.hidden) return; generation++; stop('页面隐藏已暂停，返回需明确开始。'); if (active) render(); };
  const mediaChanged = event => { if (!alive) return; generation++; stop('系统动效偏好变化已暂停，返回需明确开始。'); systemReduce = event.matches === true; paint(); if (active) render(); };
  document.addEventListener('visibilitychange', visibility); if (media?.addEventListener) media.addEventListener('change', mediaChanged); else media?.addListener?.(mediaChanged);
  paint(); render(); return { activate() { if (!alive || active) return; active = true; message = '返回时保持暂停，请明确开始。'; render(); }, deactivate() { if (!alive) return; active = false; generation++; stop(); render(); }, destroy() { if (!alive) return; stop(); alive = false; generation++; scrub(); document.removeEventListener('visibilitychange', visibility); if (media?.removeEventListener) media.removeEventListener('change', mediaChanged); else media?.removeListener?.(mediaChanged); for (const url of urls) URL.revokeObjectURL(url); urls.clear(); host.innerHTML = ''; source = ''; status = null; session.destroy(); } };
} };
