export const TYPES=Object.freeze({contains:'包含',depends:'依赖',contrast:'对比'});
const clone=x=>JSON.parse(JSON.stringify(x)),bytes=s=>new TextEncoder().encode(s).length;
const scalar=s=>![...s].some(c=>c.codePointAt(0)>=0xd800&&c.codePointAt(0)<=0xdfff);
export async function sourceHash(source){if(typeof source!=='string'||!scalar(source))throw Error('原文含无效Unicode。');const digest=await globalThis.crypto.subtle.digest('SHA-256',new TextEncoder().encode(source));return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function example(){const source='A需要B。B需要A。',hash=await sourceHash(source);return{source,nodes:[{id:'A',label:'概念A'},{id:'B',label:'概念B'}],edges:[{id:'R1',from:'A',to:'B',type:'depends',anchor:{start:0,end:5,quote:'A需要B。',sourceHash:hash}},{id:'R2',from:'B',to:'A',type:'depends',anchor:{start:5,end:10,quote:'B需要A。',sourceHash:hash}}]};}
export function validate(draft){
 if(typeof draft?.source!=='string'||!scalar(draft.source)||bytes(draft.source)>4096)throw Error('教材片段须为有效Unicode，最多4096 UTF-8字节。');
 if(!Array.isArray(draft.nodes)||draft.nodes.length<1||draft.nodes.length>20)throw Error('请建立1–20个概念。');
 const ids=new Set();for(const n of draft.nodes){if(!n||typeof n.id!=='string'||!/^[A-Za-z][A-Za-z0-9_-]{0,11}$/.test(n.id)||ids.has(n.id))throw Error('概念ID须唯一，1–12位英文字母/数字/_/-且字母开头。');ids.add(n.id);if(typeof n.label!=='string'||!n.label.trim()||n.label.length>60||/[\x00-\x1f\x7f]/.test(n.label))throw Error('概念名称须为1–60字符单行文本。');}
 if(!Array.isArray(draft.edges)||draft.edges.length>60)throw Error('最多60条关系边。');const relations=new Set();
 for(const e of draft.edges){if(!e||typeof e.id!=='string'||!/^[A-Za-z][A-Za-z0-9_-]{0,15}$/.test(e.id)||relations.has(e.id))throw Error('关系ID须唯一，最多16位字母开头的字母/数字/_/-。');relations.add(e.id);if(!ids.has(e.from)||!ids.has(e.to)||!Object.hasOwn(TYPES,e.type))throw Error('关系端点或类型无效。');const a=e.anchor;if(a!==null&&(!a||!Number.isInteger(a.start)||!Number.isInteger(a.end)||a.start<0||a.end<=a.start||typeof a.quote!=='string'||!a.quote||bytes(a.quote)>4096||typeof a.sourceHash!=='string'||!/^[0-9a-f]{64}$/.test(a.sourceHash)))throw Error('原文锚点格式无效。');}
 return clone(draft);
}
export async function anchor(source,start,end){if(typeof source!=='string'||bytes(source)>4096||!Number.isInteger(start)||!Number.isInteger(end)||start<0||end<=start||end>source.length)throw Error('请在教材片段中选择非空原文。');return{start,end,quote:source.slice(start,end),sourceHash:await sourceHash(source)};}
function components(nodes,edges){
 const adj=new Map(nodes.map(n=>[n.id,[]]));edges.filter(e=>e.type==='depends').forEach(e=>adj.get(e.from).push(e.to));let index=0;const indices=new Map(),low=new Map(),stack=[],onStack=new Set(),result=[];
 function visit(v){indices.set(v,index);low.set(v,index++);stack.push(v);onStack.add(v);for(const w of adj.get(v)){if(!indices.has(w)){visit(w);low.set(v,Math.min(low.get(v),low.get(w)));}else if(onStack.has(w))low.set(v,Math.min(low.get(v),indices.get(w)));}if(low.get(v)===indices.get(v)){const group=[];let w;do{w=stack.pop();onStack.delete(w);group.push(w);}while(w!==v);if(group.length>1||adj.get(v).includes(v))result.push(group.sort());}}
 for(const n of nodes)if(!indices.has(n.id))visit(n.id);return result.sort((a,b)=>a[0].localeCompare(b[0])).map(group=>{const set=new Set(group),within=edges.filter(e=>e.type==='depends'&&set.has(e.from)&&set.has(e.to));let cycle=null;function walk(v,path){for(const w of adj.get(v)){if(!set.has(w))continue;const at=path.indexOf(w);if(at!==-1){cycle=[...path.slice(at),w];return true;}if(walk(w,[...path,w]))return true;}return false;}walk(group[0],[group[0]]);return{nodes:group,edgeIds:within.map(e=>e.id),exampleCycle:cycle};});
}
export async function audit(input){const draft=validate(input),hash=await sourceHash(draft.source),issues=[],seen=new Map(),edges=draft.edges.map(e=>{const a=e.anchor,valid=!!a&&a.sourceHash===hash&&a.end<=draft.source.length&&draft.source.slice(a.start,a.end)===a.quote;if(!valid)issues.push({kind:'anchor',edgeId:e.id,message:a?'原文已更改或区间不匹配；保留旧引用，需重新绑定。':'此边没有原文引用，请人工绑定。'});if(e.from===e.to)issues.push({kind:'self',edgeId:e.id,message:'关系指向自身，请核对建模。'});const ends=e.type==='contrast'?[e.from,e.to].sort():[e.from,e.to],key=JSON.stringify([e.type,...ends]);if(seen.has(key))issues.push({kind:'duplicate',edgeId:e.id,otherEdgeId:seen.get(key),message:'同类同端点重复关系；对比按无向关系检查。'});else seen.set(key,e.id);return{...e,anchorValid:valid};}),cycles=components(draft.nodes,draft.edges);cycles.forEach((c,i)=>issues.push({kind:'dependencyCycle',component:i+1,nodes:c.nodes,message:`依赖循环示例：${c.exampleCycle.join(' → ')}`}));return{feature:'L001',version:1,inputs:draft,sourceHash:hash,nodes:draft.nodes,edges,dependencyCycles:cycles,issues,policy:'依赖循环按强连通分组，每组给一条示例，不枚举所有简单环。包含边不参与依赖循环，对比按无向边。原文引用只证明选中了文本，不证明文本支持关系或概念正确。'};}
export function stored(draft){const value={feature:'L001',version:1,draft:validate(draft)};if(bytes(JSON.stringify(value))>65536)throw Error('草稿超过64KiB UTF-8，请删减或另存完整报告。');return value;}
export function restore(text){if(typeof text!=='string'||bytes(text)>65536)throw Error('恢复最多64KiB UTF-8。');const value=JSON.parse(text);if(value?.feature!=='L001'||value.version!==1)throw Error('仅支持L001版本1。');return validate(value.inputs||value.draft);}
const xml=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function svg(result){const size=900,mid=450,radius=310,positions=new Map(result.nodes.map((n,i)=>[n.id,{x:mid+radius*Math.cos(2*Math.PI*i/result.nodes.length-Math.PI/2),y:mid+radius*Math.sin(2*Math.PI*i/result.nodes.length-Math.PI/2)}]));const colors={contains:'#9cc5ff',depends:'#ffbc75',contrast:'#bfa6ed'};const paths=result.edges.map((e,i)=>{const a=positions.get(e.from),b=positions.get(e.to),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,bend=95+(i%3)*20,cx=(a.x+b.x)/2-dy/len*bend,cy=(a.y+b.y)/2+dx/len*bend;const path=e.from===e.to?`M ${a.x-25} ${a.y-8} C ${a.x-100} ${a.y-130},${a.x+100} ${a.y-130},${a.x+25} ${a.y-8}`:`M ${a.x+dx/len*48} ${a.y+dy/len*25} Q ${cx} ${cy} ${b.x-dx/len*58} ${b.y-dy/len*30}`;return`<g><path d="${path}" fill="none" stroke="${colors[e.type]}" stroke-width="2" ${e.type==='contrast'?'stroke-dasharray="8 4"':`marker-end="url(#arrow-${e.type})"`}/><text x="${e.from===e.to?a.x:(a.x+b.x)/4+cx/2}" y="${e.from===e.to?a.y-80:(a.y+b.y)/4+cy/2}" text-anchor="middle" fill="${colors[e.type]}" font-size="13">${xml(e.id)} ${TYPES[e.type]}${e.anchorValid?'':' · 引用失效'}</text></g>`;}).join('');const nodes=result.nodes.map(n=>{const p=positions.get(n.id),label=[...n.label].length>12?[...n.label].slice(0,12).join('')+'…':n.label;return`<g><rect x="${p.x-62}" y="${p.y-26}" width="124" height="52" rx="8" fill="#27332f" stroke="#9caea4"/><text x="${p.x}" y="${p.y-3}" text-anchor="middle" fill="#edf5ef" font-size="15">${xml(n.id)}</text><text x="${p.x}" y="${p.y+16}" text-anchor="middle" fill="#edf5ef" font-size="12">${xml(label)}</text></g>`;}).join('');return`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}"><rect width="900" height="900" fill="#16211f"/><defs>${['contains','depends'].map(type=>`<marker id="arrow-${type}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3z" fill="${colors[type]}"/></marker>`).join('')}</defs><text x="25" y="35" fill="#edf5ef" font-size="20">L001 手填概念关系 · 依赖循环${result.dependencyCycles.length}组</text>${paths}${nodes}<text x="25" y="875" fill="#b9c9bf" font-size="13">橙：有向依赖；蓝：有向包含；紫虚线：无向对比。完整引用和名称见JSON。</text></svg>`;}
