import { h } from '../../core/ui.js';
import { PLANTS, LIGHTS, STAGES, LIMITS, newPlant, advance, care, stage, archive, restore, plantSVG, pngBlob, pngPayload } from './model.mjs';

export default { id:'E034', create(root) {
  let state=newPlant(), alive=true, active=true, interval=null, busy=false, nativePending=false, generation=0, message='', draft='', selectedPlant='fern', confirmNew=false;
  let host, summary, historyHost; const bindings=[],urls=new Set();
  function stopTimer(){if(interval!==null)clearInterval(interval);interval=null;}
  function update(){const result=advance(state);state=result.state;if(result.rollback)message='本地时钟早于存档时间：经过时间按0处理，直到追上原时间，不重复计成长。';}
  function display(){if(!alive||!active)return;host.innerHTML=plantSVG(state);const svg=host.querySelector('svg');if(svg){svg.style.width='100%';svg.style.height='auto';svg.style.display='block';}summary.textContent=`${PLANTS[state.plant]} · ${STAGES[stage(state)]} · 水分${state.water.toFixed(1)}% · 有效成长${state.growthHours.toFixed(2)}小时 · ${LIGHTS[state.light]} · ${state.paused?'生长与水分已暂停':'按本地经过时间照看'}${Date.now()<state.updatedAt?' · 本地时钟早于存档时间，经过时间按0处理，等待追上原时间':''}`;historyHost.replaceChildren(h('p',{},`照看记录${state.history.length}条，旧记录滚动移除${state.droppedHistory}条（最多保留100条）`),h('ol',{},...state.history.map(item=>h('li',{},`${new Date(item.at).toISOString()} · ${{new:'新盆栽',water:'浇水',light:'换位',pause:'暂停',resume:'继续'}[item.action]} · 水分${item.water.toFixed(1)}% · 成长${item.growthHours.toFixed(2)}小时 · ${LIGHTS[item.light]} · ${item.paused?'暂停':'继续'}`))));}
  function arm(){stopTimer();if(alive&&active&&!document.hidden)interval=setInterval(()=>{if(busy)return;try{update();display();}catch(error){message=error.message;stopTimer();render();}},10000);}
  function on(node,type,fn){const guarded=async event=>{if(!alive||!active||busy)return;try{await fn(event);}catch(error){message=error.message||'操作失败';render();}};node.addEventListener(type,guarded);bindings.push([node,type,guarded]);return node;}
  const button=(label,fn,disabled=false)=>on(h('button',{type:'button',class:'btn',disabled},label),'click',fn);
  function select(label,values,value,fn){const node=h('select',{'aria-label':label},...Object.entries(values).map(([v,text])=>h('option',{value:v},text)));node.value=value;on(node,'change',()=>fn(node.value));return h('label',{},label+' ',node);}
  function scrub(){for(const[node,type,fn]of bindings.splice(0))node.removeEventListener(type,fn);root.replaceChildren();}
  function report(result){message=result?.canceled===true?'已取消另存':result?.ok===true?`已保存新副本：${result.path||''}`:`保存失败：${result?.error||'未返回成功结果'}${result?.partialPath?'；请人工核对：'+result.partialPath:''}`;}
  function check(token){if(!alive||!active||document.hidden||token!==generation)throw new DOMException('已取消本地生成','AbortError');}
  async function save(kind){const files=window.toolbox?.files, capability=kind==='json'?'saveText':'saveBinary';if(files?.[capability+'SupportsCopyOnly']!==true||typeof files[capability]!=='function')throw Error('缺少安全副本接口');update();display();busy=true;nativePending=false;stopTimer();const token=++generation;render();let image,url;
    try{let payload;if(kind==='json')payload={content:archive(state),extension:'json',defaultName:`plant-${state.plant}-archive-copy.json`,copyOnly:true};else{const svg=plantSVG(state);image=new Image();url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));urls.add(url);await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('植物SVG解码失败'));image.src=url;});check(token);const canvas=document.createElement('canvas');canvas.width=800;canvas.height=600;const context=canvas.getContext('2d');if(!context)throw Error('Canvas 2D不可用');context.drawImage(image,0,0,800,600);payload=await pngPayload(await pngBlob(canvas),`plant-${state.plant}-copy.png`);check(token);}nativePending=true;render();const result=await files[capability](payload);check(token);report(result);}catch(error){if(alive&&active)message=error.name==='AbortError'?'已取消本地生成，未提交的新结果已忽略':`保存失败：${error.message}`;}finally{if(image){image.onload=image.onerror=null;image.src='';}if(url){URL.revokeObjectURL(url);urls.delete(url);}busy=nativePending=false;if(alive&&active){update();render();arm();}}
  }
  async function importFile(file){if(!file)return;if(file.size>LIMITS.archiveBytes)throw Error('存档文件限64KiB');busy=true;const token=++generation;stopTimer();render();try{const bytes=await file.arrayBuffer();check(token);if(bytes.byteLength!==file.size)throw Error('文件大小发生变化');draft=new TextDecoder('utf-8',{fatal:true}).decode(bytes);restore(draft);message='文件已严格校验并放入草稿；点击恢复才替换当前盆栽。';}catch(error){if(alive&&active)message=error.name==='AbortError'?'已取消文件读取':`读取失败：${error.message}`;}finally{busy=false;if(alive&&active){render();arm();}}}
  function render(){if(!alive)return;scrub();root.append(h('h2',{},'小盆栽'),h('p',{},'离线桌面小游戏，规则不是植物科学模拟。水分每经过小时减2点；水分>0时，明亮窗边每小时成长1小时，散光0.5小时。24/48/72有效小时进入舒展/茂盛/成熟；成长封顶72小时，水分0不会死亡或倒退。'),h('p',{},'暂停冻结水分和成长，继续不会补算暂停时间。离开/隐藏不刷新，但未暂停时返回会一次计算经过时间（含离线时间）；没有动画。切换具体功能会销毁未保存盆栽，请先导出存档。'));
    if(!active){root.append(h('p',{},'界面刷新已停止，返回按保存的暂停规则计算。'));return;}if(message)root.append(h('p',{role:'status'},message));summary=h('p',{'aria-label':'盆栽状态'});host=h('div',{'aria-label':'完整盆栽景观',style:{maxWidth:'800px',width:'100%'}});historyHost=h('div',{'aria-label':'照看历史'});
    root.append(summary,h('div',{},button('浇水（+25，最多100）',()=>{const r=care(state,'water');state=r.state;message=r.rollback?'时间倒拨按0处理；浇水已记在存档时间':'已浇水，水分不超过100%。';render();}),select('光照位置',LIGHTS,state.light,value=>{state=care(state,'light',Date.now(),value).state;message='已换位，原位置经过时间先结算。';render();}),button(state.paused?'继续生长（不补暂停时间）':'暂停生长与水分',()=>{state=care(state,state.paused?'resume':'pause').state;message=state.paused?'已冻结水分和成长':'已继续，从此刻计算，不补暂停时间';render();}),button('刷新本地经过时间',()=>{update();display();})),host);
    const confirm=h('input',{type:'checkbox',checked:confirmNew,'aria-label':'确认替换当前盆栽'});on(confirm,'change',()=>{confirmNew=confirm.checked;});root.append(h('div',{},select('新盆栽种类',PLANTS,selectedPlant,value=>{selectedPlant=value;}),h('label',{},confirm,'确认放弃当前未保存盆栽和记录'),button('建立所选新盆栽',()=>{if(!confirmNew)throw Error('请先确认替换；建议先保存旧存档');state=newPlant(selectedPlant);confirmNew=false;message='已建立新盆栽，旧计时与记录已明确重置。';render();})));
    const input=h('textarea',{'aria-label':'存档JSON草稿',rows:6,maxLength:65536,style:{width:'100%'}});input.value=draft;on(input,'input',()=>{if(input.value.length>65536||new TextEncoder().encode(input.value).length>65536)throw Error('草稿限64KiB UTF-8，过大输入未保存');draft=input.value;});const file=h('input',{type:'file',accept:'.json,application/json','aria-label':'导入存档文件'});on(file,'change',()=>importFile(file.files?.[0]));root.append(h('h3',{},'存档恢复（版本1，UTF-8 ≤64KiB）'),input,file,button('恢复草稿（替换当前盆栽）',()=>{const candidate=restore(draft);state=advance(candidate).state;message='已恢复植物、暂停状态和照看记录；非暂停档按存档时间计算离线经过时间。';render();}),button('把当前状态放入草稿',()=>{update();draft=archive(state);message='当前有效状态已放入草稿，尚未写磁盘。';render();}));
    const files=window.toolbox?.files;root.append(button('保存存档JSON副本',()=>save('json'),files?.saveTextSupportsCopyOnly!==true||typeof files?.saveText!=='function'),button('保存完整盆栽PNG副本',()=>save('png'),files?.saveBinarySupportsCopyOnly!==true||typeof files?.saveBinary!=='function'),historyHost);display();
    if(busy){const cancel=h('button',{type:'button',disabled:nativePending},'取消本地生成/读取'),fn=()=>{generation++;message='已请求取消，忽略尚未提交的结果。';render();};cancel.addEventListener('click',fn);bindings.push([cancel,'click',fn]);root.append(cancel,h('p',{},nativePending?'原生另存处理中，请在对话框取消。':'正在处理本地文件/图片。'));for(const node of root.querySelectorAll('button,input,select,textarea'))if(node!==cancel)node.disabled=true;}
  }
  const visibility=()=>{if(!alive||!active)return;if(document.hidden){generation++;stopTimer();}else{update();render();arm();}};document.addEventListener('visibilitychange',visibility);render();
  return{activate(){if(!alive)return;active=true;update();render();arm();},deactivate(){if(!alive)return;active=false;generation++;stopTimer();render();},destroy(){if(!alive)return;alive=false;active=false;generation++;stopTimer();document.removeEventListener('visibilitychange',visibility);scrub();for(const url of urls)URL.revokeObjectURL(url);urls.clear();state=null;draft='';host=summary=historyHost=null;}};
} };
