'use strict';
const http=require('node:http');const https=require('node:https');const tls=require('node:tls');const net=require('node:net');const{domainToASCII}=require('node:url');const{performance}=require('node:perf_hooks');
const LIMITS=Object.freeze({urls:4,allowedHosts:8,redirects:5,urlBytes:2048,headerBytes:16384,headerCount:128,observedSocketBytes:65536,requestMs:5000,batchMs:30000,senders:32,jobs:128});
class ChainError extends Error{constructor(code){super(code);this.code=code;}}
const fail=code=>{throw new ChainError(code)};const codeOf=e=>typeof e?.code==='string'&&/^[A-Za-z0-9_]{1,80}$/.test(e.code)?e.code:'REQUEST_ERROR';
function object(p,keys){if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).some(k=>!keys.includes(k)))fail('invalid_payload');}
function normalizeHost(raw){if(typeof raw!=='string'||!raw.length||raw.length>253||/[\x00-\x20\x7f\\/@?#%]/.test(raw))fail('invalid_host');let host=raw;if(raw.startsWith('[')){if(!raw.endsWith(']')||net.isIP(raw.slice(1,-1))!==6)fail('invalid_host');host=raw.slice(1,-1);}const family=net.isIP(host);if(family===6)host=new URL('http://['+host+']/').hostname.slice(1,-1);else if(!family){if(/^[0-9.]+$/.test(host)||host.includes(':'))fail('invalid_host');host=domainToASCII(host).toLowerCase();if(!host||host.length>253||!/^[a-z0-9.-]+$/.test(host)||host.split('.').some(s=>!s||s.length>63||s.startsWith('-')||s.endsWith('-'))||(host!=='localhost'&&!host.includes('.')))fail('invalid_host');}if(host==='0.0.0.0'||host==='::'||host==='255.255.255.255'||(family===4&&Number(host.split('.')[0])>=224)||(family===6&&/^ff/i.test(host)))fail('invalid_host');return host;}
function parseURL(raw,base){if(typeof raw!=='string'||!raw.length||Buffer.byteLength(raw)>LIMITS.urlBytes||/[\x00-\x20\x7f\\]/.test(raw))fail('invalid_url');let u;try{u=new URL(raw,base);}catch{fail('invalid_url');}if(!['http:','https:'].includes(u.protocol))fail('unsupported_protocol');if(u.username||u.password)fail('url_credentials');const host=normalizeHost(u.hostname);const fragmentRemoved=u.href.includes('#');u.hash='';if(Buffer.byteLength(u.href)>LIMITS.urlBytes)fail('url_limit');return{url:u.href,host,port:Number(u.port||(u.protocol==='https:'?443:80)),protocol:u.protocol,origin:u.origin,fragmentRemoved};}
function plan(p){object(p,['urls','allowedHosts','maxRedirects','method']);if(!Array.isArray(p.urls)||!p.urls.length||p.urls.length>LIMITS.urls||!Array.isArray(p.allowedHosts)||!p.allowedHosts.length||p.allowedHosts.length>LIMITS.allowedHosts||!Number.isSafeInteger(p.maxRedirects)||p.maxRedirects<0||p.maxRedirects>LIMITS.redirects||!['GET','HEAD'].includes(p.method))fail('input_limit');const allowedHosts=p.allowedHosts.map(normalizeHost);if(new Set(allowedHosts).size!==allowedHosts.length)fail('duplicate_host');const targets=p.urls.map(url=>parseURL(url));if(new Set(targets.map(u=>u.url)).size!==targets.length)fail('duplicate_url');if(targets.some(t=>!allowedHosts.includes(t.host)))fail('initial_host_not_allowed');return{urls:targets.map(t=>t.url),targets,allowedHosts,method:p.method,maxRedirects:p.maxRedirects,maxRequestsPerChain:p.maxRedirects+1,maxRequests:targets.length*(p.maxRedirects+1),requestTimeoutMs:LIMITS.requestMs,batchTimeoutMs:LIMITS.batchMs,responseHeaderByteLimit:LIMITS.headerBytes,responseHeaderCountLimit:LIMITS.headerCount,observedSocketByteLimit:LIMITS.observedSocketBytes,concurrency:1,tlsValidation:'strict',retry:false,implicitProxy:false,downgradePolicy:'stop_before_HTTP',hostPolicy:'exact hostname/IP; no implicit subdomains; all ports on allowed host, origin changes recorded',requestHeaders:{Host:'per-hop URL.host','User-Agent':'AgentToolbox-T065/1',Accept:'*/*',Connection:'close'},warning:'确认后各起始URL独立串行检查，保持所选HEAD/GET，仅301/302/303/307/308 Location跳转；每跳一次，无重试或HEAD失败改GET。允许域名为精确主机/IP，无隐式子域；同一允许主机的其它端口可访问且记录跨origin。未允许下一目标及HTTPS→HTTP降级记录后停止，绝不请求。无登录/Cookie/认证/Referer/系统代理或设置修改；只观察有限响应头，不保留正文或其它头。HTTP起始URL使用明文，URL查询原样发送并进入报告，分享前核对。片段标准化删除不发送。'};}
function createHost(deps={}){
 const requestHTTP=deps.httpRequest||http.request;const requestHTTPS=deps.httpsRequest||https.request;const now=deps.now||(()=>performance.now());const wall=deps.wall||(()=>Date.now());const setTimer=deps.setTimer||setTimeout;const clearTimer=deps.clearTimer||clearTimeout;const senders=new Map();const stamp=()=>new Date(wall()).toISOString();
 function sender(ctx,create){const id=ctx?.senderId;if(!Number.isSafeInteger(id)||id<1)fail('invalid_sender');if(!senders.has(id)&&create){if(senders.size>=LIMITS.senders)fail('sender_limit');senders.set(id,{seen:new Set(),job:null});}return senders.get(id);}
 function jobId(id){if(typeof id!=='string'||!/^[A-Za-z0-9_-]{12,64}$/.test(id))fail('invalid_job_id');return id;}
 function stop(job,reason){if(job.reason)return;job.reason=reason;for(const abort of [...job.pending])abort();for(const req of job.requests){try{req.destroy();}catch{}}for(const socket of job.sockets){try{socket.destroy();}catch{}}}
 function requestOne(target,method,job){return new Promise((resolve,reject)=>{
  if(job.reason)return reject(new ChainError(job.reason));const u=new URL(target.url);let req;let res;let socket;let ended=false;let infoCount=0;const informational=[];let timer;
  const cleanup=()=>{clearTimer(timer);job.pending.delete(abort);if(req){req.removeListener('response',response);req.removeListener('error',error);req.removeListener('information',information);req.removeListener('upgrade',upgrade);job.requests.delete(req);}if(socket){socket.removeListener('data',budget);job.sockets.delete(socket);}try{res?.destroy();}catch{}try{req?.destroy();}catch{}try{socket?.destroy();}catch{}};
  const finish=(error,value)=>{if(ended)return;ended=true;cleanup();if(error)reject(error);else resolve(value);};const abort=()=>finish(new ChainError(job.reason||'ECANCELLED'));const error=e=>finish(e);const budget=()=>{if(!ended&&(socket?.bytesRead||0)>LIMITS.observedSocketBytes)finish(new ChainError('SOCKET_BYTE_LIMIT'));};
  const information=info=>{if(ended)return;if(++infoCount>3)return finish(new ChainError('INFORMATION_LIMIT'));informational.push(info.statusCode);};
  const upgrade=(_res,s,head)=>{s.on('error',()=>{});s.destroy();finish(new ChainError('HTTP_UPGRADE_UNSUPPORTED'));};
  const response=message=>{if(ended){message.on('error',()=>{});message.destroy();return;}res=message;res.on('error',()=>{});res.pause();try{if((socket?.bytesRead||0)>LIMITS.observedSocketBytes)fail('SOCKET_BYTE_LIMIT');if(!Array.isArray(res.rawHeaders)||res.rawHeaders.length%2||res.rawHeaders.length/2>LIMITS.headerCount)fail('HEADER_COUNT_LIMIT');let location=null;let locationCount=0;for(let i=0;i<res.rawHeaders.length;i+=2)if(String(res.rawHeaders[i]).toLowerCase()==='location'){locationCount++;location=res.rawHeaders[i+1];}if(!Number.isSafeInteger(res.statusCode)||res.statusCode<200||res.statusCode>599)fail('INVALID_HTTP_STATUS');const authorized=target.protocol==='https:'?res.socket?.authorized===true:null;if(target.protocol==='https:'&&!authorized)fail('TLS_NOT_AUTHORIZED');finish(null,{statusCode:res.statusCode,location,locationCount,informationalStatuses:informational,tls:{required:target.protocol==='https:',authorized,strictValidation:target.protocol==='https:'},socketBytesReadAtHeaders:socket?.bytesRead??null,otherHeadersRetained:false,bodyRetained:false});}catch(e){finish(e);}};
  job.pending.add(abort);timer=setTimer(()=>finish(new ChainError('REQUEST_TIMEOUT')),LIMITS.requestMs);
  try{const options={protocol:u.protocol,hostname:target.host,port:target.port,path:u.pathname+u.search,method,headers:{Host:u.host,'User-Agent':'AgentToolbox-T065/1',Accept:'*/*',Connection:'close'},agent:false,autoSelectFamily:false,maxHeaderSize:LIMITS.headerBytes,insecureHTTPParser:false,...(deps.lookup?{lookup:deps.lookup}:{}),...(u.protocol==='https:'?{rejectUnauthorized:true,minVersion:'TLSv1.2',maxVersion:'TLSv1.3',ALPNProtocols:['http/1.1'],servername:net.isIP(target.host)?'':target.host,checkServerIdentity:(_name,cert)=>tls.checkServerIdentity(target.host,cert),...(deps.ca?{ca:deps.ca}:{})}:{})};job.calls++;req=(u.protocol==='https:'?requestHTTPS:requestHTTP)(options);job.requests.add(req);req.maxHeadersCount=0;req.on('error',()=>{});req.once('error',error);req.once('response',response);req.on('information',information);req.once('upgrade',upgrade);req.once('socket',s=>{s.on('error',()=>{});if(ended){s.destroy();return;}socket=s;job.sockets.add(s);s.disableRenegotiation?.();s.on('data',budget);});req.end();}catch(e){finish(e);}
 });}
 async function run(p,ctx){object(p,['urls','allowedHosts','maxRedirects','method','jobId','confirmed']);if(p.confirmed!==true)fail('confirmation_required');const prepared=plan({urls:p.urls,allowedHosts:p.allowedHosts,maxRedirects:p.maxRedirects,method:p.method});const id=jobId(p.jobId);const state=sender(ctx,true);if(state.seen.has(id))fail('duplicate_job_id');if(state.job)fail('job_busy');if(state.seen.size>=LIMITS.jobs)fail('job_limit');const job={id,reason:null,pending:new Set(),requests:new Set(),sockets:new Set(),calls:0};state.seen.add(id);state.job=job;const started=now();const startedAtUTC=stamp();const chains=prepared.urls.map(startURL=>({startURL,status:'not_run',code:null,reason:null,finalRequestedURL:null,terminalURL:null,terminalStatusCode:null,stopTargetURL:null,redirectsFollowed:0,warnings:[],hops:[]}));const batchTimer=setTimer(()=>stop(job,'BATCH_TIMEOUT'),LIMITS.batchMs);
  try{for(const chain of chains){if(job.reason){chain.reason=job.reason;continue;}let current=parseURL(chain.startURL);const visited=new Set();while(true){if(job.reason){chain.status=job.reason==='ECANCELLED'?'canceled':'timed_out';chain.code=job.reason;break;}visited.add(current.url);const hop={index:chain.hops.length,url:current.url,method:prepared.method,startedAtUTC:stamp(),completedAtUTC:null,elapsedMs:null,statusCode:null,code:null,nextURL:null,redirect:null,warnings:[],tls:{required:current.protocol==='https:',authorized:null,strictValidation:current.protocol==='https:'},socketBytesReadAtHeaders:null,otherHeadersRetained:false,bodyRetained:false};chain.hops.push(hop);chain.finalRequestedURL=current.url;const begin=now();let observed;try{observed=await requestOne(current,prepared.method,job);hop.statusCode=observed.statusCode;hop.tls=observed.tls;hop.socketBytesReadAtHeaders=observed.socketBytesReadAtHeaders;hop.informationalStatuses=observed.informationalStatuses;}catch(e){hop.code=codeOf(e);chain.code=hop.code;chain.status=hop.code==='ECANCELLED'?'canceled':['REQUEST_TIMEOUT','BATCH_TIMEOUT'].includes(hop.code)?'timed_out':'request_error';break;}finally{hop.completedAtUTC=stamp();hop.elapsedMs=Math.max(0,Math.round(now()-begin));}
    if(![301,302,303,307,308].includes(observed.statusCode)){chain.status='terminal';chain.terminalURL=current.url;chain.terminalStatusCode=observed.statusCode;if(observed.statusCode>=400)hop.warnings.push('terminal_http_error');else if(observed.statusCode>=300&&observed.statusCode<400)hop.warnings.push('unsupported_redirect_status_not_followed');chain.warnings.push(...hop.warnings);break;}
    if(observed.locationCount!==1||typeof observed.location!=='string'||!observed.location){chain.status=observed.locationCount>1?'ambiguous_location':'missing_location';chain.code=observed.locationCount>1?'LOCATION_DUPLICATE':'LOCATION_MISSING';hop.code=chain.code;break;}
    let next;try{next=parseURL(observed.location,current.url);}catch(e){chain.status='invalid_location';chain.code=codeOf(e);hop.code=chain.code;hop.redirect={followed:false,locationRetained:false,rejected:true};break;}
    hop.nextURL=next.url;const crossHost=next.host!==current.host;const crossOrigin=next.origin!==current.origin;const downgrade=current.protocol==='https:'&&next.protocol==='http:';const allowed=prepared.allowedHosts.includes(next.host);const loop=visited.has(next.url);hop.redirect={crossHost,crossOrigin,downgrade,targetAllowed:allowed,fragmentRemoved:next.fragmentRemoved,loop,followed:false};if(crossHost)hop.warnings.push('cross_host');if(crossOrigin)hop.warnings.push('cross_origin');if(downgrade)hop.warnings.push('https_to_http_downgrade');if(!allowed)hop.warnings.push('target_not_allowed');if(loop)hop.warnings.push('redirect_loop');chain.warnings.push(...hop.warnings);
    let stopCode=null;if(downgrade)stopCode='HTTPS_DOWNGRADE_BLOCKED';else if(!allowed)stopCode='HOST_NOT_ALLOWED';else if(loop)stopCode='REDIRECT_LOOP';else if(chain.redirectsFollowed>=prepared.maxRedirects)stopCode='MAX_REDIRECTS';if(stopCode){chain.status=stopCode==='REDIRECT_LOOP'?'loop':stopCode==='MAX_REDIRECTS'?'limit':stopCode==='HOST_NOT_ALLOWED'?'domain_blocked':'downgrade_blocked';chain.code=stopCode;chain.stopTargetURL=next.url;hop.code=stopCode;break;}hop.redirect.followed=true;chain.redirectsFollowed++;current=next;
   }}
   return{ok:true,report:{format:'T065-redirect-chains',version:1,jobId:id,plan:prepared,startedAtUTC,completedAtUTC:stamp(),elapsedMs:Math.max(0,Math.round(now()-started)),canceled:job.reason==='ECANCELLED',batchTimedOut:job.reason==='BATCH_TIMEOUT',reason:job.reason,actualRequestCalls:job.calls,chains,scope:'Each input chain independently follows only permitted exact hosts and 301/302/303/307/308 Location responses using fixed HEAD/GET. Strict TLS, no auth/cookie/session/referer/system proxy/retry/GET fallback. HTTPS-to-HTTP and unpermitted next host stop before request. Fragment removed, URL queries preserved. Final requested URL is distinct from terminal URL and unrequested stop target. Body/other response headers not retained; GET may deliver bytes in initial buffers, socket byte property is observed at header completion, not a bandwidth or total-server-transfer claim. Pending OS DNS cannot be terminated but request/socket destroy and late callback suppression prevent continuation.'}};
  }finally{clearTimer(batchTimer);stop(job,job.reason||'JOB_FINISHED');if(state.job===job)state.job=null;}
 }
 async function invoke(operation,p,ctx){try{sender(ctx,false);if(operation==='plan')return{ok:true,plan:plan(p)};if(operation==='run')return await run(p,ctx);return{ok:false,code:'unsupported_operation',error:'只支持 plan/run。'};}catch(e){return{ok:false,code:codeOf(e),error:'请求被拒绝或失败；无重试或内部异常回显。'};}}
 async function cancel(id,ctx){try{jobId(id);const state=sender(ctx,false);if(!state?.job||state.job.id!==id)return{ok:true,canceled:false,jobId:id};stop(state.job,'ECANCELLED');return{ok:true,canceled:state.job.reason==='ECANCELLED',jobId:id};}catch(e){return{ok:false,code:codeOf(e),error:'取消请求失败。'};}}
 function disposeSender(id){const state=senders.get(id);if(state?.job)stop(state.job,'ECANCELLED');senders.delete(id);}
 return{invoke,cancel,disposeSender};
}
const host=createHost();module.exports={...host,createHost,plan,parseURL,normalizeHost,LIMITS};
