import { h } from '../../core/ui.js';
import { ChainError, inputPayload, reportText, statusLabel } from './model.mjs';

export default {
  id: 'T065',
  create(root) {
    let active = false; let destroyed = false; let generation = 0; let busy = false; let plan = null; let report = null; let preview = null; let runningJob = null; let cancelRequested = false;
    const status = h('p', { role: 'status', 'aria-live': 'polite' });
    const urlsInput = h('textarea', { rows: '4', maxlength: '8192', 'aria-label': '起始 URL 清单', placeholder: '每行一个 http:// 或 https:// URL', oninput: edited });
    const hostsInput = h('textarea', { rows: '4', maxlength: '2048', 'aria-label': '精确允许主机清单', placeholder: '每行一个精确主机/IP，不带协议或端口\nexample.test', oninput: edited });
    const maxInput = h('input', { type: 'text', inputmode: 'numeric', maxlength: '1', 'aria-label': '最大重定向次数', oninput: edited }); maxInput.value = '3';
    const methodInput = h('select', { 'aria-label': '请求方法', onchange: edited }, h('option', { value: 'HEAD' }, 'HEAD'), h('option', { value: 'GET' }, 'GET')); methodInput.value = 'HEAD';
    const prepare = button('校验输入并展示跳转计划', preparePlan); const cancel = button('取消当前任务', cancelTask);
    const planHost = h('section', {}); const resultHost = h('section', {}); const previewHost = h('section', {});
    root.append(h('link', { rel: 'stylesheet', href: new URL('./style.css', import.meta.url).href }), h('section', { class: 'feature-t065', 'aria-label': '网址跳转链验收' }, h('h2', {}, '网址跳转链验收'),
      h('p', {}, '核对服务器 Location 跳转链、循环、跨域和 HTTPS 降级。先列出起始 URL、精确允许范围与次数，确认后才发请求。'),
      h('p', { class: 't065-rule' }, '未允许的下一主机和 HTTPS→HTTP 降级绝不请求；允许范围不自动包含子域，同一主机其它端口可访问并记录跨 origin。严格 TLS，无登录/Cookie/认证/Referer/系统代理，无重试或 HEAD 失败改 GET。HTTP 起始请求是明文；URL 查询将发送并进入报告，分享前核对。'),
      h('div', { class: 't065-inputs' }, field('起始 URL（1–4 行，仅 HTTP / HTTPS，无账号密码）', urlsInput), field('精确允许主机/IP（1–8 行，须包含所有起始主机）', hostsInput), field('最多重定向次数（0–5，初始请求另算一次）', maxInput), field('固定方法', methodInput)),
      actions(prepare, cancel, button('填入本机示例（不连接）', example), button('清除输入和报告', clear)), status, planHost, resultHost, previewHost,
      h('p', { class: 't065-muted' }, '各 URL 独立串行，最多 24 次请求、并发 1，每请求含 DNS/TCP/TLS/响应头等待最多 5 秒、整批 30 秒。每次头≤16 KiB / 128 项，观察 socket.bytesRead≤64 KiB；收到头即销毁，不读取/保留正文或其它响应头。GET 可能先收到缓冲中的字节，这不是总下载量承诺。只测 301/302/303/307/308 Location；不执行网页 JavaScript/meta refresh、不用浏览器登录状态，不测完整页面加载或浏览器信任。片段标准化删除；缓存与系统 DNS 路径未知。输入/结果仅当前内存，每窗口最多 128 次任务。')));
    update();
    function button(label, fn) { return h('button', { type: 'button', onclick: event => { if (!active || destroyed || document.hidden || event.detail > 1) return; fn(); } }, label); }
    function field(label, input) { return h('label', {}, h('span', {}, label), input); }
    function actions(...nodes) { return h('div', { class: 't065-actions' }, nodes); }
    function message(text) { if (!destroyed) status.textContent = text; }
    function host() { const api = window.toolbox?.features; if (api?.callHostSupported !== true || typeof api.callHost !== 'function' || typeof api.cancelHost !== 'function') throw new ChainError('host_unavailable', '宿主缺少可信功能后端接口，已阻止请求。'); return api; }
    function cancelHost() { if (!runningJob) return; try { Promise.resolve(host().cancelHost('T065', runningJob)).catch(() => {}); } catch {} }
    function invalidate() { generation++; plan = null; report = null; preview = null; planHost.replaceChildren(); resultHost.replaceChildren(); previewHost.replaceChildren(); }
    function edited() { if (!active || destroyed) return; cancelHost(); invalidate(); message('输入已改变，旧允许范围、计划、报告与预览已废弃，请重新检查。'); }
    function update() { if (destroyed) return; urlsInput.disabled = hostsInput.disabled = maxInput.disabled = methodInput.disabled = prepare.disabled = !active || busy; cancel.disabled = !active || !busy || cancelRequested; }
    async function task(fn) { if (busy) return; const owner = ++generation; busy = true; cancelRequested = false; update(); const options = { isCanceled: () => destroyed || !active || document.hidden || owner !== generation }; try { await fn(options); } catch (error) { if (!options.isCanceled()) message(error instanceof ChainError ? `${error.code}：${error.message}` : '宿主处理或保存失败；无重试或内部异常回显。'); } finally { runningJob = null; if (!destroyed) { busy = false; cancelRequested = false; update(); } } }
    function requireResult(result, key) { if (result?.ok !== true || !result[key]) throw new ChainError(typeof result?.code === 'string' && /^[a-z_]{1,40}$/.test(result.code) ? result.code : 'host_result', '宿主拒绝或未完成请求；检查输入、确认状态和任务上限。'); return result[key]; }
    async function preparePlan() { if (busy) return; invalidate(); await task(async options => { const payload = inputPayload(urlsInput.value, hostsInput.value, maxInput.value, methodInput.value); const next = requireResult(await host().callHost('T065', 'plan', payload), 'plan'); if (options.isCanceled()) return; plan = next; renderPlan(); message('跳转计划已准备，尚未请求。核对 URL、允许主机、端口范围、方法与次数后另行确认。'); }); }
    function renderPlan() { planHost.replaceChildren(); if (!plan) return; const expected = plan; planHost.append(h('h3', {}, '待确认：目标与有限请求次数'), h('ol', {}, ...plan.targets.map(t => h('li', {}, `${t.url} · 端口 ${t.port}${t.protocol === 'http:' ? ' · HTTP 明文' : ' · 严格 HTTPS'}${t.fragmentRemoved ? ' · 已删除片段' : ''}`))), h('p', {}, `精确允许：${plan.allowedHosts.join(' / ')}；方法 ${plan.method}；每链最多重定向 ${plan.maxRedirects} 次 / 请求 ${plan.maxRequestsPerChain} 次；整批最多 ${plan.maxRequests} 次请求 / 并发 1。每请求 ${plan.requestTimeoutMs} ms / 整批 ${plan.batchTimeoutMs} ms。`), h('pre', {}, `固定请求头模板（每跳 Host 按对应 URL）：\n${JSON.stringify(plan.requestHeaders, null, 2)}`), h('p', {}, plan.warning), button('确认允许范围，运行有限跳转链', () => run(expected))); }
    async function run(expected) { if (busy || plan !== expected) return; report = null; preview = null; planHost.replaceChildren(); resultHost.replaceChildren(); previewHost.replaceChildren(); plan = null; await task(async options => { const api = host(); if (typeof globalThis.crypto?.randomUUID !== 'function') throw new ChainError('random_unavailable', '宿主缺少随机任务 ID 能力，已阻止请求。'); const id = globalThis.crypto.randomUUID(); runningJob = id; message(`任务 ${id}：最多 ${expected.maxRequests} 次 ${expected.method}，只在明确允许范围内串行；不登录或重试。`); const response = await api.callHost('T065', 'run', { urls: expected.urls, allowedHosts: expected.allowedHosts, maxRedirects: expected.maxRedirects, method: expected.method, jobId: id, confirmed: true }); if (options.isCanceled()) return; report = requireResult(response, 'report'); renderResults(); message(`链检查结束${report.canceled ? '（已取消）' : report.batchTimedOut ? '（整批超时）' : ''}：${report.chains.map(c => statusLabel(c.status)).join('；')}；实际请求 ${report.actualRequestCalls} 次。收到终点响应不代表业务成功。`); }); }
    async function cancelTask() { if (!busy || cancelRequested) return; if (!runningJob) { generation++; message('当前计划或保存等待已取消；已实际保存的副本无法撤回。'); return; } const owner = generation; const id = runningJob; cancelRequested = true; update(); message(`正在取消任务 ${id}，停止后续跳转并销毁请求/连接。`); try { const response = await host().cancelHost('T065', id); if (destroyed || !active || owner !== generation || runningJob !== id) return; if (response?.ok !== true) message('取消尚未确认，等待原请求有限期限，不重试。'); else if (response.canceled !== true) message('原任务已结束或不存在，以返回结果为准。'); } catch { if (!destroyed && active && owner === generation && runningJob === id) message('取消请求失败，等待原请求期限，不重试。'); } }
    function renderResults() { resultHost.replaceChildren(); if (!report) return; resultHost.append(h('h3', {}, '完整逐链结果'), h('p', {}, `开始 UTC ${report.startedAtUTC}；结束 UTC ${report.completedAtUTC}；耗时 ${report.elapsedMs} ms；实际请求 ${report.actualRequestCalls} 次。`), ...report.chains.map(c => h('section', { class: 't065-chain' }, h('h4', {}, `${statusLabel(c.status)} · ${c.code ?? c.reason ?? '—'}`), h('p', {}, `起始 ${c.startURL}`), h('p', {}, `最后已请求：${c.finalRequestedURL ?? '无'}；终点：${c.terminalURL ?? '未取得终点'}${c.terminalStatusCode !== null ? ' / HTTP ' + c.terminalStatusCode : ''}。`), h('p', {}, `未请求停止目标：${c.stopTargetURL ?? '无'}；已跟随重定向 ${c.redirectsFollowed}；警告 ${c.warnings.join(' / ') || '无'}。`), h('div', { class: 't065-table' }, h('table', {}, h('thead', {}, h('tr', {}, ...['请求索引', 'URL / 方法', 'HTTP / code', 'ms / UTC 开始', '下一 URL', '跳转标记 / 警告'].map(v => h('th', { scope: 'col' }, v)))), h('tbody', {}, ...c.hops.map(s => h('tr', {}, h('td', {}, s.index), h('td', {}, `${s.url}\n${s.method}`), h('td', {}, `${s.statusCode ?? '未收到'} / ${s.code ?? '—'}`), h('td', {}, `${s.elapsedMs ?? '未测'} ms\n${s.startedAtUTC}`), h('td', {}, s.nextURL ?? '无 / 已拒绝无效值'), h('td', {}, `${s.redirect ? JSON.stringify(s.redirect) : '无'}\n${s.warnings.join(' / ')}`)))))))), h('p', {}, report.scope), actions(button('预览完整 JSON 报告', () => previewReport('json')), button('预览完整 MD 报告', () => previewReport('md')))); }
    function previewReport(extension) { if (!report || busy) return; previewHost.replaceChildren(); preview = null; generation++; try { preview = { content: reportText(report, extension), extension, defaultName: `T065-redirect-chains.${extension}` }; const expected = preview; const text = h('textarea', { rows: '14', readonly: true, 'aria-label': '完整跳转链报告预览' }); text.value = preview.content; previewHost.append(h('h3', {}, '完整报告与目标新文件'), h('p', {}, `拟创建 ${preview.defaultName}；URL/查询及跳转范围进入报告，分享前核对。没有正文或其它响应头；无效含凭据 Location 不回显。已有文件不能覆盖，保存路径另行确认。`), text, button('保存已预览报告新副本', () => save(expected))); } catch (error) { message(error instanceof ChainError ? error.message : '完整报告预览失败，没有部分导出。'); } }
    async function save(expected) { if (busy || preview !== expected) return; const api = window.toolbox?.files; if (api?.saveTextSupportsCopyOnly !== true || typeof api.saveText !== 'function') { message('宿主缺少副本保护接口，已阻止保存。'); return; } await task(async options => { const result = await api.saveText({ ...expected, copyOnly: true }); if (options.isCanceled() || preview !== expected) return; if (result?.ok === true) message('已保存完整跳转链报告新副本，未改变网络设置。'); else if (result?.canceled === true) message('已取消保存，完整预览保留。'); else message('保存失败，完整预览保留；已有文件不能覆盖。'); }); }
    function example() { if (busy) return; invalidate(); urlsInput.value = 'https://127.0.0.1:8443/start'; hostsInput.value = '127.0.0.1'; maxInput.value = '3'; methodInput.value = 'HEAD'; message('仅填入本机示例，未请求；需自己的有效 TLS 服务监听此端口并提供相应跳转。'); }
    function clear() { cancelHost(); urlsInput.value = ''; hostsInput.value = ''; maxInput.value = '3'; methodInput.value = 'HEAD'; invalidate(); message('输入、允许范围、计划和报告已清除，未写配置。'); }
    function hide() { if (document.hidden && !destroyed) { cancelHost(); generation++; message('面板隐藏，任务取消并销毁请求，晚结果忽略。'); } }
    document.addEventListener('visibilitychange', hide);
    return { activate() { if (destroyed) return; active = true; update(); }, deactivate() { if (destroyed) return; active = false; cancelHost(); generation++; update(); message('面板暂停，当前请求取消，没有自动运行。'); }, destroy() { if (destroyed) return; clear(); destroyed = true; active = false; generation++; document.removeEventListener('visibilitychange', hide); root.replaceChildren(); } };
  }
};
