import { h } from '../../core/ui.js';
import { MODEL_VERSION,example,derive,forestSvg,formatNumber,prepareStoredState,validateStoredState,reportMarkdown } from './model.mjs';
const KEY='features.L038.state';
export default {id:'L038',create(root,ctx={}){
  root.classList.add('feature-l038');let draft=example(),result=null,destroyed=false,exporting=false,initial='';try{const raw=ctx.config?.get(KEY);if(raw){const{schemaVersion,...inputs}=validateStoredState(raw);draft=inputs;initial='已恢复输入草稿，汇总和森林图需重新生成。';}}catch(error){initial=`草稿未恢复：${error.message}`;}
  const notice=h('div',{class:'l038-notice',role:'status','aria-live':'polite'},initial),storage=h('div',{class:'l038-notice',role:'status'}),editor=h('div'),output=h('div');
  function replace(node,...items){node.replaceChildren(...items.flat(Infinity).filter(item=>item!==null&&item!==undefined&&item!==false));}
  function message(text,error=false){if(!destroyed){notice.textContent=text;notice.classList.toggle('is-error',error);}}
  function persist(){if(!ctx.config?.set)return;let state;try{state=prepareStoredState(draft);}catch(error){if(!destroyed)storage.textContent=`${error.message}；当前输入未保存，关闭只能恢复较早草稿。未截断，请缩短或自行复制文本保留。`;return;}if(!destroyed)storage.textContent='';try{Promise.resolve(ctx.config.set(KEY,state)).catch(error=>message(`草稿保存失败：${error.message}`,true));}catch(error){message(`草稿保存失败：${error.message}`,true);}}
  function changed(){result=null;renderOutput();persist();message('输入已改变，旧汇总/森林图已清空，请重新计算。');}
  function field(label,value,limit,change){const input=h('input',{class:'field',type:'text',maxlength:String(limit),'aria-label':label,oninput:()=>{change(input.value);changed();}});input.value=value;return input;}
  function renderEditor(){replace(editor,h('label',{},h('strong',{},'效应单位/尺度（用户声明）'),field('效应单位/尺度',draft.unit,80,value=>draft.unit=value)),h('p',{},'仅固定共同效应模型，不选择模型。用户effect和已知SE须同一效应尺度；研究独立性、共同效应及SE正确性未验证。SE不等于SD；不自动转换比值或log。'),h('div',{class:'l038-scroll'},h('table',{},h('thead',{},h('tr',{},['行','研究标签','effect','SE（>0）','操作'].map(text=>h('th',{},text)))),h('tbody',{},draft.studies.map((row,index)=>h('tr',{},h('td',{},String(index+1)),h('td',{},field(`研究${index+1}标签`,row.label,80,value=>row.label=value)),h('td',{},field(`研究${index+1}effect`,row.effect,32,value=>row.effect=value)),h('td',{},field(`研究${index+1}SE`,row.se,32,value=>row.se=value)),h('td',{},h('button',{class:'btn','aria-label':`删除研究${index+1}`,disabled:draft.studies.length===1,onclick:()=>{draft.studies.splice(index,1);renderEditor();changed();}},'删除'))))))),h('p',{},'1–20项，标签/单位≤40 Unicode码点；effect为0或绝对值1e-150至10亿，SE为正数1e-150至10亿。十进制/科学计数法≤32字符，JS Number可能舍入；区间半宽舍入为0或刻度不可表示则整份拒绝。'),h('div',{class:'l038-actions'},h('button',{class:'btn',onclick:()=>{if(draft.studies.length>=20){message('最多20项研究，不扩容或截断。',true);return;}draft.studies.push({label:`研究${draft.studies.length+1}`,effect:'',se:''});renderEditor();changed();}},'添加研究'),h('button',{class:'btn',onclick:()=>{draft=example();result=null;renderEditor();renderOutput();persist();message('已载入1/3、SE1/1教学示例。');}},'载入50/50示例'),h('button',{class:'btn primary',onclick:run},'汇总并绘图')));}
  function run(){try{result=derive(draft);renderOutput();persist();message('已完整汇总并绘图；全部区间在轴内，没有判断显著性或模型适用。');}catch(error){result=null;renderOutput();message(`整份汇总失败：${error.message}。未生成部分结果或截断研究。`,true);}}
  function payload(){return{feature:'L038',schemaVersion:1,modelVersion:MODEL_VERSION,exportedAt:new Date().toISOString(),draft:JSON.parse(JSON.stringify(draft)),result};}
  function renderOutput(){const exports=h('div',{class:'l038-actions'},h('button',{class:'btn',onclick:()=>exportReport('json')},'导出完整 JSON'),h('button',{class:'btn',onclick:()=>exportReport('md')},'导出完整 Markdown'),h('button',{class:'btn',disabled:!result,onclick:()=>exportReport('svg')},'导出森林图 SVG'));if(!result){replace(output,h('p',{},'尚无有效汇总；合法容量草稿可导出，SVG需有效结果。'),exports);return;}const r=result;replace(output,h('section',{class:'l038-summary'},h('h3',{},`汇总effect = ${formatNumber(r.summary.mean)} · SE = ${formatNumber(r.summary.se)}`),h('p',{},`近似95%区间 [${formatNumber(r.summary.ci.low)}, ${formatNumber(r.summary.ci.high)}] = mean ± 1.96SE；不是覆盖保证。`)),h('ul',{},r.warnings.map(text=>h('li',{},text))),h('section',{class:'l038-card'},h('h3',{},'稳定逆方差中间项'),h('p',{},`minSE = ${String(r.scaling.scaleSE)}；相对权重 qi=(minSE/SEi)²，与1/SEi²成比例；sum(q)=${String(r.scaling.scaledWeightSum)}`),h('p',{},`归一化pi=qi/sum(q)；mean=sum(pi*effecti)；汇总SE=minSE/sqrt(sum(q))=${String(r.summary.se)}。未求极小SE平方的倒数。`)),h('div',{class:'l038-scroll'},h('table',{},h('thead',{},h('tr',{},['行','完整标签','原effect','原SE','相对逆方差q','归一化权重%','加权贡献','近似区间下/上'].map(text=>h('th',{},text)))),h('tbody',{},r.studies.map(row=>h('tr',{},[row.index+1,row.label,row.inputEffect,row.inputSE,row.relativeInverseVarianceWeight,row.weightPercent,row.weightedContribution,`${String(row.ci.low)} / ${String(row.ci.high)}`].map(value=>h('td',{},String(value)))))))),h('figure',{class:'l038-chart'},h('figcaption',{},'完整森林图（可横向滚动；无裁剪）'),h('img',{src:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(forestSvg(r))}`,alt:`${r.studies.length}项固定共同效应森林图，单位${r.unit}`}),h('p',{},'区间线、效应方块和汇总钻石按计算值定位，方块面积与权重成比例。图上标签最多14码点；完整名称在表/title/metadata。')),h('details',{},h('summary',{},'完整 JSON 预览'),h('pre',{class:'l038-preview'},JSON.stringify(payload(),null,2))),h('details',{},h('summary',{},'完整 Markdown 预览'),h('pre',{class:'l038-preview'},reportMarkdown(payload()))),exports);}
  async function exportReport(extension){if(exporting)return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message('当前基础层缺少防覆盖导出能力，请升级。',true);return;}try{prepareStoredState(draft);}catch(error){message(`整份导出拒绝：${error.message}；未截断，请缩短后重试。`,true);return;}if(extension==='svg'&&!result){message('SVG需要有效汇总，请先计算。',true);return;}exporting=true;try{const full=payload(),content=extension==='json'?JSON.stringify(full,null,2):extension==='md'?reportMarkdown(full):forestSvg(result),response=await files.saveText({content,extension,defaultName:`L038-fixed-effect.${extension}`,copyOnly:true});message(response?.ok===true?'已导出全部研究与汇总的新副本。':response?.canceled===true?'已取消导出，输入保留。':`导出失败：${response?.error||'未确认保存成功'}`,response?.ok!==true&&response?.canceled!==true);}catch(error){message(`导出失败：${error.message}`,true);}finally{exporting=false;}}
  root.replaceChildren(h('link',{rel:'stylesheet',href:new URL('./style.css',import.meta.url).href}),h('h2',{},'固定效应汇总演练'),h('p',{},'仅固定共同效应逆方差教学汇总；不验证假定，不作显著性或投稿建议。'),notice,storage,h('details',{},h('summary',{},'模型与保存范围'),h('p',{},'相对权重按最小SE缩放，再归一化；区间固定±1.96SE正态近似，不保证覆盖。轴自动包含全部研究/汇总区间且加5%留白；不裁剪、不做log自动转换。小SE区间若无法以不同Number端点表示会拒绝。'),h('p',{},'schemaVersion=1只存单位和原研究输入，整体UTF-8 JSON≤64KiB，无派生回填，恢复需重算。超限整份拒绝；切走保存、销毁清理，没有定时器、网络/AI或图像识别。报告/SVG保留全部20项及原输入。')),editor,output);renderEditor();renderOutput();return{activate(){},deactivate(){persist();},destroy(){if(destroyed)return;persist();destroyed=true;result=null;output.replaceChildren();root.replaceChildren();root.classList.remove('feature-l038');}};
}};
