import{h}from'../../core/ui.js';
import{TRACKS,COLORS,LIMITS,createProject,restore,parse,encode,timing,toggle,renderPCM,wav,playhead,markdown,drawScore}from'./model.mjs';
export default{id:'E012',create(root,ctx={}){
 const key='featureLab.E012.project';let project=createProject(),alive=true,active=false,fresh=false,invalid=false,saving=false,reading=false,exporting=false,nativePending=false,generation=0,exportJob=0,candidate=null,audio=null,source=null,timer=null,audioToken=0,startTime=0,starting=false,playing=false,message='点格编排；播放需明确点击，不自动发声。',saveMessage='尚无本地工程。';const listeners=[],buttons=[],controls=[],steps=[],offscreens=new Set();let status,storage,summary,score,file,confirmReset,confirmImport,confirmInvalid;
 try{const v=ctx.config?.get?.(key,null);if(v==null)fresh=true;else{project=restore(v);saveMessage='已恢复全部64步和音量，尚未播放。';}}catch(e){invalid=true;message='旧工程拒绝：'+e.message;saveMessage='旧档未覆盖，可确认清空或导入。';}
 const busy=()=>saving||reading||exporting,navigable=()=>alive&&active&&!document.hidden&&!busy()&&!invalid;
 const on=(n,t,f)=>{n.addEventListener(t,f);listeners.push([n,t,f]);};
 function cleanupDOM(){for(const[n,t,f]of listeners)n.removeEventListener(t,f);listeners.length=buttons.length=controls.length=steps.length=0;root.replaceChildren();}
 function update(){if(!alive)return;const disabled=!active||document.hidden||busy();for(const n of controls)n.disabled=disabled||invalid;for(const b of buttons)b.node.disabled=disabled||(invalid&&!['resetInvalid','import'].includes(b.kind))||(b.kind==='import'&&!candidate)||(b.kind==='play'&&(playing||starting))||(b.kind==='text'&&window.toolbox?.files?.saveTextSupportsCopyOnly!==true)||(b.kind==='binary'&&window.toolbox?.files?.saveBinarySupportsCopyOnly!==true);for(const s of steps){s.node.disabled=disabled||invalid;s.node.setAttribute('aria-pressed',String(project.tracks[s.t].steps[s.s]));s.node.style.background=project.tracks[s.t].steps[s.s]?COLORS[s.t]:'#e4e5df';s.node.style.color=project.tracks[s.t].steps[s.s]&&s.t!==3?'#ffffff':'#233f47';}confirmReset.disabled=confirmImport.disabled=confirmInvalid.disabled=disabled;const t=timing(project);summary.textContent=`${project.bpm} BPM · 开启${project.tracks.reduce((n,t)=>n+t.steps.filter(Boolean).length,0)}/64格 · ${t.frames}采样帧=${t.seconds.toFixed(5)}秒 · ${playing?'循环播放':starting?'音频启动中':'已停止'}`;status.textContent=message;storage.textContent=saveMessage;}
 function stop(text){audioToken++;starting=playing=false;if(timer!==null){clearInterval(timer);timer=null;}if(source){try{source.stop();source.disconnect();source.buffer=null;}catch{}source=null;}if(audio){const old=audio;audio=null;try{Promise.resolve(old.close()).catch(()=>{});}catch{}}for(const s of steps)s.node.style.outline='';if(text)message=text;if(alive)update();}
 function repaint(){const c=score.getContext('2d');if(c)drawScore(c,project);}
 function render(focus=null){cleanupDOM();function button(text,fn,kind){const n=h('button',{type:'button'},text);on(n,'click',fn);buttons.push({node:n,kind});return n;}function numeric(label,val,min,max,fn){const n=h('input',{type:'number',min,max,step:1,value:String(val),'aria-label':label});on(n,'change',()=>{if(!navigable())return;const v=n.value;if(!/^\d{1,10}$/.test(v)||Number(v)<min||Number(v)>max){message=label+'须'+min+'–'+max+'整数，原值未改。';n.value=String(val);update();return;}edit(()=>fn(Number(v)));});controls.push(n);return h('label',{},label+' ',n);}
 const grid=h('div',{'aria-label':'四轨16步编排'});for(let t=0;t<4;t++){const tr=project.tracks[t],row=h('div',{style:{padding:'10px 0',borderBottom:'1px solid #d5d8ce'}});const mute=h('input',{type:'checkbox','aria-label':TRACKS[t]+'静音'});mute.checked=tr.mute;on(mute,'change',()=>{if(navigable())edit(()=>{tr.mute=mute.checked;});});controls.push(mute);row.append(h('strong',{},TRACKS[t]),h('label',{},mute,' 静音'),numeric(TRACKS[t]+'音量%',tr.volume,0,100,v=>{project.tracks[t].volume=v;}));const cells=h('div',{style:{display:'grid',gridTemplateColumns:'repeat(16,minmax(28px,1fr))',gap:'3px',overflowX:'auto',marginTop:'8px'}});for(let s=0;s<16;s++){const n=h('button',{type:'button','aria-label':`${TRACKS[t]}第${s+1}步`,'aria-pressed':String(tr.steps[s]),style:{minWidth:'28px',height:'36px',border:s%4===0?'2px solid #233f47':'1px solid #abb3ad',borderRadius:'3px'}},String(s+1));on(n,'click',()=>{if(navigable())edit(()=>toggle(project,t,s),`${TRACKS[t]}第${s+1}步`);});on(n,'keydown',e=>{const delta={ArrowLeft:[0,-1],ArrowRight:[0,1],ArrowUp:[-1,0],ArrowDown:[1,0]}[e.key];if(!delta||!navigable())return;e.preventDefault();const nt=t+delta[0],ns=s+delta[1];if(nt>=0&&nt<4&&ns>=0&&ns<16)steps.find(x=>x.t===nt&&x.s===ns)?.node.focus();});steps.push({node:n,t,s});cells.append(n);}row.append(cells);grid.append(row);}
 file=h('input',{type:'file',accept:'.json,application/json','aria-label':'节奏工程JSON'});on(file,'change',()=>read(file.files?.[0]));controls.push(file);confirmReset=h('input',{type:'checkbox','aria-label':'确认清空节奏工程'});confirmImport=h('input',{type:'checkbox','aria-label':'确认替换全部节奏工程'});confirmInvalid=h('input',{type:'checkbox','aria-label':'确认清空无效节奏工程'});summary=h('p',{'aria-label':'节奏统计'});status=h('p',{role:'status','aria-label':'操作状态'});storage=h('p',{'aria-label':'节奏保存状态'});score=h('canvas',{'aria-label':'完整节奏图',style:{display:'block',width:'100%',height:'auto',maxWidth:'960px'}});
 root.append(h('section',{style:{maxWidth:'1040px',padding:'16px',margin:'0 auto',lineHeight:'1.6'}},h('h2',{},'鼓点编排'),h('p',{},'四轨合成 · 4/4一小节 · 16个十六分步。点开关或Tab后空格/Enter；方向键在格间移动，不绕边。不会调用麦克风或联网。'),h('div',{},numeric('速度BPM',project.bpm,40,240,v=>{project.bpm=v;}),numeric('摆动%',project.swing,0,50,v=>{project.swing=v;}),numeric('总音量%',project.volume,0,100,v=>{project.volume=v;})),h('p',{},'摆动按1起第2/4/6…步延后“原步长×百分比”，奇偶两步总时长不变；0%=等距，50%=3:1。修改任何开关/参数会立即停播，点击播放听新版本。建议先用低音量。'),grid,summary,h('div',{},button('播放循环鼓点',start,'play'),button('停止播放',()=>stop('已停止；再次播放从小节开头开始。'),'stop')),h('p',{},'试听与WAV使用同一44.1kHz单声道PCM16合成。固定种子使噪声音色可重现；静音轨完全不混音。尾音环绕到开头，表示循环稳定状态，并非带尾音的长录音。每轨固定÷4混合，最终±0.95限幅。'),score,storage,button('重试本地保存',()=>save(),'retry'),h('div',{},h('label',{},confirmReset,' 确认清空64步及参数'),button('新建空节奏',()=>{if(!navigable())return;if(!confirmReset.checked){message='请先确认，工程未改。';update();return;}edit(()=>{project=createProject();candidate=null;});},'reset')),invalid?h('div',{},h('label',{},confirmInvalid,' 确认清空无效旧档'),button('从空节奏开始',()=>{if(busy()||!active||!confirmInvalid.checked){message='请先确认清空旧档。';update();return;}invalid=false;project=createProject();generation++;save();},'resetInvalid')):null,h('h3',{},'完整工程与新副本'),h('p',{},'schema1工程≤64KiB，所有64步、四轨音量/静音、BPM、摆动、总音量和种子自动本地保存。恢复不会自动播放。导出冻结当前版本；修改、离开或隐藏使尚未调用原生保存的旧导出失效；已开始原生保存不能撤回。'),h('p',{},window.toolbox?.files?.saveTextSupportsCopyOnly===true&&window.toolbox?.files?.saveBinarySupportsCopyOnly===true?'副本均独占新建，已有路径拒绝。':'应用缺安全文本或二进制副本能力，请升级后导出。'),h('div',{},button('另存完整节奏JSON',()=>exportText('json'),'text'),button('另存完整节奏Markdown',()=>exportText('md'),'text'),button('另存一小节WAV',()=>exportBinary('wav'),'binary'),button('另存完整节奏PNG',()=>exportBinary('png'),'binary')),file,h('p',{'aria-label':'节奏导入预览'},candidate?`已校验4轨64步 · ${candidate.bpm} BPM · 摆动${candidate.swing}% · 尚未替换`:'选择≤64KiB严格UTF-8工程，先预览再确认。'),h('label',{},confirmImport,' 确认替换全部工程'),button('应用节奏工程',()=>{if(!alive||!active||document.hidden||busy()||!candidate)return;if(!confirmImport.checked){message='请先勾选确认替换。';update();return;}const next=candidate;candidate=null;invalid=false;edit(()=>{project=next;});},'import'),status));repaint();update();if(focus)steps.find(s=>s.node.getAttribute?.('aria-label')===focus)?.node.focus();}
 function edit(fn,focus){if(!alive||busy())return;stop();fn();restore(project);generation++;message='工程已修改，试听已停止。';save(focus);}
 async function save(focus){if(!alive||invalid||saving)return;const value=restore(project);saving=true;saveMessage='正在保存全部节奏…';render(focus);try{if(typeof ctx.config?.set!=='function')throw Error('本地配置不可用');await ctx.config.set(key,value);if(alive)saveMessage='完整工程已保存，重载继续但不自启播放。';}catch(e){if(alive)saveMessage='保存失败：'+e.message+'；当前临时保留，可重试或另存。';}finally{saving=false;if(alive){update();if(focus&&active&&!document.hidden)steps.find(s=>s.node.getAttribute?.('aria-label')===focus)?.node.focus();}}}
 async function start(){if(!navigable()||playing||starting)return;const token=++audioToken;let ac;starting=true;message='正在启动本地音频…';update();try{const Ctor=window.AudioContext||window.webkitAudioContext;if(!Ctor)throw Error('WebAudio不可用，可导出WAV');ac=new Ctor();audio=ac;await ac.resume();if(!alive||!active||document.hidden||token!==audioToken||audio!==ac)return;if(ac.state!=='running')throw Error('音频未运行，请再次点击播放');const rendered=renderPCM(project),buffer=ac.createBuffer(1,rendered.frames,LIMITS.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=rendered.pcm[i]/32768;const node=ac.createBufferSource();source=node;node.buffer=buffer;node.loop=true;node.loopStart=0;node.loopEnd=rendered.seconds;node.connect(ac.destination);startTime=ac.currentTime;node.start(startTime);starting=false;playing=true;message='循环试听中；更改参数或离开会立即停止。';timer=setInterval(()=>{if(!alive||!active||document.hidden||!playing||audio!==ac){stop('试听已停止。');return;}const current=playhead(project,ac.currentTime-startTime);for(const s of steps)s.node.style.outline=s.s===current?'3px solid #233f47':'';},60);update();}catch(e){if(alive&&token===audioToken)stop('试听失败：'+e.message);}finally{if(ac&&audio!==ac)try{await ac.close();}catch{}}}
 async function read(f){if(!f||!navigable())return;stop('已停止试听，正在校验工程。');const token=++generation;reading=true;candidate=null;update();try{if(f.size>LIMITS.bytes)throw Error('工程最多64KiB');const b=await f.arrayBuffer();if(!alive||token!==generation)return;if(b.byteLength>LIMITS.bytes)throw Error('实际工程超过64KiB');candidate=parse(new TextDecoder('utf-8',{fatal:true}).decode(b));message='完整工程校验通过，尚未替换。';}catch(e){if(alive&&token===generation)message='导入拒绝：'+e.message;}finally{if(alive&&token===generation){reading=false;render();}}}
 const response=r=>r?.ok===true?'已另存完整新副本。':r?.canceled?'已取消另存。':`另存失败：${r?.error||'未确认成功'}${r?.partialPath?'；请人工核对 '+r.partialPath:''}`;
 async function exportText(ext){if(!navigable())return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true)return;stop();const token=generation,job=++exportJob,value=restore(project);exporting=true;message='正在另存完整文本副本…';update();try{nativePending=true;const r=await files.saveText({copyOnly:true,extension:ext,defaultName:'drums-copy.'+ext,content:ext==='json'?encode(value):markdown(value)});if(alive&&token===generation)message=response(r);}catch(e){if(alive&&token===generation)message='另存失败：'+e.message;}finally{if(job===exportJob){nativePending=false;if(alive){exporting=false;update();}}}}
 async function exportBinary(kind){if(!navigable())return;const files=window.toolbox?.files;if(files?.saveBinarySupportsCopyOnly!==true)return;stop();const token=generation,job=++exportJob,value=restore(project);exporting=true;message='正在准备完整'+kind.toUpperCase()+'副本…';update();let canvas;try{let bytes;if(kind==='wav')bytes=wav(value).bytes;else{canvas=document.createElement('canvas');offscreens.add(canvas);const c=canvas.getContext('2d');if(!c)throw Error('Canvas不可用');drawScore(c,value);const blob=await new Promise((r,j)=>canvas.toBlob(v=>v?r(v):j(Error('PNG编码失败')),'image/png'));if(!alive||token!==generation)return;if(blob.size>LIMITS.binary)throw Error('PNG超过10MiB');bytes=new Uint8Array(await blob.arrayBuffer());}if(!alive||token!==generation)return;if(bytes.length>LIMITS.binary)throw Error('二进制超过10MiB');const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));if(!alive||token!==generation)return;let b='';for(let i=0;i<bytes.length;i+=8192)b+=String.fromCharCode(...bytes.subarray(i,i+8192));nativePending=true;const r=await files.saveBinary({copyOnly:true,defaultName:'drums-copy.'+kind,base64:btoa(b),sha256:[...hash].map(x=>x.toString(16).padStart(2,'0')).join('')});if(alive&&token===generation)message=response(r);}catch(e){if(alive&&token===generation)message='另存失败：'+e.message;}finally{if(canvas){canvas.width=canvas.height=0;offscreens.delete(canvas);}if(job===exportJob){nativePending=false;if(alive){exporting=false;update();}}}}
 function suspend(){stop('已离开/隐藏，返回不会自动播放。');generation++;reading=false;candidate=null;if(!nativePending){exporting=false;exportJob++;}update();}
 const visibility=()=>{if(document.hidden)suspend();else update();};document.addEventListener('visibilitychange',visibility);render();return{activate(){if(alive){active=true;if(fresh&&!invalid){fresh=false;save();}else update();}},deactivate(){if(alive){active=false;suspend();}},destroy(){if(!alive)return;stop();generation++;alive=active=false;document.removeEventListener('visibilitychange',visibility);score.width=score.height=0;for(const c of offscreens)c.width=c.height=0;offscreens.clear();cleanupDOM();project=candidate=null;}};
}};
