export const LIMITS=Object.freeze({bytes:65536,sampleRate:44100,binary:10485760});
export const TRACKS=Object.freeze(['底鼓','军鼓','踩镲','拍手']);
export const COLORS=Object.freeze(['#e4583f','#8672b3','#2b8a78','#d59d28']);
const exact=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join(',')!==[...keys].sort().join(','))throw Error('工程字段不完整或未知。');};
const integer=(n,a,b)=>Number.isSafeInteger(n)&&n>=a&&n<=b;
export function createProject(){return{schema:1,bpm:120,swing:0,volume:65,seed:27358,tracks:TRACKS.map(()=>({steps:Array(16).fill(false),volume:80,mute:false}))};}
export function restore(v){if(new TextEncoder().encode(JSON.stringify(v)).length>LIMITS.bytes)throw Error('工程超过64KiB，未截断。');exact(v,['schema','bpm','swing','volume','seed','tracks']);if(v.schema!==1||!integer(v.bpm,40,240)||!integer(v.swing,0,50)||!integer(v.volume,0,100)||!integer(v.seed,1,4294967295))throw Error('schema1，BPM40–240、摆动0–50%、音量0–100%、种子1–4294967295，均为整数。');if(!Array.isArray(v.tracks)||v.tracks.length!==4)throw Error('必须完整四轨。');for(const t of Array.from(v.tracks)){exact(t,['steps','volume','mute']);if(!integer(t.volume,0,100)||typeof t.mute!=='boolean'||!Array.isArray(t.steps)||t.steps.length!==16||Array.from(t.steps).some(x=>typeof x!=='boolean'))throw Error('每轨需16个布尔开关、整数音量与布尔静音。');}return JSON.parse(JSON.stringify(v));}
export function encode(v){return JSON.stringify(restore(v),null,2);}
// Bounded duplicate-key rejecting parser copied from own E011; no cross-feature runtime dependency.
export function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>LIMITS.bytes)throw Error('JSON最多64KiB。');let p=0;const ws=()=>{while(p<text.length&&/[ \t\r\n]/.test(text[p]))p++;};function string(){const start=p++;while(p<text.length){if(text[p]==='\\'){p+=2;continue;}if(text[p++]==='"')return JSON.parse(text.slice(start,p));}throw Error('字符串未闭合。');}function value(depth=0){if(depth>8)throw Error('JSON层级超限。');ws();if(text[p]==='"')return string();if(text[p]==='{'||text[p]==='['){const obj=text[p++]==='{',out=obj?Object.create(null):[],seen=new Set();ws();if(text[p]===(obj?'}':']')){p++;return out;}while(true){ws();let key;if(obj){if(text[p]!=='"')throw Error('键无效。');key=string();if(seen.has(key))throw Error('重复JSON键。');seen.add(key);ws();if(text[p++]!==':')throw Error('缺冒号。');}const v=value(depth+1);if(obj)out[key]=v;else out.push(v);ws();const c=text[p++];if(c===(obj?'}':']'))return out;if(c!==',')throw Error('JSON结构无效。');}}const t=text.slice(p).match(/^(?:null|true|false|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/)?.[0];if(!t)throw Error('JSON值无效。');p+=t.length;if(/^-?\d/.test(t)){if(!/^-?(?:0|[1-9]\d*)$/.test(t)||!Number.isSafeInteger(Number(t)))throw Error('只接受安全整数词法。');return Number(t);}return JSON.parse(t);}const v=value();ws();if(p!==text.length)throw Error('JSON尾部无效。');return restore(v);}
export function timing(v){restore(v);const ideal=240/v.bpm,frames=Math.round(240*LIMITS.sampleRate/v.bpm);return{idealSeconds:ideal,frames,seconds:frames/LIMITS.sampleRate,starts:Array.from({length:16},(_,s)=>Math.round(15*LIMITS.sampleRate*(100*s+(s%2?v.swing:0))/(100*v.bpm)))};}
export function toggle(v,t,s){if(!integer(t,0,3)||!integer(s,0,15))throw Error('音轨/步超界。');v.tracks[t].steps[s]=!v.tracks[t].steps[s];}
// Fixed procedural instruments. Noise is deterministic xorshift32; not random/fairness gameplay.
function drum(track,step,seed){const rate=LIMITS.sampleRate,duration=[.42,.24,.075,.22][track],n=Math.round(duration*rate),out=new Float64Array(n);let state=(seed^Math.imul(track+1,0x9e3779b9)^Math.imul(step+1,0x85ebca6b))>>>0,previous=0;
 for(let i=0;i<n;i++){state^=state<<13;state^=state>>>17;state^=state<<5;const noise=(state>>>0)/2147483648-1,high=(noise-previous)/2,t=i/rate;previous=noise;let x;
 if(track===0){const phase=2*Math.PI*(45*t+85*.035*(1-Math.exp(-t/.035)));x=.95*Math.sin(phase)*Math.exp(-t/ .105);}
 else if(track===1)x=(.75*high+.25*Math.sin(2*Math.PI*180*t))*Math.exp(-t/.06);
 else if(track===2)x=high*Math.exp(-t/.018);
 else{let envelope=0;for(const onset of[0,.012,.024])if(t>=onset)envelope+=Math.exp(-(t-onset)/.022);x=high*envelope/3;}
 const edge=Math.min(1,i/44,(n-1-i)/128);out[i]=x*Math.max(0,edge);
 }return out;
}
export function renderPCM(v){v=restore(v);const {frames,starts}=timing(v),mix=new Float64Array(frames);for(let t=0;t<4;t++){const track=v.tracks[t];if(track.mute||!track.volume||!v.volume)continue;const gain=track.volume/100*v.volume/100/4;for(let s=0;s<16;s++)if(track.steps[s]){const hit=drum(t,s,v.seed);for(let i=0;i<hit.length;i++)mix[(starts[s]+i)%frames]+=hit[i]*gain;}}
 const pcm=new Int16Array(frames);let clipped=0,peak=0;for(let i=0;i<frames;i++){if(Math.abs(mix[i])>.95)clipped++;const x=Math.max(-.95,Math.min(.95,mix[i]));pcm[i]=Math.round(x*(x<0?32768:32767));peak=Math.max(peak,Math.abs(pcm[i])/32768);}return{pcm,peak,clipped,...timing(v)};
}
export function wav(v){const audio=renderPCM(v),bytes=new Uint8Array(44+audio.pcm.length*2),d=new DataView(bytes.buffer),text=(at,s)=>{for(let i=0;i<s.length;i++)bytes[at+i]=s.charCodeAt(i);};text(0,'RIFF');d.setUint32(4,bytes.length-8,true);text(8,'WAVE');text(12,'fmt ');d.setUint32(16,16,true);d.setUint16(20,1,true);d.setUint16(22,1,true);d.setUint32(24,LIMITS.sampleRate,true);d.setUint32(28,LIMITS.sampleRate*2,true);d.setUint16(32,2,true);d.setUint16(34,16,true);text(36,'data');d.setUint32(40,audio.pcm.length*2,true);for(let i=0;i<audio.pcm.length;i++)d.setInt16(44+i*2,audio.pcm[i],true);return{bytes,audio};}
export function playhead(v,seconds){const {seconds:duration,starts}=timing(v),sample=Math.floor(((Math.max(0,seconds)%duration)*LIMITS.sampleRate));let s=0;for(let i=1;i<16;i++)if(starts[i]<=sample)s=i;return s;}
export function markdown(v){v=restore(v);const t=timing(v);return '# 鼓点工程\n\n'+`${v.bpm} BPM · 4/4 · 16个十六分步 · 摆动${v.swing}% · 总音量${v.volume}% · 种子${v.seed}。\n\n44.1kHz单声道PCM16，一小节${t.frames}帧=${t.seconds}秒（理想${t.idealSeconds}秒）。偶数0起步固定，奇数步延后步长×摆动百分比；尾音环绕到小节开头，表示循环稳定状态。静音轨完全不混音；固定每轨增益/4，不因静音重新归一化，最终±0.95限幅。\n\n`+'|音轨|步（1起）|开启|静音|音量%|起点采样帧|\n|---|---:|---|---|---:|---:|\n'+v.tracks.flatMap((tr,i)=>tr.steps.map((on,s)=>`|${TRACKS[i]}|${s+1}|${on?'开':'关'}|${tr.mute?'是':'否'}|${tr.volume}|${t.starts[s]}|`)).join('\n')+'\n\n## 可恢复源工程\n\n```json\n'+encode(v)+'\n```\n';}
export function drawScore(c,v){v=restore(v);const width=960,height=420;c.canvas.width=width;c.canvas.height=height;c.fillStyle='#faf7ef';c.fillRect(0,0,width,height);c.fillStyle='#233f47';c.font='bold 24px sans-serif';c.fillText('鼓点编排 · 16步 / 4轨',24,34);c.font='16px sans-serif';c.fillText(`${v.bpm} BPM · 摆动 ${v.swing}% · 总音量 ${v.volume}% · ${timing(v).seconds.toFixed(5)}秒 / 小节`,24,63);for(let s=0;s<16;s++){c.fillStyle='#233f47';c.fillText(String(s+1),174+s*46,90);}for(let t=0;t<4;t++){const tr=v.tracks[t];c.fillStyle='#233f47';c.fillText(TRACKS[t],24,120+t*64);c.font='12px sans-serif';c.fillText(`${tr.volume}%${tr.mute?' 静音':''}`,24,140+t*64);c.font='16px sans-serif';for(let s=0;s<16;s++){c.fillStyle=tr.steps[s]?(tr.mute?'#a8a7a1':COLORS[t]):'#e4e5df';c.fillRect(168+s*46,98+t*64,36,36);if(s%4===0){c.fillStyle='#233f47';c.fillRect(164+s*46,98+t*64,2,36);}}}c.fillStyle='#233f47';c.font='14px sans-serif';c.fillText('彩格=开启 · 灰色开启=静音 · 空白格=关闭 · 每四格一拍',24,380);c.fillText('程序合成，无外部音色/网络；此图完整保留四轨全部64步。',24,404);return{width,height};}
