export const MODEL_VERSION='L036-reachable-originals-v1';
const size=value=>new TextEncoder().encode(JSON.stringify(value)).length;
const clone=value=>JSON.parse(JSON.stringify(value));
export function example(){return{nodes:[{id:'A',label:'支持文献甲',original:false,upstream:'E',location:'教学虚构文献'},{id:'B',label:'支持文献乙',original:false,upstream:'E',location:'教学虚构文献'},{id:'C',label:'支持文献丙',original:false,upstream:'E',location:'教学虚构文献'},{id:'E',label:'同一原始实验（用户标记）',original:true,upstream:'',location:'教学自造来源，非真实论文'}],claims:[{id:'Q1',text:'虚构教学论断：三篇引用支持同一论断',supports:'A,B,C'}]};}
export function emptyDraft(){return{nodes:[{id:'S1',label:'',original:false,upstream:'',location:''}],claims:[{id:'Q1',text:'',supports:''}]};}
function text(value,limit,label){if(typeof value!=='string'||value.length>limit)throw new Error(`${label}须≤${limit}个UTF-16代码单元文本`);if(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(value)||/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(value))throw new Error(`${label}含控制符/孤立代理项`);return value;}
function identity(value,label){text(value,12,label);if(!/^[A-Za-z][A-Za-z0-9_-]{0,11}$/.test(value))throw new Error(`${label}须字母起始的1–12位ASCII字母/数字/_/-`);return value;}
export function validateDraft(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw)||size(raw)>65536)throw new Error('输入须对象且整体JSON≤64KiB UTF-8，整份拒绝不截断');if(!Array.isArray(raw.nodes)||raw.nodes.length<1||raw.nodes.length>40||!Array.isArray(raw.claims)||raw.claims.length<1||raw.claims.length>10)throw new Error('须1–40来源、1–10论断');return{nodes:raw.nodes.map((row,index)=>{if(!row||typeof row!=='object'||Array.isArray(row)||typeof row.original!=='boolean')throw new Error(`来源${index+1}类型无效`);return{id:text(row.id,12,'来源ID'),label:text(row.label,200,'来源标题'),original:row.original,upstream:text(row.upstream,1300,'上游ID列表'),location:text(row.location,300,'作者来源位置')};}),claims:raw.claims.map((row,index)=>{if(!row||typeof row!=='object'||Array.isArray(row))throw new Error(`论断${index+1}类型无效`);return{id:text(row.id,12,'论断ID'),text:text(row.text,1000,'论断文本'),supports:text(row.supports,260,'支持ID列表')};})};}
function list(raw,label,max){if(!raw.trim())return[];const ids=raw.split(',').map(id=>id.trim());if(ids.length>max||ids.some(id=>!id))throw new Error(`${label}须逗号分隔≤${max}个非空ID`);ids.forEach(id=>identity(id,label));return ids;}
export function derive(raw){const draft=validateDraft(raw),nodes=new Map(),claims=new Set();for(const row of draft.nodes){identity(row.id,'来源ID');if(nodes.has(row.id))throw new Error(`来源ID重复：${row.id}`);if(!row.label.trim())throw new Error(`来源${row.id}标题未填`);const upstream=list(row.upstream,`${row.id}上游`,40);if(new Set(upstream).size!==upstream.length)throw new Error(`${row.id}上游边重复`);if(row.original&&upstream.length)throw new Error(`原始来源${row.id}不能指向上游`);nodes.set(row.id,{...row,upstream});}
  const edges=[...nodes.values()].flatMap(row=>row.upstream.map(to=>({from:row.id,to})));if(edges.length>100)throw new Error('来源边数超过100，整份拒绝');for(const{from,to}of edges)if(!nodes.has(to))throw new Error(`${from}指向未知来源${to}`);
  const colors=new Map(),stack=[];function visit(id){if(colors.get(id)===1)throw new Error(`整个来源图含循环：${[...stack,id].join(' → ')}`);if(colors.get(id)===2)return;colors.set(id,1);stack.push(id);for(const next of nodes.get(id).upstream)visit(next);stack.pop();colors.set(id,2);}for(const id of nodes.keys())visit(id);
  const ordered=ids=>[...nodes.keys()].filter(id=>ids.has(id));
  function reach(support){const queue=[support],seen=new Set([support]),parent=new Map();for(let index=0;index<queue.length;index++){for(const next of nodes.get(queue[index]).upstream)if(!seen.has(next)){seen.add(next);parent.set(next,queue[index]);queue.push(next);}}const originals=ordered(new Set([...seen].filter(id=>nodes.get(id).original))),unknown=ordered(new Set([...seen].filter(id=>!nodes.get(id).original&&!nodes.get(id).upstream.length)));function witness(terminal){const path=[terminal];while(parent.has(path[0]))path.unshift(parent.get(path[0]));return path;}return{supportId:support,supportLabel:nodes.get(support).label,reachableIds:ordered(seen),originalIds:originals,unknownTerminalIds:unknown,witnesses:[...originals,...unknown].map(terminalId=>({terminalId,type:nodes.get(terminalId).original?'用户标记原始来源':'未知终点',path:witness(terminalId)}))};}
  const results=draft.claims.map(claim=>{identity(claim.id,'论断ID');if(claims.has(claim.id))throw new Error(`论断ID重复：${claim.id}`);claims.add(claim.id);if(!claim.text.trim())throw new Error(`论断${claim.id}文本未填`);const requested=list(claim.supports,`${claim.id}支持`,20),supportIds=[...new Set(requested)];if(!supportIds.length)throw new Error(`论断${claim.id}须至少一个支持来源`);for(const id of supportIds)if(!nodes.has(id))throw new Error(`论断${claim.id}支持未知来源${id}`);const supports=supportIds.map(reach),originalIds=ordered(new Set(supports.flatMap(row=>row.originalIds))),unknownTerminalIds=ordered(new Set(supports.flatMap(row=>row.unknownTerminalIds)));const groups=[...originalIds,...unknownTerminalIds].map(id=>({sourceId:id,label:nodes.get(id).label,type:nodes.get(id).original?'用户标记原始来源':'未知终点',supportIds:supports.filter(row=>row.reachableIds.includes(id)).map(row=>row.supportId)}));return{...claim,requestedSupportIds:requested,supportIds,supportCount:supportIds.length,duplicateSupportCount:requested.length-supportIds.length,originalSourceCount:originalIds.length,originalIds,unknownTerminalIds,unknownTerminalCount:unknownTerminalIds.length,supports,upstreamGroups:groups,sharedUpstreamGroups:groups.filter(group=>group.supportIds.length>1)};});
  return{modelVersion:MODEL_VERSION,nodes:clone([...nodes.values()]),edges,claims:results,boundaries:['可达原始来源数只按用户explicit original标记去重，不证明统计独立性或来源真实。','未标原始的终点是未知，不计入原始来源；“0个已标原始”不等于没有原始证据。','路径只给每个支持到各终点的一条BFS最短见证；完整可达集合和全图保留，不枚举指数数量的全部路径。','方向：支持/二手文献 → 上游来源；共享上游不自动证明因果，也不自动评价论断可信度。']};}
export function prepareStoredState(raw){const state={schemaVersion:1,...validateDraft(raw)};if(size(state)>65536)throw new Error('版本化草稿超过64KiB UTF-8');return state;}
export function validateStoredState(raw){if(size(raw)>65536)throw new Error('存储草稿超过64KiB UTF-8');if(raw?.schemaVersion!==1)throw new Error('草稿版本不支持');return prepareStoredState(raw);}
const escape=text=>String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function reportMarkdown(payload){const raw=escape(JSON.stringify(payload,null,2)),fence='`'.repeat(Math.max(3,...[...raw.matchAll(/`+/g)].map(match=>match[0].length+1))),lines=['# L036 引用来源独立性检查','人工来源图去重，不证明统计独立或真实来源。'];if(payload.result)for(const claim of payload.result.claims){lines.push(`## 论断 ${claim.id}`,`支持文献 ${claim.supportCount}；用户标记可达原始来源 ${claim.originalSourceCount}；未知终点 ${claim.unknownTerminalCount}；重复支持去除 ${claim.duplicateSupportCount}`,...claim.supports.flatMap(support=>support.witnesses.map(w=>`${support.supportId}：${w.type} ${w.path.join(' → ')}`)));}lines.push('## 完整论断、图、可达集合、分组和边界',`${fence}json\n${raw}\n${fence}`);return lines.join('\n\n');}
