import { h } from '../../core/ui.js';
import { LIMITS,exampleDraft,validateDraft,decodeSource,queryCorpus,origin,reportJson,reportMarkdown } from './model.mjs';
const KEY='features.L043.draft',channels=new WeakMap();
function channelFor(config){if(!config||typeof config!=='object'||typeof config.set!=='function')return null;if(!channels.has(config))channels.set(config,{pending:null,running:false,latest:null,owner:null,ticket:0});return channels.get(config);}
async function drain(config,channel){channel.running=true;try{while(channel.pending){const task=channel.pending;channel.pending=null;try{await config.set(KEY,task.value);if(!channel.pending&&channel.owner===task.owner&&channel.ticket===task.ticket)task.done();}catch(e){if(!channel.pending&&channel.owner===task.owner&&channel.ticket===task.ticket)task.done(e);}}}finally{channel.running=false;}}
export default{id:'L043',create(root,ctx={}){
  root.classList.add('feature-l043');let draft=exampleDraft(),sources=[],report=null,destroyed=false,active=true,busy=false,ticket=0,page=0,filter='',exporting=false;const channel=channelFor(ctx.config),owner={};if(channel)channel.owner=owner;
  const notice=h('div',{class:'l043-notice',role:'status','aria-live':'polite'}),storage=h('div',{class:'l043-notice'}),editor=h('div'),output=h('div'),reportHost=h('div');const replace=(node,...items)=>node.replaceChildren(...items.flat(Infinity).filter(x=>x!==null&&x!==undefined&&x!==false));
  function message(value,error=false){if(active&&!destroyed){notice.textContent=value;notice.classList.toggle('is-error',error);}}
  function persist(){if(!channel||channel.owner!==owner)return;const seq=++channel.ticket;let value;try{value=validateDraft(draft,{forStorage:true});}catch(e){storage.textContent=`草稿未保存：${e.message}；关闭只能恢复较早合法输入，源文件从不写配置。`;return;}channel.latest=value;channel.pending={value,owner,ticket:seq,done(e){if(destroyed)return;storage.textContent=e?`草稿保存未确认：${e.message}`:'仅≤64KiB的查询/粘贴输入草稿已保存；导入TXT、来源hash、索引和报告不写配置。';}};if(!channel.running)void drain(ctx.config,channel);}
  function invalidate(){ticket++;report=null;page=0;filter='';renderOutput();renderReport();persist();message('输入已改变，旧结果已失效；请重新构建完整查询。');}
  function field(label,value,max,change,rows,commit=true){const el=h(rows?'textarea':'input',{class:'field',type:rows?undefined:'text',rows:rows?String(rows):undefined,'aria-label':label,maxlength:String(max),oninput:()=>{change(el.value);if(commit)invalidate();}});el.value=value;return el;}
  function renderEditor(){const mode=h('select',{class:'field','aria-label':'语料输入模式',onchange:()=>{draft.mode=mode.value;invalidate();renderEditor();}},h('option',{value:'paste'},'粘贴/编辑TXT语料'),h('option',{value:'files'},'本地TXT文件（1–8份）'));mode.value=draft.mode;const checkbox=h('input',{type:'checkbox','aria-label':'大小写敏感',onchange:()=>{draft.caseSensitive=checkbox.checked;invalidate();}});checkbox.checked=draft.caseSensitive;const file=h('input',{class:'field',type:'file',accept:'.txt,text/plain',multiple:true,disabled:busy,'aria-label':'选择本地TXT语料',onchange:()=>loadFiles(file.files)});replace(editor,h('div',{class:'l043-query'},h('label',{},'语料输入',mode),h('label',{},'单个完整词元（不是正则）',field('查询关键词',draft.keyword,160,value=>draft.keyword=value)),h('label',{},'每侧窗口0–10词（不跨行）',field('窗口大小',draft.window,3,value=>draft.window=value)),h('label',{},checkbox,' 大小写敏感；关闭仅toLowerCase')),draft.mode==='paste'?h('section',{class:'l043-card'},h('label',{},'人工粘贴来源名（非磁盘来源声明）',field('粘贴来源名',draft.pasteName,240,value=>draft.pasteName=value)),h('label',{},'UTF-8语料正文（≤1MiB；大型输入不会写全局配置）',field('粘贴语料正文',draft.pasteText,1024*1024,value=>draft.pasteText=value,8))):h('section',{class:'l043-card'},h('label',{},'只读取原文件；所有文件一起校验后替换来源集合',file),sources.length?sources.map(s=>h('section',{class:'l043-source'},h('strong',{},`${s.id} · ${s.name}`),h('p',{},`${s.byteLength}字节 · UTF-8${s.bomRemovedForIndex?'（索引去BOM）':''} · SHA256 ${s.sha256}`),h('button',{class:'btn',disabled:busy,onclick:()=>{sources=sources.filter(item=>item!==s);invalidate();renderEditor();}},`移除${s.id}`),h('details',{},h('summary',{},'完整原文预览（只读）'),h('pre',{class:'l043-preview'},s.text)))):h('p',{},'尚未导入原文件；关闭后需重新选择来源。')),h('div',{class:'l043-actions'},h('button',{class:'btn primary',disabled:busy,onclick:run},'构建KWIC与频次'),h('button',{class:'btn',onclick:cancel},'取消当前读取/查询'),h('button',{class:'btn',onclick:()=>{draft=exampleDraft();invalidate();renderEditor();message('已装入两次take a look的可编辑文本示例；请构建，未自动查询。');}},'装入两行示例'),h('button',{class:'btn',onclick:()=>{draft={...exampleDraft(),pasteText:''};sources=[];invalidate();renderEditor();message('输入与来源已清空；零词语料可以构建零匹配报告。');}},'清空输入')));}
  async function loadFiles(fileList){if(!active||destroyed||busy)return;const files=Array.from(fileList??[]);if(!files.length)return;busy=true;const seq=++ticket;report=null;renderEditor();renderOutput();renderReport();const valid=()=>active&&!destroyed&&seq===ticket;message('正在逐份读取严格UTF-8与原字节SHA；不改写来源……');try{if(files.length>8||files.some(f=>!Number.isInteger(f.size)||f.size>LIMITS.fileBytes)||files.reduce((n,f)=>n+f.size,0)>LIMITS.totalBytes)throw Error('须1–8份、每份≤512KiB、合计≤1MiB；整组拒绝');const next=[];for(let i=0;i<files.length;i++){if(!valid())return;const bytes=await files[i].arrayBuffer();if(!valid())return;next.push(await decodeSource(bytes,files[i].name,`F${i+1}`));if(!valid())return;}sources=next;message('完整TXT来源集合已导入；原字节未改写，请构建索引。');}catch(e){if(valid())message(`导入整组拒绝：${e.message}；先前完整来源仍保留，未替换部分文件。`,true);}finally{busy=false;if(!destroyed)renderEditor();}}
  async function run(){if(busy||destroyed||!active)return;const seq=++ticket;busy=true;report=null;page=0;filter='';renderEditor();renderOutput();renderReport();message('正在完整索引/查询；循环有界让出，超限整份拒绝……');const valid=()=>active&&!destroyed&&ticket===seq;try{const snapshot=validateDraft(draft),items=snapshot.mode==='paste'?[await decodeSource(new TextEncoder().encode(snapshot.pasteText).buffer,snapshot.pasteName,'P1','paste')]:sources.map(s=>({...s}));if(!valid())return;const next=await queryCorpus(snapshot,items,{canceled:()=>!valid()});if(!valid())return;report=next;message(`完整查询完成：${report.totals.matches}个匹配，${report.totals.files}份来源；频次不自动推荐用法。`);}catch(e){if(valid())message(`未生成报告：${e.message}`,true);}finally{busy=false;if(!destroyed){renderEditor();renderOutput();renderReport();}}}
  function cancel(){if(!busy){message('当前没有读取/查询任务。');return;}ticket++;report=null;message('已请求取消，迟到结果无效；释放当前任务后可重新查询。');renderOutput();renderReport();}
  function visibleRows(){if(!report)return[];return report.matches.filter(m=>{if(!filter)return true;const {source,line}=origin(report,m);return`${source.id} ${source.name} ${line.text}`.toLowerCase().includes(filter.toLowerCase());});}
  function renderOutput(){if(!report){replace(output,h('p',{},busy?'当前没有完成报告；读取/查询中不会显示截断结果。':'还没有有效报告；输入改变后需要重新构建。'));return;}const filtered=visibleRows(),pages=Math.max(1,Math.ceil(filtered.length/25));page=Math.min(page,pages-1);const filterControl=field('出处显示过滤',filter,200,value=>{const focused=document.activeElement===filterControl,start=filterControl.selectionStart,end=filterControl.selectionEnd;filter=value;page=0;renderOutput();if(focused){const next=output.querySelector('[aria-label="出处显示过滤"]');next.focus();next.setSelectionRange(start,end);}},undefined,false),rows=filtered.slice(page*25,(page+1)*25);replace(output,h('section',{class:'l043-card'},h('h3',{},`完整结果 ${report.totals.matches}次 · ${report.totals.files}来源 · ${report.totals.lines}行 · ${report.totals.tokens}词`),h('p',{},`关键词「${report.query.keyword}」 · 每侧${report.query.windowTokensPerSide}词 · ${report.query.caseSensitive?'大小写敏感':'仅toLowerCase忽略大小写'}。原行保留完整出处，KWIC空白用单个空格显示。`),h('label',{},'按来源ID/名/原行文字过滤显示（不影响完整导出）',filterControl),h('div',{class:'l043-actions'},h('button',{class:'btn',disabled:page===0,onclick:()=>{page--;renderOutput();}},'上一页KWIC'),h('span',{},`页${page+1}/${pages} · 显示过滤后${filtered.length}/${report.totals.matches}次（每页25）`),h('button',{class:'btn',disabled:page+1>=pages,onclick:()=>{page++;renderOutput();}},'下一页KWIC')),rows.length?h('div',{class:'l043-kwic'},rows.map(m=>{const {source,line}=origin(report,m);return h('article',{class:'l043-match',dataset:{match:String(m.number)}},h('div',{class:'l043-window'},h('span',{class:'l043-left'},m.left.join(' ')||'（行首/窗口0）'),h('mark',{},m.keyword),h('span',{},m.right.join(' ')||'（行尾/窗口0）')),h('p',{class:'l043-location'},`#${m.number} · ${source.id} · ${source.name} · 第${m.lineNumber}行 · 第${m.tokenNumber}词 · UTF-16列${m.columnUtf16}`),h('div',{class:'l043-original'},h('strong',{},'原行/句子出处： '),line.text.slice(0,m.startUtf16),h('mark',{},line.text.slice(m.startUtf16,m.endUtf16)),line.text.slice(m.endUtf16)));})):h('p',{},report.totals.matches===0?'零匹配：是完整查询结果，不是0%学习评分；检查标点/大小写/分词规则。':'显示过滤后零行；完整报告仍含全部匹配。')),h('h3',{},'邻词频次（按侧和距离分别计数）'),report.neighborFrequencies.length?h('div',{class:'l043-scroll'},h('table',{},h('thead',{},h('tr',{},['侧','距关键词第几词','词元（计数键）','频次'].map(v=>h('th',{},v)))),h('tbody',{},report.neighborFrequencies.slice(0,200).map(f=>h('tr',{},h('td',{},f.side==='left'?'左':'右'),h('td',{},String(f.distance)),h('td',{},f.token),h('td',{},String(f.count)))))),h('p',{},`频次表界面首200项 / 全部${report.neighborFrequencies.length}项；JSON/Markdown全部保留，按侧/距离、频次降序、词元排序。`)):h('p',{},'没有窗口内邻词（零匹配或窗口0）。'),h('ul',{},report.definitions.map(v=>h('li',{},v))));}
  function renderReport(){if(!report){replace(reportHost,h('p',{},'有效完整查询后才可预览/导出。'));return;}try{const json=reportJson(report),md=reportMarkdown(report);replace(reportHost,h('details',{},h('summary',{},'完整JSON预览（包括全部语料正文和出处）'),h('pre',{class:'l043-preview'},json)),h('details',{},h('summary',{},'完整Markdown预览'),h('pre',{class:'l043-preview'},md)),h('div',{class:'l043-actions'},h('button',{class:'btn',onclick:()=>exportReport('json')},'导出完整 JSON'),h('button',{class:'btn',onclick:()=>exportReport('md')},'导出完整 Markdown')));}catch(e){replace(reportHost,h('p',{class:'l043-error'},`导出预算拒绝：${e.message}`));}}
  async function exportReport(extension){if(!report||exporting||destroyed)return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message('当前基础层不支持防覆盖副本导出；未调用保存，请升级。',true);return;}let content;try{content=extension==='json'?reportJson(report):reportMarkdown(report);}catch(e){message(e.message,true);return;}exporting=true;try{const response=await files.saveText({content,extension,defaultName:`L043-corpus-evidence.${extension}`,copyOnly:true});message(response?.ok===true?'完整语料/出处/KWIC/频次副本已保存；请注意报告包含全部原文。':response?.canceled===true?'保存已取消，报告保留。':`导出失败：${response?.error||'未确认ok===true'}`,response?.ok!==true&&response?.canceled!==true);}catch(e){message(`导出失败：${e.message}`,true);}finally{exporting=false;}}
  try{const raw=channel?.latest&&(channel.running||channel.pending)?channel.latest:ctx.config?.get?.(KEY);if(raw){draft=validateDraft(raw,{forStorage:true});message('已恢复输入草稿；本地TXT/hash/索引/报告未恢复，请重选原文件或重新查询粘贴文本。');}}catch(e){message(`草稿未恢复：${e.message}`,true);}
  root.replaceChildren(h('link',{rel:'stylesheet',href:new URL('./style.css',import.meta.url).href}),h('h2',{},'语料搭配观察'),h('p',{},'观察用户TXT的使用证据：KWIC、按距离邻词频次、完整文件/行号原行；不自动推荐用法。'),notice,storage,h('details',{},h('summary',{},'分词、预算与保存规则'),h('p',{},'按行空白分词，不去标点/词形还原/自动分中文词；单词字面匹配，窗口不跨行。TXT严格UTF-8，CRLF/LF/CR及末尾空行保留，BOM不参与索引但计入原字节hash。'),h('p',{},'本地1–8份TXT，每份≤512KiB、合计≤1MiB；粘贴≤1MiB；≤20000行/100000词、每行≤2048码点/词≤80码点、≤2000匹配。窗口0–10；完整报告≤4MiB、完整导出≤8MiB。任何超限整份拒绝，不截断假完成。每2048工作项让出并检查取消，切走使在途结果无效。'),h('p',{},'配置仅保存schema1输入草稿，≤64KiB；大型粘贴不写配置，关闭不能恢复。导入TXT、文件名/hash、索引和报告从不写配置；文件不改写，关闭需重新选择。报告包含全部原文，预览后保存新副本。每页25出处，频次界面首200项明确提示；导出不受分页/过滤影响。')),editor,output,reportHost);renderEditor();renderOutput();renderReport();return{activate(){active=true;},deactivate(){active=false;ticket++;persist();},destroy(){if(destroyed)return;ticket++;persist();destroyed=true;active=false;sources=[];report=null;draft=exampleDraft();root.replaceChildren();root.classList.remove('feature-l043');}};
}};
