import { h } from '../../core/ui.js';
import { MODEL_VERSION, FUNCTIONS, RELATIONS, POLICY, example, verify, prepareStoredState, validateStoredState, reportMarkdown } from './model.mjs';
const KEY='features.L024.state';
const PREDICTIONS={unsure:'未预测 / 不确定',pass:'预测通过',fail:'预测失败'};
const show=value=>Array.isArray(value)?JSON.stringify(value):String(value);
export default{
  id:'L024',
  create(root,ctx={}){
    root.classList.add('feature-l024');let draft=example();let result=null;let timer=null;let destroyed=false;let exporting=false;let restored='';
    try{const raw=ctx.config?.get(KEY);if(raw){const state=validateStoredState(raw);draft={function:state.function,array:state.array,permutation:state.permutation,scale:state.scale,predictions:state.predictions};restored='已恢复输入和预测草稿；观察结果未保存，请重新验证。';}}catch(error){restored=`草稿未能恢复：${error.message}`;}
    const notice=h('div',{class:'l024-notice',role:'status','aria-live':'polite'},restored);const storage=h('div',{class:'l024-notice',role:'status'});const editor=h('div');const output=h('div',{class:'l024-output'});
    function replace(node,...children){node.replaceChildren(...children.flat(Infinity).filter(child=>child!==null&&child!==undefined&&child!==false));}
    function message(text,error=false){if(!destroyed){notice.textContent=text;notice.classList.toggle('is-error',error);}}
    function persist(){if(timer!==null)clearTimeout(timer);timer=null;if(!ctx.config?.set)return;let state;try{state=prepareStoredState(draft);}catch(error){if(!destroyed)storage.textContent=`${error.message} 当前草稿未写入全局配置，关闭后只能恢复较早草稿；请导出完整JSON。`;return;}if(!destroyed)storage.textContent='';try{Promise.resolve(ctx.config.set(KEY,state)).catch(error=>message(`保存草稿失败：${error.message} 请导出完整JSON。`,true));}catch(error){message(`保存草稿失败：${error.message} 请导出完整JSON。`,true);}}
    function changed(resetPrediction=true){result=null;if(resetPrediction)for(const id of Object.keys(RELATIONS))draft.predictions[id]='unsure';renderOutput();message('输入或预测已改变，旧观察已清空；调整预测后重新验证。');if(timer!==null)clearTimeout(timer);timer=setTimeout(persist,250);}
    function load(kind){draft=example(kind);changed();renderEditor();persist();message('示例已载入，先预测再验证；也可直接观察。');}
    function select(label,value,choices,onchange){const control=h('select',{class:'field','aria-label':label,onchange:()=>onchange(control.value)},choices.map(([id,title])=>h('option',{value:id},title)));control.value=value;return h('label',{class:'l024-field'},h('strong',{},label),control);}
    function renderEditor(){const fn=Object.hasOwn(FUNCTIONS,draft.function)?FUNCTIONS[draft.function]:null;const input=h('textarea',{class:'field',rows:'3',maxlength:'2048',spellcheck:'false','aria-label':'JSON整数数组',oninput:()=>{draft.array=input.value;changed();renderPredictions();}});input.value=draft.array;
      const predictions=h('div',{class:'l024-predictions'});
      function renderPredictionControls(){replace(predictions,fn?h('p',{},`本函数只适用：${fn.relations.map(id=>RELATIONS[id].title).join('、')}；其他关系不会执行或参与结论。`):h('p',{},'请选择有效内置函数。'),fn?fn.relations.map(id=>select(`${RELATIONS[id].title}事前预测`,draft.predictions[id],Object.entries(PREDICTIONS),value=>{draft.predictions[id]=value;changed(false);})):null);}
      // Inputs reset prior predictions; rebuild only prediction controls to preserve the editing caret.
      renderPredictions=renderPredictionControls;
      replace(editor,select('内置函数',draft.function,Object.entries(FUNCTIONS).map(([id,value])=>[id,value.title]),value=>{draft.function=value;changed();renderEditor();}),fn?h('p',{},`内置行为：${fn.implementation}`):null,h('label',{class:'l024-field'},h('strong',{},'JSON整数数组'),input),h('p',{},'仅0–32项Number安全整数，范围±9007199254740991；可用空数组。重复元素保留在输入中。输入JSON，不写函数或代码。'),select('固定置换',draft.permutation,[['reverse','反转顺序'],['rotate','左轮转一位']],value=>{draft.permutation=value;changed();renderPredictionControls();}),fn?.relations.includes('linear')?h('label',{class:'l024-field'},h('strong',{},'缩放因子−10至10'),(()=>{const control=h('input',{class:'field',type:'text',inputmode:'numeric',maxlength:'8','aria-label':'缩放因子',oninput:()=>{draft.scale=control.value;changed();renderPredictionControls();}});control.value=draft.scale;return control;})()):h('p',{},'缩放因子只用于求和函数；排序关系不使用缩放。'),h('h3',{},'事前预测（可选）'),predictions,h('div',{class:'l024-actions'},[['dedupe','载入错误排序示例'],['correct','载入正确排序示例'],['linear','载入常量偏差示例']].map(([kind,label])=>h('button',{class:'btn',onclick:()=>load(kind)},label)),h('button',{class:'btn primary',onclick:run},'验证适用关系')));renderPredictionControls();
    }
    let renderPredictions=()=>{};
    function run(){try{result=verify(draft);persist();renderOutput();message(`已观察${result.relations.length}项适用关系：${result.failures.length}项违反，${result.predictionErrors.length}项预测错误。通过不证明函数全部正确。`);}catch(error){result=null;renderOutput();message(error.message,true);}}
    function table(headers,rows){return h('div',{class:'l024-scroll'},h('table',{},h('thead',{},h('tr',{},headers.map(label=>h('th',{scope:'col'},label)))),h('tbody',{},rows.map(row=>h('tr',{},row.map(value=>h('td',{},show(value))))))));}
    function rowView(row){return h('section',{class:`l024-relation${row.passed?'':' is-failure'}`},h('h3',{},`${row.title}：${row.passed?'通过':'失败（关系违反样例）'}`),h('p',{},row.rule),h('p',{},`变换：${row.transformation}`),table(['项目','原执行','变换执行'],[['输入',row.originalInput,row.transformedInput],['函数结果',row.originalOutput,row.transformedOutput]]),table(['检查','关系预期','实际观察','结论'],row.checks.map(check=>[check.label,check.expected,check.observed,check.passed?'通过':'失败'])),h('p',{},`${PREDICTIONS[row.prediction]} → 实际${row.passed?'通过':'失败'}；${row.predictionCorrect===null?'未计预测对错':row.predictionCorrect?'预测正确':'预测错误，请核对上述输入/输出与关系前提'}`),row.warning?h('p',{class:'l024-warning'},row.warning):null,!row.passed?h('p',{},'上方完整原/变换输入与结果就是可复现的关系违反样例，可随报告导出。'):null);}
    function renderOutput(){const exports=h('div',{class:'l024-actions'},h('button',{class:'btn',onclick:()=>exportReport('json')},'导出完整 JSON'),h('button',{class:'btn',onclick:()=>exportReport('md')},'导出完整 Markdown'));if(!result){replace(output,h('p',{},'尚无有效观察；先预测（可选），再验证适用关系。可导出当前草稿。'),exports);return;}replace(output,h('p',{class:'l024-summary'},`${result.functionTitle} · ${result.relations.length}项关系 · ${result.failures.length}项违反 · 已预测${result.predicted}项 · 预测错误${result.predictionErrors.length}项`),h('p',{},'通过只表示这些输入下的这些关系成立。错误去重排序也可能通过置换不变和幂等；常量偏差求和在k=1时也通过。没有自动产生标准答案或证明全部正确。'),result.relations.map(rowView),exports);}
    async function exportReport(extension){if(exporting)return;const files=window.toolbox?.files;if(files?.saveTextSupportsCopyOnly!==true){message('当前基础层缺少防覆盖导出能力，请升级后导出。',true);return;}exporting=true;try{const payload={feature:'L024',schemaVersion:1,modelVersion:MODEL_VERSION,exportedAt:new Date().toISOString(),draft:cloneDraft(),result};const response=await files.saveText({content:extension==='json'?JSON.stringify(payload,null,2):reportMarkdown(payload),extension,defaultName:`L024-metamorphic.${extension}`,copyOnly:true});message(response?.ok===true?'已导出新副本，包含完整变换、观察与关系违反样例。':response?.canceled===true?'已取消导出，草稿和观察保留。':`导出失败：${response?.error||'未确认保存成功'}`,response?.ok!==true&&response?.canceled!==true);}catch(error){message(`导出失败：${error.message}`,true);}finally{exporting=false;}}
    function cloneDraft(){return JSON.parse(JSON.stringify(draft));}
    root.replaceChildren(h('link',{rel:'stylesheet',href:new URL('./style.css',import.meta.url).href}),h('h2',{},'蜕变关系验真'),h('p',{},'没有标准答案时，验证函数在变换输入前后是否符合声明的关系，并检查自己的预测。'),notice,storage,h('details',{},h('summary',{},'适用前提与保存范围'),h('p',{},POLICY),h('p',{},'长度保持同时检查原输入及置换输入，不能只比较两个错误输出是否一样长。幂等将第一次输出送回同一函数。线性预期来自k×第一次输出，不是外部标准答案；整数运算以BigInt核对范围后才返回Number。'),h('p',{},'编辑输入/函数/变换会清空预测和观察；修改预测也清空观察，避免事后改写预测记录。配置只存schemaVersion=1输入及预测草稿，≤64KiB UTF-8且数组文本≤2048字节；观察需重算。没有后台执行或任意JS。')),editor,output);renderEditor();renderOutput();return{activate(){},deactivate(){persist();},destroy(){if(destroyed)return;persist();destroyed=true;root.replaceChildren();root.classList.remove('feature-l024');}};
  },
};
