import{h}from'../../core/ui.js';
import{LIMITS,TONES,CODES,NAMES,createProject,restore,parse,encode,noteName,recorder,elapsed,on as recordOn,off as recordOff,pedal,finish,midi,markdown,drawRoll}from'./model.mjs';
import{voice,replay}from'./audio.mjs';
export default{id:'E013',create(root,ctx={}){
 const key='featureLab.E013.project',clock=ctx.clock||(()=>performance.now());let project=createProject(),active=false,alive=true,invalid=false,fresh=false,saving=false,reading=false,exporting=false,nativePending=false,generation=0,exportJob=0,audioToken=0,audio=null,starting=false,record=null,playback=null,sustaining=false,pedalKeyDown=false,timer=null,candidate=null,message='先点击启用音频，再聚焦琴键演奏。',saved='尚无本地工程。';const held=new Map(),live=new Map(),nodes=new Set(),captures=new Map(),listeners=[],controls=[],buttons=[],keys=[];let status,storage,summary,keyboard,roll,file,confirmNew,confirmImport,confirmInvalid;
 try{const v=ctx.config?.get?.(key,null);if(v==null)fresh=true;else{project=restore(v);saved='完整旋律已恢复，尚未启用音频。';}}catch(e){invalid=true;message='旧工程拒绝：'+e.message;saved='旧档未覆盖，可确认清空或导入。';}
 const busy=()=>saving||reading||exporting,usable=()=>alive&&active&&!document.hidden&&!invalid&&!busy(),playing=()=>audio?.state==='running',onEvent=(n,t,f)=>{n.addEventListener(t,f);listeners.push([n,t,f]);};
 function clearDOM(){for(const[n,t,f]of listeners)n.removeEventListener(t,f);listeners.length=controls.length=buttons.length=keys.length=0;root.replaceChildren();}
 function update(){if(!alive)return;const disabled=!active||document.hidden||busy(),changing=disabled||invalid||!!record||!!playback||held.size>0||live.size>0||starting;for(const c of controls)c.disabled=c===file?disabled||!!record||!!playback||live.size>0||starting:changing;for(const b of buttons)b.node.disabled=disabled||(invalid&&!['invalid','import'].includes(b.kind))||(b.kind==='enable'&&(playing()||starting))||(b.kind==='record'&&(!playing()||record||playback||live.size))||(b.kind==='finish'&&!record)||(b.kind==='play'&&(record||playback||!project.notes.length||starting))||(b.kind==='import'&&(!candidate||record||playback||live.size))||(b.kind==='text'&&(record||playback||live.size||window.toolbox?.files?.saveTextSupportsCopyOnly!==true))||(b.kind==='binary'&&(record||playback||live.size||window.toolbox?.files?.saveBinarySupportsCopyOnly!==true));for(const k of keys){k.node.disabled=disabled||invalid||!playing()||!!playback;k.node.style.outline=live.has(k.pitch)?'3px solid #e4583f':'';k.node.setAttribute('aria-pressed',String(live.has(k.pitch)));}confirmNew.disabled=confirmImport.disabled=confirmInvalid.disabled=disabled||!!record||!!playback||live.size>0;summary.textContent=`两八度C${project.octave}–B${project.octave+1} · ${TONES[project.tone]} · 当前${live.size}音 · 延音${sustaining?'开':'关'} · ${record?'录制 '+elapsed(record,clock())+'ms / '+record.slots.length+'音符':playback?'回放中':project.notes.length+'音符 / '+project.durationMs+'ms'} · ${playing()?'音频已启用':starting?'音频启动中':'音频关闭'}`;status.textContent=message;storage.textContent=saved;}
 function tick(){if(!alive||!active||document.hidden){silence(true,'已离开，声音已停止。');return;}if(record&&elapsed(record,clock())>=LIMITS.ms){endRecord('已到五分钟，完整录制已保留。');return;}if(playback&&audio.currentTime>=playback.end){playback.close();playback=null;message='完整回放结束。';}if(!record&&!playback&&!live.size&&timer!==null){clearInterval(timer);timer=null;}update();}
 function ticking(){if(timer===null&&(record||playback||live.size))timer=setInterval(tick,50);}
 function releaseCaptures(){for(const[id,node]of captures)try{if(node.hasPointerCapture?.(id))node.releasePointerCapture(id);}catch{}captures.clear();}
 function silence(close,text){audioToken++;starting=false;if(timer!==null){clearInterval(timer);timer=null;}if(record){project=finish(record,clock());record=null;save(false);}held.clear();sustaining=pedalKeyDown=false;releaseCaptures();for(const n of nodes)n.close();nodes.clear();live.clear();if(playback){playback.close();playback=null;}if(close&&audio){const a=audio;audio=null;try{Promise.resolve(a.close()).catch(()=>{});}catch{}}if(text)message=text;update();}
 function releasePitch(pitch,force=false){if(!live.has(pitch))return;if(sustaining&&!force)return;const n=live.get(pitch);live.delete(pitch);n.release();if(record)recordOff(record,pitch,clock(),true);update();}
 function press(id,pitch){if(!usable()||!playing()||playback||held.has(id))return;const same=[...held.values()].includes(pitch);if(same){held.set(id,pitch);return;}try{if(live.has(pitch))releasePitch(pitch,true);if(live.size>=24)throw Error('最多24同时音。');if(record)recordOn(record,pitch,clock());held.set(id,pitch);const n=voice(audio,pitch,project.tone,100,project.volume);live.set(pitch,n);nodes.add(n);n.oscillator.onended=()=>{nodes.delete(n);n.close();};if(nodes.size>48){const old=[...nodes].find(v=>![...live.values()].includes(v));if(old){old.close();nodes.delete(old);}}ticking();update();}catch(e){if(record)endRecord('录制停止并保留：'+e.message);else{message=e.message;update();}}}
 function lift(id){const pitch=held.get(id);if(pitch===undefined)return;held.delete(id);if(![...held.values()].includes(pitch))releasePitch(pitch);update();}
 function setPedal(value){if(!usable()||!playing()||playback)return;sustaining=value;if(record)pedal(record,value,new Set(held.values()),clock());if(!value)for(const pitch of [...live.keys()])if(![...held.values()].includes(pitch))releasePitch(pitch,true);update();}
 async function enable(){if(!usable()||playing()||starting)return false;const token=++audioToken;let ac;starting=true;message='正在启用本地音频…';update();try{const Ctor=window.AudioContext||window.webkitAudioContext;if(!Ctor)throw Error('WebAudio不可用');ac=new Ctor();audio=ac;await ac.resume();if(!alive||!active||document.hidden||token!==audioToken||audio!==ac)return false;if(ac.state!=='running')throw Error('音频未运行，请再次点击');starting=false;message='音频已启用。点击或Tab聚焦琴键区，按住对应键发音。';update();keyboard.focus();return true;}catch(e){if(alive&&token===audioToken)silence(true,'音频失败：'+e.message);return false;}finally{if(ac&&audio!==ac)try{await ac.close();}catch{}}}
 function endRecord(text='录制结束，完整音符已保存。'){if(!record)return;project=finish(record,clock());record=null;silence(false,text);save(false);}
 async function play(){if(!usable()||record||playback||live.size||!project.notes.length)return;if(!playing()&&!await enable())return;if(!usable())return;playback=replay(audio,project);message='回放按源音符毫秒时刻调度，结束后停止。';ticking();update();}
 async function save(rebuild=true){if(!alive||invalid||saving)return;const value=restore(project);saving=true;saved='正在保存完整旋律…';if(rebuild)render();else update();try{if(typeof ctx.config?.set!=='function')throw Error('本地配置不可用');await ctx.config.set(key,value);if(alive)saved='完整旋律已保存，重载不自动发声。';}catch(e){if(alive)saved='保存失败：'+e.message+'；当前临时保留，可重试或另存。';}finally{saving=false;if(alive){if(rebuild)update();else{repaint();update();}}}}
 function repaint(){const c=roll.getContext('2d');if(c)drawRoll(c,project);}
 function render(){clearDOM();function button(t,f,kind){const n=h('button',{type:'button'},t);onEvent(n,'click',f);buttons.push({node:n,kind});return n;}function select(label,values,value,fn){const n=h('select',{'aria-label':label});for(const[v,t]of values)n.append(h('option',{value:String(v)},t));n.value=String(value);onEvent(n,'change',()=>{if(!usable()||record||playback||live.size||starting)return;const x=Number(n.value);if(!values.some(v=>v[0]===x))return;fn(x);generation++;save();});controls.push(n);return h('label',{},label+' ',n);}
 const volume=h('input',{type:'number',min:0,max:100,step:1,value:String(project.volume),'aria-label':'琴音量%'});onEvent(volume,'change',()=>{if(!usable()||record||playback||live.size||starting)return;if(!/^\d{1,3}$/.test(volume.value)||Number(volume.value)>100){message='音量须0–100整数，未改变。';volume.value=String(project.volume);update();return;}project.volume=Number(volume.value);generation++;save();});controls.push(volume);keyboard=h('div',{tabindex:'0',role:'group','aria-label':'两八度琴键',style:{display:'grid',gridTemplateColumns:'repeat(12,minmax(50px,1fr))',gap:'4px',overflowX:'auto',padding:'8px',touchAction:'none'}});for(let i=0;i<24;i++){const pitch=(project.octave+1)*12+i,black=[1,3,6,8,10].includes(i%12),n=h('button',{type:'button','aria-label':'琴键'+noteName(pitch),style:{background:black?'#233f47':'#faf7ef',color:black?'#ffffff':'#233f47',minWidth:'50px',minHeight:'86px',border:'1px solid #8eaaa4',touchAction:'none'}},h('strong',{},noteName(pitch)),h('br'),CODES[i].replace('Key','').replace('Digit',''));keys.push({node:n,pitch});onEvent(n,'pointerdown',e=>{if(!usable()||!playing()||e.button!==0||playback)return;e.preventDefault();const id='pointer'+e.pointerId;if(captures.has(e.pointerId))return;n.focus();captures.set(e.pointerId,n);try{n.setPointerCapture(e.pointerId);press(id,pitch);}catch{captures.delete(e.pointerId);}});const up=e=>{lift('pointer'+e.pointerId);if(captures.get(e.pointerId)===n){captures.delete(e.pointerId);try{if(n.hasPointerCapture?.(e.pointerId))n.releasePointerCapture(e.pointerId);}catch{}}};onEvent(n,'pointerup',up);onEvent(n,'pointercancel',up);onEvent(n,'lostpointercapture',up);keyboard.append(n);}
 onEvent(keyboard,'keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey)return;const i=CODES.indexOf(e.code);if(i>=0){e.preventDefault();if(!e.repeat)press('key'+e.code,(project.octave+1)*12+i);}else if(e.code==='Space'){e.preventDefault();if(!e.repeat){pedalKeyDown=true;setPedal(true);}}else if(e.code==='Enter'){e.preventDefault();const k=keys.find(k=>k.node===document.activeElement);if(k&&!e.repeat)press('enter',k.pitch);}else if(e.code==='Escape'){e.preventDefault();silence(false,'当前声音/录制/回放已停止。');}});
 file=h('input',{type:'file',accept:'.json,application/json','aria-label':'旋律工程JSON'});onEvent(file,'change',()=>read(file.files?.[0]));controls.push(file);confirmNew=h('input',{type:'checkbox','aria-label':'确认替换旧录制'});confirmImport=h('input',{type:'checkbox','aria-label':'确认应用旋律工程'});confirmInvalid=h('input',{type:'checkbox','aria-label':'确认清空无效琴档'});summary=h('p',{'aria-label':'琴状态'});status=h('p',{role:'status','aria-label':'操作状态'});storage=h('p',{'aria-label':'旋律保存状态'});roll=h('canvas',{'aria-label':'完整旋律琴卷',style:{width:'100%',maxWidth:'1000px',height:'auto',display:'block'}});
 root.append(h('section',{style:{maxWidth:'1060px',margin:'0 auto',padding:'16px',lineHeight:'1.6'}},h('h2',{},'随手弹琴'),h('p',{},'三种程序合成音色，两八度24个半音键，可同时按多个电脑键或多指触摸。先启用音频，默认不发声；无联网/麦克风。先以低音量演奏。'),h('div',{},select('起始八度',[2,3,4,5,6].map(n=>[n,'C'+n+'–B'+(n+1)]),project.octave,v=>project.octave=v),select('合成音色',TONES.map((t,i)=>[i,t]),project.tone,v=>project.tone=v),h('label',{},'音量% ',volume),button('启用音频',enable,'enable'),button('停止全部声音',()=>silence(true,'音频关闭，已结束并保留当前录制。'),'stop')),h('p',{},'下排键 Z S X D C V G B H N J M；高八度 Q 2 W 3 E R 5 T 6 Y 7 U。按住发音/松开发音结束，重复keydown忽略；同一音多输入持有到最后一个释放。聚焦琴键后空格为临时延音踏板，Enter按住焦点琴键，Escape停止；Tab可逐键聚焦。不是传统黑白键叠排，半音按顺序排成两行以便全部可点。'),keyboard,summary,h('div',{},button('延音开关',()=>setPedal(!sustaining),'pedal'),h('label',{},confirmNew,' 确认替换上一段录制'),button('开始新录制',()=>{if(!usable()||!playing()||record||playback||live.size)return;if(project.notes.length&&!confirmNew.checked){message='请先确认替换，旧录制未改。';update();return;}record=recorder(project,clock());sustaining=false;generation++;message='录制中，最多五分钟/512音符；停止后保存全部时值。';ticking();update();keyboard.focus();},'record'),button('结束并保存录制',()=>endRecord(),'finish'),button('回放完整旋律',play,'play')),h('p',{},'录制使用单调毫秒时钟，延音合并到note-off；同音重击先结束前音，最短时值1ms。五分钟自动停止，512音符后下一次按键触发停止保留。修改音色/八度/音量需先停止并松开琴键。离开/隐藏/失焦会收尾当前录制并停止全部声音；返回需明确启用。'),roll,storage,button('重试旋律保存',()=>save(),'retry'),h('h3',{},'完整工程与副本'),h('p',{},'所有音符/音色/力度/毫秒起止完整保存，工程schema1≤64KiB、最多512音符；MIDI type0/500PPQ/500000us（1tick=1ms）。延音已合并成音长，不另发踏板事件；外部MIDI三通道GM音色是近似映射，不保证与本机声音相同。PNG是完整概览，长录制短音符可能很窄，JSON/MD/MIDI始终保留精确值。'),h('div',{},button('另存完整旋律JSON',()=>exportFile('json'),'text'),button('另存完整旋律Markdown',()=>exportFile('md'),'text'),button('另存旋律MIDI',()=>exportFile('mid'),'binary'),button('另存完整琴卷PNG',()=>exportFile('png'),'binary')),h('p',{},window.toolbox?.files?.saveTextSupportsCopyOnly===true&&window.toolbox?.files?.saveBinarySupportsCopyOnly===true?'所有副本独占新建，不覆盖原文件。':'应用缺安全文本/二进制copyOnly能力，请升级后导出。'),file,h('p',{'aria-label':'旋律导入预览'},candidate?`已校验 ${candidate.notes.length}音符 / ${candidate.durationMs}ms；尚未替换。`:'选择≤64KiB严格UTF-8完整工程，预览再确认。'),h('label',{},confirmImport,' 确认替换全部工程'),button('应用旋律工程',()=>{if(!alive||!active||document.hidden||busy()||record||playback||live.size||!candidate)return;if(!confirmImport.checked){message='请先确认替换。';update();return;}silence(true);project=candidate;candidate=null;invalid=false;generation++;save();},'import'),invalid?h('div',{},h('label',{},confirmInvalid,' 确认清空无效档'),button('从空琴档开始',()=>{if(!active||busy()||!confirmInvalid.checked)return;invalid=false;project=createProject();generation++;save();},'invalid')):null,status));repaint();update();}
 async function read(f){if(!f||!usable()||record||playback||live.size)return;silence(true);const token=++generation;reading=true;candidate=null;message='正在校验完整工程…';update();try{if(f.size>LIMITS.bytes)throw Error('工程最多64KiB');const b=await f.arrayBuffer();if(!alive||token!==generation)return;if(b.byteLength>LIMITS.bytes)throw Error('实际工程超过64KiB');candidate=parse(new TextDecoder('utf-8',{fatal:true}).decode(b));message='全部音符校验通过，尚未替换。';}catch(e){if(alive&&token===generation)message='导入拒绝：'+e.message;}finally{if(alive&&token===generation){reading=false;render();}}}
 const response=r=>r?.ok===true?'已另存完整新副本。':r?.canceled?'已取消另存。':`另存失败：${r?.error||'未确认成功'}${r?.partialPath?'；请人工核对 '+r.partialPath:''}`;
 const offscreens=new Set();async function exportFile(kind){if(!usable()||record||playback||live.size)return;const files=window.toolbox?.files,text=['json','md'].includes(kind);if(text?files?.saveTextSupportsCopyOnly!==true:files?.saveBinarySupportsCopyOnly!==true)return;const token=generation,job=++exportJob,value=restore(project);exporting=true;message='正在准备完整副本…';update();let canvas;try{let payload;if(text)payload={copyOnly:true,extension:kind,defaultName:'melody-copy.'+kind,content:kind==='json'?encode(value):markdown(value)};else{let bytes;if(kind==='mid')bytes=midi(value);else{canvas=document.createElement('canvas');offscreens.add(canvas);drawRoll(canvas.getContext('2d'),value);const blob=await new Promise((r,j)=>canvas.toBlob(v=>v?r(v):j(Error('PNG编码失败')),'image/png'));if(!alive||token!==generation)return;if(blob.size>10485760)throw Error('PNG超过10MiB');bytes=new Uint8Array(await blob.arrayBuffer());}const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));if(!alive||token!==generation)return;let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));payload={copyOnly:true,defaultName:'melody-copy.'+kind,base64:btoa(s),sha256:[...hash].map(x=>x.toString(16).padStart(2,'0')).join('')};}if(!alive||token!==generation)return;nativePending=true;const r=await(text?files.saveText(payload):files.saveBinary(payload));if(alive&&token===generation)message=response(r);}catch(e){if(alive&&token===generation)message='另存失败：'+e.message;}finally{if(canvas){canvas.width=canvas.height=0;offscreens.delete(canvas);}if(job===exportJob){nativePending=false;if(alive){exporting=false;update();}}}}
 function suspend(){silence(true,'已离开/失焦，完整录制收尾，返回不自启。');generation++;reading=false;candidate=null;if(!nativePending){exporting=false;exportJob++;}update();}
 function keyUp(e){if(CODES.includes(e.code)&&held.has('key'+e.code)){e.preventDefault();lift('key'+e.code);}else if(e.code==='Space'&&pedalKeyDown){e.preventDefault();pedalKeyDown=false;setPedal(false);}else if(e.code==='Enter'&&held.has('enter')){e.preventDefault();lift('enter');}}
 const visibility=()=>{if(document.hidden)suspend();else update();},blur=()=>{if(active){if(nativePending)silence(true,'音频已停止，原生另存仍在进行。');else suspend();}};document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);window.addEventListener('keyup',keyUp);render();return{activate(){if(alive){active=true;if(fresh&&!invalid){fresh=false;save();}else update();}},deactivate(){if(alive){active=false;suspend();}},destroy(){if(!alive)return;silence(true);alive=active=false;generation++;document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur);window.removeEventListener('keyup',keyUp);for(const c of offscreens)c.width=c.height=0;offscreens.clear();roll.width=roll.height=0;clearDOM();project=candidate=null;}};
}};
