export const LIMITS={pages:20,visits:100,budgetSeconds:300,timerMs:600000,stopRequestMs:300000,audioBytes:8388608,decodeSeconds:301,decodedSamples:9632000};
export const bytes=s=>new TextEncoder().encode(s).length;
const clone=x=>JSON.parse(JSON.stringify(x));
function keys(x,expected,label){if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).length!==expected.length||Object.keys(x).some(k=>!expected.includes(k)))throw Error(`${label}字段无效`);}
function text(x,max,label,required=false){if(typeof x!=='string'||[...x].length>max||(required&&!x.trim())||/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(x)||/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(x))throw Error(`${label}须${required?'非空':''}≤${max}码点且无非法字符`);}
export function exampleDraft(){return{schemaVersion:1,source:{label:'用户自编提纲',location:'两页演讲练习'},pages:[{id:'P1',title:'问题与背景',outline:'说明问题、来源和适用范围。',budgetSeconds:60},{id:'P2',title:'方法与结论',outline:'介绍方法、关键事实与待核项。',budgetSeconds:60}],note:''};}
export function validateDraft(raw){if(bytes(JSON.stringify(raw))>65536)throw Error('完整输入草稿超过64KiB，不写配置；关闭只能恢复较早合法提纲');keys(raw,['schemaVersion','source','pages','note'],'草稿');if(raw.schemaVersion!==1)throw Error('只接受schemaVersion=1提纲，不含计时/媒体');keys(raw.source,['label','location'],'来源');text(raw.source.label,160,'来源名');text(raw.source.location,320,'出处');text(raw.note,500,'备注');if(!Array.isArray(raw.pages)||raw.pages.length<1||raw.pages.length>20)throw Error('页数须1–20');const ids=new Set();let sum=0;for(const p of raw.pages){keys(p,['id','title','outline','budgetSeconds'],'页面');if(typeof p.id!=='string'||!/^P(?:[1-9]|1\d|20)$/.test(p.id)||ids.has(p.id))throw Error('页面ID未知/重复');ids.add(p.id);text(p.title,120,'页标题',true);text(p.outline,2000,'页提纲');if(!Number.isInteger(p.budgetSeconds)||p.budgetSeconds<0||p.budgetSeconds>300)throw Error('每页预算须0–300整数秒，空项不是0');sum+=p.budgetSeconds;}if(sum<1||sum>300)throw Error('总预算须1–300秒，各页预算求和');return clone(raw);}
export function addPage(raw){const d=validateDraft(raw);if(d.pages.length===20)throw Error('最多20页');const id=Array.from({length:20},(_,i)=>`P${i+1}`).find(id=>!d.pages.some(p=>p.id===id));d.pages.push({id,title:'新增页（请编辑）',outline:'',budgetSeconds:0});return d;}
function clock(now){if(!Number.isFinite(now)||now<0)throw Error('时钟须非负有限毫秒');}
export function beginRun(raw,now,capture=null){clock(now);const draft=validateDraft(raw);return{draft,status:'running',elapsedMs:0,startClock:now,lastClock:now,visits:[{seq:1,pageId:draft.pages[0].id,timerStartMs:0,timerEndMs:null,captureStartSeconds:capture,captureEndSeconds:null}],stopReason:null};}
export function currentMs(run,now){clock(now);if(now<run.lastClock)throw Error('单调时钟回退，拒绝伪造时长');const value=run.elapsedMs+(run.status==='running'?now-run.startClock:0);if(value>LIMITS.timerMs)throw Error('计时记录超过600秒安全上限，整轮报告拒绝，不截断');return value;}
export function switchPage(raw,id,now,capture=null){const r=clone(raw);if(r.status!=='running')throw Error('仅计时中可切页');if(!r.draft.pages.some(p=>p.id===id))throw Error('页面未知');if(r.visits.at(-1).pageId===id)return r;if(r.visits.length>=100)throw Error('最多100次页面访问，请结束本轮');const elapsed=currentMs(r,now);r.lastClock=now;const old=r.visits.at(-1);old.timerEndMs=elapsed;old.captureEndSeconds=capture;r.visits.push({seq:r.visits.length+1,pageId:id,timerStartMs:elapsed,timerEndMs:null,captureStartSeconds:capture,captureEndSeconds:null});return r;}
export function stopRun(raw,now,capture=null,reason='用户暂停',finished=false){const r=clone(raw);if(r.status!=='running')return r;const elapsed=currentMs(r,now);r.lastClock=now;r.elapsedMs=elapsed;r.visits.at(-1).timerEndMs=elapsed;r.visits.at(-1).captureEndSeconds=capture;r.status=finished?'finished':'paused';r.stopReason=reason;return r;}
export function resumeTimer(raw,now){const r=clone(raw);if(r.status!=='paused')throw Error('只有暂停后可手动继续计时');if(r.visits.length>=100)throw Error('最多100次页面访问');clock(now);if(now<r.lastClock)throw Error('时钟回退');r.status='running';r.startClock=now;r.lastClock=now;r.visits.push({seq:r.visits.length+1,pageId:r.visits.at(-1).pageId,timerStartMs:r.elapsedMs,timerEndMs:null,captureStartSeconds:null,captureEndSeconds:null});return r;}
export function validateAudio(meta){keys(meta,['mime','extension','byteLength','sha256','decodedDurationSeconds','captureElapsedSeconds','sampleRate','channels','decodeVerified'],'录音信息');if(!['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/ogg'].includes(meta.mime)||meta.extension!==(meta.mime.startsWith('audio/ogg')?'ogg':'webm'))throw Error('仅接受实际WebM/OGG录音MIME');if(!Number.isInteger(meta.byteLength)||meta.byteLength<1||meta.byteLength>LIMITS.audioBytes||!/^([a-f0-9]{64})$/.test(meta.sha256)||meta.decodeVerified!==true)throw Error('完整录音字节/hash/解码状态无效');if(!Number.isFinite(meta.decodedDurationSeconds)||meta.decodedDurationSeconds<=0||meta.decodedDurationSeconds>301||!Number.isFinite(meta.captureElapsedSeconds)||meta.captureElapsedSeconds<0||meta.captureElapsedSeconds>600||!Number.isFinite(meta.sampleRate)||meta.sampleRate<8000||meta.sampleRate>96000||![1,2].includes(meta.channels)||meta.decodedDurationSeconds*meta.sampleRate*meta.channels>LIMITS.decodedSamples)throw Error('录音解码/采集时间/声道帧预算无效');return clone(meta);}
export function makeReport(run,meta=null,recordingStatus='未录音'){if(run.status==='running')throw Error('请先暂停或结束，不能导出仍在变化的时段');const audio=meta?validateAudio(meta):null;const elapsed=currentMs(run,run.lastClock),visits=run.visits.map(v=>{if(v.timerEndMs===null||v.timerEndMs<v.timerStartMs)throw Error('时段未封存/倒序');const start=v.captureStartSeconds;const seek=audio&&start!==null&&Number.isFinite(start)&&start>=0&&start<audio.decodedDurationSeconds?start:null;return{...v,durationSeconds:(v.timerEndMs-v.timerStartMs)/1000,playbackStartSeconds:seek,playbackEndSeconds:seek!==null&&v.captureEndSeconds!==null?Math.min(audio.decodedDurationSeconds,v.captureEndSeconds):null,playbackUnknown:seek===null?'未采集/录音不可用/标记超出实际解码长度':null};});const pages=run.draft.pages.map(p=>{const list=visits.filter(v=>v.pageId===p.id),actual=list.reduce((s,v)=>s+v.durationSeconds,0);return{...p,actualSeconds:actual,overSeconds:Math.max(0,actual-p.budgetSeconds),visited:list.length>0,visitSeqs:list.map(v=>v.seq),firstPlaybackSeconds:list.find(v=>v.playbackStartSeconds!==null)?.playbackStartSeconds??null};});const budget=pages.reduce((s,p)=>s+p.budgetSeconds,0);const report={feature:'L049',schemaVersion:1,input:run.draft,status:run.status,stopReason:run.stopReason,totals:{budgetSeconds:budget,actualSeconds:elapsed/1000,overSeconds:Math.max(0,elapsed/1000-budget)},pages,visits,audio,recordingStatus,definitions:['计时来自单调时钟活动时段，暂停间隙不计；页级实际时间是所有访问求和。','采集时间是MediaRecorder start事件后浏览器事件单调时钟，不是计时累计；两者不缩放/拼接。','播放标记以采集起点经过秒数直接定位，须在实际解码时长内；未采集时段保持未知，不映射到别页。','编码器启动延迟未测量，标记为浏览器事件对应的近似位置，不保证音频样本级同步。','回放使用完整解码样本的16位PCM WAV，有限时长与采样轴一致；二进制导出保留原始WebM/OGG字节，不导出回放转码。','软件录音/播放事件不证明物理麦克风或人耳正常；不转写、识别、评分。','配置仅提纲，不保存录音、计时或报告；窗口重载后媒体和本轮时段均丢失。']};reportJson(report);reportMarkdown(report);return report;}
export function reportJson(p){const s=JSON.stringify(p,null,2);if(bytes(s)>524288)throw Error('完整JSON超过512KiB，整份拒绝');return s;}
export function reportMarkdown(p){const raw=reportJson(p).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),fence='`'.repeat(Math.max(3,...[...raw.matchAll(/`+/g)].map(m=>m[0].length+1)));const s=['# L049 口头陈述彩排',`预算${p.totals.budgetSeconds}秒，实际${p.totals.actualSeconds}秒，超时${p.totals.overSeconds}秒。`,`${fence}json\n${raw}\n${fence}`].join('\n\n');if(bytes(s)>524288)throw Error('完整Markdown超过512KiB，整份拒绝');return s;}

export async function playbackWav(decoded,{canceled=()=>false,yieldControl=()=>new Promise(r=>setTimeout(r,0))}={}){const {length,numberOfChannels:channels,sampleRate:rate}=decoded;if(!Number.isInteger(length)||length<1||![1,2].includes(channels)||rate!==16000||length*channels>LIMITS.decodedSamples)throw Error('回放WAV解码样本须16kHz/1–2声道且在预算内');const buffer=new ArrayBuffer(44+length*channels*2),view=new DataView(buffer),write=(at,s)=>{for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i));};write(0,'RIFF');view.setUint32(4,buffer.byteLength-8,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,rate,true);view.setUint32(28,rate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,length*channels*2,true);const data=Array.from({length:channels},(_,i)=>decoded.getChannelData(i));for(let i=0;i<length;i++){if(i%16384===0){if(canceled())throw Error('回放准备已取消');await yieldControl();if(canceled())throw Error('回放准备已取消');}for(let c=0;c<channels;c++){const x=data[c][i];if(!Number.isFinite(x))throw Error('解码样本非有限');const v=Math.max(-1,Math.min(1,x));view.setInt16(44+(i*channels+c)*2,Math.round(v<0?v*32768:v*32767),true);}}return buffer;}
