import {PDFDocument,PDFName,ParseSpeeds} from './vendor/pdf-lib.esm.min.mjs';
export const LIMITS=Object.freeze({files:4,fileBytes:2097152,totalBytes:8388608,sourcePages:80,outputPages:80,binaryBytes:10485760,bundleFileBytes:2097152,runMs:15000,reportBytes:1048576});
const encoder=new TextEncoder(),strict=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join('|')!==[...keys].sort().join('|'))throw Error('字段无效');};
export async function sha(bytes){if(!(bytes instanceof Uint8Array))throw Error('须完整字节');return[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export function checkSources(raw){if(!Array.isArray(raw)||!raw.length||raw.length>4)throw Error('选择1至4份PDF');let total=0;const seen=new Set();for(const s of raw){strict(s,['id','name','bytes']);if(!/^F00[1-4]$/.test(s.id)||seen.has(s.id)||typeof s.name!=='string'||!s.name||s.name.length>240||/[\x00-\x1f\x7f]/.test(s.name)||!(s.bytes instanceof Uint8Array)||!s.bytes.length||s.bytes.length>2097152)throw Error('PDF来源ID/文件名/完整字节容量无效');seen.add(s.id);total+=s.bytes.length;}if(total>8388608)throw Error('完整PDF总容量超过8MiB');return raw;}
export async function loadSources(raw){checkSources(raw);const docs=[],sources=[];let count=0;for(const s of raw){const doc=await PDFDocument.load(s.bytes.slice(),{ignoreEncryption:false,updateMetadata:false,throwOnInvalidObject:true,parseSpeed:ParseSpeeds.Slow});if(doc.isEncrypted)throw Error('不接受加密PDF，不绕过权限');if(doc.catalog.has(PDFName.of('AcroForm')))throw Error('交互表单PDF暂不支持，避免丢失字段结构');const n=doc.getPageCount();if(!n||count+n>80)throw Error('源PDF总页数须1至80');count+=n;const pages=doc.getPages().map((p,i)=>{const mediaBox=p.getMediaBox(),cropBox=p.getCropBox(),rotation=p.getRotation().angle;if(![mediaBox.x,mediaBox.y,mediaBox.width,mediaBox.height,cropBox.x,cropBox.y,cropBox.width,cropBox.height,rotation].every(Number.isFinite)||mediaBox.width<=0||mediaBox.height<=0||mediaBox.width>14400||mediaBox.height>14400||cropBox.width<=0||cropBox.height<=0||cropBox.width>14400||cropBox.height>14400||rotation%90!==0)throw Error('页面尺寸/旋转超出支持域');return{page:i+1,mediaBox,cropBox,rotation,hasAnnotations:p.node.has(PDFName.of('Annots'))};});sources.push({id:s.id,name:s.name,bytes:s.bytes.length,sha256:await sha(s.bytes),pages});docs.push({id:s.id,doc});}return{sources,docs};}
export function rowsFor(sources){let n=0;return sources.flatMap(s=>s.pages.map(p=>({id:'P'+String(++n).padStart(3,'0'),sourceId:s.id,page:p.page})));}
export function validatePlan(sources,raw){strict(raw,['rows','mode','groupSize']);if(!Array.isArray(sources)||!sources.length||!Array.isArray(raw.rows)||!raw.rows.length||raw.rows.length>80||!['merged','split'].includes(raw.mode)||!Number.isSafeInteger(raw.groupSize)||raw.groupSize<1||raw.groupSize>80)throw Error('选择1至80输出页及有效合并/分组方式');const ids=new Set(),files=new Map(sources.map(s=>[s.id,s]));for(const r of raw.rows){strict(r,['id','sourceId','page']);const source=files.get(r.sourceId);if(!/^P\d{3}$/.test(r.id)||ids.has(r.id)||!source||!Number.isSafeInteger(r.page)||r.page<1||r.page>source.pages.length)throw Error('页引用/稳定编号无效');ids.add(r.id);}const size=raw.mode==='merged'?raw.rows.length:raw.groupSize;return{...raw,rows:raw.rows.map(r=>({...r})),groups:Array.from({length:Math.ceil(raw.rows.length/size)},(_,i)=>raw.rows.slice(i*size,(i+1)*size))};}
export function move(rows,from,to){if(!Array.isArray(rows)||!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<0||from>=rows.length||to>=rows.length)throw Error('移动位置无效');const next=rows.map(r=>({...r})),[row]=next.splice(from,1);next.splice(to,0,row);return next;}
export async function build(rawSources,rawPlan){const loaded=await loadSources(rawSources),plan=validatePlan(loaded.sources,rawPlan),docs=new Map(loaded.docs.map(s=>[s.id,s.doc])),sources=new Map(loaded.sources.map(s=>[s.id,s])),files=[],pageMap=[];let total=0,globalPage=0;for(let i=0;i<plan.groups.length;i++){const output=await PDFDocument.create({updateMetadata:false}),name=plan.mode==='merged'?'assembled.pdf':'part-'+String(i+1).padStart(2,'0')+'.pdf';for(const row of plan.groups[i]){const [copied]=await output.copyPages(docs.get(row.sourceId),[row.page-1]);output.addPage(copied);const source=sources.get(row.sourceId),info=source.pages[row.page-1];pageMap.push({outputFile:name,outputPage:output.getPageCount(),globalOutputPage:++globalPage,rowId:row.id,sourceId:row.sourceId,sourceName:source.name,sourceSHA256:source.sha256,sourcePage:row.page,mediaBox:info.mediaBox,cropBox:info.cropBox,rotation:info.rotation,sourceHasAnnotations:info.hasAnnotations});}const bytes=await output.save({useObjectStreams:false,addDefaultPage:false});total+=bytes.length;if(bytes.length>(plan.mode==='merged'?10485760:2097152)||total>10485760)throw Error('完整PDF输出超过单文件/总量预算，未提供部分副本');files.push({name,bytes,sha256:await sha(bytes),pages:output.getPageCount()});}const report={format:'T021-pdf-page-assembly',version:1,sources:loaded.sources,plan:{rows:plan.rows,mode:plan.mode,groupSize:plan.groupSize},outputs:files.map(({name,bytes,sha256,pages})=>({name,bytes:bytes.length,sha256,pages})),pageMap,scope:'仅未加密、无AcroForm普通PDF页复制；保留页内容/尺寸/裁切/旋转。新文档不继承原文档级书签/签名/附件/元数据或承诺交互链接/批注目的地完整；不是脱敏或恶意内容清理。缩略图为有限视觉预览，源字节只读。'};reportText(report,'json');reportText(report,'md');return{files,report};}
export function reportText(r,ext){const json=JSON.stringify(r,null,2),tick=String.fromCharCode(96);let text;if(ext==='json')text=json+'\n';else if(ext==='md')text='# T021 PDF逐页来源\n\n'+tick.repeat(3)+'json\n'+json.replaceAll(tick,'\\u0060')+'\n'+tick.repeat(3)+'\n';else throw Error('仅JSON/Markdown');if(encoder.encode(text).length>1048576)throw Error('完整来源报告超过1MiB，不截断');return text;}
export function binaryFile(file){if(!(file.bytes instanceof Uint8Array)||file.bytes.length>10485760)throw Error('二进制容量超限');let text='';for(let i=0;i<file.bytes.length;i+=32768)text+=String.fromCharCode(...file.bytes.subarray(i,i+32768));return{path:file.name,base64:btoa(text),sha256:file.sha256};}
export async function bundle(result){const files=result.files.map(binaryFile);for(const ext of['json','md']){const bytes=encoder.encode(reportText(result.report,ext));files.push(binaryFile({name:'page-sources.'+ext,bytes,sha256:await sha(bytes)}));}if(files.length>100||files.some(f=>atob(f.base64).length>2097152)||files.reduce((n,f)=>n+atob(f.base64).length,0)>10485760)throw Error('完整拆分包连同来源报告超过2MiB每份/10MiB总量/100文件，不截断');return files;}
